import pathlib,json,hashlib,itertools,time,sqlite3
start=time.monotonic();out=pathlib.Path(__file__).parent
src=pathlib.Path('/tmp/erdos85-sol1-q9-n78-four-orbit-order24-parameters')
def guard():
    if time.monotonic()-start>30:
        (out/'audit.json').write_text(json.dumps({'status':'UNKNOWN','original_cap_seconds':30}))
        raise SystemExit('cap reached')
for name in ['pins.json','input-pins.json']:
    for f,h in json.loads((src/name).read_text()).items():
        p=pathlib.Path(f);p=p if p.is_absolute() else src/p
        assert hashlib.sha256(p.read_bytes()).hexdigest()==h
c=sqlite3.connect('file:/Users/rwalters/GitHub/lean-genius/.squad/squad.db?mode=ro',uri=True)
for rid in [2307,2319]:
    status,res=c.execute('select status,resolution from review_requests where id=?',(rid,)).fetchone()
    assert status=='resolved' and res.startswith('PASS')
groups=json.loads((src/'groups.json').read_text());records=json.loads((src/'results.json').read_text())['records']
ht=json.loads(pathlib.Path('/tmp/erdos85-sol1-q9-n78-kernel-four-abelian-cayley/parameters.json').read_text())['H_tables']
expected={}
for h in ht:
    m=h['multiplication']
    for chi in itertools.product((0,1),repeat=8):
        if all(chi[m[a][b]]==chi[a]^chi[b] for a in range(8) for b in range(8)):
            expected[h['name']+':'+''.join(map(str,chi))]=(m,chi)
assert set(expected)=={g['name'] for g in groups[:-2]} and len(groups)==24
def freeze(x):return tuple(freeze(a) for a in x) if isinstance(x,list) else x
def matchings(vertices):
    if not vertices:yield ();return
    a=vertices[0]
    for b in vertices[1:]:
        for rest in matchings([v for v in vertices if v not in (a,b)]):yield ((a,b),)+rest
all_matchings=list(matchings(list(range(6))))
report=[]
for gi,(g,rec) in enumerate(zip(groups,records)):
    guard();assert rec['group']==gi and rec['status']=='COMPLETE'
    m=g['multiplication'];inv=g['inverse'];elts=list(map(freeze,g['elements']));idx={v:i for i,v in enumerate(elts)}
    assert len(idx)==24 and m[0]==list(range(24))
    for i,x in enumerate(elts):
        for j,y in enumerate(elts):
            if g['name'] in expected:
                h,chi=expected[g['name']];a,u=x;b,v=y
                z=((a+(-1)**chi[u]*b)%3,h[u][v])
            elif g['name']=='S4':z=tuple(x[y[k]] for k in range(4))
            else:
                a,u=x;b,v=y;z=(tuple(a[b[k]] for k in range(4)),u^v)
            assert m[i][j]==idx[z]
        assert m[i][inv[i]]==m[inv[i]][i]==0
    io=sorted({tuple(sorted({x,inv[x]})) for x in range(1,24)})
    cubic=set()
    for length in [1,2,3]:
        for blocks in itertools.combinations(io,length):
            if sum(map(len,blocks))!=3:continue
            s=tuple(sorted(x for b in blocks for x in b))
            adj=[{m[a][x] for x in s} for a in range(24)]
            if all(len(adj[a]&adj[b])<=1 for a,b in itertools.combinations(range(24),2)):cubic.add(s)
    assert cubic=={tuple(s) for s in rec['cubic_sets']}
    if not cubic:
        assert not rec['actions'];report.append({'group':gi,'cubic':0,'actions':0});continue
    # Every group of order four is generated by at most two elements.
    hs=set()
    for a in range(24):
        for b in range(a,24):
            h={0,a,b}
            while len(h)<=4:
                nxt=h|{m[u][v] for u in h for v in h}
                if nxt==h:break
                h=nxt
            if len(h)==4:hs.add(tuple(sorted(h)))
    assert len(hs)==rec['subgroups4']
    expected_actions=set()
    for h in hs:
        guard();cosets=sorted({tuple(sorted(m[a][x] for x in h)) for a in range(24)},key=min)
        labels=[next(i for i,co in enumerate(cosets) if a in co) for a in range(24)]
        reps=[min(co) for co in cosets]
        action=[[labels[m[a][r]] for r in reps] for a in range(24)]
        for pairs in all_matchings:
            match=[0]*6
            for a,b in pairs:match[a]=b;match[b]=a
            if all(match[t[i]]==t[match[i]] for t in action for i in range(6)):
                expected_actions.add((h,tuple(match)))
        for row in rec['actions']:
            if tuple(row['H'])==h:
                assert row['labels']==labels and row['coset_representatives']==reps
                assert row['matching'][0]==row['partner']
    supplied={(tuple(row['H']),tuple(row['matching'])) for row in rec['actions']}
    assert supplied==expected_actions and len(supplied)==len(rec['actions'])
    report.append({'group':gi,'cubic':len(cubic),'actions':len(supplied),'subgroups4':len(hs)})
result={'status':'COMPLETE','original_cap_seconds':30,'seconds':time.monotonic()-start,'groups':24,'cubic_sets':sum(r['cubic'] for r in report),'actions':sum(r['actions'] for r in report),'records':report}
(out/'audit.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items() if k!='records'}))
