#!/usr/bin/env python3
"""Exact cyclic-component-action lift model for q=9 order-20x4 shadows.

After coordinate changes, a preimage of the block 4-cycle acts by shifting
the four blocks and applying one closing twist alpha in Aut(C).  A lift is
generated by the 20 lines on blocks 012, hence by two permutations f,g of
the component vertices.  Invariance under the fourth power forces f and g
to commute with alpha.  The remaining line classes are their three rotated
images.  This model enforces those equations plus linearity, the intrinsic
shadow condition, and C4-freeness.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from itertools import combinations
from pathlib import Path

import networkx as nx
import z3

EXPECTED_SHA256 = "4bac89beec1465265318266117c38a2c1680e73a21efd322411207cef5313088"
ORDINALS = (4, 6, 7)


def component(raw: bytes, wanted: int) -> nx.Graph:
    ordinal = 0
    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            graph = nx.from_graph6_bytes(line.strip())
        except nx.NetworkXError:
            graph = nx.from_sparse6_bytes(line.strip())
        if len(graph) != 20:
            continue
        ordinal += 1
        if ordinal == wanted:
            return nx.convert_node_labels_to_integers(graph)
    raise AssertionError(f"missing order-20 ordinal {wanted}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("census", type=Path)
    parser.add_argument("--ordinal", type=int, choices=ORDINALS, required=True)
    parser.add_argument("--twist-class", type=int)
    parser.add_argument("--list-classes", action="store_true")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--timeout", type=int, default=300)
    args = parser.parse_args()
    raw = args.census.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == EXPECTED_SHA256
    base = component(raw, args.ordinal)
    automorphisms = sorted(
        tuple(mapping[v] for v in range(20))
        for mapping in nx.algorithms.isomorphism.GraphMatcher(base, base).isomorphisms_iter()
    )

    def compose(left, right):
        return tuple(left[right[v]] for v in range(20))

    def inverse(permutation):
        result = [0] * 20
        for source, target in enumerate(permutation):
            result[target] = source
        return tuple(result)

    unseen = set(automorphisms)
    classes = []
    while unseen:
        representative = min(unseen)
        conjugates = {
            compose(compose(element, representative), inverse(element))
            for element in automorphisms
        }
        unseen -= conjugates
        classes.append((representative, len(conjugates)))
    classes.sort()
    if args.list_classes:
        print(
            f"ordinal={args.ordinal}",
            f"automorphism_order={len(automorphisms)}",
            f"twist_class_sizes={[size for _, size in classes]}",
        )
        return
    if args.all:
        if args.twist_class is not None:
            raise SystemExit("--all and --twist-class are mutually exclusive")
        for class_index in range(len(classes)):
            process = subprocess.run(
                [
                    sys.executable,
                    str(Path(__file__).resolve()),
                    str(args.census),
                    "--ordinal", str(args.ordinal),
                    "--twist-class", str(class_index),
                    "--timeout", str(args.timeout),
                ],
                text=True,
                capture_output=True,
            )
            if process.returncode != 0 or "result=unsat" not in process.stdout:
                sys.stdout.write(process.stdout)
                sys.stderr.write(process.stderr)
                raise RuntimeError(f"incomplete twist class {class_index}")
            print(f"completed_twist_class={class_index}", flush=True)
        print(f"excluded_c4_action ordinal={args.ordinal} twist_classes={len(classes)}")
        return
    if args.twist_class is None or not 0 <= args.twist_class < len(classes):
        raise SystemExit(f"--twist-class must be in [0,{len(classes)})")
    alpha, class_size = classes[args.twist_class]
    alpha_inverse = inverse(alpha)

    solver = z3.Solver()
    f = [[z3.Bool(f"f_{x}_{y}") for y in range(20)] for x in range(20)]
    g = [[z3.Bool(f"g_{x}_{y}") for y in range(20)] for x in range(20)]
    for matrix in (f, g):
        for row in matrix:
            solver.add(z3.PbEq([(entry, 1) for entry in row], 1))
        for y in range(20):
            solver.add(z3.PbEq([(matrix[x][y], 1) for x in range(20)], 1))
        for x in range(20):
            for y in range(20):
                solver.add(matrix[alpha[x]][alpha[y]] == matrix[x][y])

    contribution = {}

    def put(triple, pair, left, right, value):
        contribution[triple, pair, left, right] = value

    for x in range(20):
        for y in range(20):
            # 012 and its first rotation 123.
            put((0, 1, 2), (0, 1), x, y, f[x][y])
            put((0, 1, 2), (0, 2), x, y, g[x][y])
            put((1, 2, 3), (1, 2), x, y, f[x][y])
            put((1, 2, 3), (1, 3), x, y, g[x][y])
            # Second rotation: (alpha(g(t)), t, f(t)) on blocks 0,2,3.
            put((0, 2, 3), (0, 2), x, y, g[y][alpha_inverse[x]])
            put((0, 2, 3), (2, 3), x, y, f[x][y])
            # Third rotation: (alpha(f(t)), alpha(g(t)), t) on 0,1,3.
            put((0, 1, 3), (0, 3), x, y, f[y][alpha_inverse[x]])
            put((0, 1, 3), (1, 3), x, y, g[y][alpha_inverse[x]])

    for left in range(20):
        for right in range(20):
            put(
                (0, 1, 2), (1, 2), left, right,
                z3.Or(*[z3.And(f[x][left], g[x][right]) for x in range(20)]),
            )
            put(
                (1, 2, 3), (2, 3), left, right,
                z3.Or(*[z3.And(f[x][left], g[x][right]) for x in range(20)]),
            )
            put(
                (0, 2, 3), (0, 3), left, right,
                z3.Or(*[
                    z3.And(g[x][alpha_inverse[left]], f[x][right])
                    for x in range(20)
                ]),
            )
            put(
                (0, 1, 3), (0, 1), left, right,
                z3.Or(*[
                    z3.And(f[x][alpha_inverse[left]], g[x][alpha_inverse[right]])
                    for x in range(20)
                ]),
            )

    edge = {}
    triples = tuple(combinations(range(4), 3))
    for block_pair in combinations(range(4), 2):
        support = [triple for triple in triples if set(block_pair) <= set(triple)]
        for left in range(20):
            for right in range(20):
                terms = [contribution[t, block_pair, left, right] for t in support]
                solver.add(z3.PbLe([(term, 1) for term in terms], 1))
                value = z3.Bool(f"edge_{block_pair[0]}_{left}_{block_pair[1]}_{right}")
                solver.add(value == z3.Or(*terms))
                edge[block_pair, left, right] = value

    def adjacency(left, right):
        lb, lx = divmod(left, 20)
        rb, rx = divmod(right, 20)
        if lb == rb:
            return z3.BoolVal(base.has_edge(lx, rx))
        if lb > rb:
            lb, rb, lx, rx = rb, lb, rx, lx
        return edge[(lb, rb), lx, rx]

    for left, right in combinations(range(80), 2):
        terms = []
        for center in range(80):
            if center in (left, right):
                continue
            one, two = adjacency(left, center), adjacency(right, center)
            if not z3.is_false(one) and not z3.is_false(two):
                terms.append(z3.And(one, two))
        shadow_edge = left // 20 == right // 20 and base.has_edge(left % 20, right % 20)
        solver.add(z3.PbLe([(term, 1) for term in terms], 0 if shadow_edge else 1))

    print(
        f"ordinal={args.ordinal}",
        f"twist_class={args.twist_class}",
        f"class_size={class_size}",
        f"assertions={len(solver.assertions())}",
        flush=True,
    )
    goal = z3.Goal()
    goal.add(*solver.assertions())
    cnf = z3.Then("simplify", "card2bv", "tseitin-cnf")(goal)
    assert len(cnf) == 1
    process = subprocess.run(
        ["kissat", "--quiet", f"--time={args.timeout}"],
        input=cnf[0].dimacs(), text=True, capture_output=True,
    )
    result = {10: "sat", 20: "unsat"}.get(process.returncode, "unknown")
    print(f"result={result}")


if __name__ == "__main__":
    main()
