# Emit a Lean module embedding one renumbered LRAT proof as an
# Array Std.Tactic.BVDecide.LRAT.IntAction literal.
# Renumbering mirrors Erdos85.LratRenumber exactly:
#   firstDerived = numOriginalClauses + 1; every addition gets the next
#   sequential id starting at firstDerived; ids < firstDerived pass through;
#   derived hint/deletion ids are looked up in the mapping.
import sys, hashlib
lrat_path, num_orig, defname, out_path = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
first = num_orig + 1
mapping = {}
next_id = first
def mid(i):
    if i < first: return i
    return mapping[i]
actions = []
raw = open(lrat_path).read()
for line in raw.splitlines():
    toks = line.split()
    if not toks: continue
    if len(toks) >= 2 and toks[1] == 'd':
        ids = [mid(int(x)) for x in toks[2:-1]]
        assert toks[-1] == '0'
        actions.append(('del', ids))
        continue
    oid = int(toks[0])
    rest = [int(x) for x in toks[1:]]
    z1 = rest.index(0)
    lits = rest[:z1]
    hints_raw = rest[z1+1:-1]
    assert rest[-1] == 0
    if any(h < 0 for h in hints_raw):
        # RAT: pivot = first literal; rup prefix until first negative;
        # then groups (−clauseId, hints...) — mirror Std parser semantics
        k = 0
        rup = []
        while k < len(hints_raw) and hints_raw[k] > 0:
            rup.append(mid(hints_raw[k])); k += 1
        groups = []
        while k < len(hints_raw):
            assert hints_raw[k] < 0
            cid = mid(-hints_raw[k]); k += 1
            hs = []
            while k < len(hints_raw) and hints_raw[k] > 0:
                hs.append(mid(hints_raw[k])); k += 1
            groups.append((cid, hs))
        mapping[oid] = next_id
        actions.append(('rat', next_id, lits, lits[0], rup, groups))
        next_id += 1
    else:
        hints = [mid(h) for h in hints_raw]
        mapping[oid] = next_id
        if lits:
            actions.append(('rup', next_id, lits, hints))
        else:
            actions.append(('empty', next_id, hints))
        next_id += 1
def arr(xs): return "#[" + ", ".join(map(str, xs)) + "]"
lines = []
lines.append("import Std.Tactic.BVDecide")
lines.append("")
lines.append(f"/- GENERATED by emit_lrat_lean.py from {lrat_path.split('/')[-1]}")
lines.append(f"   source SHA256: {hashlib.sha256(raw.encode()).hexdigest()}")
lines.append(f"   renumbered against numOriginalClauses = {num_orig} (firstDerived {first}).")
lines.append("   Semantics-preserving renumbering identical to Erdos85.LratRenumber. -/")
lines.append("")
lines.append("set_option maxRecDepth 2000000 in")
lines.append("namespace Erdos85")
lines.append("")
lines.append(f"def {defname} : Array Std.Tactic.BVDecide.LRAT.IntAction := #[")
body = []
for a in actions:
    if a[0] == 'del':
        body.append(f"  .del {arr(a[1])}")
    elif a[0] == 'rup':
        body.append(f"  .addRup {a[1]} {arr(a[2])} {arr(a[3])}")
    elif a[0] == 'empty':
        body.append(f"  .addEmpty {a[1]} {arr(a[2])}")
    else:
        _, nid, lits, pivot, rup, groups = a
        gs = "#[" + ", ".join(f"({c}, {arr(h)})" for c, h in groups) + "]"
        body.append(f"  .addRat {nid} {arr(lits)} {pivot} {arr(rup)} {gs}")
lines.append(",\n".join(body))
lines.append("]")
lines.append("")
lines.append("end Erdos85")
open(out_path, "w").write("\n".join(lines) + "\n")
import os
print(f"{defname}: {len(actions)} actions ({sum(1 for a in actions if a[0]=='rat')} RAT), "
      f"out {os.path.getsize(out_path)/1048576:.1f} MB")
