#!/usr/bin/env python3
"""Produce verified compact LRATs for the 122 refinement-pin formulas.

The input pair is emitted by ``erdos85_one_high_odd_profile_refinements.py``
using ``--slot-output`` and ``--slot-manifest``.  Every job is independently
regenerated by Lean's ``refinementcnf`` executable, clausewise self-checked,
solved with proof logging, checked by drat-trim and lrat-check, then compacted
to the format consumed by the repository's Lean LRAT runtime.
"""

from __future__ import annotations

import argparse
import concurrent.futures as futures
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import time


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def clause_count(path: Path) -> int:
    with path.open() as stream:
        for line in stream:
            if line.startswith("p cnf "):
                return int(line.split()[3])
    raise ValueError(f"missing DIMACS header: {path}")


def checked_tool(path: Path, description: str) -> Path:
    path = path.resolve()
    if not path.is_file():
        raise FileNotFoundError(f"missing {description}: {path}")
    return path


def accepted(manifest: Path) -> bool:
    if not manifest.is_file():
        return False
    try:
        data = json.loads(manifest.read_text())
    except (OSError, json.JSONDecodeError):
        return False
    compact = manifest.with_name(
        manifest.name.removesuffix(".manifest.json") + ".compact.lrat")
    return (data.get("state") == "LEAN_ACCEPTED" and
            data.get("drat_trim") == "s VERIFIED" and
            data.get("lrat_check") == "c VERIFIED" and
            data.get("lean_replay") == "LRAT accepted: true" and
            compact.is_file() and
            compact.stat().st_size == data.get("compact_bytes") and
            sha256(compact) == data.get("compact_lrat_sha256"))


def run_job(job) -> tuple[str, str]:
    index, refinement, metadata, args = job
    profile = int(metadata["profile"])
    tag = (f"p{profile}-r{int(metadata['refinement_index']):03d}-"
           f"s{int(metadata['slot_index']):02d}-"
           f"{metadata['table_tag']}")
    root = args.outdir / tag
    result = root.with_suffix(".manifest.json")
    if accepted(result):
        return tag, "SKIP"

    refinement_path = root.with_suffix(".refinement.json")
    cnf = root.with_suffix(".cnf")
    drat = root.with_suffix(".drat")
    raw_lrat = root.with_suffix(".raw.lrat")
    compact = root.with_suffix(".compact.lrat")
    solve_log = root.with_suffix(".kissat.log")
    trim_log = root.with_suffix(".drat-trim.log")
    check_log = root.with_suffix(".lrat-check.log")
    replay_log = root.with_suffix(".lean-replay.log")
    for partial in (cnf, drat, raw_lrat, compact, solve_log, trim_log,
                    check_log, replay_log):
        partial.unlink(missing_ok=True)
    refinement_path.write_text(json.dumps(refinement, separators=(",", ":")))

    with cnf.open("wb") as output:
        emitted = subprocess.run(
            [str(args.emitter), "emit", str(profile), str(refinement_path)],
            stdout=output, stderr=subprocess.PIPE, timeout=args.emit_timeout)
    if emitted.returncode or not cnf.is_file() or not cnf.stat().st_size:
        raise RuntimeError(f"{tag}: Lean CNF emission failed: {emitted.stderr!r}")
    checked = subprocess.run(
        [str(args.emitter), "check", str(profile), str(refinement_path),
         str(cnf)], capture_output=True, text=True, timeout=args.emit_timeout)
    if checked.returncode or "MATCH" not in checked.stdout:
        raise RuntimeError(f"{tag}: Lean CNF self-check failed: {checked.stdout}")

    started = time.monotonic()
    with solve_log.open("w") as output:
        solved = subprocess.run(
            [str(args.kissat), "-f", "--no-binary", "--no-factor",
             "--no-preprocessfactor", str(cnf), str(drat)],
            stdout=output, stderr=subprocess.STDOUT, timeout=args.solve_timeout)
    solve_seconds = time.monotonic() - started
    if solved.returncode != 20 or not drat.is_file():
        raise RuntimeError(f"{tag}: Kissat did not produce UNSAT DRAT "
                           f"(exit {solved.returncode})")

    trimmed = subprocess.run(
        [str(args.drat_trim), str(cnf), str(drat), "-L", str(raw_lrat)],
        capture_output=True, text=True, timeout=args.trim_timeout)
    trim_log.write_text(trimmed.stdout + trimmed.stderr)
    if trimmed.returncode or "s VERIFIED" not in trimmed.stdout:
        raise RuntimeError(f"{tag}: drat-trim rejected proof")

    checked_lrat = subprocess.run(
        [str(args.lrat_check), str(cnf), str(raw_lrat)],
        capture_output=True, text=True, timeout=args.check_timeout)
    check_log.write_text(checked_lrat.stdout + checked_lrat.stderr)
    verdicts = [line for line in checked_lrat.stdout.splitlines()
                if "VERIFIED" in line]
    if (checked_lrat.returncode or not verdicts or
            "NOT VERIFIED" in verdicts[-1]):
        raise RuntimeError(f"{tag}: lrat-check rejected proof")

    compacted = subprocess.run(
        [sys.executable, str(args.compactor), str(raw_lrat),
         str(clause_count(cnf)), str(compact)],
        capture_output=True, text=True, timeout=args.compact_timeout)
    if compacted.returncode or not compact.is_file():
        raise RuntimeError(f"{tag}: LRAT compaction failed: "
                           f"{compacted.stdout} {compacted.stderr}")

    replayed = subprocess.run(
        [str(args.lrat_replay), str(cnf), str(compact)],
        capture_output=True, text=True, timeout=args.replay_timeout)
    replay_log.write_text(replayed.stdout + replayed.stderr)
    if replayed.returncode or "LRAT accepted: true" not in replayed.stdout:
        raise RuntimeError(f"{tag}: Lean compact LRAT replay failed")

    record = dict(metadata)
    record.update({
        "tag": tag,
        "state": "LEAN_ACCEPTED",
        "lean_exact": checked.stdout.strip(),
        "solve_seconds": round(solve_seconds, 3),
        "drat_trim": "s VERIFIED",
        "lrat_check": "c VERIFIED",
        "lean_replay": "LRAT accepted: true",
        "cnf_clauses": clause_count(cnf),
        "cnf_sha256": sha256(cnf),
        "drat_sha256": sha256(drat),
        "raw_lrat_sha256": sha256(raw_lrat),
        "compact_lrat_sha256": sha256(compact),
        "compact_bytes": compact.stat().st_size,
    })
    result.write_text(json.dumps(record, sort_keys=True, indent=2) + "\n")
    if not args.keep_intermediates:
        for partial in (cnf, drat, raw_lrat):
            partial.unlink(missing_ok=True)
    return tag, "LEAN_ACCEPTED"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("variants", type=Path)
    parser.add_argument("slot_manifest", type=Path)
    parser.add_argument("outdir", type=Path)
    parser.add_argument("--emitter", type=Path, required=True)
    parser.add_argument("--drat-trim", type=Path, required=True)
    parser.add_argument("--lrat-check", type=Path, required=True)
    parser.add_argument("--compactor", type=Path, required=True)
    parser.add_argument("--lrat-replay", type=Path, required=True)
    parser.add_argument("--kissat", type=Path, default=Path("/opt/homebrew/bin/kissat"))
    parser.add_argument("--workers", type=int, default=2)
    parser.add_argument("--limit", type=int)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--keep-intermediates", action="store_true")
    parser.add_argument("--emit-timeout", type=int, default=900)
    parser.add_argument("--solve-timeout", type=int, default=3600)
    parser.add_argument("--trim-timeout", type=int, default=7200)
    parser.add_argument("--check-timeout", type=int, default=3600)
    parser.add_argument("--compact-timeout", type=int, default=3600)
    parser.add_argument("--replay-timeout", type=int, default=1800)
    args = parser.parse_args()
    if args.workers < 1:
        parser.error("--workers must be positive")
    if args.limit is not None and args.limit < 1:
        parser.error("--limit must be positive")
    args.emitter = checked_tool(args.emitter, "Lean refinement emitter")
    args.drat_trim = checked_tool(args.drat_trim, "drat-trim")
    args.lrat_check = checked_tool(args.lrat_check, "lrat-check")
    args.compactor = checked_tool(args.compactor, "LRAT compactor")
    args.lrat_replay = checked_tool(args.lrat_replay, "Lean LRAT replay")
    args.kissat = checked_tool(args.kissat, "Kissat")

    variants = json.loads(args.variants.read_text())
    metadata = [json.loads(line) for line in
                args.slot_manifest.read_text().splitlines() if line.strip()]
    if len(variants) != len(metadata):
        raise ValueError("variant and manifest counts differ")
    if len(variants) != 122:
        raise ValueError(f"expected 122 canonical-slot variants, got {len(variants)}")
    jobs = [(index, refinement, metadata[index], args)
            for index, refinement in enumerate(variants)]
    if args.limit is not None:
        jobs = jobs[:args.limit]
    args.outdir.mkdir(parents=True, exist_ok=True)
    pending = sum(not accepted(
        args.outdir /
        (f"p{int(meta['profile'])}-r{int(meta['refinement_index']):03d}-"
         f"s{int(meta['slot_index']):02d}-{meta['table_tag']}.manifest.json"))
        for _, _, meta, _ in jobs)
    print(f"jobs={len(jobs)} pending={pending} workers={args.workers}", flush=True)
    if args.dry_run:
        return
    with futures.ThreadPoolExecutor(max_workers=args.workers) as executor:
        for tag, state in executor.map(run_job, jobs):
            print(f"{tag}\t{state}", flush=True)


if __name__ == "__main__":
    main()
