/**
 * Research Data Index
 *
 * Exports:
 * - researchListings: Lightweight metadata for ResearchPage gallery (small bundle, in-graph)
 * - getResearchProblemAsync: Fetch full problem data by slug from the static asset tree
 *
 * Phase 3 of the build-perf durable fix (issue #20994, follow-up to phase 1
 * issue #20992 and phase 2 issue #20993). Previously this module used a
 * dynamic-template `import(`./problems/${slug}.json`)` glob to discover ~2074
 * per-problem JSON files, each of which Vite/Rollup pulled into the module
 * graph. That O(N) blowup mirrored the per-proof shim explosion that phase 2
 * cured. Phase 3 collapses all of that to:
 *   - this file (a thin fetch-by-slug loader)
 *   - research-listings.json (single small module, eagerly needed by
 *     ResearchPage — kept in-graph per acceptance criterion)
 *   - research-data-manifest.json (single small module mapping slug -> sha8
 *     hash for cache-busting; the manifest IS bundled with content hashing so
 *     any problem change busts the importing chunk)
 * All per-problem JSONs now live under public/data/research/<slug>.json
 * (gitignored, build-generated) and are fetched at runtime.
 *
 * The committed source-of-truth JSONs in `src/data/research/problems/` remain
 * the canonical inputs to `scripts/research/build.ts`; this file no longer
 * touches them.
 */

import type { ResearchListing, ResearchProblem } from '@/types/research'

// Import listings - generated by build script.
// This import will fail if build hasn't run yet.
import listingsData from './research-listings.json'
import dataManifest from './research-data-manifest.json'

// Lightweight listings for ResearchPage - does not pull in full problem data.
// Ensure tags always exists (defensive - build.ts should provide it).
export const researchListings: ResearchListing[] = (listingsData as ResearchListing[]).map(l => ({
  ...l,
  tags: l.tags ?? [],
}))

const DATA_MANIFEST: Record<string, string> = dataManifest as Record<string, string>

/**
 * Asynchronously load research problem data for a given slug.
 *
 * Public signature preserved: `(slug) => Promise<ResearchProblem | undefined>`.
 * The only real consumer is `src/pages/ResearchProblemPage.tsx`; no change
 * needed there.
 *
 * The loader uses the in-graph data-manifest to know (a) which slugs exist and
 * (b) the sha8 cache-buster hash for each file. A missing slug or failed fetch
 * returns undefined rather than throwing, matching the previous contract.
 */
export async function getResearchProblemAsync(slug: string): Promise<ResearchProblem | undefined> {
  const v = DATA_MANIFEST[slug]
  if (!v) return undefined

  try {
    const resp = await fetch(`/data/research/${slug}.json?v=${v}`)
    if (!resp.ok) return undefined
    return (await resp.json()) as ResearchProblem
  } catch (e) {
    console.error(`Failed to load research problem: ${slug}`, e)
    return undefined
  }
}

/**
 * Get all research listings synchronously.
 * Use this for the gallery page.
 */
export function getResearchListings(): ResearchListing[] {
  return researchListings
}
