import Proofs.CycleDoubleCoverPort.NashWilliams2
open CycleDoubleCover.FiniteGraph
#print axioms CycleDoubleCover.FiniteGraph.mem_class_of_supportGraph_insideEdges_adj
#print axioms CycleDoubleCover.FiniteGraph.inside_induce_connected
#print axioms CycleDoubleCover.FiniteGraph.quotientGraph_adj_of_mem_crossingClass
#print axioms CycleDoubleCover.FiniteGraph.quotient_reachable_of_supportGraph_adj
#print axioms CycleDoubleCover.FiniteGraph.quotientGraph_connected_of_connects
#print axioms CycleDoubleCover.FiniteGraph.reachableIn_of_rel_of_internal
#print axioms CycleDoubleCover.FiniteGraph.insideEdges_subset_erase_of_crossing
#print axioms CycleDoubleCover.FiniteGraph.reachableIn_out_of_quotient_reachable
#print axioms CycleDoubleCover.FiniteGraph.connects_of_internal_of_quotient_connects
#print axioms CycleDoubleCover.FiniteGraph.cyclicEdge_of_quotient_cyclic_of_internal
#print axioms CycleDoubleCover.FiniteGraph.reachableIn_erase_of_cyclic
#print axioms CycleDoubleCover.FiniteGraph.componentSetoid_erase_eq_of_cyclic
#print axioms CycleDoubleCover.FiniteGraph.component_card_lt_of_not_cyclic
#print axioms CycleDoubleCover.FiniteGraph.card_add_components_le_of_no_cyclic
#print axioms CycleDoubleCover.FiniteGraph.exists_cyclic_of_disconnected_of_card_ge
#print axioms CycleDoubleCover.FiniteGraph.connects_erase_of_cyclic
#print axioms CycleDoubleCover.FiniteGraph.exists_isSpanningTree_subset_of_connects
#print axioms CycleDoubleCover.FiniteGraph.supportGraph_isTree_of_spanningTree
#print axioms CycleDoubleCover.FiniteGraph.symEdge_injOn_of_spanningTree
