/-
  Primitive Solvable Permutation Groups of Prime Degree — Galois Direction
  (sub-OQ-06)

  This file scaffolds the **Galois direction** of the AGL(1, p) classification:
  every primitive solvable subgroup `H ≤ S_p` embeds into the affine group
  `AGL(1, p) = ℤ/pℤ ⋊ (ℤ/pℤ)ˣ`. The forward direction (that AGL(1, p)
  itself is solvable, primitive, faithful, and of order p(p-1)) is supplied
  by the parent file `Proofs.AbelRuffiniGaloisExtensionsOQ06` (530 LOC,
  0 sorries, 0 axioms, Docker-verified by parent S7 ACT PR #19071).

  ## S2 ORIENT status (researcher-1, 2026-06-04)

  This iteration is the S2 ORIENT scaffold: file-level theorem stub plus
  the 5-step proof skeleton (Sylow uniqueness → P normal → P is p-cycle
  → N_{S_p}(P) ≅ AGL(1, p) → H ≤ N_{S_p}(P)), each step exposed as its
  own intermediate lemma stub with `sorry`. Discharge of the stubs is
  deferred to S3-S6 ACT iterations per `research/problems/.../state.md`.

  ## Mathlib bearer audit (S1 OBSERVE, re-verified at lake-pinned SHA
  `2df2f0150c275ad53cb3c90f7c98ec15a56a1a67`)

  - `Sylow.exists` (existence of Sylow-p in a finite group).
  - `Sylow.normal_of_subsingleton` (`Mathlib/GroupTheory/Sylow.lean:724`).
  - `Equiv.Perm.isCycle_of_prime_order''`
    (`Mathlib/GroupTheory/Perm/Cycle/Type.lean:412`).
  - `Subgroup.normalizer` (`Mathlib/GroupTheory/Subgroup/Basic.lean`).
  - `MonoidHom.ofInjective` (`Mathlib/Algebra/Group/Hom/Basic.lean`).
  - Parent `AGL1Z`, `AGL1Z.toPerm`, `AGL1Z.toPerm_injective`
    (`proofs/Proofs/AbelRuffiniGaloisExtensionsOQ06.lean`).
-/

import Proofs.AbelRuffiniGaloisExtensionsOQ06
import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.Perm.Cycle.Type

namespace AbelRuffiniGaloisExtensionsOQ06GaloisDirection

open AbelRuffiniGaloisExtensionsOQ06

variable {p : ℕ} [Fact p.Prime]

/-- **Step 1 (Sylow uniqueness).** Inside a primitive solvable
    subgroup `H ≤ S_p`, the Sylow-p subgroup of `H` is unique.

    Mathematical content: a primitive permutation group on a prime-card
    set has order divisible by `p` and not by `p²` (since `|H| ∣ p!`),
    so by Sylow's third theorem the number of Sylow-p subgroups divides
    `|H|/p < p` and is `≡ 1 (mod p)`, forcing uniqueness. -/
theorem sylow_p_unique
    (H : Subgroup (Equiv.Perm (ZMod p)))
    (_hPrim : MulAction.IsPreprimitive H (ZMod p))
    (_hSolv : IsSolvable H) :
    Subsingleton (Sylow p H) := by
  sorry

/-- **Step 2 (Normal Sylow).** The unique Sylow-p subgroup `P` of `H`
    is normal in `H` (any unique Sylow is normal). -/
theorem sylow_p_normal
    (H : Subgroup (Equiv.Perm (ZMod p)))
    (_hPrim : MulAction.IsPreprimitive H (ZMod p))
    (_hSolv : IsSolvable H)
    (P : Sylow p H) :
    (P : Subgroup H).Normal := by
  sorry

/-- **Step 3 (p-cycle structure).** The Sylow-p subgroup `P` is
    generated by a `p`-cycle in `S_p`. Bearer:
    `Equiv.Perm.isCycle_of_prime_order''` specialized to prime degree. -/
theorem sylow_p_is_pcycle
    (H : Subgroup (Equiv.Perm (ZMod p)))
    (_hPrim : MulAction.IsPreprimitive H (ZMod p))
    (_hSolv : IsSolvable H)
    (P : Sylow p H) :
    ∃ σ : Equiv.Perm (ZMod p), σ.IsCycle ∧ σ.support.card = p ∧
      ∀ g : P, (H.subtype.comp (P : Subgroup H).subtype) g ∈
        Subgroup.zpowers σ := by
  sorry

/-- **Step 4 (Normalizer ≅ AGL(1, p)).** The normalizer of any
    Sylow-p subgroup of `S_p` (generated by a `p`-cycle) is isomorphic
    to `AGL(1, p)` via the conjugation action of `(ℤ/pℤ)ˣ` on `ℤ/pℤ`.

    The isomorphism `N_{S_p}(P) ≅ AGL1Z p` factors through the parent
    file's `AGL1Z.toPerm : AGL1Z p →* Equiv.Perm (ZMod p)`. -/
theorem normalizer_iso_AGL1Z
    (σ : Equiv.Perm (ZMod p)) (_hσ : σ.IsCycle) (_hσ_card : σ.support.card = p) :
    ∃ φ : (Subgroup.zpowers σ).normalizer →* AGL1Z p,
      Function.Injective φ ∧ Function.Surjective φ := by
  sorry

/-- **Step 5 (H ≤ N_{S_p}(P)).** Since the Sylow-p subgroup `P` is
    normal in `H`, the group `H` is contained in the normalizer of `P`
    in `S_p`. Composition with the step-4 isomorphism gives the desired
    embedding `H ↪ AGL(1, p)`. -/
theorem H_le_normalizer
    (H : Subgroup (Equiv.Perm (ZMod p)))
    (_hPrim : MulAction.IsPreprimitive H (ZMod p))
    (_hSolv : IsSolvable H)
    (σ : Equiv.Perm (ZMod p))
    (_hσ_in_H : σ ∈ H) :
    H ≤ (Subgroup.zpowers σ).normalizer := by
  sorry

/-- **Main theorem (file-level stub).** Every primitive solvable subgroup
    of `S_p = Equiv.Perm (ZMod p)` embeds into `AGL(1, p)`.

    Discharge plan: compose
    `sylow_p_unique` → `sylow_p_normal` → `sylow_p_is_pcycle` →
    `normalizer_iso_AGL1Z` → `H_le_normalizer`. See `problem.md` §"Proof
    plan" for the classical (Galois 1832 / Rotman 9.11) recipe. -/
theorem primitive_solvable_subgroup_embeds_AGL1Z
    (H : Subgroup (Equiv.Perm (ZMod p)))
    (_hPrim : MulAction.IsPreprimitive H (ZMod p))
    (_hSolv : IsSolvable H) :
    ∃ φ : H →* AGL1Z p, Function.Injective φ := by
  sorry

end AbelRuffiniGaloisExtensionsOQ06GaloisDirection
