/-
  Aristotle companion for Step 4 of the Galois-direction structure theorem
  (`abel-ruffini-galois-extensions-oq-06-galois-direction`).

  Target: `normalizer_iso_AGL1Z` — the ONLY remaining `sorry` in the registered
  `AbelRuffiniGaloisExtensionsOQ06GaloisDirection.lean` (line 471). Every other
  step (1, 2, 3, 5, and the file-level composition) is already `sorry`-free on
  `main`, so discharging this one lemma completes the whole theorem
  `primitive_solvable_subgroup_embeds_AGL1Z`.

  A hand-drafted, `sorry`-free proof exists in the orphan
  `AbelRuffiniGaloisExtensionsOQ06GaloisDirectionStep4.lean` (via
  `normalizer_eq_range` + conjugation transport) but is build-pending under a
  contended local Docker gate. This companion submits the same obligation to
  Aristotle for an independent remote proof.

  Mathematical content. For `σ` a `p`-cycle in `S_p`, the normalizer
  `N_{S_p}(⟨σ⟩)` is isomorphic to `AGL(1,p)` via the affine action: every
  `h` normalising `⟨σ⟩` satisfies a functional equation `h(σ x) = σ^k (h x)`
  with `k ∈ (ℤ/pℤ)ˣ`, forcing `h` affine; the map `h ↦ (h(0), k)` is the iso.
  The injective + surjective halves are numerically certified for p ∈ {3,5,7} in
  `verify_step4_normalizer.py`.

  Imports the registered file so the parent `AGL1Z` and all proven Step-1..3/5
  helper lemmas (e.g. `centralizer_pcycle_eq_zpowers`) are in scope.
-/
import Mathlib
import Proofs.AbelRuffiniGaloisExtensionsOQ06GaloisDirection

open AbelRuffiniGaloisExtensionsOQ06
open AbelRuffiniGaloisExtensionsOQ06GaloisDirection

namespace AbelRuffiniGaloisExtensionsOQ06GaloisDirectionStep4Aristotle

variable {p : ℕ} [Fact p.Prime]

/-- **Step 4 (Normalizer ≅ AGL(1, p)).** The normalizer of the cyclic group
    generated by a `p`-cycle `σ` in `S_p` embeds isomorphically into `AGL(1,p)`
    (injective and surjective hom). Companion restatement of the registered
    `normalizer_iso_AGL1Z` for Aristotle. -/
theorem normalizer_iso_AGL1Z_companion
    (σ : Equiv.Perm (ZMod p)) (hσ : σ.IsCycle) (hσ_card : σ.support.card = p) :
    ∃ φ : (Subgroup.zpowers σ).normalizer →* AGL1Z p,
      Function.Injective φ ∧ Function.Surjective φ := by
  sorry

end AbelRuffiniGaloisExtensionsOQ06GaloisDirectionStep4Aristotle
