import Mathlib

/-
# Abel–Ruffini OQ04·OQ01·OQ03·OQ01 — the conjugation-action homomorphism `G ⧸ C_G(c) ↪ (ZMod p)ˣ`

The sibling file `AbelRuffiniOQ04OQ01OQ03.lean` proves that in a finite group `G`
of order `p·m` (`p` prime, `p ∤ m`, no small Frobenius divisor of `m`) the cyclic
subgroup `⟨c⟩ = zpowers c` generated by an order-`p` element is **normal**, and that
an *involution* conjugates `c` to `c^{±1}` (`involution_conj_eq_self_or_inv`).

That involution `±1` lemma is the shadow of a much sharper structural fact, flagged
as the OQ04·OQ01·OQ03·OQ01 follow-up: the conjugation action of `G` on the normal
cyclic group `⟨c⟩` assembles into a *group homomorphism*

>   `Φ : G →* (ZMod p)ˣ`,   `g ↦ (the exponent k with g c g⁻¹ = c^k)`,

whose **kernel is the centralizer `C_G(c)`** and whose codomain `(ZMod p)ˣ` is cyclic
of order `p - 1`.  By the first isomorphism theorem `G ⧸ C_G(c)` embeds into `(ZMod p)ˣ`,
so the **index of the centralizer divides `p - 1`** — reading off exactly which orders
`p·m` can force `⟨c⟩` central (`[G : C_G(c)] = 1`, i.e. `c` central) versus genuinely
acted-on.  The involution case is recovered as the order-`2` slice: a non-central
involution maps to the unique element `-1` of order `2` in `(ZMod p)ˣ`.

This is the "N/C theorem" (`N_G(H)/C_G(H) ↪ Aut H`) specialised to the *normal*,
*prime-order* cyclic subgroup `H = ⟨c⟩`, where `Aut ⟨c⟩ ≅ (ZMod p)ˣ`.  The whole
development is generic (it only assumes `⟨c⟩` is normal — supplied in the application
by `zpowers_sylow_normal`) and is `0`-sorry / `0`-axiom **verified**.

## Main results

* `conjZModHom c` — the homomorphism `G →* (ZMod (Nat.card ⟨c⟩))ˣ` from conjugation.
* `conjZModHom_ker` — its kernel is the centralizer `C_G(c) = Subgroup.centralizer {c}`.
* `card_units_zmod_zpowers` — the codomain has order `p - 1` when `orderOf c = p` is prime.
* `centralizer_index_dvd` — **`[G : C_G(c)] ∣ p - 1`.**
* `quotientCentralizerEmbedding` — the induced embedding `G ⧸ C_G(c) ↪ (ZMod p)ˣ`.
* `isCyclic_quotient_centralizer` — the induced automorphism group `G ⧸ C_G(c)` is cyclic.
* `centralizer_index_dvd_four`, `central_of_index_coprime` — Abel–Ruffini `p = 5` slices.
-/

namespace AbelRuffiniConjAction

open scoped Classical

/-- The cyclic subgroup `⟨c⟩ = zpowers c` generated by any single element is cyclic
(generated by `c` itself).  Needed so that `IsCyclic.mulAutMulEquiv` applies to it. -/
instance zpowers_isCyclic {G : Type*} [Group G] (c : G) :
    IsCyclic (Subgroup.zpowers c) :=
  (Subgroup.isCyclic_iff_exists_zpowers_eq_top _).mpr ⟨c, rfl⟩

/-- **The conjugation-action homomorphism.**

When `⟨c⟩ = zpowers c` is normal, every `g : G` conjugates `⟨c⟩` to itself, giving an
automorphism `MulAut.conjNormal g : MulAut ⟨c⟩`.  Since `⟨c⟩` is cyclic, its automorphism
group is `(ZMod (Nat.card ⟨c⟩))ˣ` (Mathlib's `IsCyclic.mulAutMulEquiv`).  Composing yields
a group homomorphism `G →* (ZMod (Nat.card ⟨c⟩))ˣ`; concretely `Φ(g)` is the residue
class of the exponent `k` in `g c g⁻¹ = c^k`. -/
noncomputable def conjZModHom {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] :
    G →* (ZMod (Nat.card (Subgroup.zpowers c)))ˣ :=
  (IsCyclic.mulAutMulEquiv (Subgroup.zpowers c)).toMonoidHom.comp MulAut.conjNormal

/-- `Φ(g) = 1` iff conjugation by `g` acts trivially on `⟨c⟩`, since the cyclic
automorphism identification `MulAut ⟨c⟩ ≃* (ZMod _)ˣ` is injective. -/
theorem conjZModHom_eq_one_iff {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] (g : G) :
    conjZModHom c g = 1 ↔ (MulAut.conjNormal g : MulAut (Subgroup.zpowers c)) = 1 := by
  unfold conjZModHom
  simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom]
  exact map_eq_one_iff _ (IsCyclic.mulAutMulEquiv (Subgroup.zpowers c)).injective

/-- Conjugation by `g` acts trivially on the normal cyclic group `⟨c⟩` **iff** `g`
commutes with the generator `c`.  (One direction: evaluate at `c`; the other: every
element of `⟨c⟩` is a power `c^k`, and `g` commutes with all of them once it commutes
with `c`.) -/
theorem conjNormal_eq_one_iff_mem_centralizer {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] {g : G} :
    (MulAut.conjNormal g : MulAut (Subgroup.zpowers c)) = 1
      ↔ g ∈ Subgroup.centralizer {c} := by
  rw [Subgroup.mem_centralizer_singleton_iff]
  constructor
  · intro h
    -- Evaluate the automorphism equality at the generator `⟨c, _⟩`.
    have h2 : ((MulAut.conjNormal g : MulAut (Subgroup.zpowers c))
        ⟨c, Subgroup.mem_zpowers c⟩ : Subgroup.zpowers c)
        = (1 : MulAut (Subgroup.zpowers c)) ⟨c, Subgroup.mem_zpowers c⟩ :=
      DFunLike.congr_fun h _
    have hc : g * c * g⁻¹ = c := by
      have h3 := congrArg (Subtype.val) h2
      rwa [MulAut.conjNormal_apply, MulAut.one_apply] at h3
    -- `g * c * g⁻¹ = c`, hence `g * c = c * g`.
    rwa [mul_inv_eq_iff_eq_mul] at hc
  · intro h
    -- `g` commutes with `c` (this is exactly `Commute g c`), hence with every power `c^k`.
    have hcomm : Commute g c := h
    apply MulEquiv.ext
    intro x
    apply Subtype.ext
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp x.2
    simp only [MulAut.conjNormal_apply, MulAut.one_apply]
    -- goal: `g * ↑x * g⁻¹ = ↑x`, with `↑x = c^k`.
    rw [← hk, mul_inv_eq_iff_eq_mul]
    exact (hcomm.zpow_right k).eq

/-- **The kernel of the conjugation-action homomorphism is the centralizer of `c`.**

`Φ(g) = 1` iff `g` centralizes `c`, so `ker Φ = C_G(c)`.  This is the crux of the
N/C theorem for the normal cyclic subgroup `⟨c⟩`. -/
theorem conjZModHom_ker {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] :
    (conjZModHom c).ker = Subgroup.centralizer {c} := by
  ext g
  rw [MonoidHom.mem_ker, conjZModHom_eq_one_iff,
    conjNormal_eq_one_iff_mem_centralizer]

/-- The centralizer of `c` is a **normal** subgroup: it is the kernel of `conjZModHom c`
(kernels are always normal), which equals `C_G(c)` by `conjZModHom_ker`.  This instance
lets us form the quotient `G ⧸ C_G(c)`. -/
instance centralizer_c_normal {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] : (Subgroup.centralizer {c}).Normal :=
  conjZModHom_ker c ▸ MonoidHom.normal_ker (conjZModHom c)

/-- The codomain `(ZMod (Nat.card ⟨c⟩))ˣ` of `conjZModHom` has order `p - 1` when
`c` has prime order `p`: indeed `Nat.card ⟨c⟩ = orderOf c = p`, and `|(ZMod p)ˣ|`
is `φ(p) = p - 1`. -/
theorem card_units_zmod_zpowers {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (c : G) (hc : orderOf c = p) :
    Nat.card (ZMod (Nat.card (Subgroup.zpowers c)))ˣ = p - 1 := by
  have hcard : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  rw [hcard]
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient, Nat.totient_prime hp.out]

/-- **The index of the centralizer of `c` divides `p - 1`.**

The first isomorphism theorem gives `G ⧸ C_G(c) ≃* range Φ ≤ (ZMod p)ˣ`, so by
Lagrange `[G : C_G(c)] = |G ⧸ C_G(c)|` divides `|(ZMod p)ˣ| = p - 1`.  This is the
sharp structural constraint the "involution acts by `±1`" lemma was a shadow of:
the group of conjugation-automorphisms of the prime-order `⟨c⟩` has order dividing
`p - 1`. -/
theorem centralizer_index_dvd {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (c : G) (hc : orderOf c = p)
    [(Subgroup.zpowers c).Normal] :
    (Subgroup.centralizer {c}).index ∣ p - 1 := by
  rw [Subgroup.index_eq_card, ← conjZModHom_ker c]
  have e := QuotientGroup.quotientKerEquivRange (conjZModHom c)
  have hcong : Nat.card (G ⧸ (conjZModHom c).ker) = Nat.card (conjZModHom c).range :=
    Nat.card_congr e.toEquiv
  rw [hcong]
  have hdvd := Subgroup.card_subgroup_dvd_card (conjZModHom c).range
  rwa [card_units_zmod_zpowers c hc] at hdvd

/-- **The induced embedding `G ⧸ C_G(c) ↪ (ZMod (Nat.card ⟨c⟩))ˣ`.**

Transport the first isomorphism theorem `G ⧸ ker Φ ≃* range Φ` along `ker Φ = C_G(c)`,
then include the range into the units.  This is the literal `G ⧸ C_G(c) ↪ (ZMod p)ˣ`. -/
noncomputable def quotientCentralizerEmbedding {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] :
    (G ⧸ Subgroup.centralizer {c}) →* (ZMod (Nat.card (Subgroup.zpowers c)))ˣ :=
  (QuotientGroup.kerLift (conjZModHom c)).comp
    (QuotientGroup.quotientMulEquivOfEq (conjZModHom_ker c).symm).toMonoidHom

theorem quotientCentralizerEmbedding_injective {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] :
    Function.Injective (quotientCentralizerEmbedding c) := by
  rw [quotientCentralizerEmbedding, MonoidHom.coe_comp]
  exact (QuotientGroup.kerLift_injective _).comp
    (QuotientGroup.quotientMulEquivOfEq (conjZModHom_ker c).symm).injective

/-- **The induced automorphism group `G ⧸ C_G(c)` is cyclic.**

`G ⧸ C_G(c)` embeds into `(ZMod p)ˣ`, which is cyclic (units of the finite field
`ZMod p`).  A subgroup — indeed any group embedding into a cyclic group — is cyclic.
So the group of conjugation-automorphisms of `⟨c⟩` is cyclic of order dividing `p - 1`. -/
theorem isCyclic_quotient_centralizer {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (c : G) (hc : orderOf c = p)
    [(Subgroup.zpowers c).Normal] :
    IsCyclic (G ⧸ Subgroup.centralizer {c}) := by
  have hcard : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  haveI : Fact (Nat.Prime (Nat.card (Subgroup.zpowers c))) := ⟨hcard ▸ hp.out⟩
  haveI : NeZero (Nat.card (Subgroup.zpowers c)) := ⟨hcard ▸ hp.out.pos.ne'⟩
  -- `(ZMod p)ˣ` is cyclic (units of the finite field `ZMod p`), hence so is any
  -- subgroup and any group injecting into it.
  haveI : IsCyclic (ZMod (Nat.card (Subgroup.zpowers c)))ˣ := inferInstance
  exact isCyclic_of_injective (quotientCentralizerEmbedding c)
    (quotientCentralizerEmbedding_injective c)

/-! ### Abel–Ruffini application: the fixed prime `p = 5` -/

/-- **`p = 5` slice.**  For an order-`5` element `c` with `⟨c⟩` normal (as supplied by
`zpowers_order5_normal` in the sibling file), the centralizer index divides `4 = 5 - 1`.
In the `x⁵-4x+2` obstruction the candidate orders are `10, 20, 40`, so `[G : C_G(c)]`
divides `gcd(4, |G|)`, pinning down when a transposition can act nontrivially on the
normal `5`-cycle group. -/
theorem centralizer_index_dvd_four {G : Type*} [Group G] [Finite G]
    (c : G) (hc : orderOf c = 5) [(Subgroup.zpowers c).Normal] :
    (Subgroup.centralizer {c}).index ∣ 4 := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  simpa using centralizer_index_dvd c hc

/-- **Centrality criterion.**  If the index `[G : C_G(c)]` is coprime to `p - 1`, then
it divides `p - 1` (by `centralizer_index_dvd`) and is coprime to it, forcing index `1`:
the centralizer is everything, i.e. `c` is **central**.  This is the precise "central vs
acted-on" dichotomy — e.g. any element of order `5` in a group whose order is coprime to
`4` is central. -/
theorem central_of_index_coprime {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (c : G) (hc : orderOf c = p)
    [(Subgroup.zpowers c).Normal]
    (hcop : Nat.Coprime (Subgroup.centralizer {c}).index (p - 1)) :
    Subgroup.centralizer {c} = ⊤ := by
  have hdvd := centralizer_index_dvd c hc
  have hidx : (Subgroup.centralizer {c}).index = 1 :=
    Nat.eq_one_of_dvd_coprimes hcop dvd_rfl hdvd
  exact Subgroup.index_eq_one.mp hidx

end AbelRuffiniConjAction
