import Mathlib

/-
# The explicit chief series of A₄: `A₄ ⊵ V₄ ⊵ {e}` with identified factors

Open Question from `abel-ruffini-oq-04-oq-02-oq-02`
(*Alternating Groups: Aₙ Solvable iff n ≤ 4*):

> Can the chief series for `A₄` (`A₄ ⊵ V₄ ⊵ {e}`) be exhibited explicitly in Lean with
> the quotient group isomorphisms `A₄/V₄ ≅ ℤ/3ℤ` and `V₄ ≅ (ℤ/2ℤ)²` identified?

## Answer: YES.

The parent entry proves `A₄` solvable indirectly (as a subgroup of the solvable `S₄`, or by
collapsing its second derived subgroup with `native_decide`). This entry instead exhibits the
*classical chief (solvable) series* of `A₄` explicitly and identifies both chief factors with
their standard models:

* the **normal Klein four-group** `V₄ ◁ A₄` — Mathlib's `alternatingGroup.kleinFour (Fin 4)`,
  the subgroup generated by the cycle-type `(2,2)` permutations;
* the **top factor** `A₄ / V₄ ≅ ℤ/3ℤ`, a cyclic group of prime order `3`;
* the **bottom factor** `V₄ ≅ (ℤ/2ℤ)²`, the Klein four-group.

Both factors are abelian (indeed of prime power order), so the series

  `A₄  ⊵  V₄  ⊵  {e}`

is a chief (solvable) series with abelian factors, re-proving the solvability of `A₄`
*constructively*, by displaying the abelian layers rather than by an oracle. It is **not** a
composition series: the bottom factor `V₄ ≅ (ℤ/2ℤ)²` is abelian but not simple, so it refines
further (`V₄ ▷ C₂ ▷ 1`) to reach the genuine composition series `A₄ ▷ V₄ ▷ C₂ ▷ 1`.

## Method

Everything is assembled from Mathlib's alternating-group / Klein-four infrastructure
(`Mathlib.GroupTheory.SpecificGroups.Alternating.KleinFour`,
`Mathlib.GroupTheory.SpecificGroups.KleinFour`,
`Mathlib.GroupTheory.SpecificGroups.Cyclic`):

* `alternatingGroup.normal_kleinFour` : `V₄` is normal in `A₄` (it is even characteristic, being
  the unique Sylow `2`-subgroup);
* `|A₄| = 12` (`card_of_card_eq_four`) and `|V₄| = 4` (`kleinFour_card_of_card_eq_four`) give
  `|A₄ / V₄| = 3` by Lagrange (`Subgroup.card_eq_card_quotient_mul_card_subgroup`);
* `mulEquivOfPrimeCardEq` turns the prime order `3` into the explicit isomorphism
  `A₄ / V₄ ≅ Multiplicative (ZMod 3)`;
* `V₄` is a Klein four-group (`kleinFour_isKleinFour`), and any two Klein four-groups are
  isomorphic (`IsKleinFour.nonempty_mulEquiv`), giving `V₄ ≅ Multiplicative (ZMod 2 × ZMod 2)`.

Finally `kleinFour_eq_commutator` records that this `V₄` is exactly the commutator subgroup
`[A₄, A₄]`, so the displayed series is precisely the derived series of `A₄`.
-/

namespace AbelRuffiniA4CompositionSeries

open scoped Classical

/-- `Nat.card (Fin 4) = 4`, the hypothesis every `alternatingGroup.kleinFour` lemma needs. -/
theorem card_fin_four : Nat.card (Fin 4) = 4 :=
  Nat.card_eq_fintype_card.trans (Fintype.card_fin 4)

/-- **`V₄ ◁ A₄`.** The Klein four-group is a normal subgroup of `A₄`
(it is the unique Sylow `2`-subgroup, hence even characteristic). -/
theorem v4_normal : (alternatingGroup.kleinFour (Fin 4)).Normal :=
  alternatingGroup.normal_kleinFour card_fin_four

/-- `V₄ ◁ A₄` registered as an instance, so the quotient `A₄ ⧸ V₄` carries its group
structure in the `≃*` statements below (otherwise `Mul (A₄ ⧸ V₄)` fails to synthesize at
statement-elaboration time — a body-level `haveI` would be too late). -/
instance v4_normal_inst : (alternatingGroup.kleinFour (Fin 4)).Normal :=
  alternatingGroup.normal_kleinFour card_fin_four

/-- `V₄` coincides with the commutator subgroup `[A₄, A₄]`: the displayed series
`A₄ ⊵ V₄ ⊵ {e}` is exactly the derived series of `A₄`. -/
theorem v4_eq_commutator :
    alternatingGroup.kleinFour (Fin 4) = commutator (alternatingGroup (Fin 4)) :=
  alternatingGroup.kleinFour_eq_commutator card_fin_four

/-- `|A₄| = 12`. -/
theorem card_a4 : Nat.card (alternatingGroup (Fin 4)) = 12 :=
  alternatingGroup.card_of_card_eq_four card_fin_four

/-- `|V₄| = 4`. -/
theorem card_v4 : Nat.card (alternatingGroup.kleinFour (Fin 4)) = 4 :=
  alternatingGroup.kleinFour_card_of_card_eq_four card_fin_four

/-- **The top factor has order `3`:** `|A₄ / V₄| = 3`, by Lagrange. -/
theorem card_quotient :
    Nat.card (alternatingGroup (Fin 4) ⧸ alternatingGroup.kleinFour (Fin 4)) = 3 := by
  haveI := v4_normal
  rw [← Nat.mul_left_inj (a := Nat.card (alternatingGroup.kleinFour (Fin 4)))]
  · rw [← Subgroup.card_eq_card_quotient_mul_card_subgroup, card_a4, card_v4]
  · rw [card_v4]; simp

/-- `V₄` is a Klein four-group. -/
theorem v4_isKleinFour : IsKleinFour (alternatingGroup.kleinFour (Fin 4)) :=
  alternatingGroup.kleinFour_isKleinFour card_fin_four

/-- `|Multiplicative (ZMod 3)| = 3`. -/
theorem card_mult_zmod3 : Nat.card (Multiplicative (ZMod 3)) = 3 := by
  simp only [Nat.card_eq_fintype_card, Fintype.card_multiplicative, ZMod.card]

/-- **The top chief factor, identified: `A₄ / V₄ ≅ ℤ/3ℤ`.**
The quotient has prime order `3`, so it is cyclic and isomorphic to `Multiplicative (ZMod 3)`. -/
theorem quotient_iso_zmod3 :
    Nonempty ((alternatingGroup (Fin 4) ⧸ alternatingGroup.kleinFour (Fin 4))
      ≃* Multiplicative (ZMod 3)) := by
  haveI := v4_normal
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  exact ⟨mulEquivOfPrimeCardEq card_quotient card_mult_zmod3⟩

/-- **The bottom chief factor, identified: `V₄ ≅ (ℤ/2ℤ)²`.**
Both sides are Klein four-groups, and any two Klein four-groups are isomorphic. -/
theorem v4_iso_zmod2_sq :
    Nonempty (alternatingGroup.kleinFour (Fin 4) ≃* Multiplicative (ZMod 2 × ZMod 2)) := by
  haveI := v4_isKleinFour
  exact IsKleinFour.nonempty_mulEquiv

/-- **The explicit chief series `A₄ ⊵ V₄ ⊵ {e}` with both factors identified.**

Packages the full answer to the open question:
* `V₄` is normal in `A₄`;
* the two factors have orders `3` and `4`;
* `A₄ / V₄ ≅ ℤ/3ℤ` (top factor, cyclic of prime order);
* `V₄ ≅ (ℤ/2ℤ)²` (bottom factor, Klein four).

Both factors are abelian, so this is a chief (solvable) series with abelian factors and `A₄` is
solvable — re-derived constructively from the displayed layers. (It is not a composition series:
`V₄ ≅ (ℤ/2ℤ)²` is not simple; the true composition series refines it to `A₄ ▷ V₄ ▷ C₂ ▷ 1`.) -/
theorem composition_series_A4 :
    (alternatingGroup.kleinFour (Fin 4)).Normal ∧
      Nat.card (alternatingGroup (Fin 4) ⧸ alternatingGroup.kleinFour (Fin 4)) = 3 ∧
      Nat.card (alternatingGroup.kleinFour (Fin 4)) = 4 ∧
      Nonempty ((alternatingGroup (Fin 4) ⧸ alternatingGroup.kleinFour (Fin 4))
        ≃* Multiplicative (ZMod 3)) ∧
      Nonempty (alternatingGroup.kleinFour (Fin 4) ≃* Multiplicative (ZMod 2 × ZMod 2)) :=
  ⟨v4_normal, card_quotient, card_v4, quotient_iso_zmod3, v4_iso_zmod2_sq⟩

end AbelRuffiniA4CompositionSeries
