import Mathlib

/-!
# Abel–Ruffini OQ04·OQ01·OQ03 — Factoring the Sylow-elimination lemmas

The verified Abel–Ruffini proof that `x⁵ - 4x + 2` is not solvable by radicals
(`AbelRuffiniOQ04OQ01.lean`) rules out `|Gal| ∈ {10, 20, 40}` with three
essentially **verbatim** `private` lemmas `gal_card_ne_10 / _20 / _40`.  Each is
a Sylow argument on a subgroup `G ≤ S₅` of order `5·m` (`m = 2, 4, 8`):

* the Sylow 5-subgroup `P₅` has order `5` (since `5 ∥ |G|`);
* the number of Sylow 5-subgroups `n₅` divides the index `m` and satisfies
  `n₅ ≡ 1 (mod 5)`, forcing `n₅ = 1`;
* hence `P₅` is **normal** and equals `⟨c⟩` for any order-`5` element `c`,
  so every element normalizes `⟨c⟩`;
* but a transposition cannot normalize a 5-cycle — contradiction.

Only the last bullet is specific to `S₅`.  The first three bullets are a *pure
group-theory* statement depending solely on the **group order** `5·m`.  This
file factors that shared core into a single generic lemma, and — as the
OQ04·OQ01·OQ03·OQ01 follow-up — lifts it **from the fixed prime `5` to an
arbitrary prime `p`**: the truly general statement

> in a finite group of order `p·m` with `p ∤ m` and a "no small Frobenius
> divisor" condition on `m`, the cyclic subgroup generated by an order-`p`
> element is normal.

Generalising the prime is *not* a cosmetic rename: with `p` fixed the two
number-theoretic steps `n_p ≡ 1 (mod p) ⇒ n_p = 1` and `[G:P]·p = p·m ⇒
[G:P] = m` are discharged by `omega`/`interval_cases` on concrete numerals,
whereas for a variable `p` they require `Nat.mod_eq_of_lt` (to evaluate
`1 % p`) and `Nat.eq_of_mul_eq_mul_right` (nonlinear cancellation `omega`
cannot see).  The fixed-`5` lemma is recovered as a one-line corollary.

Everything here is fully abstract (no `Polynomial.Gal`, no permutations) and
avoids `native_decide`, so the file is `0`-sorry / `0`-axiom **verified**.  The
three original orders `10 = 5·2`, `20 = 5·4`, `40 = 5·8` are recovered as the
`example`s at the end, which discharge the divisor hypothesis for `m ∈ {2,4,8}`.

## Main results

* `zpowers_sylow_normal` — **general prime `p`.**  In a finite group of order
  `p·m` with `p ∤ m` and no divisor `d ∣ m`, `d ≡ 1 (mod p)` other than
  `d = 1`, the cyclic subgroup generated by any order-`p` element is normal.
* `conj_mem_zpowers_sylow` — consequently every element normalizes `⟨c⟩`.
* `zpowers_order5_normal` / `conj_mem_zpowers_order5` — the `p = 5`
  specialisations feeding the Abel–Ruffini `x⁵-4x+2` proof, now one-liners.
-/

namespace AbelRuffiniSylowElim

open scoped Classical

/-- **Generic Sylow-elimination core (arbitrary prime).**

In a finite group `G` of order `p·m`, where `p` is prime, `p ∤ m`, and the only
divisor `d` of `m` with `d ≡ 1 (mod p)` is `d = 1`, the Sylow `p`-subgroup is
unique, hence normal, and equals `⟨c⟩` for any element `c` of order `p`.
Therefore `⟨c⟩` is a normal subgroup.

This is the shared skeleton of the three `private` lemmas
`gal_card_ne_10 / _20 / _40` in the verified Abel–Ruffini `x⁵-4x+2` proof,
lifted to an arbitrary group **and an arbitrary prime**, parameterized by the
order `p·m`. -/
theorem zpowers_sylow_normal {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.zpowers c).Normal := by
  haveI : Fintype G := Fintype.ofFinite G
  have hm0 : m ≠ 0 := by rintro rfl; exact hpm (dvd_zero p)
  -- A Sylow `p`-subgroup has order exactly `p`, since `p ∥ |G|`.
  obtain ⟨P₅⟩ := Sylow.nonempty (p := p) (G := G)
  have hP_card : Nat.card (↑P₅ : Subgroup G) = p := by
    have hppart : (p * m).factorization p = 1 := by
      rw [Nat.factorization_mul hp.out.pos.ne' hm0, Finsupp.add_apply,
        hp.out.factorization, Finsupp.single_eq_same,
        Nat.factorization_eq_zero_of_not_dvd hpm]
    rw [P₅.card_eq_multiplicity, hcard, hppart, pow_one]
  -- Sylow's third theorem: `n_p ∣ m` and `n_p ≡ 1 (mod p)`, forcing `n_p = 1`.
  have hsylow_one : Nat.card (Sylow p G) = 1 := by
    have h_mod := card_sylow_modEq_one p G
    have h_idx : (↑P₅ : Subgroup G).index = m := by
      have hh := (↑P₅ : Subgroup G).index_mul_card
      rw [hP_card, hcard] at hh
      exact Nat.eq_of_mul_eq_mul_right hp.out.pos (by rw [hh]; ring)
    have h_dvd := Sylow.card_dvd_index P₅
    rw [h_idx] at h_dvd
    rw [Nat.ModEq, Nat.mod_eq_of_lt hp.out.one_lt] at h_mod
    exact huniq _ h_dvd h_mod
  -- Uniqueness ⇒ the Sylow `p`-subgroup is normal.
  haveI : Subsingleton (Sylow p G) := by
    haveI := Fintype.ofFinite (Sylow p G)
    rw [← Fintype.card_le_one_iff_subsingleton, ← Nat.card_eq_fintype_card]; omega
  haveI hNP : (↑P₅ : Subgroup G).Normal := by
    apply Subgroup.Normal.mk; intro n hn g
    have hs : g • P₅ = P₅ := Subsingleton.elim _ _
    rw [Sylow.smul_eq_iff_mem_normalizer] at hs
    exact ((Subgroup.mem_normalizer_iff.mp hs) n).mp hn
  -- `⟨c⟩` is a subgroup of order `p`, hence equal to the (unique) `P₅`.
  have hc_P5 : c ∈ (↑P₅ : Subgroup G) := by
    have h_pg : IsPGroup p (Subgroup.zpowers c) :=
      IsPGroup.iff_card.mpr ⟨1, by rw [pow_one, Nat.card_zpowers, hc]⟩
    obtain ⟨Q, hQ⟩ := h_pg.exists_le_sylow
    exact (Subsingleton.elim Q P₅ : Q = P₅) ▸ hQ (Subgroup.mem_zpowers c)
  have hzpow_le : Subgroup.zpowers c ≤ ↑P₅ := fun x hx => by
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
    exact (↑P₅ : Subgroup G).zpow_mem hc_P5 k
  have hP5_eq : (↑P₅ : Subgroup G) = Subgroup.zpowers c := by
    apply le_antisymm _ hzpow_le
    intro x hx
    have hbij : Function.Bijective (Subgroup.inclusion hzpow_le) := by
      haveI := Fintype.ofFinite ↥(↑P₅ : Subgroup G)
      haveI := Fintype.ofFinite ↥(Subgroup.zpowers c)
      exact (Fintype.bijective_iff_injective_and_card _).mpr
        ⟨Subgroup.inclusion_injective _, by
          rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card,
              Nat.card_zpowers, hc, hP_card]⟩
    obtain ⟨⟨y, hy⟩, hxy⟩ := hbij.surjective ⟨x, hx⟩
    rwa [show y = x from congr_arg Subtype.val hxy] at hy
  -- Transport normality along `P₅ = ⟨c⟩`.
  rwa [hP5_eq] at hNP

/-- Consequence of `zpowers_sylow_normal`: under the same hypotheses, **every**
element `g` normalizes `⟨c⟩`, i.e. `g c g⁻¹ ∈ ⟨c⟩`. -/
theorem conj_mem_zpowers_sylow {G : Type*} [Group G] [Finite G] {p : ℕ}
    [Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (g : G) :
    g * c * g⁻¹ ∈ Subgroup.zpowers c :=
  (zpowers_sylow_normal m hcard hpm huniq c hc).conj_mem c (Subgroup.mem_zpowers c) g

/-- **Abstract "an involution acts by inversion" step.**

Under the hypotheses of `zpowers_sylow_normal` (so `⟨c⟩` is normal of prime order
`p`), any *involution* `g` — an element with `g * g = 1`, in particular any
transposition once `G ↪ S₅` — conjugates `c` either to itself or to its inverse:

    `g * c * g⁻¹ = c    ∨    g * c * g⁻¹ = c⁻¹`.

This is the abstract heart of the final, `S₅`-specific bullet of the three
`gal_card_ne_10 / _20 / _40` lemmas ("a transposition cannot normalize a 5-cycle"):
conjugation by `g` normalizes `⟨c⟩`, so `g c g⁻¹ = c ^ k` for some `k : ℤ`;
conjugating a second time and using `g * g = 1` gives `c ^ (k*k) = c`, whence
`k*k ≡ 1 (mod p)`; as `p` is prime, `p ∣ (1-k)(1+k)` forces `k ≡ ±1 (mod p)`, i.e.
`c ^ k = c` or `c⁻¹`. (The concrete step then observes that a genuine transposition
conjugates a 5-cycle to a different 5-cycle, ruling out *both* alternatives — but
that part needs the permutation structure and lives in the concrete proof.) -/
theorem involution_conj_eq_self_or_inv {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) {g : G} (hg : g * g = 1) :
    g * c * g⁻¹ = c ∨ g * c * g⁻¹ = c⁻¹ := by
  -- `g c g⁻¹ ∈ ⟨c⟩`, so `g c g⁻¹ = c ^ k` for some `k : ℤ`.
  obtain ⟨k, hk⟩ :=
    Subgroup.mem_zpowers_iff.mp (conj_mem_zpowers_sylow m hcard hpm huniq c hc g)
  -- Conjugating `c ^ k` by `g` again returns `c`, using `g * g = 1`.
  have hconj2 : g * c ^ k * g⁻¹ = c := by
    rw [hk]
    have : g * (g * c * g⁻¹) * g⁻¹ = (g * g) * c * (g⁻¹ * g⁻¹) := by group
    rw [this, hg]
    have hg' : g⁻¹ * g⁻¹ = 1 := by rw [← mul_inv_rev, hg, inv_one]
    rw [hg', one_mul, mul_one]
  -- Conjugation is an automorphism, so it commutes with taking the `k`-th power.
  have hpow : g * c ^ k * g⁻¹ = (g * c * g⁻¹) ^ k := by
    simpa [MulAut.conj_apply] using (map_zpow (MulAut.conj g) c k)
  -- Combine: `c = (c ^ k) ^ k = c ^ (k * k)`.
  rw [hpow, ← hk, ← zpow_mul] at hconj2
  have hkey : c ^ (k * k) = c ^ (1 : ℤ) := by rw [zpow_one]; exact hconj2
  -- `k * k ≡ 1 (mod p)`.
  rw [zpow_eq_zpow_iff_modEq, hc] at hkey
  have hdvd : (p : ℤ) ∣ (1 - k) * (1 + k) := by
    have h := (Int.modEq_iff_dvd.mp hkey)
    calc (p : ℤ) ∣ 1 - k * k := h
      _ = (1 - k) * (1 + k) := by ring
  haveI hp_int : Prime (p : ℤ) := Int.prime_iff_natAbs_prime.mpr (by simpa using hp.out)
  rcases hp_int.dvd_mul.mp hdvd with h1 | h2
  · -- `k ≡ 1 (mod p)` ⇒ `c ^ k = c`.
    left
    have : k ≡ 1 [ZMOD p] := Int.modEq_iff_dvd.mpr h1
    have hck : c ^ k = c ^ (1 : ℤ) := zpow_eq_zpow_iff_modEq.mpr (by rw [hc]; exact this)
    rw [hk] at hck
    rw [hck, zpow_one]
  · -- `k ≡ -1 (mod p)` ⇒ `c ^ k = c⁻¹`.
    right
    have : k ≡ -1 [ZMOD p] := Int.modEq_iff_dvd.mpr (by
      have : (p : ℤ) ∣ 1 + k := h2
      rwa [show (-1 : ℤ) - k = -(1 + k) by ring, dvd_neg])
    have hck : c ^ k = c ^ (-1 : ℤ) := zpow_eq_zpow_iff_modEq.mpr (by rw [hc]; exact this)
    rw [hk] at hck
    rw [hck, zpow_neg_one]

/-- **Reusable sufficient condition for the divisor hypothesis `huniq`.** If the
index `m` is smaller than the prime `p`, then the only divisor `d ∣ m` with
`d ≡ 1 (mod p)` is `d = 1`: any such `d` satisfies `d ≤ m < p`, so `d % p = d`, and
`d % p = 1` gives `d = 1`. This discharges the `huniq` hypothesis uniformly for every
index below `p` (in the Abel–Ruffini application, `m = 2` and `m = 4` are `< 5`; only
`m = 8 > 5` genuinely needs the divisibility, as `6 ≡ 1 (mod 5)` but `6 ∤ 8`). -/
theorem huniq_of_lt {p m : ℕ} (hm0 : 0 < m) (hmp : m < p) :
    ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1 := by
  intro d hd hmod
  have hdm : d ≤ m := Nat.le_of_dvd hm0 hd
  have hdp : d < p := lt_of_le_of_lt hdm hmp
  rwa [Nat.mod_eq_of_lt hdp] at hmod

/-! ### Structural consequence: the group is not simple

The whole point of a *normal* Sylow `p`-subgroup is structural: it is a proper,
nontrivial normal subgroup, so the ambient group is **not simple**.  This is
precisely why the Galois groups arising from `x⁵-4x+2` (orders `10, 20, 40`)
cannot be the simple `A₅`, and — more generally — why the "order `p·m`" obstruction
argument never produces a simple group.  A non-simple finite group has a nontrivial
proper normal subgroup, the first ingredient of a composition/derived series, so
these results feed directly into solvability-by-radicals arguments for higher-degree
extensions. -/

/-- **The index of `⟨c⟩` equals `m`** (equivalently, the quotient `G ⧸ ⟨c⟩` has
order `m`).  Pure counting: `|⟨c⟩| = orderOf c = p` and `[G:⟨c⟩]·|⟨c⟩| = |G| = p·m`,
so cancel the prime `p`.  Needs neither the divisor hypothesis nor normality. -/
theorem zpowers_index_eq {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ) (hcard : Nat.card G = p * m)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.zpowers c).index = m := by
  have hcard_zc : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  have hh := (Subgroup.zpowers c).index_mul_card
  rw [hcard_zc, hcard] at hh
  exact Nat.eq_of_mul_eq_mul_right hp.out.pos (by rw [hh]; ring)

/-- **Non-simplicity from a normal Sylow `p`-subgroup (arbitrary prime).**

Under the hypotheses of `zpowers_sylow_normal` together with `1 < m`, the cyclic
group `⟨c⟩` is a normal subgroup that is neither trivial (it has prime order `p`)
nor everything (its index is `m > 1`), so `G` is **not simple**.  In particular no
group carrying this "order `p·m`, `p ∤ m`, no small Frobenius divisor" structure can
be a nonabelian simple group such as `A₅`. -/
theorem not_isSimpleGroup_of_sylow {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1) (hm : 1 < m)
    (c : G) (hc : orderOf c = p) :
    ¬ IsSimpleGroup G := by
  intro hsimple
  haveI := hsimple
  have hN := zpowers_sylow_normal m hcard hpm huniq c hc
  rcases IsSimpleGroup.eq_bot_or_eq_top_of_normal (Subgroup.zpowers c) hN with hb | ht
  · -- `⟨c⟩ = ⊥` would force `c = 1`, contradicting `orderOf c = p > 1`.
    rw [Subgroup.zpowers_eq_bot] at hb
    rw [hb, orderOf_one] at hc
    exact absurd hc.symm hp.out.one_lt.ne'
  · -- `⟨c⟩ = ⊤` would force index `1 = m`, contradicting `1 < m`.
    have hidx := zpowers_index_eq m hcard c hc
    rw [ht, Subgroup.index_top] at hidx
    omega

/-! ### The fixed prime `p = 5`

The original Abel–Ruffini application only needs `p = 5`.  With the general
lemma in hand these become one-liners: instantiate `[Fact (Nat.Prime 5)]` and
apply. -/

/-- **Fixed prime `5` core** (`p = 5` specialisation of `zpowers_sylow_normal`).

In a finite group of order `5·m` where `5 ∤ m` and the only divisor `d` of `m`
with `d ≡ 1 (mod 5)` is `d = 1`, the cyclic subgroup generated by any order-`5`
element is normal.  This is the shared skeleton of the three `private` lemmas
`gal_card_ne_10 / _20 / _40` in the verified Abel–Ruffini `x⁵-4x+2` proof. -/
theorem zpowers_order5_normal {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) :
    (Subgroup.zpowers c).Normal :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  zpowers_sylow_normal m hcard hm5 huniq c hc

/-- Consequence of `zpowers_order5_normal`: under the same hypotheses, **every**
element `g` normalizes `⟨c⟩`, i.e. `g c g⁻¹ ∈ ⟨c⟩`.  This is exactly the shared
`hconj_zpow` step of `gal_card_ne_10 / _20 / _40`. -/
theorem conj_mem_zpowers_order5 {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) (g : G) :
    g * c * g⁻¹ ∈ Subgroup.zpowers c :=
  (zpowers_order5_normal m hcard hm5 huniq c hc).conj_mem c (Subgroup.mem_zpowers c) g

/-- **Fixed prime `5` non-simplicity** (`p = 5` specialisation of
`not_isSimpleGroup_of_sylow`).  A finite group of order `5·m` with `1 < m`,
`5 ∤ m`, the `huniq` divisor condition, and an order-`5` element is not simple —
its normal `⟨c⟩` is a proper nontrivial normal subgroup.  This is exactly the
structural reason the `x⁵-4x+2` Galois groups of order `10, 20, 40` are not the
simple `A₅`. -/
theorem not_isSimpleGroup_order5 {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1) (hm : 1 < m)
    (c : G) (hc : orderOf c = 5) :
    ¬ IsSimpleGroup G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  not_isSimpleGroup_of_sylow m hcard hm5 huniq hm c hc

/-! ### Recovering the three original orders `10, 20, 40`

The three `private` lemmas in `AbelRuffiniOQ04OQ01.lean` instantiate the core at
`m = 2` (order `10`), `m = 4` (order `20`), and `m = 8` (order `40`).  Each such
instantiation needs the divisor hypothesis `huniq`, verified here once and for
all for the three relevant indices. -/

/-- Order `10 = 5·2`: the only divisor of `2` that is `≡ 1 (mod 5)` is `1`.
Since `2 < 5`, this is the `huniq_of_lt` case. -/
example : ∀ d : ℕ, d ∣ 2 → d % 5 = 1 → d = 1 := huniq_of_lt (by norm_num) (by norm_num)

/-- Order `20 = 5·4`: the only divisor of `4` that is `≡ 1 (mod 5)` is `1`.
Since `4 < 5`, this is again the `huniq_of_lt` case. -/
example : ∀ d : ℕ, d ∣ 4 → d % 5 = 1 → d = 1 := huniq_of_lt (by norm_num) (by norm_num)

/-- Order `40 = 5·8`: the only divisor of `8` that is `≡ 1 (mod 5)` is `1`.
Note `6 ≡ 1 (mod 5)` but `6 ∤ 8`, so the divisibility hypothesis is essential. -/
example : ∀ d : ℕ, d ∣ 8 → d % 5 = 1 → d = 1 := by
  intro d hd hmod; have := Nat.le_of_dvd (by norm_num) hd; interval_cases d <;> omega

/-- **Capstone.** Any finite group of order `40` containing an element of order `5`
is not simple: order `40 = 5·8`, `5 ∤ 8`, the divisor condition holds (only `1 ∣ 8`
is `≡ 1 mod 5`, as `6 ∤ 8`), and `8 > 1`, so `not_isSimpleGroup_order5` applies. -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 40) : ¬ IsSimpleGroup G :=
  not_isSimpleGroup_order5 8 (hcard.trans (by norm_num)) (by norm_num)
    (by intro d hd hmod; have := Nat.le_of_dvd (by norm_num) hd; interval_cases d <;> omega)
    (by norm_num) c hc

/-! ### Structural consequence: solvability

Non-simplicity is only the first structural payoff of a *normal* Sylow
`p`-subgroup.  The stronger consequence — the one that actually drives
"solvable-by-radicals" — is **solvability**.  The normal subgroup `⟨c⟩` has prime
order `p`, so it is cyclic, abelian, and solvable; a group that is an extension of
a solvable group by a solvable group is itself solvable.  Hence `G` is solvable as
soon as the order-`m` quotient `G ⧸ ⟨c⟩` is.

This is the group-theoretic engine behind the Abel–Ruffini obstruction read the
other way round: the candidate Galois-group orders `10, 20, 40` for `x⁵-4x+2` all
have solvable `⟨c⟩`-quotients (they are `2`-groups), so any group carrying that
order would be *solvable* — whereas the genuine Galois group `A₅` is **not**
solvable.  It is precisely this mismatch that rules those orders out and forces
the group to be `S₅`, the non-solvable obstruction certifying non-solvability by
radicals. -/

/-- **The normal subgroup `⟨c⟩` is solvable** (being cyclic, hence abelian).  A
standalone helper feeding the solvable-extension theorem below; needs no
finiteness or order hypothesis. -/
theorem isSolvable_zpowers {G : Type*} [Group G] (c : G) :
    IsSolvable (Subgroup.zpowers c) := by
  apply isSolvable_of_comm
  rintro ⟨a, ha⟩ ⟨b, hb⟩
  obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp ha
  obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hb
  exact Subtype.ext (by simpa using zpow_mul_comm c i j)

/-- **General solvable-extension engine.**  If `N` is a normal subgroup with both
`N` and the quotient `G ⧸ N` solvable, then `G` is solvable.  (An extension of a
solvable group by a solvable group is solvable.)  Packages Mathlib's
`solvable_of_ker_le_range` for the inclusion `N ↪ G` and the projection `G ↠ G ⧸ N`,
whose kernel `N` equals the range of the inclusion. -/
theorem isSolvable_of_normal_solvable_quotient {G : Type*} [Group G]
    (N : Subgroup G) [N.Normal] [IsSolvable N] [IsSolvable (G ⧸ N)] :
    IsSolvable G :=
  solvable_of_ker_le_range N.subtype (QuotientGroup.mk' N)
    (le_of_eq (by rw [QuotientGroup.ker_mk', Subgroup.range_subtype]))

/-- **Solvability from a normal Sylow `p`-subgroup with prime-power index.**

Under the hypotheses of `zpowers_sylow_normal`, the cyclic subgroup `⟨c⟩` is a
*normal* subgroup of prime order `p` — hence abelian and solvable — with quotient
`G ⧸ ⟨c⟩` of order `m`.  If moreover the index `m = q^k` is a prime power for some
prime `q`, then the quotient is a finite `q`-group, hence nilpotent, hence solvable,
so `G` itself is solvable by the extension engine.

This is a fully general, self-contained sufficient condition — no separate
solvability input about the quotient is needed, only that its order is a prime
power — and it upgrades the non-simplicity result `not_isSimpleGroup_of_sylow` to
the full solvability statement that feeds radical-tower arguments.  (The `x⁵-4x+2`
orders `10 = 5·2`, `20 = 5·2²`, `40 = 5·2³` are exactly this case with `q = 2`.) -/
theorem isSolvable_of_sylow_primePow_index {G : Type*} [Group G] [Finite G]
    {p q k : ℕ} [Fact p.Prime] [Fact q.Prime]
    (hcard : Nat.card G = p * q ^ k) (hpm : ¬ (p ∣ q ^ k))
    (huniq : ∀ d : ℕ, d ∣ q ^ k → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    IsSolvable G := by
  haveI : (Subgroup.zpowers c).Normal := zpowers_sylow_normal (q ^ k) hcard hpm huniq c hc
  haveI : IsSolvable (Subgroup.zpowers c) := isSolvable_zpowers c
  have hidx : Nat.card (G ⧸ Subgroup.zpowers c) = q ^ k := by
    rw [← Subgroup.index_eq_card]; exact zpowers_index_eq (q ^ k) hcard c hc
  haveI : Group.IsNilpotent (G ⧸ Subgroup.zpowers c) := (IsPGroup.of_card hidx).isNilpotent
  exact isSolvable_of_normal_solvable_quotient (Subgroup.zpowers c)

/-! ### The fixed prime `p = 5`, solvability form -/

/-- **Fixed prime `5` solvability** (`p = 5` specialisation of
`isSolvable_of_sylow_primePow_index`).  A finite group of order `5·q^k` with
`5 ∤ q^k`, the divisor condition, and an order-`5` element is solvable.  This is
the solvability counterpart of `not_isSimpleGroup_order5`. -/
theorem isSolvable_order5_primePow_index {G : Type*} [Group G] [Finite G]
    {q k : ℕ} [Fact q.Prime]
    (hcard : Nat.card G = 5 * q ^ k) (hm5 : ¬ (5 ∣ q ^ k))
    (huniq : ∀ d : ℕ, d ∣ q ^ k → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) :
    IsSolvable G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  isSolvable_of_sylow_primePow_index hcard hm5 huniq c hc

/-- **Solvability capstone for order `40`.**  Any finite group of order `40`
containing an element of order `5` is solvable: order `40 = 5·2³`, `5 ∤ 8`, the
divisor condition holds (`6 ∤ 8`), and the quotient of order `8` is a `2`-group,
hence solvable.  This is the solvability counterpart of the order-`40`
non-simplicity capstone — the two together say every such group is a *solvable,
non-simple* group, in particular never the non-solvable `A₅`. -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 40) : IsSolvable G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  isSolvable_of_sylow_primePow_index (p := 5) (q := 2) (k := 3)
    (hcard.trans (by norm_num)) (by norm_num)
    (by
      intro d hd hmod
      rw [show (2 : ℕ) ^ 3 = 8 from by norm_num] at hd
      have := Nat.le_of_dvd (by norm_num) hd
      interval_cases d <;> omega)
    c hc

/-- **Solvability capstone for order `20`.**  Any finite group of order `20`
containing an element of order `5` is solvable: order `20 = 5·2²`, `5 ∤ 4`, the
divisor condition holds (only `1 ∣ 4` is `≡ 1 mod 5`), and the quotient of order
`4` is a `2`-group, hence solvable.  Together with the order-`10` and order-`40`
cases this closes the three candidate Galois-group orders of `x⁵-4x+2`. -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 20) : IsSolvable G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  isSolvable_of_sylow_primePow_index (p := 5) (q := 2) (k := 2)
    (hcard.trans (by norm_num)) (by norm_num)
    (by
      intro d hd hmod
      rw [show (2 : ℕ) ^ 2 = 4 from by norm_num] at hd
      have := Nat.le_of_dvd (by norm_num) hd
      interval_cases d <;> omega)
    c hc

/-! ### The N/C theorem: `[G : C_G(c)] ∣ p - 1`

The `involution_conj_eq_self_or_inv` dichotomy (`g c g⁻¹ ∈ {c, c⁻¹}` for an
involution `g`) is the order-`2` shadow of a single structural fact.  Because
`⟨c⟩` is a **normal** cyclic subgroup of prime order `p`, conjugation defines a
group homomorphism `G →* MulAut ⟨c⟩`, and `MulAut ⟨c⟩ ≅ (ZMod p)ˣ` is cyclic of
order `φ(p) = p - 1`.  Its kernel is exactly the centralizer `C_G(c)` — an element
acts trivially on `⟨c⟩` iff it commutes with the generator `c` — so the first
isomorphism theorem embeds `G ⧸ C_G(c)` into a group of order `p - 1`, giving

> `[G : C_G(c)] ∣ p - 1`.

This is the classical **N/C theorem** `N_G(⟨c⟩)/C_G(⟨c⟩) ↪ Aut(⟨c⟩)` in the case
where `⟨c⟩` is normal (so `N_G(⟨c⟩) = G`).  It sharpens the `±1` dichotomy to
*arbitrary* element order: the conjugation exponent of any `g` is a `(p-1)`-st
root of unity mod `p`, of which `±1` (order dividing `2`) is only the involution
case handled by `involution_conj_eq_self_or_inv`. -/

/-- **N/C theorem for a normal Sylow `p`-subgroup.**  Under the hypotheses of
`zpowers_sylow_normal`, the centralizer `C_G(c)` of the order-`p` element `c` has
index dividing `p - 1`.  Proof: conjugation gives `G →* MulAut ⟨c⟩` with kernel
`C_G(c)`, and `|MulAut ⟨c⟩| = φ(p) = p - 1` since `⟨c⟩` is cyclic of prime order,
so `[G : C_G(c)] = |range| ∣ p - 1` by the first isomorphism theorem. -/
theorem centralizer_index_dvd_prime_sub_one {G : Type*} [Group G] [Finite G]
    {p : ℕ} [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.centralizer {c}).index ∣ p - 1 := by
  haveI hN : (Subgroup.zpowers c).Normal := zpowers_sylow_normal m hcard hpm huniq c hc
  haveI hcyc : IsCyclic ↥(Subgroup.zpowers c) :=
    (Subgroup.isCyclic_iff_exists_zpowers_eq_top _).mpr ⟨c, rfl⟩
  -- The conjugation action `G →* MulAut ⟨c⟩` has kernel exactly `C_G(c)`.
  have hker : (MulAut.conjNormal (H := Subgroup.zpowers c)).ker
      = Subgroup.centralizer {c} := by
    ext g
    rw [MonoidHom.mem_ker, Subgroup.mem_centralizer_iff]
    constructor
    · -- acting trivially on `⟨c⟩` ⇒ commuting with the generator `c`
      intro hg h hh
      rw [Set.mem_singleton_iff] at hh
      subst hh
      have happ : (MulAut.conjNormal (H := Subgroup.zpowers c) g)
          ⟨c, Subgroup.mem_zpowers c⟩ = ⟨c, Subgroup.mem_zpowers c⟩ := by
        rw [hg]; rfl
      have hval : g * c * g⁻¹ = c := by
        have hcoe := congrArg Subtype.val happ
        rwa [MulAut.conjNormal_apply] at hcoe
      rw [mul_inv_eq_iff_eq_mul] at hval
      exact hval.symm
    · -- commuting with `c` ⇒ acting trivially on all of `⟨c⟩`
      intro hg
      have hcomm : Commute c g := hg c rfl
      apply MulEquiv.ext
      intro h
      apply Subtype.ext
      obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp h.property
      have hgc : Commute g (c ^ k) := hcomm.symm.zpow_right k
      show ((MulAut.conjNormal (H := Subgroup.zpowers c) g) h : G) = (h : G)
      rw [MulAut.conjNormal_apply, ← hk, hgc.eq, mul_assoc, mul_inv_cancel, mul_one]
  -- `|MulAut ⟨c⟩| = φ(p) = p - 1`.
  have hAut : Nat.card (MulAut ↥(Subgroup.zpowers c)) = p - 1 := by
    rw [IsCyclic.card_mulAut, Nat.card_zpowers, hc, Nat.totient_prime hp.out]
  -- First isomorphism theorem: `[G : ker] = |range| ∣ |MulAut ⟨c⟩| = p - 1`.
  have hdvd : (MulAut.conjNormal (H := Subgroup.zpowers c)).ker.index ∣ p - 1 := by
    rw [Subgroup.index_ker, ← hAut]
    exact (MulAut.conjNormal (H := Subgroup.zpowers c)).range.card_subgroup_dvd_card
  rwa [hker] at hdvd

/-- **Fixed prime `5` N/C bound** (`p = 5` specialisation of
`centralizer_index_dvd_prime_sub_one`).  In a finite group of order `5·m` with
`5 ∤ m` and the divisor condition, the centralizer of an order-`5` element has
index dividing `4`.  For the Abel–Ruffini `x⁵-4x+2` application (`c` a 5-cycle in
`S₅`) this is `[G : C_G(c)] ∣ 4`, the index that in fact equals `4`. -/
theorem centralizer_index_dvd_four_order5 {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) :
    (Subgroup.centralizer {c}).index ∣ 4 := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  simpa using centralizer_index_dvd_prime_sub_one m hcard hm5 huniq c hc

end AbelRuffiniSylowElim
