import Mathlib

/-!
# Abel–Ruffini OQ04·OQ01·OQ03 — Factoring the Sylow-elimination lemmas

The verified Abel–Ruffini proof that `x⁵ - 4x + 2` is not solvable by radicals
(`AbelRuffiniOQ04OQ01.lean`) rules out `|Gal| ∈ {10, 20, 40}` with three
essentially **verbatim** `private` lemmas `gal_card_ne_10 / _20 / _40`.  Each is
a Sylow argument on a subgroup `G ≤ S₅` of order `5·m` (`m = 2, 4, 8`):

* the Sylow 5-subgroup `P₅` has order `5` (since `5 ∥ |G|`);
* the number of Sylow 5-subgroups `n₅` divides the index `m` and satisfies
  `n₅ ≡ 1 (mod 5)`, forcing `n₅ = 1`;
* hence `P₅` is **normal** and equals `⟨c⟩` for any order-`5` element `c`,
  so every element normalizes `⟨c⟩`;
* but a transposition cannot normalize a 5-cycle — contradiction.

Only the last bullet is specific to `S₅`.  The first three bullets are a *pure
group-theory* statement depending solely on the **group order** `5·m`.  This
file factors that shared core into a single generic lemma, and — as the
OQ04·OQ01·OQ03·OQ01 follow-up — lifts it **from the fixed prime `5` to an
arbitrary prime `p`**: the truly general statement

> in a finite group of order `p·m` with `p ∤ m` and a "no small Frobenius
> divisor" condition on `m`, the cyclic subgroup generated by an order-`p`
> element is normal.

Generalising the prime is *not* a cosmetic rename: with `p` fixed the two
number-theoretic steps `n_p ≡ 1 (mod p) ⇒ n_p = 1` and `[G:P]·p = p·m ⇒
[G:P] = m` are discharged by `omega`/`interval_cases` on concrete numerals,
whereas for a variable `p` they require `Nat.mod_eq_of_lt` (to evaluate
`1 % p`) and `Nat.eq_of_mul_eq_mul_right` (nonlinear cancellation `omega`
cannot see).  The fixed-`5` lemma is recovered as a one-line corollary.

Everything here is fully abstract (no `Polynomial.Gal`, no permutations) and
avoids `native_decide`, so the file is `0`-sorry / `0`-axiom **verified**.  The
three original orders `10 = 5·2`, `20 = 5·4`, `40 = 5·8` are recovered as the
`example`s at the end, which discharge the divisor hypothesis for `m ∈ {2,4,8}`.

## Main results

* `zpowers_sylow_normal` — **general prime `p`.**  In a finite group of order
  `p·m` with `p ∤ m` and no divisor `d ∣ m`, `d ≡ 1 (mod p)` other than
  `d = 1`, the cyclic subgroup generated by any order-`p` element is normal.
* `conj_mem_zpowers_sylow` — consequently every element normalizes `⟨c⟩`.
* `zpowers_order5_normal` / `conj_mem_zpowers_order5` — the `p = 5`
  specialisations feeding the Abel–Ruffini `x⁵-4x+2` proof, now one-liners.
* `mem_center_of_coprime_index` — class-equation centrality criterion: if the
  index `m` is coprime to `p − 1`, the order-`p` element `c` is central.
* `isSolvable_of_sylow_primePow_index` — solvability whenever `m = q^k`.
* `isNilpotent_of_sylow_central_primePow_index` — the **sharp** strengthening: in
  the coprime regime `gcd(q^k, p − 1) = 1` the central Sylow subgroup makes `G`
  *nilpotent*, not merely solvable (the Abel–Ruffini orders `20, 40` sit on the
  non-coprime side, where nilpotency fails: `F₂₀` is solvable but not nilpotent).
-/

namespace AbelRuffiniSylowElim

open scoped Classical

/-- **Generic Sylow-elimination core (arbitrary prime).**

In a finite group `G` of order `p·m`, where `p` is prime, `p ∤ m`, and the only
divisor `d` of `m` with `d ≡ 1 (mod p)` is `d = 1`, the Sylow `p`-subgroup is
unique, hence normal, and equals `⟨c⟩` for any element `c` of order `p`.
Therefore `⟨c⟩` is a normal subgroup.

This is the shared skeleton of the three `private` lemmas
`gal_card_ne_10 / _20 / _40` in the verified Abel–Ruffini `x⁵-4x+2` proof,
lifted to an arbitrary group **and an arbitrary prime**, parameterized by the
order `p·m`. -/
theorem zpowers_sylow_normal {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.zpowers c).Normal := by
  haveI : Fintype G := Fintype.ofFinite G
  have hm0 : m ≠ 0 := by rintro rfl; exact hpm (dvd_zero p)
  -- A Sylow `p`-subgroup has order exactly `p`, since `p ∥ |G|`.
  obtain ⟨P₅⟩ := Sylow.nonempty (p := p) (G := G)
  have hP_card : Nat.card (↑P₅ : Subgroup G) = p := by
    have hppart : (p * m).factorization p = 1 := by
      rw [Nat.factorization_mul hp.out.pos.ne' hm0, Finsupp.add_apply,
        hp.out.factorization, Finsupp.single_eq_same,
        Nat.factorization_eq_zero_of_not_dvd hpm]
    rw [P₅.card_eq_multiplicity, hcard, hppart, pow_one]
  -- Sylow's third theorem: `n_p ∣ m` and `n_p ≡ 1 (mod p)`, forcing `n_p = 1`.
  have hsylow_one : Nat.card (Sylow p G) = 1 := by
    have h_mod := card_sylow_modEq_one p G
    have h_idx : (↑P₅ : Subgroup G).index = m := by
      have hh := (↑P₅ : Subgroup G).index_mul_card
      rw [hP_card, hcard] at hh
      exact Nat.eq_of_mul_eq_mul_right hp.out.pos (by rw [hh]; ring)
    have h_dvd := Sylow.card_dvd_index P₅
    rw [h_idx] at h_dvd
    rw [Nat.ModEq, Nat.mod_eq_of_lt hp.out.one_lt] at h_mod
    exact huniq _ h_dvd h_mod
  -- Uniqueness ⇒ the Sylow `p`-subgroup is normal.
  haveI : Subsingleton (Sylow p G) := by
    haveI := Fintype.ofFinite (Sylow p G)
    rw [← Fintype.card_le_one_iff_subsingleton, ← Nat.card_eq_fintype_card]; omega
  haveI hNP : (↑P₅ : Subgroup G).Normal := by
    apply Subgroup.Normal.mk; intro n hn g
    have hs : g • P₅ = P₅ := Subsingleton.elim _ _
    rw [Sylow.smul_eq_iff_mem_normalizer] at hs
    exact ((Subgroup.mem_normalizer_iff.mp hs) n).mp hn
  -- `⟨c⟩` is a subgroup of order `p`, hence equal to the (unique) `P₅`.
  have hc_P5 : c ∈ (↑P₅ : Subgroup G) := by
    have h_pg : IsPGroup p (Subgroup.zpowers c) :=
      IsPGroup.iff_card.mpr ⟨1, by rw [pow_one, Nat.card_zpowers, hc]⟩
    obtain ⟨Q, hQ⟩ := h_pg.exists_le_sylow
    exact (Subsingleton.elim Q P₅ : Q = P₅) ▸ hQ (Subgroup.mem_zpowers c)
  have hzpow_le : Subgroup.zpowers c ≤ ↑P₅ := fun x hx => by
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
    exact (↑P₅ : Subgroup G).zpow_mem hc_P5 k
  have hP5_eq : (↑P₅ : Subgroup G) = Subgroup.zpowers c := by
    apply le_antisymm _ hzpow_le
    intro x hx
    have hbij : Function.Bijective (Subgroup.inclusion hzpow_le) := by
      haveI := Fintype.ofFinite ↥(↑P₅ : Subgroup G)
      haveI := Fintype.ofFinite ↥(Subgroup.zpowers c)
      exact (Fintype.bijective_iff_injective_and_card _).mpr
        ⟨Subgroup.inclusion_injective _, by
          rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card,
              Nat.card_zpowers, hc, hP_card]⟩
    obtain ⟨⟨y, hy⟩, hxy⟩ := hbij.surjective ⟨x, hx⟩
    rwa [show y = x from congr_arg Subtype.val hxy] at hy
  -- Transport normality along `P₅ = ⟨c⟩`.
  rwa [hP5_eq] at hNP

/-- Consequence of `zpowers_sylow_normal`: under the same hypotheses, **every**
element `g` normalizes `⟨c⟩`, i.e. `g c g⁻¹ ∈ ⟨c⟩`. -/
theorem conj_mem_zpowers_sylow {G : Type*} [Group G] [Finite G] {p : ℕ}
    [Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (g : G) :
    g * c * g⁻¹ ∈ Subgroup.zpowers c :=
  (zpowers_sylow_normal m hcard hpm huniq c hc).conj_mem c (Subgroup.mem_zpowers c) g

/-- **Abstract "an involution acts by inversion" step.**

Under the hypotheses of `zpowers_sylow_normal` (so `⟨c⟩` is normal of prime order
`p`), any *involution* `g` — an element with `g * g = 1`, in particular any
transposition once `G ↪ S₅` — conjugates `c` either to itself or to its inverse:

    `g * c * g⁻¹ = c    ∨    g * c * g⁻¹ = c⁻¹`.

This is the abstract heart of the final, `S₅`-specific bullet of the three
`gal_card_ne_10 / _20 / _40` lemmas ("a transposition cannot normalize a 5-cycle"):
conjugation by `g` normalizes `⟨c⟩`, so `g c g⁻¹ = c ^ k` for some `k : ℤ`;
conjugating a second time and using `g * g = 1` gives `c ^ (k*k) = c`, whence
`k*k ≡ 1 (mod p)`; as `p` is prime, `p ∣ (1-k)(1+k)` forces `k ≡ ±1 (mod p)`, i.e.
`c ^ k = c` or `c⁻¹`. (The concrete step then observes that a genuine transposition
conjugates a 5-cycle to a different 5-cycle, ruling out *both* alternatives — but
that part needs the permutation structure and lives in the concrete proof.) -/
theorem involution_conj_eq_self_or_inv {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) {g : G} (hg : g * g = 1) :
    g * c * g⁻¹ = c ∨ g * c * g⁻¹ = c⁻¹ := by
  -- `g c g⁻¹ ∈ ⟨c⟩`, so `g c g⁻¹ = c ^ k` for some `k : ℤ`.
  obtain ⟨k, hk⟩ :=
    Subgroup.mem_zpowers_iff.mp (conj_mem_zpowers_sylow m hcard hpm huniq c hc g)
  -- Conjugating `c ^ k` by `g` again returns `c`, using `g * g = 1`.
  have hconj2 : g * c ^ k * g⁻¹ = c := by
    rw [hk]
    have : g * (g * c * g⁻¹) * g⁻¹ = (g * g) * c * (g⁻¹ * g⁻¹) := by group
    rw [this, hg]
    have hg' : g⁻¹ * g⁻¹ = 1 := by rw [← mul_inv_rev, hg, inv_one]
    rw [hg', one_mul, mul_one]
  -- Conjugation is an automorphism, so it commutes with taking the `k`-th power.
  have hpow : g * c ^ k * g⁻¹ = (g * c * g⁻¹) ^ k := by
    simpa [MulAut.conj_apply] using (map_zpow (MulAut.conj g) c k)
  -- Combine: `c = (c ^ k) ^ k = c ^ (k * k)`.
  rw [hpow, ← hk, ← zpow_mul] at hconj2
  have hkey : c ^ (k * k) = c ^ (1 : ℤ) := by rw [zpow_one]; exact hconj2
  -- `k * k ≡ 1 (mod p)`.
  rw [zpow_eq_zpow_iff_modEq, hc] at hkey
  have hdvd : (p : ℤ) ∣ (1 - k) * (1 + k) := by
    have h := (Int.modEq_iff_dvd.mp hkey)
    calc (p : ℤ) ∣ 1 - k * k := h
      _ = (1 - k) * (1 + k) := by ring
  haveI hp_int : Prime (p : ℤ) := Int.prime_iff_natAbs_prime.mpr (by simpa using hp.out)
  rcases hp_int.dvd_mul.mp hdvd with h1 | h2
  · -- `k ≡ 1 (mod p)` ⇒ `c ^ k = c`.
    left
    have : k ≡ 1 [ZMOD p] := Int.modEq_iff_dvd.mpr h1
    have hck : c ^ k = c ^ (1 : ℤ) := zpow_eq_zpow_iff_modEq.mpr (by rw [hc]; exact this)
    rw [hk] at hck
    rw [hck, zpow_one]
  · -- `k ≡ -1 (mod p)` ⇒ `c ^ k = c⁻¹`.
    right
    have : k ≡ -1 [ZMOD p] := Int.modEq_iff_dvd.mpr (by
      have : (p : ℤ) ∣ 1 + k := h2
      rwa [show (-1 : ℤ) - k = -(1 + k) by ring, dvd_neg])
    have hck : c ^ k = c ^ (-1 : ℤ) := zpow_eq_zpow_iff_modEq.mpr (by rw [hc]; exact this)
    rw [hk] at hck
    rw [hck, zpow_neg_one]

/-! ### From involutions to arbitrary automorphism order

The involution step `involution_conj_eq_self_or_inv` handles `g` with `g * g = 1`:
the conjugation exponent `k` (with `g c g⁻¹ = c ^ k`) then satisfies `k² ≡ 1 (mod p)`,
so `k ≡ ±1`.  The genuine content is *automorphism-order-agnostic*: conjugation by `g`
is an automorphism of the cyclic group `⟨c⟩`, i.e. an element of `Aut(⟨c⟩) ≅ (ℤ/p)ˣ`,
and its order divides the order of `g`.  We make this precise below by iterating the
conjugation: for **any** `g` with `g ^ n = 1`, the exponent obeys `k ^ n ≡ 1 (mod p)`
(the involution lemma is exactly `n = 2`, where primality upgrades `k² ≡ 1` to `k ≡ ±1`). -/

/-- **Conjugation iterates the exponent.**  If conjugation by `g` sends `c` to the
power `c ^ k`, then conjugation by `g ^ j` sends `c` to `c ^ (k ^ j)`.  This is pure
group theory — no finiteness, no Sylow hypotheses: conjugation is an automorphism, so
it commutes with taking `ℤ`-powers, and iterating `j` times multiplies the exponent
`j`-fold. -/
theorem conj_pow_eq_zpow_pow {G : Type*} [Group G] (c g : G) {k : ℤ}
    (hk : g * c * g⁻¹ = c ^ k) :
    ∀ j : ℕ, g ^ j * c * (g ^ j)⁻¹ = c ^ (k ^ j) := by
  intro j
  induction j with
  | zero => simp
  | succ j ih =>
    -- conjugation by `g` commutes with the `ℤ`-power `(k ^ j)`.
    have hconj : g * (c ^ (k ^ j)) * g⁻¹ = (g * c * g⁻¹) ^ (k ^ j) := by
      simpa [MulAut.conj_apply] using (map_zpow (MulAut.conj g) c (k ^ j))
    calc g ^ (j + 1) * c * (g ^ (j + 1))⁻¹
        = g * (g ^ j * c * (g ^ j)⁻¹) * g⁻¹ := by rw [pow_succ']; group
      _ = g * (c ^ (k ^ j)) * g⁻¹ := by rw [ih]
      _ = (g * c * g⁻¹) ^ (k ^ j) := hconj
      _ = (c ^ k) ^ (k ^ j) := by rw [hk]
      _ = c ^ (k ^ (j + 1)) := by rw [← zpow_mul, ← pow_succ']

/-- **The conjugation exponent has modular order dividing `orderOf g`.**

Under the hypotheses of `zpowers_sylow_normal`, conjugation by any `g` with `g ^ n = 1`
sends `c` to `c ^ k` for a unique-mod-`p` exponent `k`, and that exponent satisfies
`k ^ n ≡ 1 (mod p)`.  Equivalently, viewing conjugation as an element of `Aut(⟨c⟩) ≅
(ℤ/p)ˣ`, its multiplicative order divides the order of `g`.  This is the automorphism-
order-agnostic generalisation of `involution_conj_eq_self_or_inv`, which is the special
case `n = 2`: there `k² ≡ 1 (mod p)` combines with the primality of `p` to force
`k ≡ ±1`, i.e. `g c g⁻¹ ∈ {c, c⁻¹}`. -/
theorem conj_exponent_pow_modEq_one {G : Type*} [Group G] [Finite G] {p : ℕ}
    [Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) {g : G} {n : ℕ} (hg : g ^ n = 1) :
    ∃ k : ℤ, g * c * g⁻¹ = c ^ k ∧ k ^ n ≡ 1 [ZMOD (p : ℤ)] := by
  obtain ⟨k, hk⟩ :=
    Subgroup.mem_zpowers_iff.mp (conj_mem_zpowers_sylow m hcard hpm huniq c hc g)
  refine ⟨k, hk.symm, ?_⟩
  -- iterate the conjugation `n` times; `g ^ n = 1` collapses the left-hand side to `c`.
  have hiter := conj_pow_eq_zpow_pow c g hk.symm n
  rw [hg] at hiter
  simp only [one_mul, inv_one, mul_one] at hiter
  -- `hiter : c = c ^ (k ^ n)`, so `c ^ (k ^ n) = c ^ (1 : ℤ)`.
  have hcc : c ^ (k ^ n) = c ^ (1 : ℤ) := by rw [zpow_one, ← hiter]
  rwa [zpow_eq_zpow_iff_modEq, hc] at hcc

/-! ### The N/C bound: the centralizer of `c` has index dividing `p - 1`

The per-element lemma `conj_exponent_pow_modEq_one` says conjugation by a *single* `g`
lands in `Aut(⟨c⟩) ≅ (ℤ/p)ˣ`.  Packaging that over **all** of `G` at once is exactly
Mathlib's conjugation action on a normal subgroup, `MulAut.conjNormal : G →* MulAut ⟨c⟩`.
Its kernel is the centralizer `C_G(c)` (an element acts trivially on the cyclic group
`⟨c⟩` iff it commutes with the generator `c`), and its image is a subgroup of the cyclic
automorphism group `Aut(⟨c⟩) ≅ (ℤ/p)ˣ`, which has order `φ(p) = p - 1`.  Noether's first
isomorphism theorem identifies `[G : C_G(c)]` with the order of that image, and Lagrange
bounds it:

    `[G : C_G(c)]  ∣  p - 1`.

Equivalently, the conjugacy class of `c` has size dividing `p - 1`.  This is the sharp
"normalizer/centralizer" (N/C) refinement of the earlier ±1 involution lemma: an
involution only forces the exponent into `{±1}` (order dividing `2`), whereas the full
centralizer index is constrained by the *entire* automorphism group `(ℤ/p)ˣ`. -/

/-- **The kernel of the conjugation action on `⟨c⟩` is the centralizer of `c`.**  An
element `g` acts trivially on the normal cyclic subgroup `⟨c⟩` (i.e. `conjNormal g = 1`)
iff it fixes the generator `c` under conjugation, i.e. commutes with `c`.  No finiteness
or order hypothesis is needed — only that `⟨c⟩` is normal, so that `conjNormal` exists. -/
theorem conjNormal_ker_eq_centralizer {G : Type*} [Group G] (c : G)
    [(Subgroup.zpowers c).Normal] :
    (MulAut.conjNormal (H := Subgroup.zpowers c)).ker = Subgroup.centralizer {c} := by
  ext g
  rw [MonoidHom.mem_ker, Subgroup.mem_centralizer_iff]
  constructor
  · -- `conjNormal g = 1` fixes `c`, so `g c g⁻¹ = c`, hence `c g = g c`.
    intro hg m hm
    rw [Set.mem_singleton_iff] at hm; rw [hm]
    have hx : (MulAut.conjNormal g) (⟨c, Subgroup.mem_zpowers c⟩ : Subgroup.zpowers c)
        = ⟨c, Subgroup.mem_zpowers c⟩ := by rw [hg]; rfl
    have key : g * c * g⁻¹ = c := by
      have h2 := congrArg Subtype.val hx
      rwa [MulAut.conjNormal_apply] at h2
    exact (mul_inv_eq_iff_eq_mul.mp key).symm
  · -- `g` commutes with `c`, hence with every `c ^ k`, so it acts trivially on `⟨c⟩`.
    intro hg
    have hcomm : Commute c g := hg c (Set.mem_singleton c)
    apply MulEquiv.ext
    rintro ⟨x, hx⟩
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
    apply Subtype.ext
    show g * c ^ k * g⁻¹ = c ^ k
    rw [(hcomm.zpow_left k).eq.symm]
    group

/-- **N/C index bound (kernel form).**  Given a normal cyclic subgroup `⟨c⟩` of prime
order `p`, the image of the conjugation homomorphism `G →* Aut(⟨c⟩)` sits inside the
cyclic group `Aut(⟨c⟩) ≅ (ℤ/p)ˣ` of order `p - 1`, so — by Noether's first isomorphism
theorem and Lagrange — the index of its kernel divides `p - 1`.  The normality of `⟨c⟩`
is taken as an instance hypothesis so that the conjugation map exists in the statement;
`centralizer_index_dvd_sub_one` discharges it from the Sylow hypotheses. -/
theorem conjNormal_ker_index_dvd_sub_one {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (c : G) (hc : orderOf c = p)
    [(Subgroup.zpowers c).Normal] :
    (MulAut.conjNormal (H := Subgroup.zpowers c)).ker.index ∣ p - 1 := by
  haveI : IsCyclic (Subgroup.zpowers c) :=
    (Subgroup.zpowers c).isCyclic_iff_exists_zpowers_eq_top.mpr ⟨c, rfl⟩
  -- `|Aut(⟨c⟩)| = φ(p) = p - 1`.
  have hcardH : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  have hAut : Nat.card (MulAut (Subgroup.zpowers c)) = p - 1 := by
    rw [IsCyclic.card_mulAut, hcardH, Nat.totient_prime hp.out]
  -- `[G : ker] = |range|` (first iso), and `|range| ∣ |Aut(⟨c⟩)|` (Lagrange).
  have hidx : (MulAut.conjNormal (H := Subgroup.zpowers c)).ker.index
      = Nat.card ((MulAut.conjNormal (H := Subgroup.zpowers c)).range) := by
    rw [Subgroup.index_eq_card,
      Nat.card_congr (QuotientGroup.quotientKerEquivRange _).toEquiv]
  rw [hidx, ← hAut]
  exact Subgroup.card_subgroup_dvd_card _

/-- **N/C bound: the index of the centralizer of `c` divides `p - 1`.**

Under the hypotheses of `zpowers_sylow_normal`, the cyclic subgroup `⟨c⟩` of prime order
`p` is normal, and conjugation gives a homomorphism `G →* Aut(⟨c⟩)` whose kernel is the
centralizer `C_G(c)` and whose image lies in `Aut(⟨c⟩) ≅ (ℤ/p)ˣ`, a group of order
`p - 1`.  Hence `[G : C_G(c)]` divides `p - 1`; equivalently the conjugacy class of `c`
has size dividing `p - 1`.  This is the structural culmination of the involution ±1 lemma
— the full automorphism-group constraint rather than the order-`2` special case. -/
theorem centralizer_index_dvd_sub_one {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.centralizer {c}).index ∣ p - 1 := by
  haveI : (Subgroup.zpowers c).Normal := zpowers_sylow_normal m hcard hpm huniq c hc
  rw [← conjNormal_ker_eq_centralizer c]
  exact conjNormal_ker_index_dvd_sub_one c hc

/-- **Reusable sufficient condition for the divisor hypothesis `huniq`.** If the
index `m` is smaller than the prime `p`, then the only divisor `d ∣ m` with
`d ≡ 1 (mod p)` is `d = 1`: any such `d` satisfies `d ≤ m < p`, so `d % p = d`, and
`d % p = 1` gives `d = 1`. This discharges the `huniq` hypothesis uniformly for every
index below `p` (in the Abel–Ruffini application, `m = 2` and `m = 4` are `< 5`; only
`m = 8 > 5` genuinely needs the divisibility, as `6 ≡ 1 (mod 5)` but `6 ∤ 8`). -/
theorem huniq_of_lt {p m : ℕ} (hm0 : 0 < m) (hmp : m < p) :
    ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1 := by
  intro d hd hmod
  have hdm : d ≤ m := Nat.le_of_dvd hm0 hd
  have hdp : d < p := lt_of_le_of_lt hdm hmp
  rwa [Nat.mod_eq_of_lt hdp] at hmod

/-! ### Structural consequence: the group is not simple

The whole point of a *normal* Sylow `p`-subgroup is structural: it is a proper,
nontrivial normal subgroup, so the ambient group is **not simple**.  This is
precisely why the Galois groups arising from `x⁵-4x+2` (orders `10, 20, 40`)
cannot be the simple `A₅`, and — more generally — why the "order `p·m`" obstruction
argument never produces a simple group.  A non-simple finite group has a nontrivial
proper normal subgroup, the first ingredient of a composition/derived series, so
these results feed directly into solvability-by-radicals arguments for higher-degree
extensions. -/

/-- **The index of `⟨c⟩` equals `m`** (equivalently, the quotient `G ⧸ ⟨c⟩` has
order `m`).  Pure counting: `|⟨c⟩| = orderOf c = p` and `[G:⟨c⟩]·|⟨c⟩| = |G| = p·m`,
so cancel the prime `p`.  Needs neither the divisor hypothesis nor normality. -/
theorem zpowers_index_eq {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ) (hcard : Nat.card G = p * m)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.zpowers c).index = m := by
  have hcard_zc : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  have hh := (Subgroup.zpowers c).index_mul_card
  rw [hcard_zc, hcard] at hh
  exact Nat.eq_of_mul_eq_mul_right hp.out.pos (by rw [hh]; ring)

/-- **Non-simplicity from a normal Sylow `p`-subgroup (arbitrary prime).**

Under the hypotheses of `zpowers_sylow_normal` together with `1 < m`, the cyclic
group `⟨c⟩` is a normal subgroup that is neither trivial (it has prime order `p`)
nor everything (its index is `m > 1`), so `G` is **not simple**.  In particular no
group carrying this "order `p·m`, `p ∤ m`, no small Frobenius divisor" structure can
be a nonabelian simple group such as `A₅`. -/
theorem not_isSimpleGroup_of_sylow {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1) (hm : 1 < m)
    (c : G) (hc : orderOf c = p) :
    ¬ IsSimpleGroup G := by
  intro hsimple
  haveI := hsimple
  have hN := zpowers_sylow_normal m hcard hpm huniq c hc
  rcases IsSimpleGroup.eq_bot_or_eq_top_of_normal (Subgroup.zpowers c) hN with hb | ht
  · -- `⟨c⟩ = ⊥` would force `c = 1`, contradicting `orderOf c = p > 1`.
    rw [Subgroup.zpowers_eq_bot] at hb
    rw [hb, orderOf_one] at hc
    exact absurd hc.symm hp.out.one_lt.ne'
  · -- `⟨c⟩ = ⊤` would force index `1 = m`, contradicting `1 < m`.
    have hidx := zpowers_index_eq m hcard c hc
    rw [ht, Subgroup.index_top] at hidx
    omega

/-! ### Conjugacy-class-size form of the N/C bound

The index `[G : C_G(c)]` is, by the orbit–stabilizer theorem, exactly the size of the
conjugacy class of `c`: conjugation makes `G` act on itself (`MulAction (ConjAct G) G`),
the orbit of `c` is its conjugacy class, and the stabilizer is the centralizer `C_G(c)`.
So the N/C bound `[G:C_G(c)] ∣ p−1` translates verbatim into a bound on the number of
conjugates of `c`:

    `|conjugacy class of c|  =  [G : C_G(c)]  ∣  p − 1`.

This is the class-equation-facing reading of the same fact: in a group of order `p·m`
with a normal Sylow `p`-subgroup `⟨c⟩`, every order-`p` element sits in a conjugacy class
whose size divides `p − 1` (hence `≤ p − 1`). -/

/-- **Orbit–stabilizer identity: the conjugacy class of `c` has size `[G : C_G(c)]`.**
The orbit of `c` under the conjugation action `ConjAct G ↷ G` is its conjugacy class, and
by the orbit–stabilizer theorem its cardinality is the index of the stabilizer, which is
the centralizer `C_G(c)`.  Pure group theory — no finiteness or order hypothesis. -/
theorem orbit_conjAct_card_eq_centralizer_index {G : Type*} [Group G] (c : G) :
    Nat.card (MulAction.orbit (ConjAct G) c) = (Subgroup.centralizer {c}).index := by
  rw [Nat.card_congr (MulAction.orbitEquivQuotientStabilizer (ConjAct G) c),
    ← Subgroup.index_eq_card, Subgroup.centralizer_eq_comap_stabilizer c,
    Subgroup.index_comap_of_surjective _ (ConjAct.toConjAct (G := G)).surjective]

/-- **N/C bound, conjugacy-class form.**  Under the hypotheses of `zpowers_sylow_normal`,
the number of conjugates of the order-`p` element `c` — the size of its conjugacy class,
i.e. the orbit of `c` under the conjugation action — divides `p − 1`.  This is the
class-equation-facing restatement of `centralizer_index_dvd_sub_one` via the
orbit–stabilizer theorem: `|conj class of c| = [G : C_G(c)] ∣ p − 1`. -/
theorem conjClass_card_dvd_sub_one {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    Nat.card (MulAction.orbit (ConjAct G) c) ∣ p - 1 := by
  rw [orbit_conjAct_card_eq_centralizer_index]
  exact centralizer_index_dvd_sub_one m hcard hpm huniq c hc

/-! ### The class-equation arithmetic consequence: coprime index forces centrality

The N/C bound `[G : C_G(c)] ∣ p − 1` gained its force from the automorphism group
`Aut(⟨c⟩) ≅ (ℤ/p)ˣ` of order `p − 1`.  There is a *second*, orthogonal constraint on the
same index coming from the subgroup lattice: since `c` commutes with its own powers,
`⟨c⟩ ≤ C_G(c)`, so `[G : C_G(c)]` divides `[G : ⟨c⟩] = m`.  Combining the two:

    `|conj class of c|  =  [G : C_G(c)]  ∣  gcd(m, p − 1)`.

This is the sharp class-equation reading.  Its most striking consequence is a **centrality
criterion**: whenever the index `m` and `p − 1` are *coprime*, the gcd is `1`, the
conjugacy class of `c` is a singleton, and `c` is central.  Equivalently: an order-`p`
element whose index is coprime to `p − 1` cannot be moved by conjugation — it lies in the
centre `Z(G)`.  (This is the elementary transfer-theoretic phenomenon behind Burnside's
normal `p`-complement theorem read for a single element: no automorphism of `⟨c⟩` of order
dividing `p − 1` can be realised by conjugation when the available conjugating room `m` is
coprime to `p − 1`.) -/

/-- **`⟨c⟩` centralises `c`.**  Every power of `c` commutes with `c`, so the cyclic
subgroup `⟨c⟩` is contained in the centralizer `C_G(c)`.  Pure group theory. -/
theorem zpowers_le_centralizer {G : Type*} [Group G] (c : G) :
    Subgroup.zpowers c ≤ Subgroup.centralizer {c} := by
  intro x hx
  rw [Subgroup.mem_centralizer_iff]
  rintro y hy
  rw [Set.mem_singleton_iff] at hy; subst hy
  obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
  exact (Commute.refl y).zpow_right k

/-- **The centralizer index also divides `m`.**  Because `⟨c⟩ ≤ C_G(c)` and
`[G : ⟨c⟩] = m`, the tower law gives `[G : C_G(c)] ∣ m`.  This is the lattice-side
constraint on the conjugacy-class size, complementary to the automorphism-group bound
`[G : C_G(c)] ∣ p − 1`.  Needs only the order hypothesis, not `huniq`. -/
theorem centralizer_index_dvd_index_zpowers {G : Type*} [Group G] [Finite G] {p : ℕ}
    [Fact p.Prime] (m : ℕ) (hcard : Nat.card G = p * m)
    (c : G) (hc : orderOf c = p) :
    (Subgroup.centralizer {c}).index ∣ m := by
  have h := Subgroup.index_dvd_of_le (zpowers_le_centralizer c)
  rwa [zpowers_index_eq m hcard c hc] at h

/-- **Conjugacy class size divides `gcd(m, p − 1)`.**  Sharpens `conjClass_card_dvd_sub_one`:
the size of the conjugacy class of `c` divides *both* the index `m` (lattice constraint) and
`p − 1` (automorphism-group constraint), hence their gcd.  This is the tightest per-element
bound the class equation supplies here. -/
theorem conjClass_card_dvd_gcd {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    Nat.card (MulAction.orbit (ConjAct G) c) ∣ Nat.gcd m (p - 1) := by
  rw [orbit_conjAct_card_eq_centralizer_index]
  exact Nat.dvd_gcd (centralizer_index_dvd_index_zpowers m hcard c hc)
    (centralizer_index_dvd_sub_one m hcard hpm huniq c hc)

/-- **Centrality criterion: coprime index forces `c` central.**

Under the hypotheses of `zpowers_sylow_normal`, if the index `m = [G : ⟨c⟩]` is *coprime*
to `p − 1`, then the order-`p` element `c` lies in the centre `Z(G)`.  Indeed the
conjugacy class of `c` has size dividing `gcd(m, p − 1) = 1`, so the class is a singleton,
i.e. `C_G(c) = G`.  This is the class-equation punchline: the only way an order-`p` element
can *avoid* being central is for its index to share a common factor with `p − 1`; the
Abel–Ruffini orders `20 = 5·4`, `40 = 5·8` (with `gcd(4, 4) = 4`, `gcd(8, 4) = 4`) live
precisely in the non-coprime regime where non-central order-`5` elements are possible. -/
theorem mem_center_of_coprime_index {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime m (p - 1)) :
    c ∈ Subgroup.center G := by
  have hgcd1 : Nat.gcd m (p - 1) = 1 := hcop
  have hdvd : (Subgroup.centralizer {c}).index ∣ Nat.gcd m (p - 1) :=
    Nat.dvd_gcd (centralizer_index_dvd_index_zpowers m hcard c hc)
      (centralizer_index_dvd_sub_one m hcard hpm huniq c hc)
  rw [hgcd1] at hdvd
  have htop : Subgroup.centralizer {c} = ⊤ :=
    Subgroup.index_eq_one.mp (Nat.dvd_one.mp hdvd)
  rw [Subgroup.mem_center_iff]
  intro g
  have hg : g ∈ Subgroup.centralizer {c} := htop ▸ Subgroup.mem_top g
  exact (Subgroup.mem_centralizer_iff.mp hg c (Set.mem_singleton c)).symm

/-! ### Global structure: central Sylow-`p`, `p ∣ |Z(G)|`, and the internal direct product

The single-element centrality criterion `mem_center_of_coprime_index` promotes to a statement
about the *whole* Sylow `p`-subgroup.  Three global consequences follow.

* **Central Sylow.**  When `gcd(m, p−1) = 1` every power of `c` is central, so `⟨c⟩ ≤ Z(G)`
  (`zpowers_le_center_of_coprime_index`).
* **Class-number divisibility.**  Lagrange applied to `⟨c⟩ ≤ Z(G)` forces `p ∣ |Z(G)|`
  (`prime_dvd_card_center_of_coprime_index`): the centre is large — its order a multiple of `p`.
* **Internal direct product.**  Since `p ∤ m`, Schur–Zassenhaus supplies a complement `H` of order
  `m` to the normal subgroup `⟨c⟩` (`exists_pComplement`).  When `⟨c⟩` is central this complement is
  itself normal, exhibiting `G` as the internal direct product `⟨c⟩ × H` of its central Sylow
  `p`-subgroup and a normal `p`-complement (`exists_normal_pComplement_of_coprime_index`).  This is
  the structural endgame: in the coprime-index regime the order-`p` part splits off as a *central*
  direct factor — the elementary content of Burnside's normal `p`-complement theorem read here. -/

/-- **Central Sylow: `⟨c⟩ ≤ Z(G)` under coprime index.**  Promotes the single-element criterion
`mem_center_of_coprime_index` to the whole cyclic Sylow `p`-subgroup: if the index `m = [G:⟨c⟩]`
is coprime to `p − 1`, then every power of `c` is central, i.e. `⟨c⟩ ≤ Z(G)`. -/
theorem zpowers_le_center_of_coprime_index {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime m (p - 1)) :
    Subgroup.zpowers c ≤ Subgroup.center G :=
  Subgroup.zpowers_le.mpr (mem_center_of_coprime_index m hcard hpm huniq c hc hcop)

/-- **`p ∣ |Z(G)|` under coprime index.**  Because the order-`p` subgroup `⟨c⟩` sits inside the
centre (`zpowers_le_center_of_coprime_index`), Lagrange's theorem forces `p = |⟨c⟩|` to divide the
order of the centre.  In particular `Z(G)` is nontrivial and its order is a multiple of `p`. -/
theorem prime_dvd_card_center_of_coprime_index {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime m (p - 1)) :
    p ∣ Nat.card (Subgroup.center G) := by
  have hdvd := Subgroup.card_dvd_of_le
    (zpowers_le_center_of_coprime_index m hcard hpm huniq c hc hcop)
  rwa [Nat.card_zpowers, hc] at hdvd

/-- **Schur–Zassenhaus `p`-complement.**  Since `p ∤ m`, the orders `p = |⟨c⟩|` and `m = [G:⟨c⟩]`
are coprime, so the normal subgroup `⟨c⟩` admits a complement `H`: a subgroup with `⟨c⟩ ⊓ H = 1`
and `⟨c⟩·H = G`.  Counting the complement gives `|H| = m`.  This is the `p`-complement existence
statement; it needs only `p ∤ m`, not the coprime-index hypothesis. -/
theorem exists_pComplement {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    ∃ H : Subgroup G, Subgroup.IsComplement' (Subgroup.zpowers c) H ∧ Nat.card H = m := by
  haveI : (Subgroup.zpowers c).Normal := zpowers_sylow_normal m hcard hpm huniq c hc
  have hNcard : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  have hNidx : (Subgroup.zpowers c).index = m := zpowers_index_eq m hcard c hc
  have hcop : Nat.Coprime (Nat.card (Subgroup.zpowers c)) (Subgroup.zpowers c).index := by
    rw [hNcard, hNidx]; exact hp.out.coprime_iff_not_dvd.mpr hpm
  obtain ⟨H, hH⟩ := Subgroup.exists_right_complement'_of_coprime hcop
  refine ⟨H, hH, ?_⟩
  have hmul := hH.card_mul
  rw [hNcard, hcard] at hmul
  exact Nat.eq_of_mul_eq_mul_left hp.out.pos hmul

/-- **Internal direct product `G = ⟨c⟩ × H`.**  Combining the central-Sylow result with the
Schur–Zassenhaus complement: when `gcd(m, p−1) = 1`, the complement `H` of the (now central)
subgroup `⟨c⟩` is itself *normal*, so `G` is the internal direct product of its central Sylow
`p`-subgroup `⟨c⟩` and a normal `p`-complement `H` of order `m`.  A central normal Hall subgroup
splits off as a direct factor — the structural endgame of the coprime-index analysis. -/
theorem exists_normal_pComplement_of_coprime_index {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime m (p - 1)) :
    ∃ H : Subgroup G, H.Normal ∧ Subgroup.IsComplement' (Subgroup.zpowers c) H ∧
      Nat.card H = m := by
  obtain ⟨H, hHc, hHcard⟩ := exists_pComplement m hcard hpm huniq c hc
  have hcen := zpowers_le_center_of_coprime_index m hcard hpm huniq c hc hcop
  refine ⟨H, ⟨?_⟩, hHc, hHcard⟩
  intro x hx g
  -- Factor `g = n · h₀` with `n ∈ ⟨c⟩` (central) and `h₀ ∈ H`.
  have hfact : ∃ n ∈ Subgroup.zpowers c, ∃ h' ∈ H, n * h' = g := by
    obtain ⟨q, hq⟩ := (hHc.existsUnique g).exists
    exact ⟨q.1, SetLike.mem_coe.mp q.1.2, q.2, SetLike.mem_coe.mp q.2.2, hq⟩
  obtain ⟨n, hn_mem, h₀, hh₀_mem, hg⟩ := hfact
  have hncen : n ∈ Subgroup.center G := hcen hn_mem
  -- `n` central ⇒ conjugation by `n` is trivial.
  have hcen_w : n * (h₀ * x * h₀⁻¹) * n⁻¹ = h₀ * x * h₀⁻¹ := by
    have hcomm : n * (h₀ * x * h₀⁻¹) = (h₀ * x * h₀⁻¹) * n :=
      (Subgroup.mem_center_iff.mp hncen (h₀ * x * h₀⁻¹)).symm
    rw [hcomm]; group
  have key : g * x * g⁻¹ = h₀ * x * h₀⁻¹ := by
    rw [← hg, mul_inv_rev,
      (by group : n * h₀ * x * (h₀⁻¹ * n⁻¹) = n * (h₀ * x * h₀⁻¹) * n⁻¹)]
    exact hcen_w
  rw [key]
  exact H.mul_mem (H.mul_mem hh₀_mem hx) (H.inv_mem hh₀_mem)

/-! ### The fixed prime `p = 5`

The original Abel–Ruffini application only needs `p = 5`.  With the general
lemma in hand these become one-liners: instantiate `[Fact (Nat.Prime 5)]` and
apply. -/

/-- **Fixed prime `5` core** (`p = 5` specialisation of `zpowers_sylow_normal`).

In a finite group of order `5·m` where `5 ∤ m` and the only divisor `d` of `m`
with `d ≡ 1 (mod 5)` is `d = 1`, the cyclic subgroup generated by any order-`5`
element is normal.  This is the shared skeleton of the three `private` lemmas
`gal_card_ne_10 / _20 / _40` in the verified Abel–Ruffini `x⁵-4x+2` proof. -/
theorem zpowers_order5_normal {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) :
    (Subgroup.zpowers c).Normal :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  zpowers_sylow_normal m hcard hm5 huniq c hc

/-- Consequence of `zpowers_order5_normal`: under the same hypotheses, **every**
element `g` normalizes `⟨c⟩`, i.e. `g c g⁻¹ ∈ ⟨c⟩`.  This is exactly the shared
`hconj_zpow` step of `gal_card_ne_10 / _20 / _40`. -/
theorem conj_mem_zpowers_order5 {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) (g : G) :
    g * c * g⁻¹ ∈ Subgroup.zpowers c :=
  (zpowers_order5_normal m hcard hm5 huniq c hc).conj_mem c (Subgroup.mem_zpowers c) g

/-- **Fixed prime `5` non-simplicity** (`p = 5` specialisation of
`not_isSimpleGroup_of_sylow`).  A finite group of order `5·m` with `1 < m`,
`5 ∤ m`, the `huniq` divisor condition, and an order-`5` element is not simple —
its normal `⟨c⟩` is a proper nontrivial normal subgroup.  This is exactly the
structural reason the `x⁵-4x+2` Galois groups of order `10, 20, 40` are not the
simple `A₅`. -/
theorem not_isSimpleGroup_order5 {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1) (hm : 1 < m)
    (c : G) (hc : orderOf c = 5) :
    ¬ IsSimpleGroup G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  not_isSimpleGroup_of_sylow m hcard hm5 huniq hm c hc

/-- **Fixed prime `5` centrality criterion** (`p = 5` specialisation of
`mem_center_of_coprime_index`).  In a finite group of order `5·m` with `5 ∤ m`, the
divisor condition, and an order-`5` element `c`, if `m` is coprime to `4 = 5 − 1` (i.e.
`m` is odd), then `c` is central.  The order-`15` groups (`m = 3`) are the smallest
instance: every order-`5` element of a group of order `15` lies in the centre — the
group-theoretic reason all groups of order `15` are cyclic. -/
theorem mem_center_order5_of_coprime_index {G : Type*} [Group G] [Finite G] (m : ℕ)
    (hcard : Nat.card G = 5 * m) (hm5 : ¬ (5 ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) (hcop : Nat.Coprime m 4) :
    c ∈ Subgroup.center G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  mem_center_of_coprime_index m hcard hm5 huniq c hc (by simpa using hcop)

/-- **Order `15` centrality.** Any order-`5` element of a finite group of order `15` is
central: order `15 = 5·3`, `5 ∤ 3`, the divisor condition holds (`3 < 5`), and `3` is
coprime to `4`, so `mem_center_order5_of_coprime_index` applies.  (This is the crux of the
classification of order-`15` groups as cyclic.) -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 15) : c ∈ Subgroup.center G :=
  mem_center_order5_of_coprime_index 3 (hcard.trans (by norm_num)) (by norm_num)
    (huniq_of_lt (by norm_num) (by norm_num)) c hc (by norm_num)

/-! ### Recovering the three original orders `10, 20, 40`

The three `private` lemmas in `AbelRuffiniOQ04OQ01.lean` instantiate the core at
`m = 2` (order `10`), `m = 4` (order `20`), and `m = 8` (order `40`).  Each such
instantiation needs the divisor hypothesis `huniq`, verified here once and for
all for the three relevant indices. -/

/-- Order `10 = 5·2`: the only divisor of `2` that is `≡ 1 (mod 5)` is `1`.
Since `2 < 5`, this is the `huniq_of_lt` case. -/
example : ∀ d : ℕ, d ∣ 2 → d % 5 = 1 → d = 1 := huniq_of_lt (by norm_num) (by norm_num)

/-- Order `20 = 5·4`: the only divisor of `4` that is `≡ 1 (mod 5)` is `1`.
Since `4 < 5`, this is again the `huniq_of_lt` case. -/
example : ∀ d : ℕ, d ∣ 4 → d % 5 = 1 → d = 1 := huniq_of_lt (by norm_num) (by norm_num)

/-- Order `40 = 5·8`: the only divisor of `8` that is `≡ 1 (mod 5)` is `1`.
Note `6 ≡ 1 (mod 5)` but `6 ∤ 8`, so the divisibility hypothesis is essential. -/
example : ∀ d : ℕ, d ∣ 8 → d % 5 = 1 → d = 1 := by
  intro d hd hmod; have := Nat.le_of_dvd (by norm_num) hd; interval_cases d <;> omega

/-- **Capstone.** Any finite group of order `40` containing an element of order `5`
is not simple: order `40 = 5·8`, `5 ∤ 8`, the divisor condition holds (only `1 ∣ 8`
is `≡ 1 mod 5`, as `6 ∤ 8`), and `8 > 1`, so `not_isSimpleGroup_order5` applies. -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 40) : ¬ IsSimpleGroup G :=
  not_isSimpleGroup_order5 8 (hcard.trans (by norm_num)) (by norm_num)
    (by intro d hd hmod; have := Nat.le_of_dvd (by norm_num) hd; interval_cases d <;> omega)
    (by norm_num) c hc

/-! ### Structural consequence: solvability

Non-simplicity is only the first structural payoff of a *normal* Sylow
`p`-subgroup.  The stronger consequence — the one that actually drives
"solvable-by-radicals" — is **solvability**.  The normal subgroup `⟨c⟩` has prime
order `p`, so it is cyclic, abelian, and solvable; a group that is an extension of
a solvable group by a solvable group is itself solvable.  Hence `G` is solvable as
soon as the order-`m` quotient `G ⧸ ⟨c⟩` is.

This is the group-theoretic engine behind the Abel–Ruffini obstruction read the
other way round: the candidate Galois-group orders `10, 20, 40` for `x⁵-4x+2` all
have solvable `⟨c⟩`-quotients (they are `2`-groups), so any group carrying that
order would be *solvable* — whereas the genuine Galois group `A₅` is **not**
solvable.  It is precisely this mismatch that rules those orders out and forces
the group to be `S₅`, the non-solvable obstruction certifying non-solvability by
radicals. -/

/-- **The normal subgroup `⟨c⟩` is solvable** (being cyclic, hence abelian).  A
standalone helper feeding the solvable-extension theorem below; needs no
finiteness or order hypothesis. -/
theorem isSolvable_zpowers {G : Type*} [Group G] (c : G) :
    IsSolvable (Subgroup.zpowers c) := by
  apply isSolvable_of_comm
  rintro ⟨a, ha⟩ ⟨b, hb⟩
  obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp ha
  obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp hb
  exact Subtype.ext (by simpa using zpow_mul_comm c i j)

/-- **General solvable-extension engine.**  If `N` is a normal subgroup with both
`N` and the quotient `G ⧸ N` solvable, then `G` is solvable.  (An extension of a
solvable group by a solvable group is solvable.)  Packages Mathlib's
`solvable_of_ker_le_range` for the inclusion `N ↪ G` and the projection `G ↠ G ⧸ N`,
whose kernel `N` equals the range of the inclusion. -/
theorem isSolvable_of_normal_solvable_quotient {G : Type*} [Group G]
    (N : Subgroup G) [N.Normal] [IsSolvable N] [IsSolvable (G ⧸ N)] :
    IsSolvable G :=
  solvable_of_ker_le_range N.subtype (QuotientGroup.mk' N)
    (le_of_eq (by rw [QuotientGroup.ker_mk', Subgroup.range_subtype]))

/-- **Solvability from a normal Sylow `p`-subgroup with prime-power index.**

Under the hypotheses of `zpowers_sylow_normal`, the cyclic subgroup `⟨c⟩` is a
*normal* subgroup of prime order `p` — hence abelian and solvable — with quotient
`G ⧸ ⟨c⟩` of order `m`.  If moreover the index `m = q^k` is a prime power for some
prime `q`, then the quotient is a finite `q`-group, hence nilpotent, hence solvable,
so `G` itself is solvable by the extension engine.

This is a fully general, self-contained sufficient condition — no separate
solvability input about the quotient is needed, only that its order is a prime
power — and it upgrades the non-simplicity result `not_isSimpleGroup_of_sylow` to
the full solvability statement that feeds radical-tower arguments.  (The `x⁵-4x+2`
orders `10 = 5·2`, `20 = 5·2²`, `40 = 5·2³` are exactly this case with `q = 2`.) -/
theorem isSolvable_of_sylow_primePow_index {G : Type*} [Group G] [Finite G]
    {p q k : ℕ} [Fact p.Prime] [Fact q.Prime]
    (hcard : Nat.card G = p * q ^ k) (hpm : ¬ (p ∣ q ^ k))
    (huniq : ∀ d : ℕ, d ∣ q ^ k → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) :
    IsSolvable G := by
  haveI : (Subgroup.zpowers c).Normal := zpowers_sylow_normal (q ^ k) hcard hpm huniq c hc
  haveI : IsSolvable (Subgroup.zpowers c) := isSolvable_zpowers c
  have hidx : Nat.card (G ⧸ Subgroup.zpowers c) = q ^ k := by
    rw [← Subgroup.index_eq_card]; exact zpowers_index_eq (q ^ k) hcard c hc
  haveI : Group.IsNilpotent (G ⧸ Subgroup.zpowers c) := (IsPGroup.of_card hidx).isNilpotent
  exact isSolvable_of_normal_solvable_quotient (Subgroup.zpowers c)

/-! ### The fixed prime `p = 5`, solvability form -/

/-- **Fixed prime `5` solvability** (`p = 5` specialisation of
`isSolvable_of_sylow_primePow_index`).  A finite group of order `5·q^k` with
`5 ∤ q^k`, the divisor condition, and an order-`5` element is solvable.  This is
the solvability counterpart of `not_isSimpleGroup_order5`. -/
theorem isSolvable_order5_primePow_index {G : Type*} [Group G] [Finite G]
    {q k : ℕ} [Fact q.Prime]
    (hcard : Nat.card G = 5 * q ^ k) (hm5 : ¬ (5 ∣ q ^ k))
    (huniq : ∀ d : ℕ, d ∣ q ^ k → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) :
    IsSolvable G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  isSolvable_of_sylow_primePow_index hcard hm5 huniq c hc

/-- **Solvability capstone for order `40`.**  Any finite group of order `40`
containing an element of order `5` is solvable: order `40 = 5·2³`, `5 ∤ 8`, the
divisor condition holds (`6 ∤ 8`), and the quotient of order `8` is a `2`-group,
hence solvable.  This is the solvability counterpart of the order-`40`
non-simplicity capstone — the two together say every such group is a *solvable,
non-simple* group, in particular never the non-solvable `A₅`. -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 40) : IsSolvable G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  isSolvable_of_sylow_primePow_index (p := 5) (q := 2) (k := 3)
    (hcard.trans (by norm_num)) (by norm_num)
    (by
      intro d hd hmod
      rw [show (2 : ℕ) ^ 3 = 8 from by norm_num] at hd
      have := Nat.le_of_dvd (by norm_num) hd
      interval_cases d <;> omega)
    c hc

/-! ### Sharp strengthening: nilpotency in the coprime regime

Solvability (`isSolvable_of_sylow_primePow_index`) holds for *every* prime-power
index `m = q^k`.  In the special **coprime** regime `gcd(q^k, p − 1) = 1` the
centrality criterion `mem_center_of_coprime_index` places `⟨c⟩` inside the centre,
so the extension `1 → ⟨c⟩ → G → G ⧸ ⟨c⟩ → 1` is *central*.  A central extension of
a nilpotent group is nilpotent (Mathlib's `isNilpotent_of_ker_le_center`), and the
quotient `G ⧸ ⟨c⟩` is a `q`-group hence nilpotent; therefore `G` is **nilpotent**,
not merely solvable.

This is the sharp boundary separating the two structural conclusions.  The
Abel–Ruffini orders `20 = 5·4` and `40 = 5·8` live in the *non*-coprime regime
(`gcd(4, 4) = gcd(8, 4) = 4 ≠ 1`), where nilpotency genuinely fails — the metacyclic
Frobenius group `F₂₀ = C₅ ⋊ C₄` of order `20` is solvable but **not** nilpotent
(its Sylow `5`-subgroup is normal, but the Sylow `2`-subgroup is not).  The coprime
hypothesis is exactly what upgrades "solvable" to "nilpotent" here. -/

/-- **Nilpotency from a *central* normal Sylow `p`-subgroup with prime-power index.**

Under the hypotheses of `zpowers_sylow_normal`, if additionally the index `m = q^k`
is coprime to `p − 1`, then the order-`p` element `c` is central
(`mem_center_of_coprime_index`), so `⟨c⟩ ≤ Z(G)` and `1 → ⟨c⟩ → G → G ⧸ ⟨c⟩ → 1` is a
central extension of the `q`-group `G ⧸ ⟨c⟩`.  Hence `G` is nilpotent — a strict
strengthening of `isSolvable_of_sylow_primePow_index` valid precisely in the coprime
regime `gcd(q^k, p − 1) = 1`. -/
theorem isNilpotent_of_sylow_central_primePow_index {G : Type*} [Group G] [Finite G]
    {p q k : ℕ} [Fact p.Prime] [Fact q.Prime]
    (hcard : Nat.card G = p * q ^ k) (hpm : ¬ (p ∣ q ^ k))
    (huniq : ∀ d : ℕ, d ∣ q ^ k → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime (q ^ k) (p - 1)) :
    Group.IsNilpotent G := by
  haveI : (Subgroup.zpowers c).Normal := zpowers_sylow_normal (q ^ k) hcard hpm huniq c hc
  have hcent : c ∈ Subgroup.center G :=
    mem_center_of_coprime_index (q ^ k) hcard hpm huniq c hc hcop
  have hle : Subgroup.zpowers c ≤ Subgroup.center G := Subgroup.zpowers_le.mpr hcent
  have hidx : Nat.card (G ⧸ Subgroup.zpowers c) = q ^ k := by
    rw [← Subgroup.index_eq_card]; exact zpowers_index_eq (q ^ k) hcard c hc
  haveI : Group.IsNilpotent (G ⧸ Subgroup.zpowers c) := (IsPGroup.of_card hidx).isNilpotent
  refine isNilpotent_of_ker_le_center (QuotientGroup.mk' (Subgroup.zpowers c)) ?_ inferInstance
  rw [QuotientGroup.ker_mk']; exact hle

/-! ### The fixed prime `p = 5`, nilpotency form -/

/-- **Fixed prime `5` nilpotency** (`p = 5` specialisation of
`isNilpotent_of_sylow_central_primePow_index`).  A finite group of order `5·q^k` with
`5 ∤ q^k`, the divisor condition, an order-`5` element, and `q^k` coprime to `4 = 5 − 1`
is nilpotent.  This is the nilpotency counterpart of `isSolvable_order5_primePow_index`,
sharpened by the coprimality (oddness of `q^k`) hypothesis. -/
theorem isNilpotent_order5_central_primePow_index {G : Type*} [Group G] [Finite G]
    {q k : ℕ} [Fact q.Prime]
    (hcard : Nat.card G = 5 * q ^ k) (hm5 : ¬ (5 ∣ q ^ k))
    (huniq : ∀ d : ℕ, d ∣ q ^ k → d % 5 = 1 → d = 1)
    (c : G) (hc : orderOf c = 5) (hcop : Nat.Coprime (q ^ k) 4) :
    Group.IsNilpotent G :=
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  isNilpotent_of_sylow_central_primePow_index hcard hm5 huniq c hc (by simpa using hcop)

/-- **Order `15` nilpotency (hence cyclicity).**  Any finite group of order `15`
containing an element of order `5` is nilpotent: order `15 = 5·3¹`, `5 ∤ 3`, the
divisor condition holds (`3 < 5`), and `3` is coprime to `4 = 5 − 1`, so the Sylow
`5`-subgroup is central and the order-`3` quotient extension is central.  Together
with the (automatic) normal Sylow `3`-subgroup this is the group-theoretic reason
every group of order `15` is cyclic — the smallest coprime-regime instance, sitting
strictly on the nilpotent side of the `20/40` non-nilpotent boundary. -/
example {G : Type*} [Group G] [Finite G] (c : G) (hc : orderOf c = 5)
    (hcard : Nat.card G = 15) : Group.IsNilpotent G :=
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  isNilpotent_order5_central_primePow_index (q := 3) (k := 1)
    (hcard.trans (by norm_num)) (by norm_num)
    (huniq_of_lt (by norm_num) (by norm_num)) c hc (by norm_num)

/-! ### From central Sylow to abelian: the `G ⧸ ⟨c⟩` cyclic upgrade

The nilpotency result above places the group on the nilpotent side of the boundary, but in
the *prime-index* subcase (`k = 1`) one can say strictly more: `G` is **abelian**.  Once the
centrality criterion `mem_center_of_coprime_index` puts `c` in `Z(G)`, the classical theorem
"`G ⧸ Z(G)` cyclic ⟹ `G` abelian" (`commutative_of_cyclic_center_quotient`) applies through
the intermediate central subgroup `⟨c⟩`, provided the quotient `G ⧸ ⟨c⟩` is cyclic.  When the
index is a *prime* `q`, that quotient has prime order and is automatically cyclic.  This is
the exact mechanism behind "every group of order `15` is cyclic": `15 = 5·3`, `gcd(3, 4) = 1`
centralises the order-`5` element, and the order-`3` quotient is cyclic — giving
commutativity, a strict strengthening of the order-`15` nilpotency example above. -/

/-- **A central element generates a normal subgroup.**  If `c ∈ Z(G)` then every element of
`⟨c⟩` is central, hence fixed by conjugation, so `⟨c⟩ ⊴ G`.  This is exactly what makes the
coset space `G ⧸ ⟨c⟩` a *group* (rather than a bare quotient), a prerequisite for even stating
that it is cyclic below. -/
theorem zpowers_normal_of_mem_center {G : Type*} [Group G] {c : G}
    (hc : c ∈ Subgroup.center G) : (Subgroup.zpowers c).Normal := by
  refine ⟨fun n hn g => ?_⟩
  have hcen : n ∈ Subgroup.center G := Subgroup.zpowers_le.mpr hc hn
  rw [Subgroup.mem_center_iff] at hcen
  have hfix : g * n * g⁻¹ = n := by rw [hcen g]; group
  rw [hfix]; exact hn

/-- **Central element with cyclic quotient ⟹ abelian.**  If `c ∈ Z(G)` and the quotient
`G ⧸ ⟨c⟩` is cyclic, then `G` is commutative.  This routes Mathlib's
`commutative_of_cyclic_center_quotient` through the quotient map `G → G ⧸ ⟨c⟩`, whose kernel
`⟨c⟩` lies in the centre exactly because `c` is central (`Subgroup.zpowers_le`).  The `Normal`
instance — needed for `G ⧸ ⟨c⟩` to carry a group structure — follows from centrality via
`zpowers_normal_of_mem_center`. -/
theorem mul_comm_of_center_zpowers_cyclic_quotient {G : Type*} [Group G] (c : G)
    (hc : c ∈ Subgroup.center G) [(Subgroup.zpowers c).Normal]
    [IsCyclic (G ⧸ Subgroup.zpowers c)] (a b : G) :
    a * b = b * a := by
  refine commutative_of_cyclic_center_quotient (QuotientGroup.mk' (Subgroup.zpowers c)) ?_ a b
  rw [QuotientGroup.ker_mk']
  exact Subgroup.zpowers_le.mpr hc

/-- **Prime index ⟹ cyclic quotient.**  If `⟨c⟩` has order `p` and `Nat.card G = p·q` with
`q` prime, then `G ⧸ ⟨c⟩` has order `q`, hence is cyclic.  (Lagrange:
`|G| = |G ⧸ ⟨c⟩| · |⟨c⟩|` with `|⟨c⟩| = orderOf c = p`, cancel the `p`.) -/
theorem isCyclic_quotient_zpowers_of_prime_index {G : Type*} [Group G] [Finite G]
    (c : G) [(Subgroup.zpowers c).Normal] {p q : ℕ} (hc : orderOf c = p) (hq : q.Prime)
    (hcard : Nat.card G = p * q) :
    IsCyclic (G ⧸ Subgroup.zpowers c) := by
  haveI : Fact q.Prime := ⟨hq⟩
  apply isCyclic_of_prime_card (p := q)
  have hlag : Nat.card G
      = Nat.card (G ⧸ Subgroup.zpowers c) * Nat.card (Subgroup.zpowers c) :=
    Subgroup.card_eq_card_quotient_mul_card_subgroup _
  rw [Nat.card_zpowers, hc, hcard,
    mul_comm (Nat.card (G ⧸ Subgroup.zpowers c)) p] at hlag
  exact (Nat.eq_of_mul_eq_mul_left (hc ▸ orderOf_pos c) hlag).symm

/-- **Coprime prime index ⟹ abelian.**  Under the `zpowers_sylow_normal` hypotheses, if the
index `q = [G : ⟨c⟩]` is a *prime* coprime to `p − 1`, then `G` is commutative: `c` is central
by `mem_center_of_coprime_index`, and the prime-order quotient `G ⧸ ⟨c⟩` is cyclic, so
`mul_comm_of_center_zpowers_cyclic_quotient` applies.  This upgrades the nilpotency conclusion
`isNilpotent_of_sylow_central_primePow_index` (in its `k = 1` subcase) from nilpotent to
abelian. -/
theorem mul_comm_of_prime_index_coprime {G : Type*} [Group G] [Finite G] {p q : ℕ}
    [hp : Fact p.Prime] (hq : q.Prime)
    (hcard : Nat.card G = p * q) (hpq : ¬ (p ∣ q))
    (huniq : ∀ d : ℕ, d ∣ q → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime q (p - 1)) (a b : G) :
    a * b = b * a := by
  have hcent : c ∈ Subgroup.center G :=
    mem_center_of_coprime_index q hcard hpq huniq c hc hcop
  haveI : (Subgroup.zpowers c).Normal := zpowers_normal_of_mem_center hcent
  haveI : IsCyclic (G ⧸ Subgroup.zpowers c) :=
    isCyclic_quotient_zpowers_of_prime_index c hc hq hcard
  exact mul_comm_of_center_zpowers_cyclic_quotient c hcent a b

/-- **Every group of order `15` is abelian.**  Cauchy provides an order-`5` element `c`; with
`15 = 5·3`, `3` prime, `5 ∤ 3`, and `gcd(3, 4) = 1`, `mul_comm_of_prime_index_coprime` gives
commutativity.  (A finite abelian group of squarefree order `15` is then cyclic — the
classical classification of order-`15` groups, here obtained by upgrading the order-`15`
nilpotency example above to full commutativity.) -/
theorem mul_comm_of_card_fifteen {G : Type*} [Group G] [Finite G]
    (hcard : Nat.card G = 15) (a b : G) : a * b = b * a := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨c, hc⟩ : ∃ x : G, orderOf x = 5 :=
    exists_prime_orderOf_dvd_card 5 (by rw [← Nat.card_eq_fintype_card, hcard]; norm_num)
  exact mul_comm_of_prime_index_coprime (q := 3) (by norm_num)
    (hcard.trans (by norm_num)) (by norm_num)
    (huniq_of_lt (by norm_num) (by norm_num)) c hc (by norm_num) a b

/-- **Abelian ⟹ cyclic, for order = product of two distinct primes.**  A finite group whose
order is `p · q` with `p, q` *distinct* primes and in which every pair of elements commutes is
cyclic.  Cauchy (`exists_prime_orderOf_dvd_card`) supplies commuting elements `c, d` of orders
`p` and `q`; distinct primes are coprime (`Nat.coprime_primes`), so
`orderOf_mul_eq_mul_orderOf_of_coprime` gives `orderOf (c * d) = p · q = |G|`, and
`isCyclic_of_orderOf_eq_card` produces `c * d` as an explicit generator.  This is the finishing
step of the order-`pq` classification: `mul_comm_of_prime_index_coprime` establishes
commutativity, and this lemma converts commutativity into a concrete cyclic generator. -/
theorem isCyclic_of_comm_card_eq_prime_mul_prime {G : Type*} [Group G] [Finite G] {p q : ℕ}
    (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) (hcard : Nat.card G = p * q)
    (hcomm : ∀ a b : G, a * b = b * a) : IsCyclic G := by
  haveI : Fintype G := Fintype.ofFinite G
  haveI : Fact p.Prime := ⟨hp⟩
  haveI : Fact q.Prime := ⟨hq⟩
  obtain ⟨c, hc⟩ : ∃ x : G, orderOf x = p :=
    exists_prime_orderOf_dvd_card p
      (by rw [← Nat.card_eq_fintype_card, hcard]; exact dvd_mul_right p q)
  obtain ⟨d, hd⟩ : ∃ x : G, orderOf x = q :=
    exists_prime_orderOf_dvd_card q
      (by rw [← Nat.card_eq_fintype_card, hcard]; exact dvd_mul_left q p)
  have hcop : (orderOf c).Coprime (orderOf d) := by
    rw [hc, hd]; exact (Nat.coprime_primes hp hq).mpr hpq
  have horder : orderOf (c * d) = Nat.card G := by
    rw [Commute.orderOf_mul_eq_mul_orderOf_of_coprime (hcomm c d) hcop, hc, hd, hcard]
  exact isCyclic_of_orderOf_eq_card (c * d) horder

/-- **Every group of order `15` is cyclic.**  The sharp classical classification of order-`15`
groups: `mul_comm_of_card_fifteen` makes `G` abelian, and `15 = 3 · 5` is a product of two
distinct primes, so `isCyclic_of_comm_card_eq_prime_mul_prime` yields an explicit generator (an
element of order `15`, i.e. `G ≅ ℤ/15ℤ`).  This strengthens `mul_comm_of_card_fifteen` from
mere commutativity to full cyclicity — the definitive statement that there is a *unique* group
of order `15` up to isomorphism. -/
theorem isCyclic_of_card_fifteen {G : Type*} [Group G] [Finite G]
    (hcard : Nat.card G = 15) : IsCyclic G :=
  isCyclic_of_comm_card_eq_prime_mul_prime (p := 3) (q := 5) (by norm_num) (by norm_num)
    (by norm_num) (hcard.trans (by norm_num)) (fun a b => mul_comm_of_card_fifteen hcard a b)

/-! ### General order-`pq` classification (the positive half, and its sharp converse)

The order-`15` results above are the `p = 3, q = 5` instance of a general phenomenon: for two
primes `p < q`, whether a group of order `pq` must be cyclic is governed *entirely* by the
elementary arithmetic condition `p ∣ q − 1`.  The two theorems below package the positive half
of the classical classification for arbitrary such `p, q`, and — via a one-line contrapositive
— show the arithmetic condition is not merely sufficient but *sharp*.  No new group-theoretic
machinery is needed: the Sylow-elimination engine of this file already supplies everything. -/

/-- **General commutativity for order `p·q` (`p < q` primes, `p ∤ q − 1`).**  For two primes
`p < q`, if `p` does not divide `q − 1` then every group of order `p·q` is abelian.  The Sylow
`q`-subgroup is normal (its index `p` is the *smaller* prime, forcing `n_q = 1`); take a
generator `c` of order `q`.  Because `p` is prime, `p ∤ (q − 1)` is exactly `Coprime p (q − 1)`,
and `p < q` discharges both `q ∤ p` and the divisor-uniqueness hypothesis (`huniq_of_lt`).  Then
`mul_comm_of_prime_index_coprime` applied to the normal cyclic subgroup `⟨c⟩` (of prime index
`p`) yields commutativity.  This is the general engine behind `mul_comm_of_card_fifteen`. -/
theorem mul_comm_of_card_eq_prime_mul_prime_of_not_dvd {G : Type*} [Group G] [Finite G]
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p < q) (hndvd : ¬ p ∣ (q - 1))
    (hcard : Nat.card G = p * q) (a b : G) : a * b = b * a := by
  haveI : Fintype G := Fintype.ofFinite G
  haveI : Fact q.Prime := ⟨hq⟩
  obtain ⟨c, hc⟩ : ∃ x : G, orderOf x = q :=
    exists_prime_orderOf_dvd_card q
      (by rw [← Nat.card_eq_fintype_card, hcard]; exact dvd_mul_left q p)
  -- Roles in `mul_comm_of_prime_index_coprime`: its `p` = q (= orderOf c), its `q` = p (index).
  refine mul_comm_of_prime_index_coprime (p := q) (q := p) hp
    (hcard.trans (Nat.mul_comm p q)) ?_ (huniq_of_lt hp.pos hpq) c hc ?_ a b
  · -- `q ∤ p`: `q` is prime and `p < q`.
    exact fun hqp => absurd hpq (Nat.not_lt.mpr (Nat.le_of_dvd hp.pos hqp))
  · -- `Coprime p (q − 1)`, since `p` is prime and `p ∤ (q − 1)`.
    exact (hp.coprime_iff_not_dvd).mpr hndvd

/-- **Positive half of the order-`pq` classification.**  For primes `p < q` with `p ∤ q − 1`,
every group of order `p·q` is cyclic — equivalently there is a *unique* group of order `pq`
(namely `ℤ/pqℤ`).  Combines the commutativity engine
`mul_comm_of_card_eq_prime_mul_prime_of_not_dvd` with the abelian-⟹-cyclic converter
`isCyclic_of_comm_card_eq_prime_mul_prime`.  Recovers `isCyclic_of_card_fifteen`
(`15 = 3·5`, `3 ∤ 4`) as the instance `p = 3, q = 5`. -/
theorem isCyclic_of_card_eq_prime_mul_prime_of_not_dvd {G : Type*} [Group G] [Finite G]
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p < q) (hndvd : ¬ p ∣ (q - 1))
    (hcard : Nat.card G = p * q) : IsCyclic G :=
  isCyclic_of_comm_card_eq_prime_mul_prime hp hq (ne_of_lt hpq) hcard
    (mul_comm_of_card_eq_prime_mul_prime_of_not_dvd hp hq hpq hndvd hcard)

/-- **Necessity: a non-cyclic group of order `pq` forces `p ∣ q − 1`.**  The exact converse of
`isCyclic_of_card_eq_prime_mul_prime_of_not_dvd`: for primes `p < q`, if some group of order
`p·q` fails to be cyclic then `p` must divide `q − 1` — the arithmetic condition that permits the
nonabelian Frobenius group `ℤ/q ⋊ ℤ/p`.  This makes the classification *sharp*: `p ∤ q − 1` is
equivalent to "every order-`pq` group is cyclic", not merely sufficient.  Proved as the
contrapositive of the positive half, so no group construction is required — the sharp boundary
is obtained purely from the divisibility dichotomy for the prime `p`. -/
theorem dvd_sub_one_of_not_isCyclic_card_eq_prime_mul_prime {G : Type*} [Group G] [Finite G]
    {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p < q)
    (hcard : Nat.card G = p * q) (hnc : ¬ IsCyclic G) : p ∣ (q - 1) := by
  by_contra hndvd
  exact hnc (isCyclic_of_card_eq_prime_mul_prime_of_not_dvd hp hq hpq hndvd hcard)

/-- **Every group of order `35` is cyclic** (`35 = 5·7`, `5 ∤ 6`).  Instance of the general
order-`pq` classification with `p = 5, q = 7`, one step beyond the order-`15` case. -/
theorem isCyclic_of_card_thirtyfive {G : Type*} [Group G] [Finite G]
    (hcard : Nat.card G = 35) : IsCyclic G :=
  isCyclic_of_card_eq_prime_mul_prime_of_not_dvd (p := 5) (q := 7)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (hcard.trans (by norm_num))

/-- **Every group of order `33` is cyclic** (`33 = 3·11`, `3 ∤ 10`).  Instance with
`p = 3, q = 11`; here `p = 3` matches the order-`21` prime but `3 ∤ 10` (unlike `3 ∣ 6`),
so — in contrast to order `21` — the group is forced cyclic. -/
theorem isCyclic_of_card_thirtythree {G : Type*} [Group G] [Finite G]
    (hcard : Nat.card G = 33) : IsCyclic G :=
  isCyclic_of_card_eq_prime_mul_prime_of_not_dvd (p := 3) (q := 11)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (hcard.trans (by norm_num))

/-! ### Structural endgame: the internal direct product `G ≃* ⟨c⟩ × H` as a genuine isomorphism

The results above are *predicates* on `G` (commutativity, cyclicity).  The theorem below upgrades
the set-level splitting `exists_normal_pComplement_of_coprime_index` to a genuine group
*isomorphism*, giving the sharpest structural form of the coprime-index analysis: in that regime
`G` is not merely "abelian" or "an extension" but literally a **direct product** of its central
Sylow `p`-subgroup with a normal `p`-complement. -/

/-- **Internal direct product `G ≃* ⟨c⟩ × H`.**  Under the coprime-index hypotheses
(`gcd(m, p−1) = 1`, `p ∤ m`), the central Sylow subgroup `⟨c⟩` (order `p`) and its normal
`p`-complement `H` (order `m`) realise `G` as the *internal direct product* `⟨c⟩ × H`: the
multiplication map `(k, h) ↦ k·h` is a group isomorphism `⟨c⟩ × H ≃* G`.

The two ingredients are already in hand:
* it is a **homomorphism** because `⟨c⟩ ≤ Z(G)` (`zpowers_le_center_of_coprime_index`), so the two
  factors commute and `MonoidHom.noncommCoprod` assembles the multiplication map;
* it is **bijective** because `⟨c⟩` and `H` are complementary
  (`exists_normal_pComplement_of_coprime_index`), which is *definitionally*
  `Function.Bijective (fun (k, h) ↦ k·h)` (`Subgroup.isComplement_iff_bijective`).

`MulEquiv.ofBijective` then packages the two into `G ≃* ⟨c⟩ × H`.  This is the structural endgame:
a central normal Hall subgroup splits off as a *direct* factor — the elementary content of the
`p = 5` Abel–Ruffini analysis, now stated as a bona-fide isomorphism rather than a mere splitting.
Concretely `G ≅ ℤ/p × H`. -/
theorem exists_mulEquiv_prod_zpowers_of_coprime_index {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime m (p - 1)) :
    ∃ H : Subgroup G, Nat.card H = m ∧ Nonempty (G ≃* (Subgroup.zpowers c) × H) := by
  obtain ⟨H, _hHnorm, hHc, hHcard⟩ :=
    exists_normal_pComplement_of_coprime_index m hcard hpm huniq c hc hcop
  have hcen := zpowers_le_center_of_coprime_index m hcard hpm huniq c hc hcop
  -- `⟨c⟩` is central, so its elements commute with everything, in particular with `H`.
  have hcomm : ∀ (k : Subgroup.zpowers c) (h : H),
      Commute ((Subgroup.zpowers c).subtype k) (H.subtype h) := by
    intro k h
    have hkcen : (k : G) ∈ Subgroup.center G := hcen k.2
    exact (Subgroup.mem_center_iff.mp hkcen (h : G)).symm
  -- The multiplication homomorphism `⟨c⟩ × H → G`, `(k, h) ↦ k·h`.
  let φ := (Subgroup.zpowers c).subtype.noncommCoprod H.subtype hcomm
  -- Complementarity says exactly that this map is bijective.
  have hbij : Function.Bijective φ :=
    (Subgroup.isComplement_iff_bijective (Subgroup.zpowers c) H).mp hHc
  exact ⟨H, hHcard, ⟨(MulEquiv.ofBijective φ hbij).symm⟩⟩

/-- **Order `15` as an internal direct product** `G ≃* ℤ/5 × H` with `|H| = 3`.  The concrete
`p = 5, m = 3` instance of `exists_mulEquiv_prod_zpowers_of_coprime_index`: Cauchy supplies an
order-`5` element `c`, and `15 = 5·3` with `gcd(3, 4) = 1`, `5 ∤ 3` puts us in the coprime-index
regime, so `G` splits as `⟨c⟩ × H`.  This is the isomorphism-level refinement of
`mul_comm_of_card_fifteen` / `isCyclic_of_card_fifteen`. -/
theorem exists_mulEquiv_prod_of_card_fifteen {G : Type*} [Group G] [Finite G]
    (hcard : Nat.card G = 15) :
    ∃ (c : G) (H : Subgroup G), Nat.card H = 3 ∧
      Nonempty (G ≃* (Subgroup.zpowers c) × H) := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨c, hc⟩ : ∃ x : G, orderOf x = 5 :=
    exists_prime_orderOf_dvd_card 5 (by rw [← Nat.card_eq_fintype_card, hcard]; norm_num)
  obtain ⟨H, hHcard, hHequiv⟩ := exists_mulEquiv_prod_zpowers_of_coprime_index (p := 5) (m := 3)
    (hcard.trans (by norm_num)) (by norm_num) (huniq_of_lt (by norm_num) (by norm_num))
    c hc (by norm_num)
  exact ⟨c, H, hHcard, hHequiv⟩

/-- **Cyclicity descends to the `p`-complement.**  Under the coprime-index hypotheses the
internal direct product `G ≃* ⟨c⟩ × H` (`exists_mulEquiv_prod_zpowers_of_coprime_index`) collapses
cyclicity of the whole group to that of the complement:

> `G` is cyclic **iff** its normal `p`-complement `H` is cyclic.

This is the sharpest structural consequence of the splitting.  The central Sylow-`p` factor `⟨c⟩` is
*always* cyclic — it is the group generated by a single element `c` of order `p` — and its order `p`
is coprime to `|H| = m` (because `p` is prime and `p ∤ m`).  `Group.isCyclic_prod_iff` therefore
reduces `IsCyclic (⟨c⟩ × H)` to `IsCyclic ⟨c⟩ ∧ IsCyclic H ∧ Coprime p m`, of which only the middle
conjunct is not automatic — so the product is cyclic exactly when `H` is.

For order `p·q` (`m = q` prime) the complement has prime order and is automatically cyclic, so the
right-hand side holds and one recovers the classical `pq`-classification (`isCyclic_of_card_fifteen`,
`isCyclic_of_card_eq_prime_mul_prime_of_not_dvd`) *through the isomorphism*, rather than as a bespoke
Sylow argument.  For composite `m` the equivalence localises the entire question of cyclicity of `G`
onto the strictly smaller group `H`. -/
theorem exists_pComplement_isCyclic_iff {G : Type*} [Group G] [Finite G] {p : ℕ}
    [hp : Fact p.Prime] (m : ℕ)
    (hcard : Nat.card G = p * m) (hpm : ¬ (p ∣ m))
    (huniq : ∀ d : ℕ, d ∣ m → d % p = 1 → d = 1)
    (c : G) (hc : orderOf c = p) (hcop : Nat.Coprime m (p - 1)) :
    ∃ H : Subgroup G, Nat.card H = m ∧ Nonempty (G ≃* (Subgroup.zpowers c) × H) ∧
      (IsCyclic G ↔ IsCyclic H) := by
  obtain ⟨H, hHcard, ⟨e⟩⟩ :=
    exists_mulEquiv_prod_zpowers_of_coprime_index m hcard hpm huniq c hc hcop
  refine ⟨H, hHcard, ⟨e⟩, ?_⟩
  -- `⟨c⟩` is cyclic and its order `p` is coprime to `|H| = m`.
  have hzc : IsCyclic (Subgroup.zpowers c) :=
    (Subgroup.isCyclic_iff_exists_zpowers_eq_top _).mpr ⟨c, rfl⟩
  have hcardz : Nat.card (Subgroup.zpowers c) = p := by rw [Nat.card_zpowers, hc]
  have hcopc : (Nat.card (Subgroup.zpowers c)).Coprime (Nat.card H) := by
    rw [hcardz, hHcard]; exact (Nat.Prime.coprime_iff_not_dvd hp.1).mpr hpm
  -- Transfer cyclicity across `e`, then peel off the always-cyclic `⟨c⟩` factor.
  rw [e.isCyclic, Group.isCyclic_prod_iff]
  exact ⟨fun ⟨_, hH, _⟩ => hH, fun hH => ⟨hzc, hH, hcopc⟩⟩

/-- **Order `15` cyclicity as a complement equivalence.**  The `p = 5, m = 3` instance of
`exists_pComplement_isCyclic_iff`: a group `G` of order `15` splits as `⟨c⟩ × H` with `|H| = 3` and
`G` is cyclic *iff* the order-`3` complement `H` is.  Since `|H| = 3` is prime, `H` is automatically
cyclic, so this recovers `isCyclic_of_card_fifteen` — but now exhibits *why* through the structural
decomposition rather than a direct Sylow count. -/
theorem exists_pComplement_isCyclic_iff_card_fifteen {G : Type*} [Group G] [Finite G]
    (hcard : Nat.card G = 15) :
    ∃ (c : G) (H : Subgroup G), Nat.card H = 3 ∧
      Nonempty (G ≃* (Subgroup.zpowers c) × H) ∧ (IsCyclic G ↔ IsCyclic H) := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨c, hc⟩ : ∃ x : G, orderOf x = 5 :=
    exists_prime_orderOf_dvd_card 5 (by rw [← Nat.card_eq_fintype_card, hcard]; norm_num)
  obtain ⟨H, hHcard, hHequiv, hHiff⟩ := exists_pComplement_isCyclic_iff (p := 5) (m := 3)
    (hcard.trans (by norm_num)) (by norm_num) (huniq_of_lt (by norm_num) (by norm_num))
    c hc (by norm_num)
  exact ⟨c, H, hHcard, hHequiv, hHiff⟩

end AbelRuffiniSylowElim
