/-
  Power sums generate the symmetric subalgebra in characteristic 0
  (amgm-inequality-oq-02-oq-01-oq-02-oq-01-oq-01-oq-01-oq-01-oq-01)

  Open Question (the listed follow-up of the reverse Newton identity entry,
  amgm-inequality-oq-02-oq-01-oq-02-oq-01-oq-01-oq-01-oq-01):
  "Upgrade membership to subalgebra equality
   adjoin ℚ (range psum) = symmetricSubalgebra σ ℚ."

  The parent entry proved the *membership* statement (reverse Newton):

      esymm σ R k ∈ Algebra.adjoin ℚ (Set.range (psum σ R))

  i.e. each elementary symmetric polynomial lies in the ℚ-subalgebra generated
  by the power sums.  This is one half of the classical fact that, in
  characteristic 0, the power sums generate the *entire* ring of symmetric
  functions.  The genuinely NEW content here is the precise SUBALGEBRA EQUALITY

      Algebra.adjoin ℚ (Set.range (psum σ ℚ)) = symmetricSubalgebra σ ℚ

  for every finite `σ`.  This is the sharp statement: the ℚ-subalgebra generated
  by the power sums is *exactly* the symmetric subalgebra — neither bigger
  (every power sum is symmetric) nor smaller (every symmetric polynomial is a
  ℚ-polynomial in the power sums).

  ## The synthesis

  The two inclusions come from two different sources, and combining them is the
  point of this entry:

  * `≤`  (`psumAdjoin_le_symmetric`): every power sum is symmetric
    (`MvPolynomial.psum_isSymmetric`), and `symmetricSubalgebra` is a subalgebra,
    so the subalgebra it generates is contained in it.  Elementary.

  * `≥`  (`symmetric_le_psumAdjoin`): this is where the two deep facts meet.
    Mathlib's *fundamental theorem of symmetric polynomials*
    (`MvPolynomial.esymmAlgHom_surjective`) says every symmetric polynomial is a
    ℚ-polynomial in the elementary symmetric polynomials `e₁, …, e_{|σ|}`.  The
    parent's *reverse Newton identity* (`esymm_mem_adjoin_psum`) says every `eₖ`
    is in turn a ℚ-polynomial in the power sums.  Composing the two places every
    symmetric polynomial in `adjoin ℚ (range psum)`.

  Mathlib has the fundamental theorem (`esymm` generate the symmetric
  subalgebra) and, via the parent, the reverse Newton identity, but no statement
  that the *power sums* generate the symmetric subalgebra.  That generation
  statement is the content of this file.

  Status: PROVED — fundamental theorem (esymm surjective) ∘ reverse Newton
  Axioms: 0, Sorries: 0
  Tags: algebra, symmetric-functions, newton-girard, power-sums, mv-polynomial,
        fundamental-theorem-of-symmetric-polynomials
-/

import Mathlib
import Proofs.AmgmInequalityOQ02OQ01OQ02OQ01OQ01OQ01OQ01

namespace AmgmInequalityOQ02OQ01OQ02OQ01OQ01OQ01OQ01OQ01

open MvPolynomial
open AmgmInequalityOQ02OQ01OQ02OQ01OQ01OQ01OQ01

variable (σ : Type*) [Fintype σ]

/-- The ℚ-subalgebra of `MvPolynomial σ ℚ` generated by all the power sums. -/
abbrev psumAdjoin : Subalgebra ℚ (MvPolynomial σ ℚ) :=
  Algebra.adjoin ℚ (Set.range (psum σ ℚ))

/-- **Easy inclusion.** The subalgebra generated by the power sums is contained
in the symmetric subalgebra, because every power sum is symmetric. -/
theorem psumAdjoin_le_symmetric :
    psumAdjoin σ ≤ symmetricSubalgebra σ ℚ := by
  apply Algebra.adjoin_le
  rintro _ ⟨n, rfl⟩
  exact (mem_symmetricSubalgebra _).mpr (psum_isSymmetric σ ℚ n)

/-- **Hard inclusion.** The symmetric subalgebra is contained in the subalgebra
generated by the power sums.  This composes Mathlib's fundamental theorem of
symmetric polynomials (`esymmAlgHom_surjective`: every symmetric polynomial is a
ℚ-polynomial in the elementary symmetric polynomials) with the parent's reverse
Newton identity (`esymm_mem_adjoin_psum`: every `eₖ` is a ℚ-polynomial in the
power sums). -/
theorem symmetric_le_psumAdjoin :
    symmetricSubalgebra σ ℚ ≤ psumAdjoin σ := by
  intro p hp
  -- Set `n = |σ|`; the fundamental theorem applies with `n` elementary symmetric polys.
  set n := Fintype.card σ with hn
  -- Surjectivity of `esymmAlgHom` gives `q` with `aeval (e_{i+1}) q = p`.
  obtain ⟨q, hq⟩ := esymmAlgHom_surjective (σ := σ) (R := ℚ) (n := n) le_rfl ⟨p, hp⟩
  have hpval : aeval (fun i : Fin n => esymm σ ℚ (i + 1)) q = p := by
    have h := esymmAlgHom_apply (σ := σ) (R := ℚ) (n := n) q
    rw [hq] at h
    exact h.symm
  -- `p` lies in the subalgebra generated by the `e_{i+1}` (image of `aeval`)...
  have hmem : p ∈ Algebra.adjoin ℚ (Set.range (fun i : Fin n => esymm σ ℚ (i + 1))) := by
    rw [Algebra.adjoin_range_eq_range_aeval]
    exact ⟨q, hpval⟩
  -- ...and each `e_{i+1}` lies in `psumAdjoin` by the reverse Newton identity.
  refine Algebra.adjoin_le ?_ hmem
  rintro _ ⟨i, rfl⟩
  exact esymm_mem_adjoin_psum σ ℚ (i + 1)

/-- **Power sums generate the symmetric subalgebra (characteristic 0).** For
every finite index type `σ`, the ℚ-subalgebra of `MvPolynomial σ ℚ` generated by
the power sums `p₁, p₂, …` is exactly the symmetric subalgebra:

  `Algebra.adjoin ℚ (Set.range (psum σ ℚ)) = symmetricSubalgebra σ ℚ`.

This is the sharp form of "the power sums generate the ring of symmetric
functions over a field of characteristic 0": the parent's reverse Newton
identity gives the `≥` inclusion (via Mathlib's fundamental theorem of symmetric
polynomials), and symmetry of the power sums gives the easy `≤` inclusion. -/
theorem psum_adjoin_eq_symmetric :
    Algebra.adjoin ℚ (Set.range (psum σ ℚ)) = symmetricSubalgebra σ ℚ :=
  le_antisymm (psumAdjoin_le_symmetric σ) (symmetric_le_psumAdjoin σ)

/-- **Every symmetric polynomial is a ℚ-polynomial in the power sums.** The
concrete corollary of the equality: a symmetric polynomial over ℚ lies in the
subalgebra generated by the power sums. -/
theorem isSymmetric_mem_psumAdjoin {p : MvPolynomial σ ℚ} (hp : p.IsSymmetric) :
    p ∈ psumAdjoin σ :=
  symmetric_le_psumAdjoin σ ((mem_symmetricSubalgebra _).mpr hp)

end AmgmInequalityOQ02OQ01OQ02OQ01OQ01OQ01OQ01OQ01
