/-
  Angle Trisection OQ02-OQ03-OQ01:
  Proving the maximal real subfield degree via Galois fixed field theory.

  Goal: Eliminate the axioms from the OQ02-OQ03 formalization by connecting
  Mathlib's cyclotomic field infrastructure to the cos(2π/n) degree computation.

  Main result: maximal_real_subfield_degree
    For n ≥ 3, ∃ F : IntermediateField ℚ (CyclotomicField n ℚ),
    [F:ℚ] = φ(n)/2.

  Proof strategy:
  1. CyclotomicField n ℚ is Galois over ℚ with degree φ(n) (Mathlib)
  2. -1 ∈ (ℤ/nℤ)* maps to an order-2 automorphism σ (via galCyclotomicEquivUnitsZMod)
  3. H = ⟨σ⟩ is a subgroup of Gal(K/ℚ) of order 2
  4. F = K^H (fixed field of H) has [K:F] = 2 (Artin/fixed field theorem)
  5. Tower law: φ(n) = [K:F]·[F:ℚ] = 2·[F:ℚ], so [F:ℚ] = φ(n)/2
-/

import Mathlib

open Polynomial

namespace AngleTrisectionOQ02OQ03OQ01

-- ============================================================================
-- § 1. Cyclotomic Field Setup
-- ============================================================================

variable (n : ℕ) [NeZero n]

/-- CyclotomicField n ℚ is a Galois extension of ℚ. -/
instance cyclotomic_isGalois : IsGalois ℚ (CyclotomicField n ℚ) :=
  IsCyclotomicExtension.isGalois {n} ℚ (CyclotomicField n ℚ)

/-- CyclotomicField n ℚ is finite-dimensional over ℚ. -/
instance cyclotomic_finiteDimensional : FiniteDimensional ℚ (CyclotomicField n ℚ) :=
  IsCyclotomicExtension.finiteDimensional {n} ℚ (CyclotomicField n ℚ)

/-- [CyclotomicField n ℚ : ℚ] = φ(n). -/
theorem cyclotomic_finrank :
    Module.finrank ℚ (CyclotomicField n ℚ) = Nat.totient n :=
  IsCyclotomicExtension.finrank (CyclotomicField n ℚ)
    (Polynomial.cyclotomic.irreducible_rat (NeZero.pos n))

-- ============================================================================
-- § 2. Order-2 Automorphism via (ℤ/nℤ)* ≃ Gal(ℚ(ζₙ)/ℚ)
-- ============================================================================

/-- The Galois group of ℚ(ζₙ)/ℚ is isomorphic to (ℤ/nℤ)*.
    This comes from galCyclotomicEquivUnitsZMod with the cyclotomic polynomial
    being irreducible over ℚ. -/
noncomputable def galEquiv :
    (Polynomial.cyclotomic n ℚ).Gal ≃* (ZMod n)ˣ :=
  galCyclotomicEquivUnitsZMod
    (L := CyclotomicField n ℚ)
    (Polynomial.cyclotomic.irreducible_rat (NeZero.pos n))

/-- The automorphism σ corresponding to -1 ∈ (ℤ/nℤ)*. This is the analogue
    of complex conjugation on the cyclotomic field. -/
noncomputable def conjAut : (Polynomial.cyclotomic n ℚ).Gal :=
  (galEquiv n).symm (-1)

/-- σ ≠ 1 for n ≥ 3: -1 ≠ 1 in (ℤ/nℤ)* when n ≥ 3. -/
theorem conjAut_ne_one (hn : 3 ≤ n) : conjAut n ≠ 1 := by
  intro h
  have h_eq := congr_arg (galEquiv n) h
  simp [conjAut, MulEquiv.apply_symm_apply] at h_eq
  -- h_eq : (-1 : (ZMod n)ˣ) = 1
  have h_neg : (-1 : ZMod n) = 1 := by
    have := congr_arg Units.val h_eq; simpa using this
  have h2 : (2 : ZMod n) = 0 := by
    have h0 := neg_add_cancel (1 : ZMod n)
    rw [h_neg] at h0
    rw [show (2 : ZMod n) = 1 + 1 from by norm_num]
    exact h0
  rw [show (2 : ZMod n) = ((2 : ℕ) : ZMod n) from by push_cast; ring] at h2
  have h_dvd : n ∣ 2 := (ZMod.natCast_eq_zero_iff 2 n).mp h2
  have : n ≤ 2 := Nat.le_of_dvd (by norm_num) h_dvd
  omega

/-- σ² = 1: (-1)² = 1 in (ℤ/nℤ)*. -/
theorem conjAut_sq : conjAut n ^ 2 = 1 := by
  have : ((-1 : (ZMod n)ˣ)) ^ 2 = 1 := by
    ext; simp
  show (galEquiv n).symm (-1) ^ 2 = 1
  rw [← map_pow, this, map_one]

/-- σ has order exactly 2 for n ≥ 3. -/
theorem conjAut_orderOf (hn : 3 ≤ n) : orderOf (conjAut n) = 2 := by
  apply orderOf_eq_prime (conjAut_sq n) (conjAut_ne_one n hn)

-- ============================================================================
-- § 3. Fixed Field of ⟨σ⟩ and Degree Computation
-- ============================================================================

/-- The subgroup H = ⟨σ⟩ ≤ Gal(ℚ(ζₙ)/ℚ), generated by complex conjugation. -/
noncomputable def conjSubgroup : Subgroup (Polynomial.cyclotomic n ℚ).Gal :=
  Subgroup.zpowers (conjAut n)

/-- H = ⟨σ⟩ has cardinality 2 for n ≥ 3. -/
theorem conjSubgroup_card (hn : 3 ≤ n) :
    Nat.card (conjSubgroup n) = 2 := by
  rw [conjSubgroup]
  rw [Nat.card_zpowers]
  exact conjAut_orderOf n hn

/-- The fixed field F = (CyclotomicField n ℚ)^⟨σ⟩: the maximal real subfield. -/
noncomputable def maxRealSubfield :
    IntermediateField ℚ (CyclotomicField n ℚ) :=
  IntermediateField.fixedField (conjSubgroup n)

/-- The degree of the maximal real subfield over ℚ is φ(n)/2 for n ≥ 3.

    Proof: By the fundamental theorem of Galois theory (fixed field theorem),
    [K : F] = |H| = 2, where K = CyclotomicField n ℚ and F = K^H.
    By the tower law, [K:ℚ] = [K:F]·[F:ℚ], so φ(n) = 2·[F:ℚ].
    Therefore [F:ℚ] = φ(n)/2. -/
theorem maximal_real_subfield_degree (hn : 3 ≤ n) :
    ∃ (F : IntermediateField ℚ (CyclotomicField n ℚ)),
    Module.finrank ℚ F = Nat.totient n / 2 := by
  use maxRealSubfield n
  set K := CyclotomicField n ℚ
  set F := maxRealSubfield n
  set H := conjSubgroup n
  -- Step 1: [K:F] = |H| = 2
  have hKF : Module.finrank F K = Nat.card H :=
    IntermediateField.finrank_fixedField_eq_card H
  rw [conjSubgroup_card n hn] at hKF
  -- Step 2: [K:ℚ] = φ(n)
  have hKQ : Module.finrank ℚ K = Nat.totient n := cyclotomic_finrank n
  -- Step 3: Tower law [K:ℚ] = [K:F] · [F:ℚ]
  have htower : Module.finrank ℚ K = Module.finrank ℚ F * Module.finrank F K :=
    (Module.finrank_mul_finrank ℚ F K).symm
  -- Step 4: Combine: φ(n) = [F:ℚ] * 2
  rw [hKQ, hKF] at htower
  -- htower : Nat.totient n = Module.finrank ℚ ↥F * 2
  omega

-- ============================================================================
-- § 4. Remaining Axioms (to be proved in future sessions)
-- ============================================================================

/-- cos(2π/n) satisfies a monic polynomial over ℚ of degree φ(n)/2. -/
axiom cos_minimal_poly_degree (hn : 3 ≤ n) :
    ∃ P : ℚ[X], P.Monic ∧ P.natDegree = Nat.totient n / 2 ∧
    Polynomial.aeval (Real.cos (2 * Real.pi / n)) P = 0

/-- From cos_minimal_poly_degree, cos(2π/n) is algebraic over ℚ. -/
omit [NeZero n] in
theorem cos_algebraic_from_cyclotomic (hn : 3 ≤ n) :
    IsAlgebraic ℚ (Real.cos (2 * Real.pi / n)) := by
  obtain ⟨P, hP_monic, _, hP_root⟩ := cos_minimal_poly_degree n hn
  exact ⟨P, hP_monic.ne_zero, hP_root⟩

/-- For n ≥ 3, the extension ℚ(cos(2π/n))/ℚ is Galois of degree φ(n)/2. -/
axiom cos_extension_is_galois (hn : 3 ≤ n) :
    ∃ (K : IntermediateField ℚ ℝ),
    FiniteDimensional ℚ K ∧
    Real.cos (2 * Real.pi / n) ∈ K ∧
    Module.finrank ℚ K = Nat.totient n / 2

-- ============================================================================
-- § 5. Axiom Inventory
-- ============================================================================

/-
  AXIOM STATUS:
  ✅ maximal_real_subfield_degree: PROVED via fixed field of ⟨σ⟩ (§3)
  ❌ cos_minimal_poly_degree: needs connection CyclotomicField → ℝ
  ❌ cos_extension_is_galois: needs normality of fixed field extension

  DEPENDENCY: maximal_real_subfield_degree → cos_minimal_poly_degree → cos_extension_is_galois
-/

end AngleTrisectionOQ02OQ03OQ01
