import Mathlib.Data.Int.GCD
import Mathlib.Data.Nat.GCD.Basic
import Mathlib.RingTheory.Coprime.Basic
import Mathlib.Tactic

/-
# GCD Structure: Complete Solution Set of Linear Diophantine Equations

## Open Question (bezout-identity-oq-04)

"Extend the Diophantine solvability criterion to fully characterize the GCD structure:
not just *when* ax + by = c has solutions, but *all* solutions and their lattice structure."

## Answer: The Solution Set Forms an Arithmetic Lattice

When gcd(a,b) | c (so solutions exist), the solution set of ax + by = c is:

  {(x₀ + (b/d)·t,  y₀ - (a/d)·t)  :  t ∈ ℤ}

where (x₀, y₀) is any particular solution and d = gcd(a, b).

This characterizes the full GCD structure: solutions form a 1-dimensional
coset of the lattice generated by (b/d, -a/d), whose step size is controlled by gcd(a,b).

## Key Theorems

1. **gcd_divides_linear_combination**: gcd(a,b) divides every ax + by.
2. **coprime_linear_null_space**: If gcd(a,b) = 1, the null space of ax+by is {(bt,-at)}.
3. **diophantine_complete_parameterization**: All solutions form an arithmetic progression.
4. **bezout_three**: Generalized Bezout for three integers.
5. **diophantine_three_solvable**: Three-variable Diophantine criterion.
6. **gcd_eq_min_pos_linear_comb**: gcd(a,b) is the minimum positive linear combination.
7. **gcd_achievable**: gcd(a,b) is itself achievable as a linear combination.
8. **gcd_complete_characterization**: Complete characterization of GCD via the ideal it generates.

## Builds On
- BezoutIdentity.lean: bezout_int, diophantine_solvable
- BezoutIdentityOQ02.lean: euclids_lemma_nat, coprime_iff_linear_combination
-/

namespace BezoutIdentityOQ04

/-! ## Structural Lemma: GCD Divides Every Linear Combination -/

/-- **GCD divides every linear combination**:
    For any integers a, b and any coefficients x, y, the GCD of a and b divides a*x + b*y.

    This is the structural fact underlying all of Bezout theory:
    the ideal {ax + by : x, y ∈ ℤ} is exactly the principal ideal gcd(a,b)·ℤ. -/
theorem gcd_divides_linear_combination (a b x y : ℤ) :
    (Int.gcd a b : ℤ) ∣ a * x + b * y := by
  have ha : (Int.gcd a b : ℤ) ∣ a := Int.gcd_dvd_left a b
  have hb : (Int.gcd a b : ℤ) ∣ b := Int.gcd_dvd_right a b
  exact dvd_add (dvd_mul_of_dvd_left ha x) (dvd_mul_of_dvd_left hb y)

/-! ## The Null Space: Solutions to ax + by = 0 when gcd = 1 -/

/-- **Null space when coprime**: If gcd(a, b) = 1, the solutions to a*x + b*y = 0
    are exactly the pairs (b*t, -a*t) for t ∈ ℤ.

    This is the "kernel characterization": the one-dimensional null space of the
    integer linear map (x,y) ↦ ax + by when a and b are coprime. -/
theorem coprime_linear_null_space (a b : ℤ) (hcop : Int.gcd a b = 1) :
    ∀ x y : ℤ, a * x + b * y = 0 ↔ ∃ t : ℤ, x = b * t ∧ y = -a * t := by
  -- Build IsCoprime a b from Bezout coefficients (needed in both cases)
  have hicop : IsCoprime a b := by
    refine ⟨Int.gcdA a b, Int.gcdB a b, ?_⟩
    have hbez := Int.gcd_eq_gcd_ab a b
    simp only [hcop, Nat.cast_one] at hbez
    linarith
  intro x y
  constructor
  · intro h
    by_cases hb0 : b = 0
    · -- When b = 0: gcd(a, 0) = natAbs a = 1, so a is a unit (a = ±1)
      subst hb0
      simp only [zero_mul, add_zero] at h
      -- isCoprime_zero_right: IsCoprime a 0 ↔ IsUnit a
      have ha_unit : IsUnit a := isCoprime_zero_right.mp hicop
      have hx0 : x = 0 := (mul_eq_zero.mp h).resolve_left ha_unit.ne_zero
      have ha_sq : a * a = 1 := by
        rcases Int.isUnit_iff.mp ha_unit with rfl | rfl <;> norm_num
      refine ⟨-a * y, by simp only [hx0, zero_mul], ?_⟩
      calc y = 1 * y := (one_mul y).symm
        _ = a * a * y := by rw [ha_sq]
        _ = -a * (-a * y) := by ring
    · -- When b ≠ 0: IsCoprime b a + b | a*x → b | x (Euclid's lemma)
      -- b divides a*x (from ax + by = 0 → ax = -by)
      have hbax : b ∣ a * x := ⟨-y, by linarith⟩
      -- Prove b | x directly using Bezout: x = u*(a*x) + v*b*x = u*(b*m) + v*b*x = b*(u*m+v*x)
      obtain ⟨u, v, huv⟩ := hicop  -- u * a + v * b = 1
      obtain ⟨m, hm⟩ := hbax       -- a * x = b * m
      have hbx : b ∣ x := ⟨u * m + v * x, by
        calc x = 1 * x := (one_mul x).symm
          _ = (u * a + v * b) * x := by rw [huv]
          _ = u * (a * x) + v * b * x := by ring
          _ = u * (b * m) + v * b * x := by rw [hm]
          _ = b * (u * m + v * x) := by ring⟩
      obtain ⟨t, ht⟩ := hbx
      refine ⟨t, ht, ?_⟩
      -- x = b*t; substitute: a*(b*t) + b*y = 0 → b*(a*t + y) = 0 → a*t + y = 0
      have h' : a * (b * t) + b * y = 0 := ht ▸ h
      have key : b * (a * t + y) = 0 := by linear_combination h'
      linarith [(mul_eq_zero.mp key).resolve_left hb0]
  · rintro ⟨t, rfl, rfl⟩
    ring

/-! ## Complete Parametrization of All Solutions -/

/-- **Complete Parametrization** (the main structural theorem):
    If (x₀, y₀) is one solution to a*x + b*y = c (with a, b not both zero), then
    ALL solutions are:
      x = x₀ + (b/d) * t,   y = y₀ - (a/d) * t,   for some t ∈ ℤ
    where d = gcd(a, b).

    This is the complete characterization of the solution lattice:
    solutions form a 1D coset {(x₀, y₀) + t * (b/d, -a/d) : t ∈ ℤ}. -/
theorem diophantine_complete_parameterization (a b c : ℤ)
    (hd_pos : 0 < Int.gcd a b)
    (x₀ y₀ : ℤ) (h₀ : a * x₀ + b * y₀ = c) :
    ∀ x y : ℤ, a * x + b * y = c ↔
    ∃ t : ℤ, x = x₀ + (b / Int.gcd a b) * t ∧ y = y₀ - (a / Int.gcd a b) * t := by
  intro x y
  -- Let d = gcd(a, b), a' = a/d, b' = b/d
  set d := (Int.gcd a b : ℤ) with hd_def
  have hd_ne : d ≠ 0 := by
    rw [hd_def]
    have h : Int.gcd a b ≠ 0 := by omega
    exact_mod_cast h
  obtain ⟨a', ha'⟩ : d ∣ a := Int.gcd_dvd_left a b
  obtain ⟨b', hb'⟩ : d ∣ b := Int.gcd_dvd_right a b
  -- a/d = a' and b/d = b'
  have had : a / d = a' := Int.ediv_eq_of_eq_mul_left hd_ne (by linarith [ha'])
  have hbd : b / d = b' := Int.ediv_eq_of_eq_mul_left hd_ne (by linarith [hb'])
  -- gcd(a', b') = 1: from a = d*a', b = d*b', d = gcd(a,b), so Bezout gives a'*u+b'*v=1
  have hcop' : Int.gcd a' b' = 1 := by
    -- From Bezout: a*gcdA + b*gcdB = d; substitute a = d*a', b = d*b':
    -- d*(a'*gcdA + b'*gcdB) = d; since d ≠ 0: a'*gcdA + b'*gcdB = 1
    have hbez : a * Int.gcdA a b + b * Int.gcdB a b = d := by
      have := Int.gcd_eq_gcd_ab a b
      exact_mod_cast this.symm
    have hprod : d * (a' * Int.gcdA a b + b' * Int.gcdB a b) = d := by
      have : d * a' * Int.gcdA a b + d * b' * Int.gcdB a b = d := by
        rw [← ha', ← hb']; linarith
      linarith [this]
    -- a' * gcdA + b' * gcdB = 1, so IsCoprime a' b' (and gcd a' b' = 1)
    have hone : a' * Int.gcdA a b + b' * Int.gcdB a b = 1 := by
      have hprod' : d * (a' * Int.gcdA a b + b' * Int.gcdB a b) = d * 1 := by
        rw [mul_one]; exact hprod
      exact mul_left_cancel₀ hd_ne hprod'
    -- gcd(a', b') divides the linear combination a'*u + b'*v = 1, so gcd divides 1
    have hdvd1 : (Int.gcd a' b' : ℤ) ∣ 1 := by
      have h := gcd_divides_linear_combination a' b' (Int.gcdA a b) (Int.gcdB a b)
      rwa [hone] at h
    -- From gcd | 1 (as Nat), gcd = 1
    have hdvd1' : Int.gcd a' b' ∣ 1 := by exact_mod_cast hdvd1
    exact Nat.dvd_one.mp hdvd1'
  constructor
  · intro h
    -- a*(x-x₀) + b*(y-y₀) = 0
    have hdiff : a * (x - x₀) + b * (y - y₀) = 0 := by linarith
    -- Divide by d: a'*(x-x₀) + b'*(y-y₀) = 0
    have hdiv_eq : a' * (x - x₀) + b' * (y - y₀) = 0 := by
      have : d * (a' * (x - x₀) + b' * (y - y₀)) = 0 := by
        calc d * (a' * (x - x₀) + b' * (y - y₀))
            = d * a' * (x - x₀) + d * b' * (y - y₀) := by ring
          _ = a * (x - x₀) + b * (y - y₀) := by rw [← ha', ← hb']
          _ = 0 := hdiff
      exact (mul_eq_zero.mp this).resolve_left hd_ne
    -- Apply coprime null space: ∃ t, x-x₀ = b'*t ∧ y-y₀ = -a'*t
    rw [coprime_linear_null_space a' b' hcop'] at hdiv_eq
    obtain ⟨t, htx, hty⟩ := hdiv_eq
    refine ⟨t, ?_, ?_⟩
    · -- x = x₀ + b'*t = x₀ + (b/d)*t
      rw [hbd]; linarith [htx]
    · -- y = y₀ - a'*t = y₀ - (a/d)*t
      rw [had]; linarith [hty]
  · intro ⟨t, hx, hy⟩
    rw [hx, hy, hbd, had]
    -- a * b' = b * a' since a = d * a' and b = d * b'
    have key : a * b' - b * a' = 0 := by rw [ha', hb']; ring
    linear_combination h₀ + key * t

/-! ## Three-Variable Generalization -/

/-- **Bezout's Identity for Three Integers**:
    For any integers a, b, c, there exist integers x, y, z with:
      a * x + b * y + c * z = gcd(gcd(a, b), c)

    Proved by applying Bezout twice:
    First to get d = a*x₀ + b*y₀ = gcd(a,b),
    then to get g = d*u + c*v = gcd(gcd(a,b), c). -/
theorem bezout_three (a b c : ℤ) :
    ∃ x y z : ℤ, a * x + b * y + c * z = Int.gcd (Int.gcd a b) c := by
  have ⟨x₀, y₀, hbez_ab⟩ : ∃ x₀ y₀ : ℤ, (Int.gcd a b : ℤ) = a * x₀ + b * y₀ :=
    ⟨Int.gcdA a b, Int.gcdB a b, Int.gcd_eq_gcd_ab a b⟩
  have ⟨u, v, hbez_dc⟩ : ∃ u v : ℤ, (Int.gcd (Int.gcd a b) c : ℤ) =
      (Int.gcd a b : ℤ) * u + c * v :=
    ⟨Int.gcdA (Int.gcd a b) c, Int.gcdB (Int.gcd a b) c,
     Int.gcd_eq_gcd_ab (Int.gcd a b) c⟩
  exact ⟨x₀ * u, y₀ * u, v, by
    calc a * (x₀ * u) + b * (y₀ * u) + c * v
        = (a * x₀ + b * y₀) * u + c * v := by ring
      _ = (Int.gcd a b : ℤ) * u + c * v := by rw [hbez_ab]
      _ = (Int.gcd (Int.gcd a b) c : ℤ) := by rw [hbez_dc]⟩

/-- **Diophantine Solvability for Three Variables**:
    The equation a*x + b*y + c*z = k has integer solutions if and only if
    gcd(gcd(a, b), c) divides k.

    This extends the two-variable criterion (diophantine_solvable from BezoutIdentity.lean)
    to three variables, characterizing the GCD structure for systems with three generators. -/
theorem diophantine_three_solvable (a b c k : ℤ) :
    (∃ x y z : ℤ, a * x + b * y + c * z = k) ↔
    (Int.gcd (Int.gcd a b) c : ℤ) ∣ k := by
  set g := (Int.gcd (Int.gcd a b) c : ℤ)
  constructor
  · intro ⟨x, y, z, heq⟩
    have hg_dvd_gab : g ∣ (Int.gcd a b : ℤ) :=
      Int.gcd_dvd_left (↑(Int.gcd a b) : ℤ) c
    have hga : g ∣ a := hg_dvd_gab.trans (Int.gcd_dvd_left a b)
    have hgb : g ∣ b := hg_dvd_gab.trans (Int.gcd_dvd_right a b)
    have hgc : g ∣ c := Int.gcd_dvd_right (↑(Int.gcd a b) : ℤ) c
    rw [← heq]
    exact dvd_add (dvd_add (dvd_mul_of_dvd_left hga x) (dvd_mul_of_dvd_left hgb y))
                  (dvd_mul_of_dvd_left hgc z)
  · intro ⟨m, hm⟩
    obtain ⟨x₀, y₀, z₀, hbez⟩ := bezout_three a b c
    exact ⟨m * x₀, m * y₀, m * z₀, by
      calc a * (m * x₀) + b * (m * y₀) + c * (m * z₀)
          = m * (a * x₀ + b * y₀ + c * z₀) := by ring
        _ = m * g := by rw [hbez]
        _ = k := by rw [hm]; ring⟩

/-! ## GCD Minimality: gcd as the Smallest Positive Linear Combination -/

/-- **GCD is the Minimum Positive Linear Combination** (Nat version):
    For natural numbers a, b, gcd(a,b) is the smallest positive integer
    expressible as a*x + b*y for integers x, y.

    This gives a fundamentally different characterization of the GCD:
    not via divisibility, but as the *generator* of the additive subgroup {ax+by : x,y ∈ ℤ}. -/
theorem gcd_eq_min_pos_linear_comb (a b : ℕ) :
    ∀ c : ℕ, c > 0 → (∃ x y : ℤ, (a : ℤ) * x + (b : ℤ) * y = c) →
    Nat.gcd a b ≤ c := by
  intro c hc ⟨x, y, heq⟩
  have hdvd : (Nat.gcd a b : ℤ) ∣ c := by
    have ha : (Nat.gcd a b : ℤ) ∣ (a : ℤ) :=
      Int.natCast_dvd_natCast.mpr (Nat.gcd_dvd_left a b)
    have hb : (Nat.gcd a b : ℤ) ∣ (b : ℤ) :=
      Int.natCast_dvd_natCast.mpr (Nat.gcd_dvd_right a b)
    rw [← heq]
    exact dvd_add (dvd_mul_of_dvd_left ha x) (dvd_mul_of_dvd_left hb y)
  exact Nat.le_of_dvd hc (by exact_mod_cast hdvd)

/-- **GCD is Achieved as a Linear Combination**:
    Bezout's identity shows gcd(a,b) is itself in {ax+by : x,y ∈ ℤ}.
    Combined with gcd_eq_min_pos_linear_comb, this shows gcd(a,b) is the minimum. -/
theorem gcd_achievable (a b : ℕ) :
    ∃ x y : ℤ, (a : ℤ) * x + (b : ℤ) * y = Nat.gcd a b := by
  exact ⟨Nat.gcdA a b, Nat.gcdB a b, by exact_mod_cast (Nat.gcd_eq_gcd_ab a b).symm⟩

/-- **Complete GCD Characterization**:
    A positive integer d equals gcd(a, b) if and only if:
      (1) d is achievable: ∃ x y : ℤ, a*x + b*y = d
      (2) d divides all achievable values: ∀ c, (∃ x y, a*x+b*y=c) → d | c

    Together, (1) and (2) say d is the *generator* of the ideal {ax+by : x,y ∈ ℤ}. -/
theorem gcd_complete_characterization (a b d : ℕ) (hd_pos : 0 < d) :
    ((∃ x y : ℤ, (a : ℤ) * x + (b : ℤ) * y = d) ∧
     (∀ c : ℤ, (∃ x y : ℤ, (a : ℤ) * x + (b : ℤ) * y = c) → (d : ℤ) ∣ c))
    ↔ d = Nat.gcd a b := by
  constructor
  · intro ⟨⟨x, y, hachieve⟩, hdivides⟩
    -- d | gcd(a,b): d divides all achievable values, and gcd(a,b) is achievable
    have hd_dvd_gcd : d ∣ Nat.gcd a b := by
      have h := hdivides ↑(Nat.gcd a b)
        ⟨Nat.gcdA a b, Nat.gcdB a b, by exact_mod_cast (Nat.gcd_eq_gcd_ab a b).symm⟩
      exact_mod_cast h
    -- gcd(a,b) | d: gcd divides a and b, so divides a*x + b*y = d
    have hgcd_dvd_d : Nat.gcd a b ∣ d := by
      have ha : (Nat.gcd a b : ℤ) ∣ (a : ℤ) :=
        Int.natCast_dvd_natCast.mpr (Nat.gcd_dvd_left a b)
      have hb : (Nat.gcd a b : ℤ) ∣ (b : ℤ) :=
        Int.natCast_dvd_natCast.mpr (Nat.gcd_dvd_right a b)
      have hdvd : (Nat.gcd a b : ℤ) ∣ (d : ℤ) := by
        rw [← hachieve]
        exact dvd_add (dvd_mul_of_dvd_left ha x) (dvd_mul_of_dvd_left hb y)
      exact_mod_cast hdvd
    exact Nat.dvd_antisymm hd_dvd_gcd hgcd_dvd_d
  · intro hd_eq
    subst hd_eq
    refine ⟨gcd_achievable a b, ?_⟩
    intro c ⟨x, y, heq⟩
    have ha : (Nat.gcd a b : ℤ) ∣ (a : ℤ) :=
      Int.natCast_dvd_natCast.mpr (Nat.gcd_dvd_left a b)
    have hb : (Nat.gcd a b : ℤ) ∣ (b : ℤ) :=
      Int.natCast_dvd_natCast.mpr (Nat.gcd_dvd_right a b)
    rw [← heq]
    exact dvd_add (dvd_mul_of_dvd_left ha x) (dvd_mul_of_dvd_left hb y)

/-! ## Summary: The Answer to OQ-04 -/

/-
The question was: "Extend the Diophantine criterion to characterize GCD structure."

## The Complete Picture

The GCD of a and b organizes the solutions to ax + by = c into a precise structure:

1. **Solvability** (from BezoutIdentity.lean):
   ax + by = c has solutions ↔ gcd(a,b) | c

2. **Solution set structure** (diophantine_complete_parameterization, this file):
   If (x₀, y₀) is one solution, ALL solutions are (x₀ + b/d·t, y₀ - a/d·t) for t ∈ ℤ
   The solution set is an arithmetic progression with step (b/d, -a/d).

3. **Null space** (coprime_linear_null_space, this file):
   Solutions to ax + by = 0 (with gcd(a,b) = 1) are exactly (b·t, -a·t).
   The null space is a 1D integer lattice.

4. **GCD minimality** (gcd_eq_min_pos_linear_comb, this file):
   gcd(a,b) is the SMALLEST positive integer expressible as ax + by.

5. **Complete characterization** (gcd_complete_characterization, this file):
   d = gcd(a,b) ↔ d is achievable AND d divides all achievable values.
   The GCD is characterized as the GENERATOR of the ideal {ax+by}.

6. **Three-variable extension** (diophantine_three_solvable, this file):
   ax + by + cz = k has solutions ↔ gcd(gcd(a,b), c) | k.
   The criterion extends inductively to any number of variables.

## Mathematical Insight

The GCD is not merely a divisibility concept — it is the IDEAL GENERATOR.
The equation ax + by = c "tests" whether c belongs to the ideal generated by a and b.
The complete solution set is the fiber of this ideal-membership test.
-/

#check gcd_divides_linear_combination
#check coprime_linear_null_space
#check diophantine_complete_parameterization
#check bezout_three
#check diophantine_three_solvable
#check gcd_eq_min_pos_linear_comb
#check gcd_achievable
#check gcd_complete_characterization

end BezoutIdentityOQ04
