import Mathlib

/-
# Multivariate Bézout Identity in Bézout Rings

## Open Question Origin

From bezout-identity-oq-02-oq-02-oq-01 (Constructive Divisibility Algorithm):
"Can the algorithm be extended to multivariate Bézout identities in
polynomial rings?"

## Answer: YES over any Bézout ring (so over F[X]); NO in genuine multivariate rings.

The two-element Bézout identity `u * a + v * b = gcd a b` generalizes to a
*finite family* `a : ι → R` in any **Bézout ring** `R` (a commutative ring in
which every finitely generated ideal is principal). There is a single element
`d` — a greatest common divisor of the family — together with coefficients
`u : ι → R` such that

    ∑ i, u i * a i = d,

`d` divides every `a i`, and every common divisor of the family divides `d`.

The proof is structural rather than algorithmic: the ideal generated by the
range of `a` is finitely generated (the index type is finite), hence principal
by the Bézout hypothesis; its generator is the sought `d`, and membership of `d`
in the span produces the explicit coefficient vector.

Because *univariate* polynomial rings `F[X]` over a field are Euclidean domains
— hence principal ideal rings, hence Bézout — the identity specializes directly
to the polynomial setting the open question asks about. It also specializes to
`ℤ` and to any principal ideal domain.

This entry works over an arbitrary `IsBezout` commutative ring; no integral
domain hypothesis is needed, since both the divisibility and the universal
property follow from the linear combination itself.

**The sharp boundary (Part VII).** The affirmative answer is exactly as wide as
the Bézout hypothesis, and no wider. *Genuine* multivariate polynomial rings
`F[x₁,…,xₙ]` with `n ≥ 2` are **not** Bézout rings — not even principal ideal
domains — so the identity fails there. We exhibit the obstruction concretely in
`F[x, y] = MvPolynomial (Fin 2) F`: the variables `X` and `Y` share no common
non-unit factor, yet the constant polynomial `1` is **not** an `F[x,y]`-linear
combination of `X` and `Y`, because every element of the ideal `(X, Y)` has zero
constant term. Hence there are no cofactors `f, g` with `f·X + g·Y = 1`, and the
extended Euclidean / Bézout construction genuinely does not survive the passage
to more than one variable.
-/

namespace BezoutIdentityOQ02OQ02OQ01OQ02

open scoped BigOperators

/-
## Part I: The Ideal Generated by a Finite Family is Principal

Over a Bézout ring, the ideal spanned by the (finite) range of a family is
finitely generated, hence principal.  We isolate its generator `familyGcd`.
-/

/-- A greatest common divisor of a finite family `a : ι → R` over a Bézout ring:
the generator of the ideal `Ideal.span (Set.range a)`. -/
noncomputable def familyGcd {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Finite ι] (a : ι → R) : R :=
  haveI : (Ideal.span (Set.range a)).IsPrincipal :=
    IsBezout.isPrincipal_of_FG _ (Submodule.fg_span (Set.finite_range a))
  Submodule.IsPrincipal.generator (Ideal.span (Set.range a))

/-- The span of the range of `a` is principal, generated by `familyGcd a`. -/
theorem span_range_eq_span_familyGcd {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Finite ι] (a : ι → R) :
    Ideal.span (Set.range a) = Ideal.span {familyGcd a} := by
  haveI hprin : (Ideal.span (Set.range a)).IsPrincipal :=
    IsBezout.isPrincipal_of_FG _ (Submodule.fg_span (Set.finite_range a))
  rw [familyGcd]
  exact (Submodule.IsPrincipal.span_singleton_generator (Ideal.span (Set.range a))).symm

/-- `familyGcd a` lies in the ideal it generates. -/
theorem familyGcd_mem_span {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Finite ι] (a : ι → R) :
    familyGcd a ∈ Ideal.span (Set.range a) := by
  rw [span_range_eq_span_familyGcd]
  exact Ideal.subset_span (Set.mem_singleton _)

/-
## Part II: The Multivariate Bézout Identity

`familyGcd a` is an explicit `R`-linear combination of the `a i`.
-/

/-- **Existence of Bézout coefficients**: over a Bézout ring, for any finite
family `a : ι → R` there is a coefficient vector `u : ι → R` with
`∑ i, u i * a i = familyGcd a`.

This is the multivariate generalization of `u * a + v * b = gcd a b`. -/
theorem exists_bezout_coeffs {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Fintype ι] (a : ι → R) :
    ∃ u : ι → R, ∑ i, u i * a i = familyGcd a := by
  have hmem : familyGcd a ∈ Submodule.span R (Set.range a) := familyGcd_mem_span a
  rw [Submodule.mem_span_range_iff_exists_fun] at hmem
  obtain ⟨u, hu⟩ := hmem
  exact ⟨u, by simpa only [smul_eq_mul] using hu⟩

/-
## Part III: The Divisibility Properties of `familyGcd`
-/

/-- `familyGcd a` divides every member of the family. -/
theorem familyGcd_dvd {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Finite ι] (a : ι → R) (i : ι) :
    familyGcd a ∣ a i := by
  have hmem : a i ∈ Ideal.span {familyGcd a} := by
    rw [← span_range_eq_span_familyGcd]
    exact Ideal.subset_span ⟨i, rfl⟩
  rwa [Ideal.mem_span_singleton] at hmem

/-- **Universal property**: any common divisor of the family divides
`familyGcd a`.  This holds because `familyGcd a` is a linear combination of the
`a i` (Part II), and a common divisor divides every term of that combination. -/
theorem dvd_familyGcd {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Fintype ι] (a : ι → R) (c : R) (hc : ∀ i, c ∣ a i) :
    c ∣ familyGcd a := by
  obtain ⟨u, hu⟩ := exists_bezout_coeffs a
  rw [← hu]
  exact Finset.dvd_sum (fun i _ => (hc i).mul_left (u i))

/-
## Part IV: The Assembled Multivariate Bézout Theorem

We package Parts II–III into one statement asserting the full gcd-as-linear-
combination phenomenon.
-/

/-- **Multivariate Bézout identity** (main theorem).  Over a Bézout ring `R`,
every finite family `a : ι → R` admits a greatest common divisor `d` expressible
as an explicit `R`-linear combination of the family:

* `∑ i, u i * a i = d`   (Bézout identity),
* `d ∣ a i` for all `i`   (`d` is a common divisor),
* `∀ c, (∀ i, c ∣ a i) → c ∣ d`   (`d` is greatest).

No integral-domain hypothesis is required. -/
theorem multivariate_bezout {R : Type*} [CommRing R] [IsBezout R]
    {ι : Type*} [Fintype ι] (a : ι → R) :
    ∃ (d : R) (u : ι → R),
      (∑ i, u i * a i = d) ∧
      (∀ i, d ∣ a i) ∧
      (∀ c : R, (∀ i, c ∣ a i) → c ∣ d) := by
  obtain ⟨u, hu⟩ := exists_bezout_coeffs a
  exact ⟨familyGcd a, u, hu, familyGcd_dvd a, dvd_familyGcd a⟩

/-- Any two witnesses satisfying the gcd universal property are associated (each
divides the other).  In particular the greatest common divisor produced by
`multivariate_bezout` is unique up to units. -/
theorem gcd_witness_unique {R : Type*} [CommRing R]
    {ι : Type*} (a : ι → R) {d d' : R}
    (hd : (∀ i, d ∣ a i) ∧ (∀ c : R, (∀ i, c ∣ a i) → c ∣ d))
    (hd' : (∀ i, d' ∣ a i) ∧ (∀ c : R, (∀ i, c ∣ a i) → c ∣ d')) :
    d ∣ d' ∧ d' ∣ d :=
  ⟨hd'.2 d hd.1, hd.2 d' hd'.1⟩

/-
## Part V: Specialization to Polynomial Rings

The open question specifically asks about polynomial rings.  For a field `F`,
`Polynomial F` is a Euclidean domain, hence a principal ideal ring, hence a
Bézout ring, so the multivariate identity applies verbatim.
-/

/-- **Multivariate Bézout in polynomial rings** `F[X]` over a field `F`.  For any
finite family of polynomials there is a gcd polynomial expressed as an explicit
polynomial-linear combination of the family. -/
theorem multivariate_bezout_polynomial {F : Type*} [Field F]
    {ι : Type*} [Fintype ι] (a : ι → Polynomial F) :
    ∃ (d : Polynomial F) (u : ι → Polynomial F),
      (∑ i, u i * a i = d) ∧
      (∀ i, d ∣ a i) ∧
      (∀ c : Polynomial F, (∀ i, c ∣ a i) → c ∣ d) :=
  multivariate_bezout a

/-- **Multivariate Bézout over `ℤ`**: the classical statement that the gcd of a
finite list of integers is an integer-linear combination of them. -/
theorem multivariate_bezout_int {ι : Type*} [Fintype ι] (a : ι → ℤ) :
    ∃ (d : ℤ) (u : ι → ℤ),
      (∑ i, u i * a i = d) ∧
      (∀ i, d ∣ a i) ∧
      (∀ c : ℤ, (∀ i, c ∣ a i) → c ∣ d) :=
  multivariate_bezout a

/-
## Part VI: Computational Verification (concrete three-element identities)

The abstract generator is `noncomputable`, but we can exhibit explicit Bézout
combinations for concrete families, confirming the multivariate identity by
direct calculation.
-/

/-- `gcd(6, 10, 15) = 1`, witnessed by `1·6 + (-2)·10 + 1·15 = 1`. -/
example : (1 : ℤ) * 6 + (-2) * 10 + 1 * 15 = 1 := by norm_num

/-- `gcd(4, 6, 9) = 1`, witnessed by `1·4 + (-2)·6 + 1·9 = 1`. -/
example : (1 : ℤ) * 4 + (-2) * 6 + 1 * 9 = 1 := by norm_num

/-- A polynomial example over `ℚ`: the pair `X` and `X + 1` is coprime, and
`(-1)·X + 1·(X + 1) = 1`, exhibiting the constant polynomial `1` as a gcd. -/
example : (-1 : Polynomial ℚ) * Polynomial.X + 1 * (Polynomial.X + 1) = 1 := by
  ring

/-
## Part VII: The Sharp Boundary — Genuine Multivariate Rings are not Bézout

The affirmative results above rest entirely on the `IsBezout` hypothesis, and
`F[x₁,…,xₙ]` fails it for `n ≥ 2`.  We make the failure explicit in
`F[x, y] = MvPolynomial (Fin 2) F`.  `X` and `Y` are coprime (they share no
common non-unit factor), yet `1 ∉ (X, Y)`, so no Bézout identity
`f·X + g·Y = 1` exists.  The witness is the constant-coefficient homomorphism:
every element of `(X, Y)` has zero constant term.
-/

open MvPolynomial

/-- The generating pair `{X 0, X 1}` lies in the kernel of the
constant-coefficient homomorphism, so the whole ideal it spans does. -/
theorem span_X_le_ker_constantCoeff {F : Type*} [CommRing F] :
    Ideal.span {X (0 : Fin 2), X 1} ≤
      RingHom.ker (constantCoeff : MvPolynomial (Fin 2) F →+* F) := by
  rw [Ideal.span_le]
  intro x hx
  rcases hx with h | h
  · rw [h, SetLike.mem_coe, RingHom.mem_ker, constantCoeff_X]
  · rw [Set.mem_singleton_iff] at h
    rw [h, SetLike.mem_coe, RingHom.mem_ker, constantCoeff_X]

/-- **Boundary theorem.** In `F[x, y]` (for a nontrivial commutative ring `F`)
the constant polynomial `1` is *not* a linear combination of `X` and `Y`, even
though `X` and `Y` are coprime.  This is the concrete obstruction stopping the
Bézout identity from extending to genuine multivariate polynomial rings. -/
theorem one_not_mem_span_X_Y {F : Type*} [CommRing F] [Nontrivial F] :
    (1 : MvPolynomial (Fin 2) F) ∉ Ideal.span {X (0 : Fin 2), X 1} := by
  intro h
  have hker : (1 : MvPolynomial (Fin 2) F) ∈
      RingHom.ker (constantCoeff : MvPolynomial (Fin 2) F →+* F) :=
    span_X_le_ker_constantCoeff h
  rw [RingHom.mem_ker, map_one] at hker
  exact one_ne_zero hker

/-- Restated as the impossibility of the two-generator Bézout identity in
`F[x, y]`: there are no cofactors `f, g` with `f * X + g * Y = 1`.  Contrast
with `multivariate_bezout_polynomial`, which *does* hold in the univariate ring
`F[X]`. -/
theorem no_bezout_identity_X_Y {F : Type*} [CommRing F] [Nontrivial F] :
    ¬ ∃ f g : MvPolynomial (Fin 2) F, f * X 0 + g * X 1 = 1 := by
  rintro ⟨f, g, hfg⟩
  refine one_not_mem_span_X_Y (F := F) ?_
  rw [← hfg]
  exact Ideal.add_mem _
    (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))
    (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp)))

end BezoutIdentityOQ02OQ02OQ01OQ02
