/-
  Bézout's Identity in Bézout Rings (OQ-04-OQ-02-OQ-01)

  Source: bezout-identity-oq-04-oq-02-oq-01
  Status: PROVED (0 sorries, 0 axioms)

  **Question** (from the parent OQ-04-OQ-02): Can the GCD complete characterization
  `∃ x y, a*x + b*y = c ↔ gcd(a,b) ∣ c` be stated for `IsBezout` domains instead of
  `EuclideanDomain`? And what is the *minimal* Mathlib typeclass for which it holds?

  **Answer**: YES — and the minimal hypothesis is even weaker than "IsBezout domain":
  it is simply `[CommRing R] [IsBezout R]`. No `IsDomain`, no Euclidean structure, no
  `DecidableEq`, and no `GCDMonoid` are required.

  A **Bézout ring** is a commutative ring in which every finitely generated ideal is
  principal (Mathlib's `IsBezout`). This is strictly more general than a Euclidean
  domain: it drops the Euclidean (division-with-remainder) algorithm, drops
  Noetherianity, and even drops the domain axiom. Notable examples that are Bézout but
  NOT Euclidean domains include valuation rings (Mathlib: `ValuationRing → IsBezout`)
  and the ring of all algebraic integers.

  The mechanism is Mathlib's abstract gcd for Bézout rings, `IsBezout.gcd a b`, defined
  as a *generator of the (principal) ideal `span {a, b}`*. Where the parent used the
  concrete extended-Euclidean coefficients `gcd_eq_gcd_ab`, we use the ideal-theoretic
  Bézout witness `IsBezout.gcd_eq_sum`.

  Why `IsBezout` and not merely a UFD: ℤ[X] is a UFD with `gcd(2, X) = 1`, yet
  `1 ∉ {2f + Xg}`. The linear-combination (Bézout) property is exactly what distinguishes
  Bézout rings among gcd rings.
-/

import Mathlib

namespace BezoutIdentityOQ04OQ02OQ01

variable {R : Type*} [CommRing R] [IsBezout R]

open IsBezout

/-!
## Part I: Core Lemmas

In a Bézout ring, `IsBezout.gcd a b` is a generator of `Ideal.span {a, b}`.
The instance `IsBezout.span_pair_isPrincipal` makes this well-defined for every pair.
-/

/-- In any Bézout ring, `gcd(a, b)` divides every linear combination `a*x + b*y`. -/
theorem gcd_dvd_linear_combination (a b x y : R) :
    gcd a b ∣ a * x + b * y :=
  dvd_add (dvd_mul_of_dvd_left (gcd_dvd_left a b) x)
           (dvd_mul_of_dvd_left (gcd_dvd_right a b) y)

/-- **Bézout's Identity in a Bézout ring**:
    `gcd(a, b)` is itself a linear combination of `a` and `b`.
    This is the ideal-theoretic witness `IsBezout.gcd_eq_sum`, reoriented so the
    coefficients sit on the right of `a` and `b` (matching the parent's convention). -/
theorem gcd_achievable_Bezout (a b : R) :
    ∃ x y : R, a * x + b * y = gcd a b := by
  obtain ⟨u, v, huv⟩ := gcd_eq_sum a b
  exact ⟨u, v, by rw [← huv]; ring⟩

/-!
## Part II: Main Characterization
-/

/-- **Generalized Bézout (OQ-04-OQ-02-OQ-01)**:
    In any Bézout ring, `c` is a linear combination of `a` and `b`
    if and only if `gcd(a, b)` divides `c`.

    This is the exact analogue of the parent's `linear_combination_iff_gcd_dvd`, but
    with `EuclideanDomain` weakened all the way to `[CommRing R] [IsBezout R]`. -/
theorem linear_combination_iff_gcd_dvd (a b c : R) :
    (∃ x y : R, a * x + b * y = c) ↔ gcd a b ∣ c := by
  constructor
  · rintro ⟨x, y, rfl⟩
    exact gcd_dvd_linear_combination a b x y
  · rintro ⟨k, hk⟩
    -- Bézout: ∃ u v, u*a + v*b = gcd a b, so c = gcd*k = a*(k*u) + b*(k*v).
    obtain ⟨u, v, huv⟩ := gcd_eq_sum a b
    exact ⟨k * u, k * v, by rw [hk, ← huv]; ring⟩

/-- **Complete GCD characterization in a Bézout ring** (cf. parent OQ-04-OQ-02 for ED):
    `d` satisfies achievability and universality iff `d` and `gcd(a, b)` divide each
    other (i.e. `d` is associated to `gcd(a, b)`). -/
theorem gcd_complete_characterization_Bezout (a b d : R) :
    ((∃ x y : R, a * x + b * y = d) ∧
     (∀ c : R, (∃ x y : R, a * x + b * y = c) → d ∣ c))
    ↔ (d ∣ gcd a b ∧ gcd a b ∣ d) := by
  simp_rw [linear_combination_iff_gcd_dvd]
  constructor
  · intro ⟨h_achieve, h_divides⟩
    exact ⟨h_divides _ (dvd_refl _), h_achieve⟩
  · intro ⟨hd_gcd, hgcd_d⟩
    exact ⟨hgcd_d, fun c hc => dvd_trans hd_gcd hc⟩

/-!
## Part III: Corollaries
-/

/-- `gcd(a, b)` itself satisfies both achievability and universality. -/
theorem gcd_characterizes_ideal (a b : R) :
    (∃ x y : R, a * x + b * y = gcd a b) ∧
    (∀ c : R, (∃ x y : R, a * x + b * y = c) → gcd a b ∣ c) :=
  (gcd_complete_characterization_Bezout a b (gcd a b)).mpr ⟨dvd_refl _, dvd_refl _⟩

/-- **Structural essence of a Bézout ring**: the ideal of all linear combinations of
    `a` and `b` is *principal*, generated by `gcd(a, b)`. This is the ideal-theoretic
    restatement of the whole characterization and is the property that fails in a
    general UFD such as ℤ[X]. -/
theorem span_pair_eq_span_gcd (a b : R) :
    Ideal.span ({a, b} : Set R) = Ideal.span {gcd a b} :=
  (span_gcd a b).symm

/-- **Coprimality via the gcd**: in a Bézout ring, `a` and `b` are coprime
    (`∃ u v, u*a + v*b = 1`) exactly when their gcd is a unit. -/
theorem isCoprime_iff_gcd_isUnit (a b : R) :
    IsCoprime a b ↔ IsUnit (gcd a b) := by
  rw [isUnit_iff_dvd_one, ← linear_combination_iff_gcd_dvd]
  constructor
  · rintro ⟨u, v, h⟩
    exact ⟨u, v, by rw [← h]; ring⟩
  · rintro ⟨x, y, h⟩
    exact ⟨x, y, by rw [← h]; ring⟩

/-!
## Part IV: Placement in the algebraic hierarchy
-/

-- Every Euclidean domain is a Bézout ring, so this file subsumes the parent OQ-04-OQ-02.
example {R : Type*} [EuclideanDomain R] : IsBezout R := inferInstance

-- More: every principal ideal ring is a Bézout ring (this is where the domain axiom is
-- dropped — `IsPrincipalIdealRing` needs no `IsDomain`).
example {R : Type*} [CommRing R] [IsPrincipalIdealRing R] : IsBezout R := inferInstance

-- A genuinely non-Euclidean witness: every valuation ring is Bézout. Valuation rings of
-- non-discrete valuations are not Noetherian, hence not PIDs and not Euclidean domains,
-- yet the characterization above applies to them verbatim.
example {R : Type*} [CommRing R] [IsDomain R] [ValuationRing R] : IsBezout R := inferInstance

/-!
## Part V: Concrete examples in ℤ

ℤ is a Euclidean domain, hence a Bézout ring, so all theorems above specialize to it.
These existential witnesses (which do not mention the noncomputable `IsBezout.gcd`)
demonstrate the characterization concretely.
-/

/-- gcd(6, 15) ∼ 3, and 3 = 6*(-2) + 15*1 (Bézout coefficients). -/
example : ∃ x y : ℤ, 6 * x + 15 * y = 3 := ⟨-2, 1, by norm_num⟩

/-- 3 ∣ 6, so 6 is achievable from {6, 15}. -/
example : ∃ x y : ℤ, 6 * x + 15 * y = 6 := ⟨1, 0, by norm_num⟩

/-- 4 is NOT achievable from {6, 15}: gcd(6, 15) ∼ 3 and 3 ∤ 4. -/
example : ¬ ∃ x y : ℤ, 6 * x + 15 * y = 4 := by
  rintro ⟨x, y, h⟩; omega

/-- gcd(7, 5) ∼ 1: 7 and 5 are coprime, so every integer is a linear combination.
    Bézout coefficients: 7 * 3 + 5 * (-4) = 1. -/
example (c : ℤ) : ∃ x y : ℤ, 7 * x + 5 * y = c := ⟨3 * c, -4 * c, by ring⟩

/-!
## Summary
-/

/-
OQ-04-OQ-02-OQ-01 is **resolved** (0 axioms, 0 sorries):

**Answer**: YES — the GCD complete characterization generalizes to Bézout rings, and the
minimal Mathlib typeclass is `[CommRing R] [IsBezout R]`. Compared to the parent
(`EuclideanDomain`) this drops:
  • the Euclidean (division-with-remainder) algorithm,
  • Noetherianity / the PID structure,
  • the integral-domain axiom, and
  • `DecidableEq` / `GCDMonoid` (the gcd here is noncomputable).

Key results:
- `linear_combination_iff_gcd_dvd`: ∃ x y, a*x+b*y = c ↔ gcd(a,b) ∣ c, using the
  ideal-theoretic Bézout witness `IsBezout.gcd_eq_sum` in place of `gcd_eq_gcd_ab`.
- `gcd_complete_characterization_Bezout`: d ∼ gcd(a,b) ↔ achievability + universality.
- `span_pair_eq_span_gcd`: span{a,b} = span{gcd(a,b)} — the ideal of linear combinations
  is principal. This is exactly the property that fails in a UFD like ℤ[X].
- `isCoprime_iff_gcd_isUnit`: IsCoprime a b ↔ IsUnit (gcd a b).

Why NOT just a UFD: ℤ[X] is a UFD, gcd(2, X) = 1, but 1 ∉ {2f + Xg}. The Bézout
(linear-combination) property is precisely `IsBezout`.
-/

#check @linear_combination_iff_gcd_dvd
#check @gcd_complete_characterization_Bezout
#check @span_pair_eq_span_gcd
#check @isCoprime_iff_gcd_isUnit

end BezoutIdentityOQ04OQ02OQ01
