import Mathlib.Data.Real.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.CrossProduct
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.Tactic

/-
# Pascal's hexagon theorem — Aristotle companion for `BrianchonTheorem.lean`

`BrianchonTheorem.lean` proves Brianchon's theorem in the projective ℝ³ model,
modulo a single axiom `conic_implies_pascal`: six points on a symmetric conic make
the three intersections of opposite sides of the inscribed hexagon collinear
(Pascal's hexagon theorem / a Cayley–Bacharach instance). The same fact is
axiomatized by the gallery's `PascalsHexagon.lean` as
`conic_implies_pascal_constraint`.

This companion restates that axiom as an ordinary `theorem ... := by sorry` so the
Aristotle proof-search engine can attempt it (Aristotle skips `axiom`
declarations). A successful proof here would let us discharge the shared Pascal
axiom in BOTH the Brianchon and Pascal gallery entries.

## Proof strategy (research note, 2026-06-19)

Numerical evidence (200k+ random hexagons, for rank-1 double lines, rank-2 line
pairs, the standard conic `diag(1,1,-1)`, and random nondegenerate symmetric
conics; normalized `det(P,Q,R)` residuals 1e-9 … 1e-28) shows the *determinant
form* of the conclusion below holds for **every** symmetric conic `C`, with **no
nondegeneracy or point-validity hypothesis**. Hence `conic_implies_pascal` is a
genuine **polynomial identity**: `det(P,Q,R)` lies in the ideal generated by the
six conic equations `conicQuadraticForm C (hex.A) = 0, …`. Two consequences:

* The gallery axiom is *sound as stated* — there is no missing-hypothesis bug.
* The discharge does **not** require Sylvester's law of inertia / reduction to
  the standard conic (the route scaffolded in `PascalsHexagon.lean` via
  `sylvester_stdConic_of_isotropic`, which needs nondegeneracy + a real point).
  A direct ideal-membership / `linear_combination` proof in the six quadratic
  hypotheses should exist and is preferable. The cofactors are degree ≈10
  polynomials in the 18 coordinates and the entries of `C`; finding them is the
  task delegated here.

Suggested tactics: expand `collinear`/`lineIntersection`/`lineThrough` to
coordinates, then `linear_combination` of the six `hex.h?` hypotheses (or
`polyrith`), using symmetry `hC` to fold `C i j`/`C j i`.

The model (identical to `BrianchonTheorem.lean`):
* projective points/lines are vectors in `ℝ³`;
* join of points / meet of lines is the cross product;
* three points are collinear iff the `3×3` determinant of their rows vanishes;
* a conic is a symmetric `3×3` matrix `C`, and `p` lies on it iff `pᵀ C p = 0`.

The Pascal hypothesis is carried by the six `pointOnConic` fields of
`ContactHexagon`; the goal is the collinearity of the three Pascal points.

This file is intended to contain EXACTLY ONE `sorry` (the Pascal theorem). Every
supporting declaration is a complete definition.
-/

set_option linter.unusedVariables false

open Matrix

namespace BrianchonAristotle

/-- A projective point: a (nonzero) vector in `ℝ³`. -/
abbrev ProjPoint := Fin 3 → ℝ

/-- A projective line: a (nonzero) covector in `ℝ³`. -/
abbrev ProjLine := Fin 3 → ℝ

/-- The line through two points is their cross product. -/
noncomputable def lineThrough (p q : ProjPoint) : ProjLine := crossProduct p q

/-- The meet of two lines is their cross product. -/
noncomputable def lineIntersection (l m : ProjLine) : ProjPoint := crossProduct l m

/-- The `3×3` matrix whose rows are the three given vectors. -/
def threeVectorMatrix (u v w : Fin 3 → ℝ) : Matrix (Fin 3) (Fin 3) ℝ :=
  Matrix.of fun i j =>
    match i with
    | 0 => u j
    | 1 => v j
    | 2 => w j

/-- Three points are collinear iff their coordinate determinant vanishes. -/
def collinear (p q r : ProjPoint) : Prop := (threeVectorMatrix p q r).det = 0

/-- A conic is a symmetric `3×3` matrix `C`; a point `p` lies on it iff
`pᵀ C p = 0`. -/
abbrev Conic := Matrix (Fin 3) (Fin 3) ℝ

/-- The conic's quadratic form `pᵀ C p`. -/
noncomputable def conicQuadraticForm (C : Conic) (p : ProjPoint) : ℝ :=
  ∑ i, ∑ j, C i j * p i * p j

/-- A point lies on a conic iff its quadratic form vanishes. -/
def pointOnConic (p : ProjPoint) (C : Conic) : Prop := conicQuadraticForm C p = 0

/-- `C` is symmetric (`Cᵢⱼ = Cⱼᵢ`). -/
def Conic.symmetric (C : Conic) : Prop := ∀ i j, C i j = C j i

/-- Six contact points on a conic `C`. -/
structure ContactHexagon (C : Conic) where
  A : ProjPoint
  B : ProjPoint
  C' : ProjPoint
  D : ProjPoint
  E : ProjPoint
  F : ProjPoint
  hA : pointOnConic A C
  hB : pointOnConic B C
  hC : pointOnConic C' C
  hD : pointOnConic D C
  hE : pointOnConic E C
  hF : pointOnConic F C

/-- **Pascal's hexagon theorem** (projective ℝ³ model).

Six points `A, B, C', D, E, F` lying on a symmetric conic `C` make the three
intersections of opposite sides of the hexagon `A B C' D E F` collinear:

* `AB ∩ DE`,
* `BC' ∩ EF`,
* `C'D ∩ FA`

lie on a common line (the Pascal line).

This is the single fact `BrianchonTheorem.lean` and `PascalsHexagon.lean`
axiomatize. Proving it here (Cayley–Bacharach / a determinant identity using the
six conic constraints) would discharge that shared axiom. -/
theorem conic_implies_pascal (C : Conic) (hC : C.symmetric) (hex : ContactHexagon C) :
    collinear
      (lineIntersection (lineThrough hex.A hex.B) (lineThrough hex.D hex.E))
      (lineIntersection (lineThrough hex.B hex.C') (lineThrough hex.E hex.F))
      (lineIntersection (lineThrough hex.C' hex.D) (lineThrough hex.F hex.A)) := by
  sorry

end BrianchonAristotle
