/-
# Cyclic Specialization: cyc(rotation r) = gcd(n, r), and k^{gcd(n,r)} Fixed Colorings
## (burnside-counting-oq-03-oq-02-oq-01)

**Open question** (from `burnside-counting-oq-03-oq-02`): the parent proves the
group-agnostic master formula `#(colorings fixed by g) = k ^ cyc g`, where
`cyc g = Nat.card (orbitRel.Quotient ⟨g⟩ X)` is the number of `⟨g⟩`-orbits on the
positions. Specialize this to the **cyclic rotation action** of `ZMod n` on an
`n`-bead necklace and recover the classical count.

Write the cyclic group multiplicatively as `Rot n := Multiplicative (ZMod n)` so the
parent's *multiplicative* Burnside machinery applies verbatim, and let it act on itself
(the `n` positions) by translation: `g • x = g * x`, i.e. rotation. For `r : ZMod n` the
**rotation by `r`** is `rotation r := Multiplicative.ofAdd r`. We prove:

* **(A) Cycle count** (`cyc_rotation`):
    `cyc (rotation r) = Nat.gcd n r.val`.
  The rotation `r` partitions the `n` positions into exactly `gcd(n, r)` cycles, each of
  length `n / gcd(n, r)` (the additive order of `r`). Proof: the `⟨r⟩`-orbit quotient is
  the coset space `Rot n ⧸ ⟨r⟩` (Mathlib's `equivSubgroupOrbitsQuotientGroup`, valid since
  translation is pretransitive and cancellative), so `cyc (rotation r) = ⟨r⟩.index`. Lagrange
  (`card_mul_index`) plus `|⟨r⟩| = addOrderOf r = n / gcd(n,r)` (`ZMod.addOrderOf_coe`) give
  `index = gcd(n, r)`.

* **(B) Fixed colorings** (`card_fixedColorings_rotation`):
    `#(colorings fixed by rotation r) = k ^ gcd(n, r)`,
  immediate from `(A)` and the parent's `card_fixedBy_eq_pow_cyc`.

* **(C) Cyclic necklace counting** (`sum_pow_gcd_eq_card_necklaces_mul`):
    `∑_{r : ZMod n} k ^ gcd(n, r) = (#necklaces up to rotation) * n`,
  the classical Burnside count of `k`-colored `n`-bead necklaces in integer form, obtained by
  reindexing the parent's `sum_pow_cyc_eq_card_orbits_mul_card` along `Multiplicative.toAdd`.

This grounds the general `k ^ cyc g` formula in the concrete number-theoretic value
`k ^ gcd(n,r)` that drives every cyclic necklace count in the gallery.

**Sorry count**: 0. **Axiom count**: 0 (only Lean/Mathlib foundational axioms).
-/

import Mathlib
import Proofs.BurnsideCountingOQ03OQ02

open MulAction Subgroup BigOperators

namespace BurnsideCountingOQ03OQ02OQ01

open BurnsideCountingOQ03OQ02 (cyc card_fixedBy_eq_pow_cyc sum_pow_cyc_eq_card_orbits_mul_card)

/-! ## Section I: The cyclic rotation action

`Rot n` is the cyclic group of `n` rotations, written multiplicatively so the parent's
multiplicative `cyc`/Burnside machinery applies directly. It acts on itself — the `n`
necklace positions — by left translation `g • x = g * x`, i.e. rotation. -/

/-- The cyclic group of `n` rotations (as a set, `ZMod n`; written multiplicatively). -/
abbrev Rot (n : ℕ) := Multiplicative (ZMod n)

/-- The rotation by `r`: shift every position by `r`. -/
def rotation {n : ℕ} (r : ZMod n) : Rot n := Multiplicative.ofAdd r

variable {n : ℕ} [NeZero n]

/-- The necklace has exactly `n` positions. -/
lemma card_rot : Nat.card (Rot n) = n := by
  rw [Nat.card_eq_fintype_card]
  simp [ZMod.card]

/-! ## Section II: (A) The cycle count `cyc (rotation r) = gcd(n, r)` -/

/-- The size of the cyclic subgroup generated by `rotation r` is the additive order of `r`,
namely `n / gcd(n, r)`. -/
lemma card_zpowers_rotation (r : ZMod n) :
    Nat.card (zpowers (rotation r)) = n / Nat.gcd n r.val := by
  rw [Nat.card_zpowers, rotation, orderOf_ofAdd_eq_addOrderOf]
  conv_lhs => rw [← ZMod.natCast_zmod_val (a := r)]
  exact ZMod.addOrderOf_coe r.val (NeZero.ne n)

/-- **(A)** The rotation by `r` decomposes the `n` positions into exactly `gcd(n, r)`
cycles (orbits of `⟨r⟩`). -/
theorem cyc_rotation (r : ZMod n) :
    cyc (X := Rot n) (rotation r) = Nat.gcd n r.val := by
  -- Step 1: cyc = index of ⟨rotation r⟩ via the orbit ↔ coset equivalence.
  have hidx : cyc (X := Rot n) (rotation r) = (zpowers (rotation r)).index := by
    rw [Subgroup.index_eq_card]
    exact Nat.card_congr (equivSubgroupOrbitsQuotientGroup (1 : Rot n) (zpowers (rotation r)))
  -- Step 2: |⟨r⟩| * index = n  (Lagrange).
  have hmul : Nat.card (zpowers (rotation r)) * (zpowers (rotation r)).index = Nat.card (Rot n) :=
    Subgroup.card_mul_index _
  rw [card_zpowers_rotation, card_rot] at hmul
  -- Step 3: (n / d) * index = n with d = gcd(n, r) ∣ n  ⟹  index = d.
  have hdvd : Nat.gcd n r.val ∣ n := Nat.gcd_dvd_left _ _
  have hn0 : 0 < n := Nat.pos_of_ne_zero (NeZero.ne n)
  have hdpos : 0 < Nat.gcd n r.val := Nat.gcd_pos_iff.mpr (Or.inl hn0)
  have hpos : 0 < n / Nat.gcd n r.val := Nat.div_pos (Nat.le_of_dvd hn0 hdvd) hdpos
  rw [hidx]
  have hcancel : (n / Nat.gcd n r.val) * (zpowers (rotation r)).index
      = (n / Nat.gcd n r.val) * Nat.gcd n r.val := by
    rw [hmul, Nat.div_mul_cancel hdvd]
  exact Nat.eq_of_mul_eq_mul_left hpos hcancel

/-! ## Section III: (B) Fixed colorings `= k ^ gcd(n, r)` -/

/-- **(B)** The number of `k`-colorings of the `n`-bead necklace fixed by rotation `r`
is `k ^ gcd(n, r)`. Immediate from `(A)` and the parent's `card_fixedBy_eq_pow_cyc`. -/
theorem card_fixedColorings_rotation (r : ZMod n) (k : ℕ) :
    Nat.card (fixedBy (Rot n → Fin k) (rotation r)) = k ^ Nat.gcd n r.val := by
  rw [card_fixedBy_eq_pow_cyc (X := Rot n) (k := k) (rotation r), cyc_rotation]

/-! ## Section IV: (C) Cyclic necklace counting (Burnside average) -/

/-- **(C)** Summing the fixed-coloring counts over all rotations recovers the classical
cyclic necklace formula in integer form:
`∑_{r : ZMod n} k ^ gcd(n, r) = (#necklaces up to rotation) * n`. Dividing by `n` gives
the usual `(1/n) ∑_r k^{gcd(n,r)}` necklace count. -/
theorem sum_pow_gcd_eq_card_necklaces_mul (k : ℕ) :
    (∑ r : ZMod n, k ^ Nat.gcd n r.val)
      = Nat.card (orbitRel.Quotient (Rot n) (Rot n → Fin k)) * n := by
  have hsum : (∑ g : Rot n, k ^ cyc (X := Rot n) g)
      = ∑ r : ZMod n, k ^ Nat.gcd n r.val := by
    refine Fintype.sum_equiv Multiplicative.toAdd _ _ (fun g => ?_)
    have hcyc : cyc (X := Rot n) g = Nat.gcd n (Multiplicative.toAdd g).val :=
      cyc_rotation (Multiplicative.toAdd g)
    simp only [hcyc]
  rw [← hsum]
  have h := sum_pow_cyc_eq_card_orbits_mul_card (G := Rot n) (X := Rot n) (k := k)
  rw [h, card_rot]

#check @cyc_rotation
#check @card_fixedColorings_rotation
#check @sum_pow_gcd_eq_card_necklaces_mul

end BurnsideCountingOQ03OQ02OQ01
