import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

/-
# From Cauchy to Sylow: the maximal `p`-power subgroup as a named corollary

## What This Proves

The parent file `CauchyGroupTheoremOQ01` packages Cauchy's theorem in its
*subgroup* form (`cauchy_subgroup`): a prime `p ∣ |G|` yields a subgroup of
order exactly `p`, the cyclic group generated by a Cauchy element. That is the
**first rung** of the Sylow ladder. This file climbs the whole ladder, packaging
**Sylow's first theorem** as the natural completion of Cauchy.

Mathlib proves the underlying existence statements
(`Sylow.exists_subgroup_card_pow_prime`, `Sylow.card_eq_multiplicity`) but, just
as with Cauchy, records **none** of the classical packaged corollaries that make
the Cauchy → Sylow bridge explicit. We supply them.

* **The full prime-power tower** (`exists_subgroup_card_pow_prime`). For every
  exponent `n` with `pⁿ ∣ |G|` there is a subgroup of order exactly `pⁿ`. This is
  Sylow I in its strongest form; Cauchy's subgroup theorem is precisely the
  `n = 1` slice.

* **Recovering the parent** (`cauchy_subgroup`). The `n = 1` case literally
  reproduces the parent's `cauchy_subgroup`: `p ∣ |G| ⟹ ∃ H, |H| = p`. Cauchy is
  the base of the tower.

* **The Sylow `p`-subgroup** (`exists_sylow_subgroup`). There is a subgroup whose
  order is `p ^ (multiplicity of p in |G|)` — the *maximal* power of `p` dividing
  `|G|`. This is the genuine "`p`-Sylow subgroup of order `pᵏ`" the title asks
  for, obtained from Mathlib's `Sylow` type via `card_eq_multiplicity`.

* **It really is maximal** (`sylow_index_not_dvd`, `sylow_card_dvd_card`). The
  Sylow subgroup's order divides `|G|`, and crucially its **index is coprime to
  `p`** — the defining property that distinguishes a *full* Sylow subgroup from a
  merely-large `p`-subgroup. No bigger power of `p` can divide `|G|`.

* **Nontriviality boundary** (`sylow_nontrivial_iff_dvd`). The Sylow
  `p`-subgroup is nontrivial **iff** `p ∣ |G|` — pinning down exactly when Cauchy
  (and hence the whole tower) fires.

* **Concrete instances on `S₃`** (`card_perm_fin3`, `sylow2_perm_fin3`,
  `sylow3_perm_fin3`, `factorization_six_two`, `factorization_six_three`). On the
  symmetric group `S₃` (order `6 = 2 · 3`) the Sylow `2`-subgroup has order `2`
  and the Sylow `3`-subgroup has order `3`; the relevant multiplicities of `p`
  in `6` are pinned down via `pow_dvd_iff_le_factorization` (`p ∣ 6` but
  `p² ∤ 6`), so the file stays genuinely `0`-axiom.

## Context

Cauchy (1845) and Sylow (1872) form a single arc: `p ∣ |G|` produces an element,
hence a subgroup, of order `p`; Sylow extends this to a subgroup of order equal
to the full `p`-part of `|G|`, and shows the index is prime to `p`. The inductive
proof of Sylow I builds the tower one rung at a time, each step a Cauchy-style
extension inside a normalizer — so Cauchy is not merely the base case but the
engine of the induction. This file makes the "Cauchy ⟹ Sylow" packaging that
working group theorists cite, none of which Mathlib states.
-/

open Subgroup

namespace CauchyGroupTheoremOQ01OQ02

variable {G : Type*} [Group G] [Finite G]

/-! ### The prime-power tower (Sylow's first theorem) -/

/-- **Sylow's first theorem (tower form).** For a prime `p` and any exponent `n`
with `pⁿ ∣ |G|`, the group `G` has a subgroup of order exactly `pⁿ`. This is the
strongest form of Sylow I; Mathlib proves it as
`Sylow.exists_subgroup_card_pow_prime`, restated here as the baseline that
contains Cauchy as its `n = 1` slice. -/
theorem exists_subgroup_card_pow_prime (p : ℕ) [Fact p.Prime] {n : ℕ}
    (hdvd : p ^ n ∣ Nat.card G) : ∃ H : Subgroup G, Nat.card H = p ^ n :=
  Sylow.exists_subgroup_card_pow_prime p hdvd

/-- **Recovering the parent's `cauchy_subgroup`.** The `n = 1` case of the tower:
if `p ∣ |G|` then `G` has a subgroup of order exactly `p`. This is precisely
`CauchyGroupTheoremOQ01.cauchy_subgroup`, here exhibited as the base rung of the
Sylow ladder rather than via an explicit Cauchy element. -/
theorem cauchy_subgroup (p : ℕ) [Fact p.Prime] (hdvd : p ∣ Nat.card G) :
    ∃ H : Subgroup G, Nat.card H = p := by
  obtain ⟨H, hH⟩ := exists_subgroup_card_pow_prime p (n := 1) (by rwa [pow_one])
  exact ⟨H, by rwa [pow_one] at hH⟩

/-! ### The Sylow `p`-subgroup: the maximal `p`-power -/

/-- **The Sylow `p`-subgroup.** `G` has a subgroup of order `p ^ k`, where
`k = multiplicity of p in |G|` is the largest exponent with `pᵏ ∣ |G|`. This is
the "`p`-Sylow subgroup of order `pᵏ`" — obtained from Mathlib's `Sylow` type and
`Sylow.card_eq_multiplicity`. -/
theorem exists_sylow_subgroup (p : ℕ) [Fact p.Prime] :
    ∃ H : Subgroup G, Nat.card H = p ^ (Nat.card G).factorization p := by
  obtain ⟨P⟩ := (Sylow.nonempty : Nonempty (Sylow p G))
  exact ⟨P, P.card_eq_multiplicity⟩

omit [Group G] [Finite G] in
/-- **The Sylow order divides `|G|`** (Lagrange). The maximal `p`-power
`p ^ (factorization)` divides the group order. -/
theorem sylow_card_dvd_card (p : ℕ) :
    p ^ (Nat.card G).factorization p ∣ Nat.card G :=
  Nat.ordProj_dvd _ _

/-- **The Sylow subgroup is genuinely maximal: its index is coprime to `p`.**
There is a subgroup `H` of order `p ^ k` (the full `p`-part of `|G|`) whose index
`[G : H]` is **not** divisible by `p`. This coprime-index property is exactly what
separates a *full* Sylow subgroup from an arbitrary large `p`-subgroup: no higher
power of `p` divides `|G|`. -/
theorem sylow_index_not_dvd (p : ℕ) [Fact p.Prime] :
    ∃ H : Subgroup G, Nat.card H = p ^ (Nat.card G).factorization p ∧ ¬ p ∣ H.index := by
  obtain ⟨H, hH⟩ := exists_sylow_subgroup (G := G) p
  refine ⟨H, hH, ?_⟩
  have hp : p.Prime := Fact.out
  have hcard : Nat.card G ≠ 0 := Nat.card_pos.ne'
  -- `|H| · [G : H] = |G|`, and `|H| = ordProj`, so `[G : H] = ordCompl`, prime to `p`.
  have hmul : Nat.card H * H.index = Nat.card G := H.card_mul_index
  rw [hH] at hmul
  have hcompl : ordCompl[p] (Nat.card G) = H.index := by
    have hself := Nat.ordProj_mul_ordCompl_eq_self (Nat.card G) p
    have heq : p ^ (Nat.card G).factorization p * ordCompl[p] (Nat.card G)
        = p ^ (Nat.card G).factorization p * H.index := by
      rw [hself, hmul]
    exact Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos _) heq
  rw [← hcompl]
  exact Nat.not_dvd_ordCompl hp hcard

/-- **Nontriviality boundary.** The Sylow `p`-subgroup is nontrivial (its order
exceeds `1`) **iff** `p ∣ |G|`. Equivalently the multiplicity of `p` is positive
iff `p` divides the order — pinning down exactly when Cauchy, and hence the whole
Sylow tower, fires. -/
theorem sylow_nontrivial_iff_dvd (p : ℕ) [Fact p.Prime] :
    1 < p ^ (Nat.card G).factorization p ↔ p ∣ Nat.card G := by
  have hp : p.Prime := Fact.out
  have hcard : Nat.card G ≠ 0 := Nat.card_pos.ne'
  constructor
  · intro h
    -- `pᵏ > 1` forces `k ≠ 0`, hence `p ∣ |G|`.
    have hk : (Nat.card G).factorization p ≠ 0 := by
      rintro h0
      rw [h0, pow_zero] at h
      exact lt_irrefl 1 h
    exact Nat.dvd_of_factorization_pos hk
  · intro hdvd
    have hk : 0 < (Nat.card G).factorization p :=
      hp.factorization_pos_of_dvd hcard hdvd
    calc 1 = p ^ 0 := (pow_zero p).symm
      _ < p ^ (Nat.card G).factorization p := by
          exact Nat.pow_lt_pow_right hp.one_lt hk

/-! ### Concrete instances on the symmetric group `S₃` -/

/-- The symmetric group on three letters has order `6`. -/
theorem card_perm_fin3 : Nat.card (Equiv.Perm (Fin 3)) = 6 := by
  rw [Nat.card_eq_fintype_card, Fintype.card_perm, Fintype.card_fin]; rfl

/-- The `2`-adic multiplicity of `6` is `1`: the Sylow `2`-subgroup of `S₃` has
order `2¹ = 2`. Pinned down by `2 ∣ 6` but `4 ∤ 6` via `pow_dvd_iff_le_factorization`. -/
theorem factorization_six_two : (6 : ℕ).factorization 2 = 1 := by
  have hlo : 1 ≤ (6 : ℕ).factorization 2 :=
    (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_two (by norm_num)).mp
      (by norm_num : (2 : ℕ) ^ 1 ∣ 6)
  have hhi : (6 : ℕ).factorization 2 ≤ 1 := by
    by_contra h
    have h2 : 2 ≤ (6 : ℕ).factorization 2 := by omega
    have hdvd : (2 : ℕ) ^ 2 ∣ 6 :=
      (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_two (by norm_num)).mpr h2
    norm_num at hdvd
  omega

/-- The `3`-adic multiplicity of `6` is `1`: the Sylow `3`-subgroup of `S₃` has
order `3¹ = 3`. Pinned down by `3 ∣ 6` but `9 ∤ 6` via `pow_dvd_iff_le_factorization`. -/
theorem factorization_six_three : (6 : ℕ).factorization 3 = 1 := by
  have hlo : 1 ≤ (6 : ℕ).factorization 3 :=
    (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_three (by norm_num)).mp
      (by norm_num : (3 : ℕ) ^ 1 ∣ 6)
  have hhi : (6 : ℕ).factorization 3 ≤ 1 := by
    by_contra h
    have h2 : 2 ≤ (6 : ℕ).factorization 3 := by omega
    have hdvd : (3 : ℕ) ^ 2 ∣ 6 :=
      (Nat.Prime.pow_dvd_iff_le_factorization Nat.prime_three (by norm_num)).mpr h2
    norm_num at hdvd
  omega

/-- **Sylow `2`-subgroup of `S₃`.** The symmetric group `S₃` (order `6`) has a
subgroup of order exactly `2` — its Sylow `2`-subgroup (generated by a
transposition). Derived from the tower at `p = 2, n = 1`. -/
theorem sylow2_perm_fin3 : ∃ H : Subgroup (Equiv.Perm (Fin 3)), Nat.card H = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  refine cauchy_subgroup 2 ?_
  rw [card_perm_fin3]; decide

/-- **Sylow `3`-subgroup of `S₃`.** The symmetric group `S₃` (order `6`) has a
subgroup of order exactly `3` — its Sylow `3`-subgroup (the alternating group
`A₃` of `3`-cycles). Derived from the tower at `p = 3, n = 1`. -/
theorem sylow3_perm_fin3 : ∃ H : Subgroup (Equiv.Perm (Fin 3)), Nat.card H = 3 := by
  haveI : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  refine cauchy_subgroup 3 ?_
  rw [card_perm_fin3]; decide

end CauchyGroupTheoremOQ01OQ02
