import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

/-
# Cauchy's theorem for finite groups and its classical corollaries

## What This Proves

**Cauchy's theorem** (1845) is the cornerstone existence result of finite group
theory: if a prime `p` divides the order of a finite group `G`, then `G`
contains an element of order exactly `p`. It is the base case of the Sylow
theorems and the reason every finite group of even order contains an involution.

Mathlib proves the existence statement itself
(`exists_prime_orderOf_dvd_card` and its `Nat.card` and additive variants in
`Mathlib/GroupTheory/Perm/Cycle/Type.lean`), but it records **none** of the
classical packaged corollaries. This file repackages the theorem and proves the
standard consequences that mathematicians actually cite.

* **Main theorem** (`cauchy`, `cauchy'`, `cauchy_add`). For a finite group `G`
  and a prime `p` with `p ∣ |G|`, there is an element of order `p`. Stated in
  the `Fintype.card`, `Nat.card`, and additive forms. These are the Mathlib
  headlines, restated as the baseline.

* **Subgroup of order `p`** (`cauchy_subgroup`). The genuinely structural form:
  `p ∣ |G|` yields a *subgroup* `H ≤ G` with `Nat.card H = p` — namely the cyclic
  group generated by a Cauchy element. This is the form used as the seed of the
  Sylow construction, and Mathlib states it nowhere.

* **Even order ⟹ involution** (`exists_involution_of_even_card`). Every finite
  group of even order contains an element `x ≠ 1` with `x * x = 1`. This is the
  `p = 2` case of Cauchy, the fact underlying the odd-order theorem framing and
  countless parity arguments. New content.

* **Contrapositive characterisation** (`not_dvd_card_of_no_orderOf_eq`). If `G`
  has no element of order `p`, then `p ∤ |G|`: the absence of an element of
  order `p` certifies that `p` is coprime to the group order. New content.

* **Concrete instances** (`zmod6_involution`, `addOrderOf_three_zmod6`,
  `addOrderOf_two_zmod6`, `cauchy_zmod6_two`, `cauchy_zmod6_three`). In the
  additive group `ZMod 6` the element `3` has order `2` (the involution
  `3 + 3 = 0`, `3 ≠ 0`) and `2` has order `3`, witnessing Cauchy at the two
  primes `2, 3` dividing `6`. Verified by kernel `decide` (no `native_decide`),
  so the file stays genuinely `0`-axiom.

## Context

Cauchy's theorem is the converse-in-the-prime-case of Lagrange's theorem and the
first step toward the Sylow theorems: `p ∣ |G| ⟹ G` has an element, hence a
subgroup, of order `p`. The involution corollary is the engine of the theory of
groups of even order (Brauer–Fowler, Feit–Thompson).
-/

open Subgroup

namespace CauchyGroupTheoremOQ01

variable {G : Type*}

/-- **Cauchy's theorem** (`Fintype.card` form). If a prime `p` divides the order
of a finite group `G`, then `G` contains an element of order exactly `p`. This is
Mathlib's `exists_prime_orderOf_dvd_card`, restated as the baseline. -/
theorem cauchy [Group G] [Fintype G] (p : ℕ) [Fact p.Prime]
    (hdvd : p ∣ Fintype.card G) : ∃ x : G, orderOf x = p :=
  exists_prime_orderOf_dvd_card p hdvd

/-- **Cauchy's theorem** (`Nat.card` form), for a possibly non-`Fintype` finite
group. Mathlib's `exists_prime_orderOf_dvd_card'`. -/
theorem cauchy' [Group G] [Finite G] (p : ℕ) [Fact p.Prime]
    (hdvd : p ∣ Nat.card G) : ∃ x : G, orderOf x = p :=
  exists_prime_orderOf_dvd_card' p hdvd

/-- **Cauchy's theorem** (additive form). If a prime `p` divides the order of a
finite additive group `G`, then `G` contains an element of additive order `p`.
Mathlib's `exists_prime_addOrderOf_dvd_card`. -/
theorem cauchy_add [AddGroup G] [Fintype G] (p : ℕ) [Fact p.Prime]
    (hdvd : p ∣ Fintype.card G) : ∃ x : G, addOrderOf x = p :=
  exists_prime_addOrderOf_dvd_card p hdvd

/-- **Cauchy's theorem, subgroup form.** If a prime `p` divides `|G|`, then `G`
has a subgroup of order exactly `p` — the cyclic subgroup generated by a Cauchy
element. This is the form used to seed the Sylow theorems; Mathlib provides only
the element form, so this packaging is new content. -/
theorem cauchy_subgroup [Group G] [Finite G] (p : ℕ) [Fact p.Prime]
    (hdvd : p ∣ Nat.card G) : ∃ H : Subgroup G, Nat.card H = p := by
  obtain ⟨x, hx⟩ := cauchy' p hdvd
  exact ⟨zpowers x, by rw [Nat.card_zpowers, hx]⟩

/-- **Even order ⟹ involution.** Every finite group of even order contains an
element `x ≠ 1` with `x * x = 1`. This is the `p = 2` case of Cauchy: the order-2
element is precisely a non-trivial involution. New content — Mathlib has the
existence of an order-`p` element but not this classical packaging. -/
theorem exists_involution_of_even_card [Group G] [Fintype G]
    (h : Even (Fintype.card G)) : ∃ x : G, x ≠ 1 ∧ x * x = 1 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨x, hx⟩ := cauchy (G := G) 2 h.two_dvd
  refine ⟨x, ?_, ?_⟩
  · intro hx1
    rw [hx1, orderOf_one] at hx
    exact absurd hx (by norm_num)
  · have hpow := pow_orderOf_eq_one x
    rwa [hx, pow_two] at hpow

/-- **Contrapositive characterisation.** If `G` has no element of order `p` (for
`p` prime), then `p` does not divide `|G|`. Equivalently, the absence of an
order-`p` element certifies `p` is coprime to the group order. New content. -/
theorem not_dvd_card_of_no_orderOf_eq [Group G] [Fintype G] (p : ℕ) [Fact p.Prime]
    (h : ¬ ∃ x : G, orderOf x = p) : ¬ p ∣ Fintype.card G :=
  fun hdvd => h (cauchy p hdvd)

/- ### Concrete instances in `ZMod 6`

The additive group `ZMod 6` has order `6 = 2 · 3`, so Cauchy guarantees elements
of order `2` and `3`. We exhibit them explicitly and verify by kernel `decide`,
keeping the file free of `Lean.ofReduceBool` (no `native_decide`). -/

/-- The explicit involution in `ZMod 6`: `3 ≠ 0` but `3 + 3 = 0`. -/
theorem zmod6_involution : (3 : ZMod 6) ≠ 0 ∧ (3 : ZMod 6) + 3 = 0 := by decide

/-- The element `3 : ZMod 6` realises additive order `2` — the involution above
seen through `addOrderOf`, a concrete Cauchy witness at `p = 2`. -/
theorem addOrderOf_three_zmod6 : addOrderOf (3 : ZMod 6) = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact addOrderOf_eq_prime (by decide) (by decide)

/-- The element `2 : ZMod 6` realises additive order `3` — a concrete Cauchy
witness at `p = 3`. -/
theorem addOrderOf_two_zmod6 : addOrderOf (2 : ZMod 6) = 3 := by
  haveI : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  exact addOrderOf_eq_prime (by decide) (by decide)

/-- Cauchy at `p = 2` fires in `ZMod 6`: an element of additive order `2` exists.
Derived from the general theorem, not the explicit witness. -/
theorem cauchy_zmod6_two : ∃ x : ZMod 6, addOrderOf x = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact cauchy_add 2 (by decide)

/-- Cauchy at `p = 3` fires in `ZMod 6`: an element of additive order `3` exists. -/
theorem cauchy_zmod6_three : ∃ x : ZMod 6, addOrderOf x = 3 := by
  haveI : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  exact cauchy_add 3 (by decide)

end CauchyGroupTheoremOQ01
