import Mathlib
import Proofs.CayleyHamiltonOQ01OQ01

/-
# Minimal Polynomial = lcm of Annihilator Polynomials over a Basis

## Source
Open question `cayley-hamilton-oq-01-oq-02`, extending `cayley-hamilton-oq-01`.

## What This Proves

Fix an n×n matrix `M` over a field `K`. View `Kⁿ` as a `K[X]`-module via `M`
(the `Module.AEval' M.mulVecLin` structure from `CayleyHamiltonOQ01OQ01`). For a
vector `v`, its *annihilator (order) ideal* is
`vecAnnIdeal M v = {p : K[X] | p(M)·v = 0}`, a principal ideal generated by the
*order polynomial* `μ_v` of `v`.

The minimal polynomial of `M` is the least common multiple of the order
polynomials of the vectors of any basis:

1. `minpoly_span_eq_iInf_vecAnnIdeal` — for any *spanning family* `v`,
   `Ideal.span {minpoly K M} = ⨅ i, vecAnnIdeal M (v i)`.
   (The minimal polynomial generates the intersection of all the vector
   annihilator ideals.)

2. `iInf_span_singleton_eq_lcm` — in `K[X]` (a PID / `NormalizedGCDMonoid`),
   `⨅ i, span {a i} = span {Finset.univ.lcm a}`. The intersection of finitely
   many principal ideals is generated by the lcm of the generators.

3. `minpoly_span_eq_lcm_of_generators` — combining 1 and 2: if `μ i` generates
   `vecAnnIdeal M (b i)` over a basis `b`, then
   `Ideal.span {minpoly K M} = Ideal.span {Finset.univ.lcm μ}`.

4. `minpoly_eq_lcm` / `exists_minpoly_eq_lcm` — the literal polynomial identity
   `minpoly K M = Finset.univ.lcm μ` for *monic* order polynomials `μ i`, and
   the existence of such monic generators. Both `minpoly K M` and the lcm are
   monic and associated, hence equal.

## Mathematical Significance
This is the structural reason the minimal polynomial of a matrix can be read off
a basis: it is exactly the lcm of the individual "orders" of the basis vectors.
It refines `cayley-hamilton-oq-01-oq-01` (which handles a single vector and the
cyclic case) to the whole module via a basis.

## Key Mathlib / project results used
- `CayleyHamiltonOQ01OQ01.vecAnnIdeal`, `.mem_vecAnnIdeal_iff`,
  `.minpoly_ideal_le_vecAnnIdeal`, `.minpoly_mem_vecAnnIdeal`.
- `LinearMap.ext_on_range` — a linear map vanishing on a spanning family is `0`.
- `minpoly.dvd` — `aeval x p = 0 → minpoly K x ∣ p`.
- `Finset.lcm_dvd_iff`, `Finset.normalize_lcm`.
- `Ideal.span_singleton_eq_span_singleton` (Associated), `monic_normalize`,
  `Polynomial.eq_of_monic_of_associated`.
-/

namespace CayleyHamiltonOQ01OQ02

open Matrix Polynomial Module BigOperators
open CayleyHamiltonOQ01OQ01 (vecAnnIdeal mem_vecAnnIdeal_iff minpoly_ideal_le_vecAnnIdeal
  minpoly_mem_vecAnnIdeal)

variable {K : Type*} [Field K] {n : ℕ}

/-! ## Helpers -/

/-- `minpoly K M = minpoly K M.mulVecLin` (re-proved locally; the `OQ01OQ01`
    version is `private`). -/
private theorem minpoly_mulVecLin_eq (M : Matrix (Fin n) (Fin n) K) :
    minpoly K M = minpoly K M.mulVecLin := by
  rw [show M.mulVecLin = Matrix.toLin' M from (Matrix.toLin'_apply' M).symm]
  exact (Matrix.minpoly_toLin' (M := M)).symm

/-- Every matrix over a field is integral (Cayley–Hamilton). -/
theorem isIntegral_matrix (M : Matrix (Fin n) (Fin n) K) : IsIntegral K M :=
  ⟨M.charpoly, Matrix.charpoly_monic M, Matrix.aeval_self_charpoly M⟩

/-! ## I. minpoly ideal = intersection of vector annihilators over a spanning family -/

/-- For any family `v : ι → Kⁿ` whose range spans `Kⁿ`, the ideal generated by the
    minimal polynomial of `M` equals the intersection of the annihilator ideals of
    the `v i`. Equivalently: the minimal polynomial is the lcm of the order
    polynomials of a spanning set. -/
theorem minpoly_span_eq_iInf_vecAnnIdeal {ι : Type*} (M : Matrix (Fin n) (Fin n) K)
    (v : ι → (Fin n → K)) (hv : Submodule.span K (Set.range v) = ⊤) :
    Ideal.span {minpoly K M} = ⨅ i, vecAnnIdeal M (v i) := by
  apply le_antisymm
  · -- minpoly is in every vector annihilator
    exact le_iInf fun i => minpoly_ideal_le_vecAnnIdeal M (v i)
  · -- conversely, anything killing every spanning vector is a multiple of minpoly
    intro f hf
    rw [Submodule.mem_iInf] at hf
    rw [Ideal.mem_span_singleton]
    -- f kills each spanning vector as a linear endomorphism
    have hker : ∀ i, (aeval M.mulVecLin f) (v i) = 0 := by
      intro i
      have hmem := (mem_vecAnnIdeal_iff).mp (hf i)
      have h := congr_arg (Module.AEval'.of M.mulVecLin).symm hmem
      simp only [LinearEquiv.map_zero, Module.AEval.of_symm_smul,
                 LinearEquiv.symm_apply_apply] at h
      exact h
    -- hence f(M) = 0 as an endomorphism (vanishes on a spanning family)
    have hzero : aeval M.mulVecLin f = 0 := by
      apply LinearMap.ext_on_range hv
      intro i
      simpa using hker i
    -- therefore minpoly K M ∣ f
    have hdvd : minpoly K M.mulVecLin ∣ f := minpoly.dvd K M.mulVecLin hzero
    rwa [← minpoly_mulVecLin_eq] at hdvd

/-! ## II. Intersection of principal ideals = lcm (in a PID / NormalizedGCDMonoid) -/

/-- In `K[X]`, the intersection of finitely many principal ideals is generated by
    the lcm of the generators. -/
theorem iInf_span_singleton_eq_lcm {ι : Type*} [Fintype ι] [DecidableEq K]
    (a : ι → K[X]) :
    ⨅ i, Ideal.span {a i} = Ideal.span {Finset.univ.lcm a} := by
  ext x
  simp only [Submodule.mem_iInf, Ideal.mem_span_singleton, Finset.lcm_dvd_iff,
             Finset.mem_univ, true_implies]

/-! ## III. minpoly = lcm of order polynomials of a basis -/

/-- **Ideal form.** If `μ i` generates the annihilator ideal of the basis vector
    `b i`, then `Ideal.span {minpoly K M} = Ideal.span {Finset.univ.lcm μ}`. -/
theorem minpoly_span_eq_lcm_of_generators {ι : Type*} [Fintype ι] [DecidableEq K]
    (M : Matrix (Fin n) (Fin n) K) (b : Basis ι K (Fin n → K))
    (μ : ι → K[X]) (hμ : ∀ i, vecAnnIdeal M (b i) = Ideal.span {μ i}) :
    Ideal.span {minpoly K M} = Ideal.span {Finset.univ.lcm μ} := by
  rw [minpoly_span_eq_iInf_vecAnnIdeal M (⇑b) b.span_eq]
  simp_rw [hμ]
  exact iInf_span_singleton_eq_lcm μ

/-- There exist *monic* order polynomials `μ i` of the basis vectors generating the
    annihilator ideals (the order polynomial of each `b i`). -/
theorem exists_monic_generators {ι : Type*} [Fintype ι] [DecidableEq K]
    (M : Matrix (Fin n) (Fin n) K) (b : Basis ι K (Fin n → K)) :
    ∃ μ : ι → K[X], (∀ i, vecAnnIdeal M (b i) = Ideal.span {μ i}) ∧
      (∀ i, (μ i).Monic) := by
  have hmono : (minpoly K M).Monic := minpoly.monic (isIntegral_matrix M)
  -- each annihilator ideal is principal (PID); pick a generator
  choose g hg using fun i =>
    (IsPrincipalIdealRing.principal (vecAnnIdeal M (b i))).principal
  refine ⟨fun i => normalize (g i), fun i => ?_, fun i => ?_⟩
  · -- vecAnnIdeal M (b i) = span {normalize (g i)} : normalize is associated to g i
    rw [hg i]
    exact (Ideal.span_singleton_eq_span_singleton.mpr (normalize_associated (g i))).symm
  · -- normalize of a nonzero polynomial is monic
    apply monic_normalize
    intro h0
    have hmem : minpoly K M ∈ vecAnnIdeal M (b i) := minpoly_mem_vecAnnIdeal M (b i)
    rw [hg i, h0, Submodule.span_zero_singleton, Submodule.mem_bot] at hmem
    exact hmono.ne_zero hmem

/-- **Polynomial form.** For *any* generators `μ i` of the annihilator ideals of
    the basis vectors, the minimal polynomial is literally their lcm:
    `minpoly K M = Finset.univ.lcm μ`. (No monicity hypothesis is needed: a
    `Finset.lcm` is already normalized, hence monic, and `minpoly` is monic.) -/
theorem minpoly_eq_lcm {ι : Type*} [Fintype ι] [DecidableEq K]
    (M : Matrix (Fin n) (Fin n) K) (b : Basis ι K (Fin n → K))
    (μ : ι → K[X]) (hμ_gen : ∀ i, vecAnnIdeal M (b i) = Ideal.span {μ i}) :
    minpoly K M = Finset.univ.lcm μ := by
  have hmono : (minpoly K M).Monic := minpoly.monic (isIntegral_matrix M)
  have hspan : Ideal.span {minpoly K M} = Ideal.span {Finset.univ.lcm μ} :=
    minpoly_span_eq_lcm_of_generators M b μ hμ_gen
  have hassoc : Associated (minpoly K M) (Finset.univ.lcm μ) :=
    Ideal.span_singleton_eq_span_singleton.mp hspan
  -- the lcm is nonzero (else minpoly would be associated to 0, hence 0)
  have hlcm_ne : Finset.univ.lcm μ ≠ 0 := by
    intro h0
    rw [h0, associated_zero_iff_eq_zero] at hassoc
    exact hmono.ne_zero hassoc
  -- a `Finset.lcm` is normalized; a nonzero normalized polynomial is monic
  have hlcm_monic : (Finset.univ.lcm μ).Monic := by
    have h := monic_normalize (R := K) hlcm_ne
    rwa [Finset.normalize_lcm] at h
  exact eq_of_monic_of_associated hmono hlcm_monic hassoc

/-- **Headline.** The minimal polynomial of `M` is the lcm of the (monic) order
    polynomials of the vectors of any basis of `Kⁿ`. -/
theorem exists_minpoly_eq_lcm {ι : Type*} [Fintype ι] [DecidableEq K]
    (M : Matrix (Fin n) (Fin n) K) (b : Basis ι K (Fin n → K)) :
    ∃ μ : ι → K[X], (∀ i, (μ i).Monic) ∧
      (∀ i, vecAnnIdeal M (b i) = Ideal.span {μ i}) ∧
      minpoly K M = Finset.univ.lcm μ := by
  obtain ⟨μ, hgen, hmonic⟩ := exists_monic_generators M b
  exact ⟨μ, hmonic, hgen, minpoly_eq_lcm M b μ hgen⟩

end CayleyHamiltonOQ01OQ02
