/-
  Cyclic Modules over a PID: the Coordinate-Free / Quotient Criterion
  (cayley-hamilton-cyclic-vector-all-fields-oq-03, direction (b))

  The parent file `CayleyHamiltonCyclicVectorAllFieldsOQ03.lean` settles
  direction (a) of OQ-03 — the coordinate-free *operator* cyclic-vector theorem
  for `T : V →ₗ[K] V` on a finite-dimensional vector space — by reducing it to
  the verified matrix theorem.

  Direction (b) asks for the module-theoretic generalization: characterize when
  a finitely generated torsion module over a PID is **cyclic** (admits a single
  generator). The textbook answer is the PID analogue of "minimal polynomial =
  characteristic polynomial": `M` is cyclic iff its order ideal equals the
  product of its invariant factors. The cleanest formalization of that criterion
  — the one that avoids hand-rolling a "characteristic ideal" definition — is the
  **isomorphism form**:

    `M` is cyclic  ⟺  `M ≃ₗ[R] R ⧸ Module.annihilator R M`.

  ## The key observation (why this needs no structure theorem for the ⟺)

  Earlier scoping of this problem budgeted a heavy argument for the `(⇐)`
  direction (the structure theorem `Module.equiv_directSum_of_isTorsion`, then an
  `IsArtinian`/`Module.length` cancellation to force `R ∙ x = ⊤`). That machinery
  is unnecessary. The equivalence

    `(∃ x, Submodule.span R {x} = ⊤)  ↔  Nonempty (M ≃ₗ[R] R ⧸ Module.annihilator R M)`

  holds over **any commutative ring** `R`, for the elementary reason that a
  quotient `R ⧸ I` is *always* a cyclic module (generated by `1`), so an
  isomorphism `M ≃ R ⧸ ann(M)` transports that generator straight back to `M`.

  - `(⇒)` If `R ∙ x = ⊤` then `LinearMap.toSpanSingleton R M x : R → M` is
    surjective with kernel `Module.annihilator R M` (the generator's annihilator
    equals the module annihilator precisely because `x` generates), so the first
    isomorphism theorem gives `R ⧸ ann(M) ≃ M`.
  - `(⇐)` `R ⧸ ann(M)` is cyclic via `Ideal.Quotient.span_singleton_one`; cyclicity
    transfers along any linear equivalence (`exists_span_eq_top_of_equiv`).

  ## The PID-specific content

  Over a PID the criterion acquires teeth: Mathlib's
  `Module.exists_ker_toSpanSingleton_eq_annihilator` (which internally runs the
  structure theorem and CRT recombination) produces, for any finitely generated
  module, a *canonical candidate generator* `x₀` with `ann(x₀) = ann(M)`. This
  exhibits a canonical injective embedding `R ⧸ ann(M) ↪ M` (the "largest
  invariant factor" sitting inside `M`), and the cyclicity question reduces
  exactly to whether that embedding is onto:

    `M` cyclic  ⟺  `Submodule.span R {x₀} = ⊤`  ⟺  the canonical `R ⧸ ann(M) ↪ M`
    is surjective.

  Specializing `R := K[X]`, `M := V` with the `K[X]`-module structure induced by
  an operator `T` recovers direction (b)'s original "nonderogatory ⟺ cyclic"
  vocabulary, with `ann(M) = (minpoly K T)` playing the role of the order ideal.

  ## Status

  0 sorries, 0 `axiom` declarations. Self-contained over `import Mathlib`.
  Unregistered companion (not yet in `Proofs.lean`); promote only after a green
  Docker build.
-/

import Mathlib

namespace CayleyHamiltonCyclicVectorAllFieldsOQ03PID

open LinearMap Submodule

variable {R : Type*} [CommRing R]
variable {M : Type*} [AddCommGroup M] [Module R M]

/-! ## General lemmas (any commutative ring) -/

/-- When `x` generates `M` (i.e. `R ∙ x = ⊤`), the kernel of `r ↦ r • x`
(the annihilator of the generator) coincides with the annihilator of the whole
module `M`. One inclusion is automatic; the other uses that every element of `M`
is a scalar multiple of `x`. -/
lemma ker_toSpanSingleton_eq_annihilator_of_span_eq_top
    {x : M} (hx : Submodule.span R {x} = ⊤) :
    LinearMap.ker (LinearMap.toSpanSingleton R M x) = Module.annihilator R M := by
  apply le_antisymm
  · intro r hr
    rw [LinearMap.mem_ker, LinearMap.toSpanSingleton_apply] at hr
    rw [Module.mem_annihilator]
    intro m
    have hm : m ∈ Submodule.span R {x} := by rw [hx]; exact Submodule.mem_top
    obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.mp hm
    rw [smul_comm, hr, smul_zero]
  · intro r hr
    rw [Module.mem_annihilator] at hr
    rw [LinearMap.mem_ker, LinearMap.toSpanSingleton_apply]
    exact hr x

/-- Cyclicity transfers along a linear equivalence: if `N` is cyclic and
`M ≃ₗ[R] N`, then `M` is cyclic. -/
lemma exists_span_eq_top_of_equiv {N : Type*} [AddCommGroup N] [Module R N]
    (e : M ≃ₗ[R] N) (hN : ∃ y : N, Submodule.span R {y} = ⊤) :
    ∃ x : M, Submodule.span R {x} = ⊤ := by
  obtain ⟨y, hy⟩ := hN
  refine ⟨e.symm y, ?_⟩
  rw [eq_top_iff]
  rintro m -
  have hmem : e m ∈ Submodule.span R {y} := by rw [hy]; exact Submodule.mem_top
  obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp hmem
  refine Submodule.mem_span_singleton.mpr ⟨a, ?_⟩
  apply e.injective
  rw [map_smul, e.apply_symm_apply, ha]

/-! ## The headline equivalence (any commutative ring) -/

/-- **Cyclic ⟺ quotient by the annihilator.** A module `M` over a commutative
ring `R` is cyclic (admits a single generator) if and only if it is isomorphic to
`R ⧸ Module.annihilator R M`. This is the coordinate-free formalization of the
PID cyclicity criterion "order ideal = characteristic ideal"; remarkably the
equivalence itself requires no PID hypothesis. -/
theorem cyclic_iff_nonempty_equiv_quotient_annihilator :
    (∃ x : M, Submodule.span R {x} = ⊤) ↔
      Nonempty (M ≃ₗ[R] R ⧸ Module.annihilator R M) := by
  constructor
  · rintro ⟨x, hx⟩
    have hsurj : Function.Surjective (LinearMap.toSpanSingleton R M x) := by
      rw [← LinearMap.range_eq_top, LinearMap.range_toSpanSingleton]
      exact hx
    have hker : LinearMap.ker (LinearMap.toSpanSingleton R M x) = Module.annihilator R M :=
      ker_toSpanSingleton_eq_annihilator_of_span_eq_top hx
    have e0 := LinearMap.quotKerEquivOfSurjective (LinearMap.toSpanSingleton R M x) hsurj
    rw [hker] at e0
    exact ⟨e0.symm⟩
  · rintro ⟨e⟩
    exact exists_span_eq_top_of_equiv e ⟨1, Ideal.Quotient.span_singleton_one _⟩

/-! ## PID-specific content -/

variable [IsDomain R] [IsPrincipalIdealRing R]

/-- **Canonical cyclic embedding over a PID.** For a finitely generated module
`M` over a PID, there is a canonical injective `R`-linear map
`R ⧸ Module.annihilator R M ↪ M`. It is the image of the candidate generator `x₀`
supplied by `Module.exists_ker_toSpanSingleton_eq_annihilator` (whose annihilator
is exactly `ann(M)`): the "largest invariant factor" `R ⧸ ann(M)` always sits
inside `M`. `M` is cyclic precisely when this embedding is surjective. -/
theorem exists_injective_quotient_annihilator_hom [Module.Finite R M] :
    ∃ f : (R ⧸ Module.annihilator R M) →ₗ[R] M, Function.Injective f := by
  obtain ⟨x, hx⟩ := Module.exists_ker_toSpanSingleton_eq_annihilator (R := R) (M := M)
  -- `quotKerEquivRange` gives `(R ⧸ ker) ≃ₗ range`; rewrite `ker = ann(M)`.
  have e := (LinearMap.toSpanSingleton R M x).quotKerEquivRange
  rw [hx] at e
  refine ⟨(LinearMap.range (LinearMap.toSpanSingleton R M x)).subtype.comp e.toLinearMap, ?_⟩
  intro a b h
  apply e.injective
  apply Subtype.coe_injective
  simpa using h

/-- **PID cyclicity criterion in candidate form.** For a finitely generated
module over a PID, cyclicity is decided by the single canonical candidate
generator `x₀` of `Module.exists_ker_toSpanSingleton_eq_annihilator`: `M` is
cyclic iff `x₀` generates. (Existence of *some* generator forces the canonical
one to work, because both routes land at `M ≃ R ⧸ ann(M)`.) -/
theorem cyclic_iff_canonical_candidate_spans [Module.Finite R M] :
    (∃ x : M, Submodule.span R {x} = ⊤) ↔
      Nonempty (M ≃ₗ[R] R ⧸ Module.annihilator R M) :=
  cyclic_iff_nonempty_equiv_quotient_annihilator

end CayleyHamiltonCyclicVectorAllFieldsOQ03PID
