import Mathlib

/-
# OQ-07-OQ-02: The inverse-is-a-polynomial identity over a commutative ring

Child of `cayley-hamilton-minpoly-oq-07` (matrix inverse is a polynomial in the
matrix, proved there over a *field*).  This entry removes the field hypothesis:
the same explicit polynomial expresses `A⁻¹` over an arbitrary **commutative
ring** `R`, provided the determinant is an actual **unit** of `R` (not merely
nonzero).

## Why the upgrade is genuine

Over a field, `det A ≠ 0` is equivalent to invertibility, and one divides by the
scalar `−c₀`.  Over a general commutative ring these two notions diverge:
`det A ≠ 0` no longer suffices, one must assume `IsUnit (det A)`, and the field
inverse `(−c₀)⁻¹` must be replaced by `Ring.inverse (−c₀)`.  The witnessing case
is `R = ℤ`: a matrix with `det A = ±1` (the group `GL(n, ℤ)`) has an
**integer-coefficient** polynomial inverse, something the field-only parent
cannot express since `ℤ` is not a field.

## Mathematical content

Let `A : Matrix n n R` with `IsUnit (det A)`, and `p = charpoly A`, `c₀ = p.coeff 0`.
Cayley–Hamilton (`Matrix.aeval_self_charpoly`) gives `p(A) = 0`.  Splitting off the
constant term via `p = (divX p) · X + C c₀` and evaluating at `A`,

    (divX p)(A) · A + c₀ • 1 = 0,   i.e.   (divX p)(A) · A = (−c₀) • 1.

By `Matrix.det_eq_sign_charpoly_coeff`, `det A = (−1)ⁿ c₀`, so `IsUnit (det A)`
forces `IsUnit (−c₀)`.  Multiplying by the ring inverse of the unit `−c₀`,

    A⁻¹ = Ring.inverse (−c₀) • (divX p)(A) = (aeval A) r,
    r = C (Ring.inverse (−c₀)) · divX p,   deg r < n.

Hence `A⁻¹ ∈ R[A]`, the subalgebra generated by `A`, given by a polynomial of
degree `< n` — over any commutative ring, exactly as over a field.

Self-contained: imports only `Mathlib`.  Sorry-free and axiom-free.
-/

namespace CayleyHamiltonMinpolyOQ07OQ02

open Polynomial Matrix

variable {n : Type*} [DecidableEq n] [Fintype n]
variable {R : Type*} [CommRing R]

/-- The **inverse polynomial** of `A` over a commutative ring:
`r = C (Ring.inverse (−c₀)) · divX (charpoly A)`, where `c₀ = (charpoly A).coeff 0`.
Evaluating at `A` produces `A⁻¹` when `det A` is a unit (see `inv_eq_aeval_invPoly`). -/
noncomputable def invPoly (A : Matrix n n R) : R[X] :=
  C (Ring.inverse (-(A.charpoly.coeff 0))) * A.charpoly.divX

/-- **Unit lens on the constant term.** If `det A` is a unit of `R`, then so is
`−c₀`, the negated constant term of the characteristic polynomial. This is what
lets us invert `−c₀` via `Ring.inverse`; over a field it degenerates to `c₀ ≠ 0`. -/
theorem isUnit_neg_charpoly_coeff_zero (A : Matrix n n R) (hA : IsUnit A.det) :
    IsUnit (-(A.charpoly.coeff 0)) := by
  have hpow : IsUnit ((-1 : R) ^ Fintype.card n) := isUnit_neg_one.pow _
  -- (−1)ⁿ is its own inverse, so c₀ = (−1)ⁿ · det A is a product of units.
  have hs2 : ((-1 : R) ^ Fintype.card n) * ((-1 : R) ^ Fintype.card n) = 1 := by
    rw [← mul_pow]; norm_num
  have hc0eq : A.charpoly.coeff 0 = ((-1 : R) ^ Fintype.card n) * A.det := by
    rw [Matrix.det_eq_sign_charpoly_coeff, ← mul_assoc, hs2, one_mul]
  have hc0 : IsUnit (A.charpoly.coeff 0) := by rw [hc0eq]; exact hpow.mul hA
  exact hc0.neg

/-- **Cayley–Hamilton in additive form.** Evaluating the decomposition
`charpoly A = divX (charpoly A) · X + C c₀` at `A` gives
`(divX p)(A) · A + c₀ • 1 = 0`. Holds over any commutative ring. -/
theorem aeval_divX_mul_self (A : Matrix n n R) :
    (aeval A) A.charpoly.divX * A
      + algebraMap R (Matrix n n R) (A.charpoly.coeff 0) = 0 := by
  have hCH : (aeval A) A.charpoly = 0 := Matrix.aeval_self_charpoly A
  have hdec : A.charpoly.divX * X + C (A.charpoly.coeff 0) = A.charpoly :=
    divX_mul_X_add A.charpoly
  have h2 : (aeval A) (A.charpoly.divX * X + C (A.charpoly.coeff 0)) = 0 := by
    rw [hdec]; exact hCH
  rwa [map_add, map_mul, aeval_X, aeval_C] at h2

/-- **The inverse polynomial is a left inverse.** `(aeval A) (invPoly A) · A = 1`
whenever `det A` is a unit. The field-case division `(−c₀)⁻¹ · (−c₀) = 1` is
replaced by `Ring.inverse_mul_cancel` on the unit `−c₀`. -/
theorem aeval_invPoly_mul_self (A : Matrix n n R) (hA : IsUnit A.det) :
    (aeval A) (invPoly A) * A = 1 := by
  have hunit : IsUnit (-(A.charpoly.coeff 0)) := isUnit_neg_charpoly_coeff_zero A hA
  -- (divX p)(A) · A = (−c₀) • 1
  have hBA : (aeval A) A.charpoly.divX * A
      = (-(A.charpoly.coeff 0)) • (1 : Matrix n n R) := by
    have h := eq_neg_of_add_eq_zero_left (aeval_divX_mul_self A)
    rw [h, Algebra.algebraMap_eq_smul_one, neg_smul]
  -- (aeval A) (invPoly A) = Ring.inverse (−c₀) • (divX p)(A)
  have hexp : (aeval A) (invPoly A)
      = Ring.inverse (-(A.charpoly.coeff 0)) • (aeval A) A.charpoly.divX := by
    rw [invPoly, map_mul, aeval_C, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
  rw [hexp, smul_mul_assoc, hBA, smul_smul, Ring.inverse_mul_cancel _ hunit, one_smul]

/-- **Main result.** For a matrix `A` over a commutative ring with `IsUnit (det A)`,
the inverse is the evaluation at `A` of an explicit polynomial:
`A⁻¹ = (aeval A) (invPoly A)`. -/
theorem inv_eq_aeval_invPoly (A : Matrix n n R) (hA : IsUnit A.det) :
    A⁻¹ = (aeval A) (invPoly A) :=
  Matrix.inv_eq_left_inv (aeval_invPoly_mul_self A hA)

/-- **Degree bound.** The inverse polynomial has degree `< n` (`= Fintype.card n`).
No invertibility hypothesis is needed for the bound itself, only `Nontrivial R`
so that the characteristic polynomial has the expected degree. -/
theorem invPoly_natDegree_lt [Nontrivial R] [Nonempty n] (A : Matrix n n R) :
    (invPoly A).natDegree < Fintype.card n := by
  have hp_ne : A.charpoly ≠ 0 := A.charpoly_monic.ne_zero
  have hdim : A.charpoly.natDegree = Fintype.card n := Matrix.charpoly_natDegree_eq_dim A
  have h1 : (invPoly A).natDegree ≤ A.charpoly.divX.natDegree := by
    rw [invPoly]; exact natDegree_C_mul_le _ _
  have h2 : A.charpoly.divX.natDegree < A.charpoly.natDegree := by
    by_cases hdv : A.charpoly.divX = 0
    · rw [hdv, natDegree_zero, hdim]; exact Fintype.card_pos
    · exact natDegree_lt_natDegree hdv (degree_divX_lt hp_ne)
  omega

/-- **The inverse lies in the subalgebra generated by `A`.** `A⁻¹ ∈ R[A]`. -/
theorem inv_mem_adjoin (A : Matrix n n R) (hA : IsUnit A.det) :
    A⁻¹ ∈ Algebra.adjoin R {A} := by
  rw [inv_eq_aeval_invPoly A hA, Algebra.adjoin_singleton_eq_range_aeval]
  exact ⟨invPoly A, rfl⟩

/-- **Right-inverse companion.** `A · (aeval A) (invPoly A) = 1`. -/
theorem self_mul_aeval_invPoly (A : Matrix n n R) (hA : IsUnit A.det) :
    A * (aeval A) (invPoly A) = 1 := by
  have h := aeval_invPoly_mul_self A hA
  exact Matrix.mul_eq_one_comm.mp h

/-- **Packaged existence statement.** Every matrix over a commutative ring with a
unit determinant has an inverse expressible as a polynomial of degree `< n` in the
matrix. -/
theorem exists_inv_eq_aeval [Nontrivial R] [Nonempty n] (A : Matrix n n R)
    (hA : IsUnit A.det) :
    ∃ r : R[X], r.natDegree < Fintype.card n ∧ A⁻¹ = (aeval A) r :=
  ⟨invPoly A, invPoly_natDegree_lt A, inv_eq_aeval_invPoly A hA⟩

/-- **Reconciliation with the adjugate formula.** The polynomial inverse computed
here is the same matrix as Mathlib's `Ring.inverse (det A) • adjugate A` — the two
constructions describe one and the same `A⁻¹` (no hypothesis needed). -/
theorem inv_eq_smul_adjugate (A : Matrix n n R) :
    A⁻¹ = Ring.inverse A.det • A.adjugate :=
  Matrix.inv_def A

/-- **Concrete non-field instance: `GL(n, ℤ)`.** Over `ℤ` (not a field), any
integer matrix whose determinant is a unit (`±1`) has its inverse inside the
integer-coefficient subalgebra `ℤ[A]`. This is out of reach of the field-only
parent entry. -/
example {m : Type*} [DecidableEq m] [Fintype m] (A : Matrix m m ℤ)
    (hA : IsUnit A.det) : A⁻¹ ∈ Algebra.adjoin ℤ {A} :=
  inv_mem_adjoin A hA

end CayleyHamiltonMinpolyOQ07OQ02
