/-
  Closing the Triple Equivalence: Centralizer = K[M] ⟹ Cyclic Vector
  (cayley-hamilton-cyclic-vector-all-fields-oq-02-oq-01)

  The classical theory of a single endomorphism / square matrix `M` over a field
  `K` rests on a triple equivalence (Hoffman & Kunze §7.5, Roman §10.4):

      (i)   `M` admits a cyclic vector
      (ii)  `M` is nonderogatory  (minpoly `M` = charpoly `M`)
      (iii) the centralizer `C(M) = {N : NM = MN}` equals `K[M]`
            (every matrix commuting with `M` is a polynomial in `M`).

  The sibling file `CayleyHamiltonCyclicVectorAllFieldsOQ02.lean` proves the
  forward edge **(i) ⟹ (iii)** (`commuting_matrix_is_polynomial`); the parent
  biconditional `nonderogatory_iff_has_cyclic_vector` gives **(i) ⟺ (ii)**.

  This file supplies the remaining **converse edge (iii) ⟹ (ii)** (hence
  ⟹ (i)), closing the triangle.

  ## Proof

  Both `K[M] = Algebra.adjoin K {M}` and the centralizer
  `C(M) = Subalgebra.centralizer K {M}` are `K`-subalgebras of the matrix
  algebra, hence finite-dimensional `K`-vector spaces.  Three facts combine:

    * **dim K[M] = deg(minpoly M).**  `M` is integral over `K`, so the power
      basis `{1, M, …, M^{d-1}}` (with `d = deg minpoly`) is a `K`-basis of
      `K[M]` (`Algebra.adjoin.powerBasis'`).  Thus
      `finrank K K[M] = (minpoly K M).natDegree`.

    * **dim C(M) ≥ n.**  The Frobenius bound on the dimension of the
      commutant.  (Isolated below as `finrank_centralizer_ge`.)

    * **deg(minpoly M) ≤ n.**  `minpoly K M ∣ charpoly M` (Cayley–Hamilton),
      and `charpoly` has degree `n`.

  If `C(M) = K[M]` then `finrank K C(M) = finrank K K[M] = deg(minpoly)`, so

      n ≤ finrank K C(M) = deg(minpoly M) ≤ n,

  forcing `deg(minpoly M) = n`.  Two monic polynomials of equal degree, one
  dividing the other, are equal, so `minpoly K M = charpoly M`, i.e. `M` is
  nonderogatory (ii).  The parent biconditional then yields a cyclic vector (i).

  ## Status

  **Fully machine-checked, 0 axioms, 0 sorries.**  The Frobenius dimension bound
  `dim C(M) ≥ n` — previously isolated as a single `axiom` because Mathlib has no
  rational-canonical-form / invariant-factor packaging — is now **proved** below
  (`finrank_centralizer_ge`) directly from Mathlib's PID primary-decomposition
  structure theorem `Module.equiv_directSum_of_isTorsion`.  The argument routes
  the matrix centralizer through the algebra equivalence
  `Matrix.toLinAlgEquiv'` to the operator centralizer, identifies that with the
  `K[X]`-endomorphisms of the module `AEval' φ`, and lower-bounds their dimension
  by `n` via the multiplication embedding (`Algebra.lmul`) of the decomposed
  module.  Combined with the dimension bookkeeping (`dim K[M] = deg minpoly`),
  the degree squeeze, and the descent to a cyclic vector, the whole converse edge
  is verified.  The three supporting lemmas (`lmul_finrank_bound`,
  `aeval_end_bound`, `endK_centralizer_bound`) are field- and module-general and
  reusable.  `#print axioms finrank_centralizer_ge` reports only
  `propext, Classical.choice, Quot.sound`.
-/
import Mathlib
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ01OQ01
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ02

noncomputable section

namespace CyclicCommutantConverse

open Matrix Polynomial

variable {K : Type*} [Field K] {n : ℕ}

-- ============================================================
-- SECTION I: dim K[M] = deg(minpoly M)
-- ============================================================

/-- The algebra `K[M] = Algebra.adjoin K {M}` of polynomials in `M` has
    `K`-dimension equal to the degree of the minimal polynomial of `M`.

    Since the matrix algebra is noncommutative, the `PowerBasis` API for
    `adjoin` does not apply directly; instead we use the first isomorphism
    theorem.  `K[M]` is the range of `aeval M : K[X] →ₐ[K] Matrix`, and the
    kernel of `aeval M` is the ideal generated by `minpoly K M`, so

      K[M] ≃ₐ[K] K[X] ⧸ (minpoly K M),

    whose `K`-dimension is `(minpoly K M).natDegree`. -/
theorem finrank_adjoin_eq_natDegree_minpoly
    (M : Matrix (Fin n) (Fin n) K) :
    Module.finrank K ↥(Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K)))
      = (minpoly K M).natDegree := by
  have hrange : Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K))
      = (Polynomial.aeval M : K[X] →ₐ[K] Matrix (Fin n) (Fin n) K).range :=
    Algebra.adjoin_singleton_eq_range_aeval K M
  have hker : RingHom.ker (Polynomial.aeval M : K[X] →ₐ[K] Matrix (Fin n) (Fin n) K)
      = Ideal.span {minpoly K M} := minpoly.ker_aeval_eq_span_minpoly K M
  -- K[M] = range(aeval M) ≃ₐ K[X]/ker(aeval M) = K[X]/(minpoly).
  have e : ↥(Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K)))
      ≃ₐ[K] (K[X] ⧸ Ideal.span {minpoly K M}) :=
    (Subalgebra.equivOfEq _ _ hrange).trans
      ((Ideal.quotientKerEquivRange
          (Polynomial.aeval M : K[X] →ₐ[K] Matrix (Fin n) (Fin n) K)).symm.trans
        (Ideal.quotientEquivAlgOfEq K hker))
  rw [LinearEquiv.finrank_eq e.toLinearEquiv]
  exact finrank_quotient_span_eq_natDegree

-- ============================================================
-- SECTION II: The Frobenius dimension bound (NOW PROVED, 0 axioms)
-- ============================================================

/-
  The Frobenius dimension bound `dim_K C(M) ≥ n` is no longer an axiom: it is
  proved below from the Mathlib PID structure theorem.  The argument runs

      C(M)  ≅ₐ  C(φ)        (φ := `Matrix.toLinAlgEquiv' M`, via the algebra
                            equivalence `Matrix ≃ₐ End K (Fin n → K)`)
      C(φ)  ⊇  End_{K[X]}(AEval' φ)   (every K[X]-linear endomorphism of the
                            module `Fin n → K` with `X` acting as `φ` commutes
                            with `φ`; this gives a K-linear injection)
      AEval' φ ≅ₗ[K[X]] ⊕ᵢ K[X]/(pᵢ^eᵢ) ≅ₗ[K[X]] Πᵢ K[X]/(pᵢ^eᵢ) =: S
                            (`Module.equiv_directSum_of_isTorsion`; finite torsion)
      n = dim_K S ≤ dim_K End_{K[X]} S        (multiplication embedding
                            `Algebra.lmul` is K-linear injective on the
                            commutative algebra `S`).

  Transporting `End_{K[X]} S` back along the structure isomorphism to
  `End_{K[X]}(AEval' φ)` and chaining the three steps yields `n ≤ dim_K C(M)`.
  This is the classical theorem of Frobenius (1878); the three supporting
  lemmas below are general-purpose and contain no matrix-specific content.
-/

/-- For a commutative `K[X]`-algebra `S` that is finite-dimensional over `K`,
    the multiplication embedding `S ↪ End_{K[X]} S` (left multiplication,
    `Algebra.lmul`) is a `K`-linear injection, so `dim_K S ≤ dim_K End_{K[X]} S`. -/
theorem lmul_finrank_bound (S : Type*) [CommRing S] [Algebra (K[X]) S]
    [Module K S] [IsScalarTower K (K[X]) S] [Module.Finite K S] :
    Module.finrank K S ≤ Module.finrank K (Module.End (K[X]) S) := by
  let f : S →ₗ[K] Module.End (K[X]) S :=
    (Algebra.lmul (K[X]) S).toLinearMap.restrictScalars K
  have hinj : Function.Injective f :=
    fun a b hab => Algebra.lmul_injective (R := K[X]) (A := S) hab
  exact LinearMap.finrank_le_finrank_of_injective hinj

/-- **Operator form of the Frobenius bound.**  For a linear endomorphism `φ` of a
    finite-dimensional `K`-vector space `V`, the `K[X]`-endomorphisms of the
    `K[X]`-module `AEval' φ` (i.e. the endomorphisms of `V` commuting with `φ`)
    span a `K`-space of dimension at least `dim_K V`.

    Proof: `AEval' φ` is a finite torsion `K[X]`-module; the PID structure
    theorem decomposes it as `⊕ᵢ K[X]/(pᵢ^eᵢ)`, isomorphic (finite index) to the
    commutative `K[X]`-algebra `S := Πᵢ K[X]/(pᵢ^eᵢ)`, and
    `dim_K V = dim_K S ≤ dim_K End_{K[X]} S = dim_K End_{K[X]}(AEval' φ)` by
    `lmul_finrank_bound`. -/
theorem aeval_end_bound {V : Type*} [AddCommGroup V] [Module K V]
    [FiniteDimensional K V] (φ : V →ₗ[K] V) :
    Module.finrank K V ≤ Module.finrank K (Module.End (K[X]) (Module.AEval' φ)) := by
  have htor : Module.IsTorsion (K[X]) (Module.AEval' φ) :=
    Module.AEval.isTorsion_of_finiteDimensional K V φ
  obtain ⟨ι, _, p, _, e, ⟨iso⟩⟩ := Module.equiv_directSum_of_isTorsion htor
  let Q : ι → Type _ := fun i => K[X] ⧸ (K[X] ∙ p i ^ e i)
  let isoS : Module.AEval' φ ≃ₗ[K[X]] (∀ i, Q i) :=
    iso.trans (DirectSum.linearEquivFunOnFintype K[X] ι Q)
  haveI hFinS : Module.Finite K (∀ i, Q i) :=
    Module.Finite.equiv (isoS.restrictScalars K)
  calc Module.finrank K V
      = Module.finrank K (Module.AEval' φ) := ((Module.AEval'.of φ).symm.finrank_eq)
    _ = Module.finrank K (∀ i, Q i) := ((isoS.restrictScalars K).finrank_eq)
    _ ≤ Module.finrank K (Module.End (K[X]) (∀ i, Q i)) := lmul_finrank_bound (∀ i, Q i)
    _ = Module.finrank K (Module.End (K[X]) (Module.AEval' φ)) :=
          ((isoS.conj.restrictScalars K).finrank_eq).symm

/-- **The bridge (operator form).**  For `φ : End K V` over a finite-dimensional
    `V`, the centralizer of `φ` inside `End K V` has `K`-dimension at least
    `dim_K V`.  The `K[X]`-endomorphisms of `AEval' φ` inject `K`-linearly into
    the centralizer (a `K[X]`-linear map commutes with the `X`-action `= φ`),
    and `aeval_end_bound` lower-bounds their dimension by `dim_K V`. -/
theorem endK_centralizer_bound {V : Type*} [AddCommGroup V] [Module K V]
    [FiniteDimensional K V] (φ : Module.End K V) :
    Module.finrank K V ≤
      Module.finrank K (Subalgebra.centralizer K ({φ} : Set (Module.End K V))) := by
  let ι0 : Module.End (K[X]) (Module.AEval' φ) →ₗ[K] Module.End K (Module.AEval' φ) :=
    LinearMap.restrictScalarsₗ K (K[X]) (Module.AEval' φ) (Module.AEval' φ) K
  let toEnd : Module.End (K[X]) (Module.AEval' φ) →ₗ[K] Module.End K V :=
    ((Module.AEval'.of φ).conj.symm.toLinearMap) ∘ₗ ι0
  have hval : ∀ (T : Module.End (K[X]) (Module.AEval' φ)) (x : V),
      toEnd T x = (Module.AEval'.of φ).symm (T (Module.AEval'.of φ x)) := fun T x => rfl
  have hmem : ∀ T, toEnd T ∈ Subalgebra.centralizer K ({φ} : Set (Module.End K V)) := by
    intro T
    rw [Subalgebra.mem_centralizer_iff]
    intro g hg
    simp only [Set.mem_singleton_iff] at hg
    subst hg
    ext x
    simp only [Module.End.mul_apply, hval]
    rw [← Module.AEval'.X_smul_of, map_smul, Module.AEval'.of_symm_X_smul]
  have htoEnd_inj : Function.Injective toEnd := by
    have h1 : Function.Injective (⇑(Module.AEval'.of φ).conj.symm) :=
      (Module.AEval'.of φ).conj.symm.injective
    have h2 : Function.Injective ι0 :=
      fun a b hab => LinearMap.restrictScalars_injective K hab
    intro a b hab
    exact h2 (h1 hab)
  let L : Module.End (K[X]) (Module.AEval' φ) →ₗ[K]
      ↥(Subalgebra.toSubmodule (Subalgebra.centralizer K ({φ} : Set (Module.End K V)))) :=
    LinearMap.codRestrict _ toEnd hmem
  have hLinj : Function.Injective L := by
    intro a b hab
    apply htoEnd_inj
    have := congrArg Subtype.val hab
    simpa [L, LinearMap.codRestrict] using this
  calc Module.finrank K V
      ≤ Module.finrank K (Module.End (K[X]) (Module.AEval' φ)) := aeval_end_bound φ
    _ ≤ Module.finrank K ↥(Subalgebra.toSubmodule
          (Subalgebra.centralizer K ({φ} : Set (Module.End K V)))) :=
          LinearMap.finrank_le_finrank_of_injective hLinj
    _ = Module.finrank K (Subalgebra.centralizer K ({φ} : Set (Module.End K V))) := rfl

/-- **Frobenius dimension bound (Frobenius, 1878).**  The centralizer
    `C(M) = {N : NM = MN}` of an `n × n` matrix over a field has `K`-dimension at
    least `n`.

    Transferred from `endK_centralizer_bound` along the algebra equivalence
    `Matrix.toLinAlgEquiv' : Matrix (Fin n) (Fin n) K ≃ₐ[K] End K (Fin n → K)`,
    which carries `C(M)` isomorphically onto `C(φ)` for `φ := toLinAlgEquiv' M`. -/
theorem finrank_centralizer_ge
    (M : Matrix (Fin n) (Fin n) K) :
    Fintype.card (Fin n)
      ≤ Module.finrank K
          ↥(Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))) := by
  classical
  let e : Matrix (Fin n) (Fin n) K ≃ₐ[K] Module.End K (Fin n → K) := Matrix.toLinAlgEquiv'
  let φ : Module.End K (Fin n → K) := e M
  have hsymm : e.symm φ = M := by simp [φ]
  have hmap : (Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))).map e.toAlgHom
            = Subalgebra.centralizer K ({φ} : Set (Module.End K (Fin n → K))) := by
    apply le_antisymm
    · rintro y ⟨z, hz, rfl⟩
      show (e z) ∈ Subalgebra.centralizer K ({φ} : Set (Module.End K (Fin n → K)))
      rw [Subalgebra.mem_centralizer_iff]
      intro g hg; simp only [Set.mem_singleton_iff] at hg; subst hg
      have hz' : z ∈ Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K)) := hz
      rw [Subalgebra.mem_centralizer_iff] at hz'
      have hzM : M * z = z * M := hz' M (by simp)
      have := congrArg e hzM
      simpa [map_mul, φ] using this
    · intro y hy
      rw [Subalgebra.mem_centralizer_iff] at hy
      refine ⟨e.symm y, ?_, by simp⟩
      show e.symm y ∈ Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))
      rw [Subalgebra.mem_centralizer_iff]
      intro g hg; simp only [Set.mem_singleton_iff] at hg; subst hg
      have hyφ : φ * y = y * φ := hy φ (by simp)
      have := congrArg e.symm hyφ
      simpa [map_mul, hsymm] using this
  have hfin1 : Module.finrank K
        ↥(Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K)))
      = Module.finrank K
        ↥((Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))).map e.toAlgHom) :=
    (Subalgebra.equivMapOfInjective _ e.toAlgHom e.injective).toLinearEquiv.finrank_eq
  rw [hfin1, hmap, ← Module.finrank_fintype_fun_eq_card (R := K) (η := Fin n)]
  exact endK_centralizer_bound φ

-- ============================================================
-- SECTION III: deg(minpoly M) ≤ n
-- ============================================================

/-- The minimal polynomial of an `n × n` matrix has degree at most `n`
    (it divides the degree-`n` characteristic polynomial). -/
theorem natDegree_minpoly_le
    (M : Matrix (Fin n) (Fin n) K) :
    (minpoly K M).natDegree ≤ Fintype.card (Fin n) := by
  have hdvd : minpoly K M ∣ M.charpoly := minpoly.dvd K M (Matrix.aeval_self_charpoly M)
  have hch : M.charpoly ≠ 0 := M.charpoly_monic.ne_zero
  calc (minpoly K M).natDegree
      ≤ M.charpoly.natDegree := Polynomial.natDegree_le_of_dvd hdvd hch
    _ = Fintype.card (Fin n) := M.charpoly_natDegree_eq_dim

-- ============================================================
-- SECTION IV: Main theorem — (iii) ⟹ (ii) ⟹ (i)
-- ============================================================

/-- **Converse edge of the triple equivalence (iii) ⟹ (ii).**  If the
    centralizer of `M` coincides with the algebra `K[M]` of polynomials in `M`,
    then `M` is nonderogatory: `minpoly K M = charpoly M`.

    Together with the forward edge `commuting_matrix_is_polynomial`
    (cyclic ⟹ centralizer = K[M]) and the parent biconditional
    (nonderogatory ⟺ cyclic), this closes the triple equivalence

      cyclic vector ⟺ minpoly = charpoly ⟺ centralizer = K[M]. -/
theorem centralizer_eq_adjoin_implies_nonderogatory
    (M : Matrix (Fin n) (Fin n) K)
    (h : Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))
          = Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K))) :
    minpoly K M = M.charpoly := by
  have hM : IsIntegral K M := IsIntegral.of_finite K M
  -- finrank C(M) = finrank K[M] = deg(minpoly).
  have hcentr_adj :
      Module.finrank K ↥(Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K)))
        = (minpoly K M).natDegree := by
    rw [h, finrank_adjoin_eq_natDegree_minpoly M]
  -- n ≤ deg(minpoly) ≤ n, forcing equality.
  have hge : Fintype.card (Fin n) ≤ (minpoly K M).natDegree := by
    rw [← hcentr_adj]; exact finrank_centralizer_ge M
  have hle : (minpoly K M).natDegree ≤ Fintype.card (Fin n) := natDegree_minpoly_le M
  -- deg(charpoly) = n = deg(minpoly), so charpoly.natDegree ≤ minpoly.natDegree.
  have hdeg : M.charpoly.natDegree ≤ (minpoly K M).natDegree := by
    rw [M.charpoly_natDegree_eq_dim]; omega
  -- Two monic polynomials, one dividing the other with no larger degree, are equal.
  have hdvd : minpoly K M ∣ M.charpoly := minpoly.dvd K M (Matrix.aeval_self_charpoly M)
  have hmin_monic : (minpoly K M).Monic := minpoly.monic hM
  exact (Polynomial.eq_of_monic_of_dvd_of_natDegree_le hmin_monic M.charpoly_monic hdvd hdeg).symm

/-- **Capstone: the converse edge (iii) ⟹ (i).**  If the centralizer of `M`
    equals `K[M]`, then `M` admits a cyclic vector.  This is the edge that
    closes the triple equivalence (combined with the forward edge
    `commuting_matrix_is_polynomial` and the parent biconditional). -/
theorem centralizer_eq_adjoin_implies_cyclic
    (M : Matrix (Fin n) (Fin n) K)
    (h : Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))
          = Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K))) :
    ∃ v, GeneralCyclicVector.IsCyclicVector M v :=
  (CyclicVectorBiconditional.nonderogatory_iff_has_cyclic_vector M).mp
    (centralizer_eq_adjoin_implies_nonderogatory M h)

end CyclicCommutantConverse

end
