import Mathlib.LinearAlgebra.Matrix.Charpoly.Minpoly
import Mathlib.LinearAlgebra.AnnihilatingPolynomial
import Mathlib.Algebra.Polynomial.Module.AEval
import Mathlib.LinearAlgebra.FreeModule.Finite.Quotient
import Mathlib.Tactic

/-!
# Invariant Factor Decomposition via Annihilator Ideal

## Source
Open question from `cayley-hamilton-oq-01`.

## What This Proves

For an n×n matrix M over field K, with K^n as a K[X]-module via M
(formalized using `Module.AEval' M.mulVecLin`):

**Proved theorems (0 sorries):**
1. `kn_module_annihilator_eq_minpoly`: The K[X]-annihilator of K^n = `Ideal.span {minpoly K M}`.
2. `minpoly_mem_vecAnnIdeal`: minpoly K M annihilates every vector in the AEval' module.
3. `minpoly_ideal_le_vecAnnIdeal`: `Ideal.span {minpoly K M} ≤ vecAnnIdeal M v` for all v.
4. `cyclic_vecAnnIdeal_eq_minpoly`: For cyclic v, `vecAnnIdeal M v = Ideal.span {minpoly K M}`.
   Proof: polynomial division f = q·minpoly + r, IsCyclicVector kills r.

## Key Mathlib Results Used
- `Polynomial.span_minpoly_eq_annihilator K f`: Main theorem (Mathlib).
  NOTE: `𝕜` is explicit here (from `variable (𝕜)` in the Mathlib section). Pass `K` explicitly.
- `Matrix.minpoly_toLin'`: `minpoly K (toLin' M) = minpoly K M` (Mathlib)
- `Matrix.toLin'_apply'`: `Matrix.toLin' M = M.mulVecLin` (Mathlib)
- `minpoly.aeval`: `aeval a (minpoly K a) = 0` (Mathlib)
-/

namespace CayleyHamiltonOQ01OQ01

open Matrix Polynomial Module BigOperators

variable {K : Type*} [Field K] {n : ℕ}

/-! ## Helper: minpoly K M = minpoly K M.mulVecLin -/

private theorem minpoly_matrix_eq_mulVecLin (M : Matrix (Fin n) (Fin n) K) :
    minpoly K M = minpoly K M.mulVecLin := by
  rw [show M.mulVecLin = Matrix.toLin' M from (Matrix.toLin'_apply' M).symm]
  exact (Matrix.minpoly_toLin' (M := M)).symm

/-! ## I. Module Annihilator Theorem -/

/-- The K[X]-annihilator of K^n (as Module.AEval' M.mulVecLin) equals the ideal
    spanned by the minimal polynomial.

    Proof: Direct corollary of Mathlib's `Polynomial.span_minpoly_eq_annihilator`
    (which handles the `Module.End` version) combined with `minpoly K M = minpoly K M.mulVecLin`. -/
theorem kn_module_annihilator_eq_minpoly (M : Matrix (Fin n) (Fin n) K) :
    Ideal.span {minpoly K M} =
    Module.annihilator K[X] (Module.AEval' M.mulVecLin) := by
  rw [minpoly_matrix_eq_mulVecLin]
  -- span_minpoly_eq_annihilator has 𝕜 explicit (via `variable (𝕜)` in Mathlib).
  -- Must pass K explicitly; the module type (Fin n → K) is inferred from M.mulVecLin.
  exact Polynomial.span_minpoly_eq_annihilator K M.mulVecLin

/-! ## II. Vector Annihilator Theory -/

/-- The annihilator ideal of v under M: {f : K[X] | f(M) · v = 0}.
    This is the annihilator of the cyclic K[X]-submodule generated by v. -/
noncomputable def vecAnnIdeal (M : Matrix (Fin n) (Fin n) K) (v : Fin n → K) : Ideal K[X] :=
  (Submodule.span K[X] {Module.AEval'.of M.mulVecLin v}).annihilator

/-- f ∈ vecAnnIdeal M v iff f kills v in the AEval' module. -/
theorem mem_vecAnnIdeal_iff {M : Matrix (Fin n) (Fin n) K} {v : Fin n → K} {f : K[X]} :
    f ∈ vecAnnIdeal M v ↔ f • (Module.AEval'.of M.mulVecLin v) = 0 :=
  Submodule.mem_annihilator_span_singleton _ _

/-- The minimal polynomial of M annihilates every vector v in the AEval' module:
    `(minpoly K M) • (AEval'.of M.mulVecLin v) = 0`. -/
theorem minpoly_mem_vecAnnIdeal (M : Matrix (Fin n) (Fin n) K) (v : Fin n → K) :
    minpoly K M ∈ vecAnnIdeal M v := by
  rw [mem_vecAnnIdeal_iff]
  -- Rewrite to M.mulVecLin version
  rw [minpoly_matrix_eq_mulVecLin]
  -- Use: (AEval'.of φ).symm (f • m) = aeval φ f • (AEval'.of φ).symm m
  apply_fun (Module.AEval'.of M.mulVecLin).symm using (Module.AEval'.of M.mulVecLin).symm.injective
  simp only [LinearEquiv.map_zero, Module.AEval.of_symm_smul, LinearEquiv.symm_apply_apply]
  -- Goal: aeval M.mulVecLin (minpoly K M.mulVecLin) • v = 0
  simp [minpoly.aeval K M.mulVecLin]

/-- The annihilator ideal inclusion: Ideal.span {minpoly K M} ≤ vecAnnIdeal M v. -/
theorem minpoly_ideal_le_vecAnnIdeal (M : Matrix (Fin n) (Fin n) K) (v : Fin n → K) :
    Ideal.span {minpoly K M} ≤ vecAnnIdeal M v := by
  rw [Ideal.span_singleton_le_iff_mem]
  exact minpoly_mem_vecAnnIdeal M v

/-! ## III. Cyclic Vector Characterization -/

/-- A vector v is cyclic for M if for all polynomials p of degree < n:
    p(M.mulVecLin) applied to v equals 0 implies p = 0.
    This uses the linear map form compatible with the AEval' module structure. -/
def IsCyclicVector (M : Matrix (Fin n) (Fin n) K) (v : Fin n → K) : Prop :=
  ∀ p : K[X], p.natDegree < n → aeval M.mulVecLin p v = 0 → p = 0

/-- For a cyclic vector, vecAnnIdeal M v = Ideal.span {minpoly K M}.
    Proof: If f ∈ vecAnnIdeal (f(M)v = 0), write f = q·minpoly + r, deg r < n.
    Then r(M)v = f(M)v - q(M)·minpoly(M)v = 0 - 0 = 0.
    By IsCyclicVector: r = 0, so minpoly | f. -/
theorem cyclic_vecAnnIdeal_eq_minpoly (M : Matrix (Fin n) (Fin n) K) (v : Fin n → K)
    (hv : IsCyclicVector M v) (hM : (minpoly K M).natDegree = n) :
    vecAnnIdeal M v = Ideal.span {minpoly K M} := by
  -- Establish that minpoly K M is monic (M is integral via Cayley-Hamilton)
  have hM_int : IsIntegral K M :=
    ⟨M.charpoly, Matrix.charpoly_monic M, Matrix.aeval_self_charpoly M⟩
  have hMonic : (minpoly K M).Monic := minpoly.monic hM_int
  apply le_antisymm _ (minpoly_ideal_le_vecAnnIdeal M v)
  intro f hf
  rw [mem_vecAnnIdeal_iff] at hf
  rw [Ideal.mem_span_singleton]
  -- Handle the degenerate case minpoly = 1 (forces minpoly | f trivially)
  by_cases hne : minpoly K M = 1
  · simp [hne]
  -- Main case: use modular division f = q·minpoly + r, show r = 0
  rw [← Polynomial.modByMonic_eq_zero_iff_dvd hMonic]
  -- Step 1: Extract aeval M.mulVecLin f v = 0 from the AEval' membership hf
  have hfv : aeval M.mulVecLin f v = 0 := by
    have h := congr_arg (Module.AEval'.of M.mulVecLin).symm hf
    simp only [LinearEquiv.map_zero, Module.AEval.of_symm_smul,
               LinearEquiv.symm_apply_apply] at h
    exact h
  -- Step 2: aeval M.mulVecLin (minpoly K M) = 0 (as a linear map)
  have hmin : aeval M.mulVecLin (minpoly K M) = 0 := by
    rw [minpoly_matrix_eq_mulVecLin]
    exact minpoly.aeval K M.mulVecLin
  -- Step 3: The remainder r = f %ₘ minpoly K M also kills v
  have hr : aeval M.mulVecLin (f %ₘ minpoly K M) v = 0 := by
    have hdiv : f = f %ₘ (minpoly K M) + (minpoly K M) * (f /ₘ (minpoly K M)) :=
      (Polynomial.modByMonic_add_div f hMonic).symm
    have hfv2 : aeval M.mulVecLin f v = aeval M.mulVecLin (f %ₘ minpoly K M) v := by
      conv_lhs => rw [hdiv]
      simp only [map_add, map_mul, LinearMap.add_apply, LinearMap.mul_apply,
                 hmin, LinearMap.zero_apply, zero_mul, add_zero]
    rw [← hfv2]; exact hfv
  -- Step 4: Apply IsCyclicVector — r has degree < n and r(M)v = 0, so r = 0
  apply hv
  · have h := Polynomial.natDegree_modByMonic_lt f hMonic hne
    rwa [hM] at h
  · exact hr

end CayleyHamiltonOQ01OQ01
