/-
  The operator ⟷ K[X]-module bridge for the cyclic-vector theorem
  (cayley-hamilton-cyclic-vector-all-fields-oq-03, the conceptual core)

  Two earlier companions settle the "concrete" halves of OQ-03:

  * `CayleyHamiltonCyclicVectorAllFieldsOQ03.lean` — direction (a): the
    coordinate-free *operator* cyclic-vector theorem for `T : V →ₗ[K] V` on a
    finite-dimensional vector space, proved by basis reduction to the verified
    matrix theorem.
  * `CayleyHamiltonCyclicVectorAllFieldsOQ03PID.lean` — direction (b): the
    *module-theoretic* criterion `M` cyclic `⟺ M ≃ₗ[R] R ⧸ Module.annihilator R M`
    over a commutative ring, with the PID-specific candidate-generator content.

  This file supplies the **missing conceptual link** OQ-03 actually asks for:
  recognize the operator statement as a literal instance of the PID/module
  picture, by viewing `V` as a module over `K[X]` with `X` acting as `T`
  (Mathlib's `Module.AEval' T`). Under this dictionary the module annihilator is
  exactly the minimal-polynomial ideal (`span_minpoly_eq_annihilator`), so the
  abstract criterion specializes to

      `T` has a cyclic vector  ⟺  `V ≃ₗ[K[X]] K[X] ⧸ (minpoly K T)`.

  ## Contents

  * `restrictScalars_span_singleton_eq_span_orbit` — the orbit identity: the
    `K[X]`-submodule generated by `w`, viewed as a `K`-submodule, is the
    `K`-span of the `X`-orbit `{Xⁿ • w}`. This is what makes "cyclic over `K[X]`"
    and "Krylov orbit spans over `K`" the same condition.
  * `aeval_cyclic_iff_krylov_span_top` — the operator dictionary: a cyclic
    generator for `Module.AEval' T` exists iff some `v : V` has Krylov orbit
    `{Tⁿ v}` spanning `V` over `K`.
  * `aeval_cyclic_iff_equiv_quot_minpoly` — direction (b) specialized to
    `R := K[X]`, `M := Module.AEval' T`: cyclicity of `AEval' T` `⟺`
    `AEval' T ≃ₗ[K[X]] K[X] ⧸ (minpoly K T)`.
  * `krylov_cyclic_iff_equiv_quot_minpoly` — the capstone, composing the two:
    `T` has a Krylov-cyclic vector `⟺ V` (as a `K[X]`-module via `T`) is
    isomorphic to `K[X] ⧸ (minpoly K T)`. This is the cyclic-vector theorem
    recognized as the PID structure theorem.

  ## Status

  0 sorries, 0 `axiom` declarations. Self-contained over `import Mathlib` plus the
  merged PID companion.
-/

import Mathlib
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ03PID

namespace CayleyHamiltonCyclicVectorAllFieldsOQ03Bridge

open Polynomial Submodule

variable {K : Type*} [Field K]
variable {V : Type*} [AddCommGroup V] [Module K V]

/-! ## The orbit identity

The `K[X]`-submodule generated by a single element `w`, restricted back to `K`,
is the `K`-span of the orbit `{Xⁿ • w : n}`. The point is that `K[X]` is `K`-spanned
by the monomials `Xⁿ`, so `p • w` for `p : K[X]` is a `K`-combination of the
`Xⁿ • w`. -/

/-- For `w` in the `K[X]`-module `Module.AEval' T`, the `K`-restriction of the
cyclic submodule `K[X] ∙ w` equals the `K`-span of the `X`-orbit `{Xⁿ • w}`. -/
lemma restrictScalars_span_singleton_eq_span_orbit (T : Module.End K V)
    (w : Module.AEval' T) :
    (Submodule.span K[X] {w}).restrictScalars K
      = Submodule.span K (Set.range fun n : ℕ => (X ^ n : K[X]) • w) := by
  apply le_antisymm
  · -- `K[X] ∙ w ⊆ span_K {Xⁿ • w}`: expand `p • w` over the monomial basis.
    intro x hx
    rw [Submodule.restrictScalars_mem, Submodule.mem_span_singleton] at hx
    obtain ⟨p, rfl⟩ := hx
    induction p using Polynomial.induction_on' with
    | add p q hp hq => rw [add_smul]; exact Submodule.add_mem _ hp hq
    | monomial n a =>
        rw [← Polynomial.C_mul_X_pow_eq_monomial, mul_smul, Module.AEval.C_smul]
        exact Submodule.smul_mem _ a (Submodule.subset_span ⟨n, rfl⟩)
  · -- `span_K {Xⁿ • w} ⊆ K[X] ∙ w`: each `Xⁿ • w` is in the cyclic submodule.
    rw [Submodule.span_le]
    rintro _ ⟨n, rfl⟩
    rw [SetLike.mem_coe, Submodule.restrictScalars_mem]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self w)

/-! ## The operator dictionary -/

/-- **Cyclic over `K[X]` ⟺ Krylov orbit spans over `K`.** A cyclic generator for
the `K[X]`-module `Module.AEval' T` exists exactly when some `v : V` has its
Krylov orbit `{Tⁿ v}` spanning `V` over `K`. -/
theorem aeval_cyclic_iff_krylov_span_top [FiniteDimensional K V] (T : Module.End K V) :
    (∃ w : Module.AEval' T, Submodule.span K[X] {w} = ⊤) ↔
      (∃ v : V, Submodule.span K (Set.range fun n : ℕ => (T ^ n) v) = ⊤) := by
  rw [(Module.AEval'.of T).surjective.exists]
  refine exists_congr fun v => ?_
  rw [← Submodule.restrictScalars_eq_top_iff (S := K),
      restrictScalars_span_singleton_eq_span_orbit]
  have hset : (Set.range fun n : ℕ => (X ^ n : K[X]) • Module.AEval'.of T v)
      = Module.AEval'.of T '' (Set.range fun n : ℕ => (T ^ n) v) := by
    rw [← Set.range_comp]
    congr 1
    funext n
    rw [Function.comp_apply, Module.AEval'.X_pow_smul_of, Module.End.smul_def]
  rw [hset, ← Submodule.map_span, Submodule.map_eq_top_iff]

/-! ## Recognizing the PID structure theorem -/

/-- **Direction (b) on the operator module.** Specializing the commutative-ring
criterion `cyclic_iff_nonempty_equiv_quotient_annihilator` to `R := K[X]`,
`M := Module.AEval' T` and rewriting the annihilator as the minimal-polynomial
ideal (`span_minpoly_eq_annihilator`): `Module.AEval' T` is cyclic iff it is
isomorphic, as a `K[X]`-module, to `K[X] ⧸ (minpoly K T)`. -/
theorem aeval_cyclic_iff_equiv_quot_minpoly (T : Module.End K V) :
    (∃ w : Module.AEval' T, Submodule.span K[X] {w} = ⊤) ↔
      Nonempty (Module.AEval' T ≃ₗ[K[X]] K[X] ⧸ Ideal.span {minpoly K T}) := by
  rw [CayleyHamiltonCyclicVectorAllFieldsOQ03PID.cyclic_iff_nonempty_equiv_quotient_annihilator]
  constructor
  · rintro ⟨e⟩
    exact ⟨e.trans (Submodule.quotEquivOfEq _ _ (span_minpoly_eq_annihilator K T).symm)⟩
  · rintro ⟨e⟩
    exact ⟨e.trans (Submodule.quotEquivOfEq _ _ (span_minpoly_eq_annihilator K T))⟩

/-- **Capstone: the cyclic-vector theorem as the PID structure theorem.**
Composing the operator dictionary with the module criterion: `T` admits a Krylov
cyclic vector (some `v` with `{Tⁿ v}` spanning `V` over `K`) if and only if `V`,
regarded as a `K[X]`-module with `X` acting as `T`, is isomorphic to
`K[X] ⧸ (minpoly K T)`. -/
theorem krylov_cyclic_iff_equiv_quot_minpoly [FiniteDimensional K V] (T : Module.End K V) :
    (∃ v : V, Submodule.span K (Set.range fun n : ℕ => (T ^ n) v) = ⊤) ↔
      Nonempty (Module.AEval' T ≃ₗ[K[X]] K[X] ⧸ Ideal.span {minpoly K T}) := by
  rw [← aeval_cyclic_iff_krylov_span_top, aeval_cyclic_iff_equiv_quot_minpoly]

end CayleyHamiltonCyclicVectorAllFieldsOQ03Bridge
