/-
  Nonderogatory Operators: Module-Theoretic Extension to Infinite Dimensions

  Extends the cyclic vector theory from finite-dimensional matrices
  (CayleyHamiltonMinpolyOQ05OQ01.lean) to general endomorphisms on K-modules.

  The finite-dimensional proof uses:
  - "Nonderogatory" = minpoly equals charpoly
  - Union avoidance over finitely many proper subspaces (irreducible factors)

  In infinite dimensions, there is no characteristic polynomial. The correct
  generalization uses K[X]-module structure:
  - V becomes a K[X]-module via the action X · v = T(v)
  - "Nonderogatory" = V is a cyclic K[X]-module
  - Cyclic vector = generator of the K[X]-module

  The key construction is the evaluation map φ_v : K[X] → V, p ↦ p(T)(v),
  which bridges polynomial algebra and cyclic subspaces. Its image is the
  T-cyclic subspace of v, and its kernel is the annihilator ideal.

  For the structure theorem for f.g. modules over PIDs:
  - V ≅ ⊕ᵢ K[X]/(fᵢ) with f₁ | f₂ | ⋯ | fᵣ (invariant factors)
  - V cyclic ⟺ r = 1 (single invariant factor)
  - minpoly = fᵣ, charpoly = ∏ fᵢ
  - "nonderogatory" (minpoly = charpoly) ⟺ cyclic (r = 1)

  REFERENCES:
  - CayleyHamiltonMinpolyOQ05OQ01.lean: finite-dim proof (infinite field)
  - CayleyHamiltonMinpolyOQ05OQ01OQ02.lean: measure-theoretic (ℝ)
  - CayleyHamiltonMinpolyOQ05.lean: K-algebra minpoly reduction
-/
import Mathlib

noncomputable section

namespace NonderogatoryModule

open Polynomial

variable {K : Type*} [Field K]
variable {V : Type*} [AddCommGroup V] [Module K V]

-- ============================================================
-- SECTION I: Definitions
-- ============================================================

/-- The T-cyclic subspace generated by v: span_K{v, Tv, T²v, ...}.
    This is the smallest T-invariant K-subspace containing v. -/
def cyclicSubspace (T : Module.End K V) (v : V) : Submodule K V :=
  Submodule.span K (Set.range fun k : ℕ => (T ^ k : Module.End K V) v)

/-- A vector v is cyclic for T if the powers {T^k v} span all of V. -/
def IsCyclicVector (T : Module.End K V) (v : V) : Prop :=
  cyclicSubspace T v = ⊤

/-- An endomorphism is nonderogatory (module-theoretic) if V is a cyclic
    K[X]-module. This is the correct infinite-dimensional generalization
    of "minpoly = charpoly". -/
def IsNonderogatory (T : Module.End K V) : Prop :=
  ∃ v, IsCyclicVector T v

-- ============================================================
-- SECTION II: The Evaluation Map
-- ============================================================

/-- The evaluation map φ_v : K[X] → V sending p to p(T)(v).
    This is the fundamental bridge: its image is the cyclic subspace,
    its kernel is the annihilator ideal. -/
def evalMap (T : Module.End K V) (v : V) : K[X] →ₗ[K] V where
  toFun p := (aeval T p) v
  map_add' p q := by
    show (aeval T (p + q)) v = (aeval T p) v + (aeval T q) v
    rw [map_add, LinearMap.add_apply]
  map_smul' r p := by
    simp only [RingHom.id_apply]
    show (aeval T (r • p)) v = r • (aeval T p) v
    have h : (aeval T).toLinearMap (r • p) = r • (aeval T).toLinearMap p :=
      (aeval T).toLinearMap.map_smul r p
    show ((aeval T).toLinearMap (r • p)) v = r • ((aeval T).toLinearMap p) v
    rw [h, LinearMap.smul_apply]

@[simp]
theorem evalMap_apply (T : Module.End K V) (v : V) (p : K[X]) :
    evalMap T v p = (aeval T p) v := rfl

theorem evalMap_one (T : Module.End K V) (v : V) :
    evalMap T v 1 = v := by
  simp [map_one, LinearMap.one_apply]

theorem evalMap_X (T : Module.End K V) (v : V) :
    evalMap T v X = T v := by
  simp [aeval_X]

theorem evalMap_X_pow (T : Module.End K V) (v : V) (k : ℕ) :
    evalMap T v (X ^ k) = (T ^ k) v := by
  simp [map_pow, aeval_X]

-- ============================================================
-- SECTION III: Cyclic Subspace Properties
-- ============================================================

/-- v is in its own cyclic subspace: T⁰v = v. -/
theorem mem_cyclicSubspace_self (T : Module.End K V) (v : V) :
    v ∈ cyclicSubspace T v :=
  Submodule.subset_span ⟨0, by simp⟩

/-- T^k v is in the cyclic subspace of v. -/
theorem pow_mem_cyclicSubspace (T : Module.End K V) (v : V) (k : ℕ) :
    (T ^ k) v ∈ cyclicSubspace T v :=
  Submodule.subset_span ⟨k, rfl⟩

/-- The cyclic subspace is T-invariant: T maps it into itself. -/
theorem map_cyclicSubspace_le (T : Module.End K V) (v : V) :
    Submodule.map T (cyclicSubspace T v) ≤ cyclicSubspace T v := by
  rw [Submodule.map_le_iff_le_comap]
  apply Submodule.span_le.mpr
  rintro w ⟨k, rfl⟩
  show T ((T ^ k) v) ∈ cyclicSubspace T v
  have h : T ((T ^ k) v) = (T ^ (k + 1)) v := by
    rw [pow_succ']
    rfl
  rw [h]
  exact pow_mem_cyclicSubspace T v (k + 1)

/-- T applied to an element of the cyclic subspace stays in it. -/
theorem cyclicSubspace_T_mem (T : Module.End K V) (v : V)
    (w : V) (hw : w ∈ cyclicSubspace T v) :
    T w ∈ cyclicSubspace T v := by
  have := map_cyclicSubspace_le T v
  exact this ⟨w, hw, rfl⟩

-- ============================================================
-- SECTION IV: Image of Evaluation Map = Cyclic Subspace
-- ============================================================

/-- The image of evalMap equals the cyclic subspace. This is the
    key structural fact: every element of the orbit is p(T)v for
    some polynomial p, and conversely. -/
theorem range_evalMap_eq_cyclicSubspace (T : Module.End K V) (v : V) :
    LinearMap.range (evalMap T v) = cyclicSubspace T v := by
  ext w
  constructor
  · -- Forward: p(T)v is in span{T^k v}
    rintro ⟨p, rfl⟩
    simp only [evalMap_apply]
    -- p(T)v is a K-linear combination of T^k v for k ≤ deg p
    -- This follows because aeval T p = ∑ coeff(p,k) * T^k
    induction p using Polynomial.induction_on' with
    | h_add p q hp hq =>
      rw [map_add, LinearMap.add_apply]
      exact Submodule.add_mem _ (hp ⟨p, rfl⟩) (hq ⟨q, rfl⟩)
    | h_monomial n a =>
      rw [aeval_monomial]
      show a • (T ^ n) v ∈ cyclicSubspace T v
      exact Submodule.smul_mem _ a (pow_mem_cyclicSubspace T v n)
  · -- Backward: elements of span{T^k v} are in the image
    intro hw
    refine Submodule.span_induction hw ?_ ?_ ?_ ?_
    · rintro w ⟨k, rfl⟩
      exact ⟨X ^ k, by simp [map_pow, aeval_X]⟩
    · exact ⟨0, by simp⟩
    · rintro w₁ w₂ ⟨p₁, hp₁⟩ ⟨p₂, hp₂⟩
      exact ⟨p₁ + p₂, by simp [map_add, LinearMap.add_apply, hp₁, hp₂]⟩
    · rintro r w ⟨p, hp⟩
      refine ⟨C r * p, ?_⟩
      simp only [evalMap_apply, map_mul, map_C, Algebra.algebraMap_eq_smul_one]
      rw [LinearMap.smul_apply, LinearMap.one_apply, LinearMap.mul_apply, hp]

-- ============================================================
-- SECTION V: Cyclic Vector Characterization
-- ============================================================

/-- v is cyclic iff the evaluation map is surjective. -/
theorem isCyclicVector_iff_surjective (T : Module.End K V) (v : V) :
    IsCyclicVector T v ↔ Function.Surjective (evalMap T v) := by
  rw [IsCyclicVector, ← range_evalMap_eq_cyclicSubspace, LinearMap.range_eq_top]

/-- v is cyclic iff every w is p(T)v for some polynomial p. -/
theorem isCyclicVector_iff_forall_exists (T : Module.End K V) (v : V) :
    IsCyclicVector T v ↔ ∀ w : V, ∃ p : K[X], (aeval T p) v = w := by
  rw [isCyclicVector_iff_surjective]
  constructor
  · intro h w; obtain ⟨p, hp⟩ := h w; exact ⟨p, hp⟩
  · intro h w; obtain ⟨p, hp⟩ := h w; exact ⟨p, hp⟩

-- ============================================================
-- SECTION VI: Annihilator Properties
-- ============================================================

/-- The minimal polynomial of T annihilates every vector.
    (If T is not integral, minpoly K T = 0 and this is trivial.) -/
theorem minpoly_apply_eq_zero (T : Module.End K V) (v : V) :
    (aeval T (minpoly K T)) v = 0 := by
  have h := minpoly.aeval K T
  show (aeval T (minpoly K T)) v = 0
  rw [h, LinearMap.zero_apply]

/-- If p(T)v = 0, then (qp)(T)v = 0 for any q. The annihilator
    of v is closed under multiplication: it is a K[X]-ideal. -/
theorem annihilator_mul_closed (T : Module.End K V) (v : V)
    (p q : K[X]) (hp : (aeval T p) v = 0) :
    (aeval T (q * p)) v = 0 := by
  rw [map_mul, LinearMap.mul_apply, hp, map_zero]

/-- Any multiple of the minimal polynomial annihilates v. -/
theorem minpoly_multiple_annihilates (T : Module.End K V) (v : V)
    (q : K[X]) : (aeval T (q * minpoly K T)) v = 0 :=
  annihilator_mul_closed T v (minpoly K T) q (minpoly_apply_eq_zero T v)

/-- If p(T) annihilates v, then any polynomial congruent to p
    modulo the minimal polynomial also annihilates v. -/
theorem annihilator_congr (T : Module.End K V) (v : V)
    (p q : K[X]) (hp : (aeval T p) v = 0)
    (h : minpoly K T ∣ p - q) :
    (aeval T q) v = 0 := by
  obtain ⟨r, hr⟩ := h
  have hq : q = p - r * minpoly K T := by linarith [show p - q = r * minpoly K T from hr]
  rw [show q = p - r * minpoly K T from by linarith [hr]]
  rw [map_sub, LinearMap.sub_apply, hp, minpoly_multiple_annihilates, sub_zero]

-- ============================================================
-- SECTION VII: Orbit Dimension Bound
-- ============================================================

/-- The finite span of the first d powers is contained in the cyclic subspace. -/
theorem finiteSpan_le_cyclicSubspace (T : Module.End K V) (v : V) (d : ℕ) :
    Submodule.span K (Set.range fun i : Fin d => (T ^ (i : ℕ)) v) ≤
      cyclicSubspace T v := by
  apply Submodule.span_le.mpr
  rintro w ⟨i, rfl⟩
  exact pow_mem_cyclicSubspace T v i

/-- For an integral endomorphism, the cyclic subspace of v is
    finite-dimensional with dimension ≤ deg(minpoly T). This
    bounds the "size" of any single orbit, even in infinite
    dimensions.

    Proof strategy: Since (minpoly K T)(T) = 0 and minpoly is monic
    of degree d, we get T^d v = -(a_{d-1}T^{d-1}v + ... + a_0 v).
    This makes span{v, Tv, ..., T^{d-1}v} T-invariant, so by
    induction T^k v lies in this span for all k ≥ d. -/
theorem cyclicSubspace_le_minpoly_degree (T : Module.End K V)
    (hT : IsIntegral K T) (v : V) :
    ∀ k : ℕ, (minpoly K T).natDegree ≤ k →
      (T ^ k) v ∈ Submodule.span K (Set.range fun i : Fin (minpoly K T).natDegree =>
        (T ^ (i : ℕ)) v) := by
  set d := (minpoly K T).natDegree
  set S := Submodule.span K (Set.range fun i : Fin d => (T ^ (i : ℕ)) v)
  -- Step 1: T^d v ∈ S (from minpoly relation)
  have hd_mem : (T ^ d) v ∈ S := by
    have hμ_zero := minpoly.aeval K T
    have hμ_monic := minpoly.monic hT
    -- Expand aeval T μ as a sum over range(d+1)
    have h_expand : aeval T (minpoly K T) =
        ∑ i ∈ Finset.range (d + 1),
          (minpoly K T).coeff i • T ^ i := by
      rw [aeval_def, eval₂_eq_sum_range]
      congr 1; ext i
      rw [Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
    -- Apply to v: 0 = T^d v + ∑_{i<d} coeff_i • T^i v
    have h_zero_v : (aeval T (minpoly K T)) v = 0 := by
      rw [hμ_zero, LinearMap.zero_apply]
    rw [h_expand] at h_zero_v
    -- Distribute the sum application and split off the d-th term
    rw [Finset.sum_range_succ, LinearMap.add_apply] at h_zero_v
    simp only [LinearMap.smul_apply] at h_zero_v
    -- Distribute sum application using linear map sum lemma
    have h_sum_app : (∑ i ∈ Finset.range d, (minpoly K T).coeff i • T ^ i) v =
        ∑ i ∈ Finset.range d, (minpoly K T).coeff i • (T ^ i) v := by
      induction Finset.range d using Finset.induction_on with
      | empty => simp
      | insert ha ih => rw [Finset.sum_insert ha, LinearMap.add_apply,
                             LinearMap.smul_apply, ih, Finset.sum_insert ha]
    rw [h_sum_app] at h_zero_v
    -- Use monic: coeff d = 1
    rw [show (minpoly K T).coeff d = 1 from hμ_monic, one_smul] at h_zero_v
    -- h_zero_v : (∑ ... + T^d v = 0), so T^d v = -∑ ...
    have h_eq := eq_neg_of_add_eq_zero_right h_zero_v
    rw [h_eq]
    apply S.neg_mem
    apply Submodule.sum_mem
    intro i hi
    exact S.smul_mem _ (Submodule.subset_span ⟨⟨i, Finset.mem_range.mp hi⟩, rfl⟩)
  -- Step 2: S is T-invariant
  have hS_inv : ∀ w ∈ S, T w ∈ S := by
    intro w hw
    refine Submodule.span_induction hw ?_ ?_ ?_ ?_
    · -- Generators: T(T^i v) = T^{i+1} v
      rintro _ ⟨i, rfl⟩
      rw [← LinearMap.mul_apply, ← pow_succ']
      by_cases h : (↑i : ℕ) + 1 < d
      · exact Submodule.subset_span ⟨⟨↑i + 1, h⟩, rfl⟩
      · -- i + 1 ≥ d, and i < d (since i : Fin d), so i + 1 = d
        have : (↑i : ℕ) + 1 = d := by have := i.isLt; omega
        rw [this]; exact hd_mem
    · show T 0 ∈ S; rw [map_zero]; exact S.zero_mem
    · intro x y hx hy; show T (x + y) ∈ S
      rw [map_add]; exact S.add_mem hx hy
    · intro a x hx; show T (a • x) ∈ S
      rw [map_smul]; exact S.smul_mem a hx
  -- Step 3: Induction on k
  intro k hk
  induction k with
  | zero =>
    simp only [Nat.le_zero] at hk; rw [pow_zero]
    -- d = 0: minpoly = 1, so V = {0}
    suffices v = 0 by rw [this]; exact S.zero_mem
    have h_deg0 : (minpoly K T).natDegree = 0 := hk
    have h_one : minpoly K T = 1 := by
      have := Polynomial.eq_C_of_natDegree_eq_zero h_deg0
      rw [this]; convert Polynomial.C_1
      exact show (minpoly K T).coeff 0 = 1 by
        have := (minpoly.monic hT : (minpoly K T).leadingCoeff = 1)
        rwa [Polynomial.leadingCoeff, h_deg0] at this
    have := minpoly.aeval K T; rw [h_one, map_one] at this
    have := congr_arg (· v) this; simpa [LinearMap.one_apply] using this
  | succ k ih =>
    by_cases hk' : d ≤ k
    · rw [pow_succ', LinearMap.mul_apply]
      exact hS_inv _ (ih hk')
    · have : k + 1 = d := by omega
      rw [this]; exact hd_mem

-- ============================================================
-- SECTION VIII: Relating to Finite-Dimensional Case
-- ============================================================

section FiniteDimensional

variable {n : ℕ}

/-- The matrix definition of IsCyclicVector from CayleyHamiltonMinpolyOQ05OQ01
    matches our module-theoretic definition when V = Fin n → K. -/
def IsCyclicVectorMatrix (M : Matrix (Fin n) (Fin n) K) (v : Fin n → K) : Prop :=
  ∀ p : K[X], p.natDegree < n → (aeval M p).mulVec v = 0 → p = 0

def IsNonderogatoryMatrix (M : Matrix (Fin n) (Fin n) K) : Prop :=
  minpoly K M = M.charpoly

/-- In the finite-dimensional matrix case, the matrix notion of
    nonderogatory (minpoly = charpoly) implies the module-theoretic
    notion (cyclic K[X]-module). The converse also holds by the
    structure theorem, but requires more infrastructure. -/
theorem matrix_nonderogatory_implies_module [Infinite K] (hn : 0 < n)
    (M : Matrix (Fin n) (Fin n) K) (hM : IsNonderogatoryMatrix M) :
    ∃ v, IsCyclicVectorMatrix M v := by
  -- This is proved in CayleyHamiltonMinpolyOQ05OQ01.lean
  -- (nonderogatory_has_cyclic_vector) using union avoidance
  -- over the finitely many irreducible factors of the minimal polynomial.
  sorry

end FiniteDimensional

-- ============================================================
-- SECTION IX: Invariant Factor Decomposition (Stated)
-- ============================================================

/-- The structure theorem for finitely generated torsion modules over K[X]
    decomposes V into cyclic summands. The number of summands (invariant
    factors) determines whether T has a cyclic vector.

    In the finite-dimensional case:
    - V ≅ ⊕ᵢ K[X]/(fᵢ) with f₁ | f₂ | ⋯ | fᵣ
    - minpoly T = fᵣ, charpoly T = ∏ fᵢ
    - T nonderogatory ⟺ r = 1 ⟺ cyclic K[X]-module

    In the infinite-dimensional case with countably many invariant factors:
    - V ≅ ⊕ᵢ K[X]/(fᵢ) with f₁ | f₂ | ⋯ (countable)
    - T has cyclic vector ⟺ decomposition has single factor
    - Construction of cyclic vector may require countable union avoidance
      (needs uncountable base field for constructive existence) -/
theorem structure_theorem_cyclic_iff [Module.Finite K V]
    (T : Module.End K V) (hT : IsIntegral K T) :
    IsNonderogatory T ↔ ∀ p : K[X], p ≠ 0 → p.natDegree < (minpoly K T).natDegree →
      aeval T p ≠ 0 := by
  sorry -- Requires structure theorem for f.g. modules over PIDs

end NonderogatoryModule

end
