/-
  The commutant of a cyclic endomorphism is K[X]/(μ_T)  —  algebra-level capstone
  (cayley-hamilton-cyclic-vector-all-fields-oq-02-oq-03)

  This file upgrades the *linear* description of the commutant of a cyclic
  endomorphism (`centralizerEvalEquiv : C(T) ≃ₗ[K] V`, Frobenius equality
  `dim C(T) = dim V`) to the full *algebra-level* description:

    **If `T : Module.End K V` has a cyclic vector, then its commutant is
    isomorphic as a `K`-algebra to the polynomial quotient `K[X]/(μ_T)`,
    where `μ_T = minpoly K T`.  Moreover `μ_T = χ_T` (the characteristic
    polynomial): a cyclic endomorphism is nonderogatory.**

  ## Statements

  * `end_charpoly_eq_minpoly_of_cyclic` : `T.charpoly = minpoly K T`.
    The nonderogatory *equality* — previously only the degree identity
    `deg μ_T = dim V` (`minpoly_natDegree_eq_finrank_of_cyclic`) was recorded.
  * `centralizerQuotientAlgEquiv` :
    `K[X] ⧸ span {minpoly K T}  ≃ₐ[K]  Subalgebra.centralizer K {T}`.
    The first isomorphism theorem for `aeval T`, landed on the commutant via
    `end_centralizer_eq_adjoin` (which is where the cyclic vector enters).
  * `centralizerQuotientAlgEquiv_mk_coe` : the isomorphism sends the class of
    `p` to `p(T)` — it is induced by evaluation, not an abstract accident.
  * `finrank_quotient_span_minpoly_of_cyclic` :
    `dim_K K[X]/(μ_T) = dim_K V`, transporting the Frobenius equality through
    the isomorphism.

  ## Proof sketch

  1. `μ_T ∣ χ_T` (Cayley–Hamilton), both are monic, and
     `deg μ_T = dim V = deg χ_T` in the cyclic case — so `χ_T = μ_T`
     (`Polynomial.eq_of_monic_of_dvd_of_natDegree_le`).
  2. `ker (aeval T) = (μ_T)` (`minpoly.ker_aeval_eq_span_minpoly`), so the
     first isomorphism theorem (`Ideal.quotientKerAlgEquivOfSurjective` on
     `(aeval T).rangeRestrict`) gives `K[X]/(μ_T) ≃ₐ[K] (aeval T).range`.
  3. `(aeval T).range = adjoin K {T} = centralizer K {T}` — the second
     equality is the commutant characterization `end_centralizer_eq_adjoin`
     from the base file, the only step that uses the cyclic vector.

  Together with the existing files this completes the algebraic picture:
  the commutant of a cyclic endomorphism is the commutative `K`-algebra
  `K[X]/(χ_T)` of dimension `dim V`, with underlying `K`-vector space
  canonically identified with `V` (evaluation at the cyclic vector).

  Status: 0 sorries, 0 axioms.
-/
import Mathlib
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ02OQ03
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ02OQ03Frobenius

noncomputable section

namespace EndCyclicCommutant

open Polynomial Module

variable {K : Type*} [Field K] {V : Type*} [AddCommGroup V] [Module K V]

-- ============================================================
-- SECTION I: a cyclic endomorphism is nonderogatory — χ_T = μ_T
-- ============================================================

/-- **Nonderogatory equality.**  If `T : Module.End K V` (over a
    finite-dimensional `V`) has a cyclic vector, its characteristic polynomial
    *equals* its minimal polynomial:

        `χ_T = μ_T`.

    Sharpens the degree identity `minpoly_natDegree_eq_finrank_of_cyclic`
    (`deg μ_T = dim V`): `μ_T` divides `χ_T` by Cayley–Hamilton, both are
    monic, and their degrees agree, so they coincide. -/
theorem end_charpoly_eq_minpoly_of_cyclic [FiniteDimensional K V]
    (T : Module.End K V) (v : V) (hcyc : IsEndCyclicVector T v) :
    T.charpoly = minpoly K T := by
  have hint : IsIntegral K T := LinearMap.isIntegral T
  refine Polynomial.eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hint)
    T.charpoly_monic (minpoly.dvd K T (LinearMap.aeval_self_charpoly T)) ?_
  have h1 : T.charpoly.natDegree = finrank K V := T.charpoly_natDegree
  have h2 : (minpoly K T).natDegree = finrank K V :=
    minpoly_natDegree_eq_finrank_of_cyclic T v hcyc
  exact le_of_eq (h1.trans h2.symm)

-- ============================================================
-- SECTION II: the kernel of evaluation at T is (μ_T)
-- ============================================================

/-- The annihilator ideal of `T` in `K[X]` is generated by the minimal
    polynomial, stated for the range-restricted evaluation map: this is the
    kernel identification feeding the first isomorphism theorem below. -/
theorem span_minpoly_eq_ker_rangeRestrict (T : Module.End K V) :
    Ideal.span {minpoly K T} = RingHom.ker ((aeval T).rangeRestrict) := by
  rw [AlgHom.ker_rangeRestrict, minpoly.ker_aeval_eq_span_minpoly,
    Ideal.submodule_span_eq]

-- ============================================================
-- SECTION III: the commutant is K[X]/(μ_T) as a K-algebra
-- ============================================================

/-- **The commutant of a cyclic endomorphism is `K[X]/(μ_T)`.**  If
    `T : Module.End K V` has a cyclic vector, then evaluation `p ↦ p(T)`
    induces a `K`-algebra isomorphism

        `K[X] ⧸ (minpoly K T)  ≃ₐ[K]  centralizer K {T}`.

    This is the algebra-level upgrade of the linear evaluation isomorphism
    `centralizerEvalEquiv : C(T) ≃ₗ[K] V`: the commutant is not merely
    `dim V`-dimensional, it is the polynomial quotient algebra on `μ_T = χ_T`.
    Composite of the first isomorphism theorem for `aeval T` with the
    commutant characterization `end_centralizer_eq_adjoin` (the only step
    using the cyclic vector). -/
def centralizerQuotientAlgEquiv [FiniteDimensional K V]
    (T : Module.End K V) (v : V) (hcyc : IsEndCyclicVector T v) :
    (K[X] ⧸ Ideal.span {minpoly K T}) ≃ₐ[K]
      Subalgebra.centralizer K ({T} : Set (Module.End K V)) :=
  ((Ideal.quotientEquivAlgOfEq K (span_minpoly_eq_ker_rangeRestrict T)).trans
    (Ideal.quotientKerAlgEquivOfSurjective
      (AlgHom.rangeRestrict_surjective (aeval T)))).trans
    (Subalgebra.equivOfEq _ _ (by
      rw [← Algebra.adjoin_singleton_eq_range_aeval,
        end_centralizer_eq_adjoin T v hcyc]))

/-- The isomorphism `centralizerQuotientAlgEquiv` is induced by evaluation:
    the class of `p` is sent to the operator `p(T)` (as an element of
    `Module.End K V`, after coercion out of the centralizer subalgebra). -/
@[simp] theorem centralizerQuotientAlgEquiv_mk_coe [FiniteDimensional K V]
    (T : Module.End K V) (v : V) (hcyc : IsEndCyclicVector T v) (p : K[X]) :
    (centralizerQuotientAlgEquiv T v hcyc
        (Ideal.Quotient.mk (Ideal.span {minpoly K T}) p) : Module.End K V)
      = aeval T p := by
  simp [centralizerQuotientAlgEquiv, Ideal.quotientEquivAlgOfEq_mk,
    Ideal.quotientKerAlgEquivOfSurjective_mk]

-- ============================================================
-- SECTION IV: dimension of the quotient — transport of Frobenius equality
-- ============================================================

/-- The polynomial quotient on the minimal polynomial of a cyclic
    endomorphism has `K`-dimension `dim_K V` — the Frobenius equality
    `dim C(T) = dim V` transported through `centralizerQuotientAlgEquiv`. -/
theorem finrank_quotient_span_minpoly_of_cyclic [FiniteDimensional K V]
    (T : Module.End K V) (v : V) (hcyc : IsEndCyclicVector T v) :
    finrank K (K[X] ⧸ Ideal.span {minpoly K T}) = finrank K V := by
  rw [(centralizerQuotientAlgEquiv T v hcyc).toLinearEquiv.finrank_eq]
  exact finrank_centralizer_eq_of_cyclic T v hcyc

end EndCyclicCommutant

end
