/-
  Closing the Triple Equivalence: Centralizer = K[M] ⟹ Cyclic Vector
  (cayley-hamilton-cyclic-vector-all-fields-oq-02-oq-01)

  The classical theory of a single endomorphism / square matrix `M` over a field
  `K` rests on a triple equivalence (Hoffman & Kunze §7.5, Roman §10.4):

      (i)   `M` admits a cyclic vector
      (ii)  `M` is nonderogatory  (minpoly `M` = charpoly `M`)
      (iii) the centralizer `C(M) = {N : NM = MN}` equals `K[M]`
            (every matrix commuting with `M` is a polynomial in `M`).

  The sibling file `CayleyHamiltonCyclicVectorAllFieldsOQ02.lean` proves the
  forward edge **(i) ⟹ (iii)** (`commuting_matrix_is_polynomial`); the parent
  biconditional `nonderogatory_iff_has_cyclic_vector` gives **(i) ⟺ (ii)**.

  This file supplies the remaining **converse edge (iii) ⟹ (ii)** (hence
  ⟹ (i)), closing the triangle.

  ## Proof

  Both `K[M] = Algebra.adjoin K {M}` and the centralizer
  `C(M) = Subalgebra.centralizer K {M}` are `K`-subalgebras of the matrix
  algebra, hence finite-dimensional `K`-vector spaces.  Three facts combine:

    * **dim K[M] = deg(minpoly M).**  `M` is integral over `K`, so the power
      basis `{1, M, …, M^{d-1}}` (with `d = deg minpoly`) is a `K`-basis of
      `K[M]` (`Algebra.adjoin.powerBasis'`).  Thus
      `finrank K K[M] = (minpoly K M).natDegree`.

    * **dim C(M) ≥ n.**  The Frobenius bound on the dimension of the
      commutant.  (Isolated below as `finrank_centralizer_ge`.)

    * **deg(minpoly M) ≤ n.**  `minpoly K M ∣ charpoly M` (Cayley–Hamilton),
      and `charpoly` has degree `n`.

  If `C(M) = K[M]` then `finrank K C(M) = finrank K K[M] = deg(minpoly)`, so

      n ≤ finrank K C(M) = deg(minpoly M) ≤ n,

  forcing `deg(minpoly M) = n`.  Two monic polynomials of equal degree, one
  dividing the other, are equal, so `minpoly K M = charpoly M`, i.e. `M` is
  nonderogatory (ii).  The parent biconditional then yields a cyclic vector (i).

  ## Status

  The reduction is fully machine-checked.  The single structural input
  `finrank_centralizer_ge` (the Frobenius dimension bound `dim C(M) ≥ n`, whose
  standard proof passes through the rational canonical form / invariant-factor
  decomposition of `M`) is **isolated as one `sorry`** and is not yet available
  in Mathlib v4.26.0.  Everything else — the dimension bookkeeping, the
  degree equality, and the descent to a cyclic vector — is complete and
  axiom-free.
-/
import Mathlib
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ01OQ01
import Proofs.CayleyHamiltonCyclicVectorAllFieldsOQ02

noncomputable section

namespace CyclicCommutantConverse

open Matrix Polynomial

variable {K : Type*} [Field K] {n : ℕ}

-- ============================================================
-- SECTION I: dim K[M] = deg(minpoly M)
-- ============================================================

/-- The algebra `K[M] = Algebra.adjoin K {M}` of polynomials in `M` has
    `K`-dimension equal to the degree of the minimal polynomial of `M`.

    Since the matrix algebra is noncommutative, the `PowerBasis` API for
    `adjoin` does not apply directly; instead we use the first isomorphism
    theorem.  `K[M]` is the range of `aeval M : K[X] →ₐ[K] Matrix`, and the
    kernel of `aeval M` is the ideal generated by `minpoly K M`, so

      K[M] ≃ₐ[K] K[X] ⧸ (minpoly K M),

    whose `K`-dimension is `(minpoly K M).natDegree`. -/
theorem finrank_adjoin_eq_natDegree_minpoly
    (M : Matrix (Fin n) (Fin n) K) :
    Module.finrank K ↥(Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K)))
      = (minpoly K M).natDegree := by
  have hrange : Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K))
      = (Polynomial.aeval M : K[X] →ₐ[K] Matrix (Fin n) (Fin n) K).range :=
    Algebra.adjoin_singleton_eq_range_aeval K M
  have hker : RingHom.ker (Polynomial.aeval M : K[X] →ₐ[K] Matrix (Fin n) (Fin n) K)
      = Ideal.span {minpoly K M} := minpoly.ker_aeval_eq_span_minpoly K M
  -- K[M] = range(aeval M) ≃ₐ K[X]/ker(aeval M) = K[X]/(minpoly).
  have e : ↥(Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K)))
      ≃ₐ[K] (K[X] ⧸ Ideal.span {minpoly K M}) :=
    (Subalgebra.equivOfEq _ _ hrange).trans
      ((Ideal.quotientKerEquivRange
          (Polynomial.aeval M : K[X] →ₐ[K] Matrix (Fin n) (Fin n) K)).symm.trans
        (Ideal.quotientEquivAlgOfEq K hker))
  rw [LinearEquiv.finrank_eq e.toLinearEquiv]
  exact finrank_quotient_span_eq_natDegree

-- ============================================================
-- SECTION II: The Frobenius dimension bound (ISOLATED CRUX)
-- ============================================================

/-- **Frobenius dimension bound (isolated crux).** The centralizer
    `C(M) = {N : NM = MN}` of an `n × n` matrix has `K`-dimension at least `n`.

    This is the only ingredient of the converse edge not yet in Mathlib: the
    standard proof factors `K^n` as a `K[X]`-module into its invariant factors
    `K[X]/(f_1) ⊕ ⋯ ⊕ K[X]/(f_k)` (rational canonical form) and observes that
    the block-diagonal scalar multiplications already span an `n`-dimensional
    subspace of the commutant (`dim C(M) = Σ_{i,j} deg gcd(f_i, f_j) ≥ Σ deg f_i
    = n`).  Equality holds iff `M` is nonderogatory.

    Mathlib v4.26.0 provides the primary-decomposition structure theorem
    (`Module.equiv_directSum_of_isTorsion`) but not the invariant-factor /
    rational-canonical-form packaging needed here, so this is left as a single
    documented `sorry`. -/
theorem finrank_centralizer_ge
    (M : Matrix (Fin n) (Fin n) K) :
    Fintype.card (Fin n)
      ≤ Module.finrank K ↥(Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))) := by
  sorry

-- ============================================================
-- SECTION III: deg(minpoly M) ≤ n
-- ============================================================

/-- The minimal polynomial of an `n × n` matrix has degree at most `n`
    (it divides the degree-`n` characteristic polynomial). -/
theorem natDegree_minpoly_le
    (M : Matrix (Fin n) (Fin n) K) :
    (minpoly K M).natDegree ≤ Fintype.card (Fin n) := by
  have hdvd : minpoly K M ∣ M.charpoly := minpoly.dvd K M (Matrix.aeval_self_charpoly M)
  have hch : M.charpoly ≠ 0 := M.charpoly_monic.ne_zero
  calc (minpoly K M).natDegree
      ≤ M.charpoly.natDegree := Polynomial.natDegree_le_of_dvd hdvd hch
    _ = Fintype.card (Fin n) := M.charpoly_natDegree_eq_dim

-- ============================================================
-- SECTION IV: Main theorem — (iii) ⟹ (ii) ⟹ (i)
-- ============================================================

/-- **Converse edge of the triple equivalence (iii) ⟹ (ii).**  If the
    centralizer of `M` coincides with the algebra `K[M]` of polynomials in `M`,
    then `M` is nonderogatory: `minpoly K M = charpoly M`.

    Together with the forward edge `commuting_matrix_is_polynomial`
    (cyclic ⟹ centralizer = K[M]) and the parent biconditional
    (nonderogatory ⟺ cyclic), this closes the triple equivalence

      cyclic vector ⟺ minpoly = charpoly ⟺ centralizer = K[M]. -/
theorem centralizer_eq_adjoin_implies_nonderogatory
    (M : Matrix (Fin n) (Fin n) K)
    (h : Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))
          = Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K))) :
    minpoly K M = M.charpoly := by
  have hM : IsIntegral K M := IsIntegral.of_finite K M
  -- finrank C(M) = finrank K[M] = deg(minpoly).
  have hcentr_adj :
      Module.finrank K ↥(Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K)))
        = (minpoly K M).natDegree := by
    rw [h, finrank_adjoin_eq_natDegree_minpoly M]
  -- n ≤ deg(minpoly) ≤ n, forcing equality.
  have hge : Fintype.card (Fin n) ≤ (minpoly K M).natDegree := by
    rw [← hcentr_adj]; exact finrank_centralizer_ge M
  have hle : (minpoly K M).natDegree ≤ Fintype.card (Fin n) := natDegree_minpoly_le M
  -- deg(charpoly) = n = deg(minpoly), so charpoly.natDegree ≤ minpoly.natDegree.
  have hdeg : M.charpoly.natDegree ≤ (minpoly K M).natDegree := by
    rw [M.charpoly_natDegree_eq_dim]; omega
  -- Two monic polynomials, one dividing the other with no larger degree, are equal.
  have hdvd : minpoly K M ∣ M.charpoly := minpoly.dvd K M (Matrix.aeval_self_charpoly M)
  have hmin_monic : (minpoly K M).Monic := minpoly.monic hM
  exact (Polynomial.eq_of_monic_of_dvd_of_natDegree_le hmin_monic M.charpoly_monic hdvd hdeg).symm

/-- **Capstone: the converse edge (iii) ⟹ (i).**  If the centralizer of `M`
    equals `K[M]`, then `M` admits a cyclic vector.  This is the edge that
    closes the triple equivalence (combined with the forward edge
    `commuting_matrix_is_polynomial` and the parent biconditional). -/
theorem centralizer_eq_adjoin_implies_cyclic
    (M : Matrix (Fin n) (Fin n) K)
    (h : Subalgebra.centralizer K ({M} : Set (Matrix (Fin n) (Fin n) K))
          = Algebra.adjoin K ({M} : Set (Matrix (Fin n) (Fin n) K))) :
    ∃ v, GeneralCyclicVector.IsCyclicVector M v :=
  (CyclicVectorBiconditional.nonderogatory_iff_has_cyclic_vector M).mp
    (centralizer_eq_adjoin_implies_nonderogatory M h)

end CyclicCommutantConverse

end
