/-
  Nonderogatory Operators via Module Theory (Infinite-Dimensional Extension)

  Extends the nonderogatory → cyclic vector theory from finite-dimensional
  matrices (CayleyHamiltonMinpolyOQ05OQ01.lean) to arbitrary K-modules.

  KEY INSIGHT: A linear endomorphism T on V makes V into a K[X]-module
  (via p · v = p(T)v). T is "nonderogatory" exactly when V is cyclic as
  a K[X]-module, i.e., generated by a single element.

  This connects to the structure theorem for modules over PIDs:
  if V is finitely generated as K[X]-module, the invariant factor
  decomposition V ≅ K[X]/(d₁) ⊕ ... ⊕ K[X]/(dₖ) has k = 1 iff T is
  nonderogatory. For infinite-dimensional V, the cyclic subspace framework
  still applies with the annihilator ideal replacing the minimal polynomial.

  Results:
  I.   cyclicSubspace T v is T-invariant and p(T)-invariant for all p
  II.  cyclicSubspace T v = range of the polynomial action map p ↦ p(T)v
  III. For cyclic vectors: p(T)v = 0 ⟺ p(T) = 0 (annihilator = kernel)
  IV.  Annihilator of cyclic vector = ideal generated by minimal polynomial
  V.   Infinite-dimensional example: K[X] with multiplication by X
-/
import Mathlib

noncomputable section

namespace NonderogatoryModule

open Polynomial

variable {K : Type*} [Field K]
variable {V : Type*} [AddCommGroup V] [Module K V]

-- ============================================================
-- SECTION I: Definitions
-- ============================================================

/-- The cyclic subspace: K-span of {v, Tv, T²v, ...}.
    Works for arbitrary modules, not just finite-dimensional spaces. -/
def cyclicSubspace (T : Module.End K V) (v : V) : Submodule K V :=
  Submodule.span K (Set.range fun n : ℕ => (T ^ n) v)

/-- v is a cyclic vector for T if its cyclic subspace is all of V. -/
def IsCyclicVectorOp (T : Module.End K V) (v : V) : Prop :=
  cyclicSubspace T v = ⊤

/-- T is nonderogatory if V has a cyclic vector. Generalizes the matrix
    definition (minpoly = charpoly) to arbitrary modules. -/
def IsNonderogatoryOp (T : Module.End K V) : Prop :=
  ∃ v : V, IsCyclicVectorOp T v

/-- The polynomial evaluation map at v: sends p to p(T)v. -/
def polynomialAction (T : Module.End K V) (v : V) : K[X] →ₗ[K] V where
  toFun p := (aeval T p) v
  map_add' p q := by
    show (aeval T (p + q)) v = (aeval T p) v + (aeval T q) v
    rw [map_add, LinearMap.add_apply]
  map_smul' c p := by
    simp only [RingHom.id_apply]
    show (aeval T (c • p)) v = c • ((aeval T p) v)
    conv_lhs => rw [Algebra.smul_def, map_mul, AlgHom.commutes, ← Algebra.smul_def]
    exact LinearMap.smul_apply c (aeval T p) v

@[simp]
theorem polynomialAction_apply (T : Module.End K V) (v : V) (p : K[X]) :
    polynomialAction T v p = (aeval T p) v := rfl

/-- The annihilator ideal: {p ∈ K[X] | p(T)v = 0}. This is a two-sided
    ideal because K[X] is commutative. -/
def annihilatorIdeal (T : Module.End K V) (v : V) : Ideal K[X] where
  carrier := {p : K[X] | (aeval T p) v = 0}
  add_mem' {a b} ha hb := by
    show (aeval T (a + b)) v = 0
    rw [map_add, LinearMap.add_apply, ha, hb, add_zero]
  zero_mem' := by show (aeval T 0) v = 0; simp
  smul_mem' q {p} hp := by
    show (aeval T (q * p)) v = 0
    rw [map_mul, LinearMap.mul_apply, hp, map_zero]

-- ============================================================
-- SECTION II: Basic Properties of Cyclic Subspaces
-- ============================================================

theorem mem_cyclicSubspace (T : Module.End K V) (v : V) :
    v ∈ cyclicSubspace T v :=
  Submodule.subset_span ⟨0, by simp⟩

theorem pow_mem_cyclicSubspace (T : Module.End K V) (v : V) (n : ℕ) :
    (T ^ n) v ∈ cyclicSubspace T v :=
  Submodule.subset_span ⟨n, rfl⟩

/-- The cyclic subspace is T-invariant. -/
theorem T_mem_cyclicSubspace (T : Module.End K V) (v : V)
    {w : V} (hw : w ∈ cyclicSubspace T v) : T w ∈ cyclicSubspace T v := by
  refine Submodule.span_induction hw ?_ ?_ ?_ ?_
  · rintro _ ⟨n, rfl⟩
    have : T ((T ^ n) v) = (T ^ (n + 1)) v := by
      rw [pow_succ', LinearMap.mul_apply]
    rw [this]
    exact pow_mem_cyclicSubspace T v (n + 1)
  · exact Submodule.zero_mem _
  · intro x y hx hy; rw [map_add]; exact Submodule.add_mem _ hx hy
  · intro c x hx; rw [map_smul]; exact Submodule.smul_mem _ c hx

/-- The cyclic subspace is invariant under p(T) for any polynomial p.
    Key strengthening of T-invariance, proved by polynomial induction. -/
theorem aeval_mem_cyclicSubspace (T : Module.End K V) (v : V) (p : K[X]) :
    ∀ {w : V}, w ∈ cyclicSubspace T v → (aeval T p) w ∈ cyclicSubspace T v := by
  induction p using Polynomial.induction_on with
  | h_C c =>
    intro w hw
    simp only [aeval_C, Algebra.algebraMap_eq_smul_one,
               LinearMap.smul_apply, LinearMap.one_apply]
    exact Submodule.smul_mem _ c hw
  | h_add p q hp hq =>
    intro w hw
    simp only [map_add, LinearMap.add_apply]
    exact Submodule.add_mem _ (hp hw) (hq hw)
  | h_X p hp =>
    intro w hw
    rw [map_mul, aeval_X, LinearMap.mul_apply]
    exact hp (T_mem_cyclicSubspace T v hw)

-- ============================================================
-- SECTION III: Polynomial Action Characterization
-- ============================================================

theorem polynomialAction_X_pow (T : Module.End K V) (v : V) (n : ℕ) :
    polynomialAction T v (X ^ n) = (T ^ n) v := by
  simp [aeval_X_pow]

/-- The cyclic subspace equals the range of the polynomial action map. -/
theorem cyclicSubspace_eq_range (T : Module.End K V) (v : V) :
    cyclicSubspace T v = LinearMap.range (polynomialAction T v) := by
  apply le_antisymm
  · -- Every T^n v is in the range (via X^n)
    rw [Submodule.span_le]
    rintro _ ⟨n, rfl⟩
    exact ⟨X ^ n, polynomialAction_X_pow T v n⟩
  · -- Every p(T)v is in the cyclic subspace
    rintro _ ⟨p, rfl⟩
    exact aeval_mem_cyclicSubspace T v p (mem_cyclicSubspace T v)

/-- v is cyclic iff the polynomial action is surjective. -/
theorem isCyclicVectorOp_iff_surjective (T : Module.End K V) (v : V) :
    IsCyclicVectorOp T v ↔ Function.Surjective (polynomialAction T v) := by
  rw [IsCyclicVectorOp, cyclicSubspace_eq_range, LinearMap.range_eq_top]

-- ============================================================
-- SECTION IV: Annihilator Structure for Cyclic Vectors
-- ============================================================

theorem mem_annihilatorIdeal_iff (T : Module.End K V) (v : V) (p : K[X]) :
    p ∈ annihilatorIdeal T v ↔ (aeval T p) v = 0 :=
  Iff.rfl

/-- The minimal polynomial of T is in the annihilator of every vector. -/
theorem minpoly_mem_annihilator (T : Module.End K V) (v : V)
    (hT : IsIntegral K T) : minpoly K T ∈ annihilatorIdeal T v := by
  rw [mem_annihilatorIdeal_iff]
  show (aeval T (minpoly K T)) v = 0
  rw [minpoly.aeval, LinearMap.zero_apply]

/-- For a cyclic vector, pointwise annihilation implies global annihilation.
    The annihilator of a cyclic vector equals the annihilator of the
    entire operator, because K[X] is commutative. -/
theorem aeval_eq_zero_of_cyclic (T : Module.End K V) (v : V)
    (hv : IsCyclicVectorOp T v) (p : K[X])
    (hp : (aeval T p) v = 0) : aeval T p = 0 := by
  ext w
  show (aeval T p) w = 0
  have hw : w ∈ cyclicSubspace T v := hv ▸ Submodule.mem_top
  rw [cyclicSubspace_eq_range] at hw
  obtain ⟨q, rfl⟩ := hw
  -- p(T)(q(T)v) = q(T)(p(T)v) = q(T)0 = 0 by commutativity of K[X]
  have h_comm : (aeval T p) ((aeval T q) v) = (aeval T q) ((aeval T p) v) := by
    change (aeval T p * aeval T q) v = (aeval T q * aeval T p) v
    congr 1
    rw [← map_mul, ← map_mul, mul_comm]
  rw [h_comm, hp, map_zero]

/-- For a cyclic vector, the annihilator ideal characterizes when p(T) = 0. -/
theorem annihilator_cyclic_iff (T : Module.End K V) (v : V)
    (hv : IsCyclicVectorOp T v) (p : K[X]) :
    p ∈ annihilatorIdeal T v ↔ aeval T p = 0 :=
  ⟨aeval_eq_zero_of_cyclic T v hv p, fun h => by
    rw [mem_annihilatorIdeal_iff, h, LinearMap.zero_apply]⟩

/-- For an integral operator with a cyclic vector, the annihilator ideal
    is generated by the minimal polynomial. -/
theorem annihilator_cyclic_eq_span_minpoly (T : Module.End K V) (v : V)
    (hv : IsCyclicVectorOp T v) (hT : IsIntegral K T) :
    annihilatorIdeal T v = Ideal.span {minpoly K T} := by
  ext p
  rw [Ideal.mem_span_singleton]
  constructor
  · -- If p(T)v = 0, then p(T) = 0, so minpoly divides p
    intro hp
    exact minpoly.dvd K T (aeval_eq_zero_of_cyclic T v hv p hp)
  · -- If minpoly divides p, then p(T) = 0, so p(T)v = 0
    rintro ⟨q, rfl⟩
    rw [mem_annihilatorIdeal_iff, map_mul, LinearMap.mul_apply,
        minpoly.aeval, LinearMap.zero_apply, map_zero]

-- ============================================================
-- SECTION V: Infinite-Dimensional Example
-- ============================================================

section InfDimExample

variable (K)

/-- Multiplication by X as a K-linear endomorphism of K[X].
    The canonical nonderogatory operator on an infinite-dimensional space. -/
def mulByX : Module.End K K[X] where
  toFun p := (X : K[X]) * p
  map_add' p q := mul_add X p q
  map_smul' c p := by
    simp only [RingHom.id_apply]
    show (X : K[X]) * (c • p) = c • ((X : K[X]) * p)
    rw [Algebra.mul_smul_comm]

/-- The polynomial action of mulByX is multiplication: p(mulByX)(q) = p * q. -/
theorem aeval_mulByX_eq_mul (p : K[X]) :
    ∀ q : K[X], ((aeval (mulByX K) p) : Module.End K K[X]) q = p * q := by
  induction p using Polynomial.induction_on with
  | h_C c =>
    intro q
    simp only [aeval_C, Algebra.algebraMap_eq_smul_one, LinearMap.smul_apply,
               LinearMap.one_apply, C_mul']
  | h_add p₁ p₂ hp₁ hp₂ =>
    intro q
    rw [map_add, LinearMap.add_apply, hp₁, hp₂, add_mul]
  | h_X p hp =>
    intro q
    rw [map_mul, aeval_X, LinearMap.mul_apply, hp ((mulByX K) q)]
    change p * ((X : K[X]) * q) = p * (X : K[X]) * q
    ring

/-- Evaluating any polynomial p at mulByX on the identity gives p back. -/
theorem aeval_mulByX_one (p : K[X]) :
    ((aeval (mulByX K) p) : Module.End K K[X]) (1 : K[X]) = p := by
  rw [aeval_mulByX_eq_mul, mul_one]

/-- 1 is a cyclic vector for mulByX on K[X]. This demonstrates
    nonderogatory operators on infinite-dimensional spaces. -/
theorem one_isCyclicVector_mulByX :
    IsCyclicVectorOp (mulByX K) (1 : K[X]) := by
  rw [isCyclicVectorOp_iff_surjective]
  intro p
  exact ⟨p, by simp [aeval_mulByX_one K p]⟩

/-- mulByX is nonderogatory on K[X]. -/
theorem isNonderogatoryOp_mulByX : IsNonderogatoryOp (mulByX K) :=
  ⟨1, one_isCyclicVector_mulByX K⟩

/-- The annihilator of 1 under mulByX is trivial.
    No nonzero polynomial annihilates the identity element, showing that
    infinite-dimensional nonderogatory operators need not have a minimal
    polynomial (the annihilator ideal can be zero). -/
theorem annihilator_mulByX_one_eq_bot :
    annihilatorIdeal (mulByX K) (1 : K[X]) = ⊥ := by
  ext p
  simp only [Ideal.mem_bot, mem_annihilatorIdeal_iff]
  constructor
  · intro hp; rwa [aeval_mulByX_one] at hp
  · intro hp; rw [hp, map_zero, LinearMap.zero_apply]

end InfDimExample

end NonderogatoryModule

end
