import Proofs.CramersRuleOQ05
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Tactic

/-
# Similarity is an Equivalence Relation, Preserved by Polynomial Evaluation (cramers-rule-oq-05-oq-02)

The parent entry (`cramers-rule-oq-05`) introduced conjugation `conj U N = U N U⁻¹`
by a unit matrix and the textbook similarity relation

    IsSimilar M N  :=  ∃ U, N = conj U M

and proved that similar matrices share their determinant, trace, and
characteristic polynomial.  It stopped short of two structural facts that make
similarity the *right* notion of "same operator in a different basis":

  1. **`IsSimilar` is an equivalence relation.**  The parent proved only
     reflexivity.  Here we add symmetry and transitivity and bundle the three
     into `Equivalence`/`Setoid` instances.

  2. **Similarity is preserved by polynomial evaluation.**  If `M ~ N` then for
     every polynomial `p ∈ R[X]` we have `p(M) ~ p(N)`.  The conceptual reason is
     that conjugation by a fixed unit is an *`R`-algebra homomorphism* of the
     matrix ring, and `Polynomial.aeval` is natural with respect to algebra
     homomorphisms (`Polynomial.aeval_algHom_apply`).  We make the algebra
     homomorphism `conjAlgHom U` explicit and read the result off it.

Together these say: matrix similarity is a congruence for the entire polynomial
functional calculus.  As a capstone we combine (2) with the parent's
characteristic-polynomial invariance to conclude that `p(M)` and `p(N)` have
equal characteristic polynomials for *every* `p` — a strong basis-independence
statement for the whole `R[X]`-module generated by a similarity class.

Everything is over an arbitrary commutative ring `R`.

Status: 0 axioms, 0 sorries
-/

namespace CramersRuleOQ05OQ02

open Matrix Polynomial BigOperators
open CramersRuleOQ05 (conj conj_apply IsSimilar)

variable {n : Type*} [DecidableEq n] [Fintype n]
variable {R : Type*} [CommRing R]

-- ============================================================================
-- Part I: Algebraic laws of conjugation by a unit
-- ============================================================================

/-- Conjugation preserves products: `U (a*b) U⁻¹ = (U a U⁻¹)(U b U⁻¹)`.  The
inner `U⁻¹ U = 1` cancels, which is exactly where invertibility of `U` is used. -/
theorem conj_mul (U : (Matrix n n R)ˣ) (a b : Matrix n n R) :
    conj U (a * b) = conj U a * conj U b := by
  simp only [conj_apply]
  calc ↑U * (a * b) * ↑U⁻¹
      = ↑U * a * (↑U⁻¹ * ↑U) * b * ↑U⁻¹ := by rw [Units.inv_mul]; noncomm_ring
    _ = (↑U * a * ↑U⁻¹) * (↑U * b * ↑U⁻¹) := by noncomm_ring

/-- Conjugation preserves the identity: `U 1 U⁻¹ = 1`. -/
theorem conj_one (U : (Matrix n n R)ˣ) : conj U (1 : Matrix n n R) = 1 := by
  simp only [conj_apply, mul_one, Units.mul_inv]

/-- Conjugation preserves sums: `U (a+b) U⁻¹ = U a U⁻¹ + U b U⁻¹`. -/
theorem conj_add (U : (Matrix n n R)ˣ) (a b : Matrix n n R) :
    conj U (a + b) = conj U a + conj U b := by
  simp only [conj_apply, mul_add, add_mul]

/-- Conjugation fixes the zero matrix. -/
theorem conj_zero (U : (Matrix n n R)ˣ) : conj U (0 : Matrix n n R) = 0 := by
  simp only [conj_apply, mul_zero, zero_mul]

/-- Conjugation fixes scalar (central) matrices: `U (r • 1) U⁻¹ = r • 1`. -/
theorem conj_algebraMap (U : (Matrix n n R)ˣ) (r : R) :
    conj U (algebraMap R (Matrix n n R) r) = algebraMap R (Matrix n n R) r := by
  simp only [conj_apply]
  rw [mul_assoc, Algebra.commutes, ← mul_assoc, Units.mul_inv, one_mul]

/-- **Conjugation by a unit is an `R`-algebra homomorphism** of the matrix ring.
Packaging the five preservation laws above turns `conj U` into a first-class
morphism, which is what lets `Polynomial.aeval` see through it. -/
def conjAlgHom (U : (Matrix n n R)ˣ) : Matrix n n R →ₐ[R] Matrix n n R where
  toFun := conj U
  map_one' := conj_one U
  map_mul' := conj_mul U
  map_zero' := conj_zero U
  map_add' := conj_add U
  commutes' := conj_algebraMap U

@[simp]
theorem conjAlgHom_apply (U : (Matrix n n R)ˣ) (N : Matrix n n R) :
    conjAlgHom U N = conj U N := rfl

-- ============================================================================
-- Part II: Cancellation and the group law of conjugation
-- ============================================================================

/-- Conjugating by `U` and then by `U⁻¹` returns the original matrix. -/
@[simp]
theorem conj_inv_conj (U : (Matrix n n R)ˣ) (N : Matrix n n R) :
    conj U⁻¹ (conj U N) = N := by
  simp only [conj_apply, inv_inv, mul_assoc]
  rw [Units.inv_mul, mul_one, ← mul_assoc, Units.inv_mul, one_mul]

/-- Nested conjugations compose along the product of units:
`V (U N U⁻¹) V⁻¹ = (VU) N (VU)⁻¹`. -/
theorem conj_conj (U V : (Matrix n n R)ˣ) (N : Matrix n n R) :
    conj V (conj U N) = conj (V * U) N := by
  simp only [conj_apply, _root_.mul_inv_rev, Units.val_mul, mul_assoc]

-- ============================================================================
-- Part III: Similarity is an equivalence relation
-- ============================================================================

/-- **Similarity is symmetric.**  If `N = U M U⁻¹` then `M = U⁻¹ N U`. -/
theorem IsSimilar.symm {M N : Matrix n n R} (h : IsSimilar M N) : IsSimilar N M := by
  obtain ⟨U, rfl⟩ := h
  exact ⟨U⁻¹, (conj_inv_conj U M).symm⟩

/-- **Similarity is transitive.**  Conjugations compose: `U` then `V` is `VU`. -/
theorem IsSimilar.trans {M N P : Matrix n n R}
    (h₁ : IsSimilar M N) (h₂ : IsSimilar N P) : IsSimilar M P := by
  obtain ⟨U, rfl⟩ := h₁
  obtain ⟨V, rfl⟩ := h₂
  exact ⟨V * U, conj_conj U V M⟩

/-- **Similarity is an equivalence relation** on `Matrix n n R`. -/
theorem isSimilar_equivalence :
    Equivalence (@IsSimilar n _ _ R _) :=
  { refl := IsSimilar.refl
    symm := IsSimilar.symm
    trans := IsSimilar.trans }

/-- The similarity `Setoid`: matrices modulo change of basis. -/
def isSimilarSetoid : Setoid (Matrix n n R) :=
  ⟨IsSimilar, isSimilar_equivalence⟩

-- ============================================================================
-- Part IV: Similarity is preserved by polynomial evaluation
-- ============================================================================

/-- **Key naturality:** evaluating a polynomial commutes with conjugation,
`p(U M U⁻¹) = U p(M) U⁻¹`.  This is `Polynomial.aeval_algHom_apply` applied to the
algebra homomorphism `conjAlgHom U`. -/
theorem aeval_conj (U : (Matrix n n R)ˣ) (M : Matrix n n R) (p : R[X]) :
    aeval (conj U M) p = conj U (aeval M p) := by
  have h := Polynomial.aeval_algHom_apply (conjAlgHom U) M p
  simpa only [conjAlgHom_apply] using h

/-- **Similarity is a congruence for polynomial evaluation.**  If `M ~ N` then
`p(M) ~ p(N)` for every polynomial `p`.  Thus the whole polynomial functional
calculus descends to the quotient by similarity. -/
theorem IsSimilar.aeval {M N : Matrix n n R} (h : IsSimilar M N) (p : R[X]) :
    IsSimilar (aeval M p) (aeval N p) := by
  obtain ⟨U, rfl⟩ := h
  exact ⟨U, aeval_conj U M p⟩

-- ============================================================================
-- Part V: Capstone — equal characteristic polynomials of polynomial values
-- ============================================================================

/-- Similar matrices have equal characteristic polynomial (re-derived here from
the unit-conjugation form, matching the parent entry). -/
theorem IsSimilar.charpoly_eq {M N : Matrix n n R} (h : IsSimilar M N) :
    N.charpoly = M.charpoly := by
  obtain ⟨U, rfl⟩ := h
  exact Matrix.charpoly_units_conj U M

/-- **Capstone.**  If `M ~ N`, then for every polynomial `p` the matrices `p(M)`
and `p(N)` have the *same characteristic polynomial* — hence the same
determinant, trace, and eigenvalues.  Similarity is invariant under the entire
polynomial functional calculus, not just under the identity polynomial. -/
theorem IsSimilar.charpoly_aeval_eq {M N : Matrix n n R}
    (h : IsSimilar M N) (p : R[X]) :
    (Polynomial.aeval N p).charpoly = (Polynomial.aeval M p).charpoly :=
  IsSimilar.charpoly_eq (IsSimilar.aeval h p)

-- ============================================================================
-- Part VI: Summary
-- ============================================================================

/-
## Summary

| Result | Statement |
|--------|-----------|
| `conjAlgHom` | `conj U` is an `R`-algebra homomorphism of `Matrix n n R` |
| `IsSimilar.symm` / `.trans` | similarity is symmetric and transitive |
| `isSimilar_equivalence` / `isSimilarSetoid` | similarity is an equivalence relation |
| `aeval_conj` | `p(U M U⁻¹) = U p(M) U⁻¹` |
| `IsSimilar.aeval` | `M ~ N ⟹ p(M) ~ p(N)` for all `p` |
| `IsSimilar.charpoly_aeval_eq` | `M ~ N ⟹ charpoly (p(M)) = charpoly (p(N))` |

The parent entry showed the *classical invariants* (det, trace, charpoly) are
constant on a similarity class.  This entry shows the underlying relation is a
genuine equivalence relation and, more strongly, a **congruence for the whole
polynomial functional calculus**: applying any `p ∈ R[X]` to both members of a
similar pair yields another similar pair.  The mechanism is that conjugation by a
fixed unit is an algebra homomorphism, so `aeval` — being natural in the algebra
— commutes with it.
-/

end CramersRuleOQ05OQ02

#check @CramersRuleOQ05OQ02.conjAlgHom
#check @CramersRuleOQ05OQ02.isSimilar_equivalence
#check @CramersRuleOQ05OQ02.IsSimilar.aeval
#check @CramersRuleOQ05OQ02.IsSimilar.charpoly_aeval_eq
