import Mathlib
import Proofs.DescartesCircleTheorem

/-!
# Descartes Circle Theorem OQ-01-OQ-02: integral Apollonian curvatures

The parent `descartes-circle-theorem-oq-01` (`DescartesCircleTheorem.lean`) established the
curvature relation `(k₁+k₂+k₃+k₄)² = 2(k₁²+k₂²+k₃²+k₄²)` for four mutually tangent circles,
solved it as a quadratic in `k₄` to recover the two **Soddy curvatures**
`k₄ = (k₁+k₂+k₃) ± 2√(k₁k₂+k₂k₃+k₃k₁)`, and recorded the Vieta relations.

This leaf addresses the **integrality phenomenon** behind *integral Apollonian gaskets*: when
the curvatures of a Descartes quadruple are integers, the whole gasket generated by repeatedly
adding a tangent circle stays integral, and the existence of such an integer quadruple is
governed exactly by whether the symmetric product (the discriminant) is a perfect square.

## What this proves

Working with the integer Descartes relation
`descartesRelZ a b c d : (a+b+c+d)² = 2(a²+b²+c²+d²)`:

1. **`descartesRelZ_iff_sq`** — the quadratic-in-`d` rewriting `(d-(a+b+c))² = 4(ab+bc+ca)`.
2. **`soddyReflect`** `= 2(a+b+c) - d`, the *conjugate* Soddy curvature, and
   **`soddyReflect_involutive`** — reflecting twice returns the original.
3. **`descartesRelZ_reflect`** — the conjugate of a Descartes quadruple is again a Descartes
   quadruple. This is the gasket-generation step: the new tangent circle's curvature
   `2(a+b+c)-d` is an **integer** whenever `a,b,c,d` are, so integrality propagates.
4. **`soddy_sum_Z` / `soddy_prod_Z`** — the integer Vieta relations for the two solutions.
5. **`exists_integral_fourth_iff_sq`** (headline) — *an integer fourth curvature completing
   `a,b,c` to a Descartes quadruple exists **iff** the symmetric product `ab+bc+ca` is a
   perfect square.* This is the integrality/discriminant dictionary.
6. **`apollonian_new_curvature_isInt`** — the real-curvature phrasing of (3): if the four
   real curvatures are integers and Descartes-related, the reflected Soddy curvature is again
   an integer and gives a Descartes quadruple. Bridged to the parent's real `descartesRel`.

## How

The discriminant identity `(d-(a+b+c))² = 4(ab+bc+ca)` is the engine. For the headline
biconditional, one direction substitutes a perfect square `ab+bc+ca = m²` and takes
`d = (a+b+c)+2m`; the other uses that `4 ∣ (d-(a+b+c))²` forces `2 ∣ d-(a+b+c)` (primality
of `2`), so `ab+bc+ca` is the square of the half-difference. The reflection facts are pure
`ring`/`linear_combination` identities; the real bridge is `push_cast`.

All results are machine-checked: `0` `sorry`, `0` `axiom`, no `native_decide`.
-/

open DescartesCircleTheorem

namespace DescartesCircleIntegrality

/-- The **integer Descartes relation** among four signed curvatures. -/
def descartesRelZ (a b c d : ℤ) : Prop :=
  (a + b + c + d) ^ 2 = 2 * (a ^ 2 + b ^ 2 + c ^ 2 + d ^ 2)

/-- The Descartes relation, as a quadratic in `d`, is equivalent to the discriminant identity:
the deviation of `d` from the outer-curvature sum squares to `4` times the symmetric product. -/
theorem descartesRelZ_iff_sq (a b c d : ℤ) :
    descartesRelZ a b c d ↔ (d - (a + b + c)) ^ 2 = 4 * (a * b + b * c + c * a) := by
  unfold descartesRelZ
  constructor <;> intro h <;> linear_combination -h

/-- The **conjugate Soddy curvature**: the other root of the Descartes quadratic in `d`. -/
def soddyReflect (a b c d : ℤ) : ℤ := 2 * (a + b + c) - d

/-- Reflecting the fourth curvature twice returns the original (the two Soddy circles). -/
theorem soddyReflect_involutive (a b c d : ℤ) :
    soddyReflect a b c (soddyReflect a b c d) = d := by
  unfold soddyReflect; ring

/-- **Gasket-generation step.** The conjugate of a Descartes quadruple is again a Descartes
quadruple. Since `soddyReflect a b c d = 2(a+b+c)-d` is an integer whenever `a,b,c,d` are,
this shows integer curvatures propagate through the Apollonian gasket. -/
theorem descartesRelZ_reflect {a b c d : ℤ} (h : descartesRelZ a b c d) :
    descartesRelZ a b c (soddyReflect a b c d) := by
  unfold descartesRelZ soddyReflect at *
  linear_combination h

/-- **Vieta (sum).** The two Soddy curvatures sum to twice the outer-curvature sum. -/
theorem soddy_sum_Z (a b c d : ℤ) : d + soddyReflect a b c d = 2 * (a + b + c) := by
  unfold soddyReflect; ring

/-- **Vieta (product).** When the Descartes relation holds, the two Soddy curvatures multiply
to `(a+b+c)² - 4(ab+bc+ca)`. -/
theorem soddy_prod_Z {a b c d : ℤ} (h : descartesRelZ a b c d) :
    d * soddyReflect a b c d = (a + b + c) ^ 2 - 4 * (a * b + b * c + c * a) := by
  unfold descartesRelZ soddyReflect at *
  linear_combination h

/-- **Headline: integrality ⟺ perfect-square discriminant.** Given three integer curvatures
`a, b, c`, an integer fourth curvature `d` completing them to a Descartes quadruple exists if
and only if the symmetric product `ab+bc+ca` is a perfect square. This is the arithmetic core
of integral Apollonian gaskets: integer base curvatures occur exactly when the discriminant is
a square. -/
theorem exists_integral_fourth_iff_sq {a b c : ℤ} :
    (∃ d : ℤ, descartesRelZ a b c d) ↔ ∃ m : ℤ, a * b + b * c + c * a = m ^ 2 := by
  constructor
  · rintro ⟨d, hd⟩
    rw [descartesRelZ_iff_sq] at hd
    have hdvd : (2 : ℤ) ∣ (d - (a + b + c)) :=
      Int.prime_two.dvd_of_dvd_pow ⟨2 * (a * b + b * c + c * a), by rw [hd]; ring⟩
    obtain ⟨m, hm⟩ := hdvd
    refine ⟨m, ?_⟩
    rw [hm] at hd
    have h4 : (4 : ℤ) * (a * b + b * c + c * a) = 4 * m ^ 2 := by linear_combination -hd
    exact mul_left_cancel₀ (by norm_num : (4 : ℤ) ≠ 0) h4
  · rintro ⟨m, hm⟩
    refine ⟨(a + b + c) + 2 * m, ?_⟩
    rw [descartesRelZ_iff_sq]
    linear_combination -4 * hm

/-- The integer Descartes relation agrees with the parent's real-valued `descartesRel` under
the canonical cast `ℤ → ℝ`. -/
theorem descartesRelZ_iff_real (a b c d : ℤ) :
    descartesRelZ a b c d ↔ descartesRel (a : ℝ) (b : ℝ) (c : ℝ) (d : ℝ) := by
  unfold descartesRelZ DescartesCircleTheorem.descartesRel
  constructor <;> intro h <;> exact_mod_cast h

/-- **Apollonian integrality (real phrasing).** If four real curvatures are integers and satisfy
the Descartes relation, the reflected Soddy curvature `2(k₁+k₂+k₃)-k₄` is again an integer and
yields a Descartes quadruple — every circle added to an integral gasket has integer curvature. -/
theorem apollonian_new_curvature_isInt {k₁ k₂ k₃ k₄ : ℝ}
    (hk₁ : ∃ a : ℤ, k₁ = a) (hk₂ : ∃ b : ℤ, k₂ = b) (hk₃ : ∃ c : ℤ, k₃ = c)
    (hk₄ : ∃ d : ℤ, k₄ = d) (h : descartesRel k₁ k₂ k₃ k₄) :
    ∃ e : ℤ, 2 * (k₁ + k₂ + k₃) - k₄ = (e : ℝ) ∧
      descartesRel k₁ k₂ k₃ (2 * (k₁ + k₂ + k₃) - k₄) := by
  obtain ⟨a, rfl⟩ := hk₁
  obtain ⟨b, rfl⟩ := hk₂
  obtain ⟨c, rfl⟩ := hk₃
  obtain ⟨d, rfl⟩ := hk₄
  refine ⟨soddyReflect a b c d, ?_, ?_⟩
  · unfold soddyReflect; push_cast; ring
  · have hZ : descartesRelZ a b c (soddyReflect a b c d) :=
      descartesRelZ_reflect ((descartesRelZ_iff_real a b c d).mpr h)
    rw [descartesRelZ_iff_real] at hZ
    have hcast : ((soddyReflect a b c d : ℤ) : ℝ) = 2 * ((a : ℝ) + b + c) - d := by
      unfold soddyReflect; push_cast; ring
    rw [hcast] at hZ
    exact hZ

end DescartesCircleIntegrality
