import Mathlib
import Proofs.DissectionOfCubesOQ02

/-!
# Dissection of Cubes OQ-02 WIP-01: Tensor Product Dehn Invariant

Formalizes the proper tensor product Dehn invariant D(P) ∈ ℝ ⊗_ℚ (ℝ/πℚ)
and uses it to distinguish the cube from the regular tetrahedron.

Key results:
- D(cube) = 0 because all dihedral angles are π/2 ∈ πℚ
- D(tetrahedron) ≠ 0 because arccos(1/3) ∉ πℚ (Niven's theorem)
- Therefore the cube and regular tetrahedron are not scissors congruent
-/

namespace DissectionOfCubesOQ02WIP01

open Real DissectionOfCubesOQ02

/-- The ℚ-submodule of ℝ generated by π: the set {q·π | q : ℚ}. -/
noncomputable def piRatSpan : Submodule ℚ ℝ :=
  Submodule.span ℚ {Real.pi}

/-- Map an angle θ to its class [θ] in ℝ/πℚ. -/
noncomputable def angleClass (θ : ℝ) : ℝ ⧸ piRatSpan :=
  Submodule.mkQ piRatSpan θ

/-- A Dehn invariant element n ⊗ [θ] in ℝ ⊗_ℚ (ℝ/πℚ). -/
noncomputable def dehnElement (n : ℕ) (θ : ℝ) : TensorProduct ℚ ℝ (ℝ ⧸ piRatSpan) :=
  (n : ℚ) • ((1 : ℝ) ⊗ₜ[ℚ] angleClass θ)

/-- π/2 lies in piRatSpan since π/2 = (1/2)·π. -/
theorem pi_half_mem_piRatSpan : Real.pi / 2 ∈ piRatSpan := by
  simp only [piRatSpan, Submodule.mem_span_singleton]
  exact ⟨1/2, by
    have h : algebraMap ℚ ℝ (1/2 : ℚ) = (1/2 : ℝ) := by norm_num
    rw [Algebra.smul_def, h]; ring⟩

/-- The cube's dihedral angle π/2 has class zero in ℝ/πℚ. -/
theorem cube_angle_class_zero : angleClass (Real.pi / 2) = 0 := by
  simp only [angleClass, Submodule.mkQ_apply]
  exact (Submodule.Quotient.mk_eq_zero piRatSpan).mpr pi_half_mem_piRatSpan

/-- arccos(1/3) does not lie in piRatSpan (consequence of Niven's theorem). -/
theorem arccos_third_not_mem_piRatSpan : Real.arccos (1 / 3) ∉ piRatSpan := by
  intro hmem
  apply tetrahedron_angle_irrational_pi
  obtain ⟨q, hq⟩ := Submodule.mem_span_singleton.mp hmem
  exact ⟨q, by
    simp only [tetrahedronDihedralAngle]
    have hsmul : q • Real.pi = (q : ℝ) * Real.pi := by
      simp [Algebra.smul_def]
    linarith [hq.symm.trans hsmul]⟩

/-- The tetrahedron's dihedral angle arccos(1/3) has nonzero class in ℝ/πℚ. -/
theorem tetra_angle_class_ne_zero : angleClass (Real.arccos (1 / 3)) ≠ 0 := by
  simp only [angleClass, Submodule.mkQ_apply]
  rw [Ne, Submodule.Quotient.mk_eq_zero]
  exact arccos_third_not_mem_piRatSpan

/-- For a nonzero element m in a ℚ-module M, 1 ⊗ m ≠ 0 in ℝ ⊗_ℚ M.
    Proof: pick a ℚ-linear functional φ with φ(m) ≠ 0 (exists by Hahn-Banach for vector spaces),
    then apply id ⊗ φ and use ℝ ⊗_ℚ ℚ ≅ ℝ to conclude. -/
theorem one_tmul_ne_zero {M : Type*} [AddCommGroup M] [Module ℚ M] {m : M}
    (hm : m ≠ 0) : (1 : ℝ) ⊗ₜ[ℚ] m ≠ 0 := by
  classical
  obtain ⟨φ, hφ⟩ : ∃ (φ : M →ₗ[ℚ] ℚ), φ m ≠ 0 := by
    haveI : Module.Free ℚ M := inferInstance
    let B := Module.Free.chooseBasis ℚ M
    have hrm : B.repr m ≠ 0 :=
      fun h => hm (B.repr.injective (h.trans (map_zero _).symm))
    obtain ⟨b, hb⟩ : ∃ b, B.repr m b ≠ 0 := by
      rw [Ne, Finsupp.ext_iff] at hrm
      push_neg at hrm
      simpa using hrm
    exact ⟨B.coord b, hb⟩
  intro h
  apply hφ
  have key : (TensorProduct.rid ℚ ℝ) ((φ.lTensor ℝ) ((1 : ℝ) ⊗ₜ[ℚ] m)) = 0 := by
    rw [h, map_zero, map_zero]
  rw [LinearMap.lTensor_tmul, TensorProduct.rid_tmul] at key
  rcases smul_eq_zero.mp key with h1 | h1
  · exact h1
  · exact absurd h1 one_ne_zero

/-- The Dehn invariant of the cube is zero (12 edges, each with dihedral angle π/2). -/
theorem cube_dehn_zero : dehnElement 12 (Real.pi / 2) = 0 := by
  unfold dehnElement
  rw [cube_angle_class_zero]
  simp

/-- The Dehn invariant of the regular tetrahedron is nonzero. -/
theorem tetra_dehn_ne_zero : dehnElement 6 (Real.arccos (1 / 3)) ≠ 0 := by
  unfold dehnElement
  exact smul_ne_zero (by norm_num) (one_tmul_ne_zero tetra_angle_class_ne_zero)

/-- The Dehn invariants of the cube and regular tetrahedron differ. -/
theorem dehn_invariants_differ :
    dehnElement 12 (Real.pi / 2) ≠ dehnElement 6 (Real.arccos (1 / 3)) := by
  rw [cube_dehn_zero]
  exact Ne.symm tetra_dehn_ne_zero

end DissectionOfCubesOQ02WIP01
