/-
  # Jacobi Sum Integrality: J(χ,χ) ∈ ℤ[ζ_n] for a Character of Order n
  # (elementary-quadratic-reciprocity-oq-01-oq-01-oq-03-oq-01)

  ## The Open Question

  **OQ-01-OQ-01-OQ-03-OQ-01**: The parent entry (`...-oq-03`) established the
  Gauss–Jacobi identity g(χ)·g(φ) = J(χ,φ)·g(χφ) and the algebraic norm formula
  J(χ,φ)·J(χ⁻¹,φ⁻¹) = #F. Those identities only pin down the *magnitude* of a
  Jacobi sum. The reciprocity program additionally needs the **ring membership**:

    For a character χ of order n on 𝔽_p, the Jacobi sum J(χ,χ) is an
    *algebraic integer* in ℤ[ζ_n] (the ring generated by a primitive n-th
    root of unity), not merely a complex number of absolute value √p.

  This is the missing structural fact: together with J·J̄ = p it says J(χ,χ) is
  an element of ℤ[ζ_n] of norm p, which is exactly what factors p in the
  cyclotomic ring and drives cubic (ℤ[ω]) and quartic (ℤ[i]) reciprocity.

  ## Answer: YES — directly from Mathlib

  `Mathlib.NumberTheory.JacobiSum.Basic` (2026) contains
  `jacobiSum_mem_algebraAdjoin_of_pow_eq_one`:

    χ^n = φ^n = 1  and  μ a primitive n-th root of unity in R
      ⟹  J(χ,φ) ∈ Algebra.adjoin ℤ {μ}  ( = ℤ[μ] = ℤ[ζ_n] ).

  The proof is elementary: each summand χ(x)·φ(1−x) is a product of values of χ
  and φ, and a character value is a power of μ (or 0) when the character has
  order dividing n. Hence every summand — and therefore the whole sum — lies in
  ℤ[μ]. Mathlib also records the sharper congruence
  `exists_jacobiSum_eq_neg_one_add`: J(χ,φ) ≡ −1 (mod (μ−1)²) in ℤ[μ].

  ## What this file adds over the parent (`...-oq-03`)

  The parent file proved the *norm* J(χ,χ)·J(χ⁻¹,χ⁻¹) = p. This file proves the
  *integrality* J(χ,χ) ∈ ℤ[ζ_n], packages the order-n phrasing, specializes to
  the cubic (ℤ[ω]) and quartic (ℤ[i]) rings, exposes the (μ−1)²-congruence, and
  combines integrality with the norm into the single structural statement
  "J(χ,χ) is an algebraic integer of norm p in ℤ[ζ_n]".

  References:
  - Ireland & Rosen, "A Classical Introduction to Modern Number Theory", Ch. 8–9
  - Berndt, Evans & Williams, "Gauss and Jacobi Sums", §2
-/

import Mathlib.NumberTheory.JacobiSum.Basic
import Mathlib.NumberTheory.GaussSum
import Mathlib.Tactic

open MulChar

set_option maxHeartbeats 800000

namespace JacobiSumIntegrality

-- ============================================================================
-- Part I: Integrality of the Jacobi sum in ℤ[ζ_n]
-- ============================================================================

section Integrality

variable {F R : Type*} [Fintype F] [Field F] [CommRing R] [IsDomain R]

/-- **Jacobi sum integrality**: J(χ,φ) ∈ ℤ[μ].

    If χ and φ are multiplicative characters on a finite field F with values in
    an integral domain R, both of order dividing n (χ^n = φ^n = 1), and μ is a
    primitive n-th root of unity in R, then the Jacobi sum lies in the subring
    ℤ[μ] = Algebra.adjoin ℤ {μ}.

    Source: `jacobiSum_mem_algebraAdjoin_of_pow_eq_one` in Mathlib. -/
theorem jacobiSum_mem_cyclotomic {n : ℕ} [NeZero n] {χ φ : MulChar F R}
    (hχ : χ ^ n = 1) (hφ : φ ^ n = 1) {μ : R} (hμ : IsPrimitiveRoot μ n) :
    jacobiSum χ φ ∈ Algebra.adjoin ℤ {μ} :=
  jacobiSum_mem_algebraAdjoin_of_pow_eq_one hχ hφ hμ

/-- **Diagonal integrality**: J(χ,χ) ∈ ℤ[ζ_n] whenever χ^n = 1.

    This is the case relevant to power reciprocity: the diagonal Jacobi sum of a
    single character with itself. -/
theorem jacobiSum_self_mem_cyclotomic {n : ℕ} [NeZero n] {χ : MulChar F R}
    (hχ : χ ^ n = 1) {μ : R} (hμ : IsPrimitiveRoot μ n) :
    jacobiSum χ χ ∈ Algebra.adjoin ℤ {μ} :=
  jacobiSum_mem_algebraAdjoin_of_pow_eq_one hχ hχ hμ

/-- **Character of order n**: J(χ,χ) ∈ ℤ[ζ_n].

    Stated directly in terms of `orderOf χ = n`, which is the classical
    hypothesis "χ is a character of order n". Since χ^(orderOf χ) = 1, the
    membership follows from `jacobiSum_self_mem_cyclotomic`. -/
theorem jacobiSum_self_mem_cyclotomic_of_orderOf {n : ℕ} [NeZero n] {χ : MulChar F R}
    (hord : orderOf χ = n) {μ : R} (hμ : IsPrimitiveRoot μ n) :
    jacobiSum χ χ ∈ Algebra.adjoin ℤ {μ} := by
  apply jacobiSum_self_mem_cyclotomic _ hμ
  rw [← hord]
  exact pow_orderOf_eq_one χ

/-- **Cubic case**: J(χ,χ) ∈ ℤ[ω], the Eisenstein integers.

    For a character χ with χ³ = 1 and ω a primitive cube root of unity, the
    Jacobi sum lies in ℤ[ω]. Combined with the norm J·J̄ = p (parent entry),
    this realizes p = a² − ab + b² with J(χ,χ) = a + bω. -/
theorem cubic_jacobiSum_mem {χ : MulChar F R} (hχ : χ ^ 3 = 1)
    {ω : R} (hω : IsPrimitiveRoot ω 3) :
    jacobiSum χ χ ∈ Algebra.adjoin ℤ {ω} := by
  haveI : NeZero (3 : ℕ) := ⟨by norm_num⟩
  exact jacobiSum_self_mem_cyclotomic hχ hω

/-- **Quartic case**: J(χ,χ) ∈ ℤ[i], the Gaussian integers.

    For a character χ with χ⁴ = 1 and i a primitive 4-th root of unity, the
    Jacobi sum lies in ℤ[i]. Combined with the norm J·J̄ = p, this realizes
    p = a² + b² with J(χ,χ) = a + bi — the Jacobi sum *is* an explicit
    two-squares decomposition of p ≡ 1 (mod 4). -/
theorem quartic_jacobiSum_mem {χ : MulChar F R} (hχ : χ ^ 4 = 1)
    {i : R} (hi : IsPrimitiveRoot i 4) :
    jacobiSum χ χ ∈ Algebra.adjoin ℤ {i} := by
  haveI : NeZero (4 : ℕ) := ⟨by norm_num⟩
  exact jacobiSum_self_mem_cyclotomic hχ hi

/-- **The (μ−1)²-congruence**: J(χ,χ) ≡ −1 (mod (μ−1)²) inside ℤ[μ].

    A sharpening of integrality: for n > 2 with n ∣ #F − 1, there is z ∈ ℤ[μ]
    with J(χ,χ) = −1 + z·(μ−1)². This congruence underlies the determination of
    the cubic/quartic residue symbol from the reduction of J modulo a prime.

    Source: `exists_jacobiSum_eq_neg_one_add` in Mathlib. -/
theorem jacobiSum_self_congr_neg_one {n : ℕ} (hn : 2 < n) {χ : MulChar F R}
    (hχ : χ ^ n = 1) (hn' : n ∣ Fintype.card F - 1) {μ : R} (hμ : IsPrimitiveRoot μ n) :
    ∃ z ∈ Algebra.adjoin ℤ {μ}, jacobiSum χ χ = -1 + z * (μ - 1) ^ 2 :=
  exists_jacobiSum_eq_neg_one_add hn hχ hχ hn' hμ

end Integrality

-- ============================================================================
-- Part II: The structural theorem — algebraic integer of norm p
-- ============================================================================

section PrimeNorm

variable {p : ℕ} [hp : Fact p.Prime] {F' : Type*} [Field F']

/-- **Algebraic integer of norm p** (the structural payload).

    For a character χ on the prime field 𝔽_p with values in a field F' of
    characteristic ≠ p, of order dividing n (χ^n = 1) but with χ ≠ 1 and χ² ≠ 1,
    and μ a primitive n-th root of unity in F', the Jacobi sum J(χ,χ)
    simultaneously satisfies:

      • J(χ,χ) ∈ ℤ[ζ_n]                          (integrality, Part I)
      • J(χ,χ)·J(χ⁻¹,χ⁻¹) = p                     (algebraic norm, parent entry)

    i.e. J(χ,χ) is an *algebraic integer of norm p* in ℤ[ζ_n]. This is the exact
    object that factors p in the cyclotomic ring and reads off the higher power
    residue symbol. The condition χ² ≠ 1 (automatic when ord χ = n ≥ 3) is what
    makes χ·χ nontrivial so the norm formula applies — the quadratic case
    (χ² = 1) is degenerate and gives only the sign J(χ,χ) = ±1. -/
theorem jacobiSum_self_integral_of_norm_p {n : ℕ} [NeZero n]
    (h_char : ringChar F' ≠ p) {χ : MulChar (ZMod p) F'}
    (hn : χ ^ n = 1) (hχ : χ ≠ 1) (hχ2 : χ ^ 2 ≠ 1)
    {μ : F'} (hμ : IsPrimitiveRoot μ n) :
    jacobiSum χ χ ∈ Algebra.adjoin ℤ {μ} ∧
      jacobiSum χ χ * jacobiSum χ⁻¹ χ⁻¹ = p := by
  refine ⟨jacobiSum_self_mem_cyclotomic hn hμ, ?_⟩
  have h := jacobiSum_mul_jacobiSum_inv
    (by rwa [ZMod.ringChar_zmod_n]) hχ hχ (by rwa [← sq])
  simpa [ZMod.card] using h

/-- **Cubic specialization of the structural theorem**: for a cubic character
    (χ³ = 1, χ ≠ 1, χ² ≠ 1) on 𝔽_p with ω a primitive cube root of unity in F',
    J(χ,χ) ∈ ℤ[ω] and J(χ,χ)·J(χ⁻¹,χ⁻¹) = p. The factorization
    p = a² − ab + b² lives in ℤ[ω]. (As in the parent entry, χ² ≠ 1 is stated
    explicitly — it is the nontriviality of χ·χ that activates the norm formula,
    and it holds automatically once ord χ = 3.) -/
theorem cubic_jacobiSum_integral_of_norm_p
    (h_char : ringChar F' ≠ p) {χ : MulChar (ZMod p) F'}
    (hχ3 : χ ^ 3 = 1) (hχ : χ ≠ 1) (hχ2 : χ ^ 2 ≠ 1) {ω : F'} (hω : IsPrimitiveRoot ω 3) :
    jacobiSum χ χ ∈ Algebra.adjoin ℤ {ω} ∧
      jacobiSum χ χ * jacobiSum χ⁻¹ χ⁻¹ = p := by
  haveI : NeZero (3 : ℕ) := ⟨by norm_num⟩
  exact jacobiSum_self_integral_of_norm_p (n := 3) h_char hχ3 hχ hχ2 hω

end PrimeNorm

/-
  ## Results Summary

  | Theorem | Statement | Source |
  |---------|-----------|--------|
  | `jacobiSum_mem_cyclotomic` | J(χ,φ) ∈ ℤ[μ] for χ^n=φ^n=1 | Mathlib |
  | `jacobiSum_self_mem_cyclotomic` | J(χ,χ) ∈ ℤ[ζ_n] for χ^n=1 | Mathlib |
  | `jacobiSum_self_mem_cyclotomic_of_orderOf` | J(χ,χ) ∈ ℤ[ζ_n] for ord χ = n | This file |
  | `cubic_jacobiSum_mem` | J(χ,χ) ∈ ℤ[ω] for χ³=1 | This file |
  | `quartic_jacobiSum_mem` | J(χ,χ) ∈ ℤ[i] for χ⁴=1 | This file |
  | `jacobiSum_self_congr_neg_one` | J(χ,χ) = −1 + z(μ−1)² in ℤ[μ] | Mathlib |
  | `jacobiSum_self_integral_of_norm_p` | J ∈ ℤ[ζ_n] ∧ J·J̄ = p | This file |
  | `cubic_jacobiSum_integral_of_norm_p` | J ∈ ℤ[ω] ∧ J·J̄ = p | This file |

  **Sorries**: 0
  **Axioms**: 0

  ## Mathematical Significance

  The parent entry pinned the *magnitude* of a Jacobi sum (J·J̄ = p). This file
  supplies the complementary *integrality*: J(χ,χ) is not just a complex number
  of absolute value √p, but a genuine algebraic integer in the cyclotomic ring
  ℤ[ζ_n]. The combined statement `jacobiSum_self_integral_of_norm_p` — "J(χ,χ) is
  an algebraic integer of norm p in ℤ[ζ_n]" — is precisely the object that:

  - n = 3: factors p ≡ 1 (mod 3) as (a + bω)(a + bω²) in ℤ[ω], a² − ab + b² = p;
  - n = 4: factors p ≡ 1 (mod 4) as (a + bi)(a − bi) in ℤ[i], a² + b² = p
    (a constructive form of Fermat's two-squares theorem);
  - general n: provides a norm-p element of ℤ[ζ_n] whose reduction mod a prime q
    yields the n-th power residue symbol, driving Eisenstein reciprocity.

  Both the integrality (`jacobiSum_mem_algebraAdjoin_of_pow_eq_one`) and the
  norm (`jacobiSum_mul_jacobiSum_inv`) are available in Mathlib's
  `NumberTheory.JacobiSum.Basic`; this file assembles them into the structural
  statement the reciprocity program needs.
-/

end JacobiSumIntegrality
