/-
Erdos Problem 662 -- Distances in Separated Point Sets

Conjecture (Erdos-Lovasz-Vesztergombi, 1997): Among all n-point
1-separated sets in R2, the triangular lattice maximizes the number
of pairs at distance le t, for each t ge 1.

Status: OPEN
Reference: https://erdosproblems.com/662
-/

import Mathlib.Data.Nat.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Tactic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.Arg

open Finset Classical

attribute [local instance] Classical.propDecidable

-- ## Definitions

/-- A point in R2. -/
def Point2D := ℝ × ℝ

/-- Squared Euclidean distance between two points. -/
noncomputable def sqDist (p q : Point2D) : ℝ :=
  (p.1 - q.1) ^ 2 + (p.2 - q.2) ^ 2

/-- A set of points is 1-separated if all pairwise squared distances ge 1. -/
def IsSeparated (pts : Finset Point2D) : Prop :=
  ∀ p ∈ pts, ∀ q ∈ pts, p ≠ q → sqDist p q ≥ 1

/-- The set of neighbors of p in pts at squared distance le t squared. -/
noncomputable def neighbors (pts : Finset Point2D) (p : Point2D) (t : ℝ) :
    Finset Point2D :=
  pts.filter fun q => p ≠ q ∧ sqDist p q ≤ t ^ 2

/-- The number of ordered pairs at squared distance le t squared. -/
noncomputable def orderedPairsWithinDist (pts : Finset Point2D) (t : ℝ) : ℕ :=
  ((pts ×ˢ pts).filter fun pq => pq.1 ≠ pq.2 ∧ sqDist pq.1 pq.2 ≤ t ^ 2).card

/-- The number of unordered pairs at distance le t. -/
noncomputable def pairsWithinDist (pts : Finset Point2D) (t : ℝ) : ℕ :=
  orderedPairsWithinDist pts t / 2

-- ## Triangular Lattice

/-- The triangular lattice in R2 with unit spacing, generated by
    basis vectors (1, 0) and (1/2, sqrt3/2). -/
noncomputable def triLatticePoint (a b : ℤ) : Point2D :=
  (↑a + ↑b / 2, ↑b * Real.sqrt 3 / 2)

/-- The triangular lattice norm: a² + ab + b² (equals squared Euclidean
    distance for lattice point (a,b) from the origin). -/
def triLatticeNorm (a b : ℤ) : ℤ := a ^ 2 + a * b + b ^ 2

/-- Computable count of nonzero lattice points with norm ≤ T.
    The range [-T, T] × [-T, T] suffices since a² + ab + b² ≥ max(a², b²/2)
    for all a, b. -/
def triLatticeCountInt (T : ℕ) : ℕ :=
  (((Finset.Icc (-(T : ℤ)) T) ×ˢ (Finset.Icc (-(T : ℤ)) T)).filter
    fun ab : ℤ × ℤ => ab ≠ (0, 0) ∧ triLatticeNorm ab.1 ab.2 ≤ T).card

/-- f(t): the number of nonzero lattice points at distance ≤ t from the origin
    in the triangular lattice. Since all lattice norms a² + ab + b² are integers,
    f(t) = triLatticeCountInt ⌊t²⌋₊. -/
noncomputable def triangularLatticeCount (t : ℝ) : ℕ :=
  triLatticeCountInt (Nat.floor (t ^ 2))

-- ## Known Lattice Values

/-- The squared distance from the origin to lattice point (a,b) is
    a squared + ab + b squared in the triangular lattice. -/
theorem triLattice_sqDist (a b : ℤ) :
    sqDist (triLatticePoint a b) (triLatticePoint 0 0) =
      ↑a ^ 2 + ↑a * ↑b + ↑b ^ 2 := by
  simp only [sqDist, triLatticePoint, Int.cast_zero, zero_div, add_zero, mul_zero,
    zero_mul, sub_zero]
  have h3 : Real.sqrt 3 ^ 2 = 3 := Real.sq_sqrt (by norm_num : (3 : ℝ) ≥ 0)
  have key : (↑b * Real.sqrt 3 / 2) ^ 2 = ↑b ^ 2 * 3 / 4 := by
    rw [div_pow, mul_pow, h3]; ring
  rw [key]; ring

/-- The integer count at threshold 1 is 6: points (±1,0), (0,±1), (1,−1), (−1,1). -/
theorem triLatticeCountInt_one : triLatticeCountInt 1 = 6 := by native_decide

/-- The integer count at threshold 3 is 12: 6 nearest + 6 second-shell. -/
theorem triLatticeCountInt_three : triLatticeCountInt 3 = 12 := by native_decide

/-- The 6 nearest neighbors in the triangular lattice at distance 1. -/
theorem triLattice_nearest_neighbors :
    triangularLatticeCount 1 = 6 := by
  unfold triangularLatticeCount
  norm_num
  exact triLatticeCountInt_one

/-- The 12 points within distance √3. -/
theorem triLattice_second_shell :
    triangularLatticeCount (Real.sqrt 3) = 12 := by
  unfold triangularLatticeCount
  have hsq : (Real.sqrt 3) ^ 2 = 3 := Real.sq_sqrt (by norm_num : (3 : ℝ) ≥ 0)
  rw [hsq]
  have hfl : Nat.floor (3 : ℝ) = 3 := by
    rw [Nat.floor_eq_iff (by norm_num : (0 : ℝ) ≤ 3)]
    constructor <;> norm_num
  rw [hfl]
  exact triLatticeCountInt_three

-- ## Contact Number Bound (t = 1 case)

/-- In a 1-separated set, all unit neighbors are at exactly unit squared distance.
    Neighbors satisfy sqDist ≤ 1 (from neighbors def) and sqDist ≥ 1 (from separation).
    Together: sqDist = 1, so all neighbors lie on the unit circle around p. -/
private lemma neighbor_sqDist_eq_one (pts : Finset Point2D) (p q : Point2D)
    (hp : p ∈ pts) (hsep : IsSeparated pts)
    (hneigh : q ∈ neighbors pts p 1) :
    sqDist p q = 1 := by
  have hmem := Finset.mem_filter.mp hneigh
  have hle : sqDist p q ≤ 1 ^ 2 := hmem.2.2
  have hge := hsep p hp q hmem.1 hmem.2.1
  linarith [sq_nonneg (1 : ℝ)]

/-- The dot product of relative position vectors of two distinct neighbors
    is at most 1/2. From the identity sqDist(q₁,q₂) = 2 - 2·dot and
    the separation constraint sqDist(q₁,q₂) ≥ 1. -/
private lemma neighbor_dot_le_half (pts : Finset Point2D) (p q₁ q₂ : Point2D)
    (hp : p ∈ pts) (hsep : IsSeparated pts)
    (hq₁ : q₁ ∈ neighbors pts p 1) (hq₂ : q₂ ∈ neighbors pts p 1)
    (hne : q₁ ≠ q₂) :
    (q₁.1 - p.1) * (q₂.1 - p.1) + (q₁.2 - p.2) * (q₂.2 - p.2) ≤ 1 / 2 := by
  have hq₁_mem := (Finset.mem_filter.mp hq₁).1
  have hq₂_mem := (Finset.mem_filter.mp hq₂).1
  have hd₁ := neighbor_sqDist_eq_one pts p q₁ hp hsep hq₁
  have hd₂ := neighbor_sqDist_eq_one pts p q₂ hp hsep hq₂
  have hd₁₂ := hsep q₁ hq₁_mem q₂ hq₂_mem hne
  unfold sqDist at hd₁ hd₂ hd₁₂
  -- Key identity: (q₁-q₂)² = |q₁-p|² + |q₂-p|² - 2·dot
  have key : (q₁.1 - q₂.1) ^ 2 + (q₁.2 - q₂.2) ^ 2 =
      (p.1 - q₁.1) ^ 2 + (p.2 - q₁.2) ^ 2 +
      ((p.1 - q₂.1) ^ 2 + (p.2 - q₂.2) ^ 2) -
      2 * ((q₁.1 - p.1) * (q₂.1 - p.1) + (q₁.2 - p.2) * (q₂.2 - p.2)) := by ring
  linarith

-- ===== Kissing Number Proof Infrastructure =====

/-- Sector assignment for angles in (-π, π]: six half-open arcs of width π/3. -/
private noncomputable def angleSector (θ : ℝ) : Fin 6 :=
  if θ ≤ -2 * Real.pi / 3 then ⟨0, by omega⟩
  else if θ ≤ -Real.pi / 3 then ⟨1, by omega⟩
  else if θ ≤ 0 then ⟨2, by omega⟩
  else if θ ≤ Real.pi / 3 then ⟨3, by omega⟩
  else if θ ≤ 2 * Real.pi / 3 then ⟨4, by omega⟩
  else ⟨5, by omega⟩

private noncomputable def sectorLo : Fin 6 → ℝ
  | ⟨0, _⟩ => -Real.pi
  | ⟨1, _⟩ => -2 * Real.pi / 3
  | ⟨2, _⟩ => -Real.pi / 3
  | ⟨3, _⟩ => 0
  | ⟨4, _⟩ => Real.pi / 3
  | ⟨5, _⟩ => 2 * Real.pi / 3
  | ⟨n + 6, h⟩ => absurd h (by omega)

private noncomputable def sectorHi : Fin 6 → ℝ
  | ⟨0, _⟩ => -2 * Real.pi / 3
  | ⟨1, _⟩ => -Real.pi / 3
  | ⟨2, _⟩ => 0
  | ⟨3, _⟩ => Real.pi / 3
  | ⟨4, _⟩ => 2 * Real.pi / 3
  | ⟨5, _⟩ => Real.pi
  | ⟨n + 6, h⟩ => absurd h (by omega)

private lemma sectorHi_sub_sectorLo (k : Fin 6) :
    sectorHi k - sectorLo k = Real.pi / 3 := by
  fin_cases k <;> simp [sectorHi, sectorLo] <;> ring

private lemma angleSector_in_range (θ : ℝ) (hθ : θ ∈ Set.Ioc (-Real.pi) Real.pi) :
    sectorLo (angleSector θ) < θ ∧ θ ≤ sectorHi (angleSector θ) := by
  simp only [angleSector]
  split_ifs with h1 h2 h3 h4 h5
  all_goals (simp only [sectorLo, sectorHi]; constructor <;> linarith [hθ.1, hθ.2])

private lemma same_sector_diff_lt {θ φ : ℝ}
    (hθ : θ ∈ Set.Ioc (-Real.pi) Real.pi)
    (hφ : φ ∈ Set.Ioc (-Real.pi) Real.pi)
    (hs : angleSector θ = angleSector φ) :
    |θ - φ| < Real.pi / 3 := by
  obtain ⟨hlo_θ, hhi_θ⟩ := angleSector_in_range θ hθ
  obtain ⟨hlo_φ, hhi_φ⟩ := angleSector_in_range φ hφ
  rw [hs] at hlo_φ hhi_φ
  have hw := sectorHi_sub_sectorLo (angleSector θ)
  rw [abs_sub_lt_iff]; constructor <;> linarith

private lemma cos_gt_half_of_abs_lt {d : ℝ} (hd : |d| < Real.pi / 3) :
    1 / 2 < Real.cos d := by
  have hpi := Real.pi_pos
  have heven : Real.cos d = Real.cos |d| := by
    rcases le_or_lt 0 d with h | h
    · rw [abs_of_nonneg h]
    · rw [abs_of_neg h, Real.cos_neg]
  rw [heven, show (1 : ℝ) / 2 = Real.cos (Real.pi / 3) from Real.cos_pi_div_three.symm]
  rcases eq_or_lt_of_le (abs_nonneg d) with h0 | h0
  · rw [← h0, Real.cos_zero, Real.cos_pi_div_three]; norm_num
  · exact Real.strictAntiOn_cos
      (Set.mem_Icc.mpr ⟨le_of_lt h0, by linarith⟩)
      (Set.mem_Icc.mpr ⟨by linarith, by linarith⟩)
      hd

/-- Dot product of unit vectors equals cosine of their Complex.arg difference. -/
private lemma unit_dot_eq_cos_arg_sub {v w : ℝ × ℝ}
    (hv : v.1 ^ 2 + v.2 ^ 2 = 1) (hw : w.1 ^ 2 + w.2 ^ 2 = 1) :
    v.1 * w.1 + v.2 * w.2 =
      Real.cos (Complex.arg ⟨v.1, v.2⟩ - Complex.arg ⟨w.1, w.2⟩) := by
  set zv : ℂ := ⟨v.1, v.2⟩
  set zw : ℂ := ⟨w.1, w.2⟩
  have hv_ne : zv ≠ 0 := by
    intro h; have := Complex.ext_iff.mp h; simp at this; nlinarith [this.1, this.2, hv]
  have hw_ne : zw ≠ 0 := by
    intro h; have := Complex.ext_iff.mp h; simp at this; nlinarith [this.1, this.2, hw]
  have hv_abs : Complex.abs zv = 1 := by
    have hsq : (Complex.abs zv) ^ 2 = 1 := by
      rw [sq_abs]; simp [Complex.normSq_apply, zv]; nlinarith
    have hnn := Complex.abs.nonneg zv
    nlinarith [sq_nonneg (Complex.abs zv - 1)]
  have hw_abs : Complex.abs zw = 1 := by
    have hsq : (Complex.abs zw) ^ 2 = 1 := by
      rw [sq_abs]; simp [Complex.normSq_apply, zw]; nlinarith
    have hnn := Complex.abs.nonneg zw
    nlinarith [sq_nonneg (Complex.abs zw - 1)]
  rw [Real.cos_sub,
    show Real.cos (Complex.arg zv) = v.1 from by
      rw [Complex.cos_arg hv_ne, hv_abs, div_one],
    show Real.sin (Complex.arg zv) = v.2 from by
      rw [Complex.sin_arg hv_ne, hv_abs, div_one],
    show Real.cos (Complex.arg zw) = w.1 from by
      rw [Complex.cos_arg hw_ne, hw_abs, div_one],
    show Real.sin (Complex.arg zw) = w.2 from by
      rw [Complex.sin_arg hw_ne, hw_abs, div_one]]

-- ===== Main Kissing Number Theorem =====

/-- **2D Kissing Number**: At most 6 unit vectors in ℝ² can have pairwise
    dot product ≤ 1/2. Equivalently: at most 6 points on the unit circle
    can have pairwise distance ≥ 1.

    Proof: Assign each vector to one of 6 sectors of width π/3 via Complex.arg.
    Two vectors in the same sector have angular separation < π/3, hence
    dot product > cos(π/3) = 1/2. So the sector map is injective on S,
    giving |S| ≤ 6. -/
theorem kissing_number_2d (S : Finset (ℝ × ℝ))
    (hunit : ∀ v ∈ S, v.1 ^ 2 + v.2 ^ 2 = 1)
    (hdot : ∀ v ∈ S, ∀ w ∈ S, v ≠ w → v.1 * w.1 + v.2 * w.2 ≤ 1 / 2) :
    S.card ≤ 6 := by
  let f : ℝ × ℝ → Fin 6 := fun v => angleSector (Complex.arg ⟨v.1, v.2⟩)
  have hinj : Set.InjOn f ↑S := by
    intro v hv w hw hfw
    by_contra hvw
    have hv_mem : v ∈ S := Finset.mem_coe.mp hv
    have hw_mem : w ∈ S := Finset.mem_coe.mp hw
    have hv_range : Complex.arg ⟨v.1, v.2⟩ ∈ Set.Ioc (-Real.pi) Real.pi :=
      ⟨Complex.neg_pi_lt_arg _, Complex.arg_le_pi _⟩
    have hw_range : Complex.arg ⟨w.1, w.2⟩ ∈ Set.Ioc (-Real.pi) Real.pi :=
      ⟨Complex.neg_pi_lt_arg _, Complex.arg_le_pi _⟩
    have h_close := same_sector_diff_lt hv_range hw_range hfw
    have h_cos := cos_gt_half_of_abs_lt h_close
    have h_dot := unit_dot_eq_cos_arg_sub (hunit v hv_mem) (hunit w hw_mem)
    linarith [hdot v hv_mem w hw_mem hvw]
  have h1 := (Finset.card_image_of_injOn hinj).symm
  have h2 := Finset.card_le_univ (S.image f)
  simp [Fintype.card_fin] at h2
  linarith

/-- In a 1-separated set, each point has at most 6 unit neighbors.
    Reduces to the 2D kissing number via translation to the origin. -/
theorem unit_neighbor_bound (pts : Finset Point2D) (p : Point2D)
    (hp : p ∈ pts) (hsep : IsSeparated pts) :
    (neighbors pts p 1).card ≤ 6 := by
  -- Translate neighbors to origin: S = {q - p : q ∈ neighbors}
  set S := (neighbors pts p 1).image (fun q : Point2D => (q.1 - p.1, q.2 - p.2))
  -- Translation is injective, so card is preserved
  have hcard : S.card = (neighbors pts p 1).card := by
    apply Finset.card_image_of_injective
    intro q₁ q₂ heq
    exact Prod.ext (by linarith [Prod.mk.inj heq |>.1])
                   (by linarith [Prod.mk.inj heq |>.2])
  rw [← hcard]
  apply kissing_number_2d S
  · -- All translated vectors are unit (sqDist = 1)
    intro v hv
    rw [Finset.mem_image] at hv
    obtain ⟨q, hq, rfl⟩ := hv
    have h := neighbor_sqDist_eq_one pts p q hp hsep hq
    unfold sqDist at h; nlinarith
  · -- Pairwise dot products ≤ 1/2
    intro v hv w hw hvw
    rw [Finset.mem_image] at hv hw
    obtain ⟨q₁, hq₁, rfl⟩ := hv
    obtain ⟨q₂, hq₂, rfl⟩ := hw
    have hne : q₁ ≠ q₂ := fun heq => hvw (by subst heq; rfl)
    exact neighbor_dot_le_half pts p q₁ q₂ hp hsep hq₁ hq₂ hne

/-- Ordered unit-distance pairs bounded by 6n.

    Proof: decompose the filtered product into fibers indexed by first coordinate.
    Each fiber has card ≤ |neighbors(p)| ≤ 6. Sum over p gives ≤ 6n. -/
theorem ordered_unit_pairs_bound (pts : Finset Point2D)
    (hsep : IsSeparated pts) :
    orderedPairsWithinDist pts 1 ≤ 6 * pts.card := by
  unfold orderedPairsWithinDist
  set S := (pts ×ˢ pts).filter
    (fun pq : Point2D × Point2D => pq.1 ≠ pq.2 ∧ sqDist pq.1 pq.2 ≤ 1 ^ 2)
  -- T(p) = {(p,q) : q ∈ neighbors(pts, p, 1)} — the fiber over p
  set T := fun p => (neighbors pts p 1).image (fun q => (p, q))
  -- S ⊆ ⋃_{p ∈ pts} T(p): every ordered pair lives in its first-coordinate fiber
  have h_sub : S ⊆ pts.biUnion T := by
    intro ⟨p, q⟩ hpq
    rw [Finset.mem_biUnion]
    have hpq' := Finset.mem_filter.mp hpq
    have hp := (Finset.mem_product.mp hpq'.1).1
    have hq := (Finset.mem_product.mp hpq'.1).2
    exact ⟨p, hp, Finset.mem_image.mpr ⟨q,
      Finset.mem_filter.mpr ⟨hq, hpq'.2.1, hpq'.2.2⟩, rfl⟩⟩
  -- |T(p)| ≤ |neighbors(p)| ≤ 6
  have h_card_T : ∀ p ∈ pts, (T p).card ≤ 6 := fun p hp =>
    le_trans Finset.card_image_le (unit_neighbor_bound pts p hp hsep)
  -- Chain: |S| ≤ |⋃ T(p)| ≤ ∑ |T(p)| ≤ ∑ 6 = 6n
  calc S.card
      ≤ (pts.biUnion T).card := Finset.card_le_card h_sub
    _ ≤ pts.sum (fun p => (T p).card) := Finset.card_biUnion_le
    _ ≤ pts.sum (fun _ => 6) := Finset.sum_le_sum h_card_T
    _ = 6 * pts.card := by simp [Finset.sum_const, mul_comm]

/-- Contact Number Bound (3n): unordered unit-distance pairs le 3n. -/
theorem contact_number_3n (pts : Finset Point2D)
    (hsep : IsSeparated pts) :
    pairsWithinDist pts 1 ≤ 3 * pts.card := by
  unfold pairsWithinDist
  have h := ordered_unit_pairs_bound pts hsep
  omega

-- ## Main Conjecture (OPEN)

/-- Erdos-Lovasz-Vesztergombi Conjecture (OPEN). -/
axiom erdos_662_lattice_optimal :
  ∀ t : ℝ, t ≥ 1 →
    ∃ N : ℕ, ∀ (pts : Finset Point2D), IsSeparated pts →
      pts.card ≥ N →
      pairsWithinDist pts t ≤ pts.card * triangularLatticeCount t / 2
