import Proofs.Erdos85SizeTwoMuNegFiveMatchingNormalization
import Proofs.Erdos85FinEightPairCoordinates
import Proofs.Erdos85OneHighCanonicalMate

/-!
# Canonical coordinates for the `mu=-5` shore matchings

Each eight-point shore carries a free involution.  We construct its four
two-point orbits and label the orbit/end-point coordinates by
`Fin 4 × Fin 2 ≃ Fin 8`, making the matching the standard involution
`(01)(23)(45)(67)`.
-/

namespace Erdos85

noncomputable section

/-- The orbit relation generated by an involution. -/
def freeInvolutionSetoid {X : Type*} (mate : X → X)
    (hinv : Function.Involutive mate) : Setoid X where
  r x y := y = x ∨ y = mate x
  iseqv := {
    refl := fun _ => Or.inl rfl
    symm := by
      intro x y h
      rcases h with rfl | h
      · exact Or.inl rfl
      · right
        rw [h, hinv x]
    trans := by
      intro x y z hxy hyz
      rcases hxy with rfl | hxy <;> rcases hyz with rfl | hyz
      · exact Or.inl rfl
      · exact Or.inr hyz
      · exact Or.inr hxy
      · left
        rw [hyz, hxy, hinv x] }

abbrev FreeInvolutionOrbit {X : Type*} (mate : X → X)
    (hinv : Function.Involutive mate) :=
  Quotient (freeInvolutionSetoid mate hinv)

/-- Each orbit of a fixed-point-free involution has canonical two-point
coordinates after choosing the quotient's representative. -/
def freeInvolutionFiberEquiv {X : Type*} [DecidableEq X]
    (mate : X → X) (hinv : Function.Involutive mate)
    (hfree : ∀ x, mate x ≠ x)
    (q : FreeInvolutionOrbit mate hinv) :
    Fin 2 ≃ {x : X // Quotient.mk (freeInvolutionSetoid mate hinv) x = q} := by
  let f : Fin 2 → {x : X //
      Quotient.mk (freeInvolutionSetoid mate hinv) x = q} := fun i =>
    if i = 0 then
      ⟨q.out, Quotient.out_eq q⟩
    else
      ⟨mate q.out, (Quotient.sound (Or.inr rfl)).symm.trans
        (Quotient.out_eq q)⟩
  apply Equiv.ofBijective f
  constructor
  · intro i j hij
    fin_cases i <;> fin_cases j
    · rfl
    · exfalso
      exact hfree q.out (Subtype.ext_iff.mp hij).symm
    · exfalso
      exact hfree q.out (Subtype.ext_iff.mp hij)
    · rfl
  · intro z
    have hzq : Quotient.mk (freeInvolutionSetoid mate hinv) z.1 =
        Quotient.mk (freeInvolutionSetoid mate hinv) q.out :=
      z.2.trans (Quotient.out_eq q).symm
    rcases Quotient.exact hzq with hz | hz
    · exact ⟨0, by apply Subtype.ext; simpa [f] using hz⟩
    · have hz' : z.1 = mate q.out := by
        rw [hz, hinv]
      exact ⟨1, by apply Subtype.ext; simpa [f] using hz'.symm⟩

theorem freeInvolutionFiberEquiv_swap {X : Type*} [DecidableEq X]
    (mate : X → X) (hinv : Function.Involutive mate)
    (hfree : ∀ x, mate x ≠ x)
    (q : FreeInvolutionOrbit mate hinv) (i : Fin 2) :
    (freeInvolutionFiberEquiv mate hinv hfree q (finTwoSwap i)).1 =
      mate (freeInvolutionFiberEquiv mate hinv hfree q i).1 := by
  fin_cases i
  · rfl
  · exact (hinv q.out).symm

/-- Any free involution on an eight-element finite type admits `Fin 8`
coordinates in which it is the standard four-edge matching. -/
theorem exists_finEight_coordinates_of_freeInvolution
    {X : Type*} [Fintype X] [DecidableEq X]
    (hcard : Fintype.card X = 8)
    (mate : Equiv.Perm X)
    (hinv : Function.Involutive mate)
    (hfree : ∀ x, mate x ≠ x) :
    ∃ e : X ≃ Fin 8, ∀ x,
      e (mate x) = oneHighStandardMate (e x) := by
  let Q := FreeInvolutionOrbit mate hinv
  let mk : X → Q := Quotient.mk (freeInvolutionSetoid mate hinv)
  letI : DecidableEq Q := Classical.decEq Q
  letI : Fintype Q := Fintype.ofSurjective mk Quotient.mk_surjective
  let fiber : (q : Q) → Fin 2 ≃ {x : X // mk x = q} := fun q =>
    freeInvolutionFiberEquiv mate hinv hfree q
  let pairCoords : X ≃ Q × Fin 2 :=
    (Equiv.sigmaFiberEquiv mk).symm |>.trans
      (Equiv.sigmaCongrRight fun q => (fiber q).symm) |>.trans
      (Equiv.sigmaEquivProd Q (Fin 2))
  have hpairCard : Fintype.card Q * 2 = 8 := by
    rw [← Fintype.card_fin 2, ← Fintype.card_prod,
      ← Fintype.card_congr pairCoords, hcard]
  have hQcard : Fintype.card Q = 4 := by omega
  let orbitCoords : Q ≃ Fin 4 := Fintype.equivOfCardEq (by simpa using hQcard)
  let e : X ≃ Fin 8 := pairCoords |>.trans
    (Equiv.prodCongr orbitCoords (Equiv.refl (Fin 2))) |>.trans
    finEightPairCoordinates.symm
  have finTwo_eq_swap_of_ne (a b : Fin 2) (hab : a ≠ b) :
      a = finTwoSwap b := by
    fin_cases a <;> fin_cases b <;> simp_all [finTwoSwap_apply]
  have hpair (x : X) : pairCoords (mate x) =
      (pairCoords x).map id finTwoSwap := by
    have hfirst : (pairCoords (mate x)).1 = (pairCoords x).1 := by
      simp only [pairCoords, Equiv.trans_apply, Equiv.sigmaEquivProd_apply,
        Equiv.sigmaCongrRight_apply]
      change mk (mate x) = mk x
      exact Quotient.sound (Or.inr (hinv x).symm)
    apply Prod.ext
    · simpa using hfirst
    · simp only [Prod.map, id_eq]
      apply finTwo_eq_swap_of_ne
      intro hsecond
      have heq : pairCoords (mate x) = pairCoords x :=
        Prod.ext hfirst hsecond
      exact hfree x (pairCoords.injective heq)
  have hstandard (i : Fin 8) :
      finEightPairCoordinates (oneHighStandardMate i) =
        (finEightPairCoordinates i).map id finTwoSwap := by
    fin_cases i <;> decide
  refine ⟨e, ?_⟩
  intro x
  apply finEightPairCoordinates.injective
  simp only [e, Equiv.trans_apply, Equiv.apply_symm_apply, hstandard]
  rw [hpair]
  rfl

/-- The two `mu=-5` shore matchings can simultaneously be put into the
standard `Fin 8` matching coordinates. -/
theorem orderSixtyFour_sizeTwo_muNegFive_standard_matching_coordinates
    {V : Type*} [Fintype V] [DecidableEq V]
    (G : SimpleGraph V) [DecidableRel G.Adj]
    [DecidableRel (antipodalGraph G).Adj]
    [DecidableRel (triangleFreeEdgeGraph G).Adj]
    [Fintype (secondOrderDefectGraph G).ConnectedComponent]
    [DecidableEq (secondOrderDefectGraph G).ConnectedComponent]
    (hfree : ¬ containsC4 V G)
    (hreg : ∀ x, G.degree x = 8)
    (hcard : Fintype.card V = 8 * 8)
    (c : (secondOrderDefectGraph G).ConnectedComponent)
    (hc : c.supp.ncard = 8 * 2)
    (s : V → ℤ)
    (hs_out : ∀ x, x ∉ c.supp → s x = 0)
    (hs_in : ∀ x, x ∈ c.supp → s x = -1 ∨ s x = 1)
    (hH : ∀ z ∈ c.supp, ∑ y ∈ (G.neighborFinset z).filter
      (fun y ↦ (secondOrderDefectGraph G).connectedComponentMk y = c),
        s y = -2 * s z)
    (hD : ∀ z, z ∈ c.supp →
      ∑ y ∈ (secondOrderDefectGraph G).neighborFinset z, s y =
        (-5 : ℤ) * s z) :
    let D := secondOrderDefectGraph G
    let Xp := MuNegFivePositiveShore D c s
    let Xm := MuNegFiveNegativeShore D c s
    ∃ ep : Xp ≃ Fin 8, ∃ em : Xm ≃ Fin 8,
      (∀ x y, D.Adj x.1 y.1 ↔ oneHighStandardMate (ep x) = ep y) ∧
      (∀ x y, D.Adj x.1 y.1 ↔ oneHighStandardMate (em x) = em y) := by
  classical
  dsimp only
  let D := secondOrderDefectGraph G
  let Xp := MuNegFivePositiveShore D c s
  let Xm := MuNegFiveNegativeShore D c s
  have hprofile := orderSixtyFour_sizeTwo_muNegFive_signed_internal_degreeProfile
    G hfree hreg hcard c hc s hs_out hs_in hH hD
  have hXpCard : Fintype.card Xp = 8 := by
    let S := (Finset.univ : Finset V).filter fun x => x ∈ c.supp ∧ s x = 1
    let e : Xp ≃ {x : V // x ∈ S} :=
      Equiv.subtypeEquivRight fun x => by simp [S, D]
    calc
      Fintype.card Xp = Fintype.card {x : V // x ∈ S} :=
        Fintype.card_congr e
      _ = S.card := Fintype.card_coe S
      _ = 8 := hprofile.1
  have hXmCard : Fintype.card Xm = 8 := by
    let S := (Finset.univ : Finset V).filter fun x => x ∈ c.supp ∧ s x = -1
    let e : Xm ≃ {x : V // x ∈ S} :=
      Equiv.subtypeEquivRight fun x => by simp [S, D]
    calc
      Fintype.card Xm = Fintype.card {x : V // x ∈ S} :=
        Fintype.card_congr e
      _ = S.card := Fintype.card_coe S
      _ = 8 := hprofile.2.1
  obtain ⟨fp, fm, hfp, hfpinv, hfpne, hfm, hfminv, hfmne⟩ :=
    orderSixtyFour_sizeTwo_muNegFive_sameSign_defect_matchings
      G hfree hreg hcard c hc s hs_out hs_in hH hD
  obtain ⟨ep, hep⟩ := exists_finEight_coordinates_of_freeInvolution
    hXpCard fp hfpinv hfpne
  obtain ⟨em, hem⟩ := exists_finEight_coordinates_of_freeInvolution
    hXmCard fm hfminv hfmne
  refine ⟨ep, em, ?_, ?_⟩
  · intro x y
    rw [hfp x y, ← ep.apply_eq_iff_eq]
    exact Eq.congr_left (hep x)
  · intro x y
    rw [hfm x y, ← em.apply_eq_iff_eq]
    exact Eq.congr_left (hem x)

end

end Erdos85

#print axioms Erdos85.exists_finEight_coordinates_of_freeInvolution
#print axioms Erdos85.orderSixtyFour_sizeTwo_muNegFive_standard_matching_coordinates
