/-
Erdős Problem #481: Affine Sequence Iteration and Eventual Repetition

Source: https://erdosproblems.com/481
Status: SOLVED (Klarner 1982)

Statement:
Let a₁,...,aᵣ,b₁,...,bᵣ ∈ ℕ such that Σᵢ(1/aᵢ) > 1.
For a sequence A = (x₁,...,xₙ), define T(A) as the sequence of length rn:
  T(A) = (aᵢxⱼ + bᵢ)_{1≤j≤n, 1≤i≤r}

Prove: If A₁ = (1) and Aₖ₊₁ = T(Aₖ), then some Aₖ has repeated elements.

Key Insight:
The condition Σ(1/aᵢ) > 1 ensures the "density" of produced numbers
is high enough that collisions must eventually occur.

References:
- Erdős-Graham [ErGr80]: Original problem, p.96
- Klarner [Kl82]: First proof (free semigroup condition)
- Kolpakov-Talambutsa [KoTa22]: Generalization
-/

import Mathlib.Data.Nat.Basic
import Mathlib.Data.List.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Algebra.BigOperators.Group.Finset

namespace Erdos481

/-
## Part I: Basic Definitions
-/

/--
**Affine transformation:**
The map x ↦ ax + b for natural numbers a, b.
-/
def affineTransform (a b x : ℕ) : ℕ := a * x + b

/--
**The affine parameters:**
A collection of (aᵢ, bᵢ) pairs defining the transformations.
-/
structure AffineParams where
  r : ℕ                -- number of transformations
  a : Fin r → ℕ        -- the aᵢ values
  b : Fin r → ℕ        -- the bᵢ values
  a_pos : ∀ i, a i > 0 -- aᵢ must be positive

/--
**The critical condition: Σ(1/aᵢ) > 1**
This "density" condition ensures enough coverage for collisions.
-/
def satisfiesDensityCondition (params : AffineParams) : Prop :=
  (∑ i : Fin params.r, (1 : ℚ) / params.a i) > 1

/--
**Apply transformation T to a sequence:**
T(A) = (aᵢxⱼ + bᵢ) for all i, j combinations.
-/
def applyT (params : AffineParams) (seq : List ℕ) : List ℕ :=
  seq.bind (fun x => List.ofFn (fun i => affineTransform (params.a i) (params.b i) x))

/-
## Part II: The Iteration Process
-/

/--
**Initial sequence:**
A₁ = (1), a singleton list containing 1.
-/
def initialSeq : List ℕ := [1]

/--
**k-th iterate of T:**
Aₖ is T applied k-1 times to the initial sequence.
-/
def iterateT (params : AffineParams) : ℕ → List ℕ
  | 0 => []
  | 1 => initialSeq
  | k + 1 => applyT params (iterateT params k)

/--
**Sequence has repeated elements:**
The list contains some value at least twice.
-/
def hasRepeats (seq : List ℕ) : Prop :=
  ∃ x, seq.count x ≥ 2

/--
**Sequence has no repeated elements:**
All values in the list are distinct.
-/
def allDistinct (seq : List ℕ) : Prop :=
  seq.Nodup

/-
## Part III: The Main Theorem
-/

/--
**Erdős-Graham Conjecture (PROVED):**
If Σ(1/aᵢ) > 1, then some iterate Aₖ must have repeated elements.

The key insight is that the density condition Σ(1/aᵢ) > 1 means the
transformations "overlap" enough. If we think of [0, N] being covered
by intervals of length N/aᵢ, the total coverage exceeds N, so
pigeonhole applies. Klarner (1982) formalized this via free semigroup
theory: the density condition characterizes when the affine semigroup
generated by x ↦ aᵢx + bᵢ is non-free, and non-freeness implies
relations that manifest as collisions.

When Σ(1/aᵢ) ≤ 1, the semigroup IS free and the conjecture can fail.
The transformations are "sparse" enough to avoid collisions.
-/
axiom erdos_graham_conjecture :
    ∀ params : AffineParams,
      satisfiesDensityCondition params →
        ∃ k : ℕ, hasRepeats (iterateT params k)

/--
**The main theorem (Klarner 1982):**
The conjecture is true. Klarner proved the affine semigroup generated
by x ↦ aᵢx + bᵢ is free iff Σ(1/aᵢ) ≤ 1. The Erdős conjecture
follows: non-freeness implies relations, which become collisions.

Kolpakov-Talambutsa (2022) extended this to more general settings,
including affine maps on the real line.
-/
theorem klarner_theorem (params : AffineParams)
    (h_density : satisfiesDensityCondition params) :
    ∃ k : ℕ, hasRepeats (iterateT params k) :=
  erdos_graham_conjecture params h_density

/-
## Part IV: Summary

PROBLEM: For affine transformations with Σ(1/aᵢ) > 1,
prove that iterating T(A) = (aᵢxⱼ + bᵢ) eventually produces
repeated elements.

ANSWER: YES (Klarner 1982)

KEY INSIGHTS:
1. The density condition Σ(1/aᵢ) > 1 is crucial
2. It corresponds to the affine semigroup being non-free
3. Non-freeness implies relations, which become collisions
4. The condition is tight: Σ(1/aᵢ) ≤ 1 can avoid collisions

This connects number theory to algebraic semigroup theory.
-/

/--
**Erdős Problem #481 Summary:**
Klarner's theorem resolves the conjecture: the density condition
is both necessary and sufficient for eventual collisions.
-/
theorem erdos_481_summary (params : AffineParams)
    (h_density : satisfiesDensityCondition params) :
    ∃ k : ℕ, hasRepeats (iterateT params k) :=
  klarner_theorem params h_density

end Erdos481
