import Proofs.Erdos85OrderFortyNineT2RepAProofChunk0
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk1
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk2
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk3
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk4
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk5
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk6
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk7
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk8
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk9
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk10
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk11
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk12
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk13
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk14
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk15
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk16
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk17
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk18
import Proofs.Erdos85OrderFortyNineT2RepAProofChunk19

/- GENERATED aggregator for OrderFortyNineT2RepAProof: 9145 actions across 20 chunks;
   source t2_repA.lrat sha256 fbb6093345fe5ebbb18442dd9aedd0eac5a7d2f880f3f6caf74ff209cae8fcff;
   renumbered vs numOriginalClauses = 1329452; leading deletions omitted. -/

namespace Erdos85

def orderFortyNineT2RepAProof : Array Std.Tactic.BVDecide.LRAT.IntAction :=
  orderFortyNineT2RepAProofChunk0 ++ orderFortyNineT2RepAProofChunk1 ++ orderFortyNineT2RepAProofChunk2 ++ orderFortyNineT2RepAProofChunk3 ++ orderFortyNineT2RepAProofChunk4 ++ orderFortyNineT2RepAProofChunk5 ++ orderFortyNineT2RepAProofChunk6 ++ orderFortyNineT2RepAProofChunk7 ++ orderFortyNineT2RepAProofChunk8 ++ orderFortyNineT2RepAProofChunk9 ++ orderFortyNineT2RepAProofChunk10 ++ orderFortyNineT2RepAProofChunk11 ++ orderFortyNineT2RepAProofChunk12 ++ orderFortyNineT2RepAProofChunk13 ++ orderFortyNineT2RepAProofChunk14 ++ orderFortyNineT2RepAProofChunk15 ++ orderFortyNineT2RepAProofChunk16 ++ orderFortyNineT2RepAProofChunk17 ++ orderFortyNineT2RepAProofChunk18 ++ orderFortyNineT2RepAProofChunk19

end Erdos85
