import Proofs.Erdos85ThirtyTwo

/-!
# The antipodal quotient at order 32

Any hypothetical `C₄`-free graph on 32 vertices of minimum degree six has a
canonical fixed-point-free antipode automorphism.  This file constructs its
quotient graph.  Quotient adjacency means that the two antipodal fibers have
an edge between them; the original graph selects one of the two possible
perfect matchings over every quotient edge.
-/

namespace Erdos85

open SimpleGraph

noncomputable section

variable (G : SimpleGraph (Fin 32)) [DecidableRel G.Adj]
variable (hfree : ¬ containsC4 (Fin 32) G) (hmin : 6 ≤ G.minDegree)

private abbrev p := thirtyTwoAntipode G hfree hmin

/-- Equivalence relation generated by the antipode involution. -/
def thirtyTwoAntipodeSetoid : Setoid (Fin 32) where
  r x y := x = y ∨ x = p G hfree hmin y
  iseqv := by
    refine ⟨fun x => Or.inl rfl, ?_, ?_⟩
    · intro x y hxy
      rcases hxy with rfl | hxy
      · exact Or.inl rfl
      · right
        have hp := congrArg (p G hfree hmin) hxy
        exact (hp.trans (thirtyTwoAntipode_involutive G hfree hmin y)).symm
    · intro x y z hxy hyz
      rcases hxy with rfl | hxy
      · exact hyz
      · rcases hyz with rfl | hyz
        · exact Or.inr hxy
        · left
          calc
            x = p G hfree hmin y := hxy
            _ = p G hfree hmin (p G hfree hmin z) :=
              congrArg (p G hfree hmin) hyz
            _ = z := thirtyTwoAntipode_involutive G hfree hmin z

noncomputable instance thirtyTwoAntipodeSetoid.instDecidableRel :
    DecidableRel (thirtyTwoAntipodeSetoid G hfree hmin : Fin 32 → Fin 32 → Prop) :=
  Classical.decRel _

/-- The 16 antipodal fibers (cardinality 16 is established below). -/
abbrev ThirtyTwoQuotient := Quotient (thirtyTwoAntipodeSetoid G hfree hmin)

/-- Representatives belong to the same fiber exactly when they are equal or
antipodal. -/
theorem thirtyTwoAntipodeSetoid_rel_iff (x y : Fin 32) :
    (thirtyTwoAntipodeSetoid G hfree hmin : Fin 32 → Fin 32 → Prop) x y ↔
      x = y ∨ x = p G hfree hmin y := Iff.rfl

/-- There is an edge between two fibers if `x` is adjacent to either lift of
the second fiber. -/
def thirtyTwoFiberAdj (x y : Fin 32) : Prop :=
  G.Adj x y ∨ G.Adj x (p G hfree hmin y)

theorem thirtyTwoFiberAdj_left_antipode (x y : Fin 32) :
    thirtyTwoFiberAdj G hfree hmin (p G hfree hmin x) y ↔
      thirtyTwoFiberAdj G hfree hmin x y := by
  rw [thirtyTwoFiberAdj, thirtyTwoFiberAdj]
  have hcross := adj_thirtyTwoAntipode_iff G hfree hmin x y
  have hauto := thirtyTwoAntipode_adj_iff G hfree hmin x y
  constructor
  · rintro (h | h)
    · exact Or.inr (hcross.mpr h.symm)
    · exact Or.inl (hauto.mp h)
  · rintro (h | h)
    · exact Or.inr (hauto.mpr h)
    · exact Or.inl (hcross.mp h).symm

theorem thirtyTwoFiberAdj_right_antipode (x y : Fin 32) :
    thirtyTwoFiberAdj G hfree hmin x (p G hfree hmin y) ↔
      thirtyTwoFiberAdj G hfree hmin x y := by
  rw [thirtyTwoFiberAdj, thirtyTwoFiberAdj,
    show p G hfree hmin (p G hfree hmin y) = y from
      thirtyTwoAntipode_involutive G hfree hmin y]
  exact or_comm

theorem thirtyTwoFiberAdj_congr {x x' y y' : Fin 32}
    (hxx : (thirtyTwoAntipodeSetoid G hfree hmin : Fin 32 → Fin 32 → Prop) x x')
    (hyy : (thirtyTwoAntipodeSetoid G hfree hmin : Fin 32 → Fin 32 → Prop) y y') :
    thirtyTwoFiberAdj G hfree hmin x y ↔
      thirtyTwoFiberAdj G hfree hmin x' y' := by
  rcases hxx with rfl | hxx
  · rcases hyy with rfl | hyy
    · rfl
    · subst y
      exact thirtyTwoFiberAdj_right_antipode G hfree hmin x y'
  · subst x
    rcases hyy with rfl | hyy
    · exact thirtyTwoFiberAdj_left_antipode G hfree hmin x' y
    · subst y
      exact (thirtyTwoFiberAdj_left_antipode G hfree hmin x'
        (p G hfree hmin y')).trans
          (thirtyTwoFiberAdj_right_antipode G hfree hmin x' y')

/-- Adjacency on antipodal fibers. -/
def thirtyTwoQuotientAdj :
    ThirtyTwoQuotient G hfree hmin → ThirtyTwoQuotient G hfree hmin → Prop :=
  Quotient.lift₂ (fun x y => thirtyTwoFiberAdj G hfree hmin x y)
    (fun _ _ _ _ hx hy => propext
      (thirtyTwoFiberAdj_congr G hfree hmin hx hy))

theorem thirtyTwoQuotientAdj_mk (x y : Fin 32) :
    thirtyTwoQuotientAdj G hfree hmin
      (Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) x)
      (Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) y) ↔
        thirtyTwoFiberAdj G hfree hmin x y := Iff.rfl

/-- Every quotient fiber contains exactly its representative and its distinct
antipode. -/
theorem card_thirtyTwoQuotient_fiber (x : Fin 32) :
    Fintype.card {y : Fin 32 //
      Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) y =
        Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) x} = 2 := by
  rw [Fintype.card_subtype]
  have heq :
      Finset.univ.filter (fun y : Fin 32 =>
        Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) y =
          Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) x) =
        {x, p G hfree hmin x} := by
    ext y
    simp only [Finset.mem_filter, Finset.mem_univ, true_and,
      Finset.mem_insert, Finset.mem_singleton]
    rw [Quotient.eq]
    change (y = x ∨ y = p G hfree hmin x) ↔ _
    rfl
  have hnot : x ∉ ({p G hfree hmin x} : Finset (Fin 32)) := by
    rw [Finset.mem_singleton]
    exact (thirtyTwoAntipode_spec G hfree hmin x).1.symm
  rw [heq, Finset.card_insert_of_notMem hnot]
  simp

/-- The antipodal quotient has exactly 16 vertices. -/
theorem card_thirtyTwoQuotient :
    Fintype.card (ThirtyTwoQuotient G hfree hmin) = 16 := by
  let q : Fin 32 → ThirtyTwoQuotient G hfree hmin :=
    fun x => Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) x
  have hfiber : ∀ X : ThirtyTwoQuotient G hfree hmin,
      Fintype.card {x : Fin 32 // q x = X} = 2 := by
    intro X
    refine Quotient.inductionOn X ?_
    intro x
    exact card_thirtyTwoQuotient_fiber G hfree hmin x
  have hcard := Fintype.card_congr (Equiv.sigmaFiberEquiv q)
  rw [Fintype.card_sigma] at hcard
  simp_rw [hfiber] at hcard
  norm_num at hcard ⊢
  omega

/-- The canonical graph on the antipodal quotient. -/
def thirtyTwoQuotientGraph : SimpleGraph (ThirtyTwoQuotient G hfree hmin) where
  Adj := thirtyTwoQuotientAdj G hfree hmin
  symm := by
    constructor
    intro X Y hXY
    revert hXY
    refine Quotient.inductionOn₂ X Y ?_
    intro x y hxy
    rw [thirtyTwoQuotientAdj_mk] at hxy ⊢
    rcases hxy with hxy | hxp
    · exact Or.inl hxy.symm
    · exact Or.inr ((adj_thirtyTwoAntipode_iff G hfree hmin x y).mp hxp)
  loopless := by
    constructor
    intro X hXX
    revert hXX
    refine Quotient.inductionOn X ?_
    intro x hxx
    rw [thirtyTwoQuotientAdj_mk, thirtyTwoFiberAdj] at hxx
    rcases hxx with hloop | hant
    · exact G.loopless.irrefl x hloop
    · exact (thirtyTwoAntipode_ne_and_not_adj G
        ((mem_thirtyTwoAntipodes_iff G hfree hmin x
          (p G hfree hmin x)).2
            (thirtyTwoAntipode_spec G hfree hmin x))).2 hant

noncomputable instance thirtyTwoQuotientGraph.instDecidableAdj :
    DecidableRel (thirtyTwoQuotientGraph G hfree hmin).Adj :=
  Classical.decRel _

/-- The quotient neighborhood of `[x]` is exactly the image of the original
neighborhood of `x`. -/
theorem thirtyTwoQuotient_neighborFinset_mk (x : Fin 32) :
    (thirtyTwoQuotientGraph G hfree hmin).neighborFinset
        (Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) x) =
      Finset.image (fun y =>
        Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) y)
        (G.neighborFinset x) := by
  ext Y
  refine Quotient.inductionOn Y ?_
  intro y
  rw [SimpleGraph.mem_neighborFinset]
  change thirtyTwoQuotientAdj G hfree hmin
      (Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) x)
      (Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) y) ↔ _
  rw [thirtyTwoQuotientAdj_mk]
  constructor
  · rintro (hxy | hxpy)
    · rw [Finset.mem_image]
      exact ⟨y, (G.mem_neighborFinset x y).mpr hxy, rfl⟩
    · rw [Finset.mem_image]
      refine ⟨p G hfree hmin y,
        (G.mem_neighborFinset x (p G hfree hmin y)).mpr hxpy, ?_⟩
      apply Quotient.sound
      exact Or.inr rfl
  · intro himage
    rw [Finset.mem_image] at himage
    obtain ⟨z, hzx, hzy⟩ := himage
    rw [Quotient.eq] at hzy
    have hxz : G.Adj x z := (G.mem_neighborFinset x z).mp hzx
    rcases hzy with hzy | hzy
    · exact Or.inl (by simpa [hzy] using hxz)
    · exact Or.inr (by simpa [hzy] using hxz)

/-- Distinct neighbors of `x` lie in distinct antipodal fibers. -/
theorem quotient_mk_injOn_neighborFinset (x : Fin 32) :
    Set.InjOn
      (fun y => Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) y)
      (G.neighborFinset x) := by
  intro y hy z hz hyz
  rw [Quotient.eq] at hyz
  rcases hyz with hyz | hyz
  · exact hyz
  · exfalso
    have hxy : G.Adj x y := (G.mem_neighborFinset x y).mp hy
    have hxz : G.Adj x z := (G.mem_neighborFinset x z).mp hz
    have hcommon := (thirtyTwoAntipode_spec G hfree hmin z).2
    have hxmem : x ∈ G.neighborFinset z ∩
        G.neighborFinset (p G hfree hmin z) := by
      refine Finset.mem_inter.mpr
        ⟨(G.mem_neighborFinset z x).mpr hxz.symm, ?_⟩
      rw [← hyz]
      exact (G.mem_neighborFinset y x).mpr hxy.symm
    rw [Finset.card_eq_zero.mp hcommon] at hxmem
    exact Finset.notMem_empty _ hxmem

/-- The quotient graph is 6-regular. -/
theorem thirtyTwoQuotient_degree (X : ThirtyTwoQuotient G hfree hmin) :
    (thirtyTwoQuotientGraph G hfree hmin).degree X = 6 := by
  refine Quotient.inductionOn X ?_
  intro x
  rw [← SimpleGraph.card_neighborFinset_eq_degree,
    thirtyTwoQuotient_neighborFinset_mk]
  rw [Finset.card_image_iff.mpr
    (quotient_mk_injOn_neighborFinset G hfree hmin x)]
  rw [G.card_neighborFinset_eq_degree,
    degree_eq_six_of_thirtytwo_minDegree_six G hfree hmin x]

/-- Distinct quotient fibers have exactly two common neighbors. -/
theorem thirtyTwoQuotient_common_eq_two
    {X Y : ThirtyTwoQuotient G hfree hmin} (hXY : X ≠ Y) :
    ((thirtyTwoQuotientGraph G hfree hmin).neighborFinset X ∩
      (thirtyTwoQuotientGraph G hfree hmin).neighborFinset Y).card = 2 := by
  classical
  revert hXY
  refine Quotient.inductionOn₂ X Y ?_
  intro x y hXY
  let q : Fin 32 → ThirtyTwoQuotient G hfree hmin :=
    fun z => Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) z
  have hrel : ¬ (x = y ∨ x = p G hfree hmin y) := by
    intro h
    apply hXY
    exact Quotient.sound h
  have hxy : x ≠ y := fun h => hrel (Or.inl h)
  have hxpy : x ≠ p G hfree hmin y := fun h => hrel (Or.inr h)
  let A := G.neighborFinset x ∩ G.neighborFinset y
  let B := G.neighborFinset x ∩
    G.neighborFinset (p G hfree hmin y)
  have hAcard : A.card = 1 := by
    exact card_common_eq_one_of_ne_of_ne_antipode G hfree hmin hxy hxpy
  have hxpy_ne : x ≠ p G hfree hmin y := hxpy
  have hx_ne_ppy : x ≠ p G hfree hmin (p G hfree hmin y) := by
    intro h
    apply hxy
    exact h.trans (thirtyTwoAntipode_involutive G hfree hmin y)
  have hBcard : B.card = 1 := by
    exact card_common_eq_one_of_ne_of_ne_antipode G hfree hmin
      hxpy_ne hx_ne_ppy
  let C :=
    (thirtyTwoQuotientGraph G hfree hmin).neighborFinset (q x) ∩
      (thirtyTwoQuotientGraph G hfree hmin).neighborFinset (q y)
  let U := Finset.image q A ∪ Finset.image q B
  have hCU : C ⊆ U := by
    intro Z hZ
    refine Quotient.inductionOn Z ?_ hZ
    intro z hz
    have hzparts := Finset.mem_inter.mp hz
    have hxz : thirtyTwoFiberAdj G hfree hmin x z := by
      apply (thirtyTwoQuotientAdj_mk G hfree hmin x z).mp
      exact ((thirtyTwoQuotientGraph G hfree hmin).mem_neighborFinset
        (q x) (q z)).mp hzparts.1
    have hyz : thirtyTwoFiberAdj G hfree hmin y z := by
      apply (thirtyTwoQuotientAdj_mk G hfree hmin y z).mp
      exact ((thirtyTwoQuotientGraph G hfree hmin).mem_neighborFinset
        (q y) (q z)).mp hzparts.2
    change Quotient.mk (thirtyTwoAntipodeSetoid G hfree hmin) z ∈
      Finset.image q A ∪ Finset.image q B
    rw [Finset.mem_union]
    rcases hxz with hxz | hxpz <;> rcases hyz with hyz | hypz
    · left
      rw [Finset.mem_image]
      refine ⟨z, Finset.mem_inter.mpr
        ⟨(G.mem_neighborFinset x z).mpr hxz,
          (G.mem_neighborFinset y z).mpr hyz⟩, rfl⟩
    · right
      rw [Finset.mem_image]
      have hzpy : G.Adj z (p G hfree hmin y) :=
        (adj_thirtyTwoAntipode_iff G hfree hmin y z).mp hypz
      refine ⟨z, Finset.mem_inter.mpr
        ⟨(G.mem_neighborFinset x z).mpr hxz,
          (G.mem_neighborFinset (p G hfree hmin y) z).mpr hzpy.symm⟩, rfl⟩
    · right
      rw [Finset.mem_image]
      let z' := p G hfree hmin z
      have hz'x : G.Adj x z' := hxpz
      have hz'py : G.Adj (p G hfree hmin y) z' :=
        (thirtyTwoAntipode_adj_iff G hfree hmin y z).2 hyz
      refine ⟨z', Finset.mem_inter.mpr
        ⟨(G.mem_neighborFinset x z').mpr hz'x,
          (G.mem_neighborFinset (p G hfree hmin y) z').mpr hz'py⟩, ?_⟩
      apply Quotient.sound
      exact Or.inr rfl
    · left
      rw [Finset.mem_image]
      let z' := p G hfree hmin z
      have hz'x : G.Adj x z' := hxpz
      have hz'y : G.Adj y z' := hypz
      refine ⟨z', Finset.mem_inter.mpr
        ⟨(G.mem_neighborFinset x z').mpr hz'x,
          (G.mem_neighborFinset y z').mpr hz'y⟩, ?_⟩
      apply Quotient.sound
      exact Or.inr rfl
  have hupper : C.card ≤ 2 := by
    calc
      C.card ≤ U.card := Finset.card_le_card hCU
      _ ≤ (Finset.image q A).card + (Finset.image q B).card :=
        Finset.card_union_le _ _
      _ ≤ A.card + B.card := Nat.add_le_add Finset.card_image_le Finset.card_image_le
      _ = 2 := by rw [hAcard, hBcard]
  obtain ⟨a, ha⟩ := Finset.card_eq_one.mp hAcard
  obtain ⟨b, hb⟩ := Finset.card_eq_one.mp hBcard
  have haA : a ∈ A := by rw [ha]; simp
  have hbB : b ∈ B := by rw [hb]; simp
  have hquotAdj {u v : Fin 32} (huv : G.Adj u v) :
      (thirtyTwoQuotientGraph G hfree hmin).Adj (q u) (q v) := by
    apply (thirtyTwoQuotientAdj_mk G hfree hmin u v).2
    exact Or.inl huv
  have hquotAdjAnt {u v : Fin 32} (huv : G.Adj u (p G hfree hmin v)) :
      (thirtyTwoQuotientGraph G hfree hmin).Adj (q u) (q v) := by
    apply (thirtyTwoQuotientAdj_mk G hfree hmin u v).2
    exact Or.inr huv
  have hqaC : q a ∈ C := by
    change q a ∈
      (thirtyTwoQuotientGraph G hfree hmin).neighborFinset (q x) ∩
        (thirtyTwoQuotientGraph G hfree hmin).neighborFinset (q y)
    rw [Finset.mem_inter]
    have haa := Finset.mem_inter.mp haA
    exact ⟨((thirtyTwoQuotientGraph G hfree hmin).mem_neighborFinset
        (q x) (q a)).2 (hquotAdj ((G.mem_neighborFinset x a).mp haa.1)),
      ((thirtyTwoQuotientGraph G hfree hmin).mem_neighborFinset
        (q y) (q a)).2 (hquotAdj ((G.mem_neighborFinset y a).mp haa.2))⟩
  have hqbC : q b ∈ C := by
    change q b ∈
      (thirtyTwoQuotientGraph G hfree hmin).neighborFinset (q x) ∩
        (thirtyTwoQuotientGraph G hfree hmin).neighborFinset (q y)
    rw [Finset.mem_inter]
    have hbb := Finset.mem_inter.mp hbB
    have hxb : G.Adj x b := (G.mem_neighborFinset x b).mp hbb.1
    have hpyb : G.Adj (p G hfree hmin y) b :=
      (G.mem_neighborFinset (p G hfree hmin y) b).mp hbb.2
    have hypb : G.Adj y (p G hfree hmin b) :=
      (adj_thirtyTwoAntipode_iff G hfree hmin y b).2 hpyb.symm
    exact ⟨((thirtyTwoQuotientGraph G hfree hmin).mem_neighborFinset
        (q x) (q b)).2 (hquotAdj hxb),
      ((thirtyTwoQuotientGraph G hfree hmin).mem_neighborFinset
        (q y) (q b)).2 (hquotAdjAnt hypb)⟩
  have hqab : q a ≠ q b := by
    intro heq
    rw [Quotient.eq] at heq
    rcases heq with hab | hab
    · subst b
      have haa := Finset.mem_inter.mp haA
      have hbb := Finset.mem_inter.mp hbB
      have hzero := (thirtyTwoAntipode_spec G hfree hmin y).2
      have : a ∈ G.neighborFinset y ∩
          G.neighborFinset (p G hfree hmin y) :=
        Finset.mem_inter.mpr ⟨haa.2, hbb.2⟩
      rw [Finset.card_eq_zero.mp hzero] at this
      exact Finset.notMem_empty _ this
    · have haa := Finset.mem_inter.mp haA
      have hbb := Finset.mem_inter.mp hbB
      have hzero := (thirtyTwoAntipode_spec G hfree hmin b).2
      have : x ∈ G.neighborFinset b ∩
          G.neighborFinset (p G hfree hmin b) := by
        refine Finset.mem_inter.mpr
          ⟨(G.mem_neighborFinset b x).mpr
            ((G.mem_neighborFinset x b).mp hbb.1).symm, ?_⟩
        rw [← hab]
        exact (G.mem_neighborFinset a x).mpr
          ((G.mem_neighborFinset x a).mp haa.1).symm
      rw [Finset.card_eq_zero.mp hzero] at this
      exact Finset.notMem_empty _ this
  have hlower : 2 ≤ C.card := by
    have := Finset.one_lt_card.mpr ⟨q a, hqaC, q b, hqbC, hqab⟩
    omega
  change C.card = 2
  omega

end

end Erdos85
