/-
# Erdős Problem #335: Density Additivity Characterization

Characterize those A, B ⊆ ℕ with positive density such that
d(A + B) = d(A) + d(B).

## Key Context

- Usually d(A + B) ≥ min(d(A) + d(B), 1) (Plünnecke–Ruzsa bounds)
- Exact additivity d(A + B) = d(A) + d(B) is a strong structural condition
- Known examples: fractional part sets {n : {nθ} ∈ X} for irrational θ
- Open: do all such pairs arise from group rotation constructions?

## References

- [ErGr80] Erdős–Graham (1980), p. 51
- <https://erdosproblems.com/335>
-/

import Mathlib.Data.Real.Basic
import Mathlib.Order.Filter.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.Set.Finite.Lattice
import Mathlib.Topology.Basic
import Mathlib.Topology.Order.Basic
import Mathlib.Tactic

open Set Filter

/- ## Density Definitions -/

/-- The counting function: |A ∩ {1,...,N}|. -/
noncomputable def countingFn (A : Set ℕ) (N : ℕ) : ℕ :=
  Set.ncard (A ∩ Set.Icc 1 N)

/-- The asymptotic density of A ⊆ ℕ: lim_{N→∞} |A ∩ [1,N]| / N. -/
noncomputable def asympDensity (A : Set ℕ) : ℝ :=
  limUnder atTop (fun N => (countingFn A N : ℝ) / N)

/-- The density exists (the limit converges). -/
def DensityExists (A : Set ℕ) : Prop :=
  ∃ d : ℝ, Filter.Tendsto (fun N => (countingFn A N : ℝ) / N) atTop (nhds d)

/-- A set has positive density. -/
def HasPositiveDensity (A : Set ℕ) : Prop :=
  0 < asympDensity A

/- ## Sumset and Density Additivity -/

/-- The sumset A + B = {a + b : a ∈ A, b ∈ B}. -/
def Sumset (A B : Set ℕ) : Set ℕ :=
  {n | ∃ a ∈ A, ∃ b ∈ B, n = a + b}

/-- The key property: d(A + B) = d(A) + d(B).
    This is a strong structural constraint, much more restrictive than
    the general Plünnecke–Ruzsa inequality d(A + B) ≥ min(d(A) + d(B), 1). -/
def DensityAdditive (A B : Set ℕ) : Prop :=
  DensityExists A ∧ DensityExists B ∧ DensityExists (Sumset A B) ∧
  asympDensity (Sumset A B) = asympDensity A + asympDensity B

/- ## Known Construction: Fractional Parts -/

/-- Fractional part function. -/
noncomputable def frac (x : ℝ) : ℝ := x - ⌊x⌋

/-- Sets constructed via fractional parts of nθ:
    A = {n > 0 : {nθ} ∈ X} for a measurable X ⊆ [0,1). -/
def FractionalPartSet (θ : ℝ) (X : Set ℝ) : Set ℕ :=
  {n | n > 0 ∧ frac (n * θ) ∈ X}

/-- For irrational θ, the density of FractionalPartSet θ X equals μ(X)
    by Weyl's equidistribution theorem. -/
/-- The known construction: if X_A and X_B have additive measure on ℝ/ℤ
    (μ(X_A + X_B) = μ(X_A) + μ(X_B)), then the corresponding fractional
    part sets have additive density. -/
/- ## Main Conjecture -/

/-- **Erdős Problem #335** (OPEN): Are all density-additive pairs
    generated by group rotation constructions?

    Formally: if A, B ⊆ ℕ have positive density and d(A+B) = d(A) + d(B),
    must there exist a compact abelian group G, a group element g,
    and measurable sets X_A, X_B ⊆ G such that A and B are obtained
    from the orbit of g through X_A and X_B? -/
/- ## Basic Properties -/

/-- Density is non-negative (when the density exists). -/
theorem density_nonneg (A : Set ℕ) (hA : DensityExists A) : asympDensity A ≥ 0 := by
  obtain ⟨d, hd⟩ := hA
  rw [show asympDensity A = d from hd.limUnder_eq]
  exact ge_of_tendsto hd (Filter.eventually_atTop.mpr ⟨0, fun N _ =>
    div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)⟩)

/-- The counting function is at most N. -/
private lemma countingFn_le (A : Set ℕ) (N : ℕ) : countingFn A N ≤ N := by
  unfold countingFn
  calc Set.ncard (A ∩ Set.Icc 1 N)
      ≤ Set.ncard (Set.Icc 1 N) :=
        Set.ncard_le_ncard Set.inter_subset_right (Set.finite_Icc 1 N)
    _ ≤ N := by
        rw [Set.ncard_eq_toFinset_card']
        simp only [Set.toFinset_Icc, Nat.card_Icc]
        omega

/-- Density is at most 1. -/
theorem density_le_one (A : Set ℕ) (hA : DensityExists A) : asympDensity A ≤ 1 := by
  obtain ⟨d, hd⟩ := hA
  rw [show asympDensity A = d from hd.limUnder_eq]
  apply le_of_tendsto hd
  filter_upwards [Filter.eventually_ge_atTop 1] with N hN
  rw [div_le_one (by positivity : (0 : ℝ) < N)]
  exact_mod_cast countingFn_le A N

/-- If d(A + B) = d(A) + d(B), then d(A) + d(B) ≤ 1.
    Otherwise the sumset would have density > 1, a contradiction. -/
theorem additive_sum_le_one (A B : Set ℕ) :
    DensityAdditive A B → asympDensity A + asympDensity B ≤ 1 := by
  intro ⟨_, _, hAB_exists, heq⟩
  rw [← heq]
  exact density_le_one (Sumset A B) hAB_exists

/-- Density additivity implies the Plünnecke–Ruzsa bound is tight:
    d(A + B) = min(d(A) + d(B), 1). -/
theorem additive_implies_tight (A B : Set ℕ) (h : DensityAdditive A B) :
    asympDensity (Sumset A B) = min (asympDensity A + asympDensity B) 1 := by
  have hle := additive_sum_le_one A B h
  rw [h.2.2.2, min_eq_left hle]

/- ## Derived Structural Results -/

/-- If A is density-additive with itself, then d(A) ≤ 1/2.
    Since d(A + A) = d(A) + d(A) = 2·d(A) ≤ 1, we get d(A) ≤ 1/2. -/
theorem self_additive_density_le_half (A : Set ℕ) (h : DensityAdditive A A) :
    asympDensity A ≤ 1 / 2 := by
  have := additive_sum_le_one A A h
  linarith

/-- Sumset is monotone: A ⊆ A' and B ⊆ B' imply (A + B) ⊆ (A' + B'). -/
theorem Sumset_mono {A A' B B' : Set ℕ} (hA : A ⊆ A') (hB : B ⊆ B') :
    Sumset A B ⊆ Sumset A' B' := by
  intro n ⟨a, ha, b, hb, hn⟩
  exact ⟨a, hA ha, b, hB hb, hn⟩

/-- Sumset is commutative. -/
theorem Sumset_comm (A B : Set ℕ) : Sumset A B = Sumset B A := by
  ext n
  simp only [Sumset, Set.mem_setOf_eq]
  constructor
  · rintro ⟨a, ha, b, hb, hn⟩
    exact ⟨b, hb, a, ha, by omega⟩
  · rintro ⟨b, hb, a, ha, hn⟩
    exact ⟨a, ha, b, hb, by omega⟩

/-- Density additivity is symmetric: if d(A+B) = d(A) + d(B), then d(B+A) = d(B) + d(A). -/
theorem density_additive_comm (A B : Set ℕ) (h : DensityAdditive A B) :
    DensityAdditive B A := by
  obtain ⟨hA, hB, hAB, heq⟩ := h
  exact ⟨hB, hA, Sumset_comm B A ▸ hAB, by rw [Sumset_comm B A]; linarith⟩

/-- Density additivity with the Plünnecke–Ruzsa bound: additive pairs are
    extremal (they achieve the minimum possible sumset density). -/
theorem additive_achieves_lower_bound (A B : Set ℕ)
    (hA : DensityExists A) (hB : DensityExists B) (h : DensityAdditive A B) :
    asympDensity (Sumset A B) ≥ min (asympDensity A + asympDensity B) 1 := by
  rw [additive_implies_tight A B h]

/-- If both A and B have positive density and are density-additive,
    then their sumset also has positive density. -/
theorem density_additive_pos (A B : Set ℕ)
    (h : DensityAdditive A B) (hA : HasPositiveDensity A) (hB : HasPositiveDensity B) :
    HasPositiveDensity (Sumset A B) := by
  unfold HasPositiveDensity at *
  rw [h.2.2.2]
  linarith

/-- If one set has zero density in a density-additive pair,
    the sumset density equals the other set's density. -/
theorem density_additive_zero (A B : Set ℕ) (h : DensityAdditive A B)
    (hB : asympDensity B = 0) : asympDensity (Sumset A B) = asympDensity A := by
  rw [h.2.2.2, hB, add_zero]

/-- Sumset with the empty set is empty. -/
theorem Sumset_empty_left (B : Set ℕ) : Sumset ∅ B = ∅ := by
  ext n; simp [Sumset]

/-- Sumset with the empty set on the right is empty. -/
theorem Sumset_empty_right (A : Set ℕ) : Sumset A ∅ = ∅ := by
  ext n; simp [Sumset]

/- ## Deeper Structural Results -/

/-- Sumset is associative: (A + B) + C = A + (B + C). -/
theorem Sumset_assoc (A B C : Set ℕ) :
    Sumset (Sumset A B) C = Sumset A (Sumset B C) := by
  ext n
  simp only [Sumset, Set.mem_setOf_eq]
  constructor
  · rintro ⟨ab, ⟨a, ha, b, hb, rfl⟩, c, hc, hn⟩
    exact ⟨a, ha, b + c, ⟨b, hb, c, hc, rfl⟩, by omega⟩
  · rintro ⟨a, ha, bc, ⟨b, hb, c, hc, rfl⟩, hn⟩
    exact ⟨a + b, ⟨a, ha, b, hb, rfl⟩, c, hc, by omega⟩

/-- Sumset with the universal set contains all sufficiently large numbers.
    If a ∈ A, then for all n ≥ a, n ∈ Sumset A univ. -/
theorem Sumset_univ_right (A : Set ℕ) (a : ℕ) (ha : a ∈ A) (n : ℕ) (hn : a ≤ n) :
    n ∈ Sumset A Set.univ := by
  exact ⟨a, ha, n - a, Set.mem_univ _, by omega⟩

/-- Sumset is monotone in both arguments. -/
theorem Sumset_mono_left {A A' B : Set ℕ} (hA : A ⊆ A') :
    Sumset A B ⊆ Sumset A' B :=
  Sumset_mono hA (Set.Subset.refl B)

/-- Sumset is monotone in both arguments. -/
theorem Sumset_mono_right {A B B' : Set ℕ} (hB : B ⊆ B') :
    Sumset A B ⊆ Sumset A B' :=
  Sumset_mono (Set.Subset.refl A) hB

/-- In a density-additive pair, both sets have density at most 1. -/
theorem density_additive_parts_le_one (A B : Set ℕ) (h : DensityAdditive A B) :
    asympDensity A ≤ 1 ∧ asympDensity B ≤ 1 :=
  ⟨density_le_one A h.1, density_le_one B h.2.1⟩

/-- In a density-additive pair, both sets have non-negative density. -/
theorem density_additive_parts_nonneg (A B : Set ℕ) (h : DensityAdditive A B) :
    asympDensity A ≥ 0 ∧ asympDensity B ≥ 0 :=
  ⟨density_nonneg A h.1, density_nonneg B h.2.1⟩

/-- If d(A) + d(B) = 1 in a density-additive pair, the sumset has full density. -/
theorem density_additive_full (A B : Set ℕ) (h : DensityAdditive A B)
    (hfull : asympDensity A + asympDensity B = 1) :
    asympDensity (Sumset A B) = 1 := by
  rw [h.2.2.2, hfull]

/-- Density additivity with the empty set: d(A + ∅) = d(∅) + d(A) holds vacuously
    since ∅ has density 0 and A + ∅ = ∅. -/
theorem density_sumset_empty (A : Set ℕ) :
    Sumset A ∅ = ∅ ∧ Sumset ∅ A = ∅ :=
  ⟨Sumset_empty_right A, Sumset_empty_left A⟩

/-- Counting function is zero for the empty set. -/
theorem countingFn_empty (N : ℕ) : countingFn ∅ N = 0 := by
  simp [countingFn]

/-- Counting function is monotone in the set argument. -/
theorem countingFn_mono {A B : Set ℕ} (h : A ⊆ B) (N : ℕ) :
    countingFn A N ≤ countingFn B N := by
  unfold countingFn
  exact Set.ncard_le_ncard (Set.inter_subset_inter_left _ h)
    ((Set.finite_Icc 1 N).subset Set.inter_subset_right)

/-- Counting function is monotone in N when A is fixed. -/
theorem countingFn_mono_N (A : Set ℕ) {M N : ℕ} (h : M ≤ N) :
    countingFn A M ≤ countingFn A N := by
  unfold countingFn
  apply Set.ncard_le_ncard
  · exact Set.inter_subset_inter_right A (Set.Icc_subset_Icc_right h)
  · exact (Set.finite_Icc 1 N).subset Set.inter_subset_right

/-- The sumset of singletons is a singleton. -/
theorem Sumset_singleton (a b : ℕ) :
    Sumset {a} {b} = {a + b} := by
  ext n
  simp only [Sumset, Set.mem_setOf_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨x, rfl, y, rfl, rfl⟩; rfl
  · intro h; exact ⟨a, rfl, b, rfl, h⟩

/- ## Sumset Identity and Further Properties -/

/-- {0} is a right identity for sumsets: A + {0} = A. -/
theorem Sumset_zero_right (A : Set ℕ) : Sumset A {0} = A := by
  ext n; constructor
  · rintro ⟨a, ha, b, hb, rfl⟩
    rw [Set.mem_singleton_iff] at hb; subst hb; simpa
  · intro hn; exact ⟨n, hn, 0, rfl, by omega⟩

/-- {0} is a left identity for sumsets: {0} + A = A. -/
theorem Sumset_zero_left (A : Set ℕ) : Sumset {0} A = A := by
  rw [Sumset_comm]; exact Sumset_zero_right A

/-- Density additivity composes along a chain:
    if d(A+B) = d(A)+d(B) and d((A+B)+C) = d(A+B)+d(C),
    then d(A+B+C) = d(A)+d(B)+d(C). -/
theorem density_additive_chain (A B C : Set ℕ)
    (h1 : DensityAdditive A B) (h2 : DensityAdditive (Sumset A B) C) :
    asympDensity (Sumset (Sumset A B) C) =
      asympDensity A + asympDensity B + asympDensity C := by
  rw [h2.2.2.2, h1.2.2.2]

/-- In a density-additive pair, d(B) ≤ 1 - d(A). -/
theorem density_additive_complement_bound (A B : Set ℕ) (h : DensityAdditive A B) :
    asympDensity B ≤ 1 - asympDensity A := by
  have := additive_sum_le_one A B h
  linarith

/-- The double sumset A + A has density 2·d(A) when density-additive with itself. -/
theorem density_double_sumset (A : Set ℕ) (h : DensityAdditive A A) :
    asympDensity (Sumset A A) = 2 * asympDensity A := by
  rw [h.2.2.2]; ring
