/-
Erdős Problem #1110 — OQ-01: The multiplicative-monoid structure of power forms

Companion to `Erdos1110Problem.lean`. Erdős #1110 studies representability of
integers as sums of *power forms* `p^k q^l` (`IsPowerForm p q n := ∃ k l, n = p^k q^l`)
with no summand dividing another.

The parent file develops many representability results and two *single-base*
closure lemmas — `isPowerForm_mul_base_left` (`s ↦ s·p`) and
`isPowerForm_mul_base_right` (`s ↦ s·q`) — but not the underlying algebraic fact
that the power forms are a **multiplicative submonoid** of `ℕ`:

  * `isPowerForm_one`  — `1 = p^0 q^0` is a power form (the monoid identity);
  * `isPowerForm_mul`  — the product of two power forms is a power form
    (`p^k q^l · p^{k'} q^{l'} = p^{k+k'} q^{l+l'}`), the full closure that
    subsumes both single-base lemmas (`b = p` and `b = q`);
  * `isPowerForm_pow`  — a power of a power form is a power form;
  * `isPowerForm_prod` — a finite product of power forms is a power form.

These package the set `{p^k q^l}` as the submonoid generated by `{p, q}`, the clean
algebraic backdrop for the divisibility/representation arguments of #1110.

Verified, 0 axioms, 0 sorries, no `native_decide`.
-/

import Proofs.Erdos1110Problem

namespace Erdos1110

open Finset

/-- **`1` is a power form.** `1 = p^0 · q^0`, the identity of the multiplicative
monoid of power forms. -/
theorem isPowerForm_one (p q : ℕ) : IsPowerForm p q 1 :=
  ⟨0, 0, by simp⟩

/-- **Power forms are closed under multiplication.** If `a = p^k q^l` and
`b = p^{k'} q^{l'}` are both power forms, so is `a · b = p^{k+k'} q^{l+l'}`. This is
the multiplicative-submonoid closure; the parent's single-base lemmas
`isPowerForm_mul_base_left`/`_right` are the special cases `b = p` and `b = q`. -/
theorem isPowerForm_mul {p q a b : ℕ}
    (ha : IsPowerForm p q a) (hb : IsPowerForm p q b) :
    IsPowerForm p q (a * b) := by
  obtain ⟨k, l, rfl⟩ := ha
  obtain ⟨k', l', rfl⟩ := hb
  exact ⟨k + k', l + l', by rw [pow_add, pow_add]; ring⟩

/-- **Power forms are closed under taking powers.** If `a` is a power form then so is
`a^n`, by iterating `isPowerForm_mul` off the identity `isPowerForm_one`. -/
theorem isPowerForm_pow {p q a : ℕ} (ha : IsPowerForm p q a) (n : ℕ) :
    IsPowerForm p q (a ^ n) := by
  induction n with
  | zero => simpa using isPowerForm_one p q
  | succ n ih => rw [pow_succ]; exact isPowerForm_mul ih ha

/-- **Power forms are closed under finite products.** A finite product of power forms
is again a power form — the monoid-closure statement over an arbitrary index set,
proved from `isPowerForm_one` (empty product) and `isPowerForm_mul` (one step). -/
theorem isPowerForm_prod {p q : ℕ} {ι : Type*} (s : Finset ι) (f : ι → ℕ)
    (hf : ∀ i ∈ s, IsPowerForm p q (f i)) :
    IsPowerForm p q (∏ i ∈ s, f i) :=
  Finset.prod_induction f (IsPowerForm p q)
    (fun _ _ ha hb => isPowerForm_mul ha hb) (isPowerForm_one p q) hf

/-- The parent's `isPowerForm_mul_base_left` (`s ↦ s·p`) is the `b = p` instance of the
general closure `isPowerForm_mul`, since `p = p^1 q^0` is a power form. -/
theorem isPowerForm_mul_base_left' {p q s : ℕ} (h : IsPowerForm p q s) :
    IsPowerForm p q (s * p) :=
  isPowerForm_mul h ⟨1, 0, by simp⟩

/-- The parent's `isPowerForm_mul_base_right` (`s ↦ s·q`) is the `b = q` instance of the
general closure `isPowerForm_mul`, since `q = p^0 q^1` is a power form. -/
theorem isPowerForm_mul_base_right' {p q s : ℕ} (h : IsPowerForm p q s) :
    IsPowerForm p q (s * q) :=
  isPowerForm_mul h ⟨0, 1, by simp⟩

end Erdos1110
