import Proofs.Erdos85OrbitFactorExtraction
import Mathlib.Algebra.Algebra.Rat
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.Minpoly.Field

/-!
# Conjugation across the square subfield

The field/eigenvalue half of the orbit-parity program.  An algebraic element
`θ` that does not lie in the subfield `ℚ(θ²)` generated by its square has
minimal polynomial `X² - θ²` over that subfield, hence `-θ` is a Galois
conjugate of `θ` over `ℚ`.  Packaged in the sign-stability language of
`Erdos85OrbitFactorExtraction`: the minimal polynomial of such a `θ` is fixed
by the signed reflection `p(X) ↦ (-1)^(deg p) p(-X)`.

The contrapositive corollaries snap onto
`exists_irreducible_dvd_not_reflection_fixed_of_not_signStable`: any root of a
monic irreducible `ℚ`-polynomial that is *not* reflection-fixed must already
lie in the subfield generated by its square.
-/

open Polynomial IntermediateField

namespace Erdos85

noncomputable section

variable {L : Type*} [Field L] [CharZero L]

/-- The minimal polynomial over `ℚ(θ²)` of an element `θ` not lying in
`ℚ(θ²)` is exactly `X² - θ²`. -/
theorem minpoly_adjoin_sq_eq (θ : L) (hint : IsIntegral ℚ θ)
    (hnot : θ ∉ IntermediateField.adjoin ℚ {θ ^ 2}) :
    (X ^ 2 - C (⟨θ ^ 2, IntermediateField.subset_adjoin ℚ {θ ^ 2} rfl⟩ :
        IntermediateField.adjoin ℚ {θ ^ 2}) :
      Polynomial (IntermediateField.adjoin ℚ {θ ^ 2})) =
      minpoly (IntermediateField.adjoin ℚ {θ ^ 2}) θ := by
  set K := IntermediateField.adjoin ℚ {θ ^ 2} with hKdef
  have hmem : θ ^ 2 ∈ K := IntermediateField.subset_adjoin ℚ {θ ^ 2} rfl
  have hKint : IsIntegral K θ := hint.tower_top
  have hgmonic : (X ^ 2 - C (⟨θ ^ 2, hmem⟩ : K) : Polynomial K).Monic :=
    monic_X_pow_sub_C _ (by norm_num)
  have haevalθ :
      Polynomial.aeval θ (X ^ 2 - C (⟨θ ^ 2, hmem⟩ : K) : Polynomial K) = 0 := by
    simp only [map_sub, map_pow, aeval_X, aeval_C,
      IntermediateField.algebraMap_apply]
    exact sub_self (θ ^ 2)
  have hdvd : minpoly K θ ∣ (X ^ 2 - C (⟨θ ^ 2, hmem⟩ : K) : Polynomial K) :=
    minpoly.dvd K θ haevalθ
  have hge : 2 ≤ (minpoly K θ).natDegree := by
    rw [minpoly.two_le_natDegree_iff hKint]
    intro hθ
    obtain ⟨y, hy⟩ := RingHom.mem_range.mp hθ
    apply hnot
    rw [← hy, IntermediateField.algebraMap_apply]
    exact y.2
  exact eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hKint) hgmonic hdvd
    (by rw [natDegree_X_pow_sub_C]; exact hge)

/-- An algebraic element not lying in the subfield generated by its square
has its negation as a conjugate: `-θ` is a root of `minpoly ℚ θ`. -/
theorem aeval_neg_minpoly_eq_zero_of_not_mem_adjoin_sq
    (θ : L) (hint : IsIntegral ℚ θ)
    (hnot : θ ∉ IntermediateField.adjoin ℚ {θ ^ 2}) :
    Polynomial.aeval (-θ) (minpoly ℚ θ) = 0 := by
  set K := IntermediateField.adjoin ℚ {θ ^ 2} with hKdef
  have hmem : θ ^ 2 ∈ K := IntermediateField.subset_adjoin ℚ {θ ^ 2} rfl
  -- `-θ` is a root of `X² - θ²`, hence of `minpoly K θ`.
  have haevalneg :
      Polynomial.aeval (-θ) (X ^ 2 - C (⟨θ ^ 2, hmem⟩ : K) : Polynomial K) = 0 := by
    simp only [map_sub, map_pow, aeval_X, aeval_C,
      IntermediateField.algebraMap_apply]
    rw [neg_sq]
    exact sub_self (θ ^ 2)
  have hnegroot : Polynomial.aeval (-θ) (minpoly K θ) = 0 :=
    minpoly_adjoin_sq_eq θ hint hnot ▸ haevalneg
  -- Transfer along `minpoly K θ ∣ (minpoly ℚ θ).map (algebraMap ℚ K)`.
  have hdvd2 : minpoly K θ ∣ (minpoly ℚ θ).map (algebraMap ℚ K) :=
    minpoly.dvd_map_of_isScalarTower ℚ K θ
  have h0 : Polynomial.aeval (-θ) ((minpoly ℚ θ).map (algebraMap ℚ K)) = 0 :=
    zero_dvd_iff.mp (hnegroot ▸ map_dvd (Polynomial.aeval (-θ)) hdvd2)
  rwa [Polynomial.aeval_map_algebraMap] at h0

/-- Sign-stability packaging: the minimal polynomial of an element outside
the subfield generated by its square is fixed by the signed reflection. -/
theorem minpoly_signedReflection_eq_of_not_mem_adjoin_sq
    (θ : L) (hint : IsIntegral ℚ θ)
    (hnot : θ ∉ IntermediateField.adjoin ℚ {θ ^ 2}) :
    Polynomial.signedReflection (minpoly ℚ θ) = minpoly ℚ θ := by
  have hfmonic : (minpoly ℚ θ).Monic := minpoly.monic hint
  have hcompdeg :
      ((minpoly ℚ θ).comp (-X)).natDegree = (minpoly ℚ θ).natDegree := by
    rw [natDegree_comp, natDegree_neg, natDegree_X, mul_one]
  -- top coefficient of the signed reflection is `1`
  have hcoeff : (Polynomial.signedReflection (minpoly ℚ θ)).coeff
      (minpoly ℚ θ).natDegree = 1 := by
    unfold Polynomial.signedReflection
    rw [Polynomial.coeff_smul, Polynomial.coeff_comp_neg_X,
      hfmonic.coeff_natDegree, mul_one, smul_eq_mul, ← pow_add]
    exact Even.neg_one_pow ⟨_, rfl⟩
  have hdegle : (Polynomial.signedReflection (minpoly ℚ θ)).natDegree ≤
      (minpoly ℚ θ).natDegree := by
    unfold Polynomial.signedReflection
    exact le_trans (natDegree_smul_le _ _) (le_of_eq hcompdeg)
  have hdegeq : (Polynomial.signedReflection (minpoly ℚ θ)).natDegree =
      (minpoly ℚ θ).natDegree :=
    le_antisymm hdegle
      (le_natDegree_of_ne_zero (by rw [hcoeff]; exact one_ne_zero))
  have hhmonic : (Polynomial.signedReflection (minpoly ℚ θ)).Monic := by
    show (Polynomial.signedReflection (minpoly ℚ θ)).coeff
      (Polynomial.signedReflection (minpoly ℚ θ)).natDegree = 1
    rw [hdegeq]
    exact hcoeff
  -- `θ` is a root of the signed reflection, since `-θ` is a conjugate
  have hroot : Polynomial.aeval θ (Polynomial.signedReflection (minpoly ℚ θ)) = 0 := by
    unfold Polynomial.signedReflection
    rw [map_smul, Polynomial.aeval_comp]
    have hx : Polynomial.aeval θ (-X : Polynomial ℚ) = -θ := by simp
    rw [hx, aeval_neg_minpoly_eq_zero_of_not_mem_adjoin_sq θ hint hnot,
      smul_zero]
  have hdvd : minpoly ℚ θ ∣ Polynomial.signedReflection (minpoly ℚ θ) :=
    minpoly.dvd ℚ θ hroot
  exact eq_of_monic_of_dvd_of_natDegree_le hfmonic hhmonic hdvd
    (le_of_eq hdegeq)

/-- Contrapositive snap point: if the minimal polynomial of `θ` is *not*
reflection-fixed, then `θ` already lies in the subfield generated by its
square. -/
theorem mem_adjoin_sq_of_signedReflection_ne
    (θ : L) (hint : IsIntegral ℚ θ)
    (hne : Polynomial.signedReflection (minpoly ℚ θ) ≠ minpoly ℚ θ) :
    θ ∈ IntermediateField.adjoin ℚ {θ ^ 2} := by
  by_contra hnot
  exact hne (minpoly_signedReflection_eq_of_not_mem_adjoin_sq θ hint hnot)

/-- Bridge form for a monic irreducible factor: any root of a monic
irreducible `ℚ`-polynomial that is not reflection-fixed lies in the subfield
generated by its square.  This consumes the output shape of
`exists_irreducible_dvd_not_reflection_fixed_of_not_signStable`. -/
theorem mem_adjoin_sq_of_aeval_eq_zero_of_signedReflection_ne
    (f : Polynomial ℚ) (hf : Irreducible f) (hmonic : f.Monic)
    (hne : Polynomial.signedReflection f ≠ f)
    (θ : L) (hroot : Polynomial.aeval θ f = 0) :
    θ ∈ IntermediateField.adjoin ℚ {θ ^ 2} := by
  have hint : IsIntegral ℚ θ := ⟨f, hmonic, hroot⟩
  have hfeq : f = minpoly ℚ θ :=
    minpoly.eq_of_irreducible_of_monic hf hroot hmonic
  exact mem_adjoin_sq_of_signedReflection_ne θ hint (by rwa [← hfeq])

end

end Erdos85
