/-
Erdős Problem #1110 — OQ-01: The multiplicative-monoid structure of power forms

Companion to `Erdos1110Problem.lean`. Erdős #1110 studies representability of
integers as sums of *power forms* `p^k q^l` (`IsPowerForm p q n := ∃ k l, n = p^k q^l`)
with no summand dividing another.

The parent file develops many representability results and two *single-base*
closure lemmas — `isPowerForm_mul_base_left` (`s ↦ s·p`) and
`isPowerForm_mul_base_right` (`s ↦ s·q`) — but not the underlying algebraic fact
that the power forms are a **multiplicative submonoid** of `ℕ`:

  * `isPowerForm_one`  — `1 = p^0 q^0` is a power form (the monoid identity);
  * `isPowerForm_mul`  — the product of two power forms is a power form
    (`p^k q^l · p^{k'} q^{l'} = p^{k+k'} q^{l+l'}`), the full closure that
    subsumes both single-base lemmas (`b = p` and `b = q`);
  * `isPowerForm_pow`  — a power of a power form is a power form;
  * `isPowerForm_prod` — a finite product of power forms is a power form.

These package the set `{p^k q^l}` as the submonoid generated by `{p, q}`, the clean
algebraic backdrop for the divisibility/representation arguments of #1110.

We then make that identification exact against Mathlib's generated submonoid:

  * `powerFormSubmonoid`         — the power forms as a bundled `Submonoid ℕ`;
  * `powerFormSubmonoid_eq_closure` — it equals `Submonoid.closure {p, q}`;
  * `isPowerForm_iff_mem_closure`   — `IsPowerForm p q n ↔ n ∈ Submonoid.closure {p, q}`.

Verified, 0 axioms, 0 sorries, no `native_decide`.
-/

import Proofs.Erdos1110Problem

namespace Erdos1110

open Finset

/-- **`1` is a power form.** `1 = p^0 · q^0`, the identity of the multiplicative
monoid of power forms. -/
theorem isPowerForm_one (p q : ℕ) : IsPowerForm p q 1 :=
  ⟨0, 0, by simp⟩

/-- **Power forms are closed under multiplication.** If `a = p^k q^l` and
`b = p^{k'} q^{l'}` are both power forms, so is `a · b = p^{k+k'} q^{l+l'}`. This is
the multiplicative-submonoid closure; the parent's single-base lemmas
`isPowerForm_mul_base_left`/`_right` are the special cases `b = p` and `b = q`. -/
theorem isPowerForm_mul {p q a b : ℕ}
    (ha : IsPowerForm p q a) (hb : IsPowerForm p q b) :
    IsPowerForm p q (a * b) := by
  obtain ⟨k, l, rfl⟩ := ha
  obtain ⟨k', l', rfl⟩ := hb
  exact ⟨k + k', l + l', by rw [pow_add, pow_add]; ring⟩

/-- **Power forms are closed under taking powers.** If `a` is a power form then so is
`a^n`, by iterating `isPowerForm_mul` off the identity `isPowerForm_one`. -/
theorem isPowerForm_pow {p q a : ℕ} (ha : IsPowerForm p q a) (n : ℕ) :
    IsPowerForm p q (a ^ n) := by
  induction n with
  | zero => simpa using isPowerForm_one p q
  | succ n ih => rw [pow_succ]; exact isPowerForm_mul ih ha

/-- **Power forms are closed under finite products.** A finite product of power forms
is again a power form — the monoid-closure statement over an arbitrary index set,
proved from `isPowerForm_one` (empty product) and `isPowerForm_mul` (one step). -/
theorem isPowerForm_prod {p q : ℕ} {ι : Type*} (s : Finset ι) (f : ι → ℕ)
    (hf : ∀ i ∈ s, IsPowerForm p q (f i)) :
    IsPowerForm p q (∏ i ∈ s, f i) :=
  Finset.prod_induction f (IsPowerForm p q)
    (fun _ _ ha hb => isPowerForm_mul ha hb) (isPowerForm_one p q) hf

/-- The parent's `isPowerForm_mul_base_left` (`s ↦ s·p`) is the `b = p` instance of the
general closure `isPowerForm_mul`, since `p = p^1 q^0` is a power form. -/
theorem isPowerForm_mul_base_left' {p q s : ℕ} (h : IsPowerForm p q s) :
    IsPowerForm p q (s * p) :=
  isPowerForm_mul h ⟨1, 0, by simp⟩

/-- The parent's `isPowerForm_mul_base_right` (`s ↦ s·q`) is the `b = q` instance of the
general closure `isPowerForm_mul`, since `q = p^0 q^1` is a power form. -/
theorem isPowerForm_mul_base_right' {p q s : ℕ} (h : IsPowerForm p q s) :
    IsPowerForm p q (s * q) :=
  isPowerForm_mul h ⟨0, 1, by simp⟩

/-! ### Identification with the concrete generated submonoid

The lemmas above (`isPowerForm_one`, `isPowerForm_mul`) say the power-form predicate
carves out a submonoid of `(ℕ, ×)`. We now *name* that submonoid and prove it is
exactly Mathlib's `Submonoid.closure {p, q}` — the submonoid generated by the two
bases. This turns the informal statement "`{p^k q^l}` is the submonoid generated by
`{p, q}`" (used throughout the parent's divisibility arguments) into a checked
identity, and lets the whole `Submonoid` API be reused for power forms. -/

/-- **The power forms as a submonoid of `(ℕ, ×)`.** Carrier `{n | IsPowerForm p q n}`;
the monoid axioms are `isPowerForm_one` (identity) and `isPowerForm_mul` (closure). -/
def powerFormSubmonoid (p q : ℕ) : Submonoid ℕ where
  carrier := {n | IsPowerForm p q n}
  one_mem' := isPowerForm_one p q
  mul_mem' := fun ha hb => isPowerForm_mul ha hb

@[simp] theorem mem_powerFormSubmonoid {p q n : ℕ} :
    n ∈ powerFormSubmonoid p q ↔ IsPowerForm p q n := Iff.rfl

/-- **The power-form submonoid is the submonoid generated by `{p, q}`.** Both bases are
power forms (`p = p^1 q^0`, `q = p^0 q^1`), so `Submonoid.closure {p,q}` lands inside
the power forms; conversely `p^k q^l ∈ closure {p,q}` by `pow_mem`/`mul_mem`. This is the
precise sense in which `{p^k q^l}` is "the multiplicative submonoid generated by
`{p, q}`". -/
theorem powerFormSubmonoid_eq_closure (p q : ℕ) :
    powerFormSubmonoid p q = Submonoid.closure ({p, q} : Set ℕ) := by
  apply le_antisymm
  · intro n hn
    obtain ⟨k, l, rfl⟩ := hn
    have hp : p ∈ Submonoid.closure ({p, q} : Set ℕ) :=
      Submonoid.subset_closure (by simp)
    have hq : q ∈ Submonoid.closure ({p, q} : Set ℕ) :=
      Submonoid.subset_closure (by simp)
    exact mul_mem (pow_mem hp k) (pow_mem hq l)
  · rw [Submonoid.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact ⟨1, 0, by simp⟩
    · exact ⟨0, 1, by simp⟩

/-- **`IsPowerForm` is membership in the generated submonoid.** The predicate form of
`powerFormSubmonoid_eq_closure`: `n` is a power form `p^k q^l` iff `n` lies in the
submonoid of `ℕ` generated by `{p, q}`. -/
theorem isPowerForm_iff_mem_closure (p q n : ℕ) :
    IsPowerForm p q n ↔ n ∈ Submonoid.closure ({p, q} : Set ℕ) := by
  rw [← powerFormSubmonoid_eq_closure]
  exact mem_powerFormSubmonoid.symm

/-- **The first base lies in the power-form submonoid.** `p = p^1 q^0`, one of the two
generators identified by `powerFormSubmonoid_eq_closure`. -/
theorem self_mem_powerFormSubmonoid_left (p q : ℕ) :
    p ∈ powerFormSubmonoid p q := ⟨1, 0, by simp⟩

/-- **The second base lies in the power-form submonoid.** `q = p^0 q^1`, the other
generator. -/
theorem self_mem_powerFormSubmonoid_right (p q : ℕ) :
    q ∈ powerFormSubmonoid p q := ⟨0, 1, by simp⟩

/-- **Universal property of the power-form submonoid.** `powerFormSubmonoid p q` is the
*smallest* submonoid of `(ℕ, ×)` containing both bases: it is `≤ S` exactly when `S`
already contains `p` and `q`. Mirrors `Submonoid.closure_le` through the identification
`powerFormSubmonoid_eq_closure`, and reduces any "every power form lies in `S`" goal to the
two base facts `p ∈ S`, `q ∈ S`. -/
theorem powerFormSubmonoid_le_iff {p q : ℕ} {S : Submonoid ℕ} :
    powerFormSubmonoid p q ≤ S ↔ p ∈ S ∧ q ∈ S := by
  rw [powerFormSubmonoid_eq_closure, Submonoid.closure_le]
  constructor
  · intro h
    exact ⟨h (by simp), h (by simp)⟩
  · rintro ⟨hp, hq⟩ x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact hp
    · exact hq

/-! ### The divisibility order on power forms (distinct prime bases)

For **distinct primes** `p ≠ q`, the exponent pair `(k, l)` of a power form
`p^k q^l` is unique (unique factorization), and divisibility of power forms is
exactly the product order on the exponents:

  `p^k q^l ∣ p^{k'} q^{l'} ↔ k ≤ k' ∧ l ≤ l'`.

Equivalently `(k, l) ↦ p^k q^l` is an order isomorphism from `(ℕ², ≤)` onto the
power forms under divisibility. This is the structural fact behind #1110's
central *antichain* hypothesis — "no summand divides another" — since it turns the
divisibility test on power-form summands into a coordinatewise comparison of
exponent vectors. The two prime-exponent readouts `factorization_powerForm_left`
and `factorization_powerForm_right` extract `k` and `l` from `p^k q^l`. -/

/-- **The `p`-adic exponent of a power form.** For distinct primes `p ≠ q`, the
`p`-factorization of `p^k q^l` is exactly `k` (the `q^l` factor contributes nothing
at `p`). -/
theorem factorization_powerForm_left {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p ≠ q) (k l : ℕ) : (p ^ k * q ^ l).factorization p = k := by
  have hp0 : p ^ k ≠ 0 := pow_ne_zero k hp.pos.ne'
  have hq0 : q ^ l ≠ 0 := pow_ne_zero l hq.pos.ne'
  rw [Nat.factorization_mul hp0 hq0, Finsupp.add_apply, hp.factorization_pow,
      hq.factorization_pow, Finsupp.single_eq_same,
      Finsupp.single_eq_of_ne (Ne.symm hpq), add_zero]

/-- **The `q`-adic exponent of a power form.** For distinct primes `p ≠ q`, the
`q`-factorization of `p^k q^l` is exactly `l`. -/
theorem factorization_powerForm_right {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p ≠ q) (k l : ℕ) : (p ^ k * q ^ l).factorization q = l := by
  have hp0 : p ^ k ≠ 0 := pow_ne_zero k hp.pos.ne'
  have hq0 : q ^ l ≠ 0 := pow_ne_zero l hq.pos.ne'
  rw [Nat.factorization_mul hp0 hq0, Finsupp.add_apply, hp.factorization_pow,
      hq.factorization_pow, Finsupp.single_eq_of_ne hpq, Finsupp.single_eq_same,
      zero_add]

/-- **Divisibility of power forms is the product order on exponents.** For distinct
primes `p ≠ q`,

  `p^k q^l ∣ p^{k'} q^{l'} ↔ k ≤ k' ∧ l ≤ l'`.

The `←` direction is `mul_dvd_mul` of `pow_dvd_pow`; the `→` direction reads the two
prime exponents off both sides via `factorization_le_iff_dvd`. -/
theorem powerForm_dvd_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    p ^ k * q ^ l ∣ p ^ k' * q ^ l' ↔ k ≤ k' ∧ l ≤ l' := by
  constructor
  · intro h
    have hp0 : p ^ k * q ^ l ≠ 0 :=
      mul_ne_zero (pow_ne_zero k hp.pos.ne') (pow_ne_zero l hq.pos.ne')
    have hn0 : p ^ k' * q ^ l' ≠ 0 :=
      mul_ne_zero (pow_ne_zero k' hp.pos.ne') (pow_ne_zero l' hq.pos.ne')
    have hle := (Nat.factorization_le_iff_dvd hp0 hn0).mpr h
    rw [Finsupp.le_def] at hle
    refine ⟨?_, ?_⟩
    · have hpk := hle p
      simpa only [factorization_powerForm_left hp hq hpq] using hpk
    · have hql := hle q
      simpa only [factorization_powerForm_right hp hq hpq] using hql
  · rintro ⟨hk, hl⟩
    exact mul_dvd_mul (pow_dvd_pow p hk) (pow_dvd_pow q hl)

/-- **Unique exponents.** For distinct primes `p ≠ q`, equal power forms have equal
exponent pairs: `p^k q^l = p^{k'} q^{l'} → k = k' ∧ l = l'`. Hence `(k, l) ↦ p^k q^l`
is injective, and the power-form submonoid is freely generated (as a commutative
monoid) by the two bases. -/
theorem powerForm_exponents_unique {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p ≠ q) {k l k' l' : ℕ} (h : p ^ k * q ^ l = p ^ k' * q ^ l') :
    k = k' ∧ l = l' := by
  refine ⟨?_, ?_⟩
  · have := congrArg (fun n => n.factorization p) h
    simpa only [factorization_powerForm_left hp hq hpq] using this
  · have := congrArg (fun n => n.factorization q) h
    simpa only [factorization_powerForm_right hp hq hpq] using this

/-- **Antichain criterion — the "no summand divides another" condition of #1110.**
For distinct primes `p ≠ q`, two power forms are mutually non-dividing exactly when their
exponent pairs are incomparable in the product order on `ℕ²`:

    ¬(p^k q^l ∣ p^{k'} q^{l'}) ∧ ¬(p^{k'} q^{l'} ∣ p^k q^l)
      ↔ ¬(k ≤ k' ∧ l ≤ l') ∧ ¬(k' ≤ k ∧ l' ≤ l).

This is the divisibility-antichain backbone of Erdős #1110's representation hypothesis
(sums of power forms in which *no summand divides another*): the exponent map
`(k, l) ↦ p^k q^l` sends `≤`-antichains of `ℕ²` to `∣`-antichains of the power forms.
Both directions are the double application of `powerForm_dvd_iff`. -/
theorem powerForm_incomparable_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    (¬ p ^ k * q ^ l ∣ p ^ k' * q ^ l' ∧ ¬ p ^ k' * q ^ l' ∣ p ^ k * q ^ l)
      ↔ (¬ (k ≤ k' ∧ l ≤ l') ∧ ¬ (k' ≤ k ∧ l' ≤ l)) := by
  rw [powerForm_dvd_iff hp hq hpq, powerForm_dvd_iff hp hq hpq]

/-! ### Closure under the divisibility lattice: divisors, `gcd` and `lcm`

The divisibility order on power forms (`powerForm_dvd_iff`) is the product order on
exponent pairs, which is a lattice with `min`/`max` as meet/join. The following lemmas
show the power-form set is *closed* under the corresponding arithmetic operations:
every divisor of a power form is a power form, and hence power forms are closed under
`Nat.gcd` and `Nat.lcm`. This completes the picture of `{p^k q^l}` (for prime bases) as a
**sublattice** of `(ℕ, ∣)` on top of its submonoid structure — the natural home for
Erdős #1110's divisibility/antichain arguments. -/

/-- **Divisors of a power form are power forms.** For prime bases `p, q`, if `n = p^k q^l`
is a power form and `d ∣ n`, then `d = p^a q^b` for some `a ≤ k`, `b ≤ l`, hence a power
form. Since `ℕ` is a decomposition monoid, `d` splits as `d₁ d₂` with `d₁ ∣ p^k`,
`d₂ ∣ q^l`; each factor of a prime power is a prime power (`Nat.dvd_prime_pow`). No
distinctness of `p, q` is needed. -/
theorem isPowerForm_of_dvd {p q d n : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hn : IsPowerForm p q n) (hd : d ∣ n) : IsPowerForm p q d := by
  obtain ⟨k, l, rfl⟩ := hn
  obtain ⟨d₁, d₂, hd₁, hd₂, rfl⟩ := exists_dvd_and_dvd_of_dvd_mul hd
  obtain ⟨a, _, rfl⟩ := (Nat.dvd_prime_pow hp).mp hd₁
  obtain ⟨b, _, rfl⟩ := (Nat.dvd_prime_pow hq).mp hd₂
  exact ⟨a, b, rfl⟩

/-- **Power forms are closed under `gcd`.** For prime bases `p, q`, the `gcd` of a power
form `m` with any `n` is a power form, because `Nat.gcd m n ∣ m`. (The meet of two power
forms in the divisibility order.) -/
theorem isPowerForm_gcd {p q m : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hm : IsPowerForm p q m) (n : ℕ) : IsPowerForm p q (Nat.gcd m n) :=
  isPowerForm_of_dvd hp hq hm (Nat.gcd_dvd_left m n)

/-- **Power forms are closed under `lcm`.** For prime bases `p, q`, the `lcm` of two power
forms is a power form: `Nat.lcm m n ∣ m * n`, and `m * n` is a power form by
`isPowerForm_mul`. (The join of two power forms in the divisibility order.) -/
theorem isPowerForm_lcm {p q m n : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hm : IsPowerForm p q m) (hn : IsPowerForm p q n) : IsPowerForm p q (Nat.lcm m n) :=
  isPowerForm_of_dvd hp hq (isPowerForm_mul hm hn) (Nat.lcm_dvd_mul m n)

end Erdos1110
