import Proofs.Erdos85RealCyclotomicNormSquare
import Mathlib.NumberTheory.Cyclotomic.Gal

/-!
# The real cyclotomic subfield has index two

For a primitive root `z` of order at least three, this file constructs the
inversion automorphism of `ℚ(z)`, proves that `z` is not contained in
`ℚ(z + z⁻¹)`, and deduces that the latter subfield has index two.
-/

open Polynomial IntermediateField

namespace Erdos85

noncomputable section

variable {L : Type*} [Field L] [CharZero L]

private theorem primitiveRoot_ne_inv {ell : ℕ} {z : L}
    (hz : IsPrimitiveRoot z ell) (hell : 3 ≤ ell) : z ≠ z⁻¹ := by
  intro h
  have hzsq : z ^ 2 = 1 := by
    rw [pow_two]
    nth_rewrite 1 [h]
    rw [inv_mul_cancel₀]
    exact hz.ne_zero (Nat.ne_of_gt (lt_of_lt_of_le (by norm_num) hell))
  have hdvd : ell ∣ 2 := hz.dvd_of_pow_eq_one 2 hzsq
  exact (not_le_of_gt (Nat.lt_of_lt_of_le (by norm_num) hell)) (Nat.le_of_dvd (by norm_num) hdvd)

/-- In a cyclotomic extension generated by a primitive root, that root does
not belong to the subfield generated by its real trace. -/
theorem primitiveRoot_not_mem_adjoin_add_inv_of_isCyclotomicExtension
    {K : Type*} [Field K] [CharZero K] {ell : ℕ} {z : K}
    (hz : IsPrimitiveRoot z ell) (hell : 3 ≤ ell)
    [IsCyclotomicExtension {ell} ℚ K] :
    z ∉ IntermediateField.adjoin ℚ {z + z⁻¹} := by
  letI : NeZero ell := ⟨Nat.ne_of_gt (lt_of_lt_of_le (by norm_num) hell)⟩
  have hmp : minpoly ℚ (hz.powerBasis ℚ).gen =
      minpoly ℚ (hz.inv.powerBasis ℚ).gen := by
    simp only [IsPrimitiveRoot.powerBasis_gen]
    exact (hz.minpoly_eq_cyclotomic_of_irreducible
      (Polynomial.cyclotomic.irreducible_rat (NeZero.pos ell))).symm.trans
        (hz.inv.minpoly_eq_cyclotomic_of_irreducible
          (Polynomial.cyclotomic.irreducible_rat (NeZero.pos ell)))
  let σ : K ≃ₐ[ℚ] K :=
    (hz.powerBasis ℚ).equivOfMinpoly (hz.inv.powerBasis ℚ) hmp
  have hσz : σ z = z⁻¹ := by
    simpa [σ, IsPrimitiveRoot.powerBasis_gen] using
      (hz.powerBasis ℚ).equivOfMinpoly_gen (hz.inv.powerBasis ℚ) hmp
  intro hmem
  have hfix_all (x : K) (hxmem : x ∈ IntermediateField.adjoin ℚ {z + z⁻¹}) :
      σ x = x := by
    induction hxmem using IntermediateField.adjoin_induction with
    | mem x hx =>
        rw [Set.mem_singleton_iff] at hx
        subst x
        simp [hσz, add_comm]
    | algebraMap q => exact σ.commutes q
    | add x y _ _ hx hy => simp [hx, hy]
    | inv x _ hx => simp [hx]
    | mul x y _ _ hx hy => simp [hx, hy]
  have hfix : σ z = z := hfix_all z hmem
  exact primitiveRoot_ne_inv hz hell (hfix.symm.trans hσz)

/-- The subfield generated by `z + z⁻¹` has index two in a cyclotomic field
generated by a primitive root `z` of order at least three. -/
theorem finrank_adjoin_add_inv_eq_two_of_isCyclotomicExtension
    {K : Type*} [Field K] [CharZero K] {ell : ℕ} {z : K}
    (hz : IsPrimitiveRoot z ell) (hell : 3 ≤ ell)
    [IsCyclotomicExtension {ell} ℚ K] :
    Module.finrank (IntermediateField.adjoin ℚ {z + z⁻¹}) K = 2 := by
  let E := IntermediateField.adjoin ℚ {z + z⁻¹}
  let μ : E := ⟨z + z⁻¹, IntermediateField.subset_adjoin ℚ _ rfl⟩
  have hnot : z ∉ E :=
    primitiveRoot_not_mem_adjoin_add_inv_of_isCyclotomicExtension hz hell
  have hzint : IsIntegral E z :=
    (hz.isIntegral (lt_of_lt_of_le (by norm_num) hell)).tower_top
  let f : Polynomial E := X ^ 2 - C μ * X + 1
  have hfmonic : f.Monic := by
    dsimp [f]
    monicity
    all_goals norm_num [max_def]
  have hfeval : Polynomial.aeval z f = 0 := by
    simp only [f, map_add, map_sub, map_mul, map_pow, aeval_X, aeval_C,
      map_one, IntermediateField.algebraMap_apply]
    dsimp [μ]
    field_simp [hz.ne_zero (Nat.ne_of_gt (lt_of_lt_of_le (by norm_num) hell))]
    ring
  have hfdeg : f.natDegree = 2 := by
    dsimp [f]
    compute_degree
    all_goals norm_num [max_def]
  have hmin : f = minpoly E z := by
    have hdvd : minpoly E z ∣ f := minpoly.dvd E z hfeval
    have hdeg : 2 ≤ (minpoly E z).natDegree := by
      rw [minpoly.two_le_natDegree_iff hzint]
      intro hzrange
      obtain ⟨x, hx⟩ := RingHom.mem_range.mp hzrange
      apply hnot
      rw [← hx, IntermediateField.algebraMap_apply]
      exact x.2
    exact eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hzint) hfmonic hdvd
      (by simpa [hfdeg] using hdeg)
  have htop : IntermediateField.adjoin E {z} = ⊤ := by
    apply le_antisymm le_top
    intro x hx
    have hz_top : IntermediateField.adjoin ℚ ({z} : Set K) = ⊤ := by
      letI : NeZero ell := ⟨Nat.ne_of_gt (lt_of_lt_of_le (by norm_num) hell)⟩
      exact IntermediateField.adjoin_eq_top_of_algebra ℚ _
        (IsCyclotomicExtension.adjoin_primitive_root_eq_top (A := ℚ) hz)
    have hxQ : x ∈ IntermediateField.adjoin ℚ ({z} : Set K) := by
      rw [hz_top]
      trivial
    have hall (y : K) (hyQ : y ∈ IntermediateField.adjoin ℚ ({z} : Set K)) :
        y ∈ IntermediateField.adjoin E {z} := by
      induction hyQ using IntermediateField.adjoin_induction with
      | mem y hy =>
          rw [Set.mem_singleton_iff] at hy
          subst y
          exact IntermediateField.subset_adjoin E {z} rfl
      | algebraMap q =>
          change algebraMap E K (⟨algebraMap ℚ K q,
            IntermediateField.algebraMap_mem E q⟩ : E) ∈ IntermediateField.adjoin E {z}
          exact IntermediateField.algebraMap_mem _ _
      | add x y _ _ hx hy => exact IntermediateField.add_mem _ hx hy
      | inv x _ hx => exact IntermediateField.inv_mem _ hx
      | mul x y _ _ hx hy => exact IntermediateField.mul_mem _ hx hy
    exact hall x hxQ
  rw [← IntermediateField.finrank_top', ← htop,
    IntermediateField.adjoin.finrank hzint, ← hmin, hfdeg]

end

end Erdos85
