/-
Erdős Problem #1110 — OQ-01: The multiplicative-monoid structure of power forms

Companion to `Erdos1110Problem.lean`. Erdős #1110 studies representability of
integers as sums of *power forms* `p^k q^l` (`IsPowerForm p q n := ∃ k l, n = p^k q^l`)
with no summand dividing another.

The parent file develops many representability results and two *single-base*
closure lemmas — `isPowerForm_mul_base_left` (`s ↦ s·p`) and
`isPowerForm_mul_base_right` (`s ↦ s·q`) — but not the underlying algebraic fact
that the power forms are a **multiplicative submonoid** of `ℕ`:

  * `isPowerForm_one`  — `1 = p^0 q^0` is a power form (the monoid identity);
  * `isPowerForm_mul`  — the product of two power forms is a power form
    (`p^k q^l · p^{k'} q^{l'} = p^{k+k'} q^{l+l'}`), the full closure that
    subsumes both single-base lemmas (`b = p` and `b = q`);
  * `isPowerForm_pow`  — a power of a power form is a power form;
  * `isPowerForm_prod` — a finite product of power forms is a power form.

These package the set `{p^k q^l}` as the submonoid generated by `{p, q}`, the clean
algebraic backdrop for the divisibility/representation arguments of #1110.

We then make that identification exact against Mathlib's generated submonoid:

  * `powerFormSubmonoid`         — the power forms as a bundled `Submonoid ℕ`;
  * `powerFormSubmonoid_eq_closure` — it equals `Submonoid.closure {p, q}`;
  * `isPowerForm_iff_mem_closure`   — `IsPowerForm p q n ↔ n ∈ Submonoid.closure {p, q}`.

Verified, 0 axioms, 0 sorries, no `native_decide`.
-/

import Proofs.Erdos1110Problem

namespace Erdos1110

open Finset

/-- **`1` is a power form.** `1 = p^0 · q^0`, the identity of the multiplicative
monoid of power forms. -/
theorem isPowerForm_one (p q : ℕ) : IsPowerForm p q 1 :=
  ⟨0, 0, by simp⟩

/-- **Power forms are closed under multiplication.** If `a = p^k q^l` and
`b = p^{k'} q^{l'}` are both power forms, so is `a · b = p^{k+k'} q^{l+l'}`. This is
the multiplicative-submonoid closure; the parent's single-base lemmas
`isPowerForm_mul_base_left`/`_right` are the special cases `b = p` and `b = q`. -/
theorem isPowerForm_mul {p q a b : ℕ}
    (ha : IsPowerForm p q a) (hb : IsPowerForm p q b) :
    IsPowerForm p q (a * b) := by
  obtain ⟨k, l, rfl⟩ := ha
  obtain ⟨k', l', rfl⟩ := hb
  exact ⟨k + k', l + l', by rw [pow_add, pow_add]; ring⟩

/-- **Power forms are closed under taking powers.** If `a` is a power form then so is
`a^n`, by iterating `isPowerForm_mul` off the identity `isPowerForm_one`. -/
theorem isPowerForm_pow {p q a : ℕ} (ha : IsPowerForm p q a) (n : ℕ) :
    IsPowerForm p q (a ^ n) := by
  induction n with
  | zero => simpa using isPowerForm_one p q
  | succ n ih => rw [pow_succ]; exact isPowerForm_mul ih ha

/-- **Power forms are closed under finite products.** A finite product of power forms
is again a power form — the monoid-closure statement over an arbitrary index set,
proved from `isPowerForm_one` (empty product) and `isPowerForm_mul` (one step). -/
theorem isPowerForm_prod {p q : ℕ} {ι : Type*} (s : Finset ι) (f : ι → ℕ)
    (hf : ∀ i ∈ s, IsPowerForm p q (f i)) :
    IsPowerForm p q (∏ i ∈ s, f i) :=
  Finset.prod_induction f (IsPowerForm p q)
    (fun _ _ ha hb => isPowerForm_mul ha hb) (isPowerForm_one p q) hf

/-- The parent's `isPowerForm_mul_base_left` (`s ↦ s·p`) is the `b = p` instance of the
general closure `isPowerForm_mul`, since `p = p^1 q^0` is a power form. -/
theorem isPowerForm_mul_base_left' {p q s : ℕ} (h : IsPowerForm p q s) :
    IsPowerForm p q (s * p) :=
  isPowerForm_mul h ⟨1, 0, by simp⟩

/-- The parent's `isPowerForm_mul_base_right` (`s ↦ s·q`) is the `b = q` instance of the
general closure `isPowerForm_mul`, since `q = p^0 q^1` is a power form. -/
theorem isPowerForm_mul_base_right' {p q s : ℕ} (h : IsPowerForm p q s) :
    IsPowerForm p q (s * q) :=
  isPowerForm_mul h ⟨0, 1, by simp⟩

/-! ### Identification with the concrete generated submonoid

The lemmas above (`isPowerForm_one`, `isPowerForm_mul`) say the power-form predicate
carves out a submonoid of `(ℕ, ×)`. We now *name* that submonoid and prove it is
exactly Mathlib's `Submonoid.closure {p, q}` — the submonoid generated by the two
bases. This turns the informal statement "`{p^k q^l}` is the submonoid generated by
`{p, q}`" (used throughout the parent's divisibility arguments) into a checked
identity, and lets the whole `Submonoid` API be reused for power forms. -/

/-- **The power forms as a submonoid of `(ℕ, ×)`.** Carrier `{n | IsPowerForm p q n}`;
the monoid axioms are `isPowerForm_one` (identity) and `isPowerForm_mul` (closure). -/
def powerFormSubmonoid (p q : ℕ) : Submonoid ℕ where
  carrier := {n | IsPowerForm p q n}
  one_mem' := isPowerForm_one p q
  mul_mem' := fun ha hb => isPowerForm_mul ha hb

@[simp] theorem mem_powerFormSubmonoid {p q n : ℕ} :
    n ∈ powerFormSubmonoid p q ↔ IsPowerForm p q n := Iff.rfl

/-- **The power-form submonoid is the submonoid generated by `{p, q}`.** Both bases are
power forms (`p = p^1 q^0`, `q = p^0 q^1`), so `Submonoid.closure {p,q}` lands inside
the power forms; conversely `p^k q^l ∈ closure {p,q}` by `pow_mem`/`mul_mem`. This is the
precise sense in which `{p^k q^l}` is "the multiplicative submonoid generated by
`{p, q}`". -/
theorem powerFormSubmonoid_eq_closure (p q : ℕ) :
    powerFormSubmonoid p q = Submonoid.closure ({p, q} : Set ℕ) := by
  apply le_antisymm
  · intro n hn
    obtain ⟨k, l, rfl⟩ := hn
    have hp : p ∈ Submonoid.closure ({p, q} : Set ℕ) :=
      Submonoid.subset_closure (by simp)
    have hq : q ∈ Submonoid.closure ({p, q} : Set ℕ) :=
      Submonoid.subset_closure (by simp)
    exact mul_mem (pow_mem hp k) (pow_mem hq l)
  · rw [Submonoid.closure_le]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact ⟨1, 0, by simp⟩
    · exact ⟨0, 1, by simp⟩

/-- **`IsPowerForm` is membership in the generated submonoid.** The predicate form of
`powerFormSubmonoid_eq_closure`: `n` is a power form `p^k q^l` iff `n` lies in the
submonoid of `ℕ` generated by `{p, q}`. -/
theorem isPowerForm_iff_mem_closure (p q n : ℕ) :
    IsPowerForm p q n ↔ n ∈ Submonoid.closure ({p, q} : Set ℕ) := by
  rw [← powerFormSubmonoid_eq_closure]
  exact mem_powerFormSubmonoid.symm

/-- **The first base lies in the power-form submonoid.** `p = p^1 q^0`, one of the two
generators identified by `powerFormSubmonoid_eq_closure`. -/
theorem self_mem_powerFormSubmonoid_left (p q : ℕ) :
    p ∈ powerFormSubmonoid p q := ⟨1, 0, by simp⟩

/-- **The second base lies in the power-form submonoid.** `q = p^0 q^1`, the other
generator. -/
theorem self_mem_powerFormSubmonoid_right (p q : ℕ) :
    q ∈ powerFormSubmonoid p q := ⟨0, 1, by simp⟩

/-- **Universal property of the power-form submonoid.** `powerFormSubmonoid p q` is the
*smallest* submonoid of `(ℕ, ×)` containing both bases: it is `≤ S` exactly when `S`
already contains `p` and `q`. Mirrors `Submonoid.closure_le` through the identification
`powerFormSubmonoid_eq_closure`, and reduces any "every power form lies in `S`" goal to the
two base facts `p ∈ S`, `q ∈ S`. -/
theorem powerFormSubmonoid_le_iff {p q : ℕ} {S : Submonoid ℕ} :
    powerFormSubmonoid p q ≤ S ↔ p ∈ S ∧ q ∈ S := by
  rw [powerFormSubmonoid_eq_closure, Submonoid.closure_le]
  constructor
  · intro h
    exact ⟨h (by simp), h (by simp)⟩
  · rintro ⟨hp, hq⟩ x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact hp
    · exact hq

/-! ### The divisibility order on power forms (distinct prime bases)

For **distinct primes** `p ≠ q`, the exponent pair `(k, l)` of a power form
`p^k q^l` is unique (unique factorization), and divisibility of power forms is
exactly the product order on the exponents:

  `p^k q^l ∣ p^{k'} q^{l'} ↔ k ≤ k' ∧ l ≤ l'`.

Equivalently `(k, l) ↦ p^k q^l` is an order isomorphism from `(ℕ², ≤)` onto the
power forms under divisibility. This is the structural fact behind #1110's
central *antichain* hypothesis — "no summand divides another" — since it turns the
divisibility test on power-form summands into a coordinatewise comparison of
exponent vectors. The two prime-exponent readouts `factorization_powerForm_left`
and `factorization_powerForm_right` extract `k` and `l` from `p^k q^l`. -/

/-- **The `p`-adic exponent of a power form.** For distinct primes `p ≠ q`, the
`p`-factorization of `p^k q^l` is exactly `k` (the `q^l` factor contributes nothing
at `p`). -/
theorem factorization_powerForm_left {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p ≠ q) (k l : ℕ) : (p ^ k * q ^ l).factorization p = k := by
  have hp0 : p ^ k ≠ 0 := pow_ne_zero k hp.pos.ne'
  have hq0 : q ^ l ≠ 0 := pow_ne_zero l hq.pos.ne'
  rw [Nat.factorization_mul hp0 hq0, Finsupp.add_apply, hp.factorization_pow,
      hq.factorization_pow, Finsupp.single_eq_same,
      Finsupp.single_eq_of_ne hpq, add_zero]

/-- **The `q`-adic exponent of a power form.** For distinct primes `p ≠ q`, the
`q`-factorization of `p^k q^l` is exactly `l`. -/
theorem factorization_powerForm_right {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p ≠ q) (k l : ℕ) : (p ^ k * q ^ l).factorization q = l := by
  have hp0 : p ^ k ≠ 0 := pow_ne_zero k hp.pos.ne'
  have hq0 : q ^ l ≠ 0 := pow_ne_zero l hq.pos.ne'
  rw [Nat.factorization_mul hp0 hq0, Finsupp.add_apply, hp.factorization_pow,
      hq.factorization_pow, Finsupp.single_eq_of_ne (Ne.symm hpq), Finsupp.single_eq_same,
      zero_add]

/-- **Divisibility of power forms is the product order on exponents.** For distinct
primes `p ≠ q`,

  `p^k q^l ∣ p^{k'} q^{l'} ↔ k ≤ k' ∧ l ≤ l'`.

The `←` direction is `mul_dvd_mul` of `pow_dvd_pow`; the `→` direction reads the two
prime exponents off both sides via `factorization_le_iff_dvd`. -/
theorem powerForm_dvd_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    p ^ k * q ^ l ∣ p ^ k' * q ^ l' ↔ k ≤ k' ∧ l ≤ l' := by
  constructor
  · intro h
    have hp0 : p ^ k * q ^ l ≠ 0 :=
      mul_ne_zero (pow_ne_zero k hp.pos.ne') (pow_ne_zero l hq.pos.ne')
    have hn0 : p ^ k' * q ^ l' ≠ 0 :=
      mul_ne_zero (pow_ne_zero k' hp.pos.ne') (pow_ne_zero l' hq.pos.ne')
    have hle := (Nat.factorization_le_iff_dvd hp0 hn0).mpr h
    rw [Finsupp.le_def] at hle
    refine ⟨?_, ?_⟩
    · have hpk := hle p
      simpa only [factorization_powerForm_left hp hq hpq] using hpk
    · have hql := hle q
      simpa only [factorization_powerForm_right hp hq hpq] using hql
  · rintro ⟨hk, hl⟩
    exact mul_dvd_mul (pow_dvd_pow p hk) (pow_dvd_pow q hl)

/-- **Unique exponents.** For distinct primes `p ≠ q`, equal power forms have equal
exponent pairs: `p^k q^l = p^{k'} q^{l'} → k = k' ∧ l = l'`. Hence `(k, l) ↦ p^k q^l`
is injective, and the power-form submonoid is freely generated (as a commutative
monoid) by the two bases. -/
theorem powerForm_exponents_unique {p q : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hpq : p ≠ q) {k l k' l' : ℕ} (h : p ^ k * q ^ l = p ^ k' * q ^ l') :
    k = k' ∧ l = l' := by
  refine ⟨?_, ?_⟩
  · have := congrArg (fun n => n.factorization p) h
    simpa only [factorization_powerForm_left hp hq hpq] using this
  · have := congrArg (fun n => n.factorization q) h
    simpa only [factorization_powerForm_right hp hq hpq] using this

/-- **Antichain criterion — the "no summand divides another" condition of #1110.**
For distinct primes `p ≠ q`, two power forms are mutually non-dividing exactly when their
exponent pairs are incomparable in the product order on `ℕ²`:

    ¬(p^k q^l ∣ p^{k'} q^{l'}) ∧ ¬(p^{k'} q^{l'} ∣ p^k q^l)
      ↔ ¬(k ≤ k' ∧ l ≤ l') ∧ ¬(k' ≤ k ∧ l' ≤ l).

This is the divisibility-antichain backbone of Erdős #1110's representation hypothesis
(sums of power forms in which *no summand divides another*): the exponent map
`(k, l) ↦ p^k q^l` sends `≤`-antichains of `ℕ²` to `∣`-antichains of the power forms.
Both directions are the double application of `powerForm_dvd_iff`. -/
theorem powerForm_incomparable_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    (¬ p ^ k * q ^ l ∣ p ^ k' * q ^ l' ∧ ¬ p ^ k' * q ^ l' ∣ p ^ k * q ^ l)
      ↔ (¬ (k ≤ k' ∧ l ≤ l') ∧ ¬ (k' ≤ k ∧ l' ≤ l)) := by
  rw [powerForm_dvd_iff hp hq hpq, powerForm_dvd_iff hp hq hpq]

/-! ### Closure under the divisibility lattice: divisors, `gcd` and `lcm`

The divisibility order on power forms (`powerForm_dvd_iff`) is the product order on
exponent pairs, which is a lattice with `min`/`max` as meet/join. The following lemmas
show the power-form set is *closed* under the corresponding arithmetic operations:
every divisor of a power form is a power form, and hence power forms are closed under
`Nat.gcd` and `Nat.lcm`. This completes the picture of `{p^k q^l}` (for prime bases) as a
**sublattice** of `(ℕ, ∣)` on top of its submonoid structure — the natural home for
Erdős #1110's divisibility/antichain arguments. -/

/-- **Divisors of a power form are power forms.** For prime bases `p, q`, if `n = p^k q^l`
is a power form and `d ∣ n`, then `d = p^a q^b` for some `a ≤ k`, `b ≤ l`, hence a power
form. Since `ℕ` is a decomposition monoid, `d` splits as `d₁ d₂` with `d₁ ∣ p^k`,
`d₂ ∣ q^l`; each factor of a prime power is a prime power (`Nat.dvd_prime_pow`). No
distinctness of `p, q` is needed. -/
theorem isPowerForm_of_dvd {p q d n : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hn : IsPowerForm p q n) (hd : d ∣ n) : IsPowerForm p q d := by
  obtain ⟨k, l, rfl⟩ := hn
  obtain ⟨d₁, d₂, hd₁, hd₂, rfl⟩ := exists_dvd_and_dvd_of_dvd_mul hd
  obtain ⟨a, _, rfl⟩ := (Nat.dvd_prime_pow hp).mp hd₁
  obtain ⟨b, _, rfl⟩ := (Nat.dvd_prime_pow hq).mp hd₂
  exact ⟨a, b, rfl⟩

/-- **Power forms are closed under `gcd`.** For prime bases `p, q`, the `gcd` of a power
form `m` with any `n` is a power form, because `Nat.gcd m n ∣ m`. (The meet of two power
forms in the divisibility order.) -/
theorem isPowerForm_gcd {p q m : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hm : IsPowerForm p q m) (n : ℕ) : IsPowerForm p q (Nat.gcd m n) :=
  isPowerForm_of_dvd hp hq hm (Nat.gcd_dvd_left m n)

/-- **Power forms are closed under `lcm`.** For prime bases `p, q`, the `lcm` of two power
forms is a power form: `Nat.lcm m n ∣ m * n`, and `m * n` is a power form by
`isPowerForm_mul`. (The join of two power forms in the divisibility order.) -/
theorem isPowerForm_lcm {p q m n : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hm : IsPowerForm p q m) (hn : IsPowerForm p q n) : IsPowerForm p q (Nat.lcm m n) :=
  isPowerForm_of_dvd hp hq (isPowerForm_mul hm hn) (Nat.lcm_dvd_mul m n)

/-! ### Explicit meet and join: the exponent formulas for `gcd` and `lcm`

`isPowerForm_gcd`/`isPowerForm_lcm` show the power forms are *closed* under `gcd` and `lcm`,
but only qualitatively. For **distinct primes** `p ≠ q` we can pin the exact exponents: since
`powerForm_dvd_iff` makes divisibility the product order on `(k, l)`, the meet and join in the
divisibility lattice are the coordinatewise `min` and `max`. Concretely

  `gcd (p^k q^l) (p^{k'} q^{l'}) = p^{min k k'} q^{min l l'}`,
  `lcm (p^k q^l) (p^{k'} q^{l'}) = p^{max k k'} q^{max l l'}`.

This upgrades the qualitative sublattice closure to an explicit lattice isomorphism
`{p^k q^l} ≅ (ℕ², min/max)` — the exponent map `(k, l) ↦ p^k q^l` is a lattice isomorphism, not
merely an order embedding. Each proof reads the exponents of the (already-known-to-be-a-power-form)
`gcd`/`lcm` off both sides through `powerForm_dvd_iff` and pins them by `Nat.dvd_antisymm`. -/

/-- **`gcd` of power forms is `min` on exponents.** For distinct primes `p ≠ q`,

  `gcd (p^k q^l) (p^{k'} q^{l'}) = p^{min k k'} q^{min l l'}`.

The greatest common divisor is a power form (`isPowerForm_gcd`); its exponents are `≤` both
`(k, l)` and `(k', l')` (it divides both), hence `≤ (min k k', min l l')`, while
`p^{min} q^{min}` divides both and so divides the `gcd` — pinning equality via `powerForm_dvd_iff`
in each coordinate. The explicit meet of the power-form sublattice of `(ℕ, ∣)`. -/
theorem powerForm_gcd {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    Nat.gcd (p ^ k * q ^ l) (p ^ k' * q ^ l') = p ^ min k k' * q ^ min l l' := by
  obtain ⟨a, b, hab⟩ : IsPowerForm p q (Nat.gcd (p ^ k * q ^ l) (p ^ k' * q ^ l')) :=
    isPowerForm_gcd hp hq ⟨k, l, rfl⟩ _
  rw [hab]
  have hdX : p ^ a * q ^ b ∣ p ^ k * q ^ l := by rw [← hab]; exact Nat.gcd_dvd_left _ _
  have hdY : p ^ a * q ^ b ∣ p ^ k' * q ^ l' := by rw [← hab]; exact Nat.gcd_dvd_right _ _
  obtain ⟨hak, hbl⟩ := (powerForm_dvd_iff hp hq hpq a b k l).mp hdX
  obtain ⟨hak', hbl'⟩ := (powerForm_dvd_iff hp hq hpq a b k' l').mp hdY
  have hmX : p ^ min k k' * q ^ min l l' ∣ p ^ k * q ^ l :=
    (powerForm_dvd_iff hp hq hpq _ _ _ _).mpr ⟨min_le_left _ _, min_le_left _ _⟩
  have hmY : p ^ min k k' * q ^ min l l' ∣ p ^ k' * q ^ l' :=
    (powerForm_dvd_iff hp hq hpq _ _ _ _).mpr ⟨min_le_right _ _, min_le_right _ _⟩
  have hmg : p ^ min k k' * q ^ min l l' ∣ p ^ a * q ^ b := by
    rw [← hab]; exact Nat.dvd_gcd hmX hmY
  obtain ⟨hma, hmb⟩ := (powerForm_dvd_iff hp hq hpq _ _ _ _).mp hmg
  rw [le_antisymm (le_min hak hak') hma, le_antisymm (le_min hbl hbl') hmb]

/-- **`lcm` of power forms is `max` on exponents.** For distinct primes `p ≠ q`,

  `lcm (p^k q^l) (p^{k'} q^{l'}) = p^{max k k'} q^{max l l'}`.

Dual to `powerForm_gcd`: the least common multiple is a power form (`isPowerForm_lcm`); both
`(k, l)` and `(k', l')` are `≤` its exponents (they divide it), so `(max k k', max l l')` is,
while the `lcm` divides `p^{max} q^{max}` (which both factors divide) — pinning equality via
`powerForm_dvd_iff`. The explicit join of the power-form sublattice of `(ℕ, ∣)`. -/
theorem powerForm_lcm {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    Nat.lcm (p ^ k * q ^ l) (p ^ k' * q ^ l') = p ^ max k k' * q ^ max l l' := by
  obtain ⟨a, b, hab⟩ : IsPowerForm p q (Nat.lcm (p ^ k * q ^ l) (p ^ k' * q ^ l')) :=
    isPowerForm_lcm hp hq ⟨k, l, rfl⟩ ⟨k', l', rfl⟩
  rw [hab]
  have hXl : p ^ k * q ^ l ∣ p ^ a * q ^ b := by rw [← hab]; exact Nat.dvd_lcm_left _ _
  have hYl : p ^ k' * q ^ l' ∣ p ^ a * q ^ b := by rw [← hab]; exact Nat.dvd_lcm_right _ _
  obtain ⟨hka, hlb⟩ := (powerForm_dvd_iff hp hq hpq k l a b).mp hXl
  obtain ⟨hka', hlb'⟩ := (powerForm_dvd_iff hp hq hpq k' l' a b).mp hYl
  have hXM : p ^ k * q ^ l ∣ p ^ max k k' * q ^ max l l' :=
    (powerForm_dvd_iff hp hq hpq _ _ _ _).mpr ⟨le_max_left _ _, le_max_left _ _⟩
  have hYM : p ^ k' * q ^ l' ∣ p ^ max k k' * q ^ max l l' :=
    (powerForm_dvd_iff hp hq hpq _ _ _ _).mpr ⟨le_max_right _ _, le_max_right _ _⟩
  have hlM : p ^ a * q ^ b ∣ p ^ max k k' * q ^ max l l' := by
    rw [← hab]; exact Nat.lcm_dvd hXM hYM
  obtain ⟨haM, hbM⟩ := (powerForm_dvd_iff hp hq hpq _ _ _ _).mp hlM
  rw [le_antisymm haM (max_le hka hka'), le_antisymm hbM (max_le hlb hlb')]

/-- **Coprimality criterion for power forms.**  For distinct primes `p ≠ q`, two power
forms are coprime exactly when they share no prime factor — neither `p` nor `q` divides
both:

    Nat.Coprime (p^k q^l) (p^{k'} q^{l'}) ↔ (min k k' = 0 ∧ min l l' = 0).

Immediate from `powerForm_gcd` (the gcd is `p^{min k k'} q^{min l l'}`), with the
`gcd = 1` collapse pinned by `powerForm_exponents_unique`.  The `min`-form meet of the
divisibility lattice bottoming out at `1`. -/
theorem powerForm_coprime_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    Nat.Coprime (p ^ k * q ^ l) (p ^ k' * q ^ l') ↔ (min k k' = 0 ∧ min l l' = 0) := by
  rw [Nat.Coprime, powerForm_gcd hp hq hpq]
  constructor
  · intro h
    have h1 : p ^ min k k' * q ^ min l l' = p ^ 0 * q ^ 0 := by simpa using h
    exact powerForm_exponents_unique hp hq hpq h1
  · rintro ⟨ha, hb⟩
    rw [ha, hb, pow_zero, pow_zero, mul_one]

/-- **Coprimality criterion, disjunction form.**  `powerForm_coprime_iff` rephrased with
`Nat.min_eq_zero_iff`: coprimality means that for each prime, at least one of the two forms
omits it. -/
theorem powerForm_coprime_iff' {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l k' l' : ℕ) :
    Nat.Coprime (p ^ k * q ^ l) (p ^ k' * q ^ l')
      ↔ ((k = 0 ∨ k' = 0) ∧ (l = 0 ∨ l' = 0)) := by
  rw [powerForm_coprime_iff hp hq hpq, Nat.min_eq_zero_iff, Nat.min_eq_zero_iff]

/-! ### The divisor set of a power form: a finite exponent grid

The divisibility order on power forms is the product order on exponent pairs
(`powerForm_dvd_iff`), and every divisor of a power form is again a power form
(`isPowerForm_of_dvd`). Together these pin the *divisor set* of `p^k q^l` exactly: for
distinct primes `p ≠ q` the divisors are precisely the `(k+1)(l+1)` power forms
`p^a q^b` with `a ≤ k`, `b ≤ l` — the integer grid `[0,k] × [0,l]` under the exponent
map. The lemmas below record the two halves of this picture: the divisor set as the
image of that grid, and its cardinality `(k+1)(l+1)` (the classical divisor-count
formula `τ(p^k q^l) = (k+1)(l+1)`, here as a consequence of the sublattice structure). -/

/-- **Every divisor of a power form is a power form.** The `Finset` form of
`isPowerForm_of_dvd`: if `n = p^k q^l` and `d ∈ n.divisors` then `d` is a power form. -/
theorem isPowerForm_of_mem_divisors {p q n d : ℕ} (hp : p.Prime) (hq : q.Prime)
    (hn : IsPowerForm p q n) (hd : d ∈ n.divisors) : IsPowerForm p q d :=
  isPowerForm_of_dvd hp hq hn (Nat.dvd_of_mem_divisors hd)

/-- **The divisor set of a power form is the exponent grid.** For distinct primes `p ≠ q`,
the divisors of `p^k q^l` are exactly the power forms `p^a q^b` with `a ≤ k`, `b ≤ l`:

    (p^k q^l).divisors = (range (k+1) ×ˢ range (l+1)).image (fun (a,b) ↦ p^a q^b).

Forward: any divisor is a power form (`isPowerForm_of_dvd`) whose exponents are `≤ (k,l)`
(`powerForm_dvd_iff`); backward: any such `p^a q^b` divides `p^k q^l`. This realizes the
divisor lattice of a power form as the concrete integer grid `[0,k] × [0,l]`. -/
theorem powerForm_divisors_eq_grid {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l : ℕ) :
    (p ^ k * q ^ l).divisors =
      (Finset.range (k + 1) ×ˢ Finset.range (l + 1)).image (fun ab => p ^ ab.1 * q ^ ab.2) := by
  ext d
  rw [Nat.mem_divisors, Finset.mem_image]
  constructor
  · rintro ⟨hd, _⟩
    obtain ⟨a, b, rfl⟩ := isPowerForm_of_dvd hp hq ⟨k, l, rfl⟩ hd
    obtain ⟨ha, hb⟩ := (powerForm_dvd_iff hp hq hpq a b k l).mp hd
    refine ⟨(a, b), ?_, rfl⟩
    rw [Finset.mem_product, Finset.mem_range, Finset.mem_range]
    exact ⟨Nat.lt_succ_of_le ha, Nat.lt_succ_of_le hb⟩
  · rintro ⟨⟨a, b⟩, hab, rfl⟩
    rw [Finset.mem_product, Finset.mem_range, Finset.mem_range,
        Nat.lt_succ_iff, Nat.lt_succ_iff] at hab
    refine ⟨(powerForm_dvd_iff hp hq hpq a b k l).mpr ⟨hab.1, hab.2⟩, ?_⟩
    exact mul_ne_zero (pow_ne_zero k hp.pos.ne') (pow_ne_zero l hq.pos.ne')

/-- **Divisor-count formula `τ(p^k q^l) = (k+1)(l+1)`.** For distinct primes `p ≠ q`, the
number of divisors of the power form `p^k q^l` is `(k+1)(l+1)`. Since `p^k` and `q^l` are
coprime the divisor count is multiplicative (`Nat.Coprime.card_divisors_mul`), and each prime
power `p^k` has exactly `k+1` divisors (`Nat.divisors_prime_pow`). This counts the exponent
grid `[0,k] × [0,l]` of `powerForm_divisors_eq_grid`. -/
theorem powerForm_card_divisors {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l : ℕ) : (p ^ k * q ^ l).divisors.card = (k + 1) * (l + 1) := by
  have hcop : Nat.Coprime (p ^ k) (q ^ l) := Nat.coprime_pow_primes k l hp hq hpq
  rw [Nat.Coprime.card_divisors_mul hcop, Nat.divisors_prime_pow hp, Nat.divisors_prime_pow hq,
      Finset.card_map, Finset.card_map, Finset.card_range, Finset.card_range]

/-- **Prime-factor set of a power form.** For distinct primes `p ≠ q` and positive
exponents, the prime factors of `p^k q^l` are exactly `{p, q}` (both primes actually
occur, and no others). This is the support of the factorization underlying the exponent
grid of `powerForm_divisors_eq_grid`. -/
theorem powerForm_primeFactors {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    {k l : ℕ} (hk : 0 < k) (hl : 0 < l) :
    (p ^ k * q ^ l).primeFactors = {p, q} := by
  rw [Nat.primeFactors_mul (pow_ne_zero k hp.pos.ne') (pow_ne_zero l hq.pos.ne'),
      Nat.primeFactors_prime_pow hk.ne' hp, Nat.primeFactors_prime_pow hl.ne' hq,
      Finset.singleton_union]

/-- **Euler totient of a power form `φ(p^k q^l) = p^{k-1}(p-1)·q^{l-1}(q-1)`.** For distinct
primes `p ≠ q` and positive exponents. The multiplicative companion of the divisor-count
formula `powerForm_card_divisors` (`τ(p^k q^l) = (k+1)(l+1)`): since `p^k` and `q^l` are
coprime, `φ` factors as `φ(p^k)·φ(q^l)` (`Nat.totient_mul`), and each prime-power totient is
`φ(p^k) = p^{k-1}(p-1)` (`Nat.totient_prime_pow`). -/
theorem powerForm_totient {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    {k l : ℕ} (hk : 0 < k) (hl : 0 < l) :
    (p ^ k * q ^ l).totient = p ^ (k - 1) * (p - 1) * (q ^ (l - 1) * (q - 1)) := by
  have hcop : Nat.Coprime (p ^ k) (q ^ l) := Nat.coprime_pow_primes k l hp hq hpq
  rw [Nat.totient_mul hcop, Nat.totient_prime_pow hp hk, Nat.totient_prime_pow hq hl]

/-- **Sum-of-divisors `σ(p^k q^l) = (Σᵢ₌₀ᵏ pⁱ)·(Σⱼ₌₀ˡ qʲ)`.** For distinct primes `p ≠ q`,
the divisor sum `σ₁` of the power form `p^k q^l` factors through the coprime split
`p^k ⊥ q^l` (`Nat.Coprime.sum_divisors_mul`, `σ` multiplicative), and each prime-power
divisor sum reindexes over its exponent range (`Nat.sum_divisors_prime_pow`). Collapsing
the two geometric series gives the textbook closed form
`σ(p^k q^l) = ((p^{k+1}−1)/(p−1))·((q^{l+1}−1)/(q−1))`; we keep the pre-collapse product of
range-sums to avoid `ℕ`-division. This is the `σ` companion of the divisor-count `τ`
(`powerForm_card_divisors`, `(k+1)(l+1)`) and totient `φ` (`powerForm_totient`), completing
the standard multiplicative-invariant readouts (`τ, φ, ω, Ω, σ, radical`) of a two-prime
power form off the single coprime split. -/
theorem powerForm_sigma {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) (k l : ℕ) :
    ∑ d ∈ (p ^ k * q ^ l).divisors, d
      = (∑ i ∈ Finset.range (k + 1), p ^ i) * (∑ j ∈ Finset.range (l + 1), q ^ j) := by
  have hcop : Nat.Coprime (p ^ k) (q ^ l) := Nat.coprime_pow_primes k l hp hq hpq
  rw [hcop.sum_divisors_mul, Nat.sum_divisors_prime_pow hp, Nat.sum_divisors_prime_pow hq]

/-! ### The remaining classical multiplicative invariants: `ω`, radical, `Ω`, squarefree

The divisor-count `τ(p^k q^l) = (k+1)(l+1)` (`powerForm_card_divisors`) and totient
`φ` (`powerForm_totient`) read the two exponents through the coprime split
`p^k ⊥ q^l`. The same split pins the rest of the standard arithmetic-function
readouts of a two-prime power form, completing the multiplicative-invariant
picture on top of the divisor grid. -/

/-- **Number of distinct prime factors `ω(p^k q^l) = 2`.** For distinct primes `p ≠ q`
and positive exponents, a two-prime power form has exactly two distinct prime factors.
Immediate from `powerForm_primeFactors` (the prime-factor set is `{p, q}`) and
`Finset.card_pair`. The `ω` companion of the divisor-count `τ` and totient `φ`. -/
theorem powerForm_card_primeFactors {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    {k l : ℕ} (hk : 0 < k) (hl : 0 < l) :
    (p ^ k * q ^ l).primeFactors.card = 2 := by
  rw [powerForm_primeFactors hp hq hpq hk hl, Finset.card_pair hpq]

/-- **Radical of a power form `rad(p^k q^l) = p·q`.** For distinct primes `p ≠ q` and
positive exponents, the product of the distinct prime factors of `p^k q^l` is `p·q` —
the squarefree kernel is independent of the exponents. Immediate from
`powerForm_primeFactors` and `Finset.prod_pair`. -/
theorem powerForm_prod_primeFactors {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    {k l : ℕ} (hk : 0 < k) (hl : 0 < l) :
    (p ^ k * q ^ l).primeFactors.prod id = p * q := by
  rw [powerForm_primeFactors hp hq hpq hk hl, Finset.prod_pair hpq, id_eq, id_eq]

open ArithmeticFunction in
/-- **Number of prime factors with multiplicity `Ω(p^k q^l) = k + l`.** For prime bases
`p, q` (distinctness not needed), the total count of prime factors of a power form,
counted with multiplicity, is the sum of the exponents. Since `Ω` is completely additive
(`cardFactors_mul`) and `Ω(pᵏ) = k` on prime powers (`cardFactors_apply_prime_pow`), this
is the additive companion of the multiplicative `ω`, `τ`, `φ` readouts. -/
theorem powerForm_cardFactors {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (k l : ℕ) :
    cardFactors (p ^ k * q ^ l) = k + l := by
  rw [cardFactors_mul (pow_ne_zero k hp.pos.ne') (pow_ne_zero l hq.pos.ne'),
    cardFactors_apply_prime_pow hp, cardFactors_apply_prime_pow hq]

/-- **Squarefree power forms are exactly the small-exponent ones.** For distinct primes
`p ≠ q`, `p^k q^l` is squarefree iff both exponents are `≤ 1`:

    Squarefree (p^k q^l) ↔ k ≤ 1 ∧ l ≤ 1.

Through `Nat.squarefree_iff_factorization_le_one`, squarefreeness is `∀ r, factorization r ≤ 1`;
the `p`- and `q`-exponents are `k` and `l` (`factorization_powerForm_left`/`_right`) and every
other prime contributes `0`. So the four squarefree two-prime forms are `1, p, q, pq` — the
`gcd`/`lcm` lattice grid capped at exponent `1`, i.e. the divisors of the radical `p·q`
(`powerForm_prod_primeFactors`). -/
theorem powerForm_squarefree_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l : ℕ) : Squarefree (p ^ k * q ^ l) ↔ k ≤ 1 ∧ l ≤ 1 := by
  have hp0 : p ^ k ≠ 0 := pow_ne_zero k hp.pos.ne'
  have hq0 : q ^ l ≠ 0 := pow_ne_zero l hq.pos.ne'
  rw [Nat.squarefree_iff_factorization_le_one (mul_ne_zero hp0 hq0)]
  constructor
  · intro h
    refine ⟨?_, ?_⟩
    · have := h p; rwa [factorization_powerForm_left hp hq hpq] at this
    · have := h q; rwa [factorization_powerForm_right hp hq hpq] at this
  · rintro ⟨hk, hl⟩ r
    rw [Nat.factorization_mul hp0 hq0, Finsupp.add_apply, hp.factorization_pow,
      hq.factorization_pow, Finsupp.single_apply, Finsupp.single_apply]
    split_ifs <;> omega

/-! ### The Möbius function of a power form

The multiplicative-invariant readouts above (`τ, φ, ω, Ω, σ, radical, squarefree`) all
follow from the coprime split `p^k ⊥ q^l`. The remaining classical multiplicative
function is the **Möbius function `μ`**, which is supported exactly on the squarefree
forms: since `p^k q^l` is squarefree iff `k ≤ 1 ∧ l ≤ 1` (`powerForm_squarefree_iff`),
`μ` vanishes off the four small forms `1, p, q, pq` and equals `(-1)^{k+l}` on them
(`Ω(p^k q^l) = k + l`, `powerForm_cardFactors`). This is the sign-carrying companion of
the (unsigned) squarefree indicator, completing the standard multiplicative-invariant
suite. -/

open ArithmeticFunction in
open scoped ArithmeticFunction.Moebius in
/-- **Möbius of a squarefree power form `μ(p^k q^l) = (-1)^{k+l}`.** For distinct primes
`p ≠ q` with both exponents `≤ 1` (so `p^k q^l ∈ {1, p, q, pq}` is squarefree), the Möbius
value is `(-1)^{k+l}`: `μ n = (-1)^{Ω n}` on squarefree `n` (`moebius_apply_of_squarefree`)
and `Ω(p^k q^l) = k + l` (`powerForm_cardFactors`). -/
theorem powerForm_moebius_of_squarefree {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    {k l : ℕ} (hk : k ≤ 1) (hl : l ≤ 1) :
    μ (p ^ k * q ^ l) = (-1) ^ (k + l) := by
  have hsf : Squarefree (p ^ k * q ^ l) := (powerForm_squarefree_iff hp hq hpq k l).mpr ⟨hk, hl⟩
  rw [moebius_apply_of_squarefree hsf, powerForm_cardFactors hp hq]

open ArithmeticFunction in
open scoped ArithmeticFunction.Moebius in
/-- **Möbius vanishes on non-squarefree power forms.** For distinct primes `p ≠ q`, if some
exponent exceeds `1` then `p^k q^l` is not squarefree (`powerForm_squarefree_iff`), so
`μ(p^k q^l) = 0` (`moebius_eq_zero_of_not_squarefree`). -/
theorem powerForm_moebius_eq_zero {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    {k l : ℕ} (h : ¬ (k ≤ 1 ∧ l ≤ 1)) :
    μ (p ^ k * q ^ l) = 0 :=
  moebius_eq_zero_of_not_squarefree (by rwa [powerForm_squarefree_iff hp hq hpq])

open ArithmeticFunction in
open scoped ArithmeticFunction.Moebius in
/-- **Closed form for the Möbius function of a power form.** For distinct primes `p ≠ q`,

    `μ(p^k q^l) = if k ≤ 1 ∧ l ≤ 1 then (-1)^{k+l} else 0`.

Combines `powerForm_moebius_of_squarefree` (the squarefree branch) and
`powerForm_moebius_eq_zero` (everything else). This is the Möbius companion of the
divisor-count `τ` (`powerForm_card_divisors`), totient `φ` (`powerForm_totient`), divisor
sum `σ` (`powerForm_sigma`) and squarefree indicator (`powerForm_squarefree_iff`) — the
signed characteristic function of the four squarefree two-prime forms `1, p, q, pq`. -/
theorem powerForm_moebius {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q) (k l : ℕ) :
    μ (p ^ k * q ^ l) = if k ≤ 1 ∧ l ≤ 1 then (-1) ^ (k + l) else 0 := by
  split_ifs with h
  · exact powerForm_moebius_of_squarefree hp hq hpq h.1 h.2
  · exact powerForm_moebius_eq_zero hp hq hpq h

/-! ### Non-coprime bases: the power-form monoid avoids the class `1 mod d`

The submonoid identification `IsPowerForm p q n ↔ n ∈ Submonoid.closure {p, q}`
(`isPowerForm_iff_mem_closure`) has a sharp arithmetic consequence when the two bases
share a common factor `d ≥ 2`: since `d ∣ p` and `d ∣ q`, every generator (hence every
non-identity element) of the monoid is divisible by `d`, so

    ⟨p, q⟩ ⊆ {1} ∪ d·ℕ.

This lets us settle the **entire non-coprime regime** of Erdős–Lewin unconditionally.
In any admissible representation `n = ∑ S` (an antichain of power forms), the identity `1`
can occur only as the *sole* summand — otherwise it would divide another summand — so a
representation of length `> 1` has all summands `> 1`, hence all divisible by `d`, forcing
`d ∣ n`. Consequently a number that is **neither a power form nor divisible by `d`** is
non-representable, and the residue class `n ≡ 1 (mod d)` supplies infinitely many such
numbers.

This generalises the parent file's base-power family `infinite_nonRepresentable_base_pow`
(the case `p = q^k`, `d = q`) to *all* non-coprime pairs — including ones where neither
base is a power of the other, e.g. `(p, q) = (6, 4)` with `d = 2` — and is exactly the
complement of the coprimality hypothesis of the deep axiom `erdos_lewin_infinite`. -/

/-- **A common divisor of the bases divides every non-trivial power form.** If `d ∣ p` and
`d ∣ q` then any power form `p^k q^l` is either `1` (the case `k = l = 0`) or divisible by
`d`. Monoid-theoretically: the generators `p, q` of `powerFormSubmonoid p q` both lie in
`d·ℕ`, so the whole submonoid sits inside `{1} ∪ d·ℕ`. -/
theorem isPowerForm_one_or_common_dvd {p q d n : ℕ} (hdp : d ∣ p) (hdq : d ∣ q)
    (h : IsPowerForm p q n) : n = 1 ∨ d ∣ n := by
  obtain ⟨k, l, rfl⟩ := h
  rcases Nat.eq_zero_or_pos k with hk | hk
  · subst hk
    rcases Nat.eq_zero_or_pos l with hl | hl
    · subst hl; left; simp
    · right; simpa using dvd_pow hdq hl.ne'
  · right; exact (dvd_pow hdp hk.ne').mul_right _

/-- **A representation of a non-`d`-divisible number is a single power form.** With `d ∣ p`
and `d ∣ q`, every representable `n` is either itself a power form (a length-one antichain)
or divisible by `d`. Indeed, if the identity `1` appears in the representing antichain `S`
it must be the only member (it divides everything), giving `n = 1`; otherwise every summand
exceeds `1`, so `d` divides each summand (`isPowerForm_one_or_common_dvd`) and hence their
sum `n`. -/
theorem isPowerForm_or_common_dvd_of_representable {p q d n : ℕ}
    (hdp : d ∣ p) (hdq : d ∣ q) (hrep : IsRepresentable p q n) :
    IsPowerForm p q n ∨ d ∣ n := by
  obtain ⟨S, hSne, hSpf, hSanti, hSsum⟩ := hrep
  by_cases h1 : (1 : ℕ) ∈ S
  · -- `1 ∈ S` forces `S = {1}` (it divides everything), so `n = 1` is a power form.
    left
    have hsub : S = {1} := by
      refine Finset.eq_singleton_iff_unique_mem.mpr ⟨h1, ?_⟩
      intro x hx
      by_contra hx1
      exact hSanti 1 h1 x hx (Ne.symm hx1) (one_dvd x)
    rw [hsub] at hSsum
    simp only [Finset.sum_singleton, id_eq] at hSsum
    rw [← hSsum]
    exact ⟨0, 0, by simp⟩
  · -- `1 ∉ S`: every summand exceeds `1`, hence is divisible by `d`, hence so is the sum.
    right
    rw [← hSsum]
    apply Finset.dvd_sum
    intro s hs
    have hs1 : s ≠ 1 := fun h => h1 (h ▸ hs)
    rcases isPowerForm_one_or_common_dvd hdp hdq (hSpf s hs) with h | h
    · exact absurd h hs1
    · simpa using h

/-- **Non-representability test for non-coprime bases.** If `d ∣ p`, `d ∣ q`, and `n` is
neither a power form nor divisible by `d`, then `n` is non-representable — no admissible
antichain of `p^k q^l` sums to it (`isPowerForm_or_common_dvd_of_representable`). -/
theorem not_isRepresentable_of_not_common_dvd {p q d n : ℕ}
    (hdp : d ∣ p) (hdq : d ∣ q) (hpf : ¬ IsPowerForm p q n) (hn : ¬ d ∣ n) :
    ¬ IsRepresentable p q n := fun hrep =>
  (isPowerForm_or_common_dvd_of_representable hdp hdq hrep).elim hpf hn

/-- **Infinitely many non-representables for every non-coprime pair — elementary, 0-axiom.**
If the bases share a common divisor `d ≥ 2` (`d ∣ p`, `d ∣ q`), the arithmetic progression
`n = d(m+1)+1` (i.e. `n ≡ 1 (mod d)`, `n > 1`) consists entirely of non-representables:
each such `n` is not divisible by `d`, and — being `> 1` and not a multiple of `d` — is not
a power form (`isPowerForm_one_or_common_dvd`), so it is non-representable
(`not_isRepresentable_of_not_common_dvd`). The injection `m ↦ d(m+1)+1` embeds `ℕ` into
`NonRepresentable p q`. This is the full non-coprime regime of the Erdős–Lewin phenomenon,
subsuming the base-power family `infinite_nonRepresentable_base_pow`. -/
theorem infinite_nonRepresentable_of_common_dvd {p q d : ℕ}
    (hdp : d ∣ p) (hdq : d ∣ q) (hd : 2 ≤ d) :
    Set.Infinite (NonRepresentable p q) := by
  refine Set.infinite_of_injective_forall_mem
    (f := fun m : ℕ => d * (m + 1) + 1) ?_ ?_
  · intro a b hab
    change d * (a + 1) + 1 = d * (b + 1) + 1 at hab
    have h1 : d * (a + 1) = d * (b + 1) := by omega
    have := Nat.eq_of_mul_eq_mul_left (by omega : 0 < d) h1
    omega
  · intro m
    show (d * (m + 1) + 1) ∈ NonRepresentable p q
    rw [NonRepresentable, Set.mem_setOf_eq]
    have hnd : ¬ d ∣ (d * (m + 1) + 1) := by
      intro hdvd
      have h1 : d ∣ 1 := (Nat.dvd_add_right (dvd_mul_right d (m + 1))).mp hdvd
      have := Nat.le_of_dvd one_pos h1
      omega
    have hnpf : ¬ IsPowerForm p q (d * (m + 1) + 1) := by
      intro h
      rcases isPowerForm_one_or_common_dvd hdp hdq h with h1 | h2
      · have : 0 < d * (m + 1) := Nat.mul_pos (by omega) (by omega)
        omega
      · exact hnd h2
    exact not_isRepresentable_of_not_common_dvd hdp hdq hnpf hnd

/-- **Non-coprimality alone gives infinitely many non-representables.** For `p ≥ 1` with
`p, q` not coprime, `d := gcd p q ≥ 2` is a common divisor, so
`infinite_nonRepresentable_of_common_dvd` applies. The full complement of the coprime
hypothesis of `erdos_lewin_infinite`, proved with no axiom. -/
theorem infinite_nonRepresentable_of_not_coprime {p q : ℕ}
    (hp : 1 ≤ p) (hcop : ¬ Nat.Coprime p q) :
    Set.Infinite (NonRepresentable p q) := by
  have hdp : Nat.gcd p q ∣ p := Nat.gcd_dvd_left p q
  have hdq : Nat.gcd p q ∣ q := Nat.gcd_dvd_right p q
  have hne1 : Nat.gcd p q ≠ 1 := hcop
  have hne0 : Nat.gcd p q ≠ 0 := by
    intro h; rw [Nat.gcd_eq_zero_iff] at h; omega
  exact infinite_nonRepresentable_of_common_dvd hdp hdq (by omega)

/-- **The base-power family, re-derived.** `infinite_nonRepresentable_base_pow` (the parent
file's `p = q^k` result) is the special case `d = q` of
`infinite_nonRepresentable_of_common_dvd`: `q ∣ q^k` and `q ∣ q`. -/
theorem infinite_nonRepresentable_base_pow' {q k : ℕ} (hq : 2 ≤ q) (hk : 1 ≤ k) :
    Set.Infinite (NonRepresentable (q ^ k) q) :=
  infinite_nonRepresentable_of_common_dvd (dvd_pow_self q (by omega : k ≠ 0)) dvd_rfl hq

/-- **A genuinely new non-coprime pair.** `(p, q) = (6, 4)` has `gcd 6 4 = 2 ≥ 2`, yet
neither base is a power of the other — so it lies outside the base-power family
`infinite_nonRepresentable_base_pow` but is covered by
`infinite_nonRepresentable_of_common_dvd` (`d = 2`). -/
example : Set.Infinite (NonRepresentable 6 4) :=
  infinite_nonRepresentable_of_common_dvd (d := 2) (by norm_num) (by norm_num) (by norm_num)

/-- **The identity is the unique unit exponent pair.** For distinct primes `p ≠ q`,
`p^k q^l = 1` iff both exponents vanish — the exponent-uniqueness readout at the monoid
identity `1 = p^0 q^0`. So `(0, 0)` is the only exponent vector representing the unit of
the power-form submonoid. -/
theorem powerForm_eq_one_iff {p q : ℕ} (hp : p.Prime) (hq : q.Prime) (hpq : p ≠ q)
    (k l : ℕ) : p ^ k * q ^ l = 1 ↔ k = 0 ∧ l = 0 := by
  constructor
  · intro h
    exact powerForm_exponents_unique hp hq hpq (by simpa using h)
  · rintro ⟨rfl, rfl⟩; simp

end Erdos1110
