/-
# Erdős Problem #424 — Sequence Generated by a_i · a_j − 1

Start with a₁ = 2, a₂ = 3. At each step, append all values
a_i · a_j − 1 (i ≠ j) not already present. The sequence begins
2, 3, 5, 9, 14, 17, 26, ...

Does the set of integers eventually appearing have positive density?

## Key Observation
No integer ≡ 1 (mod 3) ever appears: if a, b ∈ {0, 2} (mod 3),
then ab − 1 ∈ {0, 2} (mod 3). So the maximum possible density is 2/3.

Status: OPEN
Reference: https://erdosproblems.com/424
OEIS: A005244
-/

import Mathlib.Data.Finset.Card
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Set.Basic
import Mathlib.Tactic

/- ## Definitions -/

/-- The next-generation operation: from a set A, produce all x · y − 1
    for distinct x, y ∈ A with x · y ≥ 2. -/
def nextGeneration (A : Set ℕ) : Set ℕ :=
  {z : ℕ | ∃ x y, x ∈ A ∧ y ∈ A ∧ x ≠ y ∧ x * y ≥ 2 ∧ z = x * y - 1}

/-- The iterated sequence of sets: A₀ = {2, 3}, A_{n+1} = A_n ∪ nextGen(A_n). -/
def sequenceSet : ℕ → Set ℕ
  | 0 => {2, 3}
  | n + 1 => sequenceSet n ∪ nextGeneration (sequenceSet n)

/-- The full generated set: ⋃_n A_n. -/
def generatedSet : Set ℕ := ⋃ n : ℕ, sequenceSet n

/-- The counting function: number of elements of generatedSet in {1,...,N}. -/
noncomputable def generatedCount (N : ℕ) : ℕ :=
  (Finset.Icc 1 N).filter (fun n => n ∈ generatedSet) |>.card

/- ## Main Conjecture -/

/-- **Erdős Problem #424**: does generatedSet have positive (lower) density?
    That is, lim inf |generatedSet ∩ [1,N]| / N > 0. -/
axiom erdos_424_conjecture :
  ∃ c : ℝ, c > 0 ∧
    ∀ N : ℕ, N > 0 → (generatedCount N : ℝ) ≥ c * N

/- ## Known Results -/

/-- **Mod 3 Obstruction**: no element of generatedSet is ≡ 1 (mod 3).
    If a, b ∈ {0, 2} (mod 3) then ab − 1 ∈ {0, 2} (mod 3). -/
axiom mod_3_obstruction :
  ∀ n ∈ generatedSet, n % 3 ≠ 1

/-- **Density Upper Bound**: since no element is ≡ 1 (mod 3), the density
    of generatedSet is at most 2/3. -/
axiom density_upper_bound :
  ∀ ε : ℝ, ε > 0 →
    ∃ N₀ : ℕ, ∀ N ≥ N₀,
      (generatedCount N : ℝ) ≤ (2/3 + ε) * N

/-- **Initial Elements**: the first few elements are 2, 3, 5, 9, 14, 17, 26, ...
    (OEIS A005244). -/
axiom initial_elements :
  2 ∈ generatedSet ∧ 3 ∈ generatedSet ∧ 5 ∈ generatedSet ∧
  9 ∈ generatedSet ∧ 14 ∈ generatedSet ∧ 17 ∈ generatedSet

/- ## Observations -/

/-- **Monotonicity**: A_n ⊆ A_{n+1} for all n. -/
theorem sequence_monotone (n : ℕ) :
  sequenceSet n ⊆ sequenceSet (n + 1) := by
  intro x hx; exact Set.mem_union_left _ hx

/-- Monotonicity of sequenceSet extended to ≤. -/
private lemma sequenceSet_mono {a b : ℕ} (h : a ≤ b) : sequenceSet a ⊆ sequenceSet b := by
  induction h with
  | refl => exact Set.Subset.rfl
  | step _ ih => exact Set.Subset.trans ih (sequence_monotone _)

/-- **Closure**: generatedSet is closed under the operation (x, y) ↦ xy − 1
    for distinct x, y in the set with xy ≥ 2. -/
theorem generated_closed :
  ∀ x y, x ∈ generatedSet → y ∈ generatedSet → x ≠ y → x * y ≥ 2 →
    x * y - 1 ∈ generatedSet := by
  intro x y hx hy hne hge
  simp only [generatedSet, Set.mem_iUnion] at hx hy ⊢
  obtain ⟨a, ha⟩ := hx
  obtain ⟨b, hb⟩ := hy
  exact ⟨max a b + 1, Set.mem_union_right _
    ⟨x, y, sequenceSet_mono (le_max_left a b) ha,
     sequenceSet_mono (le_max_right a b) hb, hne, hge, rfl⟩⟩

/- **Guy E31**: this problem appears as E31 in Guy's 'Unsolved Problems
    in Number Theory' and as Problem 63 on Green's open problems list. -/
