import Proofs.Erdos85CubeTreeComposition

/-!
# Goal #48 pilot: the cube tree of the hardest H1 residual root

`h1_81494a6ef36d3ec9` (profile 0) defeated every whole-instance solver cap and
was refuted by a 36-leaf adaptive cube tree (2026-09-26).  This file fixes that
tree as a Lean term, checks by kernel `decide` that the 36 solver-side leaf
cubes (sorted by variable, as `cube_bytes` writes them) cover every cube of the
tree, and composes: any CNF whose 36 cube CNFs are UNSAT is UNSAT.

Generated by
`research/problems/erdos-85-wip-01/h1_cert_pilot_20261001/gen_cube_tree_lean.py`
from `h1-cube-pass4-20260926/h1_81494a6ef36d3ec9/run-adaptive/results.json`.
-/

namespace Erdos85

/-- Banked adaptive cube tree of `h1_81494a6ef36d3ec9` (base sha256 860d8af25dee56685ed1007a03c82164a45c864253d08e667d1bd7c3a8ed177d). -/
def h1Cube81494aTree : CubeTree :=
  (.split 355
    (.split 353
      (.split 412
        (.split 381
          (.split 481
            .leaf
            .leaf)
          (.split 380
            .leaf
            .leaf))
        (.split 442
          (.split 381
            .leaf
            .leaf)
          (.split 411
            .leaf
            .leaf)))
      (.split 352
        (.split 413
          (.split 381
            .leaf
            .leaf)
          (.split 443
            .leaf
            .leaf))
        (.split 351
          (.split 383
            .leaf
            .leaf)
          (.split 350
            .leaf
            .leaf))))
    (.split 385
      (.split 383
        (.split 352
          (.split 441
            .leaf
            .leaf)
          (.split 412
            .leaf
            .leaf))
        (.split 382
          (.split 353
            .leaf
            .leaf)
          (.split 381
            .leaf
            .leaf)))
      (.split 415
        (.split 413
          (.split 352
            .leaf
            .leaf)
          (.split 412
            .leaf
            (.split 411
              .leaf
              .leaf)))
        (.split 445
          (.split 443
            .leaf
            .leaf)
          (.split 353
            .leaf
            (.split 383
              .leaf
              (.split 352
                .leaf
                (.split 413
                  .leaf
                  .leaf))))))))

/-- Solver-side leaf cubes (node ids [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 63, 64, 65, 67, 69, 70]), literals sorted by variable as in `cube_bytes`. -/
def h1Cube81494aCubes : List (List Int) := [
  [354, 356, 382, 413, 482],
  [354, 356, 382, 413, -482],
  [354, 356, 381, -382, 413],
  [354, 356, -381, -382, 413],
  [354, 356, 382, -413, 443],
  [354, 356, -382, -413, 443],
  [354, 356, 412, -413, -443],
  [354, 356, -412, -413, -443],
  [353, -354, 356, 382, 414],
  [353, -354, 356, -382, 414],
  [353, -354, 356, -414, 444],
  [353, -354, 356, -414, -444],
  [352, -353, -354, 356, 384],
  [352, -353, -354, 356, -384],
  [351, -352, -353, -354, 356],
  [-351, -352, -353, -354, 356],
  [353, -356, 384, 386, 442],
  [353, -356, 384, 386, -442],
  [-353, -356, 384, 386, 413],
  [-353, -356, 384, 386, -413],
  [354, -356, 383, -384, 386],
  [-354, -356, 383, -384, 386],
  [-356, 382, -383, -384, 386],
  [-356, -382, -383, -384, 386],
  [353, -356, -386, 414, 416],
  [-353, -356, -386, 414, 416],
  [-356, -386, 413, -414, 416],
  [-356, -386, -416, 444, 446],
  [-356, -386, -416, -444, 446],
  [354, -356, -386, -416, -446],
  [-356, -386, 412, -413, -414, 416],
  [-356, -386, -412, -413, -414, 416],
  [-354, -356, 384, -386, -416, -446],
  [353, -354, -356, -384, -386, -416, -446],
  [-353, -354, -356, -384, -386, 414, -416, -446],
  [-353, -354, -356, -384, -386, -414, -416, -446]]

/-- The banked `input/table.json` of `h1_81494a6ef36d3ec9`
(sha256 dc7dbd279417863f1e96bba1a378f27f435179623f3ed55caf18eabf721a4f2d),
as `(c, j) ↦ n` entries. -/
def h1Cube81494aTableEntries : List ((Nat × Nat) × Nat) := [
    ((0, 4), 1),
    ((0, 5), 1),
    ((0, 6), 1),
    ((0, 7), 1),
    ((1, 4), 1),
    ((1, 5), 1),
    ((1, 6), 1),
    ((1, 7), 1),
    ((2, 4), 1),
    ((2, 5), 1),
    ((2, 6), 1),
    ((2, 7), 1),
    ((3, 4), 1),
    ((3, 5), 1),
    ((3, 6), 1),
    ((3, 7), 1)]

/-- The miss table read exactly as the `v2cnf` emitter's `tableOfEntries`. -/
def h1Cube81494aTable : OneHighMissTable := fun c j =>
  match h1Cube81494aTableEntries.find? (fun e => e.1.1 = c ∧ e.1.2 = j) with
  | some e => e.2
  | none => 0

/-- The base CNF of the pilot root, generated in Lean. -/
def h1Cube81494aBaseCnf : Std.Sat.CNF Nat := oneHighFamilyV2SatCnf 0 h1Cube81494aTable

theorem h1Cube81494aTree_leafCount : h1Cube81494aTree.leafCount = 36 := by decide

theorem h1Cube81494aCubes_length : h1Cube81494aCubes.length = 36 := by decide

set_option maxRecDepth 100000 in
theorem h1Cube81494a_cover :
    ∀ c ∈ h1Cube81494aTree.cubes, ∃ d ∈ h1Cube81494aCubes, ∀ l ∈ d, l ∈ c := by
  decide

/-- Composition for the pilot tree: the 36 leaf cube CNFs refute the base. -/
theorem cnf_unsat_of_h1Cube81494a (cnf : Std.Sat.CNF Nat)
    (hleaf : ∀ d ∈ h1Cube81494aCubes, (cubeCnf cnf d).Unsat) : cnf.Unsat :=
  cnf_unsat_of_cubeTree cnf h1Cube81494aTree h1Cube81494aCubes
    h1Cube81494a_cover hleaf

end Erdos85
