/-
Erdős Problem #649: Greatest Prime Factors of Consecutive Integers

Source: https://erdosproblems.com/649
Status: SOLVED (Disproved)

Statement:
Let P(m) denote the greatest prime factor of m.
Is it true that, for any two primes p, q, there exists some integer n
such that P(n) = p and P(n+1) = q?

Answer: NO (DISPROVED)

Counterexamples:
1. p = 2, q = 7: No solution exists since 2^k ≢ -1 (mod 7) for any k.
2. Alan Tong: For any prime p, infinitely many primes q exist where the statement fails.
3. p = 19, q = 2: Fails when 2 is a primitive root modulo 19.

Key Insight:
The problem fails due to quadratic reciprocity and primitive root obstructions.
If 2 is a primitive root modulo q, then 2^k ≡ -1 (mod q) requires the order of 2
to divide 2k but not k, which imposes strong constraints.

References:
- Erdős [Er95c]: Original problem statement
- Mahler (1935): Growth of P(n(n+1))
- Rotkiewicz [Ro64b]: Primitive roots
-/

import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.FieldTheory.Finite.Basic

open Nat BigOperators Finset

namespace Erdos649

/-
## Part I: Greatest Prime Factor

P(m) is the largest prime dividing m.
-/

/--
**Greatest Prime Factor** P(m):
The largest prime number that divides m.

For m = 1, we define P(1) = 0 by convention.
For m > 1, P(m) is the maximum of the prime factors of m.

Examples:
- P(12) = P(2² · 3) = 3
- P(100) = P(2² · 5²) = 5
- P(2^k) = 2 for all k ≥ 1
-/
/-- Greatest prime factor of n: the last element of the sorted prime factorization.
    Returns 0 for n ≤ 1. Defined using Mathlib's `Nat.primeFactorsList`. -/
def greatestPrimeFactor (n : ℕ) : ℕ := n.primeFactorsList.getLast?.getD 0

-- Notation for greatest prime factor
notation "P(" m ")" => greatestPrimeFactor m

/-- The primeFactorsList of n > 1 is nonempty. -/
private lemma primeFactorsList_ne_nil' {n : ℕ} (hn : n > 1) :
    n.primeFactorsList ≠ [] := by
  intro h; have := Nat.primeFactorsList_eq_nil.mp h; omega

/-- P(n) is a member of primeFactorsList when n > 1. -/
private lemma gpf_mem_factors' {n : ℕ} (hn : n > 1) :
    P(n) ∈ n.primeFactorsList := by
  unfold greatestPrimeFactor
  have hne := primeFactorsList_ne_nil' hn
  have : n.primeFactorsList.getLast? = some (n.primeFactorsList.getLast hne) :=
    List.getLast?_eq_getLast hne
  simp [this]; exact List.getLast_mem hne

/-- P(1) = 0 by convention. Proved by computation. -/
theorem gpf_one : P(1) = 0 := by native_decide

/-- P(m) divides m for m > 1. Proved from Mathlib's primeFactorsList API. -/
theorem gpf_divides (m : ℕ) (hm : m > 1) : P(m) ∣ m :=
  (Nat.mem_primeFactorsList (by omega) |>.mp (gpf_mem_factors' hm)).2

/-- P(m) is prime for m > 1. Proved from Mathlib's primeFactorsList API. -/
theorem gpf_is_prime (m : ℕ) (hm : m > 1) : (P(m)).Prime :=
  (Nat.mem_primeFactorsList (by omega) |>.mp (gpf_mem_factors' hm)).1

/-- P(p^k) = p for prime p and k ≥ 1. -/
theorem gpf_prime_power (p k : ℕ) (hp : p.Prime) (hk : k ≥ 1) : P(p ^ k) = p := by
  simp [greatestPrimeFactor, Nat.primeFactorsList_prime_pow hp (by omega : 0 < k)]

/-- P(p) = p for prime p. -/
theorem gpf_prime (p : ℕ) (hp : p.Prime) : P(p) = p := by
  have h := gpf_prime_power p 1 hp (by omega)
  simpa [pow_one] using h

/-- P(m * n) = max(P(m), P(n)) for m, n > 1. -/
/-
## Part II: The Erdős Conjecture

The original question: Can we always find n with P(n) = p and P(n+1) = q?
-/

/--
**Erdős's Conjecture (DISPROVED):**
For any two primes p, q, there exists n such that P(n) = p and P(n+1) = q.

This was shown to be FALSE.
-/
def ErdosConjecture649 : Prop :=
  ∀ p q : ℕ, p.Prime → q.Prime →
    ∃ n : ℕ, n > 0 ∧ P(n) = p ∧ P(n + 1) = q

/-
## Part III: The Counterexample p = 2, q = 7

The simplest counterexample: there is no n with P(n) = 2 and P(n+1) = 7.
-/

/--
If P(n) = 2, then n = 2^k for some k ≥ 1.
(The only numbers whose greatest prime factor is 2 are powers of 2.)
-/
axiom gpf_eq_two_iff (n : ℕ) (hn : n > 1) :
    P(n) = 2 ↔ ∃ k : ℕ, k ≥ 1 ∧ n = 2 ^ k

/--
If P(n+1) = 7 and n = 2^k, then 7 | (2^k + 1).
-/
axiom consecutive_gpf_divides (k : ℕ) (hk : k ≥ 1) :
    P(2 ^ k + 1) = 7 → 7 ∣ (2 ^ k + 1)

/--
**Key Number-Theoretic Fact:**
2^k ≢ -1 (mod 7) for all k ≥ 0.

The powers of 2 modulo 7 cycle: 1, 2, 4, 1, 2, 4, ...
The value -1 ≡ 6 (mod 7) never appears.

This is because ord_7(2) = 3 which is odd, so -1 is not in the cyclic subgroup generated by 2.
-/
theorem two_power_mod_seven (k : ℕ) : (2 ^ k : ZMod 7) ≠ 6 := by
  have h3 : (2 : ZMod 7) ^ 3 = 1 := by decide
  have hmod : (2 : ZMod 7) ^ k = (2 : ZMod 7) ^ (k % 3) := by
    conv_lhs => rw [← Nat.div_add_mod k 3]
    rw [pow_add, pow_mul, h3, one_pow, one_mul]
  rw [hmod]
  have : k % 3 = 0 ∨ k % 3 = 1 ∨ k % 3 = 2 := by omega
  rcases this with rfl | rfl | rfl <;> decide

/-- 7 does not divide 2^k + 1 for any k. -/
theorem seven_not_divide_two_pow_plus_one (k : ℕ) : ¬(7 ∣ (2 ^ k + 1)) := by
  intro hdvd
  have h6 := two_power_mod_seven k
  have h0 : ((2 ^ k + 1 : ℕ) : ZMod 7) = 0 := by
    rwa [ZMod.natCast_zmod_eq_zero_iff_dvd]
  have h1 : (2 : ZMod 7) ^ k = -1 := by
    have : (2 : ZMod 7) ^ k + 1 = 0 := by push_cast at h0; exact h0
    have := eq_neg_of_add_eq_zero_left this; simpa using this
  rw [h1, show (-1 : ZMod 7) = 6 from by decide] at h6
  exact h6 rfl

/--
**Counterexample:** No n exists with P(n) = 2 and P(n+1) = 7.
-/
theorem no_solution_2_7 : ¬∃ n : ℕ, n > 0 ∧ P(n) = 2 ∧ P(n + 1) = 7 := by
  intro ⟨n, hn_pos, hPn, hPn1⟩
  -- P(n) = 2 implies n = 2^k for some k ≥ 1
  -- We need n > 1 (since P(1) = 0 by convention)
  have hn_gt : n > 1 := by
    by_contra h
    push_neg at h
    have : n = 0 ∨ n = 1 := by omega
    rcases this with rfl | rfl
    · exact (Nat.not_lt_zero 0 hn_pos)
    · -- P(1) = 0 by gpf_one, but hPn says P(1) = 2
      have h0 : P(1) = 0 := gpf_one
      rw [h0] at hPn
      exact absurd hPn (by norm_num)
  have ⟨k, hk, hn_eq⟩ := (gpf_eq_two_iff n hn_gt).mp hPn
  -- Then P(n+1) = 7 implies 7 | (2^k + 1)
  rw [hn_eq] at hPn1
  have hdiv := consecutive_gpf_divides k hk hPn1
  -- But 7 ∤ (2^k + 1)
  exact seven_not_divide_two_pow_plus_one k hdiv

/-
## Part IV: General Obstruction Theory

The failure is not just for (2, 7) - there are infinitely many failing pairs.
-/

/--
**Primitive Root Obstruction:**
If 2 is a primitive root modulo prime q > 2, then there are constraints on
which primes p can satisfy P(n) = p, P(n+1) = q.
-/
/- primitive_root_obstruction: if 2 is a primitive root mod prime q > 2,
    there are constraints on which primes p can satisfy P(n) = p, P(n+1) = q. -/

/--
**Tong's Theorem:**
For any prime p, there exist infinitely many primes q such that
no n exists with P(n) = p and P(n+1) = q.
-/
axiom tong_theorem (p : ℕ) (hp : p.Prime) :
    ∃ Q : Set ℕ, Q.Infinite ∧ (∀ q ∈ Q, q.Prime) ∧
      ∀ q ∈ Q, ¬∃ n : ℕ, n > 0 ∧ P(n) = p ∧ P(n + 1) = q

/--
**Specific Counterexample: p = 19, q = 2**
When 2 is a primitive root modulo 19, there is no n with P(n) = 19 and P(n+1) = 2.
-/
/-
## Part V: Positive Results

Some pairs (p, q) DO have solutions.
-/

/--
**Existence for small primes:**
For p = 2, q = 3: n = 8 works since P(8) = P(2³) = 2 and P(9) = P(3²) = 3.
-/
theorem solution_2_3 : ∃ n : ℕ, n > 0 ∧ P(n) = 2 ∧ P(n + 1) = 3 := by
  use 8
  constructor
  · norm_num
  constructor
  · -- P(8) = P(2^3) = 2
    have : (8 : ℕ) = 2 ^ 3 := by norm_num
    rw [this]
    exact gpf_prime_power 2 3 Nat.prime_two (by norm_num)
  · -- P(9) = P(3^2) = 3
    have : (9 : ℕ) = 3 ^ 2 := by norm_num
    have h9 : (8 : ℕ) + 1 = 9 := by norm_num
    rw [h9, this]
    exact gpf_prime_power 3 2 Nat.prime_three (by norm_num)

/--
**Existence for p = 3, q = 2:**
n = 3 works since P(3) = 3 and P(4) = 2.
-/
theorem solution_3_2 : ∃ n : ℕ, n > 0 ∧ P(n) = 3 ∧ P(n + 1) = 2 := by
  use 3
  constructor
  · norm_num
  constructor
  · exact gpf_prime 3 Nat.prime_three
  · -- P(4) = P(2^2) = 2
    have : (4 : ℕ) = 2 ^ 2 := by norm_num
    have h4 : (3 : ℕ) + 1 = 4 := by norm_num
    rw [h4, this]
    exact gpf_prime_power 2 2 Nat.prime_two (by norm_num)

/-
## Part VI: Growth of P(n(n+1))

Related result by Mahler (1935).
-/

/--
**Mahler's Theorem (1935):**
The largest prime factor of n(n+1) satisfies
P(n(n+1)) ~ log log n as n → ∞.

More precisely, P(n(n+1)) → ∞ but grows very slowly.
-/
axiom mahler_growth :
    ∀ C : ℕ, ∃ N : ℕ, ∀ n ≥ N, P(n * (n + 1)) > C

/--
**Corollary:** For any prime p, there exist infinitely many n
with P(n(n+1)) > p.
-/
theorem infinitely_many_large_gpf (p : ℕ) :
    ∀ N : ℕ, ∃ n ≥ N, P(n * (n + 1)) > p := by
  intro N
  obtain ⟨M, hM⟩ := mahler_growth p
  use max N M
  constructor
  · exact le_max_left N M
  · exact hM (max N M) (le_max_right N M)

/-
## Part VII: Quadratic Reciprocity Connection

The deeper reason for the counterexamples.
-/

/--
**Quadratic Residue Obstruction:**
If P(n) = p (so n is a p-smooth number times a power of p),
and P(n+1) = q, this imposes constraints via the Legendre symbol.
-/
/- quadratic_residue_constraint: if P(n) = p and P(n+1) = q, this imposes
    constraints via the Legendre symbol (quadratic residue structure). -/

/--
**Order of 2 modulo 7:**
The multiplicative order of 2 in (Z/7Z)* is 3.
Powers cycle: 2^0 = 1, 2^1 = 2, 2^2 = 4, 2^3 = 1, ...
-/
theorem order_2_mod_7 : ∃ d : ℕ, d = 3 ∧ ∀ k : ℕ, (2 ^ k : ZMod 7) = (2 ^ (k % d) : ZMod 7) :=
  ⟨3, rfl, fun k => by
    conv_lhs => rw [← Nat.div_add_mod k 3]
    rw [pow_add, pow_mul, show (2 : ZMod 7) ^ 3 = 1 from by decide, one_pow, one_mul]⟩

/--
Since ord_7(2) = 3, which is odd, 2^k ≡ -1 (mod 7) has no solution.
(Would need ord_7(2) to be even for -1 to appear.)
-/
theorem odd_order_no_minus_one : ∀ k : ℕ, (2 ^ k : ZMod 7) ≠ -1 := by
  intro k
  have h6 : (-1 : ZMod 7) = 6 := by native_decide
  rw [h6]
  exact two_power_mod_seven k

/-
## Part VIII: Main Results
-/

/--
**Erdős Problem #649: DISPROVED**

The conjecture that for any primes p, q there exists n with
P(n) = p and P(n+1) = q is FALSE.

Counterexamples:
1. (p, q) = (2, 7): No solution since 2^k ≢ -1 (mod 7)
2. (p, q) = (19, 2): No solution when 2 is primitive root mod 19
3. Tong: For any p, infinitely many q fail
-/
theorem erdos_649 : ¬ErdosConjecture649 := by
  intro hconj
  -- The conjecture claims all (p, q) pairs work
  -- But (2, 7) has no solution
  have hp7 : Nat.Prime 7 := by native_decide
  have h27 := hconj 2 7 Nat.prime_two hp7
  obtain ⟨n, hn_pos, hPn, hPn1⟩ := h27
  have hfalse := no_solution_2_7
  exact hfalse ⟨n, hn_pos, hPn, hPn1⟩

/-- Some prime pairs DO work. -/
theorem some_pairs_work :
    (∃ n : ℕ, n > 0 ∧ P(n) = 2 ∧ P(n + 1) = 3) ∧
    (∃ n : ℕ, n > 0 ∧ P(n) = 3 ∧ P(n + 1) = 2) :=
  ⟨solution_2_3, solution_3_2⟩

/-- The failure is systemic: infinitely many pairs fail. -/
theorem infinitely_many_failures :
    ∀ p : ℕ, p.Prime → ∃ Q : Set ℕ, Q.Infinite ∧
      ∀ q ∈ Q, q.Prime ∧ ¬∃ n : ℕ, n > 0 ∧ P(n) = p ∧ P(n + 1) = q := by
  intro p hp
  obtain ⟨Q, hQ_inf, hQ_prime, hQ_fail⟩ := tong_theorem p hp
  exact ⟨Q, hQ_inf, fun q hq => ⟨hQ_prime q hq, hQ_fail q hq⟩⟩

end Erdos649
