import Proofs.Erdos85ExcessDefectRegular

/-!
# Defect decomposition across an induced exterior

For a `C₄`-free graph, delete an arbitrary finite vertex set `U`.  Two
remaining vertices have no common neighbor in the induced exterior exactly
when they either had no common neighbor in the parent, or have a common
neighbor in `U`.  In the second-order defect language this says that the
exterior defect relation is the union of the restricted parent defect
relation and the equivalence cliques generated by deleted common neighbors.

In the saturated minimum-layer application every exterior vertex has a
unique deleted neighbor, so the added relation is precisely the disjoint
union of owner-fiber cliques, i.e. the graph form of
`D_ext = D_parent|ext + CᵀC - I`.
-/

open SimpleGraph

namespace Erdos85

noncomputable section

def finsetExteriorVertex {V : Type*} [DecidableEq V] (U : Finset V) :=
  {x : V // x ∉ U}

instance finsetExteriorVertexDecidableEq
    {V : Type*} [DecidableEq V] (U : Finset V) :
    DecidableEq (finsetExteriorVertex U) :=
  Subtype.instDecidableEq

instance finsetExteriorVertexFintype
    {V : Type*} [Fintype V] [DecidableEq V] (U : Finset V) :
    Fintype (finsetExteriorVertex U) := by
  unfold finsetExteriorVertex
  infer_instance

def finsetExteriorGraph
    {V : Type*} [Fintype V] [DecidableEq V]
    (G : SimpleGraph V) [DecidableRel G.Adj] (U : Finset V) :
    SimpleGraph (finsetExteriorVertex U) :=
  G.comap Subtype.val

/-- In a `C₄`-free graph, the second-order defect relation is exactly
vanishing of the common-neighbor count. -/
theorem secondOrderDefectGraph_adj_iff_card_common_eq_zero
    {V : Type*} [Fintype V] [DecidableEq V]
    (G : SimpleGraph V) [DecidableRel G.Adj]
    [DecidableRel (antipodalGraph G).Adj]
    [DecidableRel (triangleFreeEdgeGraph G).Adj]
    (hfree : ¬containsC4 V G) {x y : V} (hxy : x ≠ y) :
    (secondOrderDefectGraph G).Adj x y ↔
      (G.neighborFinset x ∩ G.neighborFinset y).card = 0 := by
  have hcommon := card_common_eq_if_secondOrderDefect G hfree x y hxy
  constructor
  · intro hD
    have hmem : y ∈ (secondOrderDefectGraph G).neighborFinset x :=
      ((secondOrderDefectGraph G).mem_neighborFinset x y).mpr hD
    simpa [hmem] using hcommon
  · intro hzero
    by_contra hD
    have hmem : y ∉ (secondOrderDefectGraph G).neighborFinset x := by
      simpa [SimpleGraph.mem_neighborFinset] using hD
    rw [if_neg hmem] at hcommon
    omega

/-- **Exterior defect decomposition.**  Deleting `U` adds exactly those
defect edges whose endpoints share a deleted common neighbor. -/
theorem finsetExterior_secondOrderDefect_adj_iff
    {V : Type*} [Fintype V] [DecidableEq V]
    (G : SimpleGraph V) [DecidableRel G.Adj]
    [DecidableRel (antipodalGraph G).Adj]
    [DecidableRel (triangleFreeEdgeGraph G).Adj]
    (U : Finset V)
    [DecidableRel (finsetExteriorGraph G U).Adj]
    [DecidableRel (antipodalGraph (finsetExteriorGraph G U)).Adj]
    [DecidableRel (triangleFreeEdgeGraph (finsetExteriorGraph G U)).Adj]
    (hfree : ¬containsC4 V G)
    {x y : finsetExteriorVertex U} (hxy : x ≠ y) :
    (secondOrderDefectGraph (finsetExteriorGraph G U)).Adj x y ↔
      (secondOrderDefectGraph G).Adj x.1 y.1 ∨
        ∃ u ∈ U, G.Adj x.1 u ∧ G.Adj y.1 u := by
  let R := finsetExteriorGraph G U
  have hfreeR : ¬containsC4 (finsetExteriorVertex U) R := by
    intro hC4
    obtain ⟨f, hf, hadj⟩ := hC4
    apply hfree
    refine ⟨Subtype.val ∘ f, Subtype.val_injective.comp hf, ?_⟩
    intro i j hij
    exact hadj i j hij
  rw [secondOrderDefectGraph_adj_iff_card_common_eq_zero
    R hfreeR hxy]
  have hxyVal : x.1 ≠ y.1 := fun h => hxy (Subtype.ext h)
  rw [secondOrderDefectGraph_adj_iff_card_common_eq_zero
    G hfree hxyVal]
  constructor
  · intro hzero
    by_cases hparent :
        (G.neighborFinset x.1 ∩ G.neighborFinset y.1).card = 0
    · exact Or.inl hparent
    · right
      have hnonempty :
          (G.neighborFinset x.1 ∩ G.neighborFinset y.1).Nonempty :=
        Finset.card_ne_zero.mp hparent
      obtain ⟨u, hu⟩ := hnonempty
      have huAdj : G.Adj x.1 u ∧ G.Adj y.1 u := by
        obtain ⟨hxu, hyu⟩ := Finset.mem_inter.mp hu
        exact ⟨(G.mem_neighborFinset x.1 u).mp hxu,
          (G.mem_neighborFinset y.1 u).mp hyu⟩
      refine ⟨u, ?_, huAdj⟩
      by_contra huU
      let w : finsetExteriorVertex U := ⟨u, huU⟩
      have hw : w ∈ R.neighborFinset x ∩ R.neighborFinset y := by
        apply Finset.mem_inter.mpr
        exact ⟨(R.mem_neighborFinset x w).mpr huAdj.1,
          (R.mem_neighborFinset y w).mpr huAdj.2⟩
      have hempty := Finset.card_eq_zero.mp hzero
      rw [hempty] at hw
      simp at hw
  · rintro (hparent | ⟨u, huU, hxu, hyu⟩)
    · apply Finset.card_eq_zero.mpr
      apply Finset.not_nonempty_iff_eq_empty.mp
      rintro ⟨w, hw⟩
      have hwParent : w.1 ∈
          G.neighborFinset x.1 ∩ G.neighborFinset y.1 := by
        obtain ⟨hxw, hyw⟩ := Finset.mem_inter.mp hw
        apply Finset.mem_inter.mpr
        exact ⟨(G.mem_neighborFinset x.1 w.1).mpr
            ((R.mem_neighborFinset x w).mp hxw),
          (G.mem_neighborFinset y.1 w.1).mpr
            ((R.mem_neighborFinset y w).mp hyw)⟩
      have hempty := Finset.card_eq_zero.mp hparent
      rw [hempty] at hwParent
      simp at hwParent
    · apply Finset.card_eq_zero.mpr
      apply Finset.not_nonempty_iff_eq_empty.mp
      rintro ⟨w, hw⟩
      obtain ⟨hxw, hyw⟩ := Finset.mem_inter.mp hw
      have hwParent : w.1 ∈
          G.neighborFinset x.1 ∩ G.neighborFinset y.1 :=
        Finset.mem_inter.mpr
          ⟨(G.mem_neighborFinset x.1 w.1).mpr
              ((R.mem_neighborFinset x w).mp hxw),
            (G.mem_neighborFinset y.1 w.1).mpr
              ((R.mem_neighborFinset y w).mp hyw)⟩
      have huParent : u ∈
          G.neighborFinset x.1 ∩ G.neighborFinset y.1 :=
        Finset.mem_inter.mpr
          ⟨(G.mem_neighborFinset x.1 u).mpr hxu,
            (G.mem_neighborFinset y.1 u).mpr hyu⟩
      have heq := Finset.card_le_one.mp
        (common_le_one_of_not_containsC4 hfree x.1 y.1 hxyVal)
          w.1 hwParent u huParent
      exact w.2 (heq ▸ huU)

end

end Erdos85
