import Proofs.Erdos85OrderFortyNineSmallHighAdaptiveSixthOrbitTransport

/-! # Finite normal form for the adaptive sixth frontier -/

namespace Erdos85

structure OrderFortyNineAdaptiveSixthCell where
  li : Fin 8
  ri : Fin 8
  ai : Fin 8
  bi : Fin 8
  ci : Fin 8
  di : Fin 8
  ei : Fin 8
deriving DecidableEq, Repr

private def orderFortyNineAdaptiveSixthCompactLive (i : Fin 8) : Bool :=
  i = 2 || 4 ≤ i.val

private def orderFortyNineAdaptiveSixthCompactMate (i : Fin 8) : Fin 8 :=
  if i = 4 then 5 else if i = 5 then 4 else if i = 6 then 7 else
    if i = 7 then 6 else i

private def orderFortyNineAdaptiveSixthCompactParent
    (c : OrderFortyNineAdaptiveSixthCell) : Bool :=
  4 ≤ c.li.val && 2 ≤ c.ri.val && c.ri != 3 && c.li != c.ri &&
  orderFortyNineAdaptiveSixthCompactLive c.ai &&
  orderFortyNineAdaptiveSixthCompactLive c.bi && c.ai != c.bi &&
  c.ai != c.li && c.ai != c.ri && c.bi != c.li && c.bi != c.ri &&
  c.ai != orderFortyNineAdaptiveSixthCompactMate c.ri &&
  !(((c.ri = 2 && c.ai = orderFortyNineAdaptiveSixthCompactMate c.li) ||
      (c.ai = 2 && c.ri = orderFortyNineAdaptiveSixthCompactMate c.li)) &&
    c.bi != 2 && c.bi != c.li &&
      c.bi != orderFortyNineAdaptiveSixthCompactMate c.li) &&
  orderFortyNineAdaptiveSixthCompactLive c.ci &&
  c.ci != c.li && c.ci != c.ri && c.ci != c.ai && c.ci != c.bi

def orderFortyNineAdaptiveSixthCompactResidual
    (c : OrderFortyNineAdaptiveSixthCell) : Bool :=
  orderFortyNineAdaptiveSixthCompactParent c &&
  orderFortyNineThreeHighB1AdaptiveSixthLiveIndex
    c.ri c.ai c.bi c.ci c.di &&
  orderFortyNineThreeHighB1AdaptiveSixthLiveIndex
    c.ri c.ai c.bi c.ci c.ei && c.di != c.ei

def orderFortyNineAdaptiveSixthTransformGenerator
    (g : OrderFortyNineAdaptiveSixthOrbitGenerator)
    (c : OrderFortyNineAdaptiveSixthCell) : OrderFortyNineAdaptiveSixthCell :=
  let t := orderFortyNineAdaptiveSixthOrbitTransform
    g c.li c.ri c.ai c.bi c.ci c.di c.ei
  ⟨t.1, t.2.1, t.2.2.1, t.2.2.2.1, t.2.2.2.2.1,
    t.2.2.2.2.2.1, t.2.2.2.2.2.2⟩

/-- The sixteen elements generated by the three matching symmetries and the
swap of the two sixth rows. -/
def orderFortyNineAdaptiveSixthOrbitElement
    (k : Fin 16) (c : OrderFortyNineAdaptiveSixthCell) :
    OrderFortyNineAdaptiveSixthCell :=
  let c := if k.val % 2 = 1 then
    orderFortyNineAdaptiveSixthTransformGenerator 0 c else c
  let c := if k.val / 2 % 2 = 1 then
    orderFortyNineAdaptiveSixthTransformGenerator 1 c else c
  let c := if k.val / 4 % 2 = 1 then
    orderFortyNineAdaptiveSixthTransformGenerator 2 c else c
  if k.val / 8 % 2 = 1 then
    orderFortyNineAdaptiveSixthTransformGenerator 3 c else c

private def orderFortyNineAdaptiveSixthCanonicalParent
    (c : OrderFortyNineAdaptiveSixthCell) : Bool :=
  (c.li = 4 && c.ri = 2 && c.ai = 6 && c.bi = 5 && c.ci = 7) ||
  (c.li = 4 && c.ri = 2 && c.ai = 6 && c.bi = 7 && c.ci = 5) ||
  (c.li = 4 && c.ri = 5 && c.ai = 6 && c.bi = 2 && c.ci = 7) ||
  (c.li = 4 && c.ri = 5 && c.ai = 6 && c.bi = 7 && c.ci = 2) ||
  (c.li = 4 && c.ri = 6 && c.ai = 2 && c.bi = 5 && c.ci = 7) ||
  (c.li = 4 && c.ri = 6 && c.ai = 2 && c.bi = 7 && c.ci = 5) ||
  (c.li = 4 && c.ri = 6 && c.ai = 5 && c.bi = 2 && c.ci = 7) ||
  (c.li = 4 && c.ri = 6 && c.ai = 5 && c.bi = 7 && c.ci = 2)

def orderFortyNineAdaptiveSixthCanonicalRepresentative
    (c : OrderFortyNineAdaptiveSixthCell) : Bool :=
  orderFortyNineAdaptiveSixthCompactResidual c &&
    orderFortyNineAdaptiveSixthCanonicalParent c && c.di.val < c.ei.val

/-- A deterministic word sending the fifth-parent part to its canonical
section.  The three bits select the matching swaps in generator order. -/
private def orderFortyNineAdaptiveSixthParentNormalIndex
    (c : OrderFortyNineAdaptiveSixthCell) : Fin 8 :=
  let b0 := if c.li.val < 6 then c.li = 5 else
    !(c.ri = 5 || c.ai = 5)
  let b1 := if c.li.val < 6 then c.ri = 7 || c.ai = 7 else c.li = 7
  let b2 := 6 ≤ c.li.val
  Fin.ofNat 8 ((if b0 then 1 else 0) + (if b1 then 2 else 0) +
    (if b2 then 4 else 0))

/-- The fourth bit orders the two sixth-row selectors after the fifth-parent
normalization. -/
def orderFortyNineAdaptiveSixthNormalIndex
    (c : OrderFortyNineAdaptiveSixthCell) : Fin 16 :=
  let k8 := orderFortyNineAdaptiveSixthParentNormalIndex c
  let k : Fin 16 := ⟨k8.val, lt_trans k8.isLt (by decide)⟩
  let t := orderFortyNineAdaptiveSixthOrbitElement k c
  Fin.ofNat 16 (k.val + if t.di.val < t.ei.val then 0 else 8)

theorem orderFortyNineAdaptiveSixthCanonicalRepresentative_count :
    (((((((Finset.univ : Finset (Fin 8)).product Finset.univ).product
      Finset.univ).product Finset.univ).product Finset.univ).product
      Finset.univ).product Finset.univ |>.filter fun p =>
        orderFortyNineAdaptiveSixthCanonicalRepresentative
          ⟨p.1.1.1.1.1.1, p.1.1.1.1.1.2, p.1.1.1.1.2,
            p.1.1.1.2, p.1.1.2, p.1.2, p.2⟩).card = 48 := by
  native_decide

theorem orderFortyNineAdaptiveSixthCompactResidual_has_normalForm
    (c : OrderFortyNineAdaptiveSixthCell)
    (hlive : orderFortyNineAdaptiveSixthCompactResidual c = true) :
    ∃ k : Fin 16,
      orderFortyNineAdaptiveSixthCanonicalRepresentative
        (orderFortyNineAdaptiveSixthOrbitElement k c) = true := by
  refine ⟨orderFortyNineAdaptiveSixthNormalIndex c, ?_⟩
  rcases c with ⟨li, ri, ai, bi, ci, di, ei⟩
  native_decide +revert

private theorem orderFortyNineAdaptiveSixthCompactParent_of_fifthResidual_aux
    (li ri ai bi ci : Fin 8)
    (hfifth : orderFortyNineThreeHighB1AdaptiveFifthResidual
      li ri ai bi ci = true) :
    orderFortyNineAdaptiveSixthCompactParent
      ⟨li, ri, ai, bi, ci, 0, 0⟩ = true := by
  native_decide +revert

theorem orderFortyNineAdaptiveSixthCompactParent_of_fifthResidual
    (c : OrderFortyNineAdaptiveSixthCell)
    (hfifth : orderFortyNineThreeHighB1AdaptiveFifthResidual
      c.li c.ri c.ai c.bi c.ci = true) :
    orderFortyNineAdaptiveSixthCompactParent c = true := by
  simpa [orderFortyNineAdaptiveSixthCompactParent] using
    orderFortyNineAdaptiveSixthCompactParent_of_fifthResidual_aux
      c.li c.ri c.ai c.bi c.ci hfifth

theorem orderFortyNineAdaptiveSixthResidual_has_normalForm
    (c : OrderFortyNineAdaptiveSixthCell)
    (hlive : orderFortyNineThreeHighB1AdaptiveSixthResidual
      c.li c.ri c.ai c.bi c.ci c.di c.ei = true) :
    ∃ k : Fin 16,
      orderFortyNineAdaptiveSixthCanonicalRepresentative
        (orderFortyNineAdaptiveSixthOrbitElement k c) = true := by
  unfold orderFortyNineThreeHighB1AdaptiveSixthResidual at hlive
  simp only [Bool.and_eq_true] at hlive
  have hfifth : orderFortyNineThreeHighB1AdaptiveFifthResidual
      c.li c.ri c.ai c.bi c.ci = true := by
    exact hlive.1.1.1
  have hparent := orderFortyNineAdaptiveSixthCompactParent_of_fifthResidual
    c hfifth
  have hcompact : orderFortyNineAdaptiveSixthCompactResidual c = true := by
    unfold orderFortyNineAdaptiveSixthCompactResidual
    simp only [Bool.and_eq_true]
    exact ⟨⟨⟨hparent, hlive.1.1.2⟩, hlive.1.2⟩, hlive.2⟩
  exact orderFortyNineAdaptiveSixthCompactResidual_has_normalForm c hcompact

end Erdos85
