/-
  The Hypersurface Presentation of the Two-Generator Numerical Semigroup Ring
  (companion to frobenius-number-oq-02-oq-02)

  The gallery entry frobenius-number-oq-02-oq-02
  (`Proofs/FrobeniusNumberOQ02OQ02.lean`) formalizes the *combinatorial* half of
  Kunz's Gorenstein duality: the gap involution of a symmetric numerical
  semigroup forces 2·(#gaps in [0,F]) = F + 1. This companion file records the
  complementary *commutative-algebra* scaffold: the reason `k[t^a, t^b]` is
  Gorenstein is that it is a **complete intersection** — the quotient of
  `k[X₀, X₁]` by the single binomial relation `X₀^b − X₁^a`.

  Mathlib currently has NO Gorenstein-ring / Cohen–Macaulay / canonical-module
  theory, so the literal statement "k[t^a,t^b] is Gorenstein" cannot yet be
  phrased inside Mathlib. This file establishes the algebraic setup of the
  hypersurface presentation, entirely within Mathlib's `MvPolynomial` /
  `Polynomial` API:

  * `phi`              — the presentation map `φ : k[X₀,X₁] → k[t]`,
                         `X₀ ↦ t^a`, `X₁ ↦ t^b`.
  * `range_phi`        — its image is exactly the semigroup ring `k[t^a, t^b]`
                         (`= Algebra.adjoin k {t^a, t^b}`).
  * `relation_mem_ker` — the defining binomial `X₀^b − X₁^a` vanishes under `φ`.
  * `span_le_ker`      — hence `(X₀^b − X₁^a) ⊆ ker φ`, giving the surjection
                         `k[X₀,X₁]/(X₀^b − X₁^a) ↠ k[t^a, t^b]`.

  The reverse inclusion `ker φ ⊆ (X₀^b − X₁^a)` — that this surjection is an
  *isomorphism*, exhibiting the semigroup ring as a genuine hypersurface /
  complete intersection — is the deep monomial-curve kernel computation and is
  recorded as the follow-up open question.

  ## Status: 0 sorries, 0 axioms (Mathlib only).
-/
import Mathlib

open MvPolynomial Polynomial

namespace FrobeniusHypersurfacePresentation

variable (K : Type*) [CommRing K]

/-- The presentation map `φ : k[X₀, X₁] → k[t]` sending `X₀ ↦ t^a` and
`X₁ ↦ t^b`. Its image is the two-generator numerical semigroup ring
`k[t^a, t^b]`. -/
noncomputable def phi (a b : ℕ) : MvPolynomial (Fin 2) K →ₐ[K] Polynomial K :=
  MvPolynomial.aeval ![Polynomial.X ^ a, Polynomial.X ^ b]

@[simp] lemma phi_X0 (a b : ℕ) : phi K a b (X 0) = Polynomial.X ^ a := by
  simp [phi]

@[simp] lemma phi_X1 (a b : ℕ) : phi K a b (X 1) = Polynomial.X ^ b := by
  simp [phi]

/-- **Image = semigroup ring.** The range of `φ` is the `k`-subalgebra generated
by `t^a` and `t^b`; i.e. `φ` realises the numerical semigroup ring `k[t^a, t^b]`
as a quotient of the polynomial ring `k[X₀, X₁]`. -/
theorem range_phi (a b : ℕ) :
    (phi K a b).range = Algebra.adjoin K {Polynomial.X ^ a, Polynomial.X ^ b} := by
  have hr : Set.range (![Polynomial.X ^ a, Polynomial.X ^ b] : Fin 2 → Polynomial K)
      = {Polynomial.X ^ a, Polynomial.X ^ b} := by
    ext p
    simp only [Set.mem_range, Fin.exists_fin_two, Matrix.cons_val_zero, Matrix.cons_val_one,
      Set.mem_insert_iff, Set.mem_singleton_iff]
    tauto
  rw [phi, ← Algebra.adjoin_range_eq_range_aeval, hr]

/-- **The defining relation lies in the kernel.** Under `φ`,
`φ(X₀^b − X₁^a) = (t^a)^b − (t^b)^a = t^{ab} − t^{ab} = 0`. -/
theorem relation_mem_ker (a b : ℕ) :
    phi K a b (X 0 ^ b - X 1 ^ a) = 0 := by
  rw [map_sub, map_pow, map_pow, phi_X0, phi_X1, ← pow_mul, ← pow_mul, Nat.mul_comm b a, sub_self]

/-- **Presentation surjection.** The principal ideal generated by the binomial
`X₀^b − X₁^a` is contained in `ker φ`, so `φ` factors through the quotient,
yielding a surjection `k[X₀,X₁]/(X₀^b − X₁^a) ↠ k[t^a, t^b]`. -/
theorem span_le_ker (a b : ℕ) :
    Ideal.span {(X 0 ^ b - X 1 ^ a : MvPolynomial (Fin 2) K)}
      ≤ RingHom.ker (phi K a b).toRingHom := by
  rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe, RingHom.mem_ker]
  simpa using relation_mem_ker K a b

/-! ### Numerical sanity check: the cuspidal cubic `⟨2, 3⟩` -/

/-- For `⟨2, 3⟩` (Frobenius number `1`) the relation is the cuspidal-cubic
binomial `X₀^3 − X₁^2`, whose image `t^6 − t^6` vanishes. -/
example : phi ℚ 2 3 (X 0 ^ 3 - X 1 ^ 2) = 0 := relation_mem_ker ℚ 2 3

-- Axiom audit: foundational axioms only (no sorryAx, no Lean.ofReduceBool).
#print axioms range_phi
#print axioms span_le_ker

end FrobeniusHypersurfacePresentation
