/-
# Furstenberg Correspondence OQ-03: Polynomial Szemerédi via Bergelson–Leibman

## What This File Contains

A **formalized statement and verified combinatorial backbone** for the
polynomial Szemerédi theorem (Bergelson–Leibman, 1996), the polynomial
extension of Szemerédi's theorem obtained through the Furstenberg
correspondence principle.

Everything in this file is fully machine-checked: **0 axioms, 0 sorries.**
We do NOT assert the deep Bergelson–Leibman theorem itself — that remains an
open formalization target. Instead we:

1. State it precisely as a `Prop`-valued definition (so it can be targeted),
2. Verify the structural lemmas that any proof must use, and
3. Survey the Mathlib recurrence infrastructure that the ergodic-theoretic
   proof builds on.

## The Theorem (Bergelson–Leibman, 1996)

**Combinatorial form.** Let `A ⊆ ℤ` have positive upper Banach density. Let
`p₁, …, p_k ∈ ℤ[X]` be integer polynomials with `pᵢ(0) = 0`. Then there exist
`x ∈ ℤ` and `d ≠ 0` such that

  x + p₁(d), x + p₂(d), …, x + p_k(d) ∈ A.

Taking `pᵢ(d) = i·d` recovers Szemerédi's theorem (arithmetic progressions).
Taking, e.g., `p(d) = d²` gives configurations `{x, x + d²}` — squares.

**Ergodic form (polynomial multiple recurrence).** For a measure-preserving
system `(X, μ, T)`, a set `E` with `μ(E) > 0`, and polynomials `pᵢ` with
`pᵢ(0) = 0`, there exists `n ≠ 0` with

  μ(E ∩ T^{-p₁(n)} E ∩ … ∩ T^{-p_k(n)} E) > 0.

The two forms are linked by the **Furstenberg correspondence principle**
(formalized as an axiom in `FurstenbergCorrespondence.lean`).

## Why The Hypothesis `pᵢ(0) = 0` Is Essential

At `d = 0` every configuration collapses to the single point `x` (verified
below: `config_collapses_at_zero`). The substance of the theorem is finding a
*nontrivial* solution with `d ≠ 0`. The condition `pᵢ(0) = 0` is exactly
"`X ∣ pᵢ`", which we show forces `d ∣ pᵢ(d)` for every `d` — a divisibility
constraint the configuration always satisfies.

## References

- V. Bergelson, A. Leibman, *Polynomial extensions of van der Waerden's and
  Szemerédi's theorems*, J. Amer. Math. Soc. 9 (1996), 725–753.
- H. Furstenberg, *Recurrence in Ergodic Theory and Combinatorial Number
  Theory*, Princeton, 1981.
- B. Host, B. Kra, *Nilpotent Structures in Ergodic Theory*, AMS, 2018.
-/
import Mathlib

namespace FurstenbergOQ03

open Polynomial MeasureTheory Set

/-! ═══════════════════════════════════════════════════════════════════════════════
PART I: POLYNOMIAL CONFIGURATIONS — THE COMBINATORIAL OBJECT
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
A *polynomial configuration* generated by polynomials `p : Fin k → ℤ[X]`, a
base point `x`, and a common difference `d` is the tuple

  `i ↦ x + (p i).eval d`.

For arithmetic progressions one takes `p i = i • X`, giving `x + i·d`.
Bergelson–Leibman allows arbitrary `p i` with no constant term.
-/

/-- The `i`-th point of the polynomial configuration with base `x` and
difference `d`. -/
def configPoint {k : ℕ} (p : Fin k → ℤ[X]) (x d : ℤ) (i : Fin k) : ℤ :=
  x + (p i).eval d

/-- A family of polynomials has *no constant term* when each vanishes at `0`.
This is the standing hypothesis of the Bergelson–Leibman theorem. -/
def NoConstantTerm {k : ℕ} (p : Fin k → ℤ[X]) : Prop :=
  ∀ i, (p i).eval 0 = 0

/-! ### Verified structural lemma 1: collapse at `d = 0` -/

/-- With no constant term, *every* configuration degenerates to the base point
`x` when `d = 0`. This is why the theorem demands a nontrivial `d ≠ 0`: the
solution `d = 0` is always available and carries no combinatorial information. -/
theorem config_collapses_at_zero {k : ℕ} (p : Fin k → ℤ[X])
    (hp : NoConstantTerm p) (x : ℤ) (i : Fin k) :
    configPoint p x 0 i = x := by
  unfold configPoint
  rw [hp i, add_zero]

/-! ### Verified structural lemma 2: vanishing at 0 ↔ divisibility by X -/

/-- `p.eval 0 = 0` is exactly the divisibility `X ∣ p`. This is the algebraic
content of "no constant term", linking the analytic hypothesis to the
factorization `p = X · q`. -/
theorem eval_zero_iff_X_dvd (p : ℤ[X]) : p.eval 0 = 0 ↔ X ∣ p := by
  rw [X_dvd_iff, coeff_zero_eq_eval_zero]

/-! ### Verified structural lemma 3: the divisibility constraint `d ∣ pᵢ(d)` -/

/-- If `p` has no constant term, then `d ∣ p.eval d` for every `d`. Hence each
configuration point satisfies `x + p(d) ≡ x (mod d)`: the polynomial
configuration lives inside a single residue class structure determined by `d`.
This is the elementary obstruction every Bergelson–Leibman configuration
respects. -/
theorem dvd_eval_of_noConstantTerm {p : ℤ[X]} (hp : p.eval 0 = 0) (d : ℤ) :
    d ∣ p.eval d := by
  obtain ⟨q, rfl⟩ := (eval_zero_iff_X_dvd p).mp hp
  rw [eval_mul, eval_X]
  exact dvd_mul_right d (q.eval d)

/-- Each configuration point is congruent to the base point modulo `d`. -/
theorem configPoint_sub_dvd {k : ℕ} {p : Fin k → ℤ[X]}
    (hp : NoConstantTerm p) (x d : ℤ) (i : Fin k) :
    d ∣ (configPoint p x d i - x) := by
  unfold configPoint
  simpa using dvd_eval_of_noConstantTerm (hp i) d

/-! ═══════════════════════════════════════════════════════════════════════════════
PART II: THE LINEAR SPECIALIZATION — RECOVERING SZEMERÉDI
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
Taking each `pᵢ` to be the degree-one polynomial `i·X` makes the configuration
the arithmetic progression `x, x + d, x + 2d, …, x + (k-1)d`. This is the sense
in which Bergelson–Leibman *extends* Szemerédi's theorem: Szemerédi is the
degree-one case.
-/

/-- The linear polynomial `a · X`. -/
noncomputable def linearPoly (a : ℤ) : ℤ[X] := C a * X

@[simp] theorem linearPoly_eval (a d : ℤ) : (linearPoly a).eval d = a * d := by
  simp [linearPoly]

@[simp] theorem linearPoly_eval_zero (a : ℤ) : (linearPoly a).eval 0 = 0 := by
  simp [linearPoly]

/-- The linear family `i ↦ (i : ℤ) · X` has no constant term. -/
theorem linearFamily_noConstantTerm (k : ℕ) :
    NoConstantTerm (fun i : Fin k => linearPoly (i : ℤ)) := by
  intro i
  simp

/-- With the linear family, the configuration is the arithmetic progression
`x + i·d`. Thus Bergelson–Leibman applied to `{i·X}` is precisely Szemerédi's
theorem on length-`k` arithmetic progressions. -/
theorem configPoint_linear {k : ℕ} (x d : ℤ) (i : Fin k) :
    configPoint (fun j : Fin k => linearPoly (j : ℤ)) x d i = x + (i : ℤ) * d := by
  simp [configPoint]

/-! ═══════════════════════════════════════════════════════════════════════════════
PART III: A GENUINELY NONLINEAR EXAMPLE — SQUARES
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
The simplest genuinely polynomial (non-Szemerédi) instance: `k = 2`,
`p₀ = 0`, `p₁ = X²`. Bergelson–Leibman then asserts every positive-density
set contains a pair `{x, x + d²}` with `d ≠ 0`. We verify the structural
facts of this configuration.
-/

/-- The square family on two points: `p₀ = 0`, `p₁ = X²`. -/
noncomputable def squareFamily : Fin 2 → ℤ[X] :=
  ![0, X ^ 2]

theorem squareFamily_noConstantTerm : NoConstantTerm squareFamily := by
  intro i
  fin_cases i <;> simp [squareFamily, pow_two]

/-- The square configuration is `{x, x + d²}`. -/
theorem configPoint_square (x d : ℤ) :
    configPoint squareFamily x d 0 = x ∧
    configPoint squareFamily x d 1 = x + d ^ 2 := by
  constructor <;> simp [configPoint, squareFamily]

/-- The gap in the square configuration is a perfect square — the defining
nonlinear feature absent from arithmetic progressions. -/
theorem squareConfig_gap_isSquare (x d : ℤ) :
    configPoint squareFamily x d 1 - configPoint squareFamily x d 0 = d ^ 2 := by
  simp [configPoint, squareFamily]

/-! ═══════════════════════════════════════════════════════════════════════════════
PART IV: THE PET DIFFERENCING ENGINE (verified degree descent)
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
The Bergelson–Leibman proof reduces polynomial averages to linear ones by the
**van der Corput finite-difference operator** `(Δ_h p)(n) = p(n + h) − p(n)`,
the engine of *PET induction* (Polynomial Exhaustion Technique). The decisive
algebraic fact — verified below with **0 axioms** — is that differencing
*strictly lowers the degree* of a nonzero polynomial, so iterating it `deg p + 1`
times annihilates the polynomial. This well-founded descent is exactly what
makes PET induction terminate. We realize `Δ_h` on polynomials as the Taylor
shift `taylor h p − p`, reusing Mathlib's `taylor` API.
-/

section PET

variable {R : Type*} [CommRing R]

/-- The forward finite-difference operator `(Δ_h p)(n) = p(n + h) − p(n)`,
realized via the Taylor shift `taylor h p − p`. -/
noncomputable def fdiff (h : R) (p : R[X]) : R[X] := taylor h p - p

@[simp] theorem fdiff_eval (h : R) (p : R[X]) (s : R) :
    (fdiff h p).eval s = p.eval (s + h) - p.eval s := by
  simp [fdiff, taylor_eval]

@[simp] theorem fdiff_zero (h : R) : fdiff h (0 : R[X]) = 0 := by
  simp [fdiff]

/-- `Δ_h` annihilates constants — the base of the descent. -/
@[simp] theorem fdiff_C (h : R) (c : R) : fdiff h (C c) = 0 := by
  simp [fdiff, taylor_C]

/-- **PET descent, core step.** Differencing a nonzero polynomial *strictly*
lowers its degree: `taylor h p` and `p` share the same leading term, which
cancels under subtraction. -/
theorem fdiff_degree_lt (h : R) {p : R[X]} (hp : p ≠ 0) :
    (fdiff h p).degree < p.degree := by
  have hd : (taylor h p).degree = p.degree := degree_taylor p h
  have hne : taylor h p ≠ 0 := by rw [ne_eq, taylor_eq_zero]; exact hp
  have hlc : (taylor h p).leadingCoeff = p.leadingCoeff := leadingCoeff_taylor h p
  have hsub : (taylor h p - p).degree < (taylor h p).degree := degree_sub_lt hd hne hlc
  rw [hd] at hsub
  simpa [fdiff] using hsub

/-- Either differencing kills the polynomial, or it strictly drops `natDegree`. -/
theorem fdiff_eq_zero_or_natDegree_lt (h : R) (p : R[X]) :
    fdiff h p = 0 ∨ (fdiff h p).natDegree < p.natDegree := by
  rcases eq_or_ne p 0 with rfl | hp
  · exact Or.inl (by simp)
  · rcases eq_or_ne (fdiff h p) 0 with h0 | h0
    · exact Or.inl h0
    · exact Or.inr (natDegree_lt_natDegree h0 (fdiff_degree_lt h hp))

/-- **PET termination.** Applying `Δ_h` more than `deg p` times annihilates `p`.
This is the well-founded descent that makes PET induction terminate. -/
theorem fdiff_iterate_eq_zero (h : R) :
    ∀ (k : ℕ) (p : R[X]), p.natDegree ≤ k → (fdiff h)^[k + 1] p = 0 := by
  intro k
  induction k with
  | zero =>
    intro p hp
    have hpc : p.natDegree = 0 := Nat.le_zero.mp hp
    have hC : p = C (p.coeff 0) := eq_C_of_natDegree_eq_zero hpc
    show (fdiff h)^[1] p = 0
    rw [Function.iterate_one, hC, fdiff_C]
  | succ k ih =>
    intro p hp
    rw [Function.iterate_succ_apply]
    rcases eq_or_ne (fdiff h p) 0 with h0 | h0
    · rw [h0]; exact Function.iterate_fixed (fdiff_zero h) (k + 1)
    · apply ih
      have hlt : (fdiff h p).natDegree < p.natDegree := by
        rcases fdiff_eq_zero_or_natDegree_lt h p with h1 | h1
        · exact absurd h1 h0
        · exact h1
      omega

/-- Headline corollary: a degree-`d` polynomial is killed by `d + 1` differencings. -/
theorem fdiff_iterate_natDegree_succ (h : R) (p : R[X]) :
    (fdiff h)^[p.natDegree + 1] p = 0 :=
  fdiff_iterate_eq_zero h p.natDegree p le_rfl

end PET

/-! ### Worked degree ladders over `ℤ` -/

/-- `Δ_h X = h`: the first difference of the identity is constant. -/
theorem fdiff_X_eval (h s : ℤ) : (fdiff h (X : ℤ[X])).eval s = h := by
  simp only [fdiff_eval, eval_X]; ring

/-- First difference of the **square** (the Sárközy polynomial): `Δ_h X² = 2hX + h²`. -/
theorem fdiff_Xsq_eval (h s : ℤ) :
    (fdiff h (X ^ 2 : ℤ[X])).eval s = 2 * h * s + h ^ 2 := by
  simp only [fdiff_eval, eval_pow, eval_X]; ring

/-- Second difference of the square is the constant `2h²` — degree drops 2 → 0
in two steps, the PET ladder underlying Sárközy's theorem. -/
theorem fdiff_fdiff_Xsq_eval (h s : ℤ) :
    (fdiff h (fdiff h (X ^ 2 : ℤ[X]))).eval s = 2 * h ^ 2 := by
  simp only [fdiff_eval, eval_pow, eval_X]; ring

/-- PET termination, concretely: three differencings annihilate `X²`. -/
theorem fdiff_iterate_Xsq (h : ℤ) : (fdiff h)^[3] (X ^ 2 : ℤ[X]) = 0 := by
  have hd : ((X : ℤ[X]) ^ 2).natDegree = 2 := natDegree_X_pow 2
  have h3 : (fdiff h)^[2 + 1] (X ^ 2 : ℤ[X]) = 0 :=
    fdiff_iterate_eq_zero h 2 (X ^ 2) (le_of_eq hd)
  exact h3

/-! ═══════════════════════════════════════════════════════════════════════════════
PART V: STATEMENT OF THE BERGELSON–LEIBMAN THEOREM
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
We package the combinatorial conclusion as a `Prop` on a set `A ⊆ ℤ`. This is
the formal target; we do **not** assert it (that would require an axiom). A
future proof would derive it for every `A` of positive upper Banach density via
the Furstenberg correspondence and polynomial multiple recurrence.
-/

/-- `A` has the *polynomial Szemerédi property*: every finite family of
polynomials with no constant term is realized as a nontrivial configuration in
`A`. This is the conclusion of the Bergelson–Leibman theorem. -/
def PolynomialSzemerediProperty (A : Set ℤ) : Prop :=
  ∀ (k : ℕ) (p : Fin k → ℤ[X]), 0 < k → NoConstantTerm p →
    ∃ x d : ℤ, d ≠ 0 ∧ ∀ i, configPoint p x d i ∈ A

/-- Sanity check: the whole line `ℤ` trivially has the polynomial Szemerédi
property (witness `x = 0`, `d = 1`). A nontrivial theorem must instead derive
the property from a density hypothesis; this only certifies the statement is
not vacuously false. -/
theorem univ_polynomialSzemerediProperty :
    PolynomialSzemerediProperty (Set.univ : Set ℤ) := by
  intro k p _ _
  exact ⟨0, 1, one_ne_zero, fun _ => Set.mem_univ _⟩

/-- The polynomial Szemerédi property is monotone: it transfers up to any
superset. (If a sub-pattern already appears, it appears in a larger set too.) -/
theorem PolynomialSzemerediProperty.mono {A B : Set ℤ} (hAB : A ⊆ B)
    (hA : PolynomialSzemerediProperty A) : PolynomialSzemerediProperty B := by
  intro k p hk hp
  obtain ⟨x, d, hd, hmem⟩ := hA k p hk hp
  exact ⟨x, d, hd, fun i => hAB (hmem i)⟩

/-! ═══════════════════════════════════════════════════════════════════════════════
PART VI: THE ERGODIC SIDE — MATHLIB RECURRENCE INFRASTRUCTURE
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
The Bergelson–Leibman theorem is proved via *polynomial multiple recurrence* in
ergodic theory. The base case `k = 1`, `p₁(n) = n`, is ordinary Poincaré
recurrence, which Mathlib provides in full. We demonstrate the infrastructure
the polynomial generalization extends.
-/

/-- **Mathlib base case.** Poincaré recurrence: a finite measure-preserving
system returns to any positive-measure set. This is `k = 1`, `p₁(n) = n` of
polynomial multiple recurrence. -/
theorem poincare_single_recurrence {α : Type*} [MeasurableSpace α]
    {μ : Measure α} {T : α → α} [IsFiniteMeasure μ]
    (hMP : MeasurePreserving T μ μ) {s : Set α}
    (hs : NullMeasurableSet s μ) (hpos : μ s ≠ 0) :
    ∃ n : ℕ, 0 < n ∧ μ (s ∩ T^[n] ⁻¹' s) ≠ 0 :=
  hMP.conservative.exists_gt_measure_inter_ne_zero hs hpos 0

/-- Iterating a measure-preserving map by a polynomial exponent stays
measure-preserving: `T^{p(n)}` preserves `μ` for any `n`. This is the
elementary fact underlying the polynomial recurrence averages
`(1/N) Σ_n μ(E ∩ T^{-p(n)} E)`. -/
theorem measurePreserving_iterate_eval {α : Type*} [MeasurableSpace α]
    {μ : Measure α} {T : α → α} (hMP : MeasurePreserving T μ μ)
    (p : ℤ[X]) (n : ℤ) :
    MeasurePreserving (T^[(p.eval n).toNat]) μ μ :=
  hMP.iterate _

/-- **Statement of polynomial multiple recurrence** (ergodic form of
Bergelson–Leibman), packaged as a `Prop`. Not asserted — a formalization
target. For commuting iterates of a single transformation, with polynomials
having no constant term, some nonzero `n` makes the joint intersection
positive. -/
def PolynomialMultipleRecurrence {α : Type*} [MeasurableSpace α]
    (μ : Measure α) (T : α → α) : Prop :=
  ∀ (k : ℕ) (p : Fin k → ℤ[X]), 0 < k → NoConstantTerm p →
    ∀ E : Set α, MeasurableSet E → μ E ≠ 0 →
      ∃ n : ℤ, n ≠ 0 ∧
        μ (⋂ i, T^[(p i).eval n |>.toNat] ⁻¹' E) ≠ 0

/-! ═══════════════════════════════════════════════════════════════════════════════
PART VII: FEASIBILITY ASSESSMENT
═══════════════════════════════════════════════════════════════════════════════ -/

/-!
## Summary

**Verified here (0 axioms, 0 sorries):**
1. The polynomial configuration object and its collapse at `d = 0`.
2. `pᵢ(0) = 0 ↔ X ∣ pᵢ`, and the consequent divisibility `d ∣ pᵢ(d)`.
3. The linear specialization recovering arithmetic progressions (Szemerédi).
4. A genuinely nonlinear example: the square configuration `{x, x + d²}`.
5. Precise `Prop`-statements of both the combinatorial Bergelson–Leibman
   theorem and its ergodic (polynomial multiple recurrence) counterpart.
6. Poincaré single recurrence (the `k = 1` base case) from Mathlib, plus the
   measure-preservation of polynomial iterates.
7. The **PET differencing engine**: the van der Corput operator `Δ_h`, its
   strict degree descent (`fdiff_degree_lt`), and PET termination
   (`fdiff_iterate_eq_zero`) — the algebraic core of polynomial exhaustion.

**The gap (open formalization targets):**
- Polynomial multiple recurrence for `k ≥ 2`. The PET *differencing engine* is
  verified here, but the full induction scheme also needs the structure theory
  of characteristic factors (nilsystems), which Mathlib lacks.
- The Furstenberg correspondence linking density to the ergodic side is
  available in this gallery only as an axiom (`FurstenbergCorrespondence.lean`).

**Estimated effort for full polynomial multiple recurrence:**
- PET induction scheme: ~800–1200 lines.
- Characteristic factors / nilsequence machinery: ~3000+ lines (this is the
  genuinely hard part; not currently tractable).
- Conclusion: the *statement* and *elementary backbone* are formalizable now
  (this file); the deep theorem awaits Mathlib nilsystem infrastructure.

This file advances the Furstenberg program by pinning down the polynomial
extension's exact statement and verifying the algebraic constraints
(`d ∣ pᵢ(d)`, collapse at `0`) that any proof must respect.
-/

-- Final checks: what we built
#check @configPoint
#check @config_collapses_at_zero
#check @dvd_eval_of_noConstantTerm
#check @configPoint_linear
#check @configPoint_square
#check @PolynomialSzemerediProperty
#check @poincare_single_recurrence
#check @PolynomialMultipleRecurrence
#check @fdiff_degree_lt
#check @fdiff_iterate_eq_zero

end FurstenbergOQ03
