/-
# Hilbert's Tenth Problem, degree 1: the linear case is decidable

Follow-up to `Hilbert10OQ04` (open question oq-03).

The parent file `Hilbert10OQ04` discharged the former `linear_bezout_n` *axiom*,
turning it into a proved theorem: the linear Diophantine equation
`a₁x₁ + ⋯ + aₙxₙ = b` is solvable over `ℤ` iff there is a nonnegative `d` that is
a *greatest common divisor* of the coefficients and divides `b`. That statement is
phrased with an existentially-quantified, abstractly-characterized `d`.

This file pushes the result one step further — from an existential characterization
to a **computable** one — and extracts the structural consequence the parent only
hinted at:

* `solvable_iff_gcd_dvd` : the explicit gcd form of `n`-variable Bézout, with the
  abstract `d` replaced by the concrete, computable `Finset.gcd` of the coefficients;
* `LinearForm.solvable_iff` : the same criterion for a linear form `∑ cᵢxᵢ + c`;
* `LinearForm.decidableSolvable` : a `Decidable` instance — solvability of a linear
  Diophantine equation is *decided* by one gcd computation and one divisibility test;
* `linear_h10_decidable` : degree-1 Hilbert's Tenth Problem is uniformly decidable in
  every number of variables `n` (`DecidablePred` over all linear forms).

This is the sharp lower edge of the H10 undecidability hierarchy: degree 1 is
decidable for every `n`, while (Jones 1982) degree 4 in 9 variables is undecidable.

Everything here is `sorry`-free and `axiom`-free (only the foundational
`propext`/`Classical.choice`/`Quot.sound` are used; no `Lean.ofReduceBool`).
-/
import Mathlib

namespace Hilbert10OQ04OQ03

/-- The ideal of `ℤ` generated by the coefficients `a : Fin n → ℤ` is generated by
their gcd. Over the principal ideal ring `ℤ` the coefficient ideal is principal, and
its generator is — up to associates — exactly `Finset.univ.gcd a`. -/
theorem span_range_eq_span_gcd (n : ℕ) (a : Fin n → ℤ) :
    Ideal.span (Set.range a) = Ideal.span {(Finset.univ.gcd a : ℤ)} := by
  classical
  apply le_antisymm
  · -- every coefficient is divisible by the gcd, so it lies in `span {gcd}`
    rw [Ideal.span_le]
    rintro y ⟨i, rfl⟩
    rw [SetLike.mem_coe, Ideal.mem_span_singleton]
    exact Finset.gcd_dvd (Finset.mem_univ i)
  · -- conversely, the gcd lies in the coefficient ideal, via its principal generator
    rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    obtain ⟨g, hg⟩ : ∃ g : ℤ, Ideal.span (Set.range a) = Ideal.span {g} :=
      ⟨Submodule.IsPrincipal.generator _,
        (Submodule.IsPrincipal.span_singleton_generator _).symm⟩
    have hg_dvd : ∀ i, g ∣ a i := by
      intro i
      have hmem : a i ∈ Ideal.span (Set.range a) := Ideal.subset_span (Set.mem_range_self i)
      rwa [hg, Ideal.mem_span_singleton] at hmem
    rw [hg, Ideal.mem_span_singleton]
    exact Finset.dvd_gcd fun i _ => hg_dvd i

/-- **`n`-variable Bézout, explicit gcd form.** The linear Diophantine equation
`∑ aᵢ xᵢ = b` is solvable over `ℤ` iff the (computable) gcd of the coefficients
divides `b`. This refines the parent file's existential characterization by pinning
the witness `d` to the concrete value `Finset.univ.gcd a`. -/
theorem solvable_iff_gcd_dvd (n : ℕ) (a : Fin n → ℤ) (b : ℤ) :
    (∃ x : Fin n → ℤ, ∑ i, a i * x i = b) ↔ (Finset.univ.gcd a : ℤ) ∣ b := by
  have hmem : (∃ x : Fin n → ℤ, ∑ i, a i * x i = b) ↔ b ∈ Ideal.span (Set.range a) := by
    rw [Ideal.mem_span_range_iff_exists_fun]
    exact ⟨fun ⟨x, hx⟩ => ⟨x, by simpa [mul_comm] using hx⟩,
           fun ⟨c, hc⟩ => ⟨c, by simpa [mul_comm] using hc⟩⟩
  rw [hmem, span_range_eq_span_gcd, Ideal.mem_span_singleton]

/-- A linear (degree-1) Diophantine form `∑ coeffsᵢ · xᵢ + const` in `n` variables. -/
structure LinearForm (n : ℕ) where
  coeffs : Fin n → ℤ
  const : ℤ

/-- A linear form is solvable when some integer assignment makes it vanish. -/
def LinearForm.Solvable {n : ℕ} (L : LinearForm n) : Prop :=
  ∃ x : Fin n → ℤ, (∑ i, L.coeffs i * x i) + L.const = 0

/-- **Decidability criterion.** A linear Diophantine form is solvable iff the gcd of
its coefficients divides its constant term — a single gcd plus one divisibility check. -/
theorem LinearForm.solvable_iff {n : ℕ} (L : LinearForm n) :
    L.Solvable ↔ (Finset.univ.gcd L.coeffs : ℤ) ∣ L.const := by
  have hshift : L.Solvable ↔ ∃ x : Fin n → ℤ, ∑ i, L.coeffs i * x i = -L.const := by
    unfold LinearForm.Solvable
    refine ⟨fun ⟨x, hx⟩ => ⟨x, by linarith⟩, fun ⟨x, hx⟩ => ⟨x, by linarith⟩⟩
  rw [hshift, solvable_iff_gcd_dvd, dvd_neg]

/-- Solvability of a linear Diophantine form is decidable: reduce to a gcd divisibility
test, which is decidable over `ℤ`. -/
instance LinearForm.decidableSolvable {n : ℕ} (L : LinearForm n) : Decidable L.Solvable :=
  decidable_of_iff' _ L.solvable_iff

/-- **Degree-1 Hilbert's Tenth Problem is decidable** uniformly in the number of
variables: solvability is a decidable predicate over all linear forms in `n` unknowns,
for every `n`. This is the decidable boundary opposite Jones's degree-4 / 9-variable
undecidable family in the parent file. -/
def linear_h10_decidable (n : ℕ) : DecidablePred (LinearForm.Solvable (n := n)) :=
  fun L => L.decidableSolvable

/-- Worked instance: `6x + 10y + 15z = 1` is solvable, since `gcd(6,10,15) = 1 ∣ 1`.
A concrete witness is `(1, 1, -1)`: `6 + 10 − 15 = 1`. -/
example : (⟨![6, 10, 15], -1⟩ : LinearForm 3).Solvable :=
  ⟨![1, 1, -1], by
    norm_num [LinearForm.Solvable, Fin.sum_univ_three,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
      Matrix.head_cons, Matrix.tail_cons]⟩

end Hilbert10OQ04OQ03
