import Mathlib.RingTheory.MvPolynomial.Symmetric.Defs
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.LinearAlgebra.Vandermonde
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Tactic

/-
# Hilbert 14 OQ-02 / OQ-02: the alternating group `Aₙ` and the Vandermonde invariant

The parent chain (`hilbert-14-oq-02`, `hilbert-14-oq-02-oq-01`) settles the optimal
degree bound `β(Sₙ) = n` for the **symmetric group** `Sₙ` acting on `R[x₁,…,xₙ]`: the
invariant ring is `R[e₁,…,eₙ]`, generated by the `n` elementary symmetric polynomials,
and the top generator `eₙ` is a genuine new generator at degree exactly `n`.

This entry addresses the natural OQ-02 follow-up — *identify the generating invariants and
their degrees for another classical group* — for the **alternating group** `Aₙ ⊆ Sₙ`.
The new phenomenon is the **Vandermonde / discriminant polynomial**

>   `Δ = ∏_{i < j} (xⱼ - xᵢ)`

which is the prototypical *alternating* (rather than symmetric) invariant.

## Main results

* `vandermondePoly_rename` : **`Δ` is alternating** — for every permutation `e`,
  `rename e Δ = sign(e) • Δ`. Proved by evaluating on all points (`MvPolynomial.funext`)
  and reducing to the classical fact that permuting the rows of a Vandermonde matrix scales
  its determinant by the sign of the permutation (`Matrix.det_permute` + `Matrix.det_vandermonde`).
* `vandermondePoly_isInvariant_of_sign_eq_one` : **`Δ` is an `Aₙ`-invariant** — every *even*
  permutation fixes `Δ`. This is the generating invariant that distinguishes the
  `Aₙ`-invariant ring from the `Sₙ`-invariant ring `R[e₁,…,eₙ]`.
* `vandermondePoly_not_isSymmetric` / `vandermondePoly_not_mem_symmetricSubalgebra` :
  over an infinite integral domain with `2 ≠ 0`, `Δ` is **not** symmetric, hence
  `Δ ∉ R[e₁,…,eₙ]`: it is a genuinely new generator, absent from the `Sₙ`-invariants.
* `vandermondePoly_sq_isSymmetric` : **`Δ² is symmetric`** — the discriminant `Δ²` lies in the
  `Sₙ`-invariant ring `R[e₁,…,eₙ]`. So `Δ` is a square root of a symmetric polynomial, exactly
  the algebraic relation `Aₙ`-invariants satisfy over the `Sₙ`-invariants.
* `vandermondePoly_isHomogeneous` : `Δ` is homogeneous of degree `∑_i |{j : i < j}| = C(n,2)`,
  i.e. `n(n-1)/2` — the degree of the new alternating generator.
-/

namespace Hilbert14OQ02OQ02

open MvPolynomial Finset Equiv Matrix

variable {n : ℕ} {R : Type*} [CommRing R]

/-- The **Vandermonde / discriminant polynomial** `Δ = ∏_{i < j} (xⱼ - xᵢ)` in
`R[x₀,…,x_{n-1}]`. The index set of the inner product matches the shape of
`Matrix.det_vandermonde`, so `Δ` evaluates to the Vandermonde determinant. -/
noncomputable def vandermondePoly (n : ℕ) (R : Type*) [CommRing R] :
    MvPolynomial (Fin n) R :=
  ∏ i : Fin n, ∏ j ∈ Finset.Ioi i, (X j - X i)

/-- Evaluating `Δ` at a point `v` gives the determinant of the Vandermonde matrix of `v`. -/
theorem eval_vandermondePoly (v : Fin n → R) :
    eval v (vandermondePoly n R) = (Matrix.vandermonde v).det := by
  rw [vandermondePoly, det_vandermonde, map_prod]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [map_prod]
  refine Finset.prod_congr rfl fun j _ => ?_
  rw [map_sub, eval_X, eval_X]

/-- Precomposing the evaluation point with a permutation `e` permutes the rows of the
Vandermonde matrix: `vandermonde (v ∘ e) = (vandermonde v).submatrix e id`. -/
theorem vandermonde_comp_perm (v : Fin n → R) (e : Equiv.Perm (Fin n)) :
    Matrix.vandermonde (v ∘ e) = (Matrix.vandermonde v).submatrix e id := by
  ext i j
  simp [Matrix.vandermonde_apply, Matrix.submatrix_apply]

/-- **Alternating law, evaluated form.** For every point `v` and permutation `e`,
`Δ(v ∘ e) = sign(e) · Δ(v)`. This is the classical determinant identity
`det (permuted Vandermonde) = sign · det (Vandermonde)`. -/
theorem eval_rename_vandermondePoly (v : Fin n → R) (e : Equiv.Perm (Fin n)) :
    eval v (rename e (vandermondePoly n R))
      = (Equiv.Perm.sign e : ℤ) • eval v (vandermondePoly n R) := by
  rw [eval_rename, eval_vandermondePoly, eval_vandermondePoly, vandermonde_comp_perm,
    det_permute]
  simp [zsmul_eq_mul]

/-- **`Δ` is alternating.** Over an infinite integral domain, `rename e Δ = sign(e) • Δ`
as polynomials, for every permutation `e`. Proved by `MvPolynomial.funext` from the
evaluated form. -/
theorem vandermondePoly_rename [IsDomain R] [Infinite R] (e : Equiv.Perm (Fin n)) :
    rename e (vandermondePoly n R) = (Equiv.Perm.sign e : ℤ) • vandermondePoly n R := by
  apply MvPolynomial.funext
  intro v
  rw [eval_rename_vandermondePoly, map_zsmul]

/-- **`Δ` is an `Aₙ`-invariant.** Every even permutation fixes `Δ`. This is the generating
invariant that enlarges the invariant ring beyond the symmetric `R[e₁,…,eₙ]`. -/
theorem vandermondePoly_isInvariant_of_sign_eq_one [IsDomain R] [Infinite R]
    {e : Equiv.Perm (Fin n)} (he : Equiv.Perm.sign e = 1) :
    rename e (vandermondePoly n R) = vandermondePoly n R := by
  rw [vandermondePoly_rename, he]
  simp

/-- **`Δ² is symmetric.** The discriminant `Δ²` is fixed by *every* permutation, so it lies
in the `Sₙ`-invariant ring `R[e₁,…,eₙ]`. Thus `Δ` is a square root of a symmetric polynomial —
the defining algebraic relation of the `Aₙ`-invariants over the `Sₙ`-invariants. -/
theorem vandermondePoly_sq_isSymmetric [IsDomain R] [Infinite R] :
    (vandermondePoly n R ^ 2).IsSymmetric := by
  intro e
  rw [map_pow, vandermondePoly_rename]
  rcases Int.units_eq_one_or (Equiv.Perm.sign e) with hs | hs <;> simp [hs]

/-- `Δ ≠ 0` over an infinite integral domain: evaluating at an injective tuple gives a
nonzero Vandermonde determinant. -/
theorem vandermondePoly_ne_zero [IsDomain R] [Infinite R] :
    vandermondePoly n R ≠ 0 := by
  intro h
  have hv : Function.Injective (fun i : Fin n => (Infinite.natEmbedding R) i) :=
    (Infinite.natEmbedding R).injective.comp Fin.val_injective
  have hne : eval (fun i : Fin n => (Infinite.natEmbedding R) i) (vandermondePoly n R) ≠ 0 := by
    rw [eval_vandermondePoly]
    exact det_vandermonde_ne_zero_iff.mpr hv
  rw [h, map_zero] at hne
  exact hne rfl

/-- **`Δ` is not symmetric.** Over an infinite integral domain with `2 ≠ 0` and `n ≥ 2`,
`Δ` fails to be `Sₙ`-invariant: the transposition of two variables sends `Δ ↦ -Δ ≠ Δ`. -/
theorem vandermondePoly_not_isSymmetric [IsDomain R] [Infinite R]
    (hn : 2 ≤ n) (h2 : (2 : R) ≠ 0) :
    ¬ (vandermondePoly n R).IsSymmetric := by
  intro hsym
  set i0 : Fin n := ⟨0, by omega⟩ with hi0
  set i1 : Fin n := ⟨1, by omega⟩ with hi1
  have hne : i0 ≠ i1 := by
    simp only [hi0, hi1, Ne, Fin.mk.injEq]
    omega
  set e : Equiv.Perm (Fin n) := Equiv.swap i0 i1 with he
  set v : Fin n → R := fun i => (Infinite.natEmbedding R) i with hv
  have hvinj : Function.Injective v := (Infinite.natEmbedding R).injective.comp Fin.val_injective
  -- from symmetry, `eval v (rename e Δ) = eval v Δ`
  have key : eval v (rename e (vandermondePoly n R)) = eval v (vandermondePoly n R) := by
    rw [hsym e]
  rw [eval_rename_vandermondePoly, he, Equiv.Perm.sign_swap hne] at key
  -- key : (-1 : ℤ) • eval v Δ = eval v Δ
  set x : R := eval v (vandermondePoly n R) with hx
  have hx0 : x ≠ 0 := by
    rw [hx, eval_vandermondePoly]
    exact det_vandermonde_ne_zero_iff.mpr hvinj
  have keyx : -x = x := by
    have : ((-1 : ℤ)) • x = x := by simpa using key
    simpa [neg_one_zsmul] using this
  have h2x : (2 : R) * x = 0 := by linear_combination -keyx
  rcases mul_eq_zero.mp h2x with h | h
  · exact h2 h
  · exact hx0 h

/-- **`Δ ∉ R[e₁,…,eₙ]`.** Over an infinite integral domain with `2 ≠ 0` and `n ≥ 2`, the
Vandermonde invariant does **not** lie in the symmetric subalgebra (the `Sₙ`-invariant ring
generated by the elementary symmetric polynomials). So `Δ` is a genuinely new generator of the
`Aₙ`-invariants, absent from the `Sₙ`-invariants. -/
theorem vandermondePoly_not_mem_symmetricSubalgebra [IsDomain R] [Infinite R]
    (hn : 2 ≤ n) (h2 : (2 : R) ≠ 0) :
    vandermondePoly n R ∉ symmetricSubalgebra (Fin n) R := by
  rw [mem_symmetricSubalgebra]
  exact vandermondePoly_not_isSymmetric hn h2

/-- **Degree of the new generator.** `Δ` is homogeneous of degree
`∑_i |{j : i < j}| = C(n,2) = n(n-1)/2`: a product of `C(n,2)` degree-one factors `xⱼ - xᵢ`. -/
theorem vandermondePoly_isHomogeneous :
    (vandermondePoly n R).IsHomogeneous (∑ i : Fin n, (Finset.Ioi i).card) := by
  rw [vandermondePoly]
  apply MvPolynomial.IsHomogeneous.prod
  intro i _
  have : (Finset.Ioi i).card = ∑ _j ∈ Finset.Ioi i, 1 := by simp
  rw [this]
  apply MvPolynomial.IsHomogeneous.prod
  intro j _
  exact (isHomogeneous_X R j).sub (isHomogeneous_X R i)

/-- The degree of `Δ` in closed form: `∑_i |{j : i < j}| = C(n,2) = n(n-1)/2`. It is the
number of pairs `i < j`, i.e. the number of degree-one factors `xⱼ - xᵢ`. -/
theorem vandermondePoly_degree_eq :
    (∑ i : Fin n, (Finset.Ioi i).card) = n * (n - 1) / 2 := by
  have h1 : (∑ i : Fin n, (Finset.Ioi i).card) = ∑ i : Fin n, (n - 1 - (i : ℕ)) :=
    Finset.sum_congr rfl fun i _ => Fin.card_Ioi i
  have h2 : (∑ i : Fin n, (n - 1 - (i : ℕ))) = ∑ i ∈ Finset.range n, (n - 1 - i) :=
    Fin.sum_univ_eq_sum_range (fun i => n - 1 - i) n
  have h3 : (∑ i ∈ Finset.range n, (n - 1 - i)) = ∑ i ∈ Finset.range n, i :=
    Finset.sum_range_reflect (fun i => i) n
  rw [h1, h2, h3, Finset.sum_range_id]

end Hilbert14OQ02OQ02
