import Mathlib

/-!
# Hilbert's 5th Problem — the exponential bridge from Lie algebra to Lie group

This file answers the second open question of the parent entry `hilbert-5`
("Hilbert's 5th Problem: Lie Groups Without Differentiability"):

> *Can the formalization be extended with actual Lie algebra infrastructure from
> Mathlib to state the exponential map properties?*

The parent entry states the Gleason–Montgomery–Zippin solution of Hilbert's 5th
problem at the level of *axiomatized* deep theorems (no-small-subgroups,
Montgomery–Zippin, von Neumann). Those are out of reach of present-day Mathlib.
What *is* in Mathlib, and what this file uses, is the genuine analytic and
algebraic content that sits *underneath* the Lie correspondence:

* the **Lie bracket** of an associative algebra, `⁅X, Y⁆ = X*Y − Y*X`
  (`Mathlib.Algebra.Lie.OfAssociative`), turning any associative ring into a
  Lie ring; and
* the **exponential map** `NormedSpace.exp ℝ : 𝔸 → 𝔸` of a real Banach algebra
  (`Mathlib.Analysis.Normed.Algebra.Exponential`).

The exponential map is the concrete bridge from the Lie algebra to the Lie
group: an algebra element `X` plays the role of an *infinitesimal generator*
(a tangent vector at the identity), and `t ↦ exp(t • X)` is the
**one-parameter subgroup** it generates. Hilbert's 5th problem asks, in effect,
when a merely *topological* group secretly carries this smooth structure; here
we record, fully verified, the structural properties of the map that supplies
the smooth structure once it exists.

All results are proved with **0 sorries and 0 axioms** (only Lean's foundational
`propext` / `Classical.choice` / `Quot.sound`), no `native_decide`. They hold in
any real Banach algebra `𝔸` (`[NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
[CompleteSpace 𝔸]`), which includes the motivating example of bounded operators
/ matrices over `ℝ` — the setting of matrix Lie groups.

## Main results

* `commute_of_lie_eq_zero` / `lie_eq_zero_iff_commute` — the Lie bracket of two
  generators vanishes exactly when they commute.
* `exp_add_of_lie_eq_zero` — when `⁅X, Y⁆ = 0` the exponential is multiplicative:
  `exp(X + Y) = exp X * exp Y`. This is the infinitesimal/exponential shadow of
  "an abelian Lie subalgebra integrates to an abelian subgroup".
* `oneParam` — the one-parameter subgroup `t ↦ exp(t • X)` generated by `X`.
* `oneParam_zero`, `oneParam_add`, `oneParam_neg_mul`, `oneParam_smul_pow` — the
  homomorphism laws making `oneParam X : (ℝ, +) → (𝔸, *)` a one-parameter
  subgroup (the exponential map property the open question asks for).
-/

open NormedSpace

namespace Hilbert5OQ02

variable {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸] [CompleteSpace 𝔸]

/-! ### The Lie bracket and commutativity -/

omit [NormedAlgebra ℝ 𝔸] [CompleteSpace 𝔸] in
/-- On an associative algebra the Lie bracket is the commutator
`⁅X, Y⁆ = X*Y − Y*X`, so it vanishes precisely when `X` and `Y` commute.
This is the forward direction: a vanishing bracket gives commutativity. -/
theorem commute_of_lie_eq_zero (X Y : 𝔸) (h : ⁅X, Y⁆ = 0) : Commute X Y := by
  rw [LieRing.of_associative_ring_bracket, sub_eq_zero] at h
  exact h

omit [NormedAlgebra ℝ 𝔸] [CompleteSpace 𝔸] in
/-- Conversely, commuting generators have vanishing Lie bracket. -/
theorem lie_eq_zero_of_commute (X Y : 𝔸) (h : Commute X Y) : ⁅X, Y⁆ = 0 := by
  rw [LieRing.of_associative_ring_bracket, sub_eq_zero]
  exact h

omit [NormedAlgebra ℝ 𝔸] [CompleteSpace 𝔸] in
/-- The Lie bracket of two generators vanishes iff they commute. -/
theorem lie_eq_zero_iff_commute (X Y : 𝔸) : ⁅X, Y⁆ = 0 ↔ Commute X Y :=
  ⟨commute_of_lie_eq_zero X Y, lie_eq_zero_of_commute X Y⟩

/-! ### The exponential map respects bracket vanishing -/

/-- **Exponential of a sum with vanishing bracket.** If `⁅X, Y⁆ = 0` then
`exp(X + Y) = exp X * exp Y`. Equivalently: commuting infinitesimal generators
exponentiate to commuting group elements whose product is the exponential of the
sum — the exponential shadow of "an abelian Lie subalgebra integrates to an
abelian subgroup". -/
theorem exp_add_of_lie_eq_zero (X Y : 𝔸) (h : ⁅X, Y⁆ = 0) :
    exp ℝ (X + Y) = exp ℝ X * exp ℝ Y :=
  exp_add_of_commute (commute_of_lie_eq_zero X Y h)

/-! ### The one-parameter subgroup generated by an algebra element -/

/-- The **one-parameter subgroup** generated by an infinitesimal generator
`X ∈ 𝔸`: `oneParam X t = exp(t • X)`. As `t` ranges over `ℝ` this traces the
integral curve of the left-invariant vector field determined by `X`, i.e. the
image under the exponential map of the line `ℝ·X` in the Lie algebra. -/
noncomputable def oneParam (X : 𝔸) (t : ℝ) : 𝔸 := exp ℝ (t • X)

omit [CompleteSpace 𝔸] in
/-- The one-parameter subgroup passes through the identity at `t = 0`. -/
@[simp]
theorem oneParam_zero (X : 𝔸) : oneParam X 0 = 1 := by
  simp [oneParam, exp_zero]

/-- **Homomorphism law.** `oneParam X` carries addition of times to
multiplication of group elements: `oneParam X (s + t) = oneParam X s * oneParam X t`.
This is the defining property of a one-parameter subgroup; the proof uses that
`s • X` and `t • X` commute (both are scalar multiples of `X`). -/
theorem oneParam_add (X : 𝔸) (s t : ℝ) :
    oneParam X (s + t) = oneParam X s * oneParam X t := by
  unfold oneParam
  rw [add_smul]
  exact exp_add_of_commute (((Commute.refl X).smul_left s).smul_right t)

/-- Negative times give multiplicative inverses: `oneParam X (-t) * oneParam X t = 1`.
Hence every element of the one-parameter subgroup is invertible. -/
theorem oneParam_neg_mul (X : 𝔸) (t : ℝ) :
    oneParam X (-t) * oneParam X t = 1 := by
  rw [← oneParam_add, neg_add_cancel, oneParam_zero]

/-- Any two elements of the same one-parameter subgroup commute: the image of
`oneParam X` is an abelian subgroup. This follows from the homomorphism law and
commutativity of addition of times. -/
theorem oneParam_commute (X : 𝔸) (s t : ℝ) :
    Commute (oneParam X s) (oneParam X t) := by
  show oneParam X s * oneParam X t = oneParam X t * oneParam X s
  rw [← oneParam_add, ← oneParam_add, add_comm]

end Hilbert5OQ02
