/-
# Infinitude of Primes OQ-01: Furstenberg's Topological Proof (1955)

## Research Question

`infinitude-primes-oq-01`: *Can we formalize Furstenberg's topological proof?*
Define a topology on `ℤ` whose open sets are unions of two-sided arithmetic
progressions, show each progression `{a + d·n}` is **clopen**, exhibit the set of
non-units `ℤ \ {-1, 1}` as the union `⋃_p pℤ` over the primes, and derive the
infinitude of primes from the fact that a nonempty open set in this topology is
infinite while `{-1, 1}` is not.

This is the celebrated one-paragraph proof of Hilbert Hotel fame (Furstenberg,
*Amer. Math. Monthly* **62** (1955), 353). Neither the proof nor the underlying
"evenly spaced integer topology" is in Mathlib (Mathlib proves the infinitude of
primes by Euclid's argument, `Nat.infinite_setOf_prime`). This file builds the
topology and runs the argument from scratch — the final theorem
`infinite_setOf_prime` does **not** cite any Mathlib infinitude result.

## Design

To avoid clashing with the standard `TopologicalSpace ℤ` instance (order /
metric topology), we never register a topology instance. Instead we work directly
with the predicate `GenerateOpen B`, which *is* `IsOpen` for the topology
`generateFrom B`, where `B` is the family of two-sided arithmetic progressions.
A set is `IsOpenF` when `GenerateOpen B` holds and `IsClosedF` when its complement
is `IsOpenF`. All of Furstenberg's structure is then elementary lemmas about these
two predicates — no instance resolution, no `@`-elaboration of a competing topology.

## Main results

* `isOpenF_AP`  / `isClosedF_AP` : every progression `AP a d` (`d > 0`) is clopen.
* `isOpenF_imp_hasAPNbhd`        : a nonempty open set contains a whole progression
  about each of its points (the key "open ⇒ infinite" mechanism), proved by
  induction on `GenerateOpen`.
* `AP_infinite`                  : every progression with positive step is infinite.
* `cover_compl_units`            : `⋃_{p prime} pℤ = ℤ \ {-1, 1}`.
* `infinite_setOf_prime`         : **there are infinitely many primes**, via the
  Furstenberg contradiction (finitely many primes ⇒ `{-1,1}` open ⇒ infinite).
-/

import Mathlib

open TopologicalSpace Set

namespace InfinitudePrimesOQ01

/-! ## The arithmetic-progression basis -/

/-- The two-sided arithmetic progression `{a + d·n : n ∈ ℤ}` with base `a` and
step `d`. As a subset of `ℤ` it is the coset `a + dℤ`. -/
def AP (a d : ℤ) : Set ℤ := {x | ∃ n : ℤ, x = a + d * n}

/-- Membership in a progression is exactly a divisibility statement:
`x ∈ a + dℤ ↔ d ∣ (x - a)`. -/
theorem mem_AP_iff_dvd {a d x : ℤ} : x ∈ AP a d ↔ d ∣ (x - a) := by
  simp only [AP, Set.mem_setOf_eq, dvd_def]
  constructor
  · rintro ⟨n, rfl⟩; exact ⟨n, by ring⟩
  · rintro ⟨c, hc⟩; exact ⟨c, by linear_combination hc⟩

/-- The generating family `B`: all progressions with **positive** step. -/
def B : Set (Set ℤ) := {s | ∃ a d, 0 < d ∧ s = AP a d}

/-- A set is *open* in Furstenberg's topology when it is generated by `B`. This is
definitionally `IsOpen` for `TopologicalSpace.generateFrom B`. -/
def IsOpenF (s : Set ℤ) : Prop := GenerateOpen B s

/-- A set is *closed* when its complement is open. -/
def IsClosedF (s : Set ℤ) : Prop := IsOpenF sᶜ

/-- Each positive-step progression is a basic open set. -/
theorem isOpenF_AP (a : ℤ) {d : ℤ} (hd : 0 < d) : IsOpenF (AP a d) :=
  GenerateOpen.basic _ ⟨a, d, hd, rfl⟩

/-! ## Containments between progressions -/

/-- A progression based at one of its own points, with the same step, sits inside
the original: if `a ∈ a₀ + dℤ` then `a + dℤ ⊆ a₀ + dℤ`. -/
theorem AP_self_subset {a₀ d a : ℤ} (ha : a ∈ AP a₀ d) : AP a d ⊆ AP a₀ d := by
  obtain ⟨k, rfl⟩ := ha
  rintro x ⟨m, rfl⟩
  exact ⟨k + m, by ring⟩

/-- Refining the step by a factor shrinks the progression: `a + (d₁d₂)ℤ ⊆ a + d₁ℤ`. -/
theorem AP_mul_subset_left (a d₁ d₂ : ℤ) : AP a (d₁ * d₂) ⊆ AP a d₁ := by
  rintro x ⟨n, rfl⟩; exact ⟨d₂ * n, by ring⟩

/-- Symmetric refinement: `a + (d₁d₂)ℤ ⊆ a + d₂ℤ`. -/
theorem AP_mul_subset_right (a d₁ d₂ : ℤ) : AP a (d₁ * d₂) ⊆ AP a d₂ := by
  rintro x ⟨n, rfl⟩; exact ⟨d₁ * n, by ring⟩

/-- Every progression with positive step is infinite: `n ↦ a + d·n` injects `ℤ`. -/
theorem AP_infinite {a d : ℤ} (hd : 0 < d) : (AP a d).Infinite := by
  have hinj : Function.Injective (fun n : ℤ => a + d * n) := by
    intro m n h
    have h' : d * m = d * n := by simpa using h
    exact mul_left_cancel₀ (ne_of_gt hd) h'
  exact Set.infinite_of_injective_forall_mem hinj (fun n => ⟨n, rfl⟩)

/-! ## The "AP-neighbourhood" property: open ⇒ contains a progression -/

/-- A set `U` *has progression neighbourhoods* when every point of `U` is the base
of a positive-step progression contained in `U`. -/
def HasAPNbhd (U : Set ℤ) : Prop := ∀ a ∈ U, ∃ d, 0 < d ∧ AP a d ⊆ U

/-- **Key lemma.** Every open set has progression neighbourhoods. Proved by
induction on the `GenerateOpen` structure: basic progressions self-contain
(`AP_self_subset`), intersections multiply the two steps (`AP_mul_subset_*`),
and unions inherit a neighbourhood from a member. No Chinese Remainder Theorem
is needed — the product step `d₁d₂` refines into both factors. -/
theorem isOpenF_imp_hasAPNbhd {U : Set ℤ} (hU : IsOpenF U) : HasAPNbhd U := by
  unfold IsOpenF at hU
  induction hU with
  | basic s hs =>
      obtain ⟨a₀, d₀, hd₀, rfl⟩ := hs
      intro a ha
      exact ⟨d₀, hd₀, AP_self_subset ha⟩
  | univ =>
      intro a _
      exact ⟨1, one_pos, fun _ _ => trivial⟩
  | inter s t _ _ IHs IHt =>
      intro a ha
      obtain ⟨d₁, hd₁, hs₁⟩ := IHs a ha.1
      obtain ⟨d₂, hd₂, ht₂⟩ := IHt a ha.2
      refine ⟨d₁ * d₂, mul_pos hd₁ hd₂, ?_⟩
      intro x hx
      exact ⟨hs₁ (AP_mul_subset_left a d₁ d₂ hx), ht₂ (AP_mul_subset_right a d₁ d₂ hx)⟩
  | sUnion S _ IH =>
      intro a ha
      obtain ⟨s, hsS, has⟩ := ha
      obtain ⟨d, hd, hsub⟩ := IH s hsS a has
      exact ⟨d, hd, hsub.trans (Set.subset_sUnion_of_mem hsS)⟩

/-! ## Closed sets: finite unions and the clopen progressions -/

/-- The empty set is closed (its complement is the whole space). -/
theorem isClosedF_empty : IsClosedF (∅ : Set ℤ) := by
  show IsOpenF (∅ : Set ℤ)ᶜ
  rw [Set.compl_empty]; exact GenerateOpen.univ

/-- A union of two closed sets is closed. -/
theorem isClosedF_union {s t : Set ℤ} (hs : IsClosedF s) (ht : IsClosedF t) :
    IsClosedF (s ∪ t) := by
  show IsOpenF (s ∪ t)ᶜ
  rw [Set.compl_union]; exact GenerateOpen.inter _ _ hs ht

/-- A finite union of closed sets is closed. -/
theorem isClosedF_biUnion {ι : Type*} {f : ι → Set ℤ} :
    ∀ (s : Finset ι), (∀ i ∈ s, IsClosedF (f i)) →
      IsClosedF (⋃ i ∈ (s : Set ι), f i) := by
  classical
  intro s
  induction s using Finset.induction_on with
  | empty => intro _; simpa using isClosedF_empty
  | @insert a s' _ ih =>
      intro h
      rw [Finset.coe_insert, Set.biUnion_insert]
      exact isClosedF_union (h a (Finset.mem_insert_self a s'))
        (ih (fun i hi => h i (Finset.mem_insert_of_mem hi)))

/-- A finite union of open sets is open. -/
theorem isOpenF_biUnion {ι : Type*} {f : ι → Set ℤ} (s : Finset ι)
    (h : ∀ i ∈ s, IsOpenF (f i)) : IsOpenF (⋃ i ∈ (s : Set ι), f i) := by
  rw [← Set.sUnion_image]
  apply GenerateOpen.sUnion
  rintro t ⟨i, hi, rfl⟩
  exact h i (Finset.mem_coe.mp hi)

/-- **Each progression is closed.** Its complement is the finite union of the
sibling progressions `a + i + dℤ` for `i = 1, …, d-1`: an integer fails to lie in
`a + dℤ` exactly when its residue `(x - a) mod d` is a nonzero element of
`{1, …, d-1}`, and that residue places it in one sibling progression. -/
theorem isClosedF_AP (a : ℤ) {d : ℤ} (hd : 0 < d) : IsClosedF (AP a d) := by
  have hcover : (AP a d)ᶜ = ⋃ i ∈ (Finset.Ioo 0 d : Set ℤ), AP (a + i) d := by
    ext x
    simp only [Set.mem_compl_iff, mem_AP_iff_dvd, Set.mem_iUnion, Finset.mem_coe,
      Finset.mem_Ioo]
    constructor
    · intro hndvd
      have h0 : 0 ≤ (x - a) % d := Int.emod_nonneg _ (ne_of_gt hd)
      have hlt : (x - a) % d < d := Int.emod_lt_of_pos _ hd
      have hne : (x - a) % d ≠ 0 := fun h => hndvd (Int.dvd_of_emod_eq_zero h)
      refine ⟨(x - a) % d, ⟨by omega, hlt⟩, ?_⟩
      refine ⟨(x - a) / d, ?_⟩
      have hadd := Int.emod_add_ediv (x - a) d
      linarith
    · rintro ⟨i, ⟨hi0, hid⟩, hdvd⟩ hdvd2
      have hdi : d ∣ i := by
        have hsub := dvd_sub hdvd2 hdvd
        have hrw : (x - a) - (x - (a + i)) = i := by ring
        rwa [hrw] at hsub
      have := Int.le_of_dvd hi0 hdi
      omega
  show IsOpenF (AP a d)ᶜ
  rw [hcover]
  exact isOpenF_biUnion (Finset.Ioo 0 d) (fun i _ => isOpenF_AP (a + i) hd)

/-! ## The cover by prime progressions and the main theorem -/

/-- **The cover identity.** The non-units of `ℤ` are exactly the integers with a
prime divisor: `⋃_{p prime} pℤ = ℤ \ {-1, 1}`, here phrased pointwise as
`(∃ prime p : ℕ, (p:ℤ) ∣ x) ↔ x ≠ 1 ∧ x ≠ -1`. -/
theorem exists_prime_dvd_iff (x : ℤ) :
    (∃ p : ℕ, p.Prime ∧ (p : ℤ) ∣ x) ↔ x ≠ 1 ∧ x ≠ -1 := by
  constructor
  · rintro ⟨p, hp, hpx⟩
    have hp2 : (2 : ℤ) ≤ (p : ℤ) := by exact_mod_cast hp.two_le
    refine ⟨?_, ?_⟩
    · rintro rfl
      have := Int.le_of_dvd one_pos hpx
      omega
    · rintro rfl
      have : (p : ℤ) ∣ (1 : ℤ) := (dvd_neg).mp hpx
      have := Int.le_of_dvd one_pos this
      omega
  · intro hx
    have hnat : x.natAbs ≠ 1 := by
      simp only [ne_eq, Int.natAbs_eq_iff, Nat.cast_one]
      push_neg
      exact ⟨hx.1, hx.2⟩
    obtain ⟨p, hp, hpd⟩ := Nat.exists_prime_and_dvd hnat
    refine ⟨p, hp, ?_⟩
    have : (p : ℤ) ∣ (x.natAbs : ℤ) := by exact_mod_cast hpd
    exact (Int.dvd_natAbs).mp this

/-- **Infinitude of primes (Furstenberg, 1955).** Proved by the topological
contradiction: were the primes finite, `⋃_{p} pℤ` would be a finite union of
closed sets, hence closed, so its complement `{-1, 1}` would be open and therefore
infinite — impossible. This proof cites no Mathlib infinitude result. -/
theorem infinite_setOf_prime : {p : ℕ | p.Prime}.Infinite := by
  by_contra hfin
  rw [Set.not_infinite] at hfin
  -- `P` is the (assumed finite) set of all primes.
  have hmem : ∀ p : ℕ, p ∈ hfin.toFinset ↔ p.Prime := fun p => Set.Finite.mem_toFinset hfin
  -- The union `⋃_{p ∈ P} pℤ` is a finite union of closed sets, hence closed.
  have hclosed : IsClosedF (⋃ p ∈ (hfin.toFinset : Set ℕ), AP 0 (p : ℤ)) := by
    apply isClosedF_biUnion
    intro p hp
    have hpp : p.Prime := (hmem p).mp hp
    exact isClosedF_AP 0 (by exact_mod_cast hpp.pos)
  -- That union is exactly the non-units `{x | x ≠ 1 ∧ x ≠ -1}`.
  have hUeq : (⋃ p ∈ (hfin.toFinset : Set ℕ), AP 0 (p : ℤ))
      = {x : ℤ | x ≠ 1 ∧ x ≠ -1} := by
    ext x
    constructor
    · intro hx
      simp only [Set.mem_iUnion] at hx
      obtain ⟨p, hpP, hxp⟩ := hx
      have hpp : p.Prime := (hmem p).mp (Finset.mem_coe.mp hpP)
      rw [mem_AP_iff_dvd, sub_zero] at hxp
      exact (exists_prime_dvd_iff x).mp ⟨p, hpp, hxp⟩
    · intro hx
      obtain ⟨p, hpp, hpx⟩ := (exists_prime_dvd_iff x).mpr hx
      simp only [Set.mem_iUnion]
      refine ⟨p, ?_, ?_⟩
      · exact Finset.mem_coe.mpr ((hmem p).mpr hpp)
      · rw [mem_AP_iff_dvd, sub_zero]; exact hpx
  -- Hence its complement `{1, -1}` is open.
  have hopen : IsOpenF {x : ℤ | x = 1 ∨ x = -1} := by
    have h := hclosed
    show IsOpenF {x : ℤ | x = 1 ∨ x = -1}
    have : ({x : ℤ | x = 1 ∨ x = -1}) = (⋃ p ∈ (hfin.toFinset : Set ℕ), AP 0 (p : ℤ))ᶜ := by
      rw [hUeq]; ext x; simp only [Set.mem_setOf_eq, Set.mem_compl_iff, not_and_or, not_not]
    rw [this]; exact h
  -- A nonempty open set contains a whole (infinite) progression — contradiction,
  -- since `{1, -1}` is finite.
  obtain ⟨d, hd, hsub⟩ := isOpenF_imp_hasAPNbhd hopen 1 (Or.inl rfl)
  have hinf : (AP 1 d).Infinite := AP_infinite hd
  have hfinset : ({x : ℤ | x = 1 ∨ x = -1}).Finite := by
    have hset : {x : ℤ | x = 1 ∨ x = -1} = ({1, -1} : Set ℤ) := by
      ext x; simp [Set.mem_insert_iff]
    rw [hset]; exact Set.finite_insert _ (Set.finite_singleton _)
  exact hinf (hfinset.subset hsub)

end InfinitudePrimesOQ01
