import Mathlib.NumberTheory.NumberField.Units.Regulator
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.Tactic

/-
# Kronecker's Jugendtraum (Hilbert's 12th), OQ-01: real quadratic fields

## What this file contains

Hilbert's 12th problem (Kronecker's *Jugendtraum*) asks for explicit generators of the
abelian extensions of a number field `K`. It is solved for `K = ℚ` (Kronecker–Weber, roots
of unity) and for imaginary quadratic `K` (complex multiplication of elliptic curves). The
**first genuinely open case** is the family of **real quadratic fields** `K = ℚ(√d)`, `d > 0`.

Why is the real quadratic case harder than the imaginary quadratic one, even though both are
degree `2`? The distinction is *unit-theoretic*. An imaginary quadratic field has unit rank
`0` (its units are just roots of unity), while a real quadratic field has unit rank `1` — an
infinite unit group generated by a fundamental unit. It is precisely this infinite unit, and
the transcendence of its logarithm, that puts real quadratic fields into the domain of the
**Stark conjectures** rather than the classical CM theory.

This file isolates and machine-checks the *structural / unit-theoretic* facts that pin down
the real quadratic case among all degree-`2` number fields. Abstractly, a "real quadratic
field" is a totally real number field of degree `2` over `ℚ`.

It does **not** address the open problem of constructing generators of abelian extensions of
real quadratic fields.

## Main results

* `card_infinitePlace_eq_two`: a totally real degree-`2` field has exactly two infinite
  places (both real).
* `rank_eq_one`: a totally real degree-`2` field has unit rank `1` — the source of the
  fundamental (Stark) unit.
* `rank_eq_one_iff_isTotallyReal`: **the dichotomy.** Among degree-`2` number fields, unit
  rank `1` (real quadratic) holds *iff* the field is totally real; the complementary
  imaginary quadratic case is `rank_eq_zero_of_not_isTotallyReal`, unit rank `0`.
* `regulator_eq_single_log`: for a totally real degree-`2` field the regulator is exactly a
  single archimedean logarithm `|log |ε||` of the fundamental unit `ε` — with **no**
  multiplicity factor, sharpening the general rank-one collapse (where a mixed-signature
  cubic would carry a factor of `2`).

## Proof strategy

Everything is a specialization of Mathlib's Dirichlet unit / infinite-place machinery. The
place counts obey `#(InfinitePlace K) = nrReal + nrComplex` and
`nrReal + 2·nrComplex = [K : ℚ]`; feeding `[K : ℚ] = 2` and (for the real case)
`nrComplex = 0` to `omega` fixes `#(InfinitePlace K) = 2`, hence `rank K = #-1 = 1`. The
regulator statement reproves the rank-one single-log collapse inline from `regulator_eq_det`
on the `equivFinRank`-transported singleton via `Matrix.det_unique`, then kills the
archimedean multiplicity via `IsTotallyReal.mult_eq` (`mult w = 1` at a real place). The file
is self-contained (Mathlib only).
-/

open NumberField NumberField.Units NumberField.InfinitePlace Module
open scoped NumberField

namespace KroneckersJugendtraumOQ01

variable (K : Type*) [Field K] [NumberField K]

/-- **Two infinite places.** A totally real number field of degree `2` has exactly two
infinite places (both real, since totally real fields have no complex places). -/
theorem card_infinitePlace_eq_two [IsTotallyReal K] (h2 : finrank ℚ K = 2) :
    Fintype.card (InfinitePlace K) = 2 := by
  have hc0 : nrComplexPlaces K = 0 := nrComplexPlaces_eq_zero_iff.mpr ‹_›
  have hsum := card_eq_nrRealPlaces_add_nrComplexPlaces K
  have hdeg := card_add_two_mul_card_eq_rank K
  rw [h2] at hdeg
  omega

/-- **Unit rank one.** A totally real number field of degree `2` — an abstract real quadratic
field — has unit rank `1`. By Dirichlet's unit theorem its unit group is `ℤ × (roots of
unity)`; the free part is generated by the fundamental unit that drives the Stark story. -/
theorem rank_eq_one [IsTotallyReal K] (h2 : finrank ℚ K = 2) : rank K = 1 := by
  have hc := card_infinitePlace_eq_two K h2
  rw [rank]
  omega

/-- **The imaginary quadratic complement.** A degree-`2` field that is *not* totally real is
imaginary quadratic: it has unit rank `0`, so (up to roots of unity) it has no nontrivial
units. This is the CM-solved case of Hilbert's 12th problem, and the rank drop is exactly why
it is easier than the real quadratic case. -/
theorem rank_eq_zero_of_not_isTotallyReal (h2 : finrank ℚ K = 2)
    (himag : ¬ IsTotallyReal K) : rank K = 0 := by
  have hne : nrComplexPlaces K ≠ 0 := fun h => himag (nrComplexPlaces_eq_zero_iff.mp h)
  have hsum := card_eq_nrRealPlaces_add_nrComplexPlaces K
  have hdeg := card_add_two_mul_card_eq_rank K
  rw [h2] at hdeg
  rw [rank]
  omega

/-- **The real/imaginary dichotomy.** Among degree-`2` number fields, unit rank `1` (real
quadratic, the open Hilbert-12 case) holds *exactly when* the field is totally real. The
`rank = 0` complement is the CM-solved imaginary quadratic case. -/
theorem rank_eq_one_iff_isTotallyReal (h2 : finrank ℚ K = 2) :
    rank K = 1 ↔ IsTotallyReal K := by
  constructor
  · intro hr
    by_contra himag
    have : rank K = 0 := rank_eq_zero_of_not_isTotallyReal K h2 himag
    omega
  · intro h
    exact rank_eq_one K h2

/-- **The regulator is a single logarithm — with no multiplicity factor.** For a totally real
degree-`2` field the regulator equals `|log |ε||`, the absolute logarithm of the fundamental
(Stark) unit `ε`, with archimedean multiplicity `1`. This sharpens the general rank-one
collapse `regulator_eq_single_log_of_rank_eq_one` (in which the mixed-signature cubic rank-one
case carries a multiplicity `2` from its complex place): the real quadratic regulator is a
bare logarithm, exactly the shape the rank-one abelian Stark conjecture predicts for
`L'(0, χ)`. -/
theorem regulator_eq_single_log [IsTotallyReal K] (h2 : finrank ℚ K = 2) :
    ∃ (w : InfinitePlace K) (ε : (𝓞 K)ˣ),
      regulator K = |Real.log (w (ε : K))| := by
  classical
  have hrank : rank K = 1 := rank_eq_one K h2
  -- `Fin (rank K)` is a singleton because `rank K = 1`, so via `equivFinRank` the index type
  -- of non-`w₀` places is a singleton too.
  haveI huniqFin : Unique (Fin (rank K)) := by rw [hrank]; infer_instance
  haveI huniq : Unique {w : InfinitePlace K // w ≠ dirichletUnitTheorem.w₀} :=
    (equivFinRank K).symm.unique
  refine ⟨(default : {w : InfinitePlace K // w ≠ dirichletUnitTheorem.w₀}).val,
    fundSystem K ((equivFinRank K).symm default), ?_⟩
  -- Express the regulator as a `1×1` determinant, read off its single entry, and kill the
  -- archimedean multiplicity (`mult w = 1` at the real place of a totally real field).
  rw [regulator_eq_det K (dirichletUnitTheorem.w₀) (equivFinRank K).symm,
    Matrix.det_unique, Matrix.of_apply, abs_mul, Nat.abs_cast,
    IsTotallyReal.mult_eq, Nat.cast_one, one_mul]

end KroneckersJugendtraumOQ01
