/-
  Lagrange's Theorem OQ-03-OQ-02:
  A₄ has no subgroup of order 6 — a 0-axiom structural proof.

  The converse of Lagrange's theorem fails: 6 divides |A₄| = 12, yet the
  alternating group A₄ has no subgroup of order 6. This is the classic
  counterexample to "m ∣ |G| ⟹ G has a subgroup of order m".

  ## What is new here

  The parent entry (lagrange-theorem-oq-03) already proves this fact, but it
  discharges the two arithmetic atoms — |A₄| = 12 and "A₄ has 9 distinct
  squares" — with `native_decide`, which trusts the compiler and pulls in the
  `Lean.ofReduceBool` axiom. This file gives a fully structural, **0-axiom**
  proof (`#print axioms` shows only `propext`/`Classical.choice`/`Quot.sound`).

  ## The argument

  Let H ≤ A₄ with |H| = 6. Then [A₄ : H] = 12 / 6 = 2, so H is normal and the
  quotient A₄/H has order 2. Hence g² ∈ H for every g ∈ A₄ (its image in the
  order-2 quotient squares to the identity).

  Every 3-cycle σ has order 3, so σ = σ⁴ = (σ²)² is itself a square; therefore
  every 3-cycle lies in H. But the 3-cycles **generate** A₄
  (`closure_three_cycles_eq_alternating`), so the image of H in `Perm (Fin 4)`
  is all of A₄. Transporting cardinalities back along the injective inclusion
  H ↪ A₄ gives |H| = |A₄| = 12, contradicting |H| = 6.

  This route never enumerates group elements: |A₄| = 12 comes from
  `card_alternatingGroup` (= 4!/2) and the "all squares" / "generated by
  3-cycles" steps are purely algebraic.

  ## References
  - Rotman, J. (2012). "An Introduction to the Theory of Groups." Ch. 3-4.
  - Mathlib: `Mathlib.GroupTheory.SpecificGroups.Alternating`.
-/

import Mathlib

set_option maxHeartbeats 400000
set_option linter.unusedVariables false

open Equiv Equiv.Perm

namespace LagrangeA4

/-- The order of A₄ is 12, obtained structurally from `card_alternatingGroup`
    (|Aₙ| = n!/2), with no `native_decide`. -/
theorem a4_card : Fintype.card (alternatingGroup (Fin 4)) = 12 := by
  rw [card_alternatingGroup]
  decide

/-- If `H` has index 2 in a finite group, then every square lies in `H`:
    the image of `g` in the order-2 quotient squares to the identity. -/
theorem sq_mem_of_index_two {G : Type*} [Group G] (H : Subgroup G) [H.Normal]
    (hindex : H.index = 2) (g : G) : g ^ 2 ∈ H := by
  rw [← QuotientGroup.eq_one_iff]
  have hcard : Nat.card (G ⧸ H) = 2 := by rw [← Subgroup.index]; exact hindex
  haveI : Finite (G ⧸ H) := Nat.finite_of_card_ne_zero (by rw [hcard]; norm_num)
  have hpow : (QuotientGroup.mk' H g) ^ Nat.card (G ⧸ H) = 1 := pow_card_eq_one'
  rw [hcard] at hpow
  rw [← QuotientGroup.mk'_apply, map_pow]
  exact hpow

/-- A subgroup of order 6 in A₄ has index 2 (since |A₄| = 12). -/
theorem index_two_of_card_six
    (H : Subgroup (alternatingGroup (Fin 4))) (hcard : Nat.card H = 6) :
    H.index = 2 := by
  have hmul := Subgroup.card_mul_index H
  have hG : Nat.card (alternatingGroup (Fin 4)) = 12 := by
    rw [Nat.card_eq_fintype_card]; exact a4_card
  rw [hcard, hG] at hmul
  omega

/-- **A₄ has no subgroup of order 6** — fully structural, 0-axiom proof. -/
theorem a4_no_subgroup_order_six :
    ¬ ∃ H : Subgroup (alternatingGroup (Fin 4)), Nat.card H = 6 := by
  rintro ⟨H, hcard⟩
  -- index 2 ⟹ normal ⟹ every square lies in H
  have hindex : H.index = 2 := index_two_of_card_six H hcard
  haveI : H.Normal := Subgroup.normal_of_index_eq_two hindex
  have hsq : ∀ g : alternatingGroup (Fin 4), g ^ 2 ∈ H :=
    sq_mem_of_index_two H hindex
  -- the inclusion A₄ ↪ Perm (Fin 4)
  set f : alternatingGroup (Fin 4) →* Perm (Fin 4) := (alternatingGroup (Fin 4)).subtype with hf
  have hfinj : Function.Injective f := Subtype.val_injective
  -- every 3-cycle lies in the image of H
  have hsub : {σ : Perm (Fin 4) | σ.IsThreeCycle} ⊆ ↑(H.map f) := by
    intro σ hσ
    -- lift σ into A₄
    have hmem : σ ∈ alternatingGroup (Fin 4) := hσ.mem_alternatingGroup
    set x : alternatingGroup (Fin 4) := ⟨σ, hmem⟩ with hx
    -- x has order 3, so x = x⁴ = (x²)²
    have hord : orderOf x = 3 := by
      have : orderOf (f x) = 3 := hσ.orderOf
      rwa [orderOf_injective f hfinj x] at this
    have hx3 : x ^ 3 = 1 := by rw [← hord]; exact pow_orderOf_eq_one x
    have hxsq : (x ^ 2) ^ 2 = x := by
      have h4 : (x ^ 2) ^ 2 = x ^ 3 * x := by group
      rw [h4, hx3, one_mul]
    -- (x²)² ∈ H, hence x ∈ H, hence σ = f x ∈ H.map f
    have hxH : x ∈ H := hxsq ▸ hsq (x ^ 2)
    exact Subgroup.mem_map.mpr ⟨x, hxH, rfl⟩
  -- the 3-cycles generate A₄, so H.map f = A₄
  have hclosure : Subgroup.closure {σ : Perm (Fin 4) | σ.IsThreeCycle} ≤ H.map f :=
    (Subgroup.closure_le (H.map f)).mpr hsub
  have hge : alternatingGroup (Fin 4) ≤ H.map f := by
    have hgen := closure_three_cycles_eq_alternating (α := Fin 4)
    rw [hgen] at hclosure
    exact hclosure
  have hle : H.map f ≤ alternatingGroup (Fin 4) := Subgroup.map_subtype_le H
  have heq : H.map f = alternatingGroup (Fin 4) := le_antisymm hle hge
  -- transport cardinality back along the injective inclusion
  have hcardmap : Nat.card H = Nat.card (H.map f) :=
    Nat.card_congr (Subgroup.equivMapOfInjective H f hfinj).toEquiv
  rw [heq, hcard] at hcardmap
  -- Nat.card (alternatingGroup (Fin 4)) = 12 ≠ 6
  have hG : Nat.card (alternatingGroup (Fin 4)) = 12 := by
    rw [Nat.card_eq_fintype_card]; exact a4_card
  rw [hG] at hcardmap
  omega

/-- **The converse of Lagrange's theorem fails**: 6 ∣ |A₄| = 12, but A₄ has no
    subgroup of order 6. -/
theorem lagrange_converse_fails :
    (6 ∣ Fintype.card (alternatingGroup (Fin 4))) ∧
    ¬ ∃ H : Subgroup (alternatingGroup (Fin 4)), Nat.card H = 6 :=
  ⟨by rw [a4_card]; decide, a4_no_subgroup_order_six⟩

end LagrangeA4
