import Mathlib

/-!
# The Frobenius–Galois structure of finite fields

The parent entry (`LittleWedderburnOQ01OQ01`) records the *classification of finite
fields by cardinality*: two finite fields are isomorphic iff they have the same number
of elements, so for each prime power `p ^ n` there is — up to isomorphism — exactly one
field of that order, namely `GaloisField p n`.

That uniqueness statement is *non‑canonical*: it asserts that the set of isomorphisms
between two fields of order `p ^ n` is **nonempty**, but says nothing about its size or
structure. The classical refinement, due to the Galois theory of finite fields, is:

* the automorphism group `Aut(GF(p^n)) = GF(p^n) ≃ₐ[ZMod p] GF(p^n)` is **cyclic of
  order `n`**, and
* it is generated by the **Frobenius** automorphism `x ↦ x ^ p`; equivalently
  `Subgroup.zpowers Frobenius = ⊤`.

From this one obtains the **torsor** picture promised in the open question: for two
finite fields `K`, `K'` of order `p ^ n`, the set of `ZMod p`‑algebra isomorphisms
`K ≃ₐ[ZMod p] K'` is a *torsor* under the cyclic group `Aut(K')` — the post‑composition
action `σ • f = f.trans σ` is **free** (left cancellation) and **transitive**, and the
set is nonempty.  Fixing any one isomorphism `f₀` therefore identifies the set of
isomorphisms with the Galois group, so there are exactly `n` of them.

## What is Mathlib's and what is new here

Mathlib already supplies the deep facts as *instances/lemmas*:

* `instance : IsCyclic Gal(L/K)` for any finite field extension — cyclicity is automatic;
* `orderOf_frobeniusAlgEquivOfAlgebraic : orderOf Frobenius = Module.finrank K L`;
* `IsGalois.card_aut_eq_finrank : Nat.card Gal(E/F) = Module.finrank F E`.

The content assembled here is the explicit `GF(p^n)` packaging — order `= n`, the
Frobenius identified as `x ↦ x ^ p`, the statement that it *generates* the whole group
(`zpowers = ⊤`) — together with the **torsor** structure on the isomorphism set between
two arbitrary order‑`p^n` fields, which is *not* recorded in Mathlib as a named result.
Everything is machine‑checked with no axioms or sorries.
-/

namespace LittleWedderburnOQ01OQ01OQ01

open scoped Classical
open FiniteField

variable (p n : ℕ) [Fact p.Prime]

instance : NeZero p := ⟨(Fact.out (p := p.Prime)).pos.ne'⟩

/-! ## The automorphism group of `GF(p^n)` -/

/-- **Cyclicity of the Galois group.** The automorphism group of `GF(p^n)` over its prime
subfield is cyclic. Mathlib provides this as an instance for every finite field
extension; we record it explicitly for the Galois field. -/
theorem aut_isCyclic :
    IsCyclic (GaloisField p n ≃ₐ[ZMod p] GaloisField p n) :=
  inferInstance

/-- A general counting lemma: the automorphism group of **any** finite field `K'` of order
`p ^ n` over its prime subfield `ZMod p` has exactly `n` elements, where `n = [K' : ZMod p]`.
This is `IsGalois.card_aut_eq_finrank` specialised to finite fields. -/
theorem card_aut_field_eq {K' : Type*} [Field K'] [Algebra (ZMod p) K'] [Finite K']
    (hcard : Nat.card K' = p ^ n) :
    Nat.card (K' ≃ₐ[ZMod p] K') = n := by
  have hp := (Fact.out (p := p.Prime))
  rw [IsGalois.card_aut_eq_finrank]
  have hpow : p ^ Module.finrank (ZMod p) K' = p ^ n := by
    rw [FiniteField.pow_finrank_eq_natCard p K', hcard]
  exact Nat.pow_right_injective hp.two_le hpow

/-- **Order of the automorphism group.** `|Aut(GF(p^n))| = n`. -/
theorem card_aut_eq (hn : n ≠ 0) :
    Nat.card (GaloisField p n ≃ₐ[ZMod p] GaloisField p n) = n :=
  card_aut_field_eq p n (GaloisField.card p n hn)

/-! ## The Frobenius generator -/

/-- The Frobenius automorphism of `GF(p^n)` is the `ZMod p`‑algebra automorphism
`x ↦ x ^ p`. -/
theorem frobenius_apply (x : GaloisField p n) :
    frobeniusAlgEquivOfAlgebraic (ZMod p) (GaloisField p n) x = x ^ p := by
  simp [ZMod.card]

/-- **Order of the Frobenius.** The Frobenius automorphism has order `n` in the
automorphism group of `GF(p^n)`. -/
theorem orderOf_frobenius (hn : n ≠ 0) :
    orderOf (frobeniusAlgEquivOfAlgebraic (ZMod p) (GaloisField p n)) = n := by
  rw [orderOf_frobeniusAlgEquivOfAlgebraic, GaloisField.finrank p hn]

/-- **The Frobenius generates the Galois group.** Since its order equals the order of the
group, the Frobenius automorphism `x ↦ x ^ p` generates `Aut(GF(p^n))`:
`⟨Frobenius⟩ = Aut(GF(p^n))`. This is the precise sense in which the Galois group is
cyclic *generated by Frobenius*. -/
theorem frobenius_generates (hn : n ≠ 0) :
    Subgroup.zpowers (frobeniusAlgEquivOfAlgebraic (ZMod p) (GaloisField p n)) = ⊤ := by
  rw [← Subgroup.card_eq_iff_eq_top, Nat.card_zpowers, orderOf_frobenius p n hn,
    card_aut_eq p n hn]

/-! ## The torsor of isomorphisms between two fields of order `p^n`

For two finite fields `K`, `K'` of order `p ^ n` over `ZMod p`, the set of
`ZMod p`‑algebra isomorphisms `K ≃ₐ[ZMod p] K'` carries a free and transitive
post‑composition action of the Galois group `Aut(K')`, i.e. it is an `Aut(K')`‑torsor. -/

section Torsor

variable {K K' : Type*} [Field K] [Field K'] [Algebra (ZMod p) K] [Algebra (ZMod p) K']
  [Finite K] [Finite K']

omit [Finite K] [Finite K'] in
/-- **Nonemptiness.** Two finite fields of equal prime‑power order admit a `ZMod p`‑algebra
isomorphism (both are realised inside the canonical Galois field). -/
theorem nonempty_algEquiv (hK : Nat.card K = p ^ n) (hK' : Nat.card K' = p ^ n) :
    Nonempty (K ≃ₐ[ZMod p] K') :=
  ⟨(GaloisField.algEquivGaloisField p n hK).trans
    (GaloisField.algEquivGaloisField p n hK').symm⟩

omit [Finite K] [Finite K'] in
/-- **Freeness of the post‑composition action.** If two automorphisms of `K'` agree after
pre‑composing with a fixed isomorphism `f`, they are equal. Equivalently, the action
`σ • f = f.trans σ` of `Aut(K')` on isomorphisms is free. -/
theorem trans_left_cancel (f : K ≃ₐ[ZMod p] K') (σ τ : K' ≃ₐ[ZMod p] K')
    (h : f.trans σ = f.trans τ) : σ = τ := by
  ext x
  obtain ⟨y, rfl⟩ := f.surjective x
  simpa using AlgEquiv.congr_fun h y

omit [Finite K] [Finite K'] in
/-- **Transitivity of the post‑composition action.** Any two isomorphisms `f, g : K ≃ₐ K'`
differ by a unique automorphism of `K'`: there is `σ ∈ Aut(K')` with `f.trans σ = g`,
namely `σ = f.symm.trans g`. -/
theorem exists_trans_eq (f g : K ≃ₐ[ZMod p] K') :
    ∃ σ : K' ≃ₐ[ZMod p] K', f.trans σ = g :=
  ⟨f.symm.trans g, by ext x; simp⟩

/-- **The torsor identification.** Fixing one isomorphism `f₀ : K ≃ₐ K'` identifies the
Galois group `Aut(K')` with the set of all isomorphisms `K ≃ₐ K'`, via post‑composition
`σ ↦ f₀.trans σ`. This is the concrete statement that the isomorphism set is an
`Aut(K')`‑torsor. -/
def autEquivIso (f₀ : K ≃ₐ[ZMod p] K') :
    (K' ≃ₐ[ZMod p] K') ≃ (K ≃ₐ[ZMod p] K') where
  toFun σ := f₀.trans σ
  invFun g := f₀.symm.trans g
  left_inv σ := by ext x; simp
  right_inv g := by ext x; simp

omit [Finite K] in
/-- **Counting isomorphisms.** Consequently there are exactly `n` distinct
`ZMod p`‑algebra isomorphisms between two finite fields of order `p ^ n`: the torsor has
the same cardinality as the structure group `Aut(K')`, which is `n`. -/
theorem card_algEquiv_eq (hK : Nat.card K = p ^ n) (hK' : Nat.card K' = p ^ n) :
    Nat.card (K ≃ₐ[ZMod p] K') = n := by
  obtain ⟨f₀⟩ := nonempty_algEquiv p n hK hK'
  rw [← Nat.card_congr (autEquivIso p f₀), card_aut_field_eq p n hK']

end Torsor

/-! ## Concrete corollaries -/

/-- The automorphism group of `GF(2^3)` (the field with 8 elements) is cyclic of order `3`,
generated by the Frobenius `x ↦ x ^ 2`. -/
theorem card_aut_galoisField_eight :
    Nat.card (GaloisField 2 3 ≃ₐ[ZMod 2] GaloisField 2 3) = 3 :=
  card_aut_eq 2 3 (by norm_num)

end LittleWedderburnOQ01OQ01OQ01
