/-
# Lovász Local Lemma — OQ-01: Discharging the Independence Hypothesis of the Toolkit

The measure-theoretic OQ-01 program has built an extensive toolkit
(`…Independence.lean`, `…DependencySplit.lean`, `…ChainRule.lean`) whose lemmas all take
as a *standing hypothesis* the pairwise fact that a bad event `A i` is independent of the
joint avoidance of some other index set:

  `IndepSet (A i) (⋂_{j ∈ S} (A j)ᶜ) μ`.

For example `seq_indep_avoidance_eq_prod` assumes `∀ n, IndepSet (A n) (⋂_{j<n} (A j)ᶜ) μ`,
and `cond_failure_eq_measure_of_indep_subset` assumes `IndepSet (A i) (⋂_{j∈S} (A j)ᶜ) μ`.
Their docstrings note that this is "a strictly weaker, one-sided condition that mutual
independence implies" — but that implication itself was **never proved in Lean**: no file
in the program derives such an `IndepSet` from the family-level mutual independence
`iIndepSet A μ`.

This file supplies exactly that missing bridge, over an arbitrary index type, and it is
`0`-axiom / `0`-sorry:

  **`iIndepSet A μ  →  i ∉ S  →  IndepSet (A i) (⋂_{j ∈ S} (A j)ᶜ) μ`.**

The proof routes through `iIndepSet.indep_generateFrom_of_disjoint` for the disjoint index
sets `{i}` and `S`: `A i` is measurable in the σ-algebra generated by `{A i}` and the finite
avoidance is measurable in the σ-algebra generated by `{A k : k ∈ S}`, so the two are
independent. Feeding this term into the existing toolkit removes the standing hypothesis,
so the whole sequential/subset development runs directly from `iIndepSet A μ`.

## Main results

* `indep_avoidance` : `μ (A i ∩ ⋂_{j ∈ S} (A j)ᶜ) = μ (A i) · μ (⋂_{j ∈ S} (A j)ᶜ)` for
  `i ∉ S` — the raw measure factorization.
* `indepSet_avoidance` *(flagship)* : the same fact packaged as
  `IndepSet (A i) (⋂_{j ∈ S} (A j)ᶜ) μ`, the exact term the OQ-01 toolkit assumes.
* `cond_avoidance_eq_self` : `μ[A i | ⋂_{j ∈ S} (A j)ᶜ] = μ (A i)` — the hypothesis-free
  form of `cond_failure_eq_measure_of_indep_subset`, obtained by discharging its `IndepSet`
  assumption with the bridge above.
* `cond_prefix_eq_self` : the chain-rule prefix specialization over a linear order.

`IsProbabilityMeasure` is derived from mutual independence, not assumed.
-/
import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.ConditionalProbability

open MeasureTheory ProbabilityTheory Finset
open scoped ENNReal ProbabilityTheory

namespace LovaszLocalLemmaOQ01CondIndep

variable {Ω : Type*} [MeasurableSpace Ω] {ι : Type*}
variable {μ : Measure Ω} {A : ι → Set Ω}

/-- **Measure factorization: a single event vs. the avoidance of a disjoint index set.**
For a mutually independent family of measurable events, if `i ∉ S` then

  `μ (A i ∩ ⋂_{j ∈ S} (A j)ᶜ) = μ (A i) · μ (⋂_{j ∈ S} (A j)ᶜ)`.

Routes through `iIndepSet.indep_generateFrom_of_disjoint` for the disjoint index sets `{i}`
and `S`: `A i` is measurable in `generateFrom {A i}`, and each complement `(A j)ᶜ` (hence
the finite intersection) is measurable in `generateFrom {A k : k ∈ S}`, so the σ-algebras —
and thus the two events — are independent. -/
theorem indep_avoidance
    (hA : ∀ i, MeasurableSet (A i)) (hind : iIndepSet A μ)
    (i : ι) (S : Finset ι) (hiS : i ∉ S) :
    μ (A i ∩ ⋂ j ∈ S, (A j)ᶜ) = μ (A i) * μ (⋂ j ∈ S, (A j)ᶜ) := by
  -- independence of the σ-algebras generated by the disjoint index sets `{i}` and `↑S`
  have hdisj : Disjoint ({i} : Set ι) (↑S : Set ι) :=
    Set.disjoint_singleton_left.2 (by simpa using hiS)
  have hIndep :=
    hind.indep_generateFrom_of_disjoint hA ({i} : Set ι) (↑S : Set ι) hdisj
  -- `A i` is measurable in `generateFrom {A i}`
  have hm1 :
      MeasurableSet[MeasurableSpace.generateFrom {t | ∃ n ∈ ({i} : Set ι), A n = t}] (A i) :=
    MeasurableSpace.measurableSet_generateFrom ⟨i, rfl, rfl⟩
  -- the avoidance set is measurable in `generateFrom {A k : k ∈ S}`
  have hm2 :
      MeasurableSet[MeasurableSpace.generateFrom {t | ∃ k ∈ (↑S : Set ι), A k = t}]
        (⋂ j ∈ S, (A j)ᶜ) := by
    refine Finset.measurableSet_biInter _ (fun j hj => ?_)
    have hmem : A j ∈ {t | ∃ k ∈ (↑S : Set ι), A k = t} := ⟨j, Finset.mem_coe.2 hj, rfl⟩
    exact (MeasurableSpace.measurableSet_generateFrom hmem).compl
  exact (Indep_iff _ _ μ).1 hIndep (A i) _ hm1 hm2

/-- **The missing bridge: mutual independence discharges the toolkit's `IndepSet` hypothesis.**
For a mutually independent measurable family and `i ∉ S`,

  `IndepSet (A i) (⋂_{j ∈ S} (A j)ᶜ) μ`.

This is precisely the standing hypothesis assumed (but never derived) throughout the OQ-01
measure-theoretic toolkit — e.g. by `seq_indep_avoidance_eq_prod` and
`cond_failure_eq_measure_of_indep_subset`. Supplying this term lets the entire
sequential/subset development be instantiated directly from `iIndepSet A μ`. -/
theorem indepSet_avoidance
    (hA : ∀ i, MeasurableSet (A i)) (hind : iIndepSet A μ)
    (i : ι) (S : Finset ι) (hiS : i ∉ S) :
    IndepSet (A i) (⋂ j ∈ S, (A j)ᶜ) μ := by
  haveI : IsProbabilityMeasure μ := hind.isProbabilityMeasure
  have hSmeas : MeasurableSet (⋂ j ∈ S, (A j)ᶜ) :=
    Finset.measurableSet_biInter _ (fun j _ => (hA j).compl)
  rw [indepSet_iff_measure_inter_eq_mul (hA i) hSmeas μ]
  exact indep_avoidance hA hind i S hiS

/-- **Conditioning on independent avoidance preserves probability (hypothesis-free form).**
For a mutually independent measurable family, conditioning `A i` on the joint avoidance of a
disjoint index set `S` (`i ∉ S`) leaves its probability unchanged, provided that avoidance
has positive probability:

  `μ[A i | ⋂_{j ∈ S} (A j)ᶜ] = μ (A i)`.

This is the conditional identity `cond_failure_eq_measure_of_indep_subset` of the OQ-01
toolkit with its `IndepSet` hypothesis discharged by `indepSet_avoidance`: it now follows
directly from mutual independence. It is the `d = 0` (fully-independent) instance of the
LLL's key inductive step — a bad event is unaffected by conditioning on the avoidance of
events outside its dependency neighbourhood. -/
theorem cond_avoidance_eq_self
    (hA : ∀ i, MeasurableSet (A i)) (hind : iIndepSet A μ)
    (i : ι) (S : Finset ι) (hiS : i ∉ S)
    (hpos : μ (⋂ j ∈ S, (A j)ᶜ) ≠ 0) :
    μ[A i | ⋂ j ∈ S, (A j)ᶜ] = μ (A i) := by
  haveI : IsProbabilityMeasure μ := hind.isProbabilityMeasure
  have hne_top : μ (⋂ j ∈ S, (A j)ᶜ) ≠ ∞ := measure_ne_top μ _
  rw [cond_apply' (hA i) μ, Set.inter_comm _ (A i), indep_avoidance hA hind i S hiS,
    mul_comm (μ (A i)) (μ (⋂ j ∈ S, (A j)ᶜ)), ← mul_assoc,
    ENNReal.inv_mul_cancel hpos hne_top, one_mul]

/-- **Chain-rule prefix specialization.** Over a linearly ordered index, conditioning `A k`
on the avoidance of all *strictly earlier* events leaves its probability unchanged when the
family is independent. Consequently the chain-rule per-event failure probability
`bₖ = μ[A k | ⋂_{j < k} (A j)ᶜ]` collapses to the unconditional `μ (A k)` in the `d = 0`
regime, so the quantitative avoidance bound `∏ (1 - bₖ)` recovers the exact factorization
`∏ (1 - μ (A k))` of the base case — now from `iIndepSet A μ` alone. -/
theorem cond_prefix_eq_self [LinearOrder ι]
    (hA : ∀ i, MeasurableSet (A i)) (hind : iIndepSet A μ)
    (k : ι) (S : Finset ι) (hS : ∀ j ∈ S, j < k)
    (hpos : μ (⋂ j ∈ S, (A j)ᶜ) ≠ 0) :
    μ[A k | ⋂ j ∈ S, (A j)ᶜ] = μ (A k) :=
  cond_avoidance_eq_self hA hind k S (fun hk => lt_irrefl k (hS k hk)) hpos

end LovaszLocalLemmaOQ01CondIndep
