import Mathlib.Data.Complex.Basic
import Mathlib.Analysis.Complex.Norm
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.RingTheory.RootsOfUnity.Complex
import Mathlib.Tactic

/-
# Napoleon's Theorem, OQ-03: Toward Petr–Douglas–Neumann

## The Open Question

Generalize Napoleon's theorem to arbitrary polygons via the
**Petr–Douglas–Neumann (PDN) theorem**: starting from any planar `n`-gon,
repeatedly erecting similar isosceles triangles (apex angle `kπ/n`) on the
sides and taking the apexes as a new polygon eventually produces a regular
`n`-gon.

## What This File Proves

PDN is fundamentally a **spectral** statement. Each "erect-similar-triangles"
construction is a *circulant* linear operator on the `n` vertices:
each new vertex `wⱼ = a·zⱼ + b·z_{j+1}` is the same affine combination of a
vertex and its cyclic successor. Circulant operators are diagonalized by the
discrete Fourier basis — the *regular component polygons* `j ↦ ζ^(m·j)` where
`ζ = e^{2πi/n}`. This file formalizes that mechanism for **all `n`**, then
works the two smallest cases in full.

1. **The circulant apex operator** `apexOp a b` on cyclic `n`-gons
   (`ZMod n → ℂ`).
2. **Spectral diagonalization (general `n`)**: every regular component
   `regular ζ` (with `ζⁿ = 1`) is an *eigenvector* of `apexOp a b` with
   eigenvalue `a + b·ζ` (`apexOp_regular`); the `m`-th Fourier mode has
   eigenvalue `a + b·ζ^m` (`apexOp_mode`).
3. **Mode annihilation**: choosing the apex parameters so that `a + b·ζ = 0`
   makes the operator *kill* that component (`apexOp_regular_eq_zero`). This is
   exactly the step PDN iterates to delete every non-regular frequency.
4. **n = 3 (Napoleon)**: the Napoleon centroid formula
   `(x+y)/2 + i√3/6·(y-x)` (the parent entry's `napoleonCenter`) is literally an
   instance of `apexOp` (`napoleonCentroid_eq_apex`), tying Napoleon's theorem
   into the general framework.
5. **n = 4 (Van Aubel's theorem)** — *fully verified*: the centers of squares
   erected on the sides of any quadrilateral satisfy `P₃ - P₁ = i·(P₄ - P₂)`,
   so the two center-diagonals are **equal in length** and **perpendicular**.
   This is the canonical quadrilateral analogue of Napoleon's theorem.

## What Remains Open

The full PDN theorem requires composing `n - 2` annihilation steps and proving
that deleting every Fourier mode except the regular one yields a regular `n`-gon
(Fourier completeness / Vandermonde invertibility over `ZMod n`). That global
composition is not formalized here; this file supplies the verified spectral
engine and the two smallest fully-worked cases.

## Status
- [x] Circulant apex operator over `ZMod n`
- [x] Regular components are eigenvectors (general `n`, no axioms)
- [x] Eigenvalue of the `m`-th Fourier mode
- [x] Mode-annihilation criterion
- [x] Napoleon (n=3) is an instance of `apexOp`
- [x] Van Aubel (n=4): equal & perpendicular center-diagonals (no axioms)
- [ ] Full PDN composition over all modes (open)
-/

namespace NapoleonsTheoremOQ03

open Complex

-- ============================================================
-- PART 1: The circulant "apex" operator on cyclic n-gons
-- ============================================================

variable {n : ℕ}

/-- A cyclic `n`-gon: vertices indexed by the cyclic group `ZMod n`. -/
abbrev Ngon (n : ℕ) := ZMod n → ℂ

/-- The **apex operator**. Each vertex is replaced by an affine combination of
    itself and its cyclic successor:  `wⱼ = a·zⱼ + b·z_{j+1}`.

    Geometrically, with `a = 1/2 - i·c` and `b = 1/2 + i·c` (so `a + b = 1`),
    `wⱼ` is the apex of the isosceles triangle erected on the directed side
    `[zⱼ, z_{j+1}]`, with the apex height controlled by `c`. This is precisely
    the construction PDN iterates. -/
def apexOp (a b : ℂ) (z : Ngon n) : Ngon n := fun j => a * z j + b * z (j + 1)

/-- The regular component polygon generated by `ζ`:  `j ↦ ζ^(val j)`.
    When `ζ = e^{2πi·m/n}` this is the `m`-th Fourier mode — a regular `n`-gon
    traversed `m` times. -/
def regular (ζ : ℂ) : Ngon n := fun j => ζ ^ j.val

-- ============================================================
-- PART 2: Arithmetic of cyclic exponents
-- ============================================================

/-- If `ζⁿ = 1`, then `ζ^·` depends only on the exponent modulo `n`. -/
theorem pow_eq_pow_of_modEq {ζ : ℂ} (hζ : ζ ^ n = 1) {a b : ℕ}
    (h : a ≡ b [MOD n]) : ζ ^ a = ζ ^ b := by
  have key : ∀ k : ℕ, ζ ^ k = ζ ^ (k % n) := fun k => by
    conv_lhs => rw [← Nat.div_add_mod k n, pow_add, pow_mul, hζ, one_pow, one_mul]
  rw [key a, key b]
  exact congrArg (ζ ^ ·) h

/-- The cyclic successor shifts the `ZMod n` value by one, modulo `n`. -/
theorem val_add_one_modEq [NeZero n] (j : ZMod n) :
    (j + 1).val ≡ j.val + 1 [MOD n] := by
  rw [← ZMod.natCast_eq_natCast_iff, ZMod.natCast_zmod_val]
  push_cast
  rw [ZMod.natCast_zmod_val]

-- ============================================================
-- PART 3: Spectral diagonalization (general n)
-- ============================================================

/-- **Regular components are eigenvectors of every apex operator.**

    For any `ζ` with `ζⁿ = 1`, the circulant operator `apexOp a b` acts on the
    regular component `regular ζ` by scalar multiplication:
      `apexOp a b (regular ζ) = (a + b·ζ) • regular ζ`.

    This is the algebraic heart of the Petr–Douglas–Neumann theorem: in the
    Fourier basis the apex construction is *diagonal*. -/
theorem apexOp_regular [NeZero n] {ζ : ℂ} (hζ : ζ ^ n = 1) (a b : ℂ) :
    apexOp a b (regular (n := n) ζ) = fun j => (a + b * ζ) * regular ζ j := by
  funext j
  simp only [apexOp, regular]
  rw [pow_eq_pow_of_modEq hζ (val_add_one_modEq j), pow_succ]
  ring

/-- The `m`-th Fourier mode `regular (ζ^m)` is an eigenvector with eigenvalue
    `a + b·ζ^m`. -/
theorem apexOp_mode [NeZero n] {ζ : ℂ} (hζ : ζ ^ n = 1) (m : ℕ) (a b : ℂ) :
    apexOp a b (regular (n := n) (ζ ^ m)) =
      fun j => (a + b * ζ ^ m) * regular (ζ ^ m) j := by
  apply apexOp_regular
  rw [← pow_mul, mul_comm m n, pow_mul, hζ, one_pow]

/-- **Mode annihilation.** If the apex parameters are tuned so that
    `a + b·ζ = 0`, then `apexOp a b` deletes the component `regular ζ`
    entirely. Iterating this over the non-regular Fourier modes is the
    mechanism by which PDN drives an arbitrary polygon to a regular one. -/
theorem apexOp_regular_eq_zero [NeZero n] {ζ : ℂ} (hζ : ζ ^ n = 1) {a b : ℂ}
    (h : a + b * ζ = 0) : apexOp a b (regular (n := n) ζ) = 0 := by
  rw [apexOp_regular hζ]
  funext j
  simp only [Pi.zero_apply, h, zero_mul]

-- ============================================================
-- PART 4: n = 3 — Napoleon's centroid is an apex operator
-- ============================================================

/-- The Napoleon centroid formula `(x + y)/2 + i√3/6·(y - x)` — the centroid of
    the equilateral triangle erected on the directed side `[x, y]`, i.e. the
    construction `NapoleonsTheorem.napoleonCenter` of the parent entry — is
    exactly the apex operator with `a = 1/2 - i√3/6`, `b = 1/2 + i√3/6`
    (apex angle 60°). Thus Napoleon's theorem (n = 3) is the smallest instance
    of the PDN spectral framework developed above. -/
theorem napoleonCentroid_eq_apex (x y : ℂ) :
    (x + y) / 2 + I * (↑(Real.sqrt 3) : ℂ) / 6 * (y - x) =
      (1 / 2 - I * (↑(Real.sqrt 3) : ℂ) / 6) * x +
      (1 / 2 + I * (↑(Real.sqrt 3) : ℂ) / 6) * y := by
  ring

-- ============================================================
-- PART 5: n = 4 — Van Aubel's theorem (fully verified)
-- ============================================================

/-- The center of the square erected externally on the directed side `[a, b]`:
      `(a + b)/2 + (i/2)(b - a)`
    (the midpoint, displaced perpendicularly by half the side length). -/
noncomputable def squareCenter (a b : ℂ) : ℂ := (a + b) / 2 + I / 2 * (b - a)

/-- **Van Aubel's identity.** For the square centers `P₁ = sc(z₁,z₂)`,
    `P₂ = sc(z₂,z₃)`, `P₃ = sc(z₃,z₄)`, `P₄ = sc(z₄,z₁)` on the sides of a
    quadrilateral `z₁z₂z₃z₄`:
      `P₃ - P₁ = i · (P₄ - P₂)`.
    Multiplication by `i` is a 90° rotation, so the two segments joining
    opposite square centers are equal in length and perpendicular. -/
theorem vanAubel_identity (z₁ z₂ z₃ z₄ : ℂ) :
    squareCenter z₃ z₄ - squareCenter z₁ z₂ =
      I * (squareCenter z₄ z₁ - squareCenter z₂ z₃) := by
  simp only [squareCenter]
  linear_combination ((z₃ + z₄ - z₁ - z₂) / 2) * Complex.I_sq

/-- **Van Aubel (equal diagonals).** The two center-diagonals have equal length. -/
theorem vanAubel_equal_length (z₁ z₂ z₃ z₄ : ℂ) :
    ‖squareCenter z₃ z₄ - squareCenter z₁ z₂‖ =
      ‖squareCenter z₄ z₁ - squareCenter z₂ z₃‖ := by
  rw [vanAubel_identity, norm_mul, norm_I, one_mul]

/-- **Van Aubel (perpendicular diagonals).** The two center-diagonals are
    orthogonal: the real part of `(P₃ - P₁) · conj(P₄ - P₂)` vanishes. -/
theorem vanAubel_perpendicular (z₁ z₂ z₃ z₄ : ℂ) :
    ((squareCenter z₃ z₄ - squareCenter z₁ z₂) *
      (starRingEnd ℂ) (squareCenter z₄ z₁ - squareCenter z₂ z₃)).re = 0 := by
  rw [vanAubel_identity, mul_assoc, Complex.mul_conj]
  simp [Complex.mul_re]

-- ============================================================
-- PART 6: A concrete primitive root (for instantiation)
-- ============================================================

/-- The standard primitive `n`-th root of unity `e^{2πi/n}` satisfies `ζⁿ = 1`,
    so it may be fed to the spectral lemmas above. -/
theorem primitiveRoot_pow (hn : n ≠ 0) :
    (Complex.exp (2 * ↑Real.pi * I / n)) ^ n = 1 :=
  (isPrimitiveRoot_exp n hn).pow_eq_one

-- ============================================================
-- Summary
-- ============================================================

#check @apexOp_regular            -- regular components are eigenvectors
#check @apexOp_mode               -- eigenvalue a + b·ζ^m
#check @apexOp_regular_eq_zero    -- annihilation of a Fourier mode
#check napoleonCentroid_eq_apex   -- Napoleon (n=3) as an apex operator
#check vanAubel_identity          -- Van Aubel (n=4): P₃-P₁ = i(P₄-P₂)
#check vanAubel_equal_length      -- equal center-diagonals
#check vanAubel_perpendicular     -- perpendicular center-diagonals

end NapoleonsTheoremOQ03
