import Mathlib

/-
# The Prime `2`: Order of `1 + 2·a` and the Non-Cyclicity of `(ZMod 2^k)ˣ`

The parent entry computes, for an **odd** prime `p` and `p ∤ a`, that the multiplicative
order of `1 + p·a` in `ZMod (p^(n+1))` is exactly `p^n`. Every admissible residue attains the
maximal `p`-power order, and this is the engine that makes `(ZMod (p^k))ˣ` cyclic for odd
prime powers.

This file answers the parent's first open question:

> *What is the corresponding order for the prime `2`, where `(ZMod 2^k)ˣ` is not cyclic for
> `k ≥ 3` and `1 + 2·a` behaves differently?*

For `p = 2` the picture genuinely changes, and we make the two phenomena precise.

## 1. The "corresponding order" needs the `1 + 4·a` form

For odd `p` the clean order formula holds for `1 + p·a`.  For `p = 2` the analogous clean
statement is **not** about `1 + 2·a` but about `1 + 4·a` with `a` odd:

`orderOf (1 + 4·a : ZMod (2^(n+2))) = 2^n`   (Mathlib: `ZMod.orderOf_one_add_four_mul`).

So the maximal `2`-power order is reached by the principal units `1 + 4ℤ` (generated by `5`),
not by the larger set `1 + 2ℤ`.  This is the precise sense in which `1 + 2·a` "behaves
differently": the residue `1 + 2·a` mod `4` already splits the units into two cosets, and only
the coset `≡ 1 mod 4` carries the maximal cyclic order.

## 2. `(ZMod 2^k)ˣ` is not cyclic for `k ≥ 3` — an explicit two-involution witness

The structural reason the unit group fails to be cyclic is that it has **more than one element
of order `2`**.  A finite cyclic group has *exactly* `φ(2) = 1` element of order two, so
exhibiting two distinct involutions is a complete and elementary proof of non-cyclicity.

We use the two canonical involutions:

* `-1`, of order `2` (since `ringChar (ZMod 2^k) = 2^k ≠ 2`), and
* `1 + 2^(k-1)`, of order `2` (its square is `1 + 2^k + 2^(2k-2) ≡ 1`),

and they are **distinct** for `k ≥ 3` (they coincide only when `k = 2`).  Counting elements of
order two via `IsCyclic.card_orderOf_eq_totient` then contradicts cyclicity.

This is a different, more constructive proof than Mathlib's `ZMod.isCyclic_units_two_pow_iff`
(which reduces to `not_isCyclic_units_eight` through a surjection); here the obstruction is
named explicitly by two group elements.

Throughout we write `k = n + 3` (so `k ≥ 3`).  No axioms, no `native_decide`.
-/

namespace OrderOneAddMulPrimeOQ0101

open scoped Nat

/-! ### Part 1: the corresponding order for `p = 2` (re-export of the `1 + 4·a` formula) -/

/-- **The "corresponding order" for `p = 2`.** For odd `a`, the multiplicative order of
`1 + 4·a` modulo `2^(n+2)` is `2^n`.  This is the `p = 2` analogue of the parent's
`orderOf (1 + p·a) = p^n`, but with `4·a` (not `2·a`): the maximal `2`-power order is carried by
the principal units `1 + 4ℤ`. -/
theorem orderOf_one_add_four_mul (a : ℤ) (ha : Odd a) (n : ℕ) :
    orderOf (1 + 4 * a : ZMod (2 ^ (n + 2))) = 2 ^ n :=
  ZMod.orderOf_one_add_four_mul a ha n

/-- The textbook generator: `5 = 1 + 4` has order `2^n` modulo `2^(n+2)`, so the principal
units form a cyclic group of order `2^(k-2)` (re-export of `ZMod.orderOf_five`). -/
theorem orderOf_five (n : ℕ) : orderOf (5 : ZMod (2 ^ (n + 2))) = 2 ^ n :=
  ZMod.orderOf_five n

/-! ### Part 2: the two involutions and non-cyclicity -/

/-- `1 < 2^(n+3)`, packaged as a `Fact` so `ZMod (2^(n+3))` is `Nontrivial`. -/
theorem one_lt_two_pow (n : ℕ) : (1 : ℕ) < 2 ^ (n + 3) := by
  have : (8 : ℕ) ≤ 2 ^ (n + 3) := by
    calc (8 : ℕ) = 2 ^ 3 := by norm_num
      _ ≤ 2 ^ (n + 3) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

/-- `2^(n+2)` is nonzero in `ZMod (2^(n+3))`: it is the residue one notch below the modulus. -/
theorem two_pow_ne_zero (n : ℕ) :
    (2 : ZMod (2 ^ (n + 3))) ^ (n + 2) ≠ 0 := by
  rw [show (2 : ZMod (2 ^ (n + 3))) ^ (n + 2) = ((2 ^ (n + 2) : ℕ) : ZMod (2 ^ (n + 3))) by
        push_cast; ring]
  rw [Ne, ZMod.natCast_eq_zero_iff, Nat.pow_dvd_pow_iff_le_right (by norm_num : 1 < 2)]
  omega

/-- The special involution `1 + 2^(k-1)` squares to `1` modulo `2^k`. With `k = n+3`:
`(1 + 2^(n+2))^2 = 1 + 2^(n+3) + 2^(2n+4) ≡ 1`. -/
theorem sq_one_add_two_pow (n : ℕ) :
    (1 + (2 : ZMod (2 ^ (n + 3))) ^ (n + 2)) ^ 2 = 1 := by
  have hmod : (1 + 2 ^ (n + 2)) ^ 2 ≡ 1 [MOD 2 ^ (n + 3)] := by
    calc (1 + 2 ^ (n + 2)) ^ 2
        = 1 + 2 ^ (n + 3) * (1 + 2 ^ (n + 1)) := by ring
      _ ≡ 1 + 0 [MOD 2 ^ (n + 3)] :=
            Nat.ModEq.add_left 1 ((Nat.modEq_zero_iff_dvd).mpr (dvd_mul_right _ _))
      _ = 1 := by ring
  have h := (ZMod.natCast_eq_natCast_iff _ _ _).mpr hmod
  push_cast at h
  convert h using 2

/-- The special involution is not the identity: `1 + 2^(n+2) ≠ 1` in `ZMod (2^(n+3))`. -/
theorem one_add_two_pow_ne_one (n : ℕ) :
    (1 + (2 : ZMod (2 ^ (n + 3))) ^ (n + 2)) ≠ 1 := fun h =>
  two_pow_ne_zero n (by simpa using h)

/-- **Order of the special involution.** `orderOf (1 + 2^(k-1)) = 2` modulo `2^k` (`k = n+3`). -/
theorem orderOf_one_add_two_pow (n : ℕ) :
    orderOf (1 + (2 : ZMod (2 ^ (n + 3))) ^ (n + 2)) = 2 := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  exact orderOf_eq_prime (sq_one_add_two_pow n) (one_add_two_pow_ne_one n)

/-- **Order of `-1`.** `orderOf (-1) = 2` modulo `2^k` for `k ≥ 2` (here `k = n+3`), because the
ring characteristic is `2^k ≠ 2`. -/
theorem orderOf_neg_one (n : ℕ) :
    orderOf (-1 : ZMod (2 ^ (n + 3))) = 2 := by
  haveI : Fact (1 < 2 ^ (n + 3)) := ⟨one_lt_two_pow n⟩
  rw [_root_.orderOf_neg_one, if_neg]
  rw [ringChar.eq (ZMod (2 ^ (n + 3))) (2 ^ (n + 3))]
  have h8 : (8 : ℕ) ≤ 2 ^ (n + 3) := by
    calc (8 : ℕ) = 2 ^ 3 := by norm_num
      _ ≤ 2 ^ (n + 3) := Nat.pow_le_pow_right (by norm_num) (by omega)
  omega

/-- The two involutions are **distinct** for `k ≥ 3`: `-1 ≠ 1 + 2^(k-1)` modulo `2^k`.
They coincide only at `k = 2`. -/
theorem neg_one_ne_one_add_two_pow (n : ℕ) :
    (-1 : ZMod (2 ^ (n + 3))) ≠ 1 + (2 : ZMod (2 ^ (n + 3))) ^ (n + 2) := by
  intro h
  -- From `-1 = 1 + 2^(n+2)` we get `2 + 2^(n+2) = 0`.
  have h0 : (2 : ZMod (2 ^ (n + 3))) + 2 ^ (n + 2) = 0 := by linear_combination -h
  -- But `0 < 2 + 2^(n+2) < 2^(n+3)`, so its cast is nonzero.
  have hcast : ((2 + 2 ^ (n + 2) : ℕ) : ZMod (2 ^ (n + 3))) = 0 := by push_cast; exact h0
  rw [ZMod.natCast_eq_zero_iff] at hcast
  have hle := Nat.le_of_dvd (by positivity) hcast
  have h4 : (4 : ℕ) ≤ 2 ^ (n + 2) := by
    calc (4 : ℕ) = 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (n + 2) := Nat.pow_le_pow_right (by norm_num) (by omega)
  have hpow : (2 : ℕ) ^ (n + 3) = 2 * 2 ^ (n + 2) := by ring
  omega

/-- **`(ZMod 2^k)ˣ` is not cyclic for `k ≥ 3`.**  We exhibit two distinct elements of order
two in the unit group, `-1` and `1 + 2^(k-1)`; a cyclic group has exactly `φ(2) = 1` such
element, a contradiction. -/
theorem not_isCyclic_units_two_pow (n : ℕ) :
    ¬ IsCyclic (ZMod (2 ^ (n + 3)))ˣ := by
  haveI : NeZero (2 ^ (n + 3)) := ⟨by positivity⟩
  intro hcyc
  haveI : IsCyclic (ZMod (2 ^ (n + 3)))ˣ := hcyc
  -- The special involution `1 + 2^(n+2)` as a unit.
  have hxx : (1 + (2 : ZMod (2 ^ (n + 3))) ^ (n + 2)) * (1 + 2 ^ (n + 2)) = 1 := by
    rw [← pow_two]; exact sq_one_add_two_pow n
  set ux : (ZMod (2 ^ (n + 3)))ˣ := Units.mkOfMulEqOne _ _ hxx with hux
  have huxval : (ux : ZMod (2 ^ (n + 3))) = 1 + 2 ^ (n + 2) := by
    rw [hux, Units.val_mkOfMulEqOne]
  -- Both involutions have order two in the unit group.
  have hord_neg : orderOf (-1 : (ZMod (2 ^ (n + 3)))ˣ) = 2 := by
    rw [← orderOf_units, Units.coe_neg_one]; exact orderOf_neg_one n
  have hord_x : orderOf ux = 2 := by
    rw [← orderOf_units, huxval]; exact orderOf_one_add_two_pow n
  -- They are distinct units.
  have hne : (-1 : (ZMod (2 ^ (n + 3)))ˣ) ≠ ux := by
    intro hxe
    have hv := congrArg Units.val hxe
    rw [Units.coe_neg_one, huxval] at hv
    exact neg_one_ne_one_add_two_pow n hv
  -- The number of order-two elements equals `φ(2) = 1`.
  have hdvd : (2 : ℕ) ∣ Fintype.card (ZMod (2 ^ (n + 3)))ˣ := by
    rw [ZMod.card_units_eq_totient, Nat.totient_prime_pow Nat.prime_two (by omega)]
    exact (dvd_pow_self 2 (by omega : n + 3 - 1 ≠ 0)).mul_right _
  have hcount := IsCyclic.card_orderOf_eq_totient
    (α := (ZMod (2 ^ (n + 3)))ˣ) (d := 2) hdvd
  rw [Nat.totient_two] at hcount
  -- But two distinct elements live in that set, so its card is `> 1`.
  have h1 : (-1 : (ZMod (2 ^ (n + 3)))ˣ) ∈
      Finset.filter (fun a => orderOf a = 2) Finset.univ :=
    (Finset.mem_filter_univ _).mpr hord_neg
  have h2 : ux ∈ Finset.filter (fun a => orderOf a = 2) Finset.univ :=
    (Finset.mem_filter_univ _).mpr hord_x
  have hlt : 1 < (Finset.filter
      (fun a : (ZMod (2 ^ (n + 3)))ˣ => orderOf a = 2) Finset.univ).card :=
    Finset.one_lt_card_iff.mpr ⟨_, _, h1, h2, hne⟩
  omega

/-! ### Part 3: the contrast with the odd-prime case, and concrete instances -/

/-- **Cyclicity dichotomy at the prime `2`** (re-export of `ZMod.isCyclic_units_two_pow_iff`):
`(ZMod 2^k)ˣ` is cyclic iff `k ≤ 2`.  Combined with the odd-prime case (where the unit group is
always cyclic) this isolates the prime `2`, powers `≥ 3`, as the sole non-cyclic prime-power. -/
theorem isCyclic_units_two_pow_iff (k : ℕ) :
    IsCyclic (ZMod (2 ^ k))ˣ ↔ k ≤ 2 :=
  ZMod.isCyclic_units_two_pow_iff k

/-- Concrete instance `k = 3`: `(ZMod 8)ˣ` is not cyclic, obtained from the general theorem
(not by kernel evaluation). -/
theorem not_isCyclic_units_eight : ¬ IsCyclic (ZMod 8)ˣ := by
  simpa using not_isCyclic_units_two_pow 0

/-- Concrete order computation: `orderOf (-1 : ZMod 8) = 2`. -/
theorem orderOf_neg_one_eight : orderOf (-1 : ZMod 8) = 2 := by
  simpa using orderOf_neg_one 0

/-- Concrete order computation: `orderOf (5 : ZMod 8) = 2`, the maximal `2`-power order
`2^(k-2) = 2` of a principal unit. -/
theorem orderOf_five_eight : orderOf (5 : ZMod 8) = 2 := by
  simpa using orderOf_five 1

end OrderOneAddMulPrimeOQ0101
