/-
Pell's Equation OQ-07: The Cayley–Hamilton Linear Recurrence of Pell Solutions

The root entry (`pell-equation`) records that the solutions of `x² − D y² = 1`
form a group generated by the fundamental solution: every solution is a power of
`(x₁ + y₁√D)` inside `ℤ[√D]` (`IsFundamental.eq_zpow_or_neg_zpow`). That
classification is *multiplicative* — it describes the solution set as a set of
powers. This entry extracts the *additive* shadow of that structure that the root
entry leaves implicit: each coordinate of the power sequence satisfies a
**second-order linear recurrence**, and the coefficients are fixed by the
characteristic polynomial of the generating quadratic integer.

Working inside Mathlib's ring of quadratic integers `ℤ√d = Zsqrtd d` for an
arbitrary `d : ℤ`, every element `a` satisfies its own characteristic relation

    a² = (2·re a)·a − N(a)              (`Zsqrtd.sq_eq_trace_mul_sub_norm`)

— the Cayley–Hamilton theorem for the 2×2 multiplication-by-`a` matrix, whose
trace is `2·re a` and whose determinant is the norm `N(a)`. Multiplying by `aⁿ`
turns this into a recurrence for the whole power sequence,

    aⁿ⁺² = (2·re a)·aⁿ⁺¹ − N(a)·aⁿ,

and reading off the two coordinates gives, for both `x` and `y`,

    uₙ₊₂ = (2·re a)·uₙ₊₁ − N(a)·uₙ.

For a Pell solution `N(a) = 1`, so this collapses to the clean recurrence

    uₙ₊₂ = (2·x₁)·uₙ₊₁ − uₙ,

whose coefficient is **twice the first coordinate of the generating solution**.
This is the general-`D` explanation of the sibling entry
`pell-equation-oq-06-oq-03`, where the `x²−2y²` chain obeys `uₙ₊₂ = 6 uₙ₊₁ − uₙ`:
the relevant norm-`+1` generator there is `3 + 2√2 = ⟨3,2⟩ ∈ ℤ[√2]`, and indeed
`2·3 = 6` (`pell_two_recurrence`). The characteristic polynomial
`t² − (2·re a) t + N(a)` of the recurrence is exactly the one whose roots are the
conjugate units `a`, `ā`.

We also prove the converse-style rigidity statement: a second-order linear
recurrence together with two initial values determines the sequence uniquely
(`seq_unique`), so the recurrence + first two coordinates *characterize* the Pell
power sequence.

Main results:
  • `Zsqrtd.sq_eq_trace_mul_sub_norm` — `a² = (2·re a)·a − N(a)` for every `a : ℤ√d`.
  • `Zsqrtd.pow_recurrence`          — `aⁿ⁺² = (2·re a)·aⁿ⁺¹ − N(a)·aⁿ`.
  • `Zsqrtd.re_recurrence` / `im_recurrence` — the same recurrence in each coordinate.
  • `re_recurrence_pell` / `im_recurrence_pell` — norm-`1` collapse to `… − uₙ`.
  • `seq_unique`                     — recurrence + 2 initial values ⇒ unique sequence.
  • `pell_two_recurrence`            — the `D = 2` instance `uₙ₊₂ = 6 uₙ₊₁ − uₙ`.

All proofs are `sorry`-free and axiom-free (no `native_decide`).

References:
- Root entry: `pell-equation` (the multiplicative classification of solutions).
- Sibling entry: `pell-equation-oq-06-oq-03` (the `D = 2` recurrence `6 uₙ₊₁ − uₙ`).
- Sibling entry: `pell-equation-oq-06-oq-02` (the chain as powers of a unit of ℤ[√2]).
- Mathlib `Mathlib/NumberTheory/Zsqrtd/Basic.lean`
  (`Zsqrtd`, `Zsqrtd.norm`, `Zsqrtd.norm_def`, `Zsqrtd.re_mul`, `Zsqrtd.im_mul`).
- Cayley–Hamilton: `M² = (tr M)·M − (det M)·I` for a 2×2 matrix `M`.
-/

import Mathlib

namespace PellEquationOQ07

/-
## The characteristic relation of a quadratic integer

Every `a : ℤ√d` is a root of its characteristic polynomial
`t² − (2·re a) t + N(a)`, where `2·re a = a + ā` is the trace and `N(a) = a·ā` is
the determinant of multiplication by `a`. This is a coordinate-free statement; we
prove it by comparing the two real/`√d` components.
-/

/-- **Cayley–Hamilton for `ℤ[√d]`.** Every quadratic integer satisfies
    `a² = (2·re a)·a − N(a)`. The coefficients are the trace `2·re a = a + ā` and
    the determinant `N(a) = a·ā` of the multiplication-by-`a` map. No hypothesis on
    `a` is needed. -/
theorem Zsqrtd.sq_eq_trace_mul_sub_norm {d : ℤ} (a : ℤ√d) :
    a ^ 2 = ((2 * a.re : ℤ) : ℤ√d) * a - ((a.norm : ℤ) : ℤ√d) := by
  rw [pow_two]
  refine Zsqrtd.ext ?_ ?_
  · simp only [Zsqrtd.re_mul, Zsqrtd.re_sub, Zsqrtd.re_intCast, Zsqrtd.im_intCast,
      Zsqrtd.norm_def]
    ring
  · simp only [Zsqrtd.im_mul, Zsqrtd.im_sub, Zsqrtd.re_intCast, Zsqrtd.im_intCast]
    ring

/-
## The recurrence for the power sequence
-/

/-- **The power sequence obeys a second-order recurrence in `ℤ[√d]`:**
    `aⁿ⁺² = (2·re a)·aⁿ⁺¹ − N(a)·aⁿ`. Obtained from the characteristic relation by
    multiplying through by `aⁿ` (`aⁿ⁺² = a²·aⁿ`). -/
theorem Zsqrtd.pow_recurrence {d : ℤ} (a : ℤ√d) (n : ℕ) :
    a ^ (n + 2)
      = ((2 * a.re : ℤ) : ℤ√d) * a ^ (n + 1) - ((a.norm : ℤ) : ℤ√d) * a ^ n := by
  have hsplit : a ^ (n + 2) = a ^ 2 * a ^ n := by ring
  rw [hsplit, Zsqrtd.sq_eq_trace_mul_sub_norm a]; ring

/-- **First-coordinate recurrence:** `re(aⁿ⁺²) = (2·re a)·re(aⁿ⁺¹) − N(a)·re(aⁿ)`.
    Reading the `ℤ[√d]` recurrence on the rational part. -/
theorem Zsqrtd.re_recurrence {d : ℤ} (a : ℤ√d) (n : ℕ) :
    (a ^ (n + 2)).re
      = 2 * a.re * (a ^ (n + 1)).re - a.norm * (a ^ n).re := by
  have h := congrArg Zsqrtd.re (Zsqrtd.pow_recurrence a n)
  simpa [Zsqrtd.re_mul, Zsqrtd.re_sub, Zsqrtd.re_intCast, Zsqrtd.im_intCast] using h

/-- **Second-coordinate recurrence:** `im(aⁿ⁺²) = (2·re a)·im(aⁿ⁺¹) − N(a)·im(aⁿ)`.
    The `√d`-coefficient obeys the *same* recurrence as the rational part. -/
theorem Zsqrtd.im_recurrence {d : ℤ} (a : ℤ√d) (n : ℕ) :
    (a ^ (n + 2)).im
      = 2 * a.re * (a ^ (n + 1)).im - a.norm * (a ^ n).im := by
  have h := congrArg Zsqrtd.im (Zsqrtd.pow_recurrence a n)
  simpa [Zsqrtd.im_mul, Zsqrtd.im_sub, Zsqrtd.re_intCast, Zsqrtd.im_intCast] using h

/-
## The Pell collapse: norm `1`

When `a` is a *Pell* solution, i.e. `N(a) = 1`, the determinant term is `−aₙ` and
the recurrence becomes the classical `uₙ₊₂ = (2·x₁)·uₙ₊₁ − uₙ`, whose only
coefficient is twice the first coordinate of the generating solution.
-/

/-- **The Pell first-coordinate recurrence** `xₙ₊₂ = (2·x₁)·xₙ₊₁ − xₙ`. When the
    generator has norm `1`, the determinant term collapses and the recurrence is
    governed by the single coefficient `2·re a`. -/
theorem re_recurrence_pell {d : ℤ} (a : ℤ√d) (h : a.norm = 1) (n : ℕ) :
    (a ^ (n + 2)).re = 2 * a.re * (a ^ (n + 1)).re - (a ^ n).re := by
  rw [Zsqrtd.re_recurrence a n, h]; ring

/-- **The Pell second-coordinate recurrence** `yₙ₊₂ = (2·x₁)·yₙ₊₁ − yₙ.** The same
    collapse for the `√d`-coordinate. -/
theorem im_recurrence_pell {d : ℤ} (a : ℤ√d) (h : a.norm = 1) (n : ℕ) :
    (a ^ (n + 2)).im = 2 * a.re * (a ^ (n + 1)).im - (a ^ n).im := by
  rw [Zsqrtd.im_recurrence a n, h]; ring

/-
## Rigidity: the recurrence and two initial values determine the sequence

A second-order linear recurrence `uₙ₊₂ = c·uₙ₊₁ − uₙ` with two prescribed initial
values has a unique solution. Together with the recurrences above this shows that
`(2·x₁, 1, 0)`-type data *characterizes* the Pell coordinate sequences.
-/

/-- **Uniqueness for a second-order linear recurrence.** Two integer sequences that
    obey `uₙ₊₂ = c·uₙ₊₁ − uₙ` and agree at `n = 0, 1` agree everywhere. A standard
    two-step induction. -/
theorem seq_unique (c : ℤ) (f g : ℕ → ℤ)
    (h0 : f 0 = g 0) (h1 : f 1 = g 1)
    (hf : ∀ n, f (n + 2) = c * f (n + 1) - f n)
    (hg : ∀ n, g (n + 2) = c * g (n + 1) - g n) :
    ∀ n, f n = g n := by
  have key : ∀ n, f n = g n ∧ f (n + 1) = g (n + 1) := by
    intro n
    induction n with
    | zero => exact ⟨h0, h1⟩
    | succ k ih =>
      obtain ⟨ihk, ihk1⟩ := ih
      refine ⟨ihk1, ?_⟩
      rw [hf k, hg k, ihk, ihk1]
  exact fun n => (key n).1

/-- **The Pell first-coordinate sequence is the unique solution of its recurrence.**
    Any integer sequence matching `re(a⁰), re(a¹)` and obeying
    `uₙ₊₂ = (2·re a)·uₙ₊₁ − uₙ` equals `re(aⁿ)`. -/
theorem re_pell_unique {d : ℤ} (a : ℤ√d) (h : a.norm = 1) (u : ℕ → ℤ)
    (h0 : u 0 = (a ^ 0).re) (h1 : u 1 = (a ^ 1).re)
    (hrec : ∀ n, u (n + 2) = 2 * a.re * u (n + 1) - u n) :
    ∀ n, u n = (a ^ n).re :=
  seq_unique (2 * a.re) u (fun n => (a ^ n).re) h0 h1 hrec
    (fun n => re_recurrence_pell a h n)

/-
## The `D = 2` instance: recovering `uₙ₊₂ = 6 uₙ₊₁ − uₙ`

The sibling entry `pell-equation-oq-06-oq-03` works with the chain of `x²−2y²`
solutions, whose norm-`+1` generator is `3 + 2√2 = ⟨3,2⟩ ∈ ℤ[√2]`. The general
coefficient `2·re a` evaluates to `2·3 = 6`, giving exactly that entry's
recurrence.
-/

/-- The norm-`+1` fundamental unit of `ℤ[√2]`. `N(3 + 2√2) = 3² − 2·2² = 1`. -/
theorem norm_three_two : ((⟨3, 2⟩ : ℤ√2)).norm = 1 := by decide

/-- The recurrence coefficient for the `D = 2` Pell generator is `2·3 = 6`, the
    coefficient of `pell-equation-oq-06-oq-03`. -/
theorem coeff_two : 2 * ((⟨3, 2⟩ : ℤ√2)).re = 6 := by decide

/-- **The `D = 2` Pell recurrence** `xₙ₊₂ = 6 xₙ₊₁ − xₙ`, recovered as the
    `2·re ⟨3,2⟩ = 6` instance of the general norm-`1` recurrence. This is the
    general-`D` explanation of the coefficient `6` in `pell-equation-oq-06-oq-03`. -/
theorem pell_two_recurrence (n : ℕ) :
    ((⟨3, 2⟩ : ℤ√2) ^ (n + 2)).re
      = 6 * ((⟨3, 2⟩ : ℤ√2) ^ (n + 1)).re - ((⟨3, 2⟩ : ℤ√2) ^ n).re := by
  have key := re_recurrence_pell (⟨3, 2⟩ : ℤ√2) norm_three_two n
  rw [show ((⟨3, 2⟩ : ℤ√2)).re = 3 from rfl] at key
  linarith [key]

/-
## Sanity checks against the explicit `D = 2` chain

The norm-`+1` chain `(3+2√2)ⁿ` begins `1, 3, 17, 99, 577, …` in the first
coordinate; the recurrence `aₙ₊₂ = 6 aₙ₊₁ − aₙ` is visible:
`17 = 6·3 − 1`, `99 = 6·17 − 3`, `577 = 6·99 − 17`.
-/

example : ((⟨3, 2⟩ : ℤ√2) ^ 2).re = 6 * ((⟨3, 2⟩ : ℤ√2) ^ 1).re - ((⟨3, 2⟩ : ℤ√2) ^ 0).re :=
  pell_two_recurrence 0
example : (17 : ℤ) = 6 * 3 - 1 := by norm_num
example : (99 : ℤ) = 6 * 17 - 3 := by norm_num
example : (577 : ℤ) = 6 * 99 - 17 := by norm_num

-- The general recurrence with the determinant term, on a non-Pell example `a = √2`
-- (`N(√2) = −2`): `aₙ₊₂ = 0·aₙ₊₁ + 2·aₙ`, i.e. the powers of `√2`.
example : ((⟨0, 1⟩ : ℤ√2)).norm = -2 := by decide

#check @Zsqrtd.sq_eq_trace_mul_sub_norm
#check @Zsqrtd.pow_recurrence
#check @Zsqrtd.re_recurrence
#check @Zsqrtd.im_recurrence
#check @re_recurrence_pell
#check @im_recurrence_pell
#check @seq_unique
#check @re_pell_unique
#check @pell_two_recurrence

end PellEquationOQ07
