import Mathlib

/-
# Pell Equation OQ-01-OQ-04-OQ-02-OQ-02: the cyclic subgroup ⟨a⟩ as an ordered group

The parent `pell-equation-oq-01-oq-04-oq-02` proved that for a Pell solution `a`
with real embedding `‖a‖ = x + y√d > 1`, the regulator ruler `n ↦ R(aⁿ) = n · R(a)`
is **strictly monotone**, hence the power map `n ↦ aⁿ` is **injective** and `a` has
infinite order.

This entry packages that faithfulness into a genuine **isomorphism of ordered
groups**

  `(ℤ, +, <)  ≃  (⟨a⟩, ·, ⪯)`,

where `⟨a⟩ = Subgroup.zpowers a` is the cyclic subgroup generated by `a` and `⪯` is
the order *pulled back from the regulator*: `g ⪯ h  ↔  R(g) ≤ R(h)`. Concretely:

* `pellPowLinearOrder`     : the regulator induces a genuine `LinearOrder` on `↥⟨a⟩`.
  This needs `‖a‖ > 1`: only then is `g ↦ R(g)` injective on the subgroup (a torsion
  `a` would collapse distinct powers to the same regulator value).
* `pellPowOrderIso`        : the explicit order isomorphism `ℤ ≃o ↥⟨a⟩`, sending
  `n ↦ aⁿ`. Monotonicity in both directions is exactly `StrictMono.le_iff_le` applied
  to the regulator ruler; bijectivity is `zpow_injective` (parent) together with the
  defining surjectivity of `zpowers`.
* `pellPowOrderIso_apply`  : the iso really is the power map, `e(n) = aⁿ`.
* `pellPowOrderIso_map_mul`: `e(m + n) = e(m) · e(n)` — so `e` is simultaneously a
  group isomorphism, making `(ℤ,+,<) ≃ (⟨a⟩,·,⪯)` an isomorphism of **ordered groups**,
  not merely of ordered sets.

The mathematical content is that `R` realizes the abstract cyclic group `⟨a⟩` as a
concrete discrete subgroup `R(a)·ℤ` of the ordered additive group `(ℝ,+,<)`: the
exponent line `ℤ`, the cyclic subgroup `⟨a⟩`, and the lattice `R(a)·ℤ ⊂ ℝ` are all
the *same* ordered group, witnessed by the single strictly-positive number `R(a)`.

The supporting norm/regulator lemmas are restated verbatim from the parent chain so
the file is self-contained; the genuinely new content is the ordered-group iso layer.

`0` axioms.
-/

namespace PellEquationOQ01OQ04OQ02OQ02

open Pell

/-- The Pell norm `x + y√d` (matching the grandparent definition). -/
noncomputable def pellNorm (d : ℤ) (x y : ℤ) : ℝ :=
  (x : ℝ) + (y : ℝ) * Real.sqrt (d : ℝ)

/-- The Pell regulator `log(x + y√d)` (matching the grandparent definition). -/
noncomputable def pellRegulator (d : ℤ) (a : Solution₁ d) : ℝ :=
  Real.log (pellNorm d a.x a.y)

variable {d : ℤ}

/-- The norm of the identity solution `(1, 0)` is `1`. -/
theorem pellNorm_one (d : ℤ) :
    pellNorm d (1 : Solution₁ d).x (1 : Solution₁ d).y = 1 := by
  rw [Solution₁.x_one, Solution₁.y_one]
  simp [pellNorm]

/-- **Brahmagupta's identity / norm multiplicativity** (parent). -/
theorem pellNorm_mul (d : ℤ) (hd : 0 ≤ d) (a b : Solution₁ d) :
    pellNorm d (a * b).x (a * b).y = pellNorm d a.x a.y * pellNorm d b.x b.y := by
  simp only [pellNorm, Solution₁.x_mul, Solution₁.y_mul]
  have hsq : Real.sqrt (d : ℝ) ^ 2 = (d : ℝ) := Real.sq_sqrt (by exact_mod_cast hd)
  push_cast
  linear_combination (-((a.y : ℝ) * (b.y : ℝ))) * hsq

/-- **The conjugate identity** (parent): `pellNorm a · pellNorm a⁻¹ = 1`. -/
theorem pellNorm_mul_inv (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) :
    pellNorm d a.x a.y * pellNorm d a⁻¹.x a⁻¹.y = 1 := by
  rw [Solution₁.x_inv, Solution₁.y_inv]
  simp only [pellNorm]
  have hsq : Real.sqrt (d : ℝ) ^ 2 = (d : ℝ) := Real.sq_sqrt (by exact_mod_cast hd)
  have hprop : (a.x : ℝ) ^ 2 - (d : ℝ) * (a.y : ℝ) ^ 2 = 1 := by exact_mod_cast a.prop
  push_cast
  linear_combination hprop - ((a.y : ℝ) ^ 2) * hsq

/-- The Pell norm is never zero (parent). -/
theorem pellNorm_ne_zero (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) :
    pellNorm d a.x a.y ≠ 0 := by
  intro h
  have hkey := pellNorm_mul_inv d hd a
  rw [h, zero_mul] at hkey
  exact zero_ne_one hkey

/-- **The norm of the inverse is the reciprocal of the norm** (parent). -/
theorem pellNorm_inv (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) :
    pellNorm d a⁻¹.x a⁻¹.y = (pellNorm d a.x a.y)⁻¹ := by
  have hkey := pellNorm_mul_inv d hd a
  have hne := pellNorm_ne_zero d hd a
  have h1 : pellNorm d a⁻¹.x a⁻¹.y = 1 / pellNorm d a.x a.y := by
    rw [eq_div_iff hne, mul_comm]; exact hkey
  rw [h1, one_div]

/-- **The Pell norm intertwines integer powers with real `zpow`** (parent):
`pellNorm (aⁿ) = (pellNorm a)ⁿ` for every `n : ℤ`. -/
theorem pellNorm_zpow (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) (n : ℤ) :
    pellNorm d (a ^ n).x (a ^ n).y = (pellNorm d a.x a.y) ^ n := by
  have hne : pellNorm d a.x a.y ≠ 0 := pellNorm_ne_zero d hd a
  refine Int.induction_on n ?_ ?_ ?_
  · simp [pellNorm]
  · intro k ih
    rw [zpow_add_one, pellNorm_mul d hd, ih, zpow_add_one₀ hne]
  · intro k ih
    rw [zpow_sub_one, pellNorm_mul d hd, ih, pellNorm_inv d hd, zpow_sub_one₀ hne]

/-- **The regulator scales linearly along all integer powers** (parent):
`R(aⁿ) = n · R(a)` for every `n : ℤ`. -/
theorem pellRegulator_zpow (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) (n : ℤ) :
    pellRegulator d (a ^ n) = (n : ℝ) * pellRegulator d a := by
  unfold pellRegulator
  rw [pellNorm_zpow d hd, Real.log_zpow]

/-- **A solution lying strictly beyond `1` has strictly positive regulator** (parent). -/
theorem pellRegulator_pos (d : ℤ) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) : 0 < pellRegulator d a :=
  Real.log_pos h

/-- **The regulator strictly monotonically orders the integer powers** (parent). -/
theorem pellRegulator_zpow_strictMono (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) :
    StrictMono (fun n : ℤ => pellRegulator d (a ^ n)) := by
  have hpos := pellRegulator_pos d a h
  intro m n hmn
  simp only [pellRegulator_zpow d hd]
  exact mul_lt_mul_of_pos_right (by exact_mod_cast hmn) hpos

/-! ## New content: the cyclic subgroup as an ordered group -/

/-- **The regulator induces a `LinearOrder` on the cyclic subgroup `⟨a⟩`.**
The map `g ↦ R(g)` separates points of `Subgroup.zpowers a` precisely when `‖a‖ > 1`:
every element is some `aᵏ`, and the strictly monotone ruler `k ↦ R(aᵏ)` then assigns
distinct values to distinct exponents. We pull `(ℝ, ≤)` back along this injection. -/
noncomputable def pellPowLinearOrder (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) : LinearOrder ↥(Subgroup.zpowers a) :=
  LinearOrder.lift' (fun g => pellRegulator d (g : Solution₁ d)) (by
    intro g₁ g₂ heq
    obtain ⟨k₁, hk₁⟩ := Subgroup.mem_zpowers_iff.mp g₁.2
    obtain ⟨k₂, hk₂⟩ := Subgroup.mem_zpowers_iff.mp g₂.2
    apply Subtype.ext
    rw [← hk₁, ← hk₂]
    have hkeq : k₁ = k₂ := by
      apply (pellRegulator_zpow_strictMono d hd a h).injective
      show pellRegulator d (a ^ k₁) = pellRegulator d (a ^ k₂)
      rw [hk₁, hk₂]
      exact heq
    rw [hkeq])

/-- **The cyclic subgroup `⟨a⟩` is order-isomorphic to `(ℤ, <)`.**
The order isomorphism is the power map `n ↦ aⁿ`. It is a bijection (`zpow_injective`
from the parent gives injectivity; surjectivity is the definition of `zpowers`), and
it is order-preserving in both directions because the subgroup order is, by
construction, the regulator order, and `n ↦ R(aⁿ)` is strictly monotone. -/
noncomputable def pellPowOrderIso (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) :
    letI := pellPowLinearOrder d hd a h
    ℤ ≃o ↥(Subgroup.zpowers a) :=
  letI := pellPowLinearOrder d hd a h
  { toFun := fun n => ⟨a ^ n, Subgroup.mem_zpowers_iff.mpr ⟨n, rfl⟩⟩
    invFun := fun g => Classical.choose (Subgroup.mem_zpowers_iff.mp g.2)
    left_inv := fun n => by
      apply (pellRegulator_zpow_strictMono d hd a h).injective
      have hspec := Classical.choose_spec (Subgroup.mem_zpowers_iff.mp
        (⟨a ^ n, Subgroup.mem_zpowers_iff.mpr ⟨n, rfl⟩⟩ : ↥(Subgroup.zpowers a)).2)
      show pellRegulator d (a ^ Classical.choose _) = pellRegulator d (a ^ n)
      rw [hspec]
    right_inv := fun g => Subtype.ext
      (Classical.choose_spec (Subgroup.mem_zpowers_iff.mp g.2))
    map_rel_iff' := by
      intro m n
      show pellRegulator d (a ^ m) ≤ pellRegulator d (a ^ n) ↔ m ≤ n
      exact (pellRegulator_zpow_strictMono d hd a h).le_iff_le }

/-- **The order isomorphism is literally the power map**: `e(n) = aⁿ`. -/
theorem pellPowOrderIso_apply (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) (n : ℤ) :
    ((pellPowOrderIso d hd a h n : ↥(Subgroup.zpowers a)) : Solution₁ d) = a ^ n :=
  rfl

/-- **The order isomorphism is also a group homomorphism**: `e(m + n) = e(m) · e(n)`.
Together with `pellPowOrderIso` this exhibits `(ℤ, +, <) ≃ (⟨a⟩, ·, ⪯)` as an
isomorphism of ordered groups: the additive exponent line maps to the multiplicative
cyclic subgroup, preserving both the group law and the order. -/
theorem pellPowOrderIso_map_mul (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) (m n : ℤ) :
    pellPowOrderIso d hd a h (m + n)
      = pellPowOrderIso d hd a h m * pellPowOrderIso d hd a h n := by
  apply Subtype.ext
  rw [Subgroup.coe_mul, pellPowOrderIso_apply, pellPowOrderIso_apply,
    pellPowOrderIso_apply, zpow_add]

/-- **The identity exponent maps to the identity element**: `e(0) = 1`. -/
theorem pellPowOrderIso_map_zero (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d)
    (h : 1 < pellNorm d a.x a.y) :
    pellPowOrderIso d hd a h 0 = 1 := by
  apply Subtype.ext
  rw [pellPowOrderIso_apply, OneMemClass.coe_one, zpow_zero]

end PellEquationOQ01OQ04OQ02OQ02
