import Mathlib

/-
# Pell Equation OQ-01-OQ-04-OQ-01: the regulator scales linearly over **all integer** exponents

The parent entry `pell-equation-oq-01-oq-04` proved that the Pell norm
`N(a) = x + y√d` is a multiplicative homomorphism on Mathlib's group of Pell
solutions `Pell.Solution₁ d` (pairs `(x, y)` with `x² − d·y² = 1`), hence the
regulator `R(a) = log N(a)` is additive, and on **natural** powers it scales:

  `N(aⁿ) = N(a)ⁿ`,    `R(aⁿ) = n·R(a)`    `(n : ℕ)`.

Restricting to `n ≥ 0` artificially truncates the `ℤ`-indexed orbit
`{aⁿ : n ∈ ℤ}` generated by a fundamental solution: the negative side encodes
the conjugate / inverse solutions, which are equally part of the unit group.
This leaf removes that restriction and proves both laws for **every integer
exponent**:

* `pellNorm_inv`        : `N(a⁻¹) = N(a)⁻¹` — the norm of the inverse solution
  (the conjugate `(x, −y)`) is the real reciprocal of the norm.
* `pellNorm_zpow`       : **`N(aⁿ) = N(a)ⁿ` for all `n : ℤ`** (real `zpow`).
* `pellRegulator_zpow`  : **`R(aⁿ) = n·R(a)` for all `n : ℤ`**, so the regulator
  is a genuine `ℤ`-linear character of the solution group.

The negative branch is the only new content: write `n = −m`, push the group
`zpow` through `zpow_neg` to an inverse, convert the norm of the inverse with
`pellNorm_inv`, and reduce to the natural-power law `pellNorm_pow`. The real
side mirrors this via `zpow_neg` / `zpow_natCast` on `ℝ`. Taking logs with
`Real.log_zpow` (valid for any sign since `N(a) ≠ 0`) gives the regulator law.

The defining engine — Brahmagupta composition and the conjugate identity
`(x + y√d)(x − y√d) = x² − d·y² = 1` — is inherited from the parent and
re-derived here so the entry is self-contained.

`0` axioms.
-/

namespace PellEquationOQ01OQ04OQ01

open Pell

/-- The Pell norm `x + y√d` (matching the parent definition). -/
noncomputable def pellNorm (d : ℤ) (x y : ℤ) : ℝ :=
  (x : ℝ) + (y : ℝ) * Real.sqrt (d : ℝ)

/-- The Pell regulator `log(x + y√d)` (matching the parent definition). -/
noncomputable def pellRegulator (d : ℤ) (a : Solution₁ d) : ℝ :=
  Real.log (pellNorm d a.x a.y)

variable {d : ℤ}

/-- The norm of the identity solution `(1, 0)` is `1`. -/
theorem pellNorm_one (d : ℤ) :
    pellNorm d (1 : Solution₁ d).x (1 : Solution₁ d).y = 1 := by
  rw [Solution₁.x_one, Solution₁.y_one]
  simp [pellNorm]

/-- **Brahmagupta's identity / norm multiplicativity** (parent). For `d ≥ 0`,
`pellNorm (a·b) = pellNorm a · pellNorm b`. -/
theorem pellNorm_mul (d : ℤ) (hd : 0 ≤ d) (a b : Solution₁ d) :
    pellNorm d (a * b).x (a * b).y = pellNorm d a.x a.y * pellNorm d b.x b.y := by
  simp only [pellNorm, Solution₁.x_mul, Solution₁.y_mul]
  have hsq : Real.sqrt (d : ℝ) ^ 2 = (d : ℝ) := Real.sq_sqrt (by exact_mod_cast hd)
  push_cast
  linear_combination (-((a.y : ℝ) * (b.y : ℝ))) * hsq

/-- **The conjugate identity** (parent). `pellNorm a · pellNorm a⁻¹ = 1`, i.e.
`(x + y√d)(x − y√d) = x² − d·y² = 1`, since `a⁻¹ = (x, −y)`. -/
theorem pellNorm_mul_inv (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) :
    pellNorm d a.x a.y * pellNorm d a⁻¹.x a⁻¹.y = 1 := by
  rw [Solution₁.x_inv, Solution₁.y_inv]
  simp only [pellNorm]
  have hsq : Real.sqrt (d : ℝ) ^ 2 = (d : ℝ) := Real.sq_sqrt (by exact_mod_cast hd)
  have hprop : (a.x : ℝ) ^ 2 - (d : ℝ) * (a.y : ℝ) ^ 2 = 1 := by exact_mod_cast a.prop
  push_cast
  linear_combination hprop - ((a.y : ℝ) ^ 2) * hsq

/-- The Pell norm is never zero (parent). -/
theorem pellNorm_ne_zero (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) :
    pellNorm d a.x a.y ≠ 0 := by
  intro h
  have hkey := pellNorm_mul_inv d hd a
  rw [h, zero_mul] at hkey
  exact zero_ne_one hkey

/-- The norm of a natural power is the power of the norm (parent). -/
theorem pellNorm_pow (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) (n : ℕ) :
    pellNorm d (a ^ n).x (a ^ n).y = (pellNorm d a.x a.y) ^ n := by
  induction n with
  | zero => rw [pow_zero, pow_zero]; exact pellNorm_one d
  | succ n ih => rw [pow_succ, pellNorm_mul d hd, ih, pow_succ]

/-- **The norm of the inverse solution is the reciprocal of the norm.**
`N(a⁻¹) = N(a)⁻¹`. This is the conjugate identity `N(a)·N(a⁻¹) = 1` read as an
inverse in the field `ℝ`; it is what lets the `zpow` law cover negative
exponents. -/
theorem pellNorm_inv (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) :
    pellNorm d a⁻¹.x a⁻¹.y = (pellNorm d a.x a.y)⁻¹ := by
  have hne := pellNorm_ne_zero d hd a
  field_simp
  linear_combination pellNorm_mul_inv d hd a

/-- **The norm of an integer power is the integer power of the norm.**
`N(aⁿ) = N(a)ⁿ` for every `n : ℤ`, where the right-hand `^` is the real `zpow`.
The non-negative branch reduces to `pellNorm_pow`; the negative branch pushes the
group `zpow` to an inverse (`zpow_neg`), rewrites the norm of the inverse with
`pellNorm_inv`, and again reduces to `pellNorm_pow`. -/
theorem pellNorm_zpow (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) (n : ℤ) :
    pellNorm d (a ^ n).x (a ^ n).y = (pellNorm d a.x a.y) ^ n := by
  obtain ⟨m, rfl | rfl⟩ := Int.eq_nat_or_neg n
  · rw [zpow_natCast, zpow_natCast]
    exact pellNorm_pow d hd a m
  · rw [zpow_neg, zpow_neg, pellNorm_inv d hd, zpow_natCast, zpow_natCast,
      pellNorm_pow d hd]

/-- **The regulator scales linearly along all integer powers.**
`R(aⁿ) = n·R(a)` for every `n : ℤ`. Taking logs of `pellNorm_zpow` (the norm is
nonzero, so `Real.log_zpow` applies for either sign), the regulator becomes a
genuine `ℤ`-linear character of the solution group: a fundamental solution of
regulator `R(D)` generates the full two-sided tower of regulators
`…, −2R(D), −R(D), 0, R(D), 2R(D), …`. -/
theorem pellRegulator_zpow (d : ℤ) (hd : 0 ≤ d) (a : Solution₁ d) (n : ℤ) :
    pellRegulator d (a ^ n) = (n : ℝ) * pellRegulator d a := by
  unfold pellRegulator
  rw [pellNorm_zpow d hd, Real.log_zpow]

end PellEquationOQ01OQ04OQ01
