import Mathlib

/-
# `60` is the *sharp* universal divisor of Pythagorean products

A **Pythagorean triple** is a triple of integers `(x, y, z)` with `x² + y² = z²`.  The sibling
entry `pythagorean-triples-oq-06-oq-01-oq-01` (`PythagoreanTriples60`) proves the divisibility
package

> `60 ∣ x·y·z` for **every** Pythagorean triple,

with the three prime-power factors `3, 4, 5` of `60 = 2²·3·5` each forced by a finite congruence
obstruction.  This file answers that entry's second recorded open question:

> *Identify the largest constant `C` such that `C ∣ xyz` for every Pythagorean triple, and prove
> `60` is sharp by exhibiting a triple whose product is divisible by no prime power beyond those
> in `60` (e.g. `(3,4,5)` with `xyz = 60`).*

## Result

Call `C` a **universal divisor** if `C ∣ xyz` for every Pythagorean triple.  We prove:

* `sixty_universal` — `60` is a universal divisor (the sibling's package).
* `universal_iff_dvd_sixty` — `C` is a universal divisor **iff** `C ∣ 60`.  So the universal
  divisors are *exactly* the divisors of `60`; the lattice of universal divisors is generated by
  the single value `60`.
* `sixty_isGreatest` — among the positive universal divisors, `60` is the **greatest**
  (`IsGreatest`).  This is the sharpness statement: no constant larger than `60` divides the
  product of every triple.

The witness throughout is the triple `(3,4,5)`, whose product is *exactly* `60`.  Because
`3·4·5 = 60 = 2²·3·5`, this single triple already certifies that none of the higher prime powers
`8 = 2³`, `9 = 3²`, `25 = 5²` is forced — recorded as `not_universal_eight / _nine /
_twentyfive`.  Hence each prime-power factor appearing in `60` is individually maximal: the
package `60 ∣ xyz` cannot be strengthened at any prime.

The proof is `0`-axiom.  The forward direction of the characterization is a one-line application
of the universal hypothesis to `(3,4,5)`; the reverse direction chains divisibility through the
sibling's `60 ∣ xyz`.  The `60 ∣ xyz` engine is reproduced here (self-contained, `decide` over
small `ZMod`s) so the entry stands alone.
-/

namespace PythagoreanTriples60Sharp

/-! ## The `60 ∣ xyz` engine (reproduced from the sibling, self-contained) -/

/-- Transport an integer Pythagorean relation `x²+y²=z²` to the ring `ZMod n`. -/
theorem zmod_rel (n : ℕ) {x y z : ℤ} (h : x ^ 2 + y ^ 2 = z ^ 2) :
    (x : ZMod n) ^ 2 + (y : ZMod n) ^ 2 = (z : ZMod n) ^ 2 := by
  exact_mod_cast congrArg (fun t : ℤ => (t : ZMod n)) h

/-- If over `ZMod n` every solution of `a²+b²=c²` has `a·b·c = 0`, then `n ∣ x·y·z` for every
integer Pythagorean triple.  Used for `n = 3, 5`. -/
theorem dvd_prod_of_zmod {n : ℕ} {x y z : ℤ} (h : x ^ 2 + y ^ 2 = z ^ 2)
    (key : ∀ a b c : ZMod n, a ^ 2 + b ^ 2 = c ^ 2 → a * b * c = 0) :
    (n : ℤ) ∣ x * y * z := by
  have hzero : ((x * y * z : ℤ) : ZMod n) = 0 := by
    push_cast
    exact key _ _ _ (zmod_rel n h)
  exact (ZMod.intCast_zmod_eq_zero_iff_dvd _ n).1 hzero

/-- **`3 ∣ xyz`** for every Pythagorean triple. -/
theorem three_dvd_prod {x y z : ℤ} (h : x ^ 2 + y ^ 2 = z ^ 2) : (3 : ℤ) ∣ x * y * z := by
  have key : ∀ a b c : ZMod 3, a ^ 2 + b ^ 2 = c ^ 2 → a * b * c = 0 := by decide
  exact_mod_cast dvd_prod_of_zmod h key

/-- **`5 ∣ xyz`** for every Pythagorean triple. -/
theorem five_dvd_prod {x y z : ℤ} (h : x ^ 2 + y ^ 2 = z ^ 2) : (5 : ℤ) ∣ x * y * z := by
  have key : ∀ a b c : ZMod 5, a ^ 2 + b ^ 2 = c ^ 2 → a * b * c = 0 := by decide
  exact_mod_cast dvd_prod_of_zmod h key

/-- **`4 ∣ xyz`** for every Pythagorean triple.  Invisible modulo `4`, so read off modulo `8`. -/
theorem four_dvd_prod {x y z : ℤ} (h : x ^ 2 + y ^ 2 = z ^ 2) : (4 : ℤ) ∣ x * y * z := by
  have key : ∀ a b c : ZMod 8, a ^ 2 + b ^ 2 = c ^ 2 →
      (ZMod.castHom (show (4 : ℕ) ∣ 8 by norm_num) (ZMod 4)) (a * b * c) = 0 := by decide
  have h8 := key _ _ _ (zmod_rel 8 h)
  have e : (x : ZMod 8) * (y : ZMod 8) * (z : ZMod 8) = ((x * y * z : ℤ) : ZMod 8) := by
    push_cast; ring
  rw [e, map_intCast] at h8
  exact (ZMod.intCast_zmod_eq_zero_iff_dvd _ 4).1 h8

/-- **`60 ∣ xyz`** for every Pythagorean triple. -/
theorem sixty_dvd_prod {x y z : ℤ} (h : x ^ 2 + y ^ 2 = z ^ 2) : (60 : ℤ) ∣ x * y * z := by
  have h3 := three_dvd_prod h
  have h4 := four_dvd_prod h
  have h5 := five_dvd_prod h
  have h12 : (12 : ℤ) ∣ x * y * z := by
    have hcop : IsCoprime (3 : ℤ) 4 := by
      rw [Int.isCoprime_iff_gcd_eq_one]; decide
    have := hcop.mul_dvd h3 h4
    norm_num at this; exact this
  have hcop : IsCoprime (12 : ℤ) 5 := by
    rw [Int.isCoprime_iff_gcd_eq_one]; decide
  have := hcop.mul_dvd h12 h5
  norm_num at this; exact this

/-! ## Sharpness: `60` is the greatest universal divisor -/

/-- `C` is a **universal divisor** of Pythagorean products if `C ∣ x·y·z` for every triple
`x² + y² = z²`. -/
def UniversalDivisor (C : ℤ) : Prop :=
  ∀ x y z : ℤ, x ^ 2 + y ^ 2 = z ^ 2 → C ∣ x * y * z

/-- `60` is a universal divisor — the sibling's divisibility package. -/
theorem sixty_universal : UniversalDivisor 60 := fun _ _ _ h => sixty_dvd_prod h

/-- The witness `(3, 4, 5)` is a Pythagorean triple whose product is exactly `60`. -/
theorem triple_345 : (3 : ℤ) ^ 2 + 4 ^ 2 = 5 ^ 2 ∧ (3 : ℤ) * 4 * 5 = 60 := by
  norm_num

/-- **Necessity.**  Any universal divisor divides `60`, since `(3,4,5)` has product `60`. -/
theorem universal_dvd_sixty {C : ℤ} (hC : UniversalDivisor C) : C ∣ 60 := by
  have h := hC 3 4 5 (by norm_num)
  simpa only [show (3 : ℤ) * 4 * 5 = 60 by norm_num] using h

/-- **Characterization.**  The universal divisors are *exactly* the divisors of `60`. -/
theorem universal_iff_dvd_sixty {C : ℤ} : UniversalDivisor C ↔ C ∣ 60 := by
  constructor
  · exact universal_dvd_sixty
  · intro hC x y z h
    exact hC.trans (sixty_dvd_prod h)

/-- **Sharpness.**  Among the positive universal divisors, `60` is the greatest:
no constant larger than `60` divides the product of every Pythagorean triple. -/
theorem sixty_isGreatest : IsGreatest {C : ℤ | 0 < C ∧ UniversalDivisor C} 60 := by
  refine ⟨⟨by norm_num, sixty_universal⟩, ?_⟩
  rintro C ⟨_, hCuniv⟩
  exact Int.le_of_dvd (by norm_num) (universal_dvd_sixty hCuniv)

/-! ### Each prime power in `60 = 2²·3·5` is individually maximal

The witness `(3,4,5)` has product `60`, divisible by no higher prime power, so none of
`8 = 2³`, `9 = 3²`, `25 = 5²` is a universal divisor. -/

/-- `8 = 2³` is *not* a universal divisor: the `2`-part of the package stops at `4`. -/
theorem not_universal_eight : ¬ UniversalDivisor 8 := by
  intro h; have := universal_dvd_sixty h; norm_num at this

/-- `9 = 3²` is *not* a universal divisor: the `3`-part of the package stops at `3`. -/
theorem not_universal_nine : ¬ UniversalDivisor 9 := by
  intro h; have := universal_dvd_sixty h; norm_num at this

/-- `25 = 5²` is *not* a universal divisor: the `5`-part of the package stops at `5`. -/
theorem not_universal_twentyfive : ¬ UniversalDivisor 25 := by
  intro h; have := universal_dvd_sixty h; norm_num at this

/-- Consequently `120 = 2·60` is not a universal divisor either — `60` cannot be doubled. -/
theorem not_universal_onehundredtwenty : ¬ UniversalDivisor 120 := by
  intro h; have := universal_dvd_sixty h; norm_num at this

/-! ### Phrased through Mathlib's `PythagoreanTriple` structure -/

/-- `60 ∣ xyz` for any `PythagoreanTriple`, the structure form of `sixty_universal`. -/
theorem sixty_dvd_prod_of_pythagoreanTriple {x y z : ℤ} (h : PythagoreanTriple x y z) :
    (60 : ℤ) ∣ x * y * z :=
  sixty_dvd_prod (by have := h.eq; ring_nf; ring_nf at this; linarith)

end PythagoreanTriples60Sharp
