#!/usr/bin/env python3
"""
Certificate for the SOLE remaining open step of zsqrtd-neg-two-oq-02:

    exists_slice_point_lt_two_mul   (Proofs/ThreeSquaresSliceMinkowski.lean:47)

      For d in {1, 2}, p > 0, and any r : Z, the index-p sublattice
          L_{p,r} = { (x, y) in Z^2 : p | (x - r*y) }
      contains a NONZERO vector with the binary form value
          x^2 + d*y^2  <  2*p.

This is the 2D geometry-of-numbers input that, combined with the proved bridge
`slice_point_to_dirichlet_vector`, discharges `dirichlet_key_lemma` in
Proofs/ThreeSquares.lean (one of its two deep axioms).

What this script certifies (all reproducible, integer arithmetic):

  (A) TRUTH over a wide range: for every d in {1,2}, every p in [1, PMAX], and
      every residue r in [0, p), the MINIMUM of x^2 + d*y^2 over the nonzero
      vectors of L_{p,r} is strictly < 2*p.  Reports 0 failures expected.

  (B) HERMITE TIGHTNESS: the worst-case ratio  min_value / p  observed.
      Hermite's binary bound is  min <= (2/sqrt(3)) * sqrt(d) * p, i.e.
        d=1: ratio <= 2/sqrt(3)        ~= 1.1547
        d=2: ratio <= 2*sqrt(2)/sqrt(3) ~= 1.6330
      Both are < 2, which is WHY the lemma is true; the script confirms the
      empirical worst case sits just under these constants.

  (C) WHY THE NAIVE THUE BOX BOUND IS INSUFFICIENT FOR d=2.
      Thue's pigeonhole gives a nonzero point with |x|, |y| <= floor(sqrt(p)),
      hence x^2 + d*y^2 <= (1 + d) * p.  For d=1 that is <= 2p (the two-square
      route), but for d=2 it is only <= 3p -- TOO WEAK.  The script exhibits
      sublattices where the best *Thue-box* point has x^2 + 2y^2 >= 2p, proving
      the formalization MUST use the Minkowski AREA bound (disk), not the box.
      This pins the Mathlib route to
        exists_ne_zero_mem_lattice_of_measure_mul_two_pow_lt_measure
      (the strict-< convex-body theorem on the disk {x^2 + d*y^2 <= R}).
"""

import math

PMAX = 1200      # p range for the exhaustive truth check (part A; O(sqrt p) per (p,r))
PMAX_BOX = 400   # smaller range for the Thue-box comparison (part C; O(p) per (p,r))


def lattice_min(p, r, d):
    """Minimum of x^2 + d*y^2 over NONZERO (x,y) with p | (x - r*y).

    The sublattice is generated by (p, 0) and (r, 1); every element is
    (a*p + b*r, b) for integers a, b. For each b in a bounded window we pick
    the integer a minimizing |a*p + b*r|, then minimize the form. The window
    on |b| only needs to reach where d*b^2 already exceeds the current best.
    """
    best = None
    # b = 0 forces x = a*p, nonzero needs |a|>=1 -> value p^2 (only matters when p small)
    # Search b up to where d*b^2 < 2*p (beyond that x^2+d*y^2 >= d*b^2 >= 2p, useless).
    bmax = int(math.isqrt((2 * p) // max(d, 1))) + 2
    for b in range(-bmax, bmax + 1):
        # choose x = a*p + b*r nearest to 0
        # x congruent to b*r mod p; nearest representative to 0:
        c = (b * r) % p
        for x in (c, c - p):  # the two nearest residues straddling 0
            if b == 0 and x == 0:
                # would be the zero vector; the next nonzero in b=0 line is x=+-p
                for xx in (p, -p):
                    val = xx * xx + d * b * b
                    if best is None or val < best:
                        best = val
                continue
            val = x * x + d * b * b
            if val == 0:
                continue
            if best is None or val < best:
                best = val
    return best


def thue_box_min(p, r, d):
    """Best x^2 + d*y^2 among sublattice points inside the Thue box
    |x|, |y| <= floor(sqrt(p)). Returns None if the box holds only the
    zero vector (can happen for tiny p)."""
    s = int(math.isqrt(p))
    best = None
    for y in range(-s, s + 1):
        for x in range(-s, s + 1):
            if x == 0 and y == 0:
                continue
            if (x - r * y) % p == 0:
                val = x * x + d * y * y
                if best is None or val < best:
                    best = val
    return best


def main():
    print(f"=== (A) TRUTH CHECK: min over L_{{p,r}} of x^2+d*y^2 < 2p, p in [1,{PMAX}], all r ===")
    failures = 0
    worst_ratio = {1: 0.0, 2: 0.0}
    worst_at = {1: None, 2: None}
    for d in (1, 2):
        for p in range(1, PMAX + 1):
            for r in range(0, p):
                m = lattice_min(p, r, d)
                assert m is not None and m > 0
                if not (m < 2 * p):
                    failures += 1
                    if failures <= 10:
                        print(f"  FAIL d={d} p={p} r={r}: min={m} >= 2p={2*p}")
                ratio = m / p
                if ratio > worst_ratio[d]:
                    worst_ratio[d] = ratio
                    worst_at[d] = (p, r, m)
    print(f"  failures (min >= 2p): {failures}  (expect 0)")
    for d in (1, 2):
        hermite = (2 / math.sqrt(3)) * math.sqrt(d)
        p, r, m = worst_at[d]
        print(f"  d={d}: worst ratio min/p = {worst_ratio[d]:.5f}  "
              f"(at p={p}, r={r}, min={m})   Hermite cap 2*sqrt(d)/sqrt(3) = {hermite:.5f}  "
              f"[< 2: {'OK' if worst_ratio[d] < 2 else 'VIOLATED'}]")

    print()
    print("=== (B)/(C) THUE BOX vs AREA BOUND: does the |x|,|y|<=floor(sqrt p) box suffice? ===")
    for d in (1, 2):
        box_fail = 0          # box's best point has value >= 2p (box bound insufficient)
        box_empty = 0         # box holds only zero vector
        examples = []
        for p in range(2, PMAX_BOX + 1):
            for r in range(0, p):
                bm = thue_box_min(p, r, d)
                if bm is None:
                    box_empty += 1
                    continue
                if not (bm < 2 * p):
                    box_fail += 1
                    if len(examples) < 5:
                        examples.append((p, r, bm))
        print(f"  d={d}: Thue-box best point >= 2p in {box_fail} (p,r) cases; "
              f"box-empty {box_empty}.")
        if examples:
            print(f"         e.g. {examples}  -> box bound (<= (1+d)p) is too weak; "
                  f"need disk/area Minkowski.")
        if d == 1 and box_fail == 0:
            print("         d=1: Thue box ALWAYS suffices (the classical two-square route).")
    print()
    print("CONCLUSION: exists_slice_point_lt_two_mul is TRUE (0 failures); d=1 is reachable by")
    print("the elementary Thue box, but d=2 genuinely requires the Minkowski AREA bound on the")
    print("disk {x^2+2y^2 <= R} via exists_ne_zero_mem_lattice_of_measure_mul_two_pow_lt_measure.")


if __name__ == "__main__":
    main()
