/**
 * Re-align legacy line-based annotations to the Lean source they describe.
 *
 * The gallery's legacy annotations (`src/data/proofs/<id>/annotations.json`,
 * array form) reference Lean constructs by line number. When a Lean file
 * changes, those numbers go stale and `scripts/annotations/build.ts` reports
 * them as misaligned ("No Lean construct found at line N", "Annotation type X
 * but found Y", "Lines A-B out of bounds"). This tool moves each misaligned
 * range back onto the construct it was written about, using the same parser
 * and the same alignment rules as the validator:
 *
 *   1. by NAME  — an identifier in the annotation's title (or a backticked
 *                 identifier in its content) that is the name of a declaration
 *                 in the Lean file; the nearest such declaration to the old
 *                 position wins.
 *   2. by PROXIMITY — the nearest construct within WINDOW lines of the old
 *                 start whose kind is compatible with the annotation's type
 *                 (theorem ↔ theorem/example, lemma ↔ lemma, definition ↔
 *                 def/abbrev/structure/inductive, …); generic types (concept,
 *                 insight, tactic, …) accept any construct. Ambiguous ties are
 *                 left alone.
 *
 * A move sets the range to the construct's full extent (doc comment through
 * end of declaration). When the matched construct's kind contradicts a
 * kind-specific annotation type, the type is corrected to what the Lean
 * source actually says.
 *
 * Anchor-based proofs (those with `annotations.source.json`) are skipped —
 * their `annotations.json` is generated by `pnpm annotations:build`.
 *
 * Usage:
 *   pnpm tsx scripts/annotations/realign-lines.ts              # dry run, summary
 *   pnpm tsx scripts/annotations/realign-lines.ts --verbose    # per-annotation detail
 *   pnpm tsx scripts/annotations/realign-lines.ts --apply      # write changes
 *   pnpm tsx scripts/annotations/realign-lines.ts --proof erdos-60 --verbose
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parseLeanFile, findConstructAtLine } from './lean-parser.js';
import type { LeanConstruct, ParsedLeanFile } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROOFS_DATA_DIR = path.join(__dirname, '../../src/data/proofs');
const PROOFS_SOURCE_DIR = path.join(__dirname, '../../proofs/Proofs');
const WINDOW = 15;

const args = process.argv.slice(2);
const APPLY = args.includes('--apply');
const VERBOSE = args.includes('--verbose');
const proofFilterIdx = args.indexOf('--proof');
const PROOF_FILTER = proofFilterIdx >= 0 ? args[proofFilterIdx + 1] : null;

// Same compatibility table as validateLineAnnotations in resolver.ts.
const KIND_COMPAT: Record<string, string[]> = {
  theorem: ['theorem', 'example'],
  lemma: ['lemma'],
  definition: ['def', 'abbrev', 'structure', 'inductive'],
  axiom: ['axiom'],
  inductive: ['inductive'],
  structure: ['structure'],
  def: ['def'],
  example: ['example'],
};
const KIND_TO_TYPE: Record<string, string> = {
  theorem: 'theorem',
  lemma: 'lemma',
  def: 'definition',
  abbrev: 'definition',
  structure: 'structure',
  inductive: 'inductive',
  axiom: 'axiom',
  example: 'example',
};

interface Ann {
  id: string;
  type: string;
  title?: string;
  content?: string;
  range?: { startLine: number; endLine: number };
  [k: string]: unknown;
}

function findLeanPath(proofDir: string, dataDir: string): string | null {
  const metaPath = path.join(dataDir, 'meta.json');
  if (!fs.existsSync(metaPath)) return null;
  let meta: { meta?: { proofRepoPath?: string } };
  try {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
  } catch {
    return null;
  }
  let leanPath: string | null = null;
  if (meta.meta?.proofRepoPath) {
    leanPath = path.join(__dirname, '../../proofs', meta.meta.proofRepoPath);
  }
  if (!leanPath || !fs.existsSync(leanPath)) {
    const pascalName = proofDir
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join('');
    const candidate = path.join(PROOFS_SOURCE_DIR, `${pascalName}.lean`);
    if (fs.existsSync(candidate)) leanPath = candidate;
  }
  if (!leanPath || !fs.existsSync(leanPath)) {
    const local = path.join(dataDir, 'source.lean');
    if (fs.existsSync(local)) leanPath = local;
  }
  return leanPath && fs.existsSync(leanPath) ? leanPath : null;
}

function effectiveStart(c: LeanConstruct): number {
  return c.docCommentStart ?? c.startLine;
}

function kindCompatible(annType: string, c: LeanConstruct): boolean {
  if (c.type !== 'declaration') return !(annType in KIND_COMPAT);
  const allowed = KIND_COMPAT[annType];
  return allowed ? allowed.includes(c.kind ?? '') : true;
}

/** Why the validator would reject this annotation, or null if it is fine. */
function misalignment(parsed: ParsedLeanFile, ann: Ann): string | null {
  if (!ann.range) return null;
  const { startLine, endLine } = ann.range;
  if (startLine < 1 || endLine > parsed.lines.length) return 'out-of-bounds';
  const c = findConstructAtLine(parsed, startLine);
  if (!c) return 'no-construct';
  if (c.type === 'declaration' && !kindCompatible(ann.type, c)) return 'type-mismatch';
  return null;
}

/** Identifiers the annotation names: title tokens plus backticked spans in content. */
function namedIdentifiers(ann: Ann): string[] {
  const out = new Set<string>();
  const grab = (s: string) => {
    for (const m of s.matchAll(/[A-Za-z_][A-Za-z0-9_'.]*/g)) {
      const tok = m[0];
      if (tok.length < 3) continue;
      out.add(tok);
      const last = tok.split('.').pop();
      if (last && last.length >= 3) out.add(last);
    }
  };
  if (ann.title) grab(ann.title);
  if (ann.content) {
    for (const m of ann.content.slice(0, 600).matchAll(/`([^`\n]{2,80})`/g)) grab(m[1]);
  }
  return [...out];
}

function byName(parsed: ParsedLeanFile, ann: Ann, oldStart: number): LeanConstruct | null {
  const names = new Set(namedIdentifiers(ann));
  const hits = parsed.constructs.filter(
    (c) => c.type === 'declaration' && c.name && names.has(c.name) && !c.name.startsWith('example_')
  );
  if (hits.length === 0) return null;
  hits.sort((a, b) => Math.abs(effectiveStart(a) - oldStart) - Math.abs(effectiveStart(b) - oldStart));
  return hits[0];
}

function byProximity(
  parsed: ParsedLeanFile,
  ann: Ann,
  oldStart: number,
  claimed: Set<number>
): LeanConstruct | null {
  const anchor = Math.min(Math.max(oldStart, 1), parsed.lines.length);
  const cands = parsed.constructs
    .filter((c) => kindCompatible(ann.type, c))
    .filter((c) => c.type === 'declaration' || !(ann.type in KIND_COMPAT))
    .map((c) => ({ c, d: Math.abs(effectiveStart(c) - anchor) }))
    .filter((x) => x.d <= WINDOW)
    .sort((a, b) => a.d - b.d);
  if (cands.length === 0) return null;
  // Prefer a construct no other annotation in this file already claims.
  const free = cands.filter((x) => !claimed.has(effectiveStart(x.c)));
  const pool = free.length > 0 ? free : cands;
  if (pool.length > 1 && pool[0].d === pool[1].d) return null; // ambiguous tie
  return pool[0].c;
}

interface Edit {
  index: number;
  id: string;
  oldStart: number;
  oldEnd: number;
  newStart: number;
  newEnd: number;
  oldType: string;
  newType: string;
}

/**
 * Byte spans of each top-level array element in the original JSON text, in
 * order, found by a brace scan that respects strings and escapes. Lets edits
 * be applied by array index, independent of key order or id text.
 */
function topLevelObjectSpans(text: string): Array<[number, number]> {
  const spans: Array<[number, number]> = [];
  let depth = 0;
  let inStr = false;
  let esc = false;
  let start = -1;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inStr) {
      if (esc) esc = false;
      else if (ch === '\\') esc = true;
      else if (ch === '"') inStr = false;
      continue;
    }
    if (ch === '"') { inStr = true; continue; }
    if (ch === '{') { if (depth === 1) start = i; depth++; }
    else if (ch === '}') { depth--; if (depth === 1 && start >= 0) { spans.push([start, i + 1]); start = -1; } }
    else if (ch === '[' || ch === ']') { depth += ch === '[' ? 1 : -1; }
  }
  return spans;
}

/**
 * Patch the original file text in place so formatting (compact ranges, inline
 * arrays, key order) survives: only the range numbers and, when corrected, the
 * type string of each edited annotation change. Edits are located by the
 * annotation's array index. Returns null (caller re-serializes) if the scan
 * does not line up with the parsed array.
 */
function patchText(original: string, edits: Edit[], total: number): string | null {
  const spans = topLevelObjectSpans(original);
  if (spans.length !== total) return null;
  let text = original;
  // Apply from the last edit backwards so earlier offsets stay valid.
  for (const e of [...edits].sort((a, b) => b.index - a.index)) {
    const [s0, s1] = spans[e.index];
    let seg = text.slice(s0, s1);
    if (!seg.includes(`"${e.id}"`)) return null;
    // Scope the numeric edits to the annotation's own `range` object so a
    // nested field that also happens to be called startLine is never touched.
    const rangeRe = /("range"\s*:\s*\{)([^}]*)(\})/;
    const rm = seg.match(rangeRe);
    if (!rm) return null;
    const inner = rm[2]
      .replace(/("startLine"\s*:\s*)\d+/, `$1${e.newStart}`)
      .replace(/("endLine"\s*:\s*)\d+/, `$1${e.newEnd}`);
    if (inner === rm[2] && (e.newStart !== e.oldStart || e.newEnd !== e.oldEnd)) return null;
    seg = seg.replace(rangeRe, `$1${inner.replace(/\$/g, '$$$$')}$3`);
    if (e.newType !== e.oldType) {
      const rt = seg.replace(new RegExp(`("type"\\s*:\\s*")${e.oldType}(")`), `$1${e.newType}$2`);
      if (rt === seg) return null;
      seg = rt;
    }
    text = text.slice(0, s0) + seg + text.slice(s1);
  }
  return text;
}

interface Stats {
  proofs: number;
  skippedAnchorBased: number;
  noLean: number;
  annotations: number;
  alreadyAligned: number;
  fixedByName: number;
  fixedByProximity: number;
  fixedByContainment: number;
  typeCorrected: number;
  unresolved: number;
  filesChanged: number;
}
const stats: Stats = {
  proofs: 0, skippedAnchorBased: 0, noLean: 0, annotations: 0, alreadyAligned: 0,
  fixedByName: 0, fixedByProximity: 0, fixedByContainment: 0, typeCorrected: 0, unresolved: 0, filesChanged: 0,
};
const unresolvedList: string[] = [];

for (const proofDir of fs.readdirSync(PROOFS_DATA_DIR).sort()) {
  if (PROOF_FILTER && proofDir !== PROOF_FILTER) continue;
  const dataDir = path.join(PROOFS_DATA_DIR, proofDir);
  if (!fs.statSync(dataDir).isDirectory()) continue;
  const annPath = path.join(dataDir, 'annotations.json');
  if (!fs.existsSync(annPath)) continue;
  if (fs.existsSync(path.join(dataDir, 'annotations.source.json'))) {
    stats.skippedAnchorBased++;
    continue;
  }
  let anns: unknown;
  try {
    anns = JSON.parse(fs.readFileSync(annPath, 'utf-8'));
  } catch {
    continue;
  }
  if (!Array.isArray(anns) || anns.length === 0) continue;
  const leanPath = findLeanPath(proofDir, dataDir);
  if (!leanPath) {
    stats.noLean++;
    continue;
  }
  stats.proofs++;
  const parsed = parseLeanFile(fs.readFileSync(leanPath, 'utf-8'), leanPath);

  // Construct starts already correctly claimed by aligned annotations.
  const claimed = new Set<number>();
  for (const ann of anns as Ann[]) {
    if (ann.range && misalignment(parsed, ann) === null) {
      const c = findConstructAtLine(parsed, ann.range.startLine);
      if (c) claimed.add(effectiveStart(c));
    }
  }

  let changed = false;
  const edits: Edit[] = [];
  for (const [index, ann] of (anns as Ann[]).entries()) {
    if (!ann.range) continue;
    stats.annotations++;
    const why = misalignment(parsed, ann);
    if (!why) {
      stats.alreadyAligned++;
      continue;
    }
    const oldStart = ann.range.startLine;
    const oldEnd = ann.range.endLine;
    // Rule order: name (strongest) → containment (preserves the author's span)
    // → proximity (last resort, nearest compatible construct within WINDOW).
    let target = byName(parsed, ann, oldStart);
    let how: 'name' | 'proximity' | 'containment' | null = target ? 'name' : null;
    if (!target && why !== 'out-of-bounds' && oldEnd > oldStart) {
      // A narrative annotation whose span still covers real constructs (its
      // start merely drifted onto a `--` comment or blank line the parser does
      // not model) snaps its start to the first construct inside that span.
      const inside = parsed.constructs
        .filter((c) => kindCompatible(ann.type, c))
        .filter((c) => effectiveStart(c) >= oldStart && effectiveStart(c) <= oldEnd)
        .sort((a, b) => effectiveStart(a) - effectiveStart(b));
      if (inside.length > 0) {
        target = inside[0];
        how = 'containment';
      }
    }
    if (!target) {
      target = byProximity(parsed, ann, oldStart, claimed);
      how = target ? 'proximity' : null;
    }
    if (!target || !how) {
      stats.unresolved++;
      unresolvedList.push(`${proofDir}/${ann.id} (${why} at ${oldStart}-${oldEnd})`);
      if (VERBOSE) console.log(`  ✗ ${proofDir}/${ann.id}: ${why} at ${oldStart}-${oldEnd} — unresolved`);
      continue;
    }
    const newStart = effectiveStart(target);
    const nLines = parsed.lines.length;
    const multiLine = oldEnd - oldStart >= 3;
    const newEnd = how === 'containment'
      ? (target.type === 'declaration' ? Math.max(oldEnd, target.endLine) : oldEnd)
      : multiLine
        ? Math.min(nLines, Math.max(target.endLine, oldEnd + (newStart - oldStart)))
        : target.endLine;
    let typeNote = '';
    const oldType = ann.type;
    if (target.type === 'declaration' && !kindCompatible(ann.type, target) && ann.type in KIND_COMPAT) {
      const newType = KIND_TO_TYPE[target.kind ?? ''];
      if (newType && newType !== ann.type) {
        typeNote = ` type ${ann.type}→${newType}`;
        ann.type = newType;
        stats.typeCorrected++;
      }
    }
    ann.range.startLine = newStart;
    ann.range.endLine = newEnd;
    edits.push({ index, id: ann.id, oldStart, oldEnd, newStart, newEnd, oldType, newType: ann.type });
    claimed.add(newStart);
    changed = true;
    if (how === 'name') stats.fixedByName++;
    else if (how === 'proximity') stats.fixedByProximity++;
    else stats.fixedByContainment++;
    if (VERBOSE) {
      const label = target.type === 'declaration' ? `${target.kind} ${target.name}` : target.type;
      console.log(`  ✓ ${proofDir}/${ann.id}: ${oldStart}-${oldEnd} → ${newStart}-${newEnd} (${how}: ${label})${typeNote}`);
    }
  }

  if (changed) {
    stats.filesChanged++;
    if (APPLY) {
      const original = fs.readFileSync(annPath, 'utf-8');
      const patched = patchText(original, edits, (anns as Ann[]).length);
      fs.writeFileSync(annPath, patched ?? JSON.stringify(anns, null, 2) + '\n');
      if (!patched) console.warn(`  ! ${proofDir}: textual patch failed, re-serialized`);
    }
  }
}

console.log(`\nrealign-lines ${APPLY ? '(APPLIED)' : '(dry run)'}`);
console.log(`  proofs scanned:        ${stats.proofs}  (anchor-based skipped: ${stats.skippedAnchorBased}, no Lean source: ${stats.noLean})`);
console.log(`  annotations checked:   ${stats.annotations}`);
console.log(`  already aligned:       ${stats.alreadyAligned}`);
console.log(`  fixed by name:         ${stats.fixedByName}`);
console.log(`  fixed by proximity:    ${stats.fixedByProximity}`);
console.log(`  fixed by containment:  ${stats.fixedByContainment}`);
console.log(`  type corrected:        ${stats.typeCorrected}`);
console.log(`  unresolved:            ${stats.unresolved}`);
console.log(`  files ${APPLY ? 'written' : 'that would change'}: ${stats.filesChanged}`);
if (unresolvedList.length > 0 && !VERBOSE) {
  console.log(`\n  first unresolved (use --verbose for all):`);
  for (const u of unresolvedList.slice(0, 15)) console.log(`    ${u}`);
}
process.exit(0);
