#!/usr/bin/env python3
"""
Reproducible verification for pell-equation-oq-05:
"Norm Equations in Number Fields of Degree > 2".

Goal of this script (build-free, Docker-independent ORIENT artifact):
independently RE-DERIVE, from first principles, the structural facts that the
higher-degree analogue of Pell's equation rests on, and check each numerically.

Nothing here is plugged in from a reference table:
  * field signatures (r1, r2) are computed by actually counting real/complex
    roots of the minimal polynomial;
  * the unit rank r1 + r2 - 1 is recomputed and the identity r1 + 2 r2 = n is
    checked;
  * the cubic norm form N(a + b t + c t^2) is derived as the determinant of the
    multiplication-by-xi matrix on the power basis (the *definition* of the
    field norm), NOT copied from a formula;
  * fundamental units are exhibited and verified to multiply to 1 in O_K;
  * the "Pell chain" of norm-1 solutions is generated by powers and each power's
    norm is recomputed.

Run:  python3 verify_norm_equations.py
Requires: sympy (tested with 1.14.0)
"""

import sympy as sp


# ---------------------------------------------------------------------------
# 1. Signatures and unit rank, derived by counting roots of the min poly.
# ---------------------------------------------------------------------------
def signature(poly_expr, x):
    """Return (n, r1, r2) for a monic irreducible Q-polynomial.

    r1 = number of real embeddings  = number of real roots
    r2 = number of conjugate pairs of complex embeddings
    Derived directly from the roots, not from a table.
    """
    poly = sp.Poly(poly_expr, x)
    n = poly.degree()
    r1 = len(sp.real_roots(poly))           # counts real roots (with no rep.)
    # irreducible over Q => squarefree => distinct roots, so:
    r2 = (n - r1) // 2
    return n, r1, r2


def unit_rank(r1, r2):
    """Dirichlet unit theorem: rank O_K^x = r1 + r2 - 1."""
    return r1 + r2 - 1


x = sp.symbols("x")

cases = {
    "Q(sqrt 2)      [real quadratic, the classical Pell field]": x**3 * 0 + x**2 - 2,
    "Q(sqrt -5)     [imaginary quadratic]": x**2 + 5,
    "Q(cbrt 2)      [pure cubic, mixed signature]": x**3 - 2,
    "Q, x^3-3x-1    [totally real cyclic cubic, conductor 9]": x**3 - 3*x - 1,
    "Q(zeta 5)      [cyclotomic quartic, totally complex]": x**4 + x**3 + x**2 + x + 1,
}

print("=" * 72)
print("1. SIGNATURES AND UNIT RANK  (rank = r1 + r2 - 1)")
print("=" * 72)
print(f"{'field':<48}{'(n,r1,r2)':>12}{'rank':>6}")
rank_table = {}
for name, p in cases.items():
    n, r1, r2 = signature(p, x)
    assert r1 + 2 * r2 == n, f"degree identity r1+2r2=n failed for {name}"
    rk = unit_rank(r1, r2)
    rank_table[name] = (n, r1, r2, rk)
    print(f"{name:<48}{f'({n},{r1},{r2})':>12}{rk:>6}")

# Sanity: Pell field has rank 1 (cyclic unit group => single fundamental unit).
assert rank_table["Q(sqrt 2)      [real quadratic, the classical Pell field]"][3] == 1
# Pure cubic Q(cbrt 2): (n,r1,r2)=(3,1,1) => rank 1 as well, BUT it now has a
# complex place; still cyclic-rank but structurally different from quadratic.
assert rank_table["Q(cbrt 2)      [pure cubic, mixed signature]"][:3] == (3, 1, 1)
assert rank_table["Q(cbrt 2)      [pure cubic, mixed signature]"][3] == 1
# Totally real cubic: rank 2 => genuinely TWO independent fundamental units.
assert rank_table["Q, x^3-3x-1    [totally real cyclic cubic, conductor 9]"][3] == 2
# Cyclotomic Q(zeta5): (4,0,2) => rank 1.
assert rank_table["Q(zeta 5)      [cyclotomic quartic, totally complex]"][:3] == (4, 0, 2)
print("\n  [check] r1 + 2 r2 = n for every field above.")
print("  [check] Pell field Q(sqrt2): rank 1  (recovers the classical cyclic chain).")
print("  [check] Q(cbrt2): rank 1 but signature (1,1) -- a complex place appears.")
print("  [check] x^3-3x-1 totally real: rank 2  => SEVERAL fundamental units.")


# ---------------------------------------------------------------------------
# 2. The cubic norm form of Q(cbrt 2), derived as a determinant.
# ---------------------------------------------------------------------------
print()
print("=" * 72)
print("2. NORM FORM OF Q(cbrt 2) AS det(mult-by-xi)  (first principles)")
print("=" * 72)

a, b, c = sp.symbols("a b c", integer=True)
# Multiplication by xi = a + b t + c t^2 on the power basis {1, t, t^2}, t^3 = 2.
#   xi*1   = a       + b t   + c t^2
#   xi*t   = 2c      + a t   + b t^2     (since c t^3 = 2c)
#   xi*t^2 = 2b      + 2c t  + a t^2     (b t^3 = 2b, c t^4 = 2c t)
M = sp.Matrix([
    [a, 2*c, 2*b],
    [b, a,   2*c],
    [c, b,   a],
])
N = sp.expand(M.det())
print("  N(a + b t + c t^2) =", N)
expected = a**3 + 2*b**3 + 4*c**3 - 6*a*b*c
assert sp.simplify(N - expected) == 0, "norm-form determinant mismatch"
print("  [check] equals a^3 + 2 b^3 + 4 c^3 - 6 a b c   (derived, not assumed).")


def norm_cbrt2(av, bv, cv):
    """Integer norm of av + bv*t + cv*t^2 in Q(cbrt2), via the same matrix."""
    return int(M.det().subs({a: av, b: bv, c: cv}))


# Multiplication in the ring, reduced mod t^3 - 2, returned as (a,b,c).
def mul_cbrt2(u, v):
    au, bu, cu = u
    av, bv, cv = v
    # (au + bu t + cu t^2)(av + bv t + cv t^2), reduce t^3->2, t^4->2t
    a0 = au*av + 2*(bu*cv + cu*bv)
    a1 = au*bv + bu*av + 2*cu*cv
    a2 = au*cv + bu*bv + cu*av
    return (a0, a1, a2)


# ---------------------------------------------------------------------------
# 3. Fundamental unit of Z[cbrt 2] and the higher-degree Pell chain.
# ---------------------------------------------------------------------------
print()
print("=" * 72)
print("3. FUNDAMENTAL UNIT OF Z[cbrt 2] AND THE NORM-1 CHAIN")
print("=" * 72)

u = (-1, 1, 0)      # t - 1
uinv = (1, 1, 1)    # t^2 + t + 1
print("  candidate fundamental unit  u = t - 1        , N(u)   =", norm_cbrt2(*u))
print("  candidate inverse          u'= t^2 + t + 1   , N(u')  =", norm_cbrt2(*uinv))
assert norm_cbrt2(*u) == 1
assert norm_cbrt2(*uinv) == 1
# Verify u * u' = 1 in O_K  (so u' = u^{-1}; the two norm-1 elements are one unit)
prod = mul_cbrt2(u, uinv)
print("  u * u' (in O_K) =", prod, " == (1,0,0)?", prod == (1, 0, 0))
assert prod == (1, 0, 0), "(t-1)(t^2+t+1) should be 1"
print("  [check] (t-1)(t^2+t+1) = t^3 - 1 = 1, so u^{-1} = t^2+t+1.")

# The higher-degree analogue of the Pell chain: powers of the fundamental unit.
print("\n  Pell-analogue chain  u^k = (t-1)^k  (every term a norm-1 solution):")
power = (1, 0, 0)
for k in range(1, 7):
    power = mul_cbrt2(power, u)
    nk = norm_cbrt2(*power)
    print(f"    u^{k} = {str(power):<22}  N = {nk}")
    assert nk == 1, f"u^{k} should have norm 1"
print("  [check] every power of the fundamental unit has norm 1")
print("          => infinitely many solutions of N(xi)=1, organized as <u> x {+-1}.")


# ---------------------------------------------------------------------------
# 4. Norm equation N(xi) = m: finiteness of solution classes mod units.
# ---------------------------------------------------------------------------
print()
print("=" * 72)
print("4. NORM EQUATION N(xi) = m  AND FINITENESS OF CLASSES")
print("=" * 72)

# t itself solves N(xi) = 2.
print("  N(t) =", norm_cbrt2(0, 1, 0), " => xi = t solves N(xi) = 2.")
assert norm_cbrt2(0, 1, 0) == 2
# Multiplying by units gives the whole solution coset; show a few representatives.
print("  t * u^k are further N=2 solutions (same class mod units):")
rep = (0, 1, 0)
for k in range(0, 4):
    print(f"    t * u^{k} = {str(rep):<22}  N = {norm_cbrt2(*rep)}")
    assert norm_cbrt2(*rep) == 2
    rep = mul_cbrt2(rep, u)
print("  [check] all share norm 2 -> one class mod units (Z[cbrt2] has class number 1).")
print("  General principle: solutions of N(xi)=m correspond to ideals of norm |m|,")
print("  finite in number, each an O_K^x-coset -> FINITELY MANY classes (S-unit thm).")


# ---------------------------------------------------------------------------
# 5. Recover the classical Pell equation as the rank-1 real-quadratic case.
# ---------------------------------------------------------------------------
print()
print("=" * 72)
print("5. SANITY: CLASSICAL PELL x^2 - 2 y^2 = 1 AS THE QUADRATIC SPECIAL CASE")
print("=" * 72)

# Q(sqrt2): N(p + q sqrt2) = p^2 - 2 q^2 (det of mult matrix), fundamental unit 1+sqrt2.
p, q = sp.symbols("p q", integer=True)
Mq = sp.Matrix([[p, 2*q], [q, p]])
Nq = sp.expand(Mq.det())
print("  N(p + q sqrt2) =", Nq, " (det of mult-by matrix)")
assert sp.simplify(Nq - (p**2 - 2*q**2)) == 0
# fundamental solution of x^2-2y^2=1 is (3,2); chain via (1+sqrt2)^k after squaring.
sols = [(3, 2)]
for _ in range(3):
    px, py = sols[-1]
    sols.append((3*px + 4*py, 2*px + 3*py))   # Brahmagupta composition with (3,2)
for (px, py) in sols:
    val = px**2 - 2*py**2
    print(f"    (x,y)=({px},{py})  x^2-2y^2 = {val}")
    assert val == 1
print("  [check] rank-1 cyclic chain reproduced; this IS pell-equation (parent).")

print()
print("=" * 72)
print("ALL CHECKS PASSED.")
print("=" * 72)
