import Proofs.Erdos85OneTwentyThreeResidualTerminal

#print axioms Erdos85.degree_sixteen_orderTwelve_diagonalQuotient_ne_three
#print axioms Erdos85.degree_sixteen_zeroLayer_false_of_orderTwelve_allA_row_unconditional
#print axioms Erdos85.degree_sixteen_zeroLayer_false_of_orderTwelve_allA_row
#print axioms Erdos85.degree_sixteen_zeroLayer_false_of_orderTwelve_allA_row_diag_zero
#print axioms Erdos85.degree_sixteen_zeroLayer_used_component_row_after_contact_excess
