/-
  TURNKEY DRAFT — Step 3 `sylow_p_is_pcycle` of the Galois-direction sub-OQ.

  Authored 2026-06-16 (researcher-2). Self-contained (Mathlib-only imports) so it
  can be verified in isolation: `cp` into `proofs/Proofs/` and run
  `./proofs/scripts/docker-build.sh Proofs.Step3SylowPIsPCycleDraft` from a worktree
  with a healthy `.lake`. (researcher-2's worktree `.lake` is a self-referential
  symlink — `proofs/.lake -> .../proofs/.lake` — so the build aborts at the Mathlib
  clone with `git exited 128`; Aristotle MCP was also 404 this session. Neither
  backend was usable, so this proof is NOT yet machine-checked.)

  Once verified, transcribe the proof body verbatim into
  `proofs/Proofs/AbelRuffiniGaloisExtensionsOQ06GaloisDirection.lean`'s
  `sylow_p_is_pcycle` (replace its `sorry`; also rename the unused `_hPrim`
  hypothesis to `hPrim` — the proof uses primitivity for `p ∣ |H|`).

  EVERY bearer below was name-and-line checked against the lake-pinned Mathlib
  v4.26.0 sibling checkout (SHA 2df2f0150c275ad53cb3c90f7c98ec15a56a1a67):
    - MulAction.IsPreprimitive extends IsPretransitive          (Primitive.lean:90)
    - MulAction.orbit_eq_univ                                   (Basic.lean:71)
    - MulAction.orbitEquivQuotientStabilizer                    (Quotient.lean:165)
    - Equiv.Set.univ, Equiv.setCongr                            (Logic/Equiv/Set.lean:166)
    - Subgroup.index_eq_card / index_dvd_card                   (Index.lean:390/398)
    - Nat.card_zmod                                             (SetTheory/Cardinal/Finite.lean:248)
    - Subgroup.card_subgroup_dvd_card                           (Coset/Card.lean:69)
    - Fintype.card_perm, ZMod.card
    - Nat.Prime.dvd_factorial (takes Nat.Prime p)              (Nat/Prime/Factorial.lean:23)
    - Nat.Prime.pow_dvd_iff_le_factorization / factorization_pos_of_dvd (Factorization/Basic.lean)
    - Sylow.card_eq_multiplicity                                (Sylow.lean:702)
    - isCyclic_of_prime_card, IsCyclic.exists_generator,
      orderOf_eq_card_of_forall_mem_zpowers (all Nat.card)      (Cyclic.lean:185/217)
    - Equiv.Perm.isCycle_of_prime_order''                       (Perm/Cycle/Type.lean:412)
    - Equiv.Perm.IsCycle.orderOf                                (Perm/Cycle/Basic.lean:363)

  The `Nat.card P = p` argument mirrors the already-Docker-verified Step 5
  (`H_le_normalizer`) in the registered file (researcher-4, 2026-06-16, 1900 jobs),
  which uses the same `Sylow.card_eq_multiplicity` + `factorization_pos_of_dvd`
  antisymmetry — so the only genuinely new machinery here is the upper bound
  `v_p(|H|) ≤ 1` (via `|H| ∣ p!` and `¬ p² ∣ p!`) and the orbit/stabilizer
  `p ∣ |H|`.
-/

import Mathlib.Tactic
import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.GroupTheory.GroupAction.Primitive
import Mathlib.GroupTheory.Solvable

namespace Step3SylowPIsPCycleDraft

variable {p : ℕ} [Fact p.Prime]

/-- **Step 3 (p-cycle structure).** The Sylow-p subgroup `P` of a primitive
    solvable `H ≤ S_p` is generated by a `p`-cycle in `S_p`. -/
theorem sylow_p_is_pcycle
    (H : Subgroup (Equiv.Perm (ZMod p)))
    (hPrim : MulAction.IsPreprimitive H (ZMod p))
    (_hSolv : IsSolvable H)
    (P : Sylow p H) :
    ∃ σ : Equiv.Perm (ZMod p), σ.IsCycle ∧ σ.support.card = p ∧
      ∀ g : P, (H.subtype.comp (P : Subgroup H).subtype) g ∈
        Subgroup.zpowers σ := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).pos.ne'⟩
  have hppos : 0 < p := Fact.out.pos
  -- The composition ι : ↥P → S_p, injective.
  set ι : (P : Subgroup H) →* Equiv.Perm (ZMod p) :=
    H.subtype.comp (P : Subgroup H).subtype with hι_def
  have hι_inj : Function.Injective ι := by
    rw [hι_def, MonoidHom.coe_comp]
    exact (Subgroup.subtype_injective H).comp (Subgroup.subtype_injective _)
  -- Step A: p ∣ |H| from primitivity (transitive action of degree p).
  have hpH : p ∣ Nat.card H := by
    haveI : MulAction.IsPretransitive (H : Subgroup (Equiv.Perm (ZMod p))) (ZMod p) :=
      hPrim.toIsPretransitive
    have ho : MulAction.orbit (H : Subgroup (Equiv.Perm (ZMod p))) (0 : ZMod p) = Set.univ :=
      MulAction.orbit_eq_univ _ 0
    have e : ZMod p ≃ H ⧸ MulAction.stabilizer (H : Subgroup (Equiv.Perm (ZMod p))) (0 : ZMod p) :=
      ((Equiv.Set.univ (ZMod p)).symm.trans (Equiv.setCongr ho.symm)).trans
        (MulAction.orbitEquivQuotientStabilizer _ (0 : ZMod p))
    have hidx :
        (MulAction.stabilizer (H : Subgroup (Equiv.Perm (ZMod p))) (0 : ZMod p)).index = p := by
      rw [Subgroup.index_eq_card, ← Nat.card_congr e, Nat.card_zmod]
    have hdvd := Subgroup.index_dvd_card
      (H := MulAction.stabilizer (H : Subgroup (Equiv.Perm (ZMod p))) (0 : ZMod p))
    rwa [hidx] at hdvd
  -- Step B: |H| ∣ p!, hence ¬ p² ∣ |H|, hence v_p(|H|) ≤ 1.
  have hH_dvd : Nat.card H ∣ p ! := by
    have h1 : Nat.card H ∣ Nat.card (Equiv.Perm (ZMod p)) := Subgroup.card_subgroup_dvd_card H
    rwa [Nat.card_eq_fintype_card (α := Equiv.Perm (ZMod p)), Fintype.card_perm,
      ZMod.card] at h1
  have hnp2 : ¬ p ^ 2 ∣ Nat.card H := by
    intro hc
    have hfac : p ! = p * (p - 1)! := by
      obtain ⟨q, hq⟩ := Nat.exists_eq_succ_of_ne_zero hppos.ne'
      rw [hq, Nat.factorial_succ, Nat.add_sub_cancel]
    have h2 : p ^ 2 ∣ p * (p - 1)! := by rw [← hfac]; exact hc.trans hH_dvd
    rw [pow_two] at h2
    have h3 : p ∣ (p - 1)! := (mul_dvd_mul_iff_left hppos.ne').mp h2
    have h4 : p ≤ p - 1 := (Nat.Prime.dvd_factorial Fact.out).mp h3
    omega
  -- Step C: |P| = p.
  have hcardP : Nat.card (P : Subgroup H) = p := by
    have hle : (Nat.card H).factorization p ≤ 1 := by
      by_contra h
      push_neg at h
      exact hnp2
        ((Nat.Prime.pow_dvd_iff_le_factorization Fact.out Nat.card_pos.ne').mpr h)
    have hge : 1 ≤ (Nat.card H).factorization p :=
      Nat.Prime.factorization_pos_of_dvd Fact.out Nat.card_pos.ne' hpH
    have hone : (Nat.card H).factorization p = 1 := le_antisymm hle hge
    rw [P.card_eq_multiplicity, hone, pow_one]
  -- Step D: P cyclic of prime order; take a generator g₀ and set σ := ι g₀.
  haveI : IsCyclic (P : Subgroup H) := isCyclic_of_prime_card hcardP
  obtain ⟨g₀, hg₀⟩ := IsCyclic.exists_generator (α := (P : Subgroup H))
  have hord : orderOf (ι g₀) = p := by
    rw [orderOf_injective ι hι_inj g₀, orderOf_eq_card_of_forall_mem_zpowers hg₀, hcardP]
  have hcyc : (ι g₀).IsCycle :=
    Equiv.Perm.isCycle_of_prime_order'' (by rw [ZMod.card]; exact Fact.out)
      (by rw [hord, ZMod.card])
  refine ⟨ι g₀, hcyc, ?_, ?_⟩
  · rw [← hcyc.orderOf, hord]
  · intro g
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hg₀ g)
    have hgn : ι g = (ι g₀) ^ n := by rw [← hn, map_zpow]
    rw [hgn]
    exact Subgroup.zpow_mem (Subgroup.mem_zpowers _) n

end Step3SylowPIsPCycleDraft
