#!/usr/bin/env python3
"""
verify_step1_sylow_unique.py
=============================

Verify-before-assert certification for **Step 1** (`sylow_p_unique`) of the
Galois-direction structure theorem in
`proofs/Proofs/AbelRuffiniGaloisExtensionsOQ06GaloisDirection.lean`:

    For a primitive solvable subgroup H <= S_p (p prime), the Sylow-p
    subgroup of H is unique  (=>  Subsingleton (Sylow p H)).

Step 1 is the single hardest remaining sorry (~70-110 LOC, per the file's
docstring); the sibling steps already have numerical certifications
(`verify_step4_normalizer.py`, `verify_step5_normalizer.py`,
`verify_capstone_embedding.py`). This script fills the Step-1 gap so its
Lean discharge can be pasted against a certified-sound argument.

Crucially, this script does NOT assume the classification (the very thing the
theorem proves, namely H <= AGL(1,p)).  It enumerates candidate subgroups
purely as `<sigma, tau>` for a fixed p-cycle `sigma` and every `tau in S_p`,
then *filters* to the transitive solvable ones and certifies the full bearer
chain of the Lean proof on each.  Because a transitive solvable group of prime
degree is metacyclic `C_p ⋊ C_d` (generated by the p-cycle and one element of
order d | (p-1)), this 2-generator sweep recovers every such subgroup -- a fact
the script independently corroborates by checking the *count* of distinct
transitive solvable subgroups equals the number of divisors of (p-1).

The argument certified (mirroring the file's "Bearer-complete sound route"):

  (1) A := last nontrivial term of the derived series of H (exists, IsSolvable)
      is abelian and normal in H.
  (2) A is transitive on the p points (minimal-normal/block argument).
  (3) A transitive on a p-set => p | |A|  (orbit-stabilizer).
  (4) v_p(|H|) = v_p(p!) = 1  (Legendre), and p | |A| | |H|, so the Sylow-p of
      A has order exactly p and is THE unique Sylow-p of H (n_p = 1).
  (5) |H| = p * m with m | (p-1), in particular m < p.

Sharpness: for a NON-solvable transitive group (A_p) the Sylow-p is NOT unique
(n_p > 1), so the solvability hypothesis is load-bearing -- also certified.

Pure standard library + sympy; deterministic; all asserts must pass.
Run:  python3 verify_step1_sylow_unique.py
(p = 7 enumerates all of S_7 = 5040 elements; allow ~15-30 s.)
"""

from __future__ import annotations

import time

from sympy.combinatorics import Permutation, PermutationGroup
from sympy.combinatorics.named_groups import AlternatingGroup, SymmetricGroup

PRIMES = [3, 5, 7]


def v_p(n: int, p: int) -> int:
    """p-adic valuation of n."""
    k = 0
    while n % p == 0:
        n //= p
        k += 1
    return k


def num_divisors(n: int) -> int:
    return sum(1 for d in range(1, n + 1) if n % d == 0)


def standard_pcycle(p: int) -> Permutation:
    """The p-cycle 0 -> 1 -> ... -> p-1 -> 0."""
    return Permutation([(i + 1) % p for i in range(p)])


def transitive_solvable_subgroups(p: int):
    """All distinct <sigma, tau> (sigma a fixed p-cycle, tau in S_p) that are
    transitive and solvable.  Returns list of (PermutationGroup, element_set)."""
    S = SymmetricGroup(p)
    sigma = standard_pcycle(p)
    seen: set[frozenset] = set()
    out = []
    for tau in S.generate():
        H = PermutationGroup([sigma, tau])
        sig = frozenset(tuple(g.array_form) for g in H.generate())
        if sig in seen:
            continue
        seen.add(sig)
        # is_transitive is a method; is_solvable is a property (sympy API quirk).
        if H.is_transitive() and H.is_solvable:
            out.append((H, sig))
    return out


def n_sylow_p(element_forms, p: int) -> int:
    """Number of Sylow-p subgroups = (#elements of order p) / (p - 1), valid
    when v_p(|H|) = 1 (each order-p subgroup contributes p-1 order-p elements
    and distinct Sylow-p's intersect trivially)."""
    nelp = sum(1 for f in element_forms if Permutation(list(f)).order() == p)
    return nelp // (p - 1)


def last_nontrivial_derived(H: PermutationGroup):
    """A := derivedSeries(d-1), d least with derivedSeries(d) = trivial."""
    ds = H.derived_series()
    nontriv = [d for d in ds if d.order() > 1]
    return nontriv[-1]


def certify_prime(p: int) -> None:
    t0 = time.time()
    groups = transitive_solvable_subgroups(p)

    # Completeness corroboration: one metacyclic C_p ⋊ C_d per divisor d|(p-1).
    expected = num_divisors(p - 1)
    assert len(groups) == expected, (
        f"p={p}: found {len(groups)} transitive-solvable subgroups, "
        f"expected tau(p-1)={expected}"
    )

    orders = []
    for H, sig in groups:
        o = H.order()
        orders.append(o)

        # (4a) v_p(|H|) = 1.
        assert v_p(o, p) == 1, f"p={p} |H|={o}: v_p != 1"

        # (5) |H| = p * m, m | (p-1), m < p.
        m = o // p
        assert o % p == 0 and (p - 1) % m == 0 and m < p, (
            f"p={p} |H|={o}: m={m} does not divide p-1 or m>=p"
        )

        # Unique Sylow-p (n_p = 1).
        assert n_sylow_p(sig, p) == 1, f"p={p} |H|={o}: Sylow-p NOT unique"

        # (1)-(3) the minimal-normal A from the derived series.
        A = last_nontrivial_derived(H)
        assert A.is_abelian, f"p={p} |H|={o}: A not abelian"
        assert A.is_transitive(), f"p={p} |H|={o}: A not transitive"
        assert A.order() % p == 0, f"p={p} |H|={o}: p does not divide |A|"
        # A is the order-p translation subgroup = the unique Sylow-p of H.
        assert A.order() == p, f"p={p} |H|={o}: |A|={A.order()} != p"

    print(
        f"[p={p}] {len(groups)} transitive-solvable subgroups "
        f"(= tau(p-1)={expected}); orders {sorted(orders)}"
    )
    print(
        f"        unique Sylow-p, v_p=1, |H|=p*m with m|(p-1), "
        f"A=⟨translations⟩ abelian+transitive order p  .... OK  ({time.time()-t0:.1f}s)"
    )


def certify_solvability_is_load_bearing() -> None:
    """A_p (transitive, NON-solvable) has n_p > 1 -- without solvability the
    unique-Sylow conclusion fails."""
    for p in (5, 7):
        Ap = AlternatingGroup(p)
        assert not Ap.is_solvable, f"A_{p} unexpectedly solvable"
        forms = [tuple(g.array_form) for g in Ap.generate()]
        np = n_sylow_p(forms, p)
        assert np > 1, f"A_{p}: expected n_p > 1, got {np}"
        print(f"[sharpness] A_{p}: non-solvable, n_p = {np} > 1 "
              f"(solvability hypothesis is load-bearing)")


def main() -> None:
    print("Certifying Step 1 (sylow_p_unique) of the Galois-direction theorem:")
    print("  primitive solvable H <= S_p  =>  unique Sylow-p subgroup")
    print()
    for p in PRIMES:
        certify_prime(p)
    print()
    certify_solvability_is_load_bearing()
    print()
    print("ALL STEP-1 CHECKS PASSED.")
    print("The Lean discharge (~70-110 LOC) follows the certified chain:")
    print("  derived-series A (abelian, normal) -> A transitive (block arg)")
    print("  -> p | |A| -> v_p(|H|)=1 -> |A_Sylow-p| = p = unique Sylow-p of H.")


if __name__ == "__main__":
    main()
